### ISSUE TITLE
SSL certificate vertification library

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#10]
We need certificate verification library

- [x] Library interface
- [x] Basic cert chain check (like SSL_get_verify_result but for STACKOF(X509*))
- [x] OSCP check (not OSCP stapling)
- [x] Chrome CRLSets
- [x] HPKP (including predefined keypins from Firefox or Chrome)
- [x] SHA1 deprecation check
- [x] Known bad roots check
- [x] Local root check

**Comment by sfionov** [comment]
added check "Handle blacklisted CAs (like StartCom) even if it is present in system CA store"

**Comment by TPS** [comment]
> added check "Handle blacklisted CAs (like StartCom) even if it is present in system CA store"

@sfionov @ameshkov Having https://github.com/AdguardTeam/AdguardForWindows/issues/1650 implemented for _Android_ is particularly important, as anything that uses Webview or apps that use data directly don't have benefit of CA blacklists!

**Comment by ameshkov** [comment]
@TPS blacklisted CAs are already checked by Adguard for Android. The thing is that we should implement it again in the new SSL verification library.

**Comment by TPS** [comment]
Huh, that's odd.  https://revoked.badssl.com/ (from https://github.com/AdguardTeam/AdguardForWindows/issues/1650) isn't blocked by ___any___ of my (Webview) browsers on my 7.1.1ß w/ the March '17 security patch! 😱

**Comment by ameshkov** [comment]
@TPS indeed, Chrome does not use OCSP.

**Comment by TPS** [comment]
Then how does
>blacklisted CAs are already checked by Adguard for Android

function?  Just internally to AG?  Or is that something AG can enforce downstream to the client (browser/app/OS/whatever)?

**Comment by ameshkov** [comment]
By blacklisted CA I mean WoSign and StartCom, which are revoked completely (not just a leaf certificate).

**Comment by TPS** [comment]
IC. Can this be extended to _full_ CRLs? I know supporting DNSSec is in process, also, so that's excellent.

**Comment by ameshkov** [comment]
Yeah, that's one of the points of the new library, to do it in a cross-platform manner.

However, it won't really help on Android, as Chrome itself does not check revocation status for some reason.

**Comment by TPS** [comment]
That's why I was hoping AG could fill that gap.  It seems like such an obvious neglect by the Chrome team.

**Comment by ameshkov** [comment]
It's just not we usually do. We should detect invalid connections so that browser could process them properly. Otherwise you'll never understand what was the problem.

**Comment by TPS** [comment]
Could it be handled like a malicious ad/link, but w/ appropriate message? E.g., custom full-page error w/ explanation & option to continue @ 1s own risk.  Many (desktop) browsers do implement this way _internally_; this'd do it _externally_.

**Comment by ameshkov** [comment]
> Could it be handled like a malicious ad/link, but w/ appropriate message?

Nope, in this case we will have to mask the fact, that certificate is invalid. The only thing we can do as a middle-box is to close connection abruptly.

**Comment by TPS** [comment]
Possibly make it optional, default off, & note it in filtering log? &/Or put up notification from AG itself?

**Comment by ameshkov** [comment]
Btw, related issues;
https://code.google.com/p/android/issues/detail?id=68643
https://bugs.chromium.org/p/chromium/issues/detail?id=362710

> Possibly make it optional, default off, & note it in filtering log? &/Or put up notification from AG itself?

We'll think about it. Android devs point out some valid points about revocation checking negative sides.

**Comment by TPS** [comment]
I've read all of that (2 to 3!) years ago, when published.  Unfortunately, better solutions are slow in being accepted, so working with what's available is what's possible now.  Also, since 3 years ago, Android _devices_ are _much_ more powerful, & probably can handle the performance hit from CRL far better than then.

I'm willing to run A/B tests for y'all.  Anyone else willing?

**Comment by ameshkov** [comment]
@sfionov I'd like to hear your thoughts on [OCSP Must-Staple](https://blog.mozilla.org/security/2015/11/23/improving-revocation-ocsp-must-staple-and-short-lived-certificates/)

**Comment by ameshkov** [comment]
Done:
https://github.com/AdguardTeam/VerificationLibrary
