### ISSUE TITLE
Requests "semi-hangs" after some time of using AdGuard

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#1000]
The issue happens not every time (at least for one user), but time to time after log using AdGuard. The problem goes away after reloading Adguard proxy server (stop and start). By the screenshot (in the NCloud) problem related to the process of establishing TLS handshake with `local.adguard.com` and around it. 
Logs will be soon in the NCloud

**Comment by ameshkov** [comment]
This must have something to do with the AV software installed on the user's computer. Please find out what the user has.

**Comment by ameshkov** [comment]
Seems to be fixed
