### ISSUE TITLE
$replace rules are not applied to some requests

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1001]
Steps to reproduce:
1. Add `||otvet.mail.ru/api/$replace=/baits/_baits/`
2. Open https://otvet.mail.ru

Expected behavior:
`baits` is replaced by `_baits`

Actual behavior:
replace is not applied

There are few different requests with the same URL. Look for this:
<details>

![image](https://user-images.githubusercontent.com/8361299/60711604-f385a200-9f1d-11e9-97bd-daa2442b47e4.png)
</details>

**Comment by Alex-302** [comment]
Another example:
https://www.csfd.cz/film/678155-frcime/prehled/
URL with ad config
`https://www.csfd.cz/film/2417132-tenkrat-na-zapade/videa/`
rule:
`||www.csfd.cz/film/*/videa/|$replace=/(<VAST[\s\S]*?>)[\s\S]*<\/VAST>/\$1<\/VAST>/`

**Comment by AdamWr** [comment]
One more example:
https://www.investigationdiscovery.com/tv-shows/jodie-marsh-gets-locked-up/full-episodes/jodie-marsh-gets-locked-up
Rules:
`||api.discovery.com/v*/streaming/video/$replace=/\{"ads":\{"breaks":[\s\S]*?"playURL":/{"playURL":/,domain=discovery.com|investigationdiscovery.com|sciencechannel.com|motortrend.com|tlc.com`

`||uplynk.com/*.m3u8$replace=/#UPLYNK-SEGMENT: \S*\\,ad\s[\s\S]+?((#UPLYNK-SEGMENT: \S+\\,segment)|(#EXT-X-ENDLIST))/\$1/,domain=abc7.com|abc7news.com|abc13.com|6abc.com|abc7chicago.com|discovery.com|fox.com|investigationdiscovery.com|sciencechannel.com|motortrend.com|tlc.com|abc7ny.com,important`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/60803548-c0d8e500-a17b-11e9-840b-9b3d6d8537ca.png)

</details>

**Comment by sxgunchenko** [comment]
fixed along with #999
