### ISSUE TITLE
CoreLibs v1.4.67 break twitch

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1002]
### Issue URL (Incorrect Blocking)
[https://www.twitch.tv/yassuo](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.twitch.tv%2Fyassuo)
### Comment
Username: @senpos
> I tried to disable filters one by one, but that did not help.
> --
> Информация ниже сгенерирована автоматически, не удаляйте ее.
> 
> Custom userscripts:
> https://userscripts.adtidy.org/beta/assistant/4.3/assistant.user.js
> https://userscripts.adtidy.org/beta/popup-blocker/2.5/popupblocker.user.js
> https://userscripts.adtidy.org/beta/adguard-extra/1.0/adguard-extra.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/92SWuT6.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/tCFqTZg.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 7.1.2838.0
Browser: | Chrome
AdGuard driver: | TDI
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing third-party cookies (180), Block WebRTC, Block Location API, Block Flash, Block Java, Hide your Referrer from third-parties (www.twitch.tv)
Filters: | AdGuard Russian,<br>AdGuard Annoyances,<br>AdGuard Base,<br>AdGuard Tracking Protection,<br>AdGuard Social Media

_Originally posted by @adguard-bot in https://github.com/AdguardTeam/AdguardFilters/issues/29035#issuecomment-508556885_

**Comment by ameshkov** [comment]
Confirmed

**Comment by sfionov** [comment]
core/pull-requests/1380
