### ISSUE TITLE
Move the https filtering configuration out of the main filtering configuration

### ISSUE THREAD

**Issue by sxgunchenko** [AdguardTeam/CoreLibs#1004]
For now, as a workaround, an application should perform fast reconfigurtion only if https configuration has not changed

**Comment by adbuker** [comment]
Also, it will be useful to move the `locale` field from the `AGProxyServerConfig` to `AGFilteringConfig`. First of all, it is more logical - `locale` affects only on the userscripts, which are in the `AGFilteringConfig`. Second, at this time changing the UI language leads to the restarting the proxy server, closing TCP connections etc. - it's a too expensive cost for such simple action
