### ISSUE TITLE
Exceptions rules don't work alongside with $replace rules

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1006]
### Steps to reproduce
1. Add these rules:
```
||example.org^$replace=/Example/Test/
example.org#%#alert("test");
example.org##body
@@||example.org^$elemhide,jsinject,important
```
2. Go to http://example.org/

### Expected behavior
Cosmetic and JS rules shouldn't be applied.

### Actual behavior
Cosmetic and JS rules are applied (there is an alert and website is blank).

Disabling `$replace` rule causes that exceptions rules work.

### Your environment
AdGuard for Windows 7.1.2838 (CL 1.4.67)

**Comment by ameshkov** [comment]
@AdamWr was it working properly in the stable release?

**Comment by AdamWr** [comment]
No, it wasn't.
It happens also with stable version (7.1.2817 (CL 1.4.32)).

**Comment by ameshkov** [comment]
It seems that I missed this case in the original spec:
https://github.com/AdguardTeam/CoreLibs/issues/45

Let's modify it a little:

* Document-level exception rules with `$content` or `$document` modifiers do disable `$replace` rules for requests matching them. Exception rules with $content or $document modifier.
* Other document-level exception rules (`$generichide`, `$elemhide` or `$jsinject` modifiers) are applied alongside the `$replace` rules. It means that you can modify the page's content with a `$replace` rule, and disable cosmetic rules there at the same time.

**Comment by AdamWr** [comment]
One more issue with exceptions.
It seems that `$jsinject,extension` disable also cosmetic rules.

Steps to reproduce
1. Add these rules:
```
example.org##body
@@||example.org^$jsinject,extension
```
2. Go to http://example.org/

Website should be blank and cosmetic filters shouldn't be disabled.
