### ISSUE TITLE
Allow using CSS-like selectors for HTML filtering

### ISSUE THREAD

**Issue by optomux** [AdguardTeam/CoreLibs#1008]
UBlock Origin can use CSS selector for HTML filtering.

Example:

> google.com##^div.bkWMgd:nth-child(2)
> index.hr##^.article-read-more-container:nth-child(3)

**Comment by Alex-302** [comment]
is not the same request?
https://github.com/AdguardTeam/CoreLibs/issues/94

**Comment by ameshkov** [comment]
Yeah you're right, marking as duplicate
