### ISSUE TITLE
Allow CSS filtering on the fly.

### ISSUE THREAD

**Issue by optomux** [AdguardTeam/CoreLibs#1009]
Provide syntax to allow filtering CSS files on the fly before it even enters the browser. 
Just like HTML is implemented. Should speed things up.

**Comment by ameshkov** [comment]
You should provide a detailed explanation of what you request: examples, proposed syntax, etc.

**Comment by optomux** [comment]
Currently Adguard for Windows modifies the CSS "after" the CSS file is downloaded from the server.
I know $replace modifier exists but this is sort of hit and miss. 

Hard to use that to delete/add/replace a specific CSS rule from a specific domain.
