### ISSUE TITLE
Strict blocking issue

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1012]
I'm not sure if it is a bug, but as I recall main frame shouldn't be blocked.
Anyway, even if it's not a bug than the rule shouldn't be marked as an `unknown`.
By the way, I have language set to English in AdGuard`s settings, but strict blocking notice is in Polish.

### Steps to reproduce

1. Enable `NoCoin Filter List` or add this rule to user filter:
`/^((?!(^https?):\/\/((www\.)?(blabla\.com))\/).)*$/$subdocument,domain=szukajka.tv`
2. Go here - http://szukajka.tv/
3. Click on logo
![image](https://user-images.githubusercontent.com/29142494/60825918-0eba1100-a1ad-11e9-88ac-50bae7abad72.png)

### Expected behavior

Website shouldn't be blocked.

### Actual behavior

Website is blocked and rule is marked as `unknown`.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/60822951-bb44c480-a1a6-11e9-9ce8-de59f7c0acfe.png)

</details>

### Your environment

* AdGuard for Windows 7.1.2484 (CL 1.4.78)

**Comment by ameshkov** [comment]
Weird, but I cannot reproduce this.

**Comment by AdamWr** [comment]
It was firstly reported here - https://github.com/AdguardTeam/AdguardFilters/issues/35861 and I can reproduce it also with stable build.

**Comment by ameshkov** [comment]
@AdamWr what about nightly build?

**Comment by ameshkov** [comment]
Okay, I've managed to repro with the NoCoin filter list:)

**Comment by ameshkov** [comment]
@sfionov here's why: https://uploads.adguard.com/up04_w3tbk_Windows_7_Enterprise_1.png

**Comment by sfionov** [comment]
core/pull-requests/1398
