### ISSUE TITLE
No AdGuard code on the page as it failed to detect HTML

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1013]
See here:
https://uploads.adguard.com/up04_zrn0e_view-sourcehttpskg-portal.rumoviesspidermanfarfromhomereviews5810.png

Problematic page:
https://kg-portal.ru/movies/spidermanfarfromhome/reviews/5810/

**Comment by sfionov** [comment]
I think we should do less strict detection if content type is text/html.

**Comment by vshlobinag** [comment]
core/pull-requests/1416
