### ISSUE TITLE
Some $replace rules work incorrectly

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1014]
It seems that with latest nightly build some `$replace` rules work incorrectly.

### Steps to reproduce
1. Enable AdGuard Base filter or add this rule to user filter:
```
||wp.pl^$replace=/(^(WP\.[\s\S]*?\.bodies)=WP\.[\s\S]*?\.bodies\|\|\{\};[\s\S]*\n)|((display:\\s\*)none(\\s\*!important)|((\.hostname;function .\(\)|=function\(\))\{return) .===.(\}))/\$4\$5\$6\$8/,script
```
2. Go to https://wiadomosci.wp.pl/

### Expected behavior
Website should works correctly.

### Actual behavior
Website is broken.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/60839355-446ef200-a1cd-11e9-9ba7-aad905e2a3be.png)

</details>

### Your environment
* AdGuard for Windows nightly 7.1.2484 (CL 1.4.78)

**Comment by Alex-302** [comment]
Another example
https://github.com/AdguardTeam/AdguardFilters/issues/36535
`||forums.overclockers.ru$replace=/(script.onerror = function\(\)\{)/\$1return;/,important`

**Comment by sfionov** [comment]
core/pull-requests/1394

**Comment by AdamWr** [comment]
It seems that some `$replace` rules still or again work incorrectly in latest nightly build 7.1.2874 (CL 1.4.127).
For example here - https://tech.wp.pl/szescioszpar-szary-zauwazony-u-wybrzezy-bahamow-naukowcy-to-podwodny-t-rex-6405675670165633a
This rule:
```
||wp.pl^$replace=/(^(WP\.[\s\S]*?\.bodies)=WP\.[\s\S]*?\.bodies\|\|\{\};[\s\S]*\n)|((display:\\s\*)none(\\s\*!important)|((\.hostname;function .\(\)|=function\(\))\{return) .===.(\}))/\$4\$5\$6\$8/,script
```

Website is broken
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/62368266-69385a00-b52c-11e9-8e24-a951cfb4367a.png)

</details>

but with stable build/Firefox extension it works fine.

**Comment by sxgunchenko** [comment]
core/pull-requests/1430
