### ISSUE TITLE
gp.se is broken

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1020]
It happens with nightly build, but works fine with stable release.

### Steps to reproduce

1. Go here - https://www.gp.se/

### Expected behavior

Website should works correctly.
### Actual behavior

Website is blank.

Adding `@@||gp.se^$elemhide,jsinject,extension` to user filter fixes it.

### Your environment

* AdGuard for Windows 7.1.2848 (CL 1.4.78)

**Comment by AdamWr** [comment]
One more broken website - https://www.purepc.pl/ (**mobile version only**)
Steps to reproduce:
1. Change to mobile view/open website on Android device
2. Go here - https://www.purepc.pl/

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/61186445-dcedf200-a665-11e9-9966-44f2b05dcd68.png)

</details>

It happens with AdGuard for Windows 7.1.2848 (CL 1.4.78) and with AdGuard for Android nightly 3.2.95 (CL1.4.79).

**Comment by sfionov** [comment]
Seems to be related to #999

**Comment by AdamWr** [comment]
One more example (mobile version only) - https://aflamyz.com/p/players/main_player.php?gdrive_ids=RkQ4amdWa2NQb1lUbUZlNGM5bEZER28yc1o1aTBTdVpWeEREWlJKMFMveVdudFhKMGZwNVVxVnR1TEhzb0FpV0FKSEpSYkR6dlN0RzhZeTAvbHpoQjFza1o5OEZWUnJaa0pKUVRYSjdJelJEVG5rakZmbCtGRkFES3RPQUp6ZG9vNWg0THdML0Z2L0dYZkZabmplTWdBPT0,&okru=1064336820874&go=6p7ziahglo5l&hls_id=5bb9e23395ab09542805496ad3c19681&img=https://www.movs4u.to/wp-content/uploads/2018/04/yo3VoCiQLepJQdGnjPUfdIwZmkS.jpg&img=https://www.movs4u.to/wp-content/uploads/2018/04/yo3VoCiQLepJQdGnjPUfdIwZmkS.jpg&backup_data=QlBJdmlYUUxEWW1Ua1BsWUppeE1BM1NqenNTSDlVc3hJeU03dHlqVXRZeTVHOGhidjBVMDJVM1J2U2F3YlJ0NjRMZkl3THlxendQTVgyQlFkT0dpSEZ2UFV0Slo4QWJGSUM3Q3BaTFk1Z052UFJ1SWVaR3J6OTFucldJQmlJYnpmcGtwRkwxZ1g0bEI5YTRBS0dxb3FhUU8rR3NGK25aK0dHams1eEEzdk1YRmZvYWp3bTloMFJBbjM0b2R1NkdVS1oyZGoyVDhDdnROL2dKaHRuQVFuRml3OWNlUit5WUllTFdUMnJHOXlUYVczQkYxMXQzZEt0alh6SlZFWlFKMkljcy9aRG9rMm4vSkZzR1JNcVlFSWNjY3F6WEZFMzJkUHFMKzZ4ZFZ6UkMxVVNQTURaUHFvYVZBVTYzNkpwKzgxWUliQkNkdUp4YkpIRGxBVnhNVFdkZjMwaUZTQ3doM291VXozZysyc2Ivbjg3UmFYVW16RlhtbHF5cFJXUHJ6eUFXVDZEeWx1cGE4eUVrRXJmY0NVdVhHR3FOTWxkVjI1TU5GNTJjSWoxblJmOUhYU1pYUDcwc3g4clUyVnNWK042MGJodzJOYUcwdVRQVnFVZVVVOHpHcnU1OElBaUd6T0dHbnc2dGZoVGVpeHprbWx6bCtPV2wwMDkydFMwYTdPMUN0Zm45QjlPMVczZlhSNjVUbE45ZGV4UGc5cmF6N1N6ei8zbFQvT3UrUGpaVnFHbVU0WmNUMVd5QVNTOUJ0

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/61583273-0a3f1200-ab36-11e9-9b54-f90a51389630.png)

</details>

**Comment by vshlobinag** [comment]
Cant reproduce

**Comment by Alex-302** [comment]
I can. Please try to clear site's data.

**Comment by AdamWr** [comment]
With the latest nightly build 7.1.2872(CL 1.4.120) everything works fine on my end.

**Comment by Xophile** [comment]
Same here!
