### ISSUE TITLE
talks.by проблемы с загрузкой форума

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/CoreLibs#1024]
Возникают сложности с открытием страниц форума крупного информационного ресурса, иной раз  требуется множество перезагрузок страницы, чтобы форум открылся. При этом при отключении защиты AdGuard форум мгновенно загружается без каких-либо технических проблем, но, естественно, с кучей рекламы.  https://talks.by/showthread.php?t=14417089

**Comment by ameshkov** [comment]
@zubrRB а попробуйте фильтры разные поотключать, может ли такое быть что это какой-то из них вызывает?

**Comment by zubrRB** [comment]
Протестировал с целиком отключенной функцией "Антибаннер": при перещелкивании страниц форум периодически не загружается, но хватает одной перезагрузки; при этом страницы загружаются несколько секунд, в то время как при полностью отключенной защите загрузка осуществляется за доли секунды.  Данная проблема проявилась именно после перехода на v7.

**Comment by ameshkov** [comment]
@sfionov 

Заголовок `Connection: close`
Ошибка: `net::ERR_CONNECTION_ABORTED`

Короче соединение рвется раньше времени. Таки нам надо больше паузу делать перед разрывом.

**Comment by sfionov** [comment]
The same problem as #1002, will be fixed in the next CL release.
