### ISSUE TITLE
`url(...)` style injections in cosmetic filters

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1026]
@ameshkov commented on [Sat Jul 13 2019](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1444)

See the original issue:
https://github.com/uBlockOrigin/uBlock-issues/issues/668

Prohibit `\` character in CSS injection rules

**Comment by vshlobinag** [comment]
core/pull-requests/1387
