### ISSUE TITLE
Listen port "0" must lead to auto selecting port, not to use "0" port

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#1028]
When the adapter passes `ListenPort` as `0`, it leads to the redirecting all the traffic to the port `0`, and accordingly to the refusing connection. Instead of such behavior port `0` must inform, that CL must select the port on its own.

**Comment by sfionov** [comment]
Seems to be a NFHandler problem. Since there is 100% working workaround for this, planning to 1.5.

**Comment by adbuker** [comment]
The workaround resolved in `core/pull-requests/1386`
