### ISSUE TITLE
Protocol TCP is passed instead of TLS in bypassed events

### ISSUE THREAD

**Issue by artemiv4nov** [AdguardTeam/CoreLibs#1029]
See for more details: https://github.com/AdguardTeam/AdguardForAndroid/issues/2912

**Comment by vshlobinag** [comment]
core/pull-requests/1392

**Comment by ameshkov** [comment]
The issue is still present.

### Steps to reproduce

1. Go to `cnn.com`
2. Open menu, open `US politics`
3. Inspect the filtering log

### Expected result

No `tcp://` requests from Chrome

### Actual result

* `tcp://code.jquery.com/`

**Comment by vshlobinag** [comment]
core/pull-requests/1410
