### ISSUE TITLE
"Self-destructing third-party cookies" considers Twitch auth cookie third-party

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1034]
### Steps to reproduce

1. Enable stealth mode + "self-destructing third-party cookies"
2. Sign in to Twitch
3. Check the "auth-token" cookie lifetime: 
    * https://uploads.adguard.com/up04_bxww0_Monosnap.png
    * https://uploads.adguard.com/up04_mpu3x_Cookies_in_use.png

### Expected result
Expires in 1 year

### Actual result
Expires in 3 hours

**Comment by Alex-302** [comment]
It seems the same issue: https://github.com/AdguardTeam/CoreLibs/issues/1034
