### ISSUE TITLE
Change LRU timeout cache resolution

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#1035]
AGLRUTimeoutCache has seconds resolution.
So we have to wait in seconds in tests e.g. sleep(BACKOFF_PERIOD_S + 1) in safebrowsing test. That decreases reliability of such tests.

1) Please increase resolution of AGLRUTimeoutCache.
Let timeout be in milliseconds in AGLRUTimeoutCache constructor.

2) Decrease sleep times to milliseconds(BACKOFF_PERIOD_S * 1000 + 20) in test to be more reliable. Or, better, make timeoutcache mockable. So we can tell to the mock that some amount of milliseconds was spent.

**Comment by vshlobinag** [comment]
core/pull-requests/1396
