### ISSUE TITLE
Websites detect stealth mode as if the browser is incognito mode

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/CoreLibs#1037]
Some websites (such as latimes.com) refuse to load articles in browser's Incognito Mode if user does not have a paid subscription to said websites.

Some ways of reproducing these issues include:
1. Opening the website in Incognito mode;
2. Opening the website w/Stealth Mode enabled (only for Android);
3. Opening the website using an in-app browser (for example, from Google News or from other apps like Reddit).

So far, I've been able to cause the "subscribe to view in incognito mode" screens to appear on an Android phone (Sony Xperia XZ1, Android 9.0, AdGuard 3.1.95n)

**Comment by ameshkov** [comment]
Bypassing is not an option, but we should figure how exactly they detect incognito mode.

**Comment by sxgunchenko** [comment]
Cannot reproduce with the current version (by the 2nd and 3rd ways).
latimes.com doesn't allow to read the articles on mobile and asks for subscription for now. But it doesn't say anything about the incognito mode.
Also tried other platforms. Result is the same, except it allows to read the articles.
