### ISSUE TITLE
$popup rule blocks iframe

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1039]
Actual behavior with Liste AR:
![image](https://user-images.githubusercontent.com/8361299/61464019-3b74e200-a97e-11e9-8e78-db34519a1c41.png)

Original issue:
https://github.com/AdguardTeam/AdguardFilters/issues/35459#issuecomment-512780152

Please disable this rule in Liste AR(added on our side) before checking:
`@@||drive.google.com/file/$domain=aflamyz.com`

**Comment by sfionov** [comment]
Duplicate of #682

**Comment by ameshkov** [comment]
No it's not

**Comment by ameshkov** [comment]
This one is about HTML parser

**Comment by vshlobinag** [comment]
core/pull-requests/1402/
