### ISSUE TITLE
dms.metlife.ru - site is not working

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1040]
@adguard-bot commented on [Tue Apr 16 2019](https://github.com/AdguardTeam/AdguardFilters/issues/32657)

### Issue URL (Incorrect Blocking)
[http://dms.metlife.ru](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fdms.metlife.ru)
### Comment
> Добрый день. 
> AdGuard на стационарном компьютере мешает входу в Личный кабинет сайта metlife.ru. При отключении службы Adguard Services доступ восстанавливается.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/xjViAzy.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/T9zylFP.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 6.4.1814.4903
Browser: | Chrome
AdGuard driver: | TDI
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing third-party cookies (30), Block Location API
Filters: | AdGuard Base
Other extensions used: | Проблема только в AdGuard.

**Comment by Alex-302** [comment]
It works when AdGuard is disabled only.

**Comment by ngorskikh** [comment]
Can't repro the original TOO_MANY_REDIRECTS. However, the site still doesn't work with tls filtration: strangely, http parser gets the same response twice in a row and errors out.
Disabling tls filtration for metlife.ru helps.
Could be a bug in SSLFilter?

**Comment by ameshkov** [comment]
@ngorskikh could you please try keeping HTTPS filtering, but simply bypass the traffic without attempting to parse HTTP? Maybe this is just a problematic web server?

**Comment by ngorskikh** [comment]
@ameshkov will check tomorrow, however, I've talked to the site with `openssl s_client` (sending the same request that our proxy sends), and it responds properly. Also, I got HTTPS filtering to work by using an outbound gomitmproxy in mitm mode :) (this way our proxy doesn't talk tls to the problematicsite directly, enforcing my suspicion that there problem is with our mitm logic)

**Comment by ngorskikh** [comment]
Alright, we've checked with https filtration, but bypassing the http parsing of the response: now the browser gets the pseudo-duplicated response: ERR_INVALID_CHUNKED_ENCODING :) Note `invalid`, not `incomplete` as when we give up and close the session.

**Comment by ngorskikh** [comment]
Update: I was able to reproduce the issue _without adguard_ on windows, with Edge and curl under msys2:
```
$ curl --version
curl 7.65.0 (x86_64-pc-msys) libcurl/7.65.0 OpenSSL/1.1.1b zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libpsl/0.20.2 (+libidn2/2.1.1) libssh2/1.8.2 nghttp2/1.36.0

$ curl https://dms.metlife.ru/pls/apex/f?p=208:LOGIN_DESKTOP::::::
<curl output omitted>
curl: (56) Illegal or missing hexadecimal sequence in chunked-encoding
```
I think the problem is that this server doesn't seem to work properly with OpenSSL. Suggestion: exclude `metlife.ru` from HTTPS filtering for now, re-test when we move to BoringSSL.
