### ISSUE TITLE
roblox.com - site is broken by JS injections

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1041]
@adguard-bot commented on [Sun Mar 31 2019](https://github.com/AdguardTeam/AdguardFilters/issues/31862)

### Issue URL (Social Widget)
[NSFW][https://www.roblox.com/my/account#!/info](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.roblox.com%2Fmy%2Faccount%23!%2Finfo)
### Comment
Username: @Yanssie
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/BNZ69Yy.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Ext
AdGuard version: | 3.0.11
Browser: | Chrome
Filters: | AdGuard Russian,<br>Filter unblocking search ads and self-promotion,<br>AdGuard Base,<br>Fanboy Anti-Facebook List
Other extensions used: | Yanssie

---

@Alex-302 commented on [Tue Apr 09 2019](https://github.com/AdguardTeam/AdguardFilters/issues/31862#issuecomment-481322086)

@Yanssie What do you mean? Chat in the corner?

---

@adguard-bot commented on [Tue Jun 11 2019](https://github.com/AdguardTeam/AdguardFilters/issues/31862#issuecomment-500847588)

### Issue URL (Annoyance)
[https://www.roblox.com/groups/4968679/LimitedEditionDev#!/about](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.roblox.com%2Fgroups%2F4968679%2FLimitedEditionDev%23!%2Fabout)
### Comment
Username: @jh
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/eKJHHEd.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Ext
AdGuard version: | 3.1.1
Browser: | YaBrowser
Stealth mode options: | Remove X-Client-Data header from HTTP requests, Self-destructing first-party cookies (), Self-destructing third-party cookies (), Block WebRTC, Hide your Referrer from third-parties
Filters: | Filter unblocking search ads and self-promotion,<br>EasyList Italy,<br>AdGuard French,<br>AdGuard Base,<br>AdGuard German,<br>AdGuard Spanish/Portuguese

---

@adguard-bot commented on [Fri Jun 14 2019](https://github.com/AdguardTeam/AdguardFilters/issues/31862#issuecomment-502169218)

### Issue URL (Incorrect Blocking)
[https://www.roblox.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.roblox.com%2F)
### Comment
> При включеном Adguard, страница в браузере пустая.
> --
> Информация ниже сгенерирована автоматически, не удаляйте ее.
> 
> Custom userscripts:
> https://greasyfork.org/scripts/4881-adsbypasser/code/AdsBypasser.user.js
> https://greasyfork.org/scripts/4294-antiadware/code/AntiAdware.user.js
> https://download.sf-helper.com/chrome/helper.user.js
> https://userscripts.adtidy.org/beta/assistant/4.3/assistant.user.js
> https://userscripts.adtidy.org/beta/popup-blocker/2.5/popupblocker.user.js
> https://userscripts.adtidy.org/beta/adguard-wot/1.0/wot.user.js
> https://userscripts.adtidy.org/beta/adguard-extra/1.0/adguard-extra.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/IdPUBKi.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/85UYhq1.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 7.0.2807.0
Browser: | Firefox
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing third-party cookies (180), Disable cache for third-party requests, Block WebRTC, Block Push API, Block Location API, Block Flash, Block Java, Hide your Referrer from third-parties (www.roblox.com), Hide your IP address (209.141.53.254)
Filters: | AdGuard Russian,<br>EasyList

**Comment by Alex-302** [comment]
URL: https://www.roblox.com/games/?SortFilter=default&TimeFilter=0

It is broken when all filters end extension module are disabled. It works with one of these exclusions:
```
@@||roblox.com^$jsinject
```
or
```
@@||roblox.com^$content
```

**Comment by Alex-302** [comment]
Another site:
http://www.megaman-11.com/us/

Actual(filters and extensions are disabled):
<details>

![image](https://user-images.githubusercontent.com/8361299/61497855-b6afb580-a9c9-11e9-91ba-1bf7766e81d5.png)

</details>

Expected(with `@@||megaman-11.com^$jsinject`):
<details>

![image](https://user-images.githubusercontent.com/8361299/61497883-cdeea300-a9c9-11e9-8374-fa7eecbc258a.png)

</details>

**Comment by vshlobinag** [comment]
Can't reproduce. Check on new version.

**Comment by Alex-302** [comment]
not reproduced
