### ISSUE TITLE
Add $redirect modifier

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1043]
https://github.com/AdguardTeam/Scriptlets#redirect-resources

Also, after this one is done, we should add new rules to the internal conversion rules:
* Handle `$rewrite` 
* `$empty` and `$mp4` should be converted into $redirect rules

**Comment by ameshkov** [comment]
We'll need @tvinzz's help with this -- we need a test page on testcases.adguard.com

**Comment by sxgunchenko** [comment]
core/pull-requests/1485
