### ISSUE TITLE
onibaku.group - the site is broken by JS injections

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1053]
@adguard-bot commented on [Wed Jul 24 2019](https://github.com/AdguardTeam/AdguardFilters/issues/37404)

### Issue URL (Incorrect Blocking)
[http://onibaku.group/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fonibaku.group%2F)
### Comment
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/C3heNv3.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/JBQcDAr.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 9
AdGuard version: | v3.2.98β (1.4.79cl)
Browser: | Firefox
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Block third-party Authorization header, Self-destructing first-party cookies (4320), Self-destructing third-party cookies (180), Disable cache for third-party requests, Block WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties (), Hide your Referrer from third-parties
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | AdGuard Russian,<br>AdGuard Mobile Ads,<br>AdGuard Annoyances,<br>AdGuard Simplified domain names,<br>AdGuard Base,<br>AdGuard Tracking Protection,<br>AdGuard Social Media

**Comment by Alex-302** [comment]
The site loads completely with exclusion only: `@@||onibaku.group^$jsinject`
Without exclusion HTML is loaded partially:
<details>

![image](https://user-images.githubusercontent.com/8361299/61809678-76778980-ae46-11e9-9bda-85fabc52e943.png)

</details>

**Comment by sfionov** [comment]
May be another case of #999

**Comment by Alex-302** [comment]
Another one https://github.com/AdguardTeam/AdguardFilters/issues/37411

**Comment by ameshkov** [comment]
Needs to be re-tested when the new nightly build is out

**Comment by ameshkov** [comment]
Works with the new nightly
