### ISSUE TITLE
$replace rules with escaped special characters aren't applied

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1057]
It even leads to an empty response.

### Steps to reproduce

1. Add this rule to the user filter: `||testcases.adguard.com/*/case6-disabling-multiple-replace-rules.txt$replace=/adguard/first \\$replace works/i`
2. Open `https://testcases.adguard.com/Filters/replace-rules/test-files/case6-disabling-multiple-replace-rules.txt`

### Expected result
The response must be `first $replace works`

### Actual result
Empty response

**Comment by sxgunchenko** [comment]
core/pull-requests/1415
