### ISSUE TITLE
3MB limit is not enforced for $replace rules

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1059]
### Steps to reproduce

1. Add `||testcases.adguard.com/*/case2-response-over-3mb.txt$replace=/adguard/Test passed/i` to the user filter
2. Open `http://testcases.adguard.com/Filters/replace-rules/test-files/case2-response-over-3mb.txt `

### Expected result
The file stays unchanged

### Actual result
$replace rule is applied

**Comment by sxgunchenko** [comment]
core/pull-requests/1422
