### ISSUE TITLE
Proxy corrupts content on some pages like mail.ru

### ISSUE THREAD

**Issue by hmage** [AdguardTeam/CoreLibs#106]
Current head of proxy (05cd5272ba5b5ce8ec14fc44c061266839638ce5) sometimes makes webpages look strange, like this:

![8eby9x93yl](https://user-images.githubusercontent.com/739119/32177443-7198419a-bd9b-11e7-9bbb-0174bc075f36.png)

To reproduce this, refresh several times, press some buttons on main site (enable newsfeed on bottom right) and click around news sections, while continuing to refresh.

**Comment by sfionov** [comment]
Seems that page data is not corrupted but extra data is written at the end of page.

**Comment by sfionov** [comment]
Body was passed to urlfilter_applyreplace without null-terminating character. Since this behaviour was changed in #104 (urlfilter_applyreplace gets length from parameter), we need to recheck it after merge of that ticket.

**Comment by sfionov** [comment]
Fixed by #104
