### ISSUE TITLE
LocalApiServer hanged after long sleep

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#1060]
After long sleep (2 days), LocalApiServer accepted connections but didn't respond to them.

**Comment by sfionov** [comment]
Actually, hanged one is main server. May be solved together with #1028

**Comment by sfionov** [comment]
Another idea: may be caused by NordVPN's connections termination - if we start listening when network is broken by NordVPN, it may cause problems.

**Comment by adbuker** [comment]
The forum thread is https://forum.adguard.com/index.php?threads/%D0%9E%D1%88%D0%B8%D0%B1%D0%BA%D0%B0-adguard-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8F-7-1-2898-cl-1-4-152-nightly.34589/

**Comment by sfionov** [comment]
Waiting for nightly with 1.5 to see if it port "0" usage helped.
