### ISSUE TITLE
AdGuard incompatibility with SecureMe(VPN)

### ISSUE THREAD

**Issue by northis** [AdguardTeam/CoreLibs#1064]
@Chinaski1 commented on [Wed Jul 03 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2808)

Unable to browse the internet with ADGuard and [VPN Secure-Me](https://www.vpnsecure.me/). 
Test method determined that the problem began to appear in nightly version 7.0.2708.6691.
For example in version 7.0.2693.6661 problem is not reproduced.

### Customer ID 

[Forum AdGuard](https://forum.adguard.com/index.php?threads/7-1-2817-unable-to-browse-internet-using-vpn.33485/#post-184767)

---

@northis commented on [Mon Jul 15 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2808#issuecomment-511486180)

Problem occured since upgrade CL 1.3.351 to 1.4.13

**Comment by war59312** [comment]
FYI, also happens with OpenVPN 2.4.7 on Win10 x64 1903
