### ISSUE TITLE
$content modifier doesn't work

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1065]
### Steps to reproduce

1. Add these rules:
`example.com$$div`
`@@||example.com^$content`
2. Go to - http://example.com/

### Expected behavior

`div` shouldn't be removed.
### Actual behavior

`div` is removed.

### Your environment
AdGuard for Windows nightly 7.1.2872(CL 1.4.120)

Works fine with stable build.

**Comment by sxgunchenko** [comment]
core/pull-requests/1425

**Comment by tvinzz** [comment]
cannot reproduce in FF ext and reproduced in Mac app
