### ISSUE TITLE
In order to allow content script we should modify response's CSP

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#107]
Here's what we need to do:

1. Add injections host (usually it is `local.adguard.com` or `injections.adguard.com`) to the list of trusted hosts
2. If a directive contains `strict-dynamic` or `nonce`, we should add our own random nonce AND pass that nonce to our content script.

I've linked the Win version code in the inner tracker.

**Comment by sfionov** [comment]
Merged, core/pull-requests/65
