### ISSUE TITLE
Uploading is impossible on both multiup.org and mirrorace.com

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1070]
@wk-952 commented on [Mon Mar 25 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2532)

The nightly build **v7.0.2372.6019** and the ones before it are causing a high CPU usage when trying to use any file hosting/mirroring website, also sometimes (but not 100% reproducible) the Adguard service crashes.
Eventually the entire upload process fails.

### Steps to reproduce

1. Install a fresh copy of Adguard **v7.0.2372.6019** then go to https://mirrorace.com/
2. Select whatever hosts you prefer then try to upload, preferably a large file >= 1GB
3. Watch the CPU usage for Adguard application in the task manger
4. Wait for sometime and the uploading process will fail

### Expected behavior

In Adguard **v6.4.1814.4903** none of that used to happen

### Your environment

* Browser 1: Opera v57.0.3098.106
* Browser 2: Microsoft Edge v42.17134.1.0
* OS: Windows 10 x64 v1803 (OS Build 17134.345)
* Adguard v7.0.2372.6019

---

@zzebrum commented on [Mon Apr 15 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2532#issuecomment-483199428)

@wk-952 please, try the latest nightly version. 

---

@zzebrum commented on [Mon Jul 15 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2532#issuecomment-511394403)

reopen task if needed. 

---

@wk-952 commented on [Thu Jul 18 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2532#issuecomment-512814104)

Hello, sorry I totally forgot about this.
I've updated to v7.1.2817 (stable) and the service no longer crashes, but uploading is still impossible on both [multiup.org](https://www.multiup.org/) and [mirrorace.com](https://mirrorace.com/).
Should I open a new issue for the new version ?

**Comment by wk-952** [comment]
There's also a strange behavior on all uploading hosts, when Adguard is enabled, the status bar of the uploading process will always reach 100% instantly and you can see an insane initial upload speed.

When I monitored the actual (initial) upload speed via programs as NetLimiter, etc..., they all reported a reasonable number.
This doesn't happen when Adguard is installed but disabled.

**Comment by ngorskikh** [comment]
Can not reproduce on current master.

**Comment by ngorskikh** [comment]
Tried this again.
Can't reproduce on Windows 10, 7.3 nightly 25 (build 3067, CL 1.5.170).
Can't reproduce with CoreLibs proxy (master).
