### ISSUE TITLE
Modifiers don't work with $replace rules

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1072]
### Steps to reproduce

1. Add this rule:
`||example.com^$replace=/Example/Test/,script`
2. Go here - http://example.com/

### Expected behavior

Rule should be applied only to `script`

### Actual behavior

Rule is applied to all requests

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/62373595-68a6c000-b53a-11e9-81f8-c71b56204a41.png)

</details>

### Your environment

* AdGuard for Windows nightly 7.1.2874 (CL 1.4.127)

**Comment by sxgunchenko** [comment]
core/pull-requests/1428
