### ISSUE TITLE
Multiple $csp rules do not work

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1073]
See the test here:
http://csp-tests.surge.sh/Filters/csp-rules/test-csp-rules.html

### Steps to reproduce

1. Add these rules to the user filter:
    ```
    ||example.org$csp=img-src https:
    ||example.org$csp=img-src example.org
    ```
2. Open `example.org`

### Expected result
Two CSP headers in the response

### Actual result:
Just one

**Comment by sxgunchenko** [comment]
core/pull-requests/1429
