### ISSUE TITLE
streetmap.co.uk - cannot load map

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1074]
@adguard-bot commented on [Wed Jul 31 2019](https://github.com/AdguardTeam/AdguardFilters/issues/37726)

### Issue URL (Incorrect Blocking)
[http://www.streetmap.co.uk](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fwww.streetmap.co.uk)
### Comment
Username: @GoneLoco460
> Streetmap used to work and now it does not so something changed either in streetmap or adguard.
> If I enter a UK postcode and press GO with Adguard enabled I get the Safari failed message. Disabling Adguard and the search on streetmap works.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/5eNB3Kr.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/A2vcHIZ.png)
</details>
<details>
  <summary>Screenshot 3</summary>

  ![Screenshot 3](https://reports-img.adguard.com/jwu1fug.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Mac
AdGuard version: | 2.0.6.559
Browser: | Safari
Filters: | AdGuard Russian,<br>EasyList Italy,<br>AdGuard Base,<br>Official Polish filters for AdBlock, uBlock Origin & AdGuard,<br>AdGuard Social Media,<br>AdGuard German,<br>AdGuard Dutch

---

@Alex-302 commented on [Wed Jul 31 2019](https://github.com/AdguardTeam/AdguardFilters/issues/37726#issuecomment-516887819)

@GoneLoco460 Hi. Please provide sample postcode. Cannot find working(GCHQ).
This `Go` button?
![image](https://user-images.githubusercontent.com/8361299/62223146-2146f500-b3bd-11e9-9a07-0d6dd3cf67d8.png)

---

@GoneLoco460 commented on [Thu Aug 01 2019](https://github.com/AdguardTeam/AdguardFilters/issues/37726#issuecomment-517195268)

Try GU11 3RB. That will give you the same map as in the suppled screenshots.

**Comment by Alex-302** [comment]
Steps to reprodue:
1. Open http://www.streetmap.co.uk
2. Enter `GU11 3RB`
3. Press GO button

Actual behavior:

Server error. Screenchot 2.

**Comment by vshlobinag** [comment]
core/pull-requests/1515
