### ISSUE TITLE
tvr.by - the site is broken by AdGuard injections

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1076]
With AdGuard codepage is wrong.
<details>

![image](https://user-images.githubusercontent.com/8361299/62530433-24bcff00-b849-11e9-8611-d9c813f4c308.png)

</details>

Not reproduced in Firefox, Opera 12 and IE.

This exclusion helps:
`@@||tvr.by^$jsinject,elemhide`
this - no:
`@@||tvr.by^$jsinject,generichide`

AdGuard 7.1.2874
Chrome and Opera 62

**Comment by zubrRB** [comment]
В Firefox при вводе адреса в адресную панель во вкладке на мгновение видны кракозябры, но затем сайт открывается нормально.

**Comment by zubrRB** [comment]
Ещё несколько недель назад сайт открывался нормально. AdGuard с тех пор не обновлялся, поэтому всё дело, вероятно, в последних обновлениях хромообразных браузеров.

**Comment by vshlobinag** [comment]
Can't reproduce on nightly 7.2.2931 (cl 1.4.163)

**Comment by Alex-302** [comment]
@zubrRB проверь снова. У меня тоже не повторяется.

**Comment by zubrRB** [comment]
На nightly 7.2.2931 (cl 1.4.163) и Chrome 77.0.3865.90 - повторяется. 
Ломает связка "Скрыть User-Agent" (по умолчанию)  + использование любого из двух юзерскриптов: 
**SaveFrom.net helper** https://download.sf-helper.com/chrome/helper.user.js
**Mouseover Popup Image Viewer** https://greasyfork.org/ru/scripts/404-mouseover-popup-image-viewer
Причем отключение только функции Антитрекинга или только обоих юзерскриптов проблему не решает, требуется одновременное отключение сокрытия юзерагента и одного из перечисленных юзерскриптов (любого из них; какого именно значения не имеет).

**Comment by zubrRB** [comment]
Либо перевод ползунка Антитрекинга в положение - Отключен, тогда даже юзерскрипты отключать нет необходимости.  При этом ручное отключение всех разделов Антитрекинга не помогает, только полное отключение его как функции AdGuard.

**Comment by vshlobinag** [comment]
Воспроизводится с одним скриптом SaveFrom.net helper, но нет необходимости отдельно отключать "скрыть UA" с отключенным Антитрекингом чтобы переставало воспроизводится (возможно потребуется несколько раз обновить страницу с отключенным кешом).

**Comment by zubrRB** [comment]
Я об это и указал: отключение сокрытия UA+скрипта либо лишь только отключение Антитрекинга.

**Comment by vshlobinag** [comment]
Есть три способа отключить Антитрекинг (при условии, что изначально включена только одна его опция "Скрыть UA")

1. Отключить опцию "Скрыть UA" и оставить включенным сам Антитрекинг.
2. Отключить опцию "Скрыть UA" и отключить Антитрекинг.
3. Оставить включенным "Скрыть UA" и отключить Антитрекинг.

Я не могу воспроизвести так, чтобы проявлялся баг в каком-либо из этих случаях. Но в сообщении от Sep 19, 2019 утверждается "При этом ручное отключение всех разделов Антитрекинга не помогает, только полное отключение его как функции AdGuard.", что соответствует утверждению, что способы 1 и 3 дают баг и только 1 не дает ему воспроизвестись. Возможно я не так понял это предложение.

У меня такое не воспроизводится на Chrome c отлюченным кешом в меню разработчика во вкладке Network. Чтобы перестало воспроизводится хватает двух обновлений страницы, либо подождать секунд 30.

Основной баг воспроизводится.

**Comment by zubrRB** [comment]
Включаете Антитрекинг, опцию в нём "Скрыть UA" и устанавливаете оба скрипта. После чего либо:
- Отключить опцию "Скрыть UA" и один любой из скриптов.
- Отключить Антитрекинг. 

При изменении любой из настроек следует дождаться перезапуска защиты (изменения цвета значка в трее с зеленого на желтый и снова на зелёный). Тестировалось в т. ч. в режиме инкогнито.

**Comment by vshlobinag** [comment]
Я просто к тому, что для воспроизведения бага достаточно двух условий: один скрипт и включить "Скрыть AU" любым способом :) Получается проще формулировка.

Например в способе "Отключить опцию "Скрыть UA" и один любой из скриптов." я просто отключил "Скрыть UA" и у меня перестал баг проявляться. У меня по крайней мере так.

Но это детали. Суть понятна, буду смотреть. Спасибо.

**Comment by zubrRB** [comment]
Для чистоты эксперимента вот все мои настройки https://github.com/AdguardTeam/AdguardFilters/issues/40623

**Comment by vshlobinag** [comment]
core/pull-requests/1521
