### ISSUE TITLE
$network rules do not work

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/CoreLibs#1077]
Rule [2606:2800:220:1:248:1893:25c8:1946]$network working good, the same situation if you use wildcard symbol like [2606:2800:220:*]$network, but it is not working when you use [2606:2800:220::/64]$network

**Comment by ameshkov** [comment]
I cannot confirm this, $network rules work just okay:
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#network-modifier

Also, after thinking a little bit about this, I don't think we need adding CIDR addresses support. Pattern matching provides almost the same capabilities.
