### ISSUE TITLE
Random (but persistent) crashes due to memory corruption

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1078]
Examples:
https://sentry.adguard.com/adg/adguard-android-rs/issues/32374/
https://sentry.adguard.com/adg/adguard-android-rs/issues/31059/

I've got a `tombstone` file from the last crash (32374), please take a look:
https://source.android.com/devices/tech/debug

All relevant files are in the NextCloud.

**Comment by sfionov** [comment]
Seems to be fixed :)
