### ISSUE TITLE
Safebrowsing/OCSP doesn't work with Parallels

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1079]
The computer seems to be just okay, but I observe these errors in the logs.

Logs are in NextCloud

**Comment by ameshkov** [comment]
The issue is probably caused by the fact that I had an IPv6 DNS server with link-local address configured in the system.

Even when we fix this, I suggest using a fallback address.

**Comment by vshlobinag** [comment]
Not problem of IPv6 DNS server with link-local address. This is problem of Parallels DNS.

**Comment by sfionov** [comment]
Fix still needed for QA.
