### ISSUE TITLE
$cookie modifier - rules with `$` as a special character doesn't work

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1085]
It seems that it's impossible to use `$` as a special character in regex rule with `$cookie` modifier.

### Steps to reproduce

1. Add this rule to user filter:
`$cookie=/^CONSENT\$/,domain=google.com`
2. Open https://www.google.com/

### Expected behavior

`CONSENT` cookie should be removed.
### Actual behavior

`CONSENT` cookie is not removed.

Rule like this works correctly:
`$cookie=/^CONSENT/,domain=google.com`

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/63167202-da016b00-c030-11e9-83ac-41ae39562034.png)

</details>

### Your environment

* AdGuard for Windows nightly 7.1.2894 (CL 1.4.150)

**Comment by vshlobinag** [comment]
core/pull-requests/1488
