### ISSUE TITLE
Crash in tls_post_process_client_hello

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1086]
https://sentry.adguard.com/adg/adguard-mac/issues/30014/

Much more details are here (also, the logs are in this issue's nextcloud folder):
https://github.com/AdguardTeam/AdguardForMac/issues/557

**Comment by ammnt** [comment]
@ameshkov,
1. Do I continue to provide logs?
2. Can you explain in short the reason for this error?
Thank you.

**Comment by ameshkov** [comment]
> Do I continue to provide logs?

I guess we might need them later when we extend logging.

> Can you explain in short the reason for this error?

It's hard to say at the moment, some deep analysis is required.

**Comment by akmLaVx** [comment]
Additional logs for this problem are available in helpdesk ticket 1662797.

**Comment by ameshkov** [comment]
@sfionov have we added additional asserts/logs to the current nightly? We should
