### ISSUE TITLE
CoreLibs doesn't fully pass GM_XMLHttpRequest testcase (1 of 2 tests passed)

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#1088]
See testcases at
https://github.com/AdguardTeam/TestCases/tree/master/public/Userscripts/apiTester
Temporary deployed into
http://userscripts.surge.sh/Userscripts/test-userscripts.html

**Comment by sfionov** [comment]
See testcases at 
https://github.com/AdguardTeam/TestCases/tree/master/public/Userscripts/apiTester
Temporary deployed into
http://userscripts.surge.sh/Userscripts/test-userscripts.html

**Comment by sxgunchenko** [comment]
The issue resides in the ApiTester userscript. No fixes needed on CoreLibs side.
