### ISSUE TITLE
Improper display of Google ads when site is whitelisted

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/CoreLibs#1091]
### Description
Whitelisting a website displaying Google AdSense ads results in said ads being displayed improperly. They only display an external frame and a "report this ad" icon, but the ad contents are gone.

### Steps to reproduce
1. Whitelist any website containing Google AdSense ads
2. Ads will be displayed improperly

### Submission & filtering log details
See ticket 2273678 for screenshots & filtering log details.

**Comment by ameshkov** [comment]
This is an old issue with nested iframes -- AdGuard cannot detect that the request from the whitelisted website
