### ISSUE TITLE
Firefox external settings doesn't allow DNS over HTTPS

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1092]
@karina-archazh commented on [Wed Jan 16 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2407)

### Steps to reproduce

1. Update Firefox to last version 64.0.2 (64-bit)
2. Open new tab about:config
3. In a search line find network.trr.mode and change to 2
4.  In a search line find network.trr.uri and change to https://dns.adguard.com/dns-query 
 or https://mozilla.cloudflare-dns.com/dns-query
5. Restart Firefox
6. Open tab about:config, find network.security.esni.enabled and change this parameter to true
7. Try to open https://forum.adguard.com/index.php
8. Change parameter to false
9. Try to open https://forum.adguard.com/index.php

### Expected behavior
If the Adguard for Win is enabled, the forum should open in both steps 7 and 9.
### Actual behavior

If the Adguard for Win is enabled, all https sites are unavailable to open.

If Adguard is disabled everything works as expected.

[adg_logs_6.4.1814.4903_0116_1317.zip](https://github.com/AdguardTeam/AdguardForWindows/files/2763652/adg_logs_6.4.1814.4903_0116_1317.zip)

<details><summary>Screenshot:</summary>

https://imgur.com/2YyNHmK
https://imgur.com/tjlwjRq

</details>

### Your environment

* Environment name and version: Firefox 64/64.0.2; AdGuard 6.4
* Operating system and version: Windows 10/7

---

@aspasskaya commented on [Wed Jan 16 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2407#issuecomment-454733037)

Logs Adguard 6.4 Win 10 
https://uploads.adguard.com/assa_v5gmy.zip

---

@neant1122 commented on [Thu Aug 15 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2407#issuecomment-521707960)

Over 7 month, can you please fix this bug? It's really annoying.

**Comment by tanus10** [comment]
I guess this is not yet fixed.

**Comment by ameshkov** [comment]
Not yet, but it is planned on the current sprint so it most likely will be addressed soon.

**Comment by ameshkov** [comment]
@vshlobinag at this point let's just add eSNI as a [custom extension](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_add_custom_ext.html) and simply forward it to the server. Full eSNI support will be added later when it becomes closer to something useable.

**Comment by vshlobinag** [comment]
core/pull-requests/1567
