### ISSUE TITLE
chilkatsoft.com - download issue

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1100]
@adguard-bot commented on [Thu Aug 29 2019](https://github.com/AdguardTeam/AdguardFilters/issues/39531)

### Issue URL (Incorrect Blocking)
[https://www.chilkatsoft.com/downloads_vcpp.asp](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.chilkatsoft.com%2Fdownloads_vcpp.asp)
### Comment
Username: @docontrol
> The issue is simply that while downloading the file https://chilkatdownload.com/9.5.0.79/chilkat-9.5.0-x86-vc2019.zip or any of the other files on the listed website, the download gets corrupted in many cases. It starts out by indicating that it will download the full content length, but then suddenly stops downloading. Even if I disable the ad blocker or stealth mode, it keeps failing. If however I add chilkatdownload.com to the https exceptions list, it works fine. It also works fine if I disable ad guard altogether. 
> 
> The images do not show much. The downloads are public, so you should be able to tests this.
> 
> --
> The information below is automatically generated. Do not delete it.
> 
> Referrer:
> https://www.chilkatsoft.com/downloads_vcpp.asp
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
> https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/MToxcR2.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/XwJYmvv.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 7.1.2817.0
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing third-party cookies (180), Block Location API
Filters: | AdGuard Russian,<br>Filter unblocking search ads and self-promotion,<br>EasyList Hebrew,<br>EasyList Italy,<br>Liste AR,<br>Fanboy's Annoyances,<br>AdGuard Annoyances,<br>AdGuard Base,<br>Web Annoyances Ultralist,<br>Adblock Warning Removal List,<br>AdGuard Tracking Protection,<br>AdGuard Social Media,<br>AdGuard German,<br>AdGuard Dutch,<br>AdGuard Spanish/Portuguese
Other extensions used: | None that are relevant here

---

@docontrol commented on [Thu Aug 29 2019](https://github.com/AdguardTeam/AdguardFilters/issues/39531#issuecomment-526060011)

Perhaps I should add to the issue that I am located on a 1 Gbps Internet connection so the download is extremely fast. If I route the traffic through Fiddler while having AdGuard enabled it also seems to work.

---

@Alex-302 commented on [Thu Aug 29 2019](https://github.com/AdguardTeam/AdguardFilters/issues/39531#issuecomment-526181445)

Is Fiddler added to filtered apps in AdGuard?

---

@Alex-302 commented on [Thu Aug 29 2019](https://github.com/AdguardTeam/AdguardFilters/issues/39531#issuecomment-526181933)

Could you please check with the latest nightly build?

---

@docontrol commented on [Thu Aug 29 2019](https://github.com/AdguardTeam/AdguardFilters/issues/39531#issuecomment-526183895)

> Is Fiddler added to filtered apps in AdGuard?

I do not see the point of the question. I only launched Fiddler for a moment to see if it would behave differently. I do not generally have Fiddler running.

---

@Alex-302 commented on [Thu Aug 29 2019](https://github.com/AdguardTeam/AdguardFilters/issues/39531#issuecomment-526185465)

As I remember, HTTPS filtering is not enabled by default in Fiddler, and AdGuard does not filter Fiddler's traffic by default.

---

@docontrol commented on [Thu Aug 29 2019](https://github.com/AdguardTeam/AdguardFilters/issues/39531#issuecomment-526192809)

> As I remember, HTTPS filtering is not enabled by default in Fiddler, and AdGuard does not filter Fiddler's traffic by default.

Please ignore my comments about Fiddler. It only helps to clutter the matter further. The issue is between Chrome, AdGuard and perhaps the cloud service used for streaming the file. To begin with I only want to know if others have the same issue?

The HTTPS filter that I mentioned is the one that is in AdGuard's Network settings under HTTPS filtering. I experimented with adding the download server to the exclusions and that solved the problem, but I prefer to find out what is causing it in the first place.

---

@docontrol commented on [Thu Aug 29 2019](https://github.com/AdguardTeam/AdguardFilters/issues/39531#issuecomment-526195576)

> Could you please check with the latest nightly build?

I just tried with 7.2.2903 NIGHTLY (CL 1.4.155) and the issue is still there. I also updated all filters and scripts. Notice however that even when I disable the ad blocker or the stealth mode, the issue is also still there. It only goes away once I add chilkatdownload.com to the HTTPS exclusions or disable AdGuard entirely.

---

@Alex-302 commented on [Thu Aug 29 2019](https://github.com/AdguardTeam/AdguardFilters/issues/39531#issuecomment-526279646)

It seems this is a bug, and cannot be resolved by filters.
Do you use download apps or default browser's downloader?
On my end this issue is not reproduced.

**Comment by docontrol** [comment]
I use the default browser implementation (Chrome Version 76.0.3809.132 (Official Build) (64-bit)). I just ran the same test in Firefox 68.0.2 (64-bit) with the same result, but it only failed once or twice and after that I could not get it to fail the download. In Chrome I can easily reproduce the error however. Finally I tried Microsoft Edge 44.18362.267.0 today and I cannot reproduce the issue there at all.

**Comment by docontrol** [comment]
By the way I also tried Chrome in incognito mode and it still fails without all the extensions (LastPass, Tampermonkey, Adobe PDF, etc.).

**Comment by docontrol** [comment]
I could keep adding results (I guess):

Opera 63.0.3368.53 (Chromium based, clean install):
AG enabled = FAIL
AG disabled = SUCCESS

Internet Explorer 11.295.18362.0:
AG enabled = FAIL (and realizes it, see image, clicking retry works)
AG disabled = SUCCESS

**Comment by ameshkov** [comment]
@docontrol could you please try one more thing -- try switching AdGuard's driver to "redirect mode", you can do it in the advanced settings.

**Comment by docontrol** [comment]
> @docontrol could you please try one more thing -- try switching AdGuard's driver to "redirect mode", you can do it in the advanced settings.
> 
> Settings -> General -> Scroll down -> Advanced -> Find "Use driver in redirect mode" there

No difference. Tried both Opera and Chrome.

**Comment by ameshkov** [comment]
@docontrol hmm, this is so weird. 

Well, the good news is that it proves that the driver is not a problem, it is somewhere in AdGuard's HTTP/2 filter.

We might have to wait for @sfionov to get back so that he could take a look. Meanwhile, I'll try to diagnose it as good as possible.

Since I cannot reproduce this issue on our side, I have to ask you for one more thing:

1. Close all unrelated tabs and disable all extensions
2. Open chrome://net-export/
3. Start logging just before reproducing the issue
4. Reproduce it
5. Export the log and send it to `devteam@adguard.com`, mention this issue in the email

**Comment by docontrol** [comment]
> Since I cannot reproduce this issue on our side, I have to ask you for one more thing:
> 
> 1. Close all unrelated tabs and disable all extensions
> 2. Open chrome://net-export/
> 3. Start logging just before reproducing the issue
> 4. Reproduce it
> 5. Export the log and send it to `devteam@adguard.com`, mention this issue in the email

@ameshkov: I have sent it now.

**Comment by ameshkov** [comment]
@docontrol got it, thank you! 

@sfionov logs are in the private NextCloud. I've also attached my own logs there. The only difference I see is that the flow control behaves differently.

In my case there many `HTTP2_STREAM_UPDATE_RECV_WINDOW` frames and the window size is always around 6MB.

In the problematic log, there are also many `HTTP2_STREAM_UPDATE_RECV_WINDOW` frames in the beginning, and the window size starts at 6MB as well. However, it then quickly drops to about 2MB, and there are no `HTTP2_STREAM_UPDATE_RECV_WINDOW` frames in the last 50ms of the log.

**Comment by docontrol** [comment]
@ameshkov I noticed that I have the same problem downloading the Postman app from https://www.getpostman.com/downloads/ or more accurately from https://dl.pstmn.io/download/latest/win64. Once I added dl.pstmn.io to the exclusions list it worked fine. 
![Annotation 2019-09-10 144912](https://user-images.githubusercontent.com/35772570/64615151-47a77980-d3da-11e9-9292-fe3a388af8c3.png)

**Comment by ameshkov** [comment]
@docontrol yeah, looks exactly the same. @sfionov is back so I guess we'll be able to look into it soon

**Comment by ameshkov** [comment]
Also, we have a few ideas about what could be the root cause of this issue, we just need to prepare a test build.

**Comment by docontrol** [comment]
@ameshkov I can't help but wonder if this is the reason why e.g. dl.dropboxusercontent.com is default added to the HTTPS Exclusions?

**Comment by ameshkov** [comment]
@docontrol tbh, this is due to some old issue which is no more relevant.

**Comment by sfionov** [comment]
core/pull-requests/1536
