### ISSUE TITLE
Get rid of dropping bypassed connections during soft-reconfig

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#1101]
In fact, this is reverting the https://github.com/AdguardTeam/CoreLibs/issues/1003. We should do it in order to don't irritating users in particular when filters and/or userscripts are updated

**Comment by ameshkov** [comment]
Guys, please note that this must be a hotfix to v1.4. We shouldn't roll out v1.5 yet.

**Comment by sxgunchenko** [comment]
core/pull-requests/1475

no need to test
