### ISSUE TITLE
BBC.com - the site is broken with local VPN mode

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1102]
@adguard-bot commented on [Wed Aug 28 2019](https://github.com/AdguardTeam/AdguardFilters/issues/39439)

### Issue URL (Incorrect Blocking)
[http://BBC.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2FBBC.com)
### Comment
> When HTTPS filtering is disabled the web site displays correctly. When enabled it is wrong. I have attached BBC sports as an example but the same happens with all Amazon sites as well.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/3Gybg2M.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/PQ6kGFU.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 8.1.0
AdGuard version: | v3.2.140 (1.4.138cl)
Browser: | Firefox
AdGuard mode: | proxy
Filtering quality: | Simplified
HTTPS filtering: | disabled
DNS requests blocking: | enabled
Filters: | AdGuard Base
Other extensions used: | Comodo mobile security

---

@slavaleleka commented on [Wed Aug 28 2019](https://github.com/AdguardTeam/AdguardFilters/issues/39439#issuecomment-525714812)

can't reproduce at my end. check please without Comodo mobile security. and notice if there any differences with proxy-/vpn-filtering mode and simplified/high quality filtering method. you also should make sure that AdGuard Certificate is installed in Firefox (it should be installed manually in Settings > Network > HTTPS Filtering)

---

@doctor-who1 commented on [Thu Aug 29 2019](https://github.com/AdguardTeam/AdguardFilters/issues/39439#issuecomment-526033941)

I tried various combinations and all works perfectly when I switched from local VPN filtering to local HTTP proxy filtering with all other settings reset to what I had set up originally.

---

@Alex-302 commented on [Thu Aug 29 2019](https://github.com/AdguardTeam/AdguardFilters/issues/39439#issuecomment-526182510)

@doctor-who1 please check with disabled filters, extensions and stealth mode.

---

@doctor-who1 commented on [Thu Aug 29 2019](https://github.com/AdguardTeam/AdguardFilters/issues/39439#issuecomment-526214692)

Everything works perfectly with filters disabled and in stealth mode. I am currently using the app in stealth mode and with comodo mobile security enabled.

---

@Alex-302 commented on [Thu Aug 29 2019](https://github.com/AdguardTeam/AdguardFilters/issues/39439#issuecomment-526274768)

Ok. Please enable stealth mode and check again. If the site works fine, please enable filters one-by-one with checking.

---

@doctor-who1 commented on [Fri Aug 30 2019](https://github.com/AdguardTeam/AdguardFilters/issues/39439#issuecomment-526450594)

Everything is working correctly (in stealth mode and normal mode). It only goes wrong if I switch back to local VPN from local http proxy filtering.

---

@Alex-302 commented on [Fri Aug 30 2019](https://github.com/AdguardTeam/AdguardFilters/issues/39439#issuecomment-526535299)

That is strange. So if you are using your own settings with local http proxy the site worsk as expected, but with local VPN it is broken? Could you please check with disabled filters, stealth mode and extensions with local VPN mode?

---

@doctor-who1 commented on [Fri Aug 30 2019](https://github.com/AdguardTeam/AdguardFilters/issues/39439#issuecomment-526540484)

With disabled filters, stealth mode and extensions disabled in local VPN mode the site displays incorrectly as per the screenshot sent previously. Only switching from local VPN to HTTP proxy the site displays correctly. I have re-enabled stealth mode, and the other filters and everything is displayed correctly.

**Comment by Alex-302** [comment]
Not reproduced on my device.

@doctor-who1 please collect debug log and send it to devteam@adguard.com, mention this issue in the email
https://kb.adguard.com/android/solving-problems/log#debug

**Comment by ameshkov** [comment]
@doctor-who1 the log is "INFO" level, it's not enough:(

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Settings -> Advanced -> Set "Logging level" to "Record everything". It's desirable to close all background apps that don't concern the problem beforehand.
2. Reproduce the problem and set the logging level back to "Default". Notice the exact time when it happened.
3. Settings -> Advanced -> Export Logs
4. Send it to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.
