### ISSUE TITLE
AdGuard for Mac randomizes domain letter case

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/CoreLibs#1104]
When HTTP request are from Chrome which works through AdGuard proxy on port 3128, AdGuard randomizes uppercase and lowercase letters of the domain. The log below is captured by Surge Mac proxy (from https://nssurge.com).

![image](https://user-images.githubusercontent.com/15856304/64063217-fb01b880-cbf9-11e9-88e8-32c79615fba3.png)

Application version: 2.1.2.595 release
OS: 10.14.6
Reported by: 2298157

**Comment by sfionov** [comment]
evdns problem, "randomize-case:0" settings is needed to be passed to evdns_base.
