### ISSUE TITLE
Blocking rules don't work alongside with specific $replace exceptions rules

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1105]
### Steps to reproduce

1. Add these rules to user filter:
`||google.com^$replace=/try/\/*test*\/try/`
`@@||google.com/xjs/$replace=/try/\/*test*\/try/`
`||google.com/xjs/$important`
2. Go to https://www.google.com/

### Expected behavior

Requests from `google.com/xjs/` should be blocked.
### Actual behavior

Requests from `google.com/xjs/` are not blocked.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/64107066-e3513e00-cd79-11e9-9444-5339fe15f448.png)

</details>

It works fine if I use `@@||google.com/xjs/$replace` (instead of `@@||google.com/xjs/$replace=/try/\/*test*\/try/`)

### Your environment

* AdGuard for Windows 7.2.2910 (CL 1.4.157)

**Comment by ameshkov** [comment]
Needs to be resolved with #1106

**Comment by sxgunchenko** [comment]
fixed along with #1106
