### ISSUE TITLE
$popup rule blocks images on argumentplus.ru

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1109]
Original issue:
https://github.com/AdguardTeam/AdguardFilters/issues/39780

caused by `||shortpixel.ai^$popup` (Base filter)

Images are loaded using redirect
![image](https://user-images.githubusercontent.com/8361299/64190825-df0f4880-ce7f-11e9-9997-461765fff524.png)

<details>

![image](https://user-images.githubusercontent.com/8361299/64190859-f51d0900-ce7f-11e9-841a-5b2f004afae6.png)

</details>

PS: disable temporary exclusion before checking: `@@||cdn.shortpixel.ai^$domain=argumentplus.ru`

**Comment by ameshkov** [comment]
It works as intended, we can't do much about this
