### ISSUE TITLE
bestbuy.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1110]
@adguard-bot commented on [Fri Sep 06 2019](https://github.com/AdguardTeam/AdguardFilters/issues/40034)

### Issue URL (Incorrect Blocking)
[https://www.bestbuy.com/site/searchpage.jsp?st=Jabra+75t&_dyncharset=UTF-8&_dynSessConf=&id=pcat17071&type=page&sc=Global&cp=1&nrp=&sp=&qp=&list=n&af=true&iht=y&usc=All+Categories&ks=960&keys=keys](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.bestbuy.com%2Fsite%2Fsearchpage.jsp%3Fst%3DJabra%2B75t%26_dyncharset%3DUTF-8%26_dynSessConf%3D%26id%3Dpcat17071%26type%3Dpage%26sc%3DGlobal%26cp%3D1%26nrp%3D%26sp%3D%26qp%3D%26list%3Dn%26af%3Dtrue%26iht%3Dy%26usc%3DAll%2BCategories%26ks%3D960%26keys%3Dkeys)
### Comment
Username: @carlylemiii
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/zm0yVTW.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/0GQ7kRH.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 10
AdGuard version: | v3.2.150 (1.4.138cl)
Browser: | Chrome
Stealth mode options: | Hide your search queries, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing third-party cookies (180)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | AdGuard Mobile Ads,<br>AdGuard Annoyances,<br>AdGuard Base,<br>AdGuard Tracking Protection,<br>AdGuard Social Media

**Comment by AdamWr** [comment]
Steps to reproduce:
1. Disable this rule from AdGuard Base filter:
`@@||bestbuy.com/site/canopy/component/fulfillment/$jsinject,elemhide,extension`
2. Go here - https://www.bestbuy.com/site/searchpage.jsp?st=Jabra+75t&_dyncharset=UTF-8&_dynSessConf=&id=pcat17071&type=page&sc=Global&cp=1&nrp=&sp=&qp=&list=n&af=true&iht=y&usc=All+Categories&ks=960&keys=keys
3. Click on `United States`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/64414380-857f6780-d093-11e9-86f9-0182ddfbafaf.png)

</details>

**Comment by sfionov** [comment]
Since page receives its chunks as text/html in XHRs, no fixes at our side are needed.

**Comment by AdamWr** [comment]
Similar issue - https://github.com/AdguardTeam/AdguardFilters/issues/41717

**Comment by ameshkov** [comment]
@sfionov can we tweak HTML detection rules to avoid this somehow?
