### ISSUE TITLE
Domain restrictions semantics

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1113]
If the following conditions are true:

* pattern === ANY_URL
* domain restriction is not empty
* resource type ===(SUB)DOCUMENT

Then use the host of the request URL to check domain restrictions.

Test rules:
* `$csp=script-src 'none',domain=example.org`
* `$cookie=test,domain=example.org`

<s>
In the case when there's no "source" hostname, `$domain` should be checked against the request's host.
</s>

**Comment by sxgunchenko** [comment]
core/pull-requests/1500

**Comment by sxgunchenko** [comment]
Testing instructions:
1) add the following rule: `*$empty,domain=google.com`
2) open in browser `google.com`
3) check that page is blank (to ensure the correctness, check that the request to google.com has no referrer)

**Comment by sxgunchenko** [comment]
core/pull-requests/1541
