### ISSUE TITLE
Check that AG works properly with Chrome and FF when DOH is enabled

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1117]
See the details here:
https://www.chromium.org/developers/dns-over-https

Also, it's unclear how it will work on Android.

**Comment by zubrRB** [comment]
И если с Simple DNSCrypt используется DoH...

**Comment by sfionov** [comment]
Related to #1092

**Comment by vshlobinag** [comment]
how to enable on firefox
https://www.zdnet.com/article/how-to-enable-dns-over-https-doh-in-firefox/

how to enable on chrome
https://www.zdnet.com/article/how-to-enable-dns-over-https-doh-in-google-chrome/

windows 10: works on FF, Chrome, but bypassed

android: doesn't work on FF, on Chrome https://github.com/bromite/bromite/wiki/Enabling-DNS-over-HTTPS can't find experiment setting.
