### ISSUE TITLE
$replace rules don't work on some websites

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1119]
### Steps to reproduce

1. Add this rule:
`||t66y.com^$replace=/[\s\S]*/Test/`
2. Go here NSFW - https://t66y.com/

### Expected behavior

Content should be replaced by `$replace` rule
### Actual behavior

`$replace` rule doesn't work

### Your environment

* AdGuard for Windows 7.2.2917 (CL 1.4.157)

**Comment by AdamWr** [comment]
It seems that it happens on other websites too - https://github.com/AdguardTeam/AdguardForWindows/issues/2950

**Comment by ameshkov** [comment]
Both websites are non-UTF8 websites.

Guys, as I've said before - use Latin1 for $replace rules when you don't know what encoding to use.

**Comment by moraks** [comment]
But, in previous ADG 7.1.2817 all user rules work fine. On non-UTF8 websites too, without any special encoding for rules...

**Comment by sfionov** [comment]
@moraks Yes, it is regression.

**Comment by vshlobinag** [comment]
core/pull-requests/1498
