### ISSUE TITLE
Some amp websites opened from google.com are not filtered on first visit

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1120]
### Steps to reproduce

1. Add these rules to user filter:
`~google.com##body`
`www-tabletowo-pl.cdn.ampproject.org,tabletowo.pl##body`
2. Change to mobile view or open link from step 3 on Android
3. Go here - https://www.google.com/search?q=ios+13+site%3Atabletowo.pl&oq=ios+13+site%3Atabletowo.pl
4. Scroll a little and click on link from `tabletowo.pl` (with amp icon, like on a screenshot below)
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/64858179-ee805580-d626-11e9-8081-0d1b6d5d1710.png)

</details>

### Expected behavior

Website should be blank.

### Actual behavior

Rules are applied after refreshing website.

### Your environment

* AdGuard for Windows 7.2.2921 (CL 1.4.157)
* AdGuard for Android v3.3 nightly 4 (18)

**Comment by ameshkov** [comment]
Well, that's how AMP work in the case of google.com. The content is pre-loaded in an XHR request, we can't do much with it at least at this point.
