### ISSUE TITLE
idol.sankakucomplex.com - broken website

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1121]
### Steps to reproduce

1. Disable this rule from Base filter:
```
@@||idol.sankakucomplex.com/post/index.content?next=*&page=$other,elemhide,jsinject,extension
```
2. Go here **NSFW** - https://idol.sankakucomplex.com/
3. Scroll down and wait a while

### Expected behavior

New images should loading while scrolling.

### Actual behavior

New images don't load.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/64867413-a587cb80-d63d-11e9-9a04-31df84b3930d.png)

</details>

### Your environment

* AdGuard for Windows 7.2.2921 (CL 1.4.157)

**Comment by sxgunchenko** [comment]
The responses for requests to `idol.sankakucomplex.com/post/index.content?next=*&page=` contain malformed HTML pages. This leads to incorrect content-script injection. Not sure if we should handle those HTMLs, I think it's better to just leave the rule. Is it OK for you, @AdamWr?

**Comment by sxgunchenko** [comment]
It seems to be the result of an overlap between the page and the filtering engine features. It does not worth to handle this case in the CoreLibs, so keeping the rule in the Base filter is good enough for now.
