### ISSUE TITLE
Requests to the `injections.adguard.org` leak to the network

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#1122]
Logs are in the NCloud
https://uploads.adguard.com/buker_gj8v0.png

**Comment by sxgunchenko** [comment]
core/pull-requests/1485

testing instructions:
1) turn on AdGuard Assistant, set intercept tcp connections flag
2) open browser console, go to any website
3) drag the assistant icon anywhere
4) check that there are no any error messages like https://uploads.adguard.com/buker_gj8v0.png in the console
