### ISSUE TITLE
www.wind.gr is not working when protection is enabled

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1124]
Steps to reproduce:
1. Open www.wind.gr

#### Actual behavior:

Infinite loop with `err_connection_reset`

### System configuration

Information | value
--- | ---
Platform: | Win7 x64
AdGuard version: | 7.2.2921.0
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing first-party cookies (4320), Self-destructing third-party cookies (180), Disable cache for third-party requests, Block Push API, Block Location API, Block Flash, Block Java, Hide your User-Agent (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36)
Filters: | AdGuard Russian,<br>AdGuard Annoyances,<br>AdGuard Base,<br>AdGuard Tracking Protection,<br>AdGuard Social Media

Logs:
[logs.zip](https://github.com/AdguardTeam/CoreLibs/files/3615139/logs.zip)

**Comment by sfionov** [comment]
Merged into https://github.com/AdguardTeam/CoreLibs/issues/1223
