### ISSUE TITLE
re-store.ru is broken by AdGuard

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1125]
Original issue: https://github.com/AdguardTeam/AdguardFilters/issues/40541

Actual behavior: blank page.

Reproduced on MacOS only. Exclusions don't help.

AdGuard 2.1.2.595

Not sure, but it seems not related to https://github.com/AdguardTeam/CoreLibs/issues/1124

**Comment by sfionov** [comment]
Duplicate of #1084
