### ISSUE TITLE
educationperfect.com - the site is broken by AdGuard injections

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1126]
@adguard-bot commented on [Mon Sep 16 2019](https://github.com/AdguardTeam/AdguardFilters/issues/40566)

### Issue URL (Incorrect Blocking)
[https://www.educationperfect.com/app/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.educationperfect.com%2Fapp%2F)
### Comment
Username: @milodakat
> just does not load when adguard is enabled. when i progress to the log in screen it does not work with  adguard enabled. but the hompage (https://www.educationperfect.com) does

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/FVc6kEP.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/k69sUp8.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 7.2.2920
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Self-destructing third-party cookies (180), Block Flash, Block Java
Filters: | Filter unblocking search ads and self-promotion,<br>AdGuard French,<br>AdGuard Base,<br>AdGuard Tracking Protection,<br>AdGuard Social Media,<br>AdGuard Dutch,<br>AdGuard Annoyances,<br>EasyList,<br>EasyPrivacy,<br>Fanboy's Enhanced Tracking List
Other extensions used: | Bitdefender total, bitdefender anti-tracker

**Comment by Alex-302** [comment]
Added temporary exclusion:
`@@||educationperfect.com^$jsinject,elemhide,extension`

**Comment by sfionov** [comment]
core//pull-requests/1496
