### ISSUE TITLE
AdGuard's JS is not injected on layardunia21.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1128]
It seems that sometimes on this website AdGuard's JS is not injected.

### Steps to reproduce

1. Add this rule:
`layardunia21.com##body`
2. Go here - http://www.layardunia21.com/
3. Refresh website few times

### Expected behavior

Everytime website should be blank.

### Actual behavior

Sometimes AdGuard's JS is not injected (there is no `local.adguard.org` in source code).

### Your environment

* AdGuard for Windows nightly 7.2.2921 (CL 1.4.157)

**Comment by sfionov** [comment]
core/pull-requests/1519
