### ISSUE TITLE
$replace rules don't work on vidapi.threepi.de

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1130]
### Steps to reproduce

1. Add this rule:
`||vidapi.threepi.de/storage/media/$replace=/[\s\S]*/Test/,important`
2. Go here - https://vidapi.threepi.de/storage/media/1d/4e/99/981b9f283b08cbc478f6cd.jpg

If for some reason the link above will stop working then go here - https://www.pietsmiet.de/videos/56215-civ6-lucker
and search for similar requests like on screenshot below.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/65148292-2ec54680-da20-11e9-897a-9802059c5b0a.png)

</details>

### Expected behavior

Content should be replaced by `$replace` rule

### Actual behavior

`$replace` rule doesn't work

### Your environment

* AdGuard for Windows nightly 7.2.2931 (CL 1.4.163)

**Comment by ameshkov** [comment]
@sxgunchenko I suggest you go visit `https://www.pietsmiet.de/videos/56215-civ6-lucker` right away and see it with your own eyes.

Once the response is received and we know the real content type, information obtained from the URL must be discarded.

**Comment by sxgunchenko** [comment]
core/pull-requests/1535
