### ISSUE TITLE
Crash with network rule in user filter

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/CoreLibs#1131]
Comment:

**In filter rule editor simple mode, type any IP like 8.8.8.8$important,network and then press enter, adguard will crash. It is significant that you add important parameter first and then network parameter**

This issue is not easy to reproduce. On some machines it not cause a crash, network rule applies successfully.

Logs are available in ncloud.

**Comment by sfionov** [comment]
core/pull-requests/1520
