### ISSUE TITLE
Browsing security breaks 'Show comments' button on telegraph.co.uk

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/CoreLibs#1132]
### The issue is reproducing on AG for MacOS and AG for Windows

---

@adguard-bot commented on [Fri Sep 13 2019](https://github.com/AdguardTeam/AdguardFilters/issues/40430)

#### Issue URL (Incorrect Blocking)
[https://www.telegraph.co.uk/politics/2019/09/13/david-cameron-attacks-boris-johnson-michael-gove-brexit-breaks/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.telegraph.co.uk%2Fpolitics%2F2019%2F09%2F13%2Fdavid-cameron-attacks-boris-johnson-michael-gove-brexit-breaks%2F)

#### Comment
Username: @RobertDunbar
> User comments are blocked/not working when AdGuard is enabled.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/xAQzetm.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/Ai8sBVo.jpg)
</details>

---
---

@slavaleleka commented on [Fri Sep 20 2019](https://github.com/AdguardTeam/AdguardFilters/issues/40430#issuecomment-533534216)

could you please disable Phishing and malware protection and check again?

---

@RobertDunbar commented on [Fri Sep 20 2019](https://github.com/AdguardTeam/AdguardFilters/issues/40430#issuecomment-533535980)

Hi,

That seems to have fixed it!!! Thank you.

So there is something about phishing and malware protection that is blocking those comments.

**Comment by vshlobinag** [comment]
core/pull-requests/1556

**Comment by slavaleleka** [comment]
<details>
  <summary>the issue is still reproducing with AG for Mac 2.4.2.712 nightly (CL 1.5.165)</summary>


![slbdz8e7e5s](https://user-images.githubusercontent.com/45171506/73184373-601bf480-412d-11ea-9a56-8418fe3ea3d6.png)

</details>
