### ISSUE TITLE
AdGuardSvc.exe is stopped by clicking on router GUI Statistics Button

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1133]
@et6at commented on [Sun Sep 22 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2983)

AdguardSvc.exe is stopped by navigating custom Router and clicking Statistics page button, in order to reproduce:

a) Install AdGuard for Windows latest stable, install Chromium, https://chromium.woolyss.com/;

b) Click Netgear DGN2200v4 Statistics button, as soon as statistic button is clicked AdGuardSvc is stopped;

c) Firmware used: 
I am using custom firmware, but GUI is same as NetGear http://alfie.altervista.org/amod2200V4/

AdGuardSvc.exe is stopped  with following output inside logs:

**ERROR, AdguardSvc, 28, 22.09.2019 20:46:23.433, Adguard.Core.Common.Logging.CoreLoggerAdapter | assert: C:\Users\Bamboo\bamboo-agent-home\xml-data\build-dir\CL-WL12-JOB1\filtering\html\src\html_parser.c:207 assertion (parser->tag == NULL) failed!**

![65393012-c0fc8000-dd7b-11e9-9599-3c829dbd2623](https://user-images.githubusercontent.com/7214961/65393193-eee2c400-dd7d-11e9-93f9-0ca12b6ce19a.png)

![0](https://user-images.githubusercontent.com/7214961/65393055-39634100-dd7c-11e9-8ad7-9f1b2336d3cd.png)

---

@et6at commented on [Sun Sep 22 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2983#issuecomment-533914091)

Problem happen with both AdGuard Assistant Enabled or Disabled, with the exception that if AdGuard assistant is disabled, the service can restart.

![0](https://user-images.githubusercontent.com/7214961/65393768-5f411380-dd85-11e9-9c2b-6104082177ee.png)

**Comment by et6at** [comment]
Without and With AdGuard, HAR:

[HAR.zip](https://github.com/AdguardTeam/CoreLibs/files/3640166/HAR.zip)

**Comment by adbuker** [comment]
logs are in the NCloud

**Comment by vshlobinag** [comment]
core/pull-requests/1528

Can be tested on emulator https://highspeed.tips/files/emulators/netgear_genie/start.html
