### ISSUE TITLE
repo.anaconda.com - downloaded file is corrupted

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1135]
@adguard-bot commented on [Wed Sep 25 2019](https://github.com/AdguardTeam/AdguardFilters/issues/41145)

### Issue URL (Incorrect Blocking)
[https://repo.anaconda.com/archive/Anaconda3-2019.07-Windows-x86_64.exe](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Frepo.anaconda.com%2Farchive%2FAnaconda3-2019.07-Windows-x86_64.exe)
### Comment
Username: @jiyongwoo
> When adguard is on, downloaded file is corrupted.
> After adguard is off, downloaded file has no error.
> --
> 하단 정보는 자동으로 생성되었습니다. 삭제하지 마세요.
> 
> Referrer:
> https://www.anaconda.com/distribution/
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
> https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/uBhNBVX.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/uBhNBVX.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 7.2.2936.0
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Self-destructing first-party cookies (0), Self-destructing third-party cookies (0), Block Push API, Block Location API
Filters: | AdGuard Annoyances,<br>AdGuard Base,<br>List-KR,<br>AdGuard Tracking Protection,<br>AdGuard Social Media

**Comment by sfionov** [comment]
core/pull-requests/1536
