### ISSUE TITLE
$generichide exclusion is not working, if exists URL exclusion

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1137]
### Steps to reproduce:

1. Disable all filters and add these rules to user filter:
```
##a[title] 
@@||wikipedia.org/wiki^
@@||wikipedia.org^$generichide
```
2. Open https://ru.wikipedia.org/wiki/%D0%92%D0%B8%D0%BA%D0%B8%D0%BF%D0%B5%D0%B4%D0%B8%D1%8F:%D0%9F%D0%BE%D0%BF%D1%83%D0%BB%D1%8F%D1%80%D0%BD%D1%8B%D0%B5_%D1%81%D1%82%D0%B0%D1%82%D1%8C%D0%B8/2017

### Expected result:

Element hiding rule is not applied:
<details><summary>Screenshot:</summary> 

![image](https://user-images.githubusercontent.com/8361299/65816835-5dee6b80-e209-11e9-9a09-9fc5ce5f28e3.png)

 </details>

### Actual behavior:

Element hiding rule is applied:
<details><summary>Screenshot:</summary> 

![image](https://user-images.githubusercontent.com/8361299/65816843-7e1e2a80-e209-11e9-8bd1-02e4b17607c3.png)

 </details>

AdGuard 7.2.2937
Windows 7 x64

**Comment by sxgunchenko** [comment]
cannot reproduce with 1.5.60 version
