### ISSUE TITLE
Exclusion not applied

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/CoreLibs#1138]
https://www.gofeminin.de/shopping/katzenhaare-entfernen-s3010897.html

Visit this site with French filter. 

giphy.com/embed/CS6YxDFlrCWmA is blocked by rule in French filter:

`/^((?!(^https?):\/\/(([0-9a-z\.\-]+)\.(20mn\.fr|doyoudreamup\.com|netdna-ssl\.com|nexcesscdn\.net|wp\.com)|([0-9a-z]+\.)?disqus\.com|([a-z]+)\.(axept\.io|axeptio\.eu|beop\.io|beopinion\.com|disquscdn\.com|jokerly\.com|og4\.me)|(ajax|cdnjs)\.cloudflare\.com|(ajax|maps|storage)\.googleapis\.com|api\.(viafoura\.co|viafoura\.com)|(apis|plus|www)\.google\.com|(api|assets|cdn)\.poool\.fr|(api|de|en|fr|www)\.tipeee\.com|(api|assets)\.pinterest\.com|(api|cdn|cdn1|cdn2|cdn3|cdn4)\.wibbitz\.com|(api|static1)\.dmcdn\.net|(assets|secure\.assets)\.tumblr\.com|(beta|www)\.qiota\.com|(cdn-us|embed)\.air\.tv|(cdn\.digitrust|quantcast|static\.quantcast)\.mgr\.consensu\.org|cdn-files\.prsmedia\.fr|(cdns|cdns2|cdns\.eu1)\.gigya\.com|(embedr|widgets)\.flickr\.com|(files|player)\.qualifio\.com|(i|s)\.po\.st|(maxcdn|stackpath)\.bootstrapcdn\.com|(odb|storage|widgets)\.outbrain\.com|(platform|www)\.instagram\.com|(secure|www)\.ultimedia\.com|(staticxx|www)\.facebook\.com|(tel\.cdn|tra\.scds)\.pmdstatic\.net|api\.matchchat\.co\.uk|app\.viewdeos\.com|assets\.(afcdn\.com|reach5\.co)|build\.suggestv\.io|cdn\.([0-9a-z]+)\.nicematin\.com|cdn\.(polyfill\.io|syndication\.twimg\.com|viafoura\.net)|(cdn|trc)\.taboola\.com|code\.jquery\.com|(staticxx|www)\.facebook\.com|connect\.facebook\.net|content\.jwplatform\.com|e\.infogr\.am|embed\.waze\.com|graphcomment\.com|hap\.h-cdn\.com|images\.marmitoncdn\.org|js\.stripe\.com|jwpsrv\.com|mb\.pixel\.swello\.com|paiement\.creditmutuel\.fr|platform\.twitter\.com|player\.pippa\.io|players\.brightcove\.net|po\.st|rcijeux\.fr|s\.pinimg\.com|s\.ytimg\.com|sadmin\.brightcove\.com|scontent-rtl\.akamaized\.net|sdk\.privacy-center\.org|snapwidget\.com|ssl\.p\.jwpcdn\.com|static\.(afcdn\.com|bfmtv\.com|lephoceen\.net)|use\.edgefonts\.net|vjs\.zencdn\.net|widget\.(beopinion\.com|crowdleap\.com)|widgets\.snack-projects\.co\.uk|www\.(bloglovin\.com|dailymotion\.com|httpcs\.com|rtl\.be|stanza\.co|youtube\.com|zap-tele\.com))\/).*)$/$script,subdocument,third-party,domain=`

Adding this rule will not unblock the request:

@@||giphy.com/embed^$important

Normally exclusion rule with $important should have highest priority, but it gets ignored (also without $important).

If I take the rule and put a @@ in front of it to whitelist, it works though.

Tested on Windows 10 and latest nightly build.

**Comment by sxgunchenko** [comment]
cannot reproduce with current nightly

**Comment by BlazDT** [comment]
Seems to be working now (French filter received also an update it seems via Liste FR modifying the rule).
