### ISSUE TITLE
Change evdns to c-ares.

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#1139]
Tired of evdns bugs, we need to use something more new and maintained.

evdns_getaddrinfo -> c-ares async request
bufferevent_socket_connect_hostname -> c-ares async request (caching) + sync wait + bufferevent_socket_connect

Please also see what to do with `ag_dns_set_servers`.

**Comment by vshlobinag** [comment]
Research partially completed.

**Comment by sfionov** [comment]
Moving to 1.5+extensionsapi milestone to decide what to do.

**Comment by sfionov** [comment]
core/pull-requests/1693
