### ISSUE TITLE
@include in userscripts is ignored 

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1142]
Original issue:
https://github.com/AdguardTeam/AdguardFilters/issues/40866#issuecomment-536290080

Script with `// @include      vk.com`:
https://drive.google.com/open?id=12fD1nyDm8-m4KmxfAlLpUN036H2_pA7N

At the moment it breaks avito.ru
Not reproduced with Tampermonkey.

@TysoN-Rus

**Comment by sxgunchenko** [comment]
core/pull-requests/1539
