### ISSUE TITLE
Incorrect extended CSS rule causes that JS rules don't work

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1147]
### Steps to reproduce

1. Add these rules:
`example.org#?#body > div[class="":has(h1)`
`example.org#%#alert(1);`
2. Go here - http://example.org/

### Expected behavior

I think that JS rules should still work.
### Actual behavior

JS rules don't work.

The real case is here - https://github.com/AdguardTeam/AdguardFilters/issues/41420
It seems that this rule:
```
cosmopolitan.lt,moteris.lt,panele.lt,manonamai.lt,tavovaikas.lt,delfi.lt#?#a[href="javascript:void(-1);":-abp-has(a[title="[x] Uždaryti"])
```
from `EasyList Lithuania` is inccorect and causes that JS rules don't work.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/66027861-19f6b180-e4fc-11e9-94c7-44d4d8f52328.png)

</details>

### Your environment

* AdGuard for Windows 7.2.2943 NIGHTLY (CL 1.5.60)

**Comment by sxgunchenko** [comment]
css rules validation was improved in core/pull-requests/1860

**Comment by AdamWr** [comment]
It seems that some rules still cause that problem.
I'm not sure if I should open new issue in this repo or maybe create issue in ExtendedCSS repo - https://github.com/AdguardTeam/ExtendedCss/issues, so I'm writing comment here.

### Steps to reproduce

1. Add these rules:
```
example.org#?#body:has(div),
example.org#%#alert(1);
```
2. Go here - http://example.org/

### Expected behavior

JS rules should still work.
### Actual behavior

JS rules don't work.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/94267639-3de8a980-ff3c-11ea-88b3-956295cd7d33.png)

</details>
