### ISSUE TITLE
Rules with $popup modifier cause that blocking rules don't work

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1148]
### Steps to reproduce

1. Go here - http://sendsurl.com/PIT8M
2. Ad marked on screenshot below should be blocked:
<details><summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/29142494/66037562-300e6d00-e510-11e9-8d29-cad1486e5ae2.png)

![image](https://user-images.githubusercontent.com/29142494/66038213-c5f6c780-e511-11e9-9fa9-793929612406.png)

</details>

There are 2 iframes from `deloplen.com` and one is blocked, but second not.
In Base filter there are these rules:
```
||deloplen.com^$third-party
||deloplen.com^$popup
||deloplen.com^
```
if I disable `||deloplen.com^$popup` then both iframes are blocked.

### Steps to reproduce if link above will stop works
1. Add these rules:
`||youtube.com^`
`||youtube.com^$popup`
 2. Go here - https://www.cdaction.pl/news-56870/doom-eternal-mamy-gameplay-i-date-premiery-wideo.html

### Expected behavior

I think that iframes from `deloplen.com`/`youtube.com` should be blocked/removed.

### Actual behavior

Iframes from `deloplen.com`/`youtube.com` are not blocked/removed.

### Your environment

* AdGuard for Windows 7.2.2943 NIGHTLY (CL 1.5.60)

**Comment by ameshkov** [comment]
@sxgunchenko haven't we resolved that already? I think there was an issue with the blocking page that @timirila1 should've resolved

**Comment by sxgunchenko** [comment]
we planned for 1.6 #682

**Comment by sfionov** [comment]
> In Base Filter there are this rules:

@AdamWr 

```
||deloplen.com^$third-party
||deloplen.com^$popup
||deloplen.com^
```

This is combination with undefined behaviour - every rule for the same url and have the same priority.
So only one of them will be applied.
Please reduce such rules into one.

**Comment by ameshkov** [comment]
Huh, yeah, this is actually not a bug, it's just due to $popup rules behavior they won't block iframes.

**Comment by AdamWr** [comment]
Ok, but it is still strange that there are two iframes from `deloplen.com` and one is blocked, but second not.

>Please reduce such rules into one.

These two rules:
`||deloplen.com^$popup`
`||deloplen.com^$third-party`
are from `EasyList` and I guess that there may be more similar rules with `$popup` modifier and without it.
I will just add `||deloplen.com/afu.php?$important`

**Comment by ameshkov** [comment]
This issue is generally caused by CoreLibs limitations as it cannot distinguish main frames from iframes until the page is loaded

**Comment by Alex-302** [comment]
`$popup` is useless in this case. We need to add `$important` to all rules, if exists `$popup` rule with the same URL?
