### ISSUE TITLE
Rules with :style() are wrongly converted

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1149]
I guess it's related to this - https://github.com/AdguardTeam/CoreLibs/issues/880

### Steps to reproduce

1. Enable `AdGuard Base filter` and add these rules:
```
@@||example.com^$generichide
example.com##div > h1:style(background: red!important;)
example.com#%#AG_onLoad(function() { var el=document.body; var ce=document.createElement('div'); if(el) { el.appendChild(ce); ce.setAttribute("class", "luhb-div"); } });
```
2. Go here - http://example.com/

### Expected behavior

CSS rule should be applied only to `h1`
### Actual behavior

CSS rule is also applied to `.luhb-div`

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/66041254-bc715d80-e519-11e9-8291-a1754720882c.png)

</details>

### Your environment

* AdGuard for Windows 7.2.2943 NIGHTLY (CL 1.5.60)

**Comment by sfionov** [comment]
Yes, ## are not converted to #$#, only the content

**Comment by sxgunchenko** [comment]
@AdamWr, by the way, you can check result of the conversion in logs, if you turn on debug log level

**Comment by AdamWr** [comment]
I didn't know about that, thank you for the information.

**Comment by AdamWr** [comment]
I might be wrong, but it seems that some rules are still incorrectly converted.

Steps to reproduce
1. Add these rules:
```
@@||example.com^$generichide
example.com##a[href*="://"]:style(color: red!important;)
```
2. Go here - http://example.com/

 `a[href*="://"]` should be red, but it seems that it doesn't work.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/66931046-d2147600-f035-11e9-95d6-ee93272d55f2.png)

</details>

**Comment by ameshkov** [comment]
Most likely you are not wrong:)

**Comment by sxgunchenko** [comment]
It's not a conversion but validation issue
fixed in core/pull-requests/1565

**Comment by AdamWr** [comment]
One more issue:
`@@||example.com^$generichide`
`example.org##p:not(.test) > a:style(color: red)`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/67483478-3fdc2580-f666-11e9-8159-3792abe07c53.png)

</details>

**Comment by sxgunchenko** [comment]
> One more issue:
> `@@||example.org^$generichide`
> `example.org##p:not(.test) > a:style(color: red!important;)`
> Screenshot

resolved in core/pull-requests/1577

**Comment by AdamWr** [comment]
And maybe one more?
`@@||example.org^$generichide`
`example.org##p::before:style(content: "Test"!important; color: red!important;)`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/68516800-5baa1300-0285-11ea-8e90-05f137c27fbb.png)

</details>

Works fine with:
`example.org#$#p::before { content: "Test"!important; color: red!important; }`
so I guess it's a bug.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/68516852-84320d00-0285-11ea-8400-56e6e04ef5a5.png)

</details>

**Comment by sxgunchenko** [comment]
fixed in core/pull-requests/1595

**Comment by ameshkov** [comment]
Rule `radikal.ru#?#.render_body_main:style(margin-top: 0 !important)` should have been converted to `radikal.ru#$?#.render_body_main { margin-top: 0 !important }`, but it's not

**Comment by sxgunchenko** [comment]
core/pull-requests/1596

**Comment by sfionov** [comment]
Already tested

**Comment by AdamWr** [comment]
It seems that now rules with `:style()` don't work.
Example:
`example.org##body:style(background: red!important;)`
or
`example.org##div > h1:style(background: red!important;)`

Link - http://example.org/

AdGuard for Windows 7.4 nightly 25 (build 3209, CL 1.5.256)

**Comment by ameshkov** [comment]
@sfionov please re-test

**Comment by sxgunchenko** [comment]
fixed in core/pull-requests/1884
