### ISSUE TITLE
Change the whitelisting cookie algorithm

### ISSUE THREAD

**Issue by sxgunchenko** [AdguardTeam/CoreLibs#115]
Instead of hardcoding whitelisting cookie, we should reuse the scheme we have in Win version

**Comment by sxgunchenko** [comment]
Merged, core/pull-requests/84

**Comment by sfionov** [comment]
Isn't it break current adBlockedPage? May be we should temporarily disable this feature until adBlockedPage script knows how to handle it.

**Comment by ameshkov** [comment]
Grab the page code from the Win version and implement the logic properly.

**Comment by sfionov** [comment]
It is already implemented but Win version's page is not localized

**Comment by sfionov** [comment]
I meant "uses different localization method"

**Comment by sxgunchenko** [comment]
Fix merged, core/pull-requests/114
