### ISSUE TITLE
Rules with $mp4 modifier don't work

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1151]
For example here - [https://www.filmmodu.org/american-woman-altyazili-izle](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.filmmodu.org%2Famerican-woman-altyazili-izle)
In Turkish filter is this rule:
`||filmmodu.com/uploads/*.mp4$mp4`
and it seems that it doesn't work.
I tried also (with disabled Turkish filter and checking rules below one by one):
`||filmmodu.com/uploads/*.mp4$mp4,important`
`||filmmodu.com/uploads/*.mp4$mp4,media`
`||filmmodu.com/uploads/*.mp4$mp4,media,important`
but without success.

https://github.com/AdguardTeam/CoreLibs/issues/1146#issuecomment-537866389

* AdGuard for Windows nightly 7.2.2943 (CL 1.5.60)

**Comment by sxgunchenko** [comment]
core/pull-requests/1545
