### ISSUE TITLE
Cookie problems with a rule

### ISSUE THREAD

**Issue by northis** [AdguardTeam/CoreLibs#1153]
These sites get stuck on anti-ddos check with rule `$cookie=/blcrm|bltsr|yc|yp|adb/`:
https://forums.mydigitallife.net/ 
https://www.torrentday.com/login.php#top

See https://github.com/AdguardTeam/AdguardForWindows/issues/3002

And some other sites, see https://github.com/AdguardTeam/AdguardForWindows/issues/3003

**Comment by sxgunchenko** [comment]
cannot reproduce with current nightly
