### ISSUE TITLE
$empty modifier does not block whole page

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1154]
`example.org$emprty` is converted to 
```
example.org$redirect=nooptext,image,stylesheet,script,object,font,media,xmlhttprequest,websocket,other
```
`document` content type cannot be added.

### Actual behavior: 

HTML is not blocked.

### Expected behavior:

Page content is empty.

AdGuard 7.2.2946

**Comment by ameshkov** [comment]
Let's make it as simple as possible then:

* `empty` -> `$redirect=nooptext`
* `mp4` -> `$redirect=noopmp4-1s,media`

**Comment by sxgunchenko** [comment]
@ameshkov so, should we allow redirect rules without any content modifiers? that's why empty is converted to rule with all those modifiers

**Comment by ameshkov** [comment]
@sxgunchenko yes

**Comment by sxgunchenko** [comment]
core/pull-requests/1552
