### ISSUE TITLE
gall.dcinside.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1155]
@adguard-bot commented on [Wed Oct 02 2019](https://github.com/AdguardTeam/AdguardFilters/issues/41606)

### Issue URL (Incorrect Blocking)
[https://gall.dcinside.com/mgallery/board/write/?id=hackslash](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fgall.dcinside.com%2Fmgallery%2Fboard%2Fwrite%2F%3Fid%3Dhackslash)
### Comment
> 사이트에서 이미지 올리려고 시도하면 올라가지 않고, 계속 시도해보면 충돌났다고 보호가 중지가됩니다.
> 
> 엣지브라우저는 켜도 잘되는데 크롬브라우져는 안됩니다.
> --
> 하단 정보는 자동으로 생성되었습니다. 삭제하지 마세요.
> 
> Referrer:
> https://gall.dcinside.com/mgallery/board/write/?id=hackslash
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
> https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/fk60Yax.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/Ym1uJrw.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 7.2.2936.0
Browser: | Chrome
AdGuard driver: | WFP
Filters: | AdGuard Base,<br>List-KR
Other extensions used: | Kaspersky

**Comment by AdamWr** [comment]
Steps to reproduce:
1. Click here:
![image](https://user-images.githubusercontent.com/29142494/66210533-5e2fb080-e6ba-11e9-8c67-46a941c19ee2.png)
2. Then click here:
![image](https://user-images.githubusercontent.com/29142494/66210571-743d7100-e6ba-11e9-8993-17eeae1baa65.png)
3. Choose image and wait as it will be uploaded.
Then AdGuard will show error
![image](https://user-images.githubusercontent.com/29142494/66210716-c5e5fb80-e6ba-11e9-9d79-a1d04c8e6cca.png)

**Comment by sfionov** [comment]
ERROR, AdguardSvc, 16, 04.10.2019 18:35:49.419, Adguard.Core.Common.Logging.CoreLoggerAdapter | assert: C:\Users\Bamboo\bamboo-agent-home\xml-data\build-dir\CL-WL12-JOB1\proxy\filter\src\AGProxyFilter.cpp:693 assertion (0) failed!

**Comment by vshlobinag** [comment]
core/pull-requests/1568
