### ISSUE TITLE
AdGuard does not filter traffic when using Shadowsocks Global mode

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/CoreLibs#1157]
@Chinaski1 commented on [Thu Oct 03 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/3005)

After updating to version 7.2. AdGuard completely stops filtering traffic when connected to Shadwosocks proxy in Global mode.
This problem was not observed in version 7.1.

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/66119305-12f59f00-e5e1-11e9-8db4-8d2f32df7cf2.png)

</details>

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/66119332-1db03400-e5e1-11e9-9bd8-6ba617dfd7c4.png)

</details>

### Your environment

* Environment name and version: [ShadowsocksR](https://github.com/shadowsocks/shadowsocks-windows/releases/tag/4.1.7.1) 4.1.7.1
* Operating system and version: Windows 10 / 1809 (17763.737)
* AdGuard: 7.2.2943  (CL 1.5.60)

**Comment by sfionov** [comment]
@TheHasagi Does it happen on the latest nightly?

**Comment by Eugene-Savenko** [comment]
User (2330428) states that it does happen on the latest nightly.
