### ISSUE TITLE
AdGuard crashes when pinging a domain via PingTools

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1158]
@akmLaVx commented on [Thu Sep 26 2019](https://github.com/AdguardTeam/AdguardForAndroid/issues/3086)

### Repro
1. Install PingTools from https://pingtools.org/
2. Attempt to ping any website (eg. example.com)
3. AdGuard crashes

### Issue Details

- **AdGuard version:**
  - 3.2.150 (Release)
- **Filtering mode:**
  - Local VPN, high-quality
- **Device:**
  - Motorola Moto G (5)
- **Operating system and version:**
  - Android 8.1.0
- **Root access:**
  - No

### Expected Behavior

PingTools pings the website, AdGuard works as usual

### Actual Behavior

PingTools pings the website, AdGuard crashes

### Additional Information

Logs: 2321485

---

@Chinaski1 commented on [Thu Sep 26 2019](https://github.com/AdguardTeam/AdguardForAndroid/issues/3086#issuecomment-535427896)

Log in *NCloud*
**Time: 16:17**

**Comment by sfionov** [comment]
Issue moved to [AdguardTeam/AdguardForAndroid #3120](https://github.com/AdguardTeam/AdguardForAndroid/issues/3120) via [**ZenHub**](https://www.zenhub.com/)

**Comment by artemiv4nov** [comment]
we need to implement some methods to get a system limit of open descriptors.
