### ISSUE TITLE
Implement API for working with the native browser assistant

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#1159]
## Implement browser API function in the CoreApi
1. Add a specified rule
2. remove a specified rule
3. match rules against the specified url
4. is filtering enabled / change filtering state
5. ~~is https filtering enabled / change https filtering state~~

## Implement function for getting the original cert for the specified domain and ip
Proposed table schema:

Table1: certs
Table2: original_certs
Table3: domain_certs
domain_name, ip, cert_id, original_cert_id

**Comment by sfionov** [comment]
Moved to milestone v1.5+extension-api
