### ISSUE TITLE
rsload.net is not filtered in Firefox due to TLS error

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1160]
### Steps to reproduce

1. Run Firefox 70
2. Open rsload.net

### Actual behavior

`PR_END_OF_FILE_ERROR` on the first visit. After that the site is added to HTTPS exclusions.

<details><summary>Screenshot:</summary> 

![image](https://user-images.githubusercontent.com/8361299/66464127-0cef3a80-ea87-11e9-862c-a46e19b8e1bf.png)

 </details>

### Logs:
[logs.zip](https://github.com/AdguardTeam/CoreLibs/files/3706271/logs.zip)

Windows 7 x64, AdGuard 7.2.2946 (CL 1.5.75)

Not sure, if it is the same issue https://github.com/AdguardTeam/CoreLibs/issues/874

**Comment by ameshkov** [comment]
Yeah, this is a duplicate. Reopened 874
