### ISSUE TITLE
The BrowserApi request shouldn't be set as bad request in case of forbidden header 

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#1163]
At this moment, if the forbidden header (https://fetch.spec.whatwg.org/#forbidden-header-name) is presented in the browser-API's request, we set such a request as a "400-BAD_REQUEST". This behavior is not accepted due to the fact, it breaks some well-known scripts (https://github.com/AdguardTeam/AdguardForWindows/issues/2937). Instead of this, we can simply remove such headers from the request and let the scripts work as expected.

**Comment by sxgunchenko** [comment]
core/pull-requests/1566
