### ISSUE TITLE
adguard urlfilter urlfilter: match_referrer(): Couldn't parse referer 'file://' and extract_domains(): Duplicate domain

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1168]
@markusg2 commented on [Mon Oct 14 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/3029)

### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

i have this error my oldest log is from 05.10.2019 and the newest from today, in all logs i have this error
and dublicate domain errors to.
it looks like the first errors are in
INFO, AdguardSvc, 48, 05.10.2019 0:11:10.694, Adguard.Core.Common.Logging.CoreLoggerAdapter | AGProxyFilter: Loading rules, listId=2
<details><summary>Screenshot:</summary>
WARNING, AdguardSvc, 16, 05.10.2019 0:00:06.338, Adguard.Core.Common.Logging.CoreLoggerAdapter | urlfilter: match_referrer(): Couldn't parse referer 'file://'
WARNING, AdguardSvc, 48, 05.10.2019 0:11:10.812, Adguard.Core.Common.Logging.CoreLoggerAdapter | urlfilter: extract_domains(): Duplicate domain 'mylink.how' in the options of rule @@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=mylink.how|mylink.how
WARNING, AdguardSvc, 48, 05.10.2019 0:11:11.555, Adguard.Core.Common.Logging.CoreLoggerAdapter | urlfilter: extract_domains(): Duplicate domain 'thepiratebay.bet' in the options of rule /storage/*.js?_=$
'urbanproxy.eu
WARNING, AdguardSvc, 48, 05.10.2019 0:11:11.555, Adguard.Core.Common.Logging.CoreLoggerAdapter | urlfilter: extract_domains(): Duplicate domain 'pirateproxy.click' in the options of rule /storage/*.js?
WARNING, AdguardSvc, 48, 05.10.2019 0:11:11.555, Adguard.Core.Common.Logging.CoreLoggerAdapter | urlfilter: extract_domains(): Duplicate domain 'thepiratebay.bet' in the options of rule /static/img/download-top.png
WARNING, AdguardSvc, 48, 05.10.2019 0:11:11.555, Adguard.Core.Common.Logging.CoreLoggerAdapter | urlfilter: extract_domains(): Duplicate domain 'thepiratebay.blue' in the options of rule /static/img/download-top.png

INFO, AdguardSvc, 48, 05.10.2019 0:11:13.311, Adguard.Core.Common.Logging.CoreLoggerAdapter | AGProxyFilter: Loading rules, listId=3
there are also dublicate domain errors
WARNING, AdguardSvc, 48, 05.10.2019 0:11:13.472, Adguard.Core.Common.Logging.CoreLoggerAdapter | urlfilter: extract_domains(): Duplicate domain 'picocurl.com' in the options of rule /index/ping^$domain=
WARNING, AdguardSvc, 48, 05.10.2019 0:11:13.472, Adguard.Core.Common.Logging.CoreLoggerAdapter | urlfilter: extract_domains(): Duplicate domain 'picocurl.com' in the options of rule /callback/*$domain=
WARNING, AdguardSvc, 48, 05.10.2019 0:11:13.512, Adguard.Core.Common.Logging.CoreLoggerAdapter | urlfilter: extract_domains(): Duplicate domain 'eugene.kaspersky.de' in the options of rule @@||google-analytics.com/analytics.js$domain=
INFO, AdguardSvc, 48, 05.10.2019 0:11:13.522, Adguard.Core.Common.Logging.CoreLoggerAdapter | AGProxyFilter: Loading rules, listId=4
WARNING, AdguardSvc, 48, 05.10.2019 0:11:13.672, Adguard.Core.Common.Logging.CoreLoggerAdapter | urlfilter: extract_domains(): Duplicate domain 'foxtrot.com.ua' in the options of rule @@||yandex.st/share/share.js$domain=

other warning 
INFO, AdguardSvc, 48, 05.10.2019 0:11:10.694, Adguard.Core.Common.Logging.CoreLoggerAdapter | AGProxyFilter: Loading rules, listId=2
WARNING, AdguardSvc, 48, 05.10.2019 0:11:10.840, Adguard.Core.Common.Logging.CoreLoggerAdapter | urlfilter: parse_rule(): Rule '@@$domain=rapidvideo.com,webrtc,websocket' is webrtc, we do not support it yet
INFO, AdguardSvc, 48, 05.10.2019 0:11:14.160, Adguard.Core.Common.Logging.CoreLoggerAdapter | AGProxyFilter: Loading rules, listId=101

WARNING, AdguardSvc, 48, 05.10.2019 0:11:14.559, Adguard.Core.Common.Logging.CoreLoggerAdapter | urlfilter: parse_rule(): Rule '$webrtc,domain=ibit.to' is webrtc, we do not support it yet
WARNING, AdguardSvc, 48, 05.10.2019 0:11:14.559, Adguard.Core.Common.Logging.CoreLoggerAdapter | urlfilter: parse_rule(): Rule '$webrtc,domain=hdmoza.com' is webrtc, we do not support it yet
WARNING, AdguardSvc, 48, 05.10.2019 0:11:14.564, Adguard.Core.Common.Logging.CoreLoggerAdapter | urlfilter: parse_rule(): Rule '$webrtc,domain=itdmusic.com|itdmusic.in' is webrtc, we do not support it yet
WARNING, AdguardSvc, 48, 05.10.2019 0:11:14.564, Adguard.Core.Common.Logging.CoreLoggerAdapter | urlfilter: parse_rule(): Rule '$webrtc,domain=blacklistednews.com' is webrtc, we do not support it yet
WARNING, AdguardSvc, 48, 05.10.2019 0:11:14.569, Adguard.Core.Common.Logging.CoreLoggerAdapter | urlfilter: parse_rule(): Rule '$webrtc,domain=uptobox.com' is webrtc, we do not support it yet
WARNING, AdguardSvc, 48, 05.10.2019 0:11:14.569, Adguard.Core.Common.Logging.CoreLoggerAdapter | urlfilter: parse_rule(): Rule '$webrtc,domain=m4ufree.com|m4ufree.tv' is webrtc, we do not support it yet
WARNING, AdguardSvc, 48, 05.10.2019 0:11:14.569, Adguard.Core.Common.Logging.CoreLoggerAdapter | urlfilter: parse_rule(): Rule '$webrtc,websocket,xmlhttprequest,domain=

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59)
* Operating system and version: (e.g. Windows 10, v.1703, build 15063.413)

**Comment by sfionov** [comment]
We should review loglevels in filters and doesn't use fixed log level for them. These warnings should be in debug log only if user turned on Debug logging.
