### ISSUE TITLE
Some rules with the $empty modifier do not work

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1169]
@dba007 commented on [Fri Sep 27 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2992)

ag version:7.2.2937

add this 5 rules：

||ctfile.com/iz.*$empty
/iz.php*$empty
||mydisplay.ctfile.com/iz.php*$empty
||mydisplay.ctfile.com/iz.*$empty
||ctfile.com/iz.php*$empty

open filter log window.

open url: https://mydisplay.ctfile.com/iz.php?i=760

Not matched by any one rule.

---

@ameshkov commented on [Mon Oct 07 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2992#issuecomment-538792461)

Yep, there's a bug indeed in CoreLibs, it will be fixed in the next update

---

@dba007 commented on [Wed Oct 23 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2992#issuecomment-545506494)

This bug still exists.

adguard version：7.3 nightly 3 (build 2958, CL 1.5.93)
CoreLibs：1.5.93

**Comment by sxgunchenko** [comment]
Cannot reproduce with current nightly version.
@dba007 are you sure that the site is filtered? Some tls error could have happened, or you have some rules which disable those `$empty` ones. To exclude tls error - check in browser that it's AdGuard's certificate in certificate details menu. To exclude other rules - disable all filters except the user filter which contains those `$empty` rules only.

Is the issue reproducible on other sites?
For example, try to add the rule `||example.org^$empty` and go to example.org. It should be blank.

**Comment by dba007** [comment]
I tested it again, and tls looked like it didn't seem to be a problem. conclusion as below:

[https://yadi.sk/i/rjCXjOl8d4-47w](https://yadi.sk/i/rjCXjOl8d4-47w)
[https://yadi.sk/i/zKo6OLPWrfZWxA](https://yadi.sk/i/zKo6OLPWrfZWxA)
[https://yadi.sk/i/Q1Xr_PcxLNxXGw](https://yadi.sk/i/Q1Xr_PcxLNxXGw)

I tested another website as follows:
[https://yadi.sk/i/wDN0vcAMpV5lIQ](https://yadi.sk/i/wDN0vcAMpV5lIQ)
[https://yadi.sk/i/Qg9JQkL0omHPAQ](https://yadi.sk/i/Qg9JQkL0omHPAQ)
[https://yadi.sk/i/Bf2oUn9ySkh4WQ](https://yadi.sk/i/Bf2oUn9ySkh4WQ)
[https://yadi.sk/i/DYerkEXjcg7hGA](https://yadi.sk/i/DYerkEXjcg7hGA)

of course, the $empty rules have not taken effect, but why is there a rule to change? I obviously did not set the $redirect rule.

I tested the website of the normal http protocol and it does not take effect.
test url:http://h5.analytics.126.net/news/c

[https://yadi.sk/i/j0kgN-BFJxnr2g](https://yadi.sk/i/j0kgN-BFJxnr2g)
[https://yadi.sk/i/oGVndtWRxJlyPA](https://yadi.sk/i/oGVndtWRxJlyPA)

os:win7
adguard: 7.3 nightly 4 (build 2959, CL 1.5.94)

Is the $empty rule broken or does not support the win7 system?  A previous version of the $empty rule can be intercepted correctly.

@sxgunchenko @ameshkov

**Comment by sxgunchenko** [comment]
@dba007 it's ok that the `$empty` rules are reported as `$redirect`, because they are converted internally into the `$redirect=nooptext`

I still can't reproduce the issue. One more thing we can exclude is the browser cache. Have you tried to clean the cache or test those sites in the incognito mode?

And there is one thing we can check: try to add the following rule `||h5.analytics.126.net^$document`, and go to http://h5.analytics.126.net/news/c. A blocking page should appear.

**Comment by dba007** [comment]
I use the same adguard version, the same rules on the windows 10 system test can be intercepted normally. Basically, it can be determined that $empty rule does not support Windows 7 system.

ps: rule ||h5.analytics.126.net^$document 
I can see a blocking page,$document

**Comment by dba007** [comment]
I tested it out, and $empty conflicts with $replace.
If there is only one $empty rule, then access can be blocked. If another $replace rule takes effect at the same time, the $empty rule will automatically expire.

test add one rule:
||ctfile.com/iz.php^$empty
open: https://mydisplay.ctfile.com/iz.php?i=760
access can be blocked normally and the rules are valid.

add two rule:
||ctfile.com/iz.php^$empty
||ctfile.com^$replace=/aaaa/bbbbb/
open: https://mydisplay.ctfile.com/iz.php?i=760
the $empty rule is invalid.

I think the priority of the blocking rule should be higher than other rules, or let the visit go through all the matching rules. When the $empty rule is encountered, the other rules can be aborted.

@sxgunchenko @ameshkov

**Comment by sxgunchenko** [comment]
In that case it's a specified behavior. If any replace rule is matched, the blocking rule will have no effect if few other conditions are not met. Please, take a look at this https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#replace-modifier for more detailed explanation.

**Comment by ameshkov** [comment]
@dba007 you can always use the `important` modifier to control the priority of the rules:
`||ctfile.com/iz.php^$empty,important`
