### ISSUE TITLE
Include OpenSSL asm code into build

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#117]

**Comment by TPS** [comment]
Does this mean it this will run on only certain ARM versions properly &/or not x86?

**Comment by sfionov** [comment]
No, it means that on some platforms asm code will be used to speedup, on other platforms cross-platform code will be used.

**Comment by sfionov** [comment]
Fixed in core/pull-requests/117

**Comment by sfionov** [comment]
OpenSSL asm code for ARM doesn't compile with latest NDK, ARM64 works incorrectly.
Seems that Clang isn't a good compiler for OpenSSL asm code. Lets try with -fno-integrated-as

**Comment by sfionov** [comment]
A long, long time ago this was fixed.
