### ISSUE TITLE
Add more information on the TLS properties to the filtering log

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1171]
This might require adding a new callback (onSessionStarted or smth like this).
Or we could simply pass it to onBeforeRequest?

Here's what makes sense to add there:

1. TLS version
2. Selected cipher
3. Original certificate (I know we're going to expose it through the browser assistant, but having it in the log is also useful)

What else?

**Comment by sfionov** [comment]
IMHO displaying selected cipher in browser assistant will be useful too, because browsers shows that.

**Comment by ameshkov** [comment]
Well, we can simply use the same cipher for the browser<->AG connection

**Comment by ameshkov** [comment]
Ah, makes sense

**Comment by billkewl** [comment]
Is Adguard able to generate ECDSA certs now? after CoreLibs ver. 1.15.25?  
https://github.com/AdguardTeam/CoreLibs/issues/360

If so. How to regenerate a new cert?
