### ISSUE TITLE
ERR_HTTP2_PROTOCOL_ERROR with partial responses (status=206)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1181]
Reproducible here and there. For instance, I often encounter it for large videos on dump.video

**Comment by AdamWr** [comment]
I see similar error on this website - [https://govid.co/play/00867176](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://govid.co/play/00867176)

Video doesn't work even if all modules all disabled.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/69414180-8169fa00-0d12-11ea-93e8-bd0ef6c1f66d.png)

</details>

AdGuard for Windows 7.3 nightly 11 (build 2984, CL 1.5.130)
