### ISSUE TITLE
fuqer.com [NSFW] - broken website

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1182]
It seems that video player on NSFW `fuqer.com` doesn't work/load if there is any cosmetic rule applied.

### Steps to reproduce

1. Disable all filter lists
2. Add any cosmetic rule to user filter, for example:
`fuqer.com###TEST`
3. Go here [NSFW] [https://www.fuqer.com/videos/busty-cougar-milf-knows-how-to-seduce-a-boy-to-fuck-4785.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.fuqer.com/videos/busty-cougar-milf-knows-how-to-seduce-a-boy-to-fuck-4785.html)

### Expected behavior

Video player should loads/works correctly.

### Actual behavior

Video player doesn't load/work.

<details><summary>Screenshot without any comsetic rules:</summary>

![image](https://user-images.githubusercontent.com/29142494/68472700-587d3b80-0221-11ea-8df1-bc6a6d45ae5d.png)

</details>

<details><summary>Screenshot with cosmetic rule:</summary>

![image](https://user-images.githubusercontent.com/29142494/68472775-82366280-0221-11ea-92fd-3ae588fe594b.png)

</details>

### Your environment

* AdGuard for Windows Version 7.3 nightly 6 (build 2970, CL 1.5.109)

**Comment by sfionov** [comment]
Merged into #1221
