### ISSUE TITLE
map.baidu.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1183]
@adguard-bot commented on [Fri Nov 08 2019](https://github.com/AdguardTeam/AdguardFilters/issues/43706)

### Issue URL (Incorrect Blocking)
[https://map.baidu.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fmap.baidu.com%2F)
### Comment
Username: @9o8i7u
> 
> --
> 以下信息是自动产生的。请不要删除它。
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
> https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/tNS68vz.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/to4FzeC.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 7.2.2936.0
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Self-destructing third-party cookies (0)
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base
Other extensions used: | 卡巴斯基

**Comment by AdamWr** [comment]
Similar issue to this one - https://github.com/AdguardTeam/CoreLibs/issues/1182

Adding any cosmetic filter causes that this element in right top corner is broken.

Steps to reproduce:
1. Disable all filter lists
2. Add any cosmetic rule to user filter, for example:
`map.baidu.com###TEST`
3. Go here - https://map.baidu.com/

**Comment by sfionov** [comment]
Merged into #1221
