### ISSUE TITLE
err_response_headers_truncated at nj.myaccount.pseg.com

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1188]
@adguard-bot commented on [Wed Nov 13 2019](https://github.com/AdguardTeam/AdguardFilters/issues/43960)

### Issue URL (Incorrect Blocking)
[https://nj.myaccount.pseg.com/user/login](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fnj.myaccount.pseg.com%2Fuser%2Flogin)
### Comment
> The URL/page shown in that failure is also what I use to log in.  I simply click on that line, it may put https:// in front of that address, and I get back to the login screen.  I enter my credentials, and get that failure screen.
> 
> I block adguard for 30 seconds, still fail.
> 
> I added a user filter from the program ("@@||nj.myaccount.pseg.com^$important,document,~extension", was done automatically by my disabling blocking on that site), then manually copied from that and added "@@||pseg.com^" and "@@||pseg.com", still failed, showing that page.
> 
> When I disable adguard it works, so it's something with your program.  And I don't know if there's some log that can show that maybe there was an intermediate page that they went to that got stopped. It goes to another page starting with the same info above -- full URL: https://nj.myaccount.pseg.com/myaccountdashboard?SelectAccountPage=1
> 
> But only with adguard completely blocked.  And I think my rule should've disregarded that page.
> 
> I'm really confused since disabling for 30 seconds should be the same as turning it off, for 30 seconds, and it fails within that time.
> --
> The information below is automatically generated. Do not delete it.
> 
> Referrer:
> https://nj.myaccount.pseg.com/user/login
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
> https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/fTjr2Dj.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/16hwFcf.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 7.2.2936.0
Browser: | Chrome
AdGuard driver: | TDI
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Language-specific:</b><br/> EasyList Italy, <br/>Adblock List for Finland, <br/>AdGuard Russian, <br/>AdGuard Japanese
Other extensions used: | mcafee

**Comment by sfionov** [comment]
Can't reproduce since website is down
