### ISSUE TITLE
Can't log in on 99% of the sites with the latest nighly

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1192]
@skipik commented on [Sat Nov 16 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/3069)

### Steps to reproduce

1. Try to log in on github for example
2.
3.
4.

### Expected behavior

Success log in
### Actual behavior

Something goes wrong

<details><summary>Screenshot:</summary>

![111](https://user-images.githubusercontent.com/24621645/68995486-8147a580-089f-11ea-9281-3fc351373b44.png)

</details>

### Your environment

* Environment name and version: ANY browser
* Operating system and version: Windows 10 1909 x64

Please fix it ASAP!

---

@skipik commented on [Sat Nov 16 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/3069#issuecomment-554647595)

Сломалось в найтли 8, до этого всё было ок!

---

@skipik commented on [Sat Nov 16 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/3069#issuecomment-554648011)

Отправил логи на почту devteam.

---

@skipik commented on [Sat Nov 16 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/3069#issuecomment-554649679)

Помогает отключение правила:
`$cookie=/blcrm|bltsr|yc|yp|adb/`
в пользовательском фильтре.
Если же правило включено, то не получается зайти на сайты.

---

@skipik commented on [Sat Nov 16 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/3069#issuecomment-554650322)

https://github.com/AdguardTeam/CoreLibs/issues/1153
Уже заводили по моему репорту, оно опять вернулось. :-(

---

@skipik commented on [Sat Nov 16 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/3069#issuecomment-554650513)

Само правило давно давал Алекс против директа на яндексе. Оно может уже и не актуально, но я оставил по привычке в пользовательском фильтре.
До найтли 8 вход на сайты оно не ломало точно.

**Comment by skipik** [comment]
Any news about this bug?

**Comment by ameshkov** [comment]
@skipik эм, да пофиксили же! неужто повторяется сейчас?

**Comment by skipik** [comment]
@ameshkov А, действительно. Я просто не включал это правило с тех времён, видя, что этот инц ещё открыт. Сейчас включил и всё ок, проблема не повторяется. Спасибо! :-)
