### ISSUE TITLE
AdGuard breaks SVG at mail.yahoo.com

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1193]
AdGuard 7.3 nightly 6
Enabled Base filter only.

With Base filter:
<details>

![image](https://user-images.githubusercontent.com/8361299/69047222-55453500-0a03-11ea-8d08-cf2a6fb6beb3.png)

</details>

Without Base filter:
<details>

![image](https://user-images.githubusercontent.com/8361299/69047256-6c842280-0a03-11ea-89f3-d01231a823ad.png)

</details>

This is caused by element hiding rules. `@@||mail.yahoo.com^$elemhide` helps. Disabling domain specific element hiding rules does not fix this issue.

**Comment by Alex-302** [comment]
Steps to reproduce:
1. Sign in to mail.yahoo.com
2. Disable all filters and add following rule to User Filter:
`##.random_elemhide_rule`
3. Refresh a tab and click on print icon
![image](https://user-images.githubusercontent.com/8361299/69049004-86bfff80-0a07-11ea-911a-a869f10ac1bf.png)

**Comment by sfionov** [comment]
Merged into #1221
