### ISSUE TITLE
`$rewrite=abp-resource:` rules are not properly converted

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#1194]
We should convert only `$rewrite=abp-resource:` rules ("internal resource rewrite rule") and drop other `$rewrite` rules since we don't support them yet (see https://github.com/AdguardTeam/CoreLibs/issues/368).

Now `$rewrite=1x1-transparent-gif` is converted to `$redirect=1x1-transparent-gif` which is incorrect because it is not "internal resource $rewrite rule".
The proper behaviour is:
`$rewrite=abp-resource:1x1-transparent-gif` is converted to `$redirect=1x1-transparent-gif`

**Comment by sxgunchenko** [comment]
core/pull-requests/1605
