### ISSUE TITLE
Some scriptlets don't work

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1195]
It seems that some scriptlets don't work, for example:
`#%#//scriptlet("googletagservices-gpt")`
`#%#//scriptlet("google-analytics")`

### Steps to reproduce

1. Add this rule:
`example.org#%#//scriptlet("googletagservices-gpt")`
2. Go here - http://example.org/

### Expected behavior

If I check `googletag` in console then it should returns some functions.

### Actual behavior

 `googletag` is undefined.

<details><summary>Screenshot with app:</summary>

![image](https://user-images.githubusercontent.com/29142494/69143262-d1ee1700-0ac8-11ea-9fdf-aa6fa464918c.png)

</details>

<details><summary>Screenshot with extension:</summary>

![image](https://user-images.githubusercontent.com/29142494/69143104-89cef480-0ac8-11ea-9498-1922a34642f7.png)

</details>

### Your environment

* AdGuard for Windows 7.3 nightly 8 (build 2976, CL 1.5.122)

**Comment by ameshkov** [comment]
@sxgunchenko Let's update scriptlet resources

**Comment by TheHasagi** [comment]
Invalid scriptlet.
