### ISSUE TITLE
AdGuard Asistant doesn't work

### ISSUE THREAD

**Issue by muhammedfurkan** [AdguardTeam/CoreLibs#1197]
I updated new version 7.3 nightly 9 (build 2979, CL 1.5.127)

after the update Asistant doesnt work. And dissappear the browser corner.

[https://i.imgur.com/VYnMCTa.jpg](url)

[https://i.imgur.com/khfKRpb.jpg](url)

**Comment by ameshkov** [comment]
Please update to nightly 10, the issue is resolved there
