### ISSUE TITLE
[Android] CL 1.5.109 breaks ICMP test

### ISSUE THREAD

**Issue by admitrevskiy** [AdguardTeam/CoreLibs#1209]
Steps to reproduce:
- Make sure you use IPv6 network
- Install AG for Android with CL 1.5.102
- Go to `https://ipv6-test.com`

ICMP test is successful

- Install AG for Android with CL 1.5.109
- Go to `https://ipv6-test.com`

ICMP test fails

Looks like it was broken in one of the following merges:
#1583
#1587

**Comment by sfionov** [comment]
https://v6.ipv6-test.com:8443/?callback=jQuery11130741708292859308_1575019630945&_=1575019630954

**Comment by sfionov** [comment]
core/pull-requests/1639
