### ISSUE TITLE
Cookie blocking

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1213]
@optomux commented on [Mon Dec 09 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/3114)

Using the latest Nightly. It seems Adguard won't block cookies.
I've tried using multiple things.

> ||youtube.com^$cookie=/.+/
> ||www.youtube.com^$cookie
> ||youtube.com^$cookie

**Comment by optomux** [comment]
You can verify the result in Chrome Cookie Settings.

**Comment by sfionov** [comment]
core/pull-requests/1641

**Comment by sfionov** [comment]
Cookie rules are still applied incorrectly to __Secure- and __Host- cookies.

__Secure- should have Secure flag.
__Host- should have Secure flag and should not have a host (it is always the current host, not subdomains)

**Comment by ameshkov** [comment]
Let's fix it then

**Comment by optomux** [comment]
Hmm no. I did test it with 
`||youtube.com^$cookie=/.+/`
`||www.youtube.com^$cookie`
`||youtube.com^$cookie`

**Comment by optomux** [comment]
This will have to wait. Uninstalled.

**Comment by optomux** [comment]
![Clipboard02](https://user-images.githubusercontent.com/10778276/71196662-8af26d80-2290-11ea-8417-680cadce6e65.jpg)

**Comment by optomux** [comment]
It seems can close this now?

**Comment by ameshkov** [comment]
Yeah, today's nightly comes with the fix.

Don't close the issue, though. We have a different internal process with Github issues, this one is currently in the "Review/QA" stage.

**Comment by optomux** [comment]
Aha. Okay.

**Comment by optomux** [comment]
Fixed? Don't think so.
