### ISSUE TITLE
Adguard.svc has stopped when you using Bookmark sidebar extension

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1214]
@Chinaski1 commented on [Mon Dec 09 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/3116)

### Steps to reproduce

1. Download [Bookmark Sidebar](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fchrome.google.com%2Fwebstore%2Fdetail%2Fbookmark-sidebar%2Fjdbnofccmhefkmjbkkdkfiicjkgofkdh) extension for Chrome browser
2.  After installing the application, the adguard.svc service is reset
3. Looks like it happens after clicking on the links: 
- [Here](https://extensions.blockbyte.de/changelog/bs?lang=fr) 
- [And here](https://extensions.blockbyte.de/privacy/bs?lang=fr)
4. Need to Add this domain to exceptions **extensions.blockbyte.de** to avoid the issue

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/70435125-0f760c80-1a97-11ea-9695-3a24ed9866f3.png)

</details>

### Customer ID 

From [AdGuard Forum](https://forum.adguard.com/index.php?threads/resvoled-adguard-service-stop-working.36127/#post-192391)
**Logs in NCloud**

### Your environment

* Environment name and version:  Chrome  78.0.3904.108 (Official Build) (64-bit)
* Operating system and version: Windows 10 (1809)  / AdGuard 7.3 nightly (3013, CL 1.5.141)

**Comment by sfionov** [comment]
core/pull-requests/1640
