### ISSUE TITLE
Блокируются интерактивные элементы YouTube

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/CoreLibs#1215]
На 7-й ветке блокируются интерактивные элементы видео YouTube: конечные заставки, логотипы каналов, похожие видео...

![1500269581154973391](https://user-images.githubusercontent.com/50718960/70478561-5b9f6c00-1aec-11ea-8840-2ba117189e52.png)
![firmennyiy-stil-youtube](https://user-images.githubusercontent.com/50718960/70478570-5cd09900-1aec-11ea-9275-8d8212ccbe8d.jpg)
![1503577700161855606](https://user-images.githubusercontent.com/50718960/70478634-8b4e7400-1aec-11ea-99d2-ab3c43feefcd.png)

**Comment by ameshkov** [comment]
Фильтр раздражителей включен? Он это все блокирует

**Comment by zubrRB** [comment]
Включен, но в v6.4 эти элементы почему-то не блокировались.

**Comment by ameshkov** [comment]
А по идее должны были:)

**Comment by zubrRB** [comment]
Да, в шестёрке на сервисах Google отсутствовал значок помощника. Из-за чего в том числе на YouTube просто не вся реклама (раздражители) фильтровалась. Спасибо, закрываю.
