### ISSUE TITLE
Add navigator.doNotTrack to stealth script

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [AdguardTeam/CoreLibs#1217]
Feature: stealth mode , option for injected do not track http, https header

**Comment by ameshkov** [comment]
Why? But it's already there

**Comment by Disqu3-mirOir-qt** [comment]
https://hidester.com/browser-fingerprint/

**Comment by Disqu3-mirOir-qt** [comment]
Do Not Track enabled (via HTTP headers):No Do Not Track

**Comment by sfionov** [comment]
Not our bug, we set DNT header, but site doesn't show it.

**Comment by ameshkov** [comment]
Well, what's wrong with `navigator.doNotTrack` then? It should've been overriden by us as well

**Comment by vshlobinag** [comment]
We send HTTP header DNT. Check on other site https://browserleaks.com/donottrack

On Safari this site https://hidester.com/browser-fingerprint/ doesn't work correctly, in other browsers it shows HTTP DNT incorrectly (sometimes on, sometimes off).
