### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION_READ in AGProxySession::processFilteredBody

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#1218]
https://sentry.adguard.com/adg/adguard-windows/issues/34956/?query=is:unresolved

**Comment by adbuker** [comment]
Can be related to https://sentry.adguard.com/adg/adguard-windows/issues/33085

**Comment by adbuker** [comment]
Seems, the issue is still here https://sentry.adguard.com/adg/adguard-windows/issues/51267

**Comment by sfionov** [comment]
This event is about 6.3

**Comment by sfionov** [comment]
*7.3
