### ISSUE TITLE
TP-Link web interface issue

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1219]
@adguard-bot commented on [Fri Dec 13 2019](https://github.com/AdguardTeam/AdguardFilters/issues/45912)

### Issue URL (Incorrect Blocking)
[http://192.168.0.1](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2F192.168.0.1)
### Comment
> При включенной защите адгард страница роутера глючит, медленно прогружается иногда не загружается совсем, а иногда частично. Это по wifi. По проводу все ок. И по wifi на компе тоже хуже грузит заметил. При чем на разных роутерах. При выкл адгарде все ок.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/rKbJuKy.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/liOY9TG.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 9
AdGuard version: | 3.3 beta 2 (102)
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-speed
HTTPS filtering: | enabled
DNS requests blocking: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Other:</b><br/> AdGuard Experimental<br/><br/><b>Language-specific:</b><br/> AdGuard Russian

---

@Alex-302 commented on [Mon Dec 16 2019](https://github.com/AdguardTeam/AdguardFilters/issues/45912#issuecomment-565981978)

Можете оставить свои реквизиты для связи? Желательно в виде аккаунта на GitHub.

---

@Vitlike commented on [Mon Dec 16 2019](https://github.com/AdguardTeam/AdguardFilters/issues/45912#issuecomment-566151559)

Это мой аккаунт

---

@Alex-302 commented on [Mon Dec 16 2019](https://github.com/AdguardTeam/AdguardFilters/issues/45912#issuecomment-566163546)

Ок. Можете проверить с выключенными фильтрами, антитрекингом и расширениями Адгарда?
Если не поможет - нам понадобится отладочный лог: https://kb.adguard.com/ru/android/solving-problems/log#debug
после получения лога проверьте такое правило:
`@@192.168.0.1$network`

---

@Vitlike commented on [Mon Dec 16 2019](https://github.com/AdguardTeam/AdguardFilters/issues/45912#issuecomment-566172061)

Отключение фильтров не помогло.
Отправил с телефона приложения через сообщение в поддержку С темой "лог к issue #45912"

---

@Vitlike commented on [Tue Dec 17 2019](https://github.com/AdguardTeam/AdguardFilters/issues/45912#issuecomment-566173816)

@@192.168.0.1$network - не дает результата 

<details><summary>Screenshot:</summary>

![Screenshot_2019-12-16-21-04-48-233_com yandex browser](https://user-images.githubusercontent.com/32840483/70931163-d36b1a80-2047-11ea-9f9e-736256c68e13.jpg)

![Screenshot_2019-12-16-21-02-12-240_com adguard android](https://user-images.githubusercontent.com/32840483/70931009-8d15bb80-2047-11ea-9c80-a9dc7b6526f8.jpg)

</details>

---

@Eugene-Savenko commented on [Tue Dec 17 2019](https://github.com/AdguardTeam/AdguardFilters/issues/45912#issuecomment-566451610)

@Alex-302 лог в 2451009.

**Comment by sxgunchenko** [comment]
Cannot reproduce with current nightly
