### ISSUE TITLE
get.todoist.help - cookie issue

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1220]
@adguard-bot commented on [Thu Nov 07 2019](https://github.com/AdguardTeam/AdguardFilters/issues/43682)

### Issue URL (Incorrect Blocking)
[https://get.todoist.help/hc/ru](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fget.todoist.help%2Fhc%2Fru)
### Comment
Username: @Rakleed
> Вхожу в свой аккаунт (насколько я понимаю, то я вхожу с помощью аккаунта Todoist, т. к. никакие данные при нажатии Войти на сайте get.todoist.help не ввожу, а на сайте todoist.com/app я уже залогинен), но через несколько часов или дней заново захожу на сайт поддержки, и я уже опять разлогинен, и мне прдлагается войти.
> --
> Информация ниже сгенерирована автоматически, не удаляйте ее.
> 
> Referrer:
> https://get.todoist.help/hc/ru?flash_digest=c62226688884b9f325264c25ed4025ba58e80daf
> 
> Custom userscripts:
> https://greasyfork.org/scripts/19993-ru-adlist-js-fixes/code/RU%20AdList%20JS%20Fixes.user.js
> https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/hArFAuA.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/SHYnPJ3.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 7.2.2936.0
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Hide your Referrer from third-parties (get.todoist.help), Hide your User-Agent ()
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/> AdGuard Russian

---

@Alex-302 commented on [Fri Nov 08 2019](https://github.com/AdguardTeam/AdguardFilters/issues/43682#issuecomment-551854503)

Проверь
`@@||todoist.help^$stealth`
`@@||todoist.com^$stealth`

---

@Rakleed commented on [Wed Nov 13 2019](https://github.com/AdguardTeam/AdguardFilters/issues/43682#issuecomment-553458555)

@Alex-302 спустя 5 дней опять требуется залогиниться, хотя я сам не выходил.

**Comment by ameshkov** [comment]
@Rakleed а вы как злогинены? Через соцсеть или нет?

**Comment by Rakleed** [comment]
@ameshkov на https://todoist.com/Users/showLogin я логинюсь через email и пароль от сервиса.

**Comment by sfionov** [comment]
@Rakleed Повторяется ли данная проблема у вас сейчас?

**Comment by Rakleed** [comment]
А как мне проверить, что проблема не в самом сервисе? Мне нужно полностью отключить AdGuard или хватит только отключить фильтрацию для сайтов [todoist.com](todoist.com) и [todoist.help](todoist.help)?

**Comment by Rakleed** [comment]
@sfionov а как мне проверить, что проблема не в самом сервисе? Мне нужно полностью отключить AdGuard или хватит только отключить фильтрацию для сайтов todoist.com и todoist.help?

**Comment by sfionov** [comment]
@rakleed Насколько я понимаю, в данный момент они используют один домен, и проблема должна уйти. Так же некоторые проблемы с third-party куками были исправлены в #1401. Просьба переоткрыть тикет, если всё же столкнётесь с этой проблемой.
