### ISSUE TITLE
Extend $stealth modifier

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1224]
We should be able to disable certain stealth mode features, not all of them.

### Examples:

* `||example.org^$stealth=cookie1p` -- disables first-party cookies blocking for a given URL
* `||example.org^$stealth=cookie3p` -- disables third-party cookies blocking for a given URL
* `||example.org^$stealth=referrer` -- disables "hiding referrer"

**Comment by slavaleleka** [comment]
there are no exception rules for `[Stealth Mode - first-party cookies]`, only for **third-party cookies** (~30 rules)

also there are such exceptions:
- `IP hiding` ~40 rules
- `Block third-party Authorization header` ~40 rules
- `User-agent` ~20 rules
- `WebRTC` ~20 rules

**Comment by sxgunchenko** [comment]
Here's the proposed options:

* `1p-cookie` -- disables blocking first-party cookies
* `3p-cookie` -- disables blocking third-party cookies
* `3p-cache` -- enables cache for third-party requests
* `xclientdata` -- disables removing X-Client-Data header from HTTP requests
* `donottrack` -- disables sending Do-Not-Track signals
* `ip` -- disables hiding IP address
* `3p-auth` -- disables blocking third-party Authorization header
* `searchqueries` -- disables hiding search queries
* `referrer` -- disables hiding referrer
* `useragent` -- disables hiding User-Agent
* `webrtc` -- disables blocking WebRTC
* `push` -- disables blocking Push API
* `location` -- disables blocking Location API
* `flash` -- disables blocking Flash
* `java` -- disables blocking Java
* `dpi` -- disables DPI fooling measures

**Comment by ameshkov** [comment]
Looks good

**Comment by piquark6046** [comment]
- seoulland.co.kr (https://github.com/List-KR/List-KR/commit/b286c49b576b5d67f634c032251354434d1970d3)
