### ISSUE TITLE
Custom script injection

### ISSUE THREAD

**Issue by optomux** [AdguardTeam/CoreLibs#1225]
Provide options to inject script like uBO does with `script:inject()` 
https://github.com/gorhill/uBlock/issues/3307

Or at the very least provide a way to disable loading of 
`/** userscript-wrapper - v1.2.4 - 11/26/2019 */`

Or even name it `Base loader wrapper script.`
So that we can inject raw scripts.

**Comment by sfionov** [comment]
AdGuard already have JS rules.

**Comment by sfionov** [comment]
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#javascript-rules

**Comment by optomux** [comment]
No. I need to unload `/** userscript-wrapper - v1.2.4 - 11/26/2019 */`

**Comment by sfionov** [comment]
You may disable userscripts by rule `@@||site.com^$extension`

**Comment by optomux** [comment]
I want to have a userscript but without the wrapper!

**Comment by sfionov** [comment]
Wrapper defines GM_ functions that many userscripts use, thats because it is injected together with userscripts. If no userscripts matches this site, wrapper will not be injected (but AG assistant matches all sites).

If you want to inject some JS code, use JS rules. If you want to use AdGuard's userscripts functionality, wrapper is just how they are implemented.

**Comment by optomux** [comment]
With JS rules you can only inject one line of JS not a file.

**Comment by optomux** [comment]
Can you comment on this? @ameshkov

**Comment by ameshkov** [comment]
Well, basically what's requested is custom scriptlets that users can create themselves. 

We will consider this for v1.7: https://github.com/AdguardTeam/CoreLibs/issues/1226. 

This is not that hard to implement, and it makes sense to have this option to make scriptlets testing easier.

**Comment by optomux** [comment]
God yes! Ha, ha, ha.
