### ISSUE TITLE
digid.nl

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1229]
@adguard-bot commented on [Mon Dec 23 2019](https://github.com/AdguardTeam/AdguardFilters/issues/46501)

### Issue URL (Incorrect Blocking)
[https://digid.nl/inloggen](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fdigid.nl%2Finloggen)
### Comment
Username: @Krizzii
> If there's 1 site in the Netherlands that can't be blocked, it's this one. Please unblock this domain asap. Why is it blocked in the first place? 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/NdRGjGx.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/nWo2VCE.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 10
AdGuard version: | 3.3 RC 1 (220)
Browser: | Chrome (data compression)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Dutch
Other extensions used: | AdGuard Home

---

@AdamWr commented on [Mon Dec 23 2019](https://github.com/AdguardTeam/AdguardFilters/issues/46501#issuecomment-568535170)

It looks like a bug.

**Comment by AdamWr** [comment]
It happens also on Windows with all modules disabled.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/71371869-ff8c1b80-25b2-11ea-912d-b647dd9e6ad0.png)

</details>

**Comment by AdamWr** [comment]
By the way, it seems that this website is in HTTPS exclusions and if I remove it from here, then website loads fine.

**Comment by ameshkov** [comment]
Hm, I cannot reproduce this neigher on Mac nor on Win

**Comment by ameshkov** [comment]
Although, I can reproduce it on Android

**Comment by ameshkov** [comment]
Weird, we'll look into it

**Comment by ameshkov** [comment]
@AdamWr temporary solution: `@@144.43.243.208$network`

**Comment by AdamWr** [comment]
Unfortunately this rule doesn't work on my end, at least on Windows.

**Comment by ameshkov** [comment]
You might need to restart AG protection

**Comment by AdamWr** [comment]
Ok I did it, even restarted PC, but it still happens.

**Comment by ameshkov** [comment]
Hm, try pinging `digid.nl`, what IP address do you see?

**Comment by AdamWr** [comment]
I see `144.43.243.208`, so I don't know why it doesn't work.

**Comment by ameshkov** [comment]
Do you use any proxy or vpn?

**Comment by AdamWr** [comment]
I have VPN installed, but it's disabled at the moment.

**Comment by ameshkov** [comment]
Maybe IPv6? 

Try this:
`@@[2a04:9a00:1010:1900::a]$network`

**Comment by AdamWr** [comment]
No, I have IPv4.
Filtering log shows `144.43.243.208` too, but for some reason it doesn't work.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/71374917-d40e2e80-25bc-11ea-9448-e40cf3bcd859.png)

</details>

**Comment by AdamWr** [comment]
I have enabled `Use redirect driver mode` and it seems that it was causing this issue.
After disabling this option website works fine even without exceptions.

**Comment by ameshkov** [comment]
Redirect driver mode is disabled by default so the only problematic platform is Android.

This $network rule should help with it.

**Comment by AdamWr** [comment]
Yes, on Android this rule works fine, added it.

**Comment by sjhgvr** [comment]
This is great and all.. but what is Adguard doing, not having any blocklist enabled to cause this in the first place?

**Comment by sjhgvr** [comment]
I also found out; 

Adguard enabled (with the local VPN) yet all of it's blocking features, including lists are disabled.

The log also shows nothing being blocked.

How is this possible?

**Comment by ameshkov** [comment]
@sjhgvr hi, have you tried the latest beta version of AG?

**Comment by sjhgvr** [comment]
> @sjhgvr hi, have you tried the latest beta version of AG?

Not sure how that answers my question.
Anyhow; this also fixed it; https://github.com/AdguardTeam/AdguardFilters/issues/55359#issuecomment-629127281
