### ISSUE TITLE
Crash while raising browser API event

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/CoreLibs#1231]
The app is crashing if you will try to block any element on the website with the assistant.

### Steps to reproduce:
1. Download and install the latest Adguard for Android version ([beta](https://agrd.op/apkb)/[nightly](https://agrd.io/android_nightly))
2. Go to AdGuard Assistant [repo](https://github.com/AdguardTeam/AdguardAssistant/releases/tag/v4.3.15) and install it from AdGuard for Android application
2. Open Chrome browser and go to [example.org](https://example.org) website
3. In the additional settings on the website request desktop site
4. Use assistant and block any element on the website

**Comment by sfionov** [comment]
https://sentry.adguard.com/adg/adguard-android-rs/issues/44884/
https://sentry.adguard.com/adg/adguard-android-rs/issues/44885/

**Comment by ameshkov** [comment]
@TheHasagi add a step with installing Assistant userscript as well to "steps to repro"

**Comment by sfionov** [comment]
core/pull-requests/1661
CL 1.5.165+
