### ISSUE TITLE
Firefox: onlinetrade.ru is broken when protection is enabled

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1232]
@adguard-bot commented on [Thu Dec 26 2019](https://github.com/AdguardTeam/AdguardFilters/issues/46617)

### Issue URL (Incorrect Blocking)
[https://www.onlinetrade.ru/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.onlinetrade.ru%2F)
### Comment
Username: @Eroppo
> При попытках перехода по ссылкам вкладка на какое-то время тупо виснет - пустая белая страница, даже переход назад не работает. Через какое-то время отображается в том же неполноценном виде. В других браузерах воспроизвести не удалось

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/LpjRAcc.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/0CKkGfb.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 7.3
Browser: | Firefox
AdGuard driver: | WFP
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Russian
Other extensions used: | LastPass, S3 translator, Group Speed Dial, Gesturefy, Windows Defender, других блокировщиков нет

---

@Alex-302 commented on [Fri Dec 27 2019](https://github.com/AdguardTeam/AdguardFilters/issues/46617#issuecomment-569247462)

@Eroppo баг что ли. 

---

@Eroppo commented on [Fri Dec 27 2019](https://github.com/AdguardTeam/AdguardFilters/issues/46617#issuecomment-569248171)

@Alex-302 да, появилось только в Firefox после обновления до 7.3. Удаление профиля и отключение блокировки не помогают - сайт открывается нормально только с полным закрытием Adguard из трея

---

@Alex-302 commented on [Fri Dec 27 2019](https://github.com/AdguardTeam/AdguardFilters/issues/46617#issuecomment-569248481)

Сейчас перенесу куда следует. Логи только соберу, у меня тоже повторилось - без фильтров, без расширений, без антитрекинга.
Исключение `@@||onlinetrade.ru^$elemhide,jsinject,extension` тоже не помогло.

**Comment by Alex-302** [comment]
My logs:
[logs.zip](https://github.com/AdguardTeam/CoreLibs/files/4005150/logs.zip)
The first attempt was successful, 2-4 - failed(page hungs)
Not sure if it is the same issue
https://github.com/AdguardTeam/CoreLibs/issues/1221

**Comment by sfionov** [comment]
Merged into #1223
