### ISSUE TITLE
ping-blocker

### ISSUE THREAD

**Issue by userbody** [AdguardTeam/CoreLibs#1233]
https://github.com/dessant/ping-blocker

**Comment by optomux** [comment]
Currently Adguard cannot remove only properties from HTML? @ameshkov 
` <a href="https://example.com" ping="https://example.com/ping" target="_blank">Click me!</a>`

**Comment by optomux** [comment]
Help! @ameshkov

**Comment by ameshkov** [comment]
@optomux no, that's not possible in the current implementation.

It might be a nice addition, though. Thanks for the idea!
