### ISSUE TITLE
Websocket connections and ws/wss schema on Firefox

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1236]
> @optomux commented on [Sat Dec 28 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/3151)

> Websockets not being blocked. Works fine on Chrome.

> `|wss*://*`
> `|ws*://*`

Websocket upgrade requests look like regular HTTP(s) requests in the filtering log. I think it makes sense to use ws(s) schema for them instead.

**Comment by ngorskikh** [comment]
core/pull-requests/1715
