### ISSUE TITLE
AG cannot handle 103 Early Hints

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1238]
@akmLaVx commented on [Tue Jan 14 2020](https://github.com/AdguardTeam/AdguardFilters/issues/47694)

***Description***:
* **Current behaviour**: 

Throws an ERR_EMPTY_RESPONSE upon attempting to open the URL.

<details><summary>Network log:</summary>

![image](https://user-images.githubusercontent.com/33634917/72304450-3d8fd300-3679-11ea-92b4-fecd20e26eef.png)

</details><br/>

* **Expected behaviour**: 

Site should open just fine.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/33634917/72304516-631cdc80-3679-11ea-91bd-8b3ad9dbed08.png)

</details>

***Steps to reproduce the problem***:

Just open the site w/protection enabled.

***System configuration***

**Filters:**

Information                            | Value
---                                    | ---
Operating system:                      | Windows 10
Operating system version (Android/iOS) | Ver 2004 Build 19041.1
Browser:                               | Chrome 80
AdGuard version:                       | 7.3n23
Filters enabled:                       | Base, Russian, Mobile ads, Annoyances, Adblock Warning Removal List
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | None
Helpdesk ID (if exists):               | 2491837

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Alex-302** [comment]
My logs: 
[logs.zip](https://github.com/AdguardTeam/CoreLibs/files/4059426/logs.zip)
<details><summary>On very-very first visit:</summary>

![image](https://user-images.githubusercontent.com/8361299/72350008-423ea080-36e6-11ea-9af9-291194fd263e.png)

</details>

<details><summary>Screenshot:</summary>


</details>

**Comment by sfionov** [comment]
Website uses `HTTP/1.1 103 Early Hints` response.
Seems that current CoreLibs handling of both `100 Continue` and `103 Early Hints` is not perfect for HTTP/1.1 - both may result in dropping response in some cases.

**Comment by andrewreedy** [comment]
Hey, Scott's Cheap Flights dev here. We ended up disabling `103 Early Hints`. It looks like multiple ad block / malware protection solution aren't compatible. Let us know if there is anything we can do to help test this though. Thanks!

**Comment by ameshkov** [comment]
@andrewreedy thank you so much, and sorry that it takes us that long to resolve the issue on our side! I can confirm that it is working just okay now.

@sfionov we still need to figure out how to handle `103` status properly to avoid this in the future.

**Comment by ngorskikh** [comment]
core/pull-requests/1684
