### ISSUE TITLE
"badfilter" modifier doesn't work with "all" modifier

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1240]
### Steps to reproduce

1. Add these rules to user filter:
```
||google.com^$all
||google.com^$all,badfilter
```
2.  Go to - https://www.google.com/

### Expected behavior

First rule should be disabled by rule with `badfilter` and website shouldn't be blocked.
### Actual behavior

Website is blocked.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/72362325-445b2c00-36f3-11ea-93c7-d2eb626883f6.png)

</details>

One more issue is, that rule with `$all,badfilter` is treated as invalid in the filter editor.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/72362581-b3388500-36f3-11ea-86af-54d59bfe204e.png)

</details>

### Your environment

* AdGuard for Windows version 7.3 nightly 23 (build 3056, CL 1.5.165)

**Comment by ameshkov** [comment]
@sxgunchenko @sfionov guys, this is a serious bug, and we'd better have it fixed in the next patch, and not a major release.

**Comment by sxgunchenko** [comment]
core/pull-requests/1669
