### ISSUE TITLE
Stealth Mode and other modifiers as whitelisted

### ISSUE THREAD

**Issue by northis** [AdguardTeam/CoreLibs#1242]
We should treat the `@@...`-rule matches with these modifiers as whitelisted:

- $badfilter
- $content
- $cookie
- $csp
- $document
- $elemhide
- $extension
- $important
- $jsinject
- $replace
- $stealth
- $urlblock

https://github.com/AdguardTeam/AdguardForWindows/issues/3123

**Comment by ameshkov** [comment]
After all, this behavior is not really okay.
