### ISSUE TITLE
Scriptlet exceptions don't work correctly

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1243]
### Steps to reproduce

1. Add these rules:
```
adamwr.github.io#@%#//scriptlet('abort-current-inline-script', 'whatever', 'abc')
adamwr.github.io#%#//scriptlet('abort-current-inline-script', 'alert', 'Test')
adamwr.github.io#%#//scriptlet('abort-current-inline-script', 'console.log', 'Test')
```
2. Go to  - https://adamwr.github.io/test-page/index.html

### Expected behavior

Alert and console.log should be aborted by `abort-current-inline-script`.

### Actual behavior

It seems that exception rule disable all other rules with `abort-current-inline-script`.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/72550438-05fc7300-3893-11ea-866c-ec3384594fc2.png)

</details>

### Your environment

* AdGuard for Windows version 7.3 nightly 24 (build 3063, CL 1.5.170)

**Comment by sxgunchenko** [comment]
Is it a bug?
Scriptlet rules follow the javascript rules syntax https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#javascript-rules-syntax-1.
And as the exception rule you mentioned has different texts with blocking ones, it doesn't exclude them.

**Comment by AdamWr** [comment]
If I add all 3 rules mentioned in the first post, then the first one disable other rules, but shouldn't.
If I add only only second and third rule then both works fine, so I think that it's a bug.

**Comment by sxgunchenko** [comment]
Yup, i misread the expected behavior. It's a bug indeed :)

**Comment by AdamWr** [comment]
By the way, the same happens with other scriptlets, for example:
`example.org#%#//scriptlet("abort-on-property-read", "alert")`
`example.org#@%#//scriptlet("abort-on-property-read", "Math")`

**Comment by ngorskikh** [comment]
core/pull-requests/1678
