### ISSUE TITLE
USCR_EMETA error while importing a userscript

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1246]
@akmLaVx commented on [Tue Jan 21 2020](https://github.com/AdguardTeam/AdguardForWindows/issues/3170)

### Steps to reproduce

Userscript in question: https://raw.githubusercontent.com/chuck-lee/tw-apple-daily-news-revealer/master/reveal.js

### Actual behavior
Attempting to import userscript to AdGuard fails with USCR_EMETA error.

### Customer ID 
2480127

### Your environment
Repro:
* AdGuard version: 7.3.3067 nightly
* Environment name and version: Edge 80 Beta
* Operating system and version: Windows 10 19041.21

**Comment by ngorskikh** [comment]
But where is the meta.json for the script? :)
