### ISSUE TITLE
AdGuard certificate is not trusted

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/CoreLibs#1247]
Somehow, after update of Chrome browser for Android (07.01.2020) every page you reach will notify about CA issue (see attachments). This can be only reproduced if AdGuard CA is installed in System store.

<details>

![image](https://user-images.githubusercontent.com/37797229/72804670-f77ed480-3c61-11ea-91d1-fe1bc667984b.png)

![image](https://user-images.githubusercontent.com/37797229/72804677-fd74b580-3c61-11ea-845c-8b6d753d685e.png)

![image](https://user-images.githubusercontent.com/37797229/72804682-01083c80-3c62-11ea-84d4-83ab1e5682f1.png)

</details>

### Steps to reproduce:

Preconditions:

You should have root access on your mobile device

1. Install AdGuard and enable protection
2. Enable HTTPS filtering and move the certificate from user to system store
3. Reboot the device
4. Try to open any webpage

**Comment by ameshkov** [comment]
> Reboot the device

Isn't it a Magisk issue?

**Comment by TheHasagi** [comment]
Issue moved to [AdguardTeam/AdguardForAndroid #3316](https://github.com/AdguardTeam/AdguardForAndroid/issues/3316) via [**ZenHub**](https://www.zenhub.com/)
