### ISSUE TITLE
vietnamnet.vn

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1249]
@adguard-bot commented on [Wed Jan 22 2020](https://github.com/AdguardTeam/AdguardFilters/issues/48349)

### Issue URL (Incorrect Blocking)
[https://vietnamnet.vn/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fvietnamnet.vn%2F)
### Comment
Username: @minhgv
> 
> --
> The information below is automatically generated. Do not delete it.
> 
> Referrer:
> 
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/adguard-wot/1.0/wot.meta.js
> https://userscripts.adtidy.org/release/assistant/4.3/assistant.meta.js
> https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.meta.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/PrELWMK.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/iwgGeMW.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Mac
AdGuard version: | 2.3.2.710 release
Browser: | Chrome
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Block third-party Authorization header, Self-destructing first-party cookies (4320), Self-destructing third-party cookies (180), Disable cache for third-party requests, Block Push API, Block Location API, Block Java, Hide your Referrer from third-parties (), Hide your User-Agent (), Hide your IP address (209.141.53.254)
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads, <br/>EasyList, <br/>Peter Lowe's Blocklist<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection, <br/>EasyPrivacy, <br/>Fanboy's Enhanced Tracking List, <br/>Fanboy Anti-Facebook List, <br/>Fanboy's Anti-thirdparty Fonts<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media, <br/>Fanboy's Social Blocking List<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>Fanboy's Annoyances, <br/>Web Annoyances Ultralist, <br/>Adblock Warning Removal List, <br/>Fanboy's Cookiemonster List<br/><br/><b>Security:</b><br/> Malware Domains Blocklist, <br/>Spam404, <br/>NoCoin Filter List<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/> AdGuard Russian, <br/>EasyList China, <br/>ABPVN List, <br/>ChinaList+EasyList
Custom filter subscriptions: | 

---

@AdamWr commented on [Thu Jan 23 2020](https://github.com/AdguardTeam/AdguardFilters/issues/48349#issuecomment-577670122)

It looks like a bug.
I can reproduce this issue even with all modules disabled
Adding:
`@@||vietnamnet.vn^$elemhide,jsinject,extension`
or
`@@||vietnamnet.vn^$document`
to user filter doesn't help.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/72985783-05aa2d80-3de7-11ea-9850-7d056ea666c2.png)

</details>

It seems that the problem is that `https://vnn-res.vgcloud.vn/` doesn't load and I guess that it may be related to this:
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/72985898-4c982300-3de7-11ea-843b-88d3b8016ebd.png)

</details>

**Comment by ngorskikh** [comment]
Their CDN (probably) `vnn-res.vgcloud.vn` is using `Protocol  : TLSv1` with an ancient `Cipher    : RC4-SHA`. (info obtained with LibreSSL 2.8.3) 

OpenSSL simply refuses to handshake with it:
```
➜  exclusions git:(master) /usr/local/Cellar/openssl@1.1/1.1.1d/bin/openssl version       
OpenSSL 1.1.1d  10 Sep 2019
➜  exclusions git:(master) /usr/local/Cellar/openssl@1.1/1.1.1d/bin/openssl s_client -connect vnn-res.vgcloud.vn:443
CONNECTED(00000005)
<pause for about 30 seconds>
write:errno=54
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 320 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

Suggestion: add `vnn-res.vgcloud.vn` to exclusions, re-test with BoringSSL later.

**Comment by ameshkov** [comment]
> OpenSSL simply refuses to handshake with it

Browsers won't allow using it as well, are you sure this is the problem?
What cipher does it use when RC4 is not advertised in the ClientHello?

**Comment by ngorskikh** [comment]
It seems the browser is advertising AES128 (among others), which is supported by the server, but not by our OpenSSL binary. Chrome is complaining that this is an obsolete cipher as well :)

**Comment by ngorskikh** [comment]
Update: OpenSSL actually supports TLSv1 with `TLS_RSA_WITH_AES_128_CBC_SHA (0x002f)` (which is what is negotiated when the browser connects to this server), and sends a proper ClientHello, but the server doesn't respond to OpenSSL's ClientHello for some reason.

Added to exclusions: https://github.com/AdguardTeam/HttpsExclusions/pull/246
