### ISSUE TITLE
Change the logic for the "EV-exclusion"

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#1252]
As for now "EV-exclusions" list represents the exclusions from the non-filtering the EV certificates, i.e. so-called "AlwayFilteredEvDomains". While we are getting rid of a double negative in the "filter EV" section (https://github.com/AdguardTeam/AdguardForWindows/issues/3133), let's use a "traditional meaning" of the EV-exclusion list, i.e. the list of the domains, which are excluded from the filtering.

**Comment by ameshkov** [comment]
What's the point of this?

**Comment by adbuker** [comment]
The point is in the making the network section more uniform, and providing users with the strict logic for both options - "Filter https(EV)" and "Exclusions" from such kind of filtration - https://uploads.adguard.com/buker-9af0x.png. At this moment the users can be frustrated with the completely opposite meanings of the term "Exclusion" (despite the label upon the button)

**Comment by ameshkov** [comment]
I don't see what's wrong with the CoreLibs interface and what it has to do with this.
