### ISSUE TITLE
Extended CSS rule is not working, if ':contains()' has ':'

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1253]
This rule works
`officelife.media#?#.drop-actions > div.label:contains(Поделиться)`
this - not
`officelife.media#?#.drop-actions > div.label:contains(Поделиться:)`
The difference is in this part `Поделиться:`

Both rules works in browser extension.

Can be checked here(wait few seconds if they are not visible):
https://officelife.media/news/14350-wargaming-opens-second-office-in-minsk/
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/73271147-bac65680-41e8-11ea-8dbb-cd864e2d058d.png)

</details>

Please add this exclusion before checking:
`officelife.media#@?#.drop-actions > div.label:contains(Поделиться)`
or disable Social filter.

**Comment by ngorskikh** [comment]
Works if the colon is escaped, like this `officelife.media#?#.drop-actions > div.label:contains(Поделиться\:)`.
Would that be acceptable? :)

**Comment by ngorskikh** [comment]
Ok, the problem was that the browser extension doesn't parse all of the pseudo-classes in the rule, just the first one. Therefore. it never reaches the second unescaped ':'. 

PR allowing the ':' to appear inside parens/brackets:
core/pull-requests/1680

**Comment by ngorskikh** [comment]
core/pull-requests/1680
