### ISSUE TITLE
Experiment with signed HTTP exchanges

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1254]
Here is a tool we can use to experiment:
https://github.com/ampproject/amppackager

Our goals at this point:
1. Not break it
2. Figure out what we can do when AMP starts using this

Assigned to v1.5+ext-api because if this proves to be a problem, we'll have to handle this in the assistant extensions.

One more way to test it:
https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/signed-exchange/#testing_1

UPD: amp.dev uses signed exchanges

if you want to experiment, do the following:
1. open dev tools
2. switch your user agent to some Pixel device
3. check "preserve log" to see the full picture
4. open this address: https://amp-dev.cdn.ampproject.org/wp/s/amp.dev/success-stories/us_xpress/

**Comment by ngorskikh** [comment]
It seems, `application/signed-exchange` passes through the corelibs proxy without problems.
