### ISSUE TITLE
Fatal Error in http2_session_send_data

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#1256]
https://sentry.adguard.com/adg/adguard-windows/issues/39387/

The issue is only with 1.5.x version and over 100 events for this time

**Comment by BlazDT** [comment]
Looks a bit like this error here:
https://forum.adguard.com/index.php?threads/website-isnt-showing-properly.38881

ERR_HTTP2_PROTOCOL_ERROR
https://stackoverflow.com/questions/58215104/whats-the-neterr-http2-protocol-error-about
