### ISSUE TITLE
Add $ping content type

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1258]
* [x] Check how we can distinguish requests sent by `navigator.sendBeacon`
* [ ] Add this content type support
* [ ] Add it to the knowledge base

**Comment by vshlobinag** [comment]
navigator.sendBeacon can send any content-type (including empty, or not existed for example "my/content")

**Comment by ameshkov** [comment]
Got it:(

**Comment by ameshkov** [comment]
Actually, it is possible to detect at least beacons sent by "ping" attribute:
![image](https://user-images.githubusercontent.com/5947035/84907225-9d245b80-b0bb-11ea-8b29-d367f8cac9fe.png)

`<a href="blahbl" ping="url">tracked link</a>`
