### ISSUE TITLE
Rules are not applied to websites with dot at the end

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1261]
I'm not sure if it's a bug, but it seems that with other adblockers like Adblock Plus and uBlock Origin it works fine.
### Steps to reproduce

1. Add these rules:
```
benchmark.pl##body
||cdn.benchmark.pl^$domain=benchmark.pl
```

2. Go here - [http://www.benchmark.pl./](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http://www.benchmark.pl./)

### Expected behavior

Website should be blank and requests from `cdn.benchmark.pl` should be blocked.

### Actual behavior

Rules are not applied due to dot at the end.

### Your environment

* AdGuard for Windows Version 7.4 nightly 3 (build 3093, CL 1.5.170)

**Comment by sfionov** [comment]
URLs with FQDN are valid, so we should support this.

**Comment by ngorskikh** [comment]
We could strip the trailing dot from the request's host, but that would break rules which do contain the trailing dot:

core/pull-requests/1692

**Comment by ngorskikh** [comment]
core/pull-requests/1695
