### ISSUE TITLE
"Proceed anyway" option doesn't work correctly if website is blocked by rule with $all modifier

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1267]
### Steps to reproduce

1. Add this rule:
`||adguard.com^$all`
2. Go here - https://adguard.com/
3. Click on "Proceed anyway" button (like on a screenshot below)

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/74101828-250ebd80-4b3e-11ea-97d0-be3a9cc6ec1b.png)

</details>

### Expected behavior

Website should loads correctly.

### Actual behavior

Website loads, but requests are still blocked.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/74101856-61421e00-4b3e-11ea-89a7-71b00d892f5b.png)

</details>

If I use `$document` modifier instead of `$all` like - `||adguard.com^$document` then website loads fine (after clicking on "Proceed anyway" button), so I think that with `$all` modifier it should works the same.

### Your environment

* AdGuard for Windows Version 7.4 nightly 3 (build 3093, CL 1.5.170)

**Comment by ameshkov** [comment]
Actually, this is expected behavior at least in the current implementation.

We should change the way it's implemented, though.
Instead of unblocking one request, we should disable the whole rule `||adguard.com^$all` at least temporary.

**Comment by ameshkov** [comment]
After some thinking, I came to the conclusion that we cannot implement this solution, it's too risky as it may expose some ways to avoid blocking to third-parties.

The only more or less viable solution would be to add an "Unblock for 30 seconds" button to the access denied page that will call AdGuard using custom scheme `scheme:`: https://github.com/AdguardTeam/AdguardForWindows/issues/2938

**Comment by marcopaone** [comment]
Hi! How you added the popup message?
