### ISSUE TITLE
body tag can't be removed by HTML filtering rules ($$)

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1268]
### Steps to reproduce

1. Add this rule:
`example.org$$body[max-length="0"]`
2. Go here - http://example.org/

### Expected behavior

`body` tag should be removed.

### Actual behavior

Rule doesn't work.

I'm not sure if it's a bug or by design, but if it's a correct behavior then I think that filtering log shouldn't show these rules.

This rule works fine in AdGuard Extension for Firefox.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/74102458-ebd94c00-4b43-11ea-9fd1-fa5a755c6232.png)

</details>

Similar with:
`example.org$$html[max-length="0"]`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/74102505-3bb81300-4b44-11ea-8024-9a5db98162b3.png)

</details>

### Your environment

* AdGuard for Windows Version 7.4 nightly 3 (build 3093, CL 1.5.170)

**Comment by ameshkov** [comment]
Hm, the `body` tag may be an exception indeed, we should check it.

**Comment by sfionov** [comment]
Yes, it is exception. There should be message that "body tag cannot be removed because it is already partially sent to client" in debug log.

**Comment by ameshkov** [comment]
Well, the question is why it is in the filtering log?

**Comment by ngorskikh** [comment]
core/pull-requests/1711
