### ISSUE TITLE
Problematic userscripts

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1273]
When async API support is added, we should revisit:

* https://github.com/AdguardTeam/AdguardForWindows/issues/3107
* https://github.com/AdguardTeam/CoreLibs/issues/186
* https://github.com/AdguardTeam/CoreLibs/issues/204
* https://github.com/AdguardTeam/AdguardForWindows/issues/3192
* https://greasyfork.org/ru/scripts/36662-image-max-url

Also, check this one, we can't parse metadata:

* https://greasyfork.org/ru/scripts/40843-kinozal-tv-me-guru-2020-torrent-magnet-%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D0%B8-%D0%B2-%D0%BF%D0%BE%D0%B8%D1%81%D0%BA%D0%BE%D0%B2%D0%BE%D0%B9-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B5-%D1%80%D0%B0%D0%B7%D0%B4%D0%B0%D1%87%D0%B8-%D0%BF%D0%B5%D1%80%D1%81%D0%BE%D0%BD%D1%8B/code

**Comment by sfionov** [comment]
Also scripts from #204 are remaining

**Comment by GrayWolfson** [comment]
Не подключается в AdGuard полезный скрипт [google-image-sizer](url=https://github.com/danieljbingham/google-image-sizer) (( В чём может быть проблема?
https://github.com/danieljbingham/google-image-sizer/blob/master/run.user.js

**Comment by ameshkov** [comment]
Вот так подключали?
https://github.com/danieljbingham/google-image-sizer/raw/master/run.user.js

**Comment by GrayWolfson** [comment]
)) Спасибо! В таком виде сработало. Свою ошибку понял )

**Comment by wanesoft** [comment]
> )) Спасибо! В таком виде подключился. Свою ошибку понял )
> 
> Однако, почему-то сам не работает (
> Через greasemonkey нормально всё.

@GrayWolfson 
спасибо. исправлено
core/pull-requests/2044

**Comment by wanesoft** [comment]
> * https://greasyfork.org/ru/scripts/36662-image-max-url

похоже этот скрипт мы не сможем поддерживать. дело в том, что он при прямом запросе картинки заменяет url (например, `https://example.com/image.jpg` на `https://example.com/image.jpg?name=orig`. соответственно, мы не можем инжектиться в картинку или запускать логику скрипта в CoreLibs

**Comment by wanesoft** [comment]
> Also, check this one, we can't parse metadata:
> 
> * https://greasyfork.org/ru/scripts/40843-kinozal-tv-me-guru-2020-torrent-magnet-%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D0%B8-%D0%B2-%D0%BF%D0%BE%D0%B8%D1%81%D0%BA%D0%BE%D0%B2%D0%BE%D0%B9-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B5-%D1%80%D0%B0%D0%B7%D0%B4%D0%B0%D1%87%D0%B8-%D0%BF%D0%B5%D1%80%D1%81%D0%BE%D0%BD%D1%8B/code

судя по всему, kinozal множество раз менял свой адрес (сейчас на аппспоте базируются), так что тут надо править `@include`. однако после правки мы благополучно его инжектим, появляются ссылки для скачивания, но, похоже, логика скрипта безнадежно устарела. аналогичное поведение с использованием GM

**Comment by qsniyg** [comment]
@wanesoft 

>похоже этот скрипт мы не сможем поддерживать. дело в том, что он при прямом запросе картинки заменяет url (например, https://example.com/image.jpg на https://example.com/image.jpg?name=orig. соответственно, мы не можем инжектиться в картинку или запускать логику скрипта в CoreLibs

Ah good point. However, I believe should work for regular web pages (e.g. pressing shift+alt+i over an image should open a popup)

If there's anything I can do from my side to make it easier to support, let me know :)
