### ISSUE TITLE
Automatic way to deal with changing proxy servers

### ISSUE THREAD

**Issue by alexdonh** [AdguardTeam/CoreLibs#1274]
### Problem Description

AdGuard doesn't support changing proxy automatically. Many VPN services offers many servers at different latencies so we may want to switch to the fastest server. Right now the only way to do that is manually updating the proxy settings.

### Proposed Solution

1. Automation API supports adding/updating proxy servers so we could do it by using taskers or alternatives.
2. Provide a way to dynamically set/switch proxy servers as per configured.

**Comment by ameshkov** [comment]
> Provide a way to dynamically set/switch proxy servers as per configured.

Via Tasker API as well?

**Comment by alexdonh** [comment]
> > Provide a way to dynamically set/switch proxy servers as per configured.
> 
> Via Tasker API as well?

See the 1.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdguardForAndroid #3363](https://github.com/AdguardTeam/AdguardForAndroid/issues/3363) via [**ZenHub**](https://www.zenhub.com/)
