### ISSUE TITLE
Add support for "$app" in cosmetic rules

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/CoreLibs#1276]
@DandelionSprout commented on [Wed Feb 26 2020](https://github.com/AdguardTeam/AdguardForWindows/issues/3209)

I came across a relatively severe bug in Internet Explorer 11 tonight on `https://www.vg.no`, wherein the browser would seemingly convert `font-feature-settings: "liga", "kern"` into `font-feature-settings: "liga": 1, "kern": 1`, which would somehow make text in the thin parts of article titles completely garbled.

So I saw this as an obvious thing I could've added to my Nordic list (which takes pride in unbreaking things), through something like `vg.no##span:style(font-feature-settings: normal)$app=iexplore.exe`... which does not seem to be supported, thus I'm in a difficult situation right now. Although `vg.no##span:style(font-feature-settings: normal)` doesn't immediately seem to break anything in other browsers (e.g. Chrome) at first glance, it'd feel unfair of me to apply it to the other 98% of browser instances out there that aren't Internet Explorer.

`!#if` does not have any IE-specific options that I'm aware of, so `$app` would've solved this problem if I could've used it in hiding rules.

### Steps to reproduce

1. Go to `https://www.vg.no` in Internet Explorer 11.
2. Notice there's a lot of garbled text in the headlines.
3. Right-click on garbled text and choose "Inspect element".
4. See that the `span` element contains the correct text, and that turning off `font-feature-settings: "liga": 1, "kern": 1` in the page inspection makes the text render correctly.

### Expected behavior
The text shows up correctly.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/75290811-54e9e080-5821-11ea-96d1-217a23ea03e4.png)

</details>

### Actual behavior
Top parts of multi-part titles are completely garbled.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/75290739-3683e500-5821-11ea-8e51-aa651c292d9e.png)

</details>

### Customer ID 

N/A

### Your environment

* Environment name and version: Internet Explorer 11.657.18362.0
* Operating system and version: Windows 10 November 2019 Update, build 18363.657

**Comment by sxgunchenko** [comment]
Non-basic rules modifiers have been introduced in `core/pull-requests/1874` which will be available in the version 1.6.

Here's the link to the specification: https://github.com/AdguardTeam/AdguardKnowledgeBase/blob/master/02.general/02.how-to-create-your-own-ad-filters/docs.en.md#non-basic-rules-modifiers
