### ISSUE TITLE
$badfilter modifier with $document exception behaves incorrectly

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1277]
### Steps to reproduce

1. Add these rules:
`@@||ghacks.net^$document`
`@@||ghacks.net^$document,badfilter`
or even just:
`@@||ghacks.net^$document,badfilter`
2. Go here - https://www.ghacks.net/2020/03/06/microsoft-adds-chrome-themes-support-to-new-edge-browser/

### Expected behavior

Exception rule should be disabled by rule with `badfilter`.

### Actual behavior

It seems that `@@||ghacks.net^$document,badfilter` works just like exception rule.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/76063409-ebd43c80-5f87-11ea-9225-3db4f348b144.png)

</details>

### Your environment

* AdGuard for Windows version 7.4 nightly 7 (build 3129, CL 1.5.215)

**Comment by ameshkov** [comment]
This one is an important bug, thanks for reporting it!

**Comment by sxgunchenko** [comment]
core/pull-requests/1745

**Comment by AdamWr** [comment]
Maybe it also has been fixed, but I just would like to inform that there is (or was) similar issue with rule like this:
`@@||ghacks.net^$elemhide,urlblock,badfilter`

**Comment by sxgunchenko** [comment]
Yup, that also has been fixed

**Comment by AdamWr** [comment]
Ok, thank you for your reply.
