### ISSUE TITLE
Issue with LINE extension

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1280]
@adguard-bot commented on [Wed Mar 18 2020](https://github.com/AdguardTeam/AdguardFilters/issues/51745)

### Issue URL (Incorrect Blocking)
 [https://chrome.google.com/webstore/detail/line/ophjlpahpchlmihnnnihgmmeilfjmjjc/related](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fchrome.google.com%2Fwebstore%2Fdetail%2Fline%2Fophjlpahpchlmihnnnihgmmeilfjmjjc%2Frelated)
### Comment
> Adguard for desktop Windows is conflicting with LINE google chrome extension. It occurs that it blocks the internet connection to the extension. When I open the extension, it shows no internet connection error message. But when I disable Adguard the LINE extension functions correctly. Below is the link to the extension on chrome store.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/s7uAkK0.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/tHUTFlu.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Mac
AdGuard version: | 2.3.2.710 release
Browser: | Chrome
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>Web Annoyances Ultralist<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/> AdGuard Russian, <br/>AdGuard German
Custom filter subscriptions: | https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt

---

@Eugene-Savenko commented on [Wed Mar 18 2020](https://github.com/AdguardTeam/AdguardFilters/issues/51745#issuecomment-600517371)

@AdguardTeam/filters-maintainers please take a look, it's regarding the LINE extension for Chrome.

---

@AdamWr commented on [Wed Mar 18 2020](https://github.com/AdguardTeam/AdguardFilters/issues/51745#issuecomment-600543550)

It seems that it happens even if all modules are disabled, so it doesn't look like a filters issue.
Adding `gf.line.naver.jp` to HTTPS exclusion fixes this issue on my end.

**Comment by AdamWr** [comment]
Steps to reproduce:
1. Install this extension -https://chrome.google.com/webstore/detail/line/ophjlpahpchlmihnnnihgmmeilfjmjjc/related
2. Open extension
3. Click on "QR Code login"

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/76951756-74e65e80-690c-11ea-9aab-c282001b716c.png)

</details>

AdGuard for Windows version 7.4 nightly 9 (build 3148, CL 1.5.229)

**Comment by ameshkov** [comment]
@AdamWr does disabling https filtering help?

**Comment by AdamWr** [comment]
Adding `gf.line.naver.jp` to HTTPS exclusion fixes the problem, so I guess that disabling HTTPS filtering should helps too.

**Comment by ameshkov** [comment]
Let's add it to the default list of exclusions then

**Comment by AdamWr** [comment]
It seems that adding `gf.line.naver.jp` is not enough - https://github.com/AdguardTeam/AdguardFilters/issues/51745#issuecomment-600991307
Adding `line.naver.jp` resolves the problem, so should we add `line.naver.jp` to HTTPS exclusions or is not good idea?

**Comment by ameshkov** [comment]
@AdamWr is there anything we should block on that domain? If not, it's fine

**Comment by AdamWr** [comment]
It seems that `https://line.naver.jp/` redirects to `https://line.me/en/`, so I guess it will be fine.
