### ISSUE TITLE
AdGuard blocking incoming emails on office365

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/CoreLibs#1283]
If security is enabled, e-mail delivery is blocked.
Disabling all modules and adding the domain to the whitelist does not bring any result.

Info:
- POP3 server: outlook.office365.com;
- Safety: SSL/TLS;
- Port 995;
- Unencrypted password.

User ID: **2583339**
Time/Date: **21.03.2020 |  10:39** 
Logs in NCloud

**Comment by ameshkov** [comment]
What platform is this?

**Comment by Chinaski1** [comment]
**Model**: Sony Xperia Z3 Compact | Android 10
**AdGuard version**: 3.4.40

**Comment by ameshkov** [comment]
@Chinaski1 what app?

There's a chance that working with outlook server may require disabling filtering for the app

**Comment by Chinaski1** [comment]
**K-9 Mail** - Judging by log files HTTPS filtering is OFF in this app

**Comment by ameshkov** [comment]
@Chinaski1 please ask to completely disable filtering for that app, there's definitely nothing else we can do from our side

**Comment by Chinaski1** [comment]
The point is that even a complete shutdown of filtering does not help.
Only disabling the protection.

**Comment by ameshkov** [comment]
@Chinaski1 

I don't know how it is possible, we should try reproducing it.

Also, I am pretty sure this task should be moved to the Android repo, please do it.
