### ISSUE TITLE
Add HTTPS enforcing feature as in "HTTPS Everywhere" browser extension

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#1284]
@sfionov commented on [Fri Jul 15 2016](https://github.com/AdguardTeam/AdguardForAndroid/issues/689)

Most of android browsers does not have capability no install HTTPS enforcing extensions like "HTTPS Everywhere".

It may be a good idea to provide that on filtering level.

---

@zero77 commented on [Fri Sep 08 2017](https://github.com/AdguardTeam/AdguardForAndroid/issues/689#issuecomment-328116418)

It may be a better solution to just send a upgrade-insecure-requests header.
w3.org/TR/upgrade-insecure-requests

---

@TPS commented on [Wed Jan 01 2020](https://github.com/AdguardTeam/AdguardForAndroid/issues/689#issuecomment-570016615)

Maybe (or perhaps in the interim) this is more reasonably a UserScript?  D'y'all know of any that would be compatible w/ AG?

---

@zsoltsandor commented on [Sat Jan 25 2020](https://github.com/AdguardTeam/AdguardForAndroid/issues/689#issuecomment-578324144)

This is a must have, it could also fix some poorly written apps that for some reason use http for certain functions, eg - horribile dictu - relaying notifications.

**Comment by ameshkov** [comment]
I think what we should do here is introduce a new rule modifier that "upgrades" HTTP to HTTPS.
