### ISSUE TITLE
ipv6.google.com - ipv6 issue

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1289]
Original report: https://github.com/AdguardTeam/AdguardFilters/issues/53191

### Issue URL (Incorrect Blocking)
 [http://ipv6.google.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fipv6.google.com)
### Comment
> Не работают сайты по ipv6. Google только для примера, с остальными то же самое

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/omxV02B.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/EYf41bv.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 10.0
AdGuard version: | 3.3.3 (231)
Browser: | Firefox Mobile
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing third-party cookies (180), Block WebRTC, Block Push API
AdGuard mode: | proxy
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Language-specific:</b><br/> AdGuard Russian

**Comment by ameshkov** [comment]
Без логов это бесполезно:(
