### ISSUE TITLE
Missed tracking parameters: mc_cid, mc_eid

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/CoreLibs#1292]
@bestpika commented on [Mon Apr 13 2020](https://github.com/AdguardTeam/AdguardForWindows/issues/3266)

I found some email's link have these tracking parameters: `mc_cid`, `mc_eid`.
Please add these parameters to the default list.
Thank you.

(These parameters is created by Mailchimp.)

---

@TheHasagi commented on [Tue Apr 14 2020](https://github.com/AdguardTeam/AdguardForWindows/issues/3266#issuecomment-613309196)

@bestpika 

Thank you for the reporting! You can manually add these tracking parameters to the default list by yourself, soon we will update the default list.

**Comment by ameshkov** [comment]
Merged into: #1184
