### ISSUE TITLE
Cosmetic rules can be used as CSS rules

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1293]
I mean that at the moment we can also use `##` instead of `#$#` and CSS rule will be applied.

Steps to reproduce:
1. Add this rule:
`example.org##body { background: red!important; }`
2. Go to - http://example.org/

It also allows to use `url(...)` and if I understand correctly it shouldn't be allowed - https://github.com/AdguardTeam/CoreLibs/issues/1026, https://github.com/AdguardTeam/CoreLibs/issues/659#issuecomment-472826518

Example:
```
example.org##body { background: lightblue url("https://www.w3schools.com/cssref/img_tree.gif") no-repeat fixed center!important; }
```

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/79440834-c3078400-7fd6-11ea-802c-8633d9595d6a.png)

</details>

AdGuard for Windows 7.4 nightly 17 (build 3185, CL 1.5.241)

**Comment by ameshkov** [comment]
@sxgunchenko please check what's wrong with the element hiding rules validation

**Comment by sxgunchenko** [comment]
ok

**Comment by sxgunchenko** [comment]
core/pull-requests/1835

**Comment by AdamWr** [comment]
It seems that it's still possible.
Example:
```
example.org##body\{\}, body { background: lightblue url("https://www.w3schools.com/cssref/img_tree.gif") no-repeat fixed center!important; }
```

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/79987500-c9ea3700-84ad-11ea-8db0-8cd31e23d556.png)

</details>

**Comment by sxgunchenko** [comment]
thanks, fixed in core/pull-requests/1855

**Comment by AdamWr** [comment]
Probably one more example:
```
example.org##body /*({})*/ { background: lightblue url("https://www.w3schools.com/cssref/img_tree.gif") no-repeat fixed center!important; }
```

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/80512386-b3e0e880-897d-11ea-9e00-e5f476ff3ac0.png)

</details>

It also works with CSS rules `#$#`, but I think it shouldn't:
```
example.org#$#body /*({})*/ { background: lightblue url("https://www.w3schools.com/cssref/img_tree.gif") no-repeat fixed center!important; }
```

**Comment by sxgunchenko** [comment]
fixed in core/pull-requests/1872

**Comment by AdamWr** [comment]
Seems to be still possible:
```
example.org##\\/*[*/, body { background: lightblue url("https://www.w3schools.com/cssref/img_tree.gif") no-repeat fixed center!important; } ,\/*]
```

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/80837471-1ee92400-8bf7-11ea-9eb3-00f84158d98c.png)

</details>

**Comment by ameshkov** [comment]
@AdamWr good job!

**Comment by sxgunchenko** [comment]
fixed in core/pull-requests/1883

**Comment by AdamWr** [comment]
One more example:
```
example.org##body:not(blabla/*[*/) { background: lightblue url("https://www.w3schools.com/cssref/img_tree.gif") no-repeat fixed center!important; } /*]*\/
```

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/81484555-7f571180-9246-11ea-8a93-818c06e641f1.png)

</details>
