### ISSUE TITLE
"Hide user agent" causes Google to use desktop website layout

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1295]
Reproducible on Android with Firefox 68.7.0

Without Hide-UA:

<details>

![image](https://user-images.githubusercontent.com/5947035/80355187-70548480-8880-11ea-9d9c-df405ce6251a.png)
</details>

With Hide-UA:

<details>

![image](https://user-images.githubusercontent.com/5947035/80355203-75193880-8880-11ea-92a4-767e8a769c6b.png)
</details>

**Comment by ngorskikh** [comment]
Couldn't repro on android master + corelibs stable-1.5, nor with v3.4 nightly 20 :( In my case the user agent doesn't change unless a custom user agent is set.
Maybe it's device-specific?

**Comment by ameshkov** [comment]
Most likely it is
