### ISSUE TITLE
gifts.marriott.com is broken

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1300]
Original issue: https://github.com/AdguardTeam/AdguardFilters/issues/55357

**Steps to reproduce:**

1. Open https://gifts.marriott.com/e-gifts/

The same problem when `Adblocker`, `Stealth mode` and `Extensions` are disabled, but protection is enabled. When protection is enabled, `https://gifts.marriott.com/cws40_svc/marriottcons/consumer/dc_1005.rpc` cannot be loaded(code 400)

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/82075154-7e116300-96e4-11ea-8729-88957ee10150.png)

</details>

Reproduced with current nightly builds(7.3 is in original report)

**Comment by sfionov** [comment]
Not reproducable with 1.8
