### ISSUE TITLE
dec.fazenda.df.gov.br - HTTPS filtering issue

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1301]
@adguard-bot commented on [Tue May 19 2020](https://github.com/AdguardTeam/AdguardFilters/issues/55728)

### Issue URL (Incorrect Blocking)
 [https://dec.fazenda.df.gov.br/senfa.restrito/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fdec.fazenda.df.gov.br%2Fsenfa.restrito%2F)
### Comment
Username: @paulolobo78
> É um site para emissão de notas no Distrito Federal - Brasil. O site só funciona com o adguard completamente desligado. Eu preciso encerrar processo no gerenciador de tarefas para o site carregar.
> --
> A informação abaixo é gerada automaticamente. Não a apague.
> 
> Referrer:
> 
> 
> Custom userscripts:
> https://userscripts.adtidy.org/beta/assistant/4.3/assistant.user.js
> https://userscripts.adtidy.org/beta/popup-blocker/2.5/popupblocker.user.js
> https://userscripts.adtidy.org/beta/adguard-extra/1.0/adguard-extra.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/xM6WjlS.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/FitJ7e6.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 7.4 nightly 29
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Self-destructing third-party cookies (180)
Filters: | <b>Ad Blocking:</b><br/> EasyList, <br/>Peter Lowe's Blocklist, <br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> EasyPrivacy, <br/>Fanboy's Enhanced Tracking List, <br/>Fanboy Anti-Facebook List, <br/>Fanboy's Anti-thirdparty Fonts, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> Fanboy's Social Blocking List, <br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> Fanboy's Annoyances, <br/>Web Annoyances Ultralist, <br/>Adblock Warning Removal List, <br/>I don't care about cookies, <br/>EasyList Cookie List, <br/>AdGuard Annoyances<br/><br/><b>Other:</b><br/> AdGuard Experimental<br/><br/><b>Language-specific:</b><br/> ABP Japanese Filters, <br/>AdGuard Russian, <br/>AdGuard German, <br/>AdGuard Dutch, <br/>AdGuard Spanish/Portuguese
Other extensions used: | não uso

**Comment by wanesoft** [comment]
https://github.com/AdguardTeam/HttpsExclusions/pull/296
