### ISSUE TITLE
yasobe.ru

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1302]
@adguard-bot commented on [Tue May 26 2020](https://github.com/AdguardTeam/AdguardFilters/issues/56152)

### Issue URL (Incorrect Blocking)
 [https://yasobe.ru/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fyasobe.ru%2F)
### Comment
Username: @Radionucleid
> 
> --
> Информация ниже сгенерирована автоматически, не удаляйте ее.
> 
> Referrer:
> 
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
> https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
> https://userscripts.adtidy.org/release/adguard-wot/1.0/wot.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/Ja4y6v9.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/4hpwaMZ.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 7.4
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing third-party cookies (180), Disable cache for third-party requests, Block WebRTC, Block Push API, Block Location API, Block Flash, Block Java
Filters: | <b>Ad Blocking:</b><br/> EasyList, <br/>Peter Lowe's Blocklist, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> EasyPrivacy, <br/>Fanboy's Enhanced Tracking List, <br/>Fanboy Anti-Facebook List, <br/>Fanboy's Anti-thirdparty Fonts, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> Fanboy's Social Blocking List, <br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> Fanboy's Annoyances, <br/>Web Annoyances Ultralist, <br/>Adblock Warning Removal List, <br/>I don't care about cookies, <br/>EasyList Cookie List, <br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/> Malware Domains Blocklist, <br/>Spam404, <br/>NoCoin Filter List<br/><br/><b>Other:</b><br/> BarbBlock, <br/>AdGuard Simplified domain names, <br/>AdGuard Experimental<br/><br/><b>Language-specific:</b><br/> RU AdList, <br/>RU AdList: Counters, <br/>RU AdList: BitBlock, <br/>AdGuard Russian

---

@Alex-302 commented on [Mon Jun 01 2020](https://github.com/AdguardTeam/AdguardFilters/issues/56152#issuecomment-636695012)

@Radionucleid У меня не повторяется. Можете прислать отладочные(подробные) логи на support@adguard.com с указанием ссылки на эту задачу?
Как включить расширенное логирование:
https://kb.adguard.com/ru/windows/solving-problems/adguard-logs

---

@Radionucleid commented on [Mon Jun 01 2020](https://github.com/AdguardTeam/AdguardFilters/issues/56152#issuecomment-636839448)

Отправил. 
Вот видео так же https://yadi.sk/d/Fn_ebpLfke4eSA

---

@Eugene-Savenko commented on [Tue Jun 02 2020](https://github.com/AdguardTeam/AdguardFilters/issues/56152#issuecomment-637365815)

USER ID 2456532.

---

@Radionucleid commented on [Tue Jun 02 2020](https://github.com/AdguardTeam/AdguardFilters/issues/56152#issuecomment-637685271)

> USER ID 2456532.

и что это значит?

---

@Alex-302 commented on [Tue Jun 02 2020](https://github.com/AdguardTeam/AdguardFilters/issues/56152#issuecomment-637736369)

Это для меня.

В логе ничего подозрительного не вижу. Если выключить все фильтры проблема повторяется?

---

@Radionucleid commented on [Wed Jun 03 2020](https://github.com/AdguardTeam/AdguardFilters/issues/56152#issuecomment-638268600)

Последовательно отключал полностью антибаннер, антитрекеринг, антифишинг, расширения и  так и не добился нормальной работы сайта. Работает через раз. что-то отключишь заработает, потом перестает. Отправил ещё логи, там выполнял различные отключения фильтров итд итп, чистил кеш броузера идт итп

**Comment by Alex-302** [comment]
Another report with logs
https://github.com/AdguardTeam/AdguardFilters/issues/57328

**Comment by sxgunchenko** [comment]
@Alex-302 seems like we should that domain in the ssl exclusions

**Comment by Alex-302** [comment]
But why it is broken?

**Comment by sxgunchenko** [comment]
For some reason the server closes connection just after we sending a request.

**Comment by AdamWr** [comment]
Is not caused by Stealth mode and AdGuard Popup Blocker?
I can reproduce this issue and if I disable stealth mode and extensions module then website loads fine.
Also adding:
```
@@||yasobe.ru^$extension
@@||yasobe.ru^$stealth
```
fixes that issue on my end.

**Comment by ameshkov** [comment]
User-agent may be causing this

**Comment by AdamWr** [comment]
It seems that it happens even if all options in stealth mode are disabled, but stealth mode is enabled.

**Comment by sxgunchenko** [comment]
Hm, it seems like the issue resides in the stealth mode script. If it's not injected, the page works fine.

**Comment by ameshkov** [comment]
Weird. Let's fix it in 1.6

**Comment by Radionucleid** [comment]
> @@||yasobe.ru^$extension
> @@||yasobe.ru^$stealth

Да таким образом сайт открылся у меня
