### ISSUE TITLE
Add $denyallow modifier

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1304]
>The purpose of denyallow is bring default-deny/allow-exceptionally ability into static network filtering arsenal.
>
>Example:
>>*$3p,script,denyallow=x.com|y.com,domain=a.com|b.com
>
>The above filter tells the network filtering engine that when the context is a.com or b.com, block all 3rd-party scripts except those from x.com and y.com.

Description - https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#denyallow

**Comment by ameshkov** [comment]
Let's wait and see how the adoption of it goes

**Comment by ameshkov** [comment]
This rule:

`*$third-party,script,denyallow=x.com|y.com,domain=a.com|b.com`

Basically translates into these three (more or less):
```
*$third-party,script,domain=a.com|b.com
@@||x.com^$third-party,script,domain=a.com|b.com
@@||y.com^$third-party,script,domain=a.com|b.com
```

The point to have `denyallow` is to avoid creating additional "exception" rules as it might be legit to continue to block some URLs from these domains.

I don't fully understand, why in this case we're limiting this type of rules to those that have `$domain` modifier.

@sxgunchenko let's start implementing any filter-related task with writing a full spec. Only when the spec is ready, it is time to start implementing it.

**Comment by sxgunchenko** [comment]
So the spec could look like that:

##### **`denyallow`**

`denyallow` allows to avoid creating additional "exception" rules if it is not needed to block requests to some domains. To add multiple domains to one rule, use the `|`  character as a separator.

Basically adding this modifier to a rule:
```
*$script,domain=a.com|b.com,denyallow=x.com|y.com
```
is equivalent to excluding the domains by the rule's matching pattern:
```
/^(?!.*(x.com|y.com)).*$/$script,domain=a.com|b.com
```
or to adding the corresponding exclusions:
```
*$script,domain=a.com|b.com
@@||x.com$script,domain=a.com|b.com
@@||y.com$script,domain=a.com|b.com
```

> Please note that rules with the `$denyallow` modifier have the following restrictions:
> * the rule's matching pattern cannot target any domain (e.g., it does not start with `||`)
> * domains in the modifier's parameter cannot be negated (`$denyallow=~x.com`) or have a wildcard TLD (`$denyallow=x.*`)
>
> The rules which violate these restrictions are considered invalid.
