### ISSUE TITLE
Partial HTML processing issues

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1308]
@adguard-bot commented on [Sat Jun 13 2020](https://github.com/AdguardTeam/AdguardFilters/issues/57303)

### Issue URL (Annoyance)
 [https://www.amd.com/ru/support/chipsets/amd-socket-am4/b350](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.amd.com%2Fru%2Fsupport%2Fchipsets%2Famd-socket-am4%2Fb350)
### Comment
> Отсутствует помощник Adguard
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
> https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/4EHkJF3.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 7.4.2
Browser: | Firefox
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, Strip URLs from tracking parameters, Disable cache for third-party requests
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Security:</b><br/> NoCoin Filter List<br/><br/><b>Other:</b><br/> AdGuard Experimental<br/><br/><b>Language-specific:</b><br/> EasyList Dutch, <br/>Liste FR, <br/>ROList, <br/>ROLIST2, <br/>road-block, <br/>Frellwit's Swedish Filter, <br/>Dandelion Sprout's Nordic Filters, <br/>AdGuard French, <br/>AdGuard Russian, <br/>AdGuard German

**Comment by AdamWr** [comment]
It seems that sometimes AdGuard's JS is not injected on this page.
Steps to reproduce:
1. Add this rule:
`amd.com##body`
2. Go here -  [https://www.amd.com/ru/support/chipsets/amd-socket-am4/b350](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.amd.com%2Fru%2Fsupport%2Fchipsets%2Famd-socket-am4%2Fb350)
3. It doesn't happen everytime, so please refresh website few times

Website should be blank, but sometimes AdGuard's JS is not injected.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/84647730-1c6f2f00-af04-11ea-929e-c5033ed916ca.png)

</details>

**Comment by sxgunchenko** [comment]
core/pull-requests/1946
