### ISSUE TITLE
Change "too wide" rules definition

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1309]
Currently, we define the rule is dangerous and "too wide" if the following conditions are true:

1. The rule matches ALL URLs
2. No domain limitations

We should change point 2 to:

2. No domain and app limitations

**Comment by sxgunchenko** [comment]
Hm, as i see we consider rule too wide if it meets the following conditions:
1) no enabled domains (note that *enabled* corresponds to `$domain=example.com`, not to `$domain=~example.com`)
2) no enabled application (the same for *enabled*)
3) no `$cookie` modifier
4) no `$removeparam` modifier
5) the rule matches any url

Do we need to change something?

**Comment by ameshkov** [comment]
Huh, I guess I missed that about the applications, I thought we only check the domain.
