### ISSUE TITLE
Add support of rules for blocking everything third-party content, except specific domains on the site

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1310]
Sample regexp rule:
`/^(?!.*(google\.com|gstatic\.com|googleapis\.com|shrink\.pe|recaptcha\.net|facebook\.net|cloudflare\.com|dmca\.com|disqus\.com|vidazoo\.com|disquscdn\.com|fluidplayer\.com)).*$/$third-party,script,domain=canyoublockit.com|aii.sh`
it blocks all third-party scripts, except domains, listed in regexp.

https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#denyallow

**Comment by ameshkov** [comment]
As I recall, uBO has come up with the syntax for this kind of rules. Please remind what's it

**Comment by AdamWr** [comment]
If I'm not wrong, it's the same feature request as here - https://github.com/AdguardTeam/CoreLibs/issues/1304

**Comment by ameshkov** [comment]
Yeah, duplicate
