### ISSUE TITLE
The filter ID of the triggered rule for a blocked request is not defined correctly.

### ISSUE THREAD

**Issue by TimusBel** [AdguardTeam/CoreLibs#1312]
The filter ID of the triggered rule for a blocked request is not defined correctly. It's seen on Filtering log.
[screen_shot](https://uploads.adguard.com/Timur5pl81.png)
CL version 1.6.114
To reproduce in Adguard for Windows: 

1. open Filter Editor
2. open Filtering log 
3. open ok.ru in any browser
4. search in corresponding filter rules for any rule for a blocked request if the filter has been defined as user rules or not defined at all

**Comment by TimusBel** [comment]
[https://uploads.adguard.com/Timur5pl81.png](url)

**Comment by TimusBel** [comment]
CL version 1.6.114

**Comment by adbuker** [comment]
related to https://github.com/AdguardTeam/AdguardForWindows/issues/3391
