### ISSUE TITLE
Mi Router 4A Giga Version login website is broken

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1313]
@adguard-bot commented on [Mon Jul 06 2020](https://github.com/AdguardTeam/AdguardFilters/issues/58724)

### Issue URL (Incorrect Blocking)
 [http://192.168.31.1/cgi-bin/luci/web](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2F192.168.31.1%2Fcgi-bin%2Fluci%2Fweb)
### Comment
> My Mi Router 4A Giga Version login website is broken when I enable AdGuard (Exactly with Stealth Mode Enabled)
> --
> The information below is automatically generated. Do not delete it.
> 
> Referrer:
> http://192.168.31.1/cgi-bin/luci/;stok=0823c8519ad048d8fcafa61d797471b6/web/home
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/u8Sk6yo.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/rS1XPeC.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.4.2
Browser: | Edge 83.0.478.58 (Chromium-based)
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br/>Send Do-Not-Track header, <br/>Remove X-Client-Data header from HTTP requests, <br/>Self-destructing third-party cookies (180), <br/>Block WebRTC, <br/>Block Push API, <br/>Hide your IP address (1.2.3.4)
Filters: | <b>Ad Blocking:</b><br/> EasyList, <br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> EasyPrivacy, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> Adblock Warning Removal List, <br/>EasyList Cookie List, <br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/> Malware Domains Blocklist<br/><br/><b>Other:</b><br/> AdGuard Simplified domain names<br/><br/><b>Language-specific:</b><br/> Liste AR, <br/>AdGuard Turkish, <br/>AdGuard Russian

**Comment by ameshkov** [comment]
I investigated this issue once and tbh I have zero idea what's wrong. The only fix is to exclude it: `@@192.168.31.1^$network`
