### ISSUE TITLE
Adguard FW 7.5 nightly randomly crashing after adding Spotify UWP exe to filtering apps

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/CoreLibs#1317]
Adguard for Windows Nightly randomly crash service after adding and start filtering Spotify UWP EXE.
Disabling or removing rule fixing crashing. 
[logs.zip](https://github.com/AdguardTeam/CoreLibs/files/4941171/logs.zip)

**Comment by ameshkov** [comment]
@adbuker please take a look

**Comment by ameshkov** [comment]
@FadeMind have you sent a crash report from the app?

**Comment by FadeMind** [comment]
@ameshkov I create only this ISSUE and after sent logs, rollback to stable 7.4.x release - here all works as expected.

**Comment by FadeMind** [comment]
@ameshkov bumping against LOGS in ZIP file in my previous post.

**Comment by FadeMind** [comment]
OK. After FRESH install Nightly without import settings I setup again ADG. Added Spotify UWP EXE to filtered app. Closing Adguard Window. Opening Spotify UWP app AAAND: Adguard just crashed.

**Comment by FadeMind** [comment]
@ameshkov NOTICE: This crash issue happen ONLY with Spotify UWP from MS Store directly.

Standalone Spotify Client from installer `SpotifySetup.exe` and exe file `%APPDATA%\Spotify\Spotify.exe`  works FINE with Adguard for Windows.

**Comment by sxgunchenko** [comment]
Should've been fixed in CoreLibs v1.7.1.
@FadeMind are you able to reproduce it with the latest nightly?

**Comment by FadeMind** [comment]
@sxgunchenko ADG 7.5 n 15 here aaand seems got fixed. Thanks <3

**Comment by sxgunchenko** [comment]
Great, thanks for your feedback :)
