### ISSUE TITLE
DNS requests blocking don't work

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1319]
### Steps to reproduce

1. Enable DNS option in AdGuard settings
2. Add this rule to user filter:
`||example.org^`
3. Go here - http://example.org/

### Expected behavior
I think that `example.org` request/website should be blocked.

### Actual behavior
Requests/website is not blocked.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/88204160-314d8980-cc4b-11ea-97e1-9cebdc4a06a5.png)

</details>

### Your environment

* AdGuard for Windows 7.5 nightly 11 (build 3312, CL 1.7.2)

**Comment by ameshkov** [comment]
Not a bug, we're not going to support DNS queries blocking in v7.5

**Comment by ameshkov** [comment]
And there should be no "Block" button there

**Comment by AdamWr** [comment]
Okay, I thought that it should works like in AdGuard for Android.
Thank you for your answer.

**Comment by ameshkov** [comment]
It will be like that in the future, but we're starting slow, with DNS encryption only
