### ISSUE TITLE
Check that trusted-types CSP does not break the content script

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1320]
https://security.googleblog.com/2020/07/towards-native-security-defenses-for.html

Create a test server that returns CSP: require-trusted-types: '....'

There should be support for this directive in AG CoreLibs as well.

**Comment by wanesoft** [comment]
@Voltairine-de-Cleyre thanks for the advice. we are processing the `require-trusted-types-for` directive properly.
