### ISSUE TITLE
Check that HTTPS outbound proxy is properly supported

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1321]
Please check what's wrong with NordVPN's HTTP SSL proxies. If this is what I think it is, it should work with AG for Android.

> @ameshkov 
> AG doesn't support NordVPN's HTTP Proxy (SSL) and HTTP CyberSec Proxy (SSL).
> Why?
> I think AG only supports HTTP proxy, not HTTPS proxy.
> Find a proxy server if you have a NordVPN account.
> https://nordvpn.com/servers/tools/

> _Originally posted by @lancelot-moon in https://github.com/AdguardTeam/AdguardForAndroid/issues/1356#issuecomment-663879022_

**Comment by lancelot-moon** [comment]
If AG uses a NordVPN proxy server which only has HTTPS proxy without HTTP proxy, no internet.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/Qq7HQ52.png)
</details><br/>

**Comment by ngorskikh** [comment]
The problem with NordVPN `HTTPS` servers is they don't seem to speak TLS: 
```
➜  source openssl s_client -debug -connect se409.nordvpn.com:443
CONNECTED(00000005)
write to 0x7fd75f2044b0 [0x7fd760012a03] (196 bytes => 196 (0xC4))
0000 - 16 03 01 00 bf 01 00 00-bb 03 03 42 ca 11 ff 3c   ...........B...<
0010 - df ef 9c 4e f0 db 6b 3b-85 0e 1c 49 37 d1 4a 94   ...N..k;...I7.J.
0020 - 2c 41 c5 f7 95 99 82 1e-4a fa a3 00 00 5c c0 30   ,A......J....\.0
0030 - c0 2c c0 28 c0 24 c0 14-c0 0a 00 9f 00 6b 00 39   .,.(.$.......k.9
0040 - cc a9 cc a8 cc aa ff 85-00 c4 00 88 00 81 00 9d   ................
0050 - 00 3d 00 35 00 c0 00 84-c0 2f c0 2b c0 27 c0 23   .=.5...../.+.'.#
0060 - c0 13 c0 09 00 9e 00 67-00 33 00 be 00 45 00 9c   .......g.3...E..
0070 - 00 3c 00 2f 00 ba 00 41-c0 11 c0 07 00 05 00 04   .<./...A........
0080 - c0 12 c0 08 00 16 00 0a-00 ff 01 00 00 36 00 0b   .............6..
0090 - 00 02 01 00 00 0a 00 08-00 06 00 1d 00 17 00 18   ................
00a0 - 00 23 00 00 00 0d 00 1c-00 1a 06 01 06 03 ef ef   .#..............
00b0 - 05 01 05 03 04 01 04 03-ee ee ed ed 03 01 03 03   ................
00c0 - 02 01 02 03                                       ....
read from 0x7fd75f2044b0 [0x7fd76000e803] (5 bytes => 0 (0x0))
4636388972:error:140040E5:SSL routines:CONNECT_CR_SRVR_HELLO:ssl handshake failure:/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-47.140.1/libressl-2.8/ssl/ssl_pkt.c:585:
```
Or with BoringSSL:
```
➜  tool ./bssl s_client -debug -connect se409.nordvpn.com:443 
Connecting to 31.13.191.136:443
Handshake started.
Handshake progress: TLS client enter_early_data
Handshake progress: TLS client read_server_hello
Error while connecting: peer closed connection
```
I've tried a few different servers and ports other than 443 -- no luck. NordVPN doesn't seems to have any kind of documentation for their HTTPS proxies. I suspect they mean something else by "HTTPS proxy"...

**Comment by ngorskikh** [comment]
Turns out they are using port 89 for "HTTPS proxy". 
AdGuard's HTTPS_CONNECT mode works.

**Comment by lancelot-moon** [comment]
For Port type 1080 (if using Socks5) or 80 (if using HTTP) and make sure you check the following boxes.

I didn’t see about port 89 for HTTPS proxy before.
Thanks.
