### ISSUE TITLE
Can't filter localhost in network extension mode

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#1322]
https://github.com/AdguardTeam/AdguardForMac/issues/692#issuecomment-664089744

We have system proxy detection in new mode but user reported that it is not filtered.

**Comment by Hackl0us** [comment]
I use [Surge](https://nssurge.com)

I have tested several times, I'm pretty sure that AdGuard won't filter ads when Surge is enable (Set as System Proxy).

I would like to offer you more details.

**Comment by ngorskikh** [comment]
Looks like traffic bound to 127.0.0.1 is not being filtered in network extension mode.
@Hackl0us please add Surge to the list of filtered apps explicitly while we work this out

**Comment by Hackl0us** [comment]
> Looks like traffic bound to 127.0.0.1 is not being filtered in network extension mode.
> 
> @Hackl0us please add Surge to the list of filtered apps explicitly while we work this out

Thank you for your reply. The weird thing is that even I added Surge in the Filter List, it still didn't work as expected.

And it will cause a extremely slow net speed 🥶

**Comment by ngorskikh** [comment]
@Hackl0us We need logs to investigate the slowdown. Please enable debug logging (Advanced -> Logging Level), reproduce the issue, then export (Advanced -> Export Logs...) the logs. Send the file to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced. 
Also please share how exactly Surge is configured in your case.

**Comment by Hackl0us** [comment]
@ngorskikh Sure thing! Thanks again for your quick response. I will do this right now.

**Comment by ngorskikh** [comment]
@Hackl0us Thank you for your patience and cooperation! We're working on a solution. Right now, the only workaround would be to use the older kernel extension mode, unfortunately. Sorry for the temporary inconvenience.

**Comment by Hackl0us** [comment]
@ngorskikh No problem,bro. Thank you so much for your patience as well.

I really appreciate you and your team's hard work, and I'm very glad to be an AdGuard user. 

I am a Java Developer, so I really understand how boring the debug work is. Please take your time to find the solution. I would switch to Safari Extension in this period of time.

Thanks again 😁 If you need more details, just mention me under this thread, I will reply ASAP.

**Comment by zzebrum** [comment]
> @owenzhao

> Just upgrade to 2.5.0.844 nightly (CL-1.7.56). The above work around, adding proxy to Filtered Apps no longer work. Websites that goes through proxy can't be opened any longer. Besides, removing the ClashXR from Filtered Apps and no ads will be blocked again.
> 
> So for me, the new version is worse than the old nightly. There is no way to block any ads by AdGuard.
> 
> The work around worked again after a system reboot. Maybe AdGuard should requests a user to reboot after upgrade to take effect the new extension.

@sfionov @ngorskikh please, take a look.

**Comment by sfionov** [comment]
Reported to Apple
Feedback ID: FB8486799
Forum topic: https://developer.apple.com/forums/thread/657762

**Comment by ngorskikh** [comment]
I've asked Apple about this: https://developer.apple.com/forums/thread/666130
