### ISSUE TITLE
Browsing security + AdGuard DNS leads to slowdown

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1324]
@skipik commented on [Tue Jun 23 2020](https://github.com/AdguardTeam/AdguardForWindows/issues/3384)

### Steps to reproduce

1. Включил в роутере Keenetic фильтр AdGuard DNS - "без рекламы"
2. Установил AdGuard for Windows 7.5 nightly 2 (build 3259, CL 1.6.109)
3. Пробую открывать и обновлять странички в браузере (Opera 68)
4.

### Expected behavior

Странички будут обновляться в обычном режиме - то есть быстро
### Actual behavior

После включения фильтра AdGuard DNS - "без рекламы", браузер стал открывать и обновлять страницы дольше обычного. Помогает отключения модуля "Антифишинг" в AdGuard. Началось с первой же ночной сборки 7.5. На предыдущей линейке 7.4 не было замечено подобного.

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Environment name and version: Opera 68.0.3618.173, AdGuard for Windows 7.5 nightly 2 (build 3259, CL 1.6.109)
* Operating system and version: Microsoft Windows 10 Enterprise (x64) Build 19041.329 (2004/May 2020 Update)

---

@skipik commented on [Tue Jun 23 2020](https://github.com/AdguardTeam/AdguardForWindows/issues/3384#issuecomment-648346026)

> обновлять страницы дольше обычного

Имеется ввиду, что долго крутится loading circle на месте favicon. Это сразу заметно.
Если нужны логи адгарда, то дайте знать, соберу и отправлю на почту. :)

UPD: хотя, тут, наверное, har-логи ещё нужны будут...

---

@adbuker commented on [Fri Jun 26 2020](https://github.com/AdguardTeam/AdguardForWindows/issues/3384#issuecomment-650166317)

@skipik, не могли бы Вы включить трейс-логигирование, [выгрузить](https://uploads.adguard.com/buker-bolm1.png) логи и отправить на почту. 
Для того, чтобы запустить трей-логгирование
1. выключите AdGuard (не оставляя службу в фоновом режиме)
2. в папке `%programfiles(x86)%/Adguard` с помощью командной строки запустите `Adguard.exe /trace`
3. после запуска AdGuard включите детальный уровень логгирования (если он был включен до этого, сделайте изменение уровня логгирования туда-сюда)

---

@skipik commented on [Fri Jun 26 2020](https://github.com/AdguardTeam/AdguardForWindows/issues/3384#issuecomment-650174118)

@adbuker так, сделал, надеюсь, что всё правильно получилось.
- запустил Adguard.exe /trace
- включил детальные логи
- зашёл в Opera на vk.com
- долго крутился кружок на вкладке
- экспортировал логи
Повторюсь, что помогает отключение модуля "Антифишинг" и это воспроизводится, если в роутере Keenetic включён фильтр AdGuard DNS "без рекламы".
Логи отправил на devteam.

---

@adbuker commented on [Fri Jun 26 2020](https://github.com/AdguardTeam/AdguardForWindows/issues/3384#issuecomment-650181653)

Да, спасибо, логи записались как надо. Трейсовые логи сильно замедляют фильтрацию, поэтому рекомендую Вам выключить их. Для этого снова выключите AdGuard (не оставляя службу в фоновом режиме) и просто запустите его снова уже без параметра

---

@skipik commented on [Fri Jun 26 2020](https://github.com/AdguardTeam/AdguardForWindows/issues/3384#issuecomment-650184388)

Да, это я в курсе, спасибо. Перезапустил AdGuard в обычном режиме и пока работаю с выключенным модулем Антифишинга.

---

@adbuker commented on [Fri Jun 26 2020](https://github.com/AdguardTeam/AdguardForWindows/issues/3384#issuecomment-650188712)

Отлично, по факту новостей - обязательно отпишу тут

---

@skipik commented on [Sun Jul 19 2020](https://github.com/AdguardTeam/AdguardForWindows/issues/3384#issuecomment-660661124)

@adbuker есть какие-то новости по проблеме?

---

@skipik commented on [Wed Jul 22 2020](https://github.com/AdguardTeam/AdguardForWindows/issues/3384#issuecomment-661807768)

Почти месяц прошёл. Анализов логов выявил проблему?

---

@skipik commented on [Fri Jul 31 2020](https://github.com/AdguardTeam/AdguardForWindows/issues/3384#issuecomment-667137876)

@adbuker @northis @ameshkov данная проблема будет вообще правиться в рамках 7.5 ?

**Comment by skipik** [comment]
Особенно явно воспроизводится, если поискать что-то на google.com. Там колёсико на вкладке прямо долго крутится.
Если потребуются новые логи, то дайте знать. :)

**Comment by ameshkov** [comment]
@skipik да, логи потребуется с последней версии

**Comment by skipik** [comment]
@ameshkov текущая найтли 17 подойдёт или лучше дождаться следующей (18?) ?

**Comment by ameshkov** [comment]
@skipik подойдет

**Comment by skipik** [comment]
@ameshkov Ок. Собрал новые логи и отправил на devteam-почту. ;)

**Comment by ameshkov** [comment]
Насколько я помню, у вас очень странная тема была - почему-то таймаутились соединения к AdGuard DNS (а антифишинг сейчас через него работает).

> После включения фильтра AdGuard DNS - "без рекламы", браузер стал открывать и обновлять страницы дольше обычного. Помогает отключения модуля "Антифишинг" в AdGuard.

Может ли Кинетик себя странно вести и обрубать соединения к нашем же IP адресам в таком случае?

**Comment by skipik** [comment]
@ameshkov 
> https://dns-family.adguard.com/ -- не зависает ли в браузере?

Не открывается, кстати. Не удается получить доступ к сайту, ERR_CONNECTION_TIMED_OUT.
Антифишинг в AdGuard сейчас выключен. В кинетике включён фильтр AdGuard DNS - без рекламы.

**Comment by ameshkov** [comment]
Может быть имеет смысл в кинетик написать, что-то они делают не так

**Comment by skipik** [comment]
Есть вот такая выдержка из хелпа: При включенном AdGuard DNS не проходит проверка состояния работы сервиса на страницах https://adguard.com/ru/adguard-dns/overview.html и https://adguard.com/ru/test.html
Это связано с тем, что при включенных интернет-фильтрах по умолчанию включается блокировка транзитного DoT/DoH, чтобы избежать утечки DNS-запросов.
Это может быть причиной?

**Comment by ameshkov** [comment]
Да, это и есть причина, и это ну ОЧЕНЬ странное решение.

**Comment by ameshkov** [comment]
В общем проблема в том, что мы это поправить не сможем со своей стороны, нам тут целенаправленно трафик зарезали получается.

Единственное - было бы чуть проще нам жить, если бы трафик не дропался, а ресетился, так хотя бы замедления никакого не будет.

**Comment by skipik** [comment]
Понял, спасибо за помощь! Я попробую написать кинетикам по этому вопросу.
