### ISSUE TITLE
The script from greasyfork.org doesn`t work properly with AdGuard

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1327]
@adguard-bot commented on [Sat Aug 08 2020](https://github.com/AdguardTeam/AdguardFilters/issues/61094)

### Issue URL (Incorrect Blocking)
 [https://www.youku.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.youku.com%2F)
### Comment
> This script from greasyfork.org doesn`t work properly with Adguard : https://greasyfork.org/scripts/375881-bilibili-%E6%B8%AF%E6%BE%B3%E5%8F%B0/code/Bilibili%20%E6%B8%AF%E6%BE%B3%E5%8F%B0.user.js
> However, this script from Tampermonkey, which has the same features that the one above, works properly: https://pxer-app.pea3nut.org/pxer.user.js

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/3q8oZ7v.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/z5iVSZx.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.4.2
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br/>Send Do-Not-Track header, <br/>Remove X-Client-Data header from HTTP requests, <br/>Self-destructing third-party cookies (180)
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Language-specific:</b><br/> EasyList China

**Comment by sfionov** [comment]
There's no such script anymore
