### ISSUE TITLE
Cannot ssh to MacOS (Big Sur public beta 1) after installing Adguard nightly

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/CoreLibs#1329]
@tarobun commented on [Thu Aug 13 2020](https://github.com/AdguardTeam/AdguardForMac/issues/724)

### Steps to reproduce

1. Start Adguard
2. Attempt to connect to MacOS from external source
3.
4.

### Expected behavior
ssh connection works

### Actual behavior
Cannot connect from externally.

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59):
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)
Adguard version: 2.5.0.838 nightly

**Comment by sfionov** [comment]
Reported to Apple: https://developer.apple.com/forums/thread/657762
Feedback ID: FB8486799

**Comment by sfionov** [comment]
Workaround will be in the next Mac nightly.
