### ISSUE TITLE
forumpravo.by cannot be loaded

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1332]
@adguard-bot commented on [Fri Aug 28 2020](https://github.com/AdguardTeam/AdguardFilters/issues/62588)

### Issue URL (Incorrect Blocking)
 [https://forumpravo.by/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fforumpravo.by%2F)
### Comment
Username: @zubrRB
> ERR_EMPTY_RESPONSE
> --
> Информация ниже сгенерирована автоматически. Не удаляйте ее.
> 
> Referrer:
> https://forumpravo.by/
> 
> Custom userscripts:
> https://github.com/Owyn/HandyImage/raw/master/HandyImage.user.js
> https://greasyfork.org/scripts/14085-kinozal-tv-magnet-links/code/kinozaltv%20magnet%20links.user.js
> https://greasyfork.org/scripts/404-mouseover-popup-image-viewer/code/Mouseover%20Popup%20Image%20Viewer.user.js
> https://download.sf-helper.com/chrome/helper.user.js
> https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
> https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
> https://userscripts.adtidy.org/release/adguard-wot/1.0/wot.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/AQrYmyW.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/UsDFuyQ.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.5.1
Browser: | Chrome
AdGuard driver: | TDI
Stealth mode options: | Hide your search queries, <br/>Send Do-Not-Track header, <br/>Remove X-Client-Data header from HTTP requests, <br/>Strip URLs from tracking parameters, <br/>Self-destructing third-party cookies (1), <br/>Disable cache for third-party requests, <br/>Block WebRTC, <br/>Block Push API, <br/>Block Location API, <br/>Hide your Referrer from third-parties (forumpravo.by), <br/>Hide your User-Agent (), <br/>Hide your IP address ()
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Russian

---

@zubrRB commented on [Fri Aug 28 2020](https://github.com/AdguardTeam/AdguardFilters/issues/62588#issuecomment-682495153)

Отключал Антибаннер+Антитрекинг+Антифишинг+Расширения,  но открывается лишь при отключении защиты на 30 сек.

**Comment by zubrRB** [comment]
Через TOR + Ghostery открывается, а также если добавить данный сайт в HTTPS-исключения.
