### ISSUE TITLE
vseinstrumenti.ru

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1333]
@adguard-bot commented on [Sat Aug 22 2020](https://github.com/AdguardTeam/AdguardFilters/issues/62095)

### Issue URL (Incorrect Blocking)
 [https://www.vseinstrumenti.ru](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.vseinstrumenti.ru)
### Comment
> С включенным Adguard сайт или не грузится или грузится с 5 раза и долго.
> --
> Информация ниже сгенерирована автоматически. Не удаляйте ее.
> 
> Referrer:
> https://www.vseinstrumenti.ru/rashodnie-materialy/instrument/dlya-gaykovertov-i-shurupovertov/nasadki/bity/torx-s-otverstiem/show_cat.php?formType=param&cat_id=4026&tagpage_id=8492&orderby=sales_rating&asc=DESC&bdc_sort_id=&bdc[207042][ids][237702]=on&bdc[207042][ids][237693]=on&bdc[207042][type]=check
> 
> Custom userscripts:
> https://greasyfork.org/scripts/15884-auto-ru-del-ad-units/code/Autoru%20del%20ad-units.user.js
> https://greasyfork.org/scripts/19993-ru-adlist-js-fixes/code/RU AdList JS Fixes.user.js
> https://greasyfork.org/scripts/28032-wowhead-ad-free/code/Wowhead Ad-free.user.js
> https://greasyfork.org/scripts/27211-wowhead-expand-site/code/Wowhead Expand Site.user.js
> https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
> https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
> https://userscripts.adtidy.org/release/adguard-wot/1.0/wot.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/hLguZ2C.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/yllHGrP.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.5
Browser: | Firefox
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br/>Send Do-Not-Track header, <br/>Remove X-Client-Data header from HTTP requests
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/> Adblock Warning Removal List, <br/>I don't care about cookies, <br/>EasyList Cookie List, <br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/> Spam404<br/><br/><b>Language-specific:</b><br/> RU AdList, <br/>RU AdList: BitBlock, <br/>AdGuard Russian
Other extensions used: | -

---

@Alex-302 commented on [Tue Aug 25 2020](https://github.com/AdguardTeam/AdguardFilters/issues/62095#issuecomment-680093134)

Попробуйте обновиться до последней "ночной" сборки(канал обновления переключается в настройках)

---

@VadBar13 commented on [Sun Aug 30 2020](https://github.com/AdguardTeam/AdguardFilters/issues/62095#issuecomment-683351334)

> 
> 
> Попробуйте обновиться до последней "ночной" сборки(канал обновления переключается в настройках)

Ни стабильная 7.5.1, ни ночная 7.5(24) проблему не решили.

**Comment by sfionov** [comment]
Old Variti problem.
