### ISSUE TITLE
files.fm 

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/CoreLibs#1335]
При попытке скачивания с файлообменника https://files.fm/f/v2p5ts67 у одних выдаёт ошибки, у других — нет.  
У меня лично в первом случае ошибка имеет место быть, а у @Alex-302 её нет. Chrome 85.0.4183.83 + AdGuard 7.5.1.
<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/50718960/92309091-1771c700-efab-11ea-8ddd-ed0e72576a5a.png)
![2](https://user-images.githubusercontent.com/50718960/92308516-bba53f00-efa6-11ea-935e-958e5631d98a.png)

</details>
<hr>

~С P2P (Peer-2-Peer) ошибка:~

```
Sorry, your Internet browser does not support P2P file download. 
Please use another download method or another Internet browser.
```

При попытке обычного скачивания у некоторых дополнительно выдаёт ошибку:

```
Не удалось подтвердить, что это сервер fv2-3.failiem.lv. Его сертификат безопасности относится к *.adguard.com. 
Возможно, сервер настроен неправильно или кто-то пытается перехватить ваши данные.
 
NET::ERR_CERT_COMMON_NAME_INVALID

```

**Comment by Alex-302** [comment]
Логов бы ещё.

**Comment by zubrRB** [comment]
Стандартных программы?

**Comment by zubrRB** [comment]
Первая проблема (с P2P) — из-за блокирования WebRTC.

**Comment by Alex-302** [comment]
Проблему с WebRTC поправил в фильтрах.

**Comment by ameshkov** [comment]
`fv2-3.failiem.lv` - заблокирован антифишингом - поправим-разберемся, спасибо
