### ISSUE TITLE
Exceptions with xmlhttprequest type are applied to document

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1336]
Related to - https://github.com/AdguardTeam/CoreLibs/issues/1222#issuecomment-667133142

Steps to reproduce:
1. Add these rules:
```
@@||xvideos.com/models/$elemhide,jsinject,extension,badfilter
@@||xvideos.com/models/$xmlhttprequest,jsinject,elemhide,extension
```
2. Go here NSFW - `https://www.xvideos.com/models/jessica-koks`

### Expected behavior

Rule should be applied only to requests with `xmlhttprequest` type.

### Actual behavior

Rule is applied also to `document` type only.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/92571903-fdbed100-f283-11ea-9d1d-63556d8bd59d.png)

</details>

### Your environment

* AdGuard for Windows 7.5 nightly 25 (build 3382, CL 1.7.64)

**Comment by sxgunchenko** [comment]
core/pull-requests/2128
