### ISSUE TITLE
URL contains extra slash while matching against filters and some rules are not applied

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1338]
### Steps to reproduce:
1. Add these rules:
```
||example.org^$replace=/<h1>[\s\S]*?<\/h1>/<script src="path\/thisistest\/adv\.js"><\/script>/
/thisistest/*$domain=example.org
@@||example.org/path/thisistest/adv.js
```
2. Go here - http://example.org/

### Expected behavior

Request/script `example.org/path/thisistest/adv.js` shouldn't be blocked.

### Actual behavior

It seems that request/script is removed, because there is added additional slash and it looks like that:
`http://example.org//path/thisistest/adv.js`

<details><summary>Screenshot when request is not blocked</summary>

![image](https://user-images.githubusercontent.com/29142494/92692022-d9c2c480-f343-11ea-9e43-c7fb9fc0a52b.png)

</details>

<details><summary>Screenshot when request/script is blocked/removed</summary>

![image](https://user-images.githubusercontent.com/29142494/92692233-25756e00-f344-11ea-8405-c1a7bf3da886.png)

</details>

Additionally, I'm not sure if it's a bug, but it seems that exception with `$content` modifier disable `$replace` rules as well:
`@@||example.org^$content`

### Your environment

* AdGuard for Windows 7.5 nightly 25 (build 3382, CL 1.7.64)

**Comment by sxgunchenko** [comment]
Regarding `$content` modifier disabling `$replace` rules: it's intended behaviour, but according to [spec](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#content-modifier) it seems like a bug (or maybe the specification should be corrected)

**Comment by AdamWr** [comment]
>Regarding $content modifier disabling $replace rules: it's intended behaviour

Yes, it's in specification, but I missed it https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#disabling-replace-rules
Thank you for your answer.

**Comment by sxgunchenko** [comment]
Oh, and I missed that it is specified in the `$replace` section. :)

**Comment by ameshkov** [comment]
Huh, inventive way of reproducing the issue
