### ISSUE TITLE
hkclubs.samsung.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1340]
@adguard-bot commented on [Fri Sep 11 2020](https://github.com/AdguardTeam/AdguardFilters/issues/63618)

### Issue URL (Incorrect Blocking)
 [https://hkclubs.samsung.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fhkclubs.samsung.com%2F)
### Comment
Username: @thisiskarsten
> 
> --
> 下面的資訊是被自動地產生。不要刪除它。
> 
> Referrer:
> 
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/MwBx3b7.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/sc2TQA9.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.5.1
Browser: | Vivaldi
AdGuard driver: | TDI
Stealth mode options: | Hide your search queries, <br/>Send Do-Not-Track header, <br/>Remove X-Client-Data header from HTTP requests, <br/>Strip URLs from tracking parameters, <br/>Self-destructing third-party cookies (180), <br/>Block WebRTC, <br/>Block Push API, <br/>Block Location API
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> Web Annoyances Ultralist, <br/>AdGuard Annoyances<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion, <br/>AdGuard Experimental<br/><br/><b>Language-specific:</b><br/> EasyList China, <br/>AdGuard German, <br/>AdGuard Japanese
Other extensions used: | Bitdefender Total Security, Bitwarden, Smart HTTPS, IDM, Adguard VPN, Dark Reader

**Comment by ameshkov** [comment]
Reproduced with Mac version as well
