### ISSUE TITLE
videoder.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1341]
@adguard-bot commented on [Wed Sep 09 2020](https://github.com/AdguardTeam/AdguardFilters/issues/63489)

### Issue URL (Annoyance)
 [https://www.videoder.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.videoder.com%2F)
### Comment
> 
> --
> The information below is automatically generated. Do not delete it.
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/5A3JWio.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 10
AdGuard product: | AdGuard for Android v3.5 (63)
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> Liste AR
Custom filter subscriptions: | 

---

@Sergey-Lyapin commented on [Fri Sep 11 2020](https://github.com/AdguardTeam/AdguardFilters/issues/63489#issuecomment-691055322)

`videoder.com,youglish.com###gdprModal` should work for this popup, but it doesn't work even from user rules, I tried different selectors and `videoder.com$$div[id="gdprModal"]` - they didn't work.
But content blocker and AG for iOS hide this popup successfully.

@AdguardTeam/filters-maintainers please check on your devices

---

@AdamWr commented on [Fri Sep 11 2020](https://github.com/AdguardTeam/AdguardFilters/issues/63489#issuecomment-691059079)

I can reproduce it on my device, it looks like that for some reason there is no AdGuard certificate on this website.
On Android only.

**Comment by AdamWr** [comment]
Similar issue on `fonearena.com` -  [https://www.fonearena.com/blog/322753/apple-ipad-8th-gen-price-india-specifications.html/amp](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.fonearena.com%2Fblog%2F322753%2Fapple-ipad-8th-gen-price-india-specifications.html%2Famp)
It seems that it happens only on Android.
https://github.com/AdguardTeam/AdguardFilters/issues/63968

**Comment by ngorskikh** [comment]
Fixed in core/pull-requests/2150
