### ISSUE TITLE
Compatibility issue between AdGuard and Windscribe VPN

### ISSUE THREAD

**Issue by northis** [AdguardTeam/CoreLibs#1342]
https://github.com/AdguardTeam/AdguardForWindows/issues/3541

**Comment by NUser2018** [comment]
@northis и @ngorskikh Текущие статусы **Resolution: Fixed** и **Status: Resolved**

Данное исправление уже доступно хотя бы на **Nightly**-канале или ещё нет? В **7.5 Nightly 31** оно уже входит? **_Если да_**, то не могу к сожалению согласится с тем что проблема решена, у меня она по-прежнему воспроизводится. **_Если нет_**, то когда ожидается хотя бы примерно доступность исправления хотя бы сначала на **Nightly**-канале? Когда оно станет доступно хотя бы на **Nightly**-канале, то пожалуйста напишите об этом здесь или в моей [связаннной исходной задаче](https://github.com/AdguardTeam/AdguardForWindows/issues/3541). Заранее спасибо. С уважением Александр.

**Comment by NUser2018** [comment]
https://github.com/AdguardTeam/AdguardForWindows/issues/3541

**Comment by northis** [comment]
@NUser2018 будет в ближайших nightly-выпусках

**Comment by NUser2018** [comment]
@northis Хорошо, тогда когда оно станет доступно хотя бы на Nightly-канале, то пожалуйста напишите об этом здесь или в моей [связаннной исходной задаче](https://github.com/AdguardTeam/AdguardForWindows/issues/3541) чтобы я получил email-уведомление от GitHub об этом и смог бы проверить. Просто я не сижу постоянно на Nightly-канале, обычно я сижу на релизном канале обновлений. Заранее спасибо. С уважением Александр.

**Comment by NUser2018** [comment]
@northis В релизную версию **7.5.2** что ли уже вошёл этот фикс?
По крайней мере у меня на **7.5.2** проблема больше не воспроизводится в части описания [здесь](https://github.com/AdguardTeam/AdguardForWindows/issues/3541) когда _включена_ опция **Force close all TCP sockets after connection** в настройках **Windscribe**. Сообщения от **Windscribe** о конфликте больше нет, подключение к VPN-серверу происходит нормально без дополнительных задержек.

В части описания (_в других моих сообщениях в [той](https://github.com/AdguardTeam/AdguardForWindows/issues/3541) задаче_) когда опция **Force close all TCP sockets after connection**  в настройках **Windscribe** выключена все пока еще так или иначе воспроизводится, но поскольку и для работы и для VPN лучше когда эта опция включена (да и по моему она по умолчанию включена) то  уже хорошо, что проблема пофиксилась хотя бы для основного сценария когда опция **Force close all TCP sockets after connection**  в настройках **Windscribe** включена.

А сценарии воспроизведения когда опция **Force close all TCP sockets after connection**  в настройках **Windscribe** выключена вполне может иметь общие корни с [этой](https://github.com/AdguardTeam/AdguardForWindows/issues/3542) моей проблемой.
