### ISSUE TITLE
Rules with $extension modifier unblock blocked requests

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1350]
### Steps to reproduce

1. Add these rules:
```
||ghacks.net/wp-content/
@@||ghacks.net^$extension
```
2. Go to  -  [https://www.ghacks.net/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.ghacks.net/)

### Expected behavior

Requests from `ghacks.net/wp-content/` should be blocked (like on a screenshot below).
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/94349209-d49f8e00-0042-11eb-995b-c586dd3f4719.png)

</details>

### Actual behavior

Requests are unblocked by a rule with `$extension` modifier.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/94349243-057fc300-0043-11eb-92a2-eeab3e31e10a.png)

</details>

### Your environment

* AdGuard for Windows version 7.5 nightly 30 (build 3395, CL 1.7.114)

**Comment by AdamWr** [comment]
Do I understand correctly that it should works fine with `CL 1.7.140` and newer like for example `CL 1.7.153`? - https://github.com/AdguardTeam/AdguardForWindows/issues/3585
If so, then unfortunately it doesn't work :(

AdGuard for Windows 7.6 nightly 5 (build 3433, CL 1.7.153)

**Comment by ameshkov** [comment]
Hm, @sxgunchenko ?

**Comment by ngorskikh** [comment]
Hm, this was actually fixed in 1.8

**Comment by AdamWr** [comment]
Okay, thank you for your reply :)
