### ISSUE TITLE
FTP pages are broken

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1351]
Original issue:
https://forum.adguard.com/index.php?threads/39943/

Reproduced with enabled `redirect driver mode`(not reproduced with disabled)

Sample FTP: ftp://ftp.adobe.com/pub/adobe/

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/94431694-4a6c3c80-019e-11eb-83c6-7d9501070c8d.png)

</details>

**Comment by sfionov** [comment]
We should port workaround from Mac kext driver

**Comment by krystian3w** [comment]
FTP killed in Firefox Quantum.
