### ISSUE TITLE
Element hiding is not working on the first visit

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1355]
Original issue:
https://github.com/AdguardTeam/AdguardFilters/issues/64631#issuecomment-703199493

### Steps to reproduce:
1. Search for `HorribleSubs reddit` in mobile mode on google.com;
2. Select reddit result(`amp`)
![image](https://user-images.githubusercontent.com/8361299/95319020-04029600-08a0-11eb-983b-87cdc75fc39a.png)

### Expected behavior

Mobile app banner is blocked.
Selector for popup: `div[class*="AppSelectorModal"]`
Original rule: `amp-reddit-com.cdn.ampproject.org,amp.reddit.com##div[class*="AppSelectorModal"]`

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/95319195-3f04c980-08a0-11eb-97fe-2f06497b571f.png)

</details>

### Actual behavior

Popup is not hidden.
Reproduced with `AdGuard for Android`(v4.0 n6 24-1.7.114cl)  and `AdGuard for Windows`(last nightly)

**Comment by AdamWr** [comment]
Looks similar to this issue - https://github.com/AdguardTeam/CoreLibs/issues/1120

**Comment by Alex-302** [comment]
Sure.
![image](https://user-images.githubusercontent.com/8361299/95321716-1ed70980-08a4-11eb-9e45-23d5e0df1d75.png)
