### ISSUE TITLE
Sometimes AdGuard script is blocked by CSP

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1356]
### Steps to reproduce

1.  Add this rule:
`github.com##body`
2. Go here - https://github.com/AdguardTeam/AdguardForAndroid
3. Refresh website few times

### Expected behavior

Website should be blank.

### Actual behavior

AdGuard script is blocked by CSP.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/95379902-477ff300-08e6-11eb-8fb5-d411e3ba6a7a.png)

</details>

### Your environment

* AdGuard for Windows version 7.5 nightly 33 (build 3407, CL 1.7.114)
The same happens on Android - https://github.com/AdguardTeam/AdguardFilters/issues/65128#issuecomment-705125448

**Comment by ngorskikh** [comment]
Highly probably fixed by core/pull-requests/2345
