### ISSUE TITLE
Add support for "!#include" in non-included filterlists

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1358]
@DandelionSprout commented on [Sun Oct 11 2020](https://github.com/AdguardTeam/AdguardForWindows/issues/3574)

### Steps to reproduce

1. Open AdGuard for Windows' list settings.
2. Import https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList as a new custom list.
3. Rightclick on the cogwheel next to the list and choose *Edit*.
4. See that there's only metadata and non-utilised `!#include` links in the list preview.

### Expected behavior
Around 2 years after it became supported in lists that are included as a part of most AdGuard products (e.g. Frellwit's Swedish Filter), `!#include` still hasn't become supported in non-included custom lists to this day, so I think it's at least a year overdue that it becomes fully supported.

This presumably also applies to AdGuard for Mac/Chromium/Firefox, with the potential to have it apply to AdGuard for Android as well. For AdGuard Home I submitted [a standalone request for this](https://github.com/AdguardTeam/AdGuardHome/issues/2173) in its repo instead.

### Actual behavior
`!#include` tags/links in custom filterlists are not being recognised nor utilised.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/95665069-2ec54680-0b4d-11eb-8131-07752f190fc8.png)

</details>

### Customer ID 
N/A

### Your environment

* Environment name and version: AdGuard for Windows 7.5.2
* Operating system and version: Windows 10 May 2020 Update

**Comment by ameshkov** [comment]
We want this to be implemented in CoreLibs as this would be useful for all our products.

This is fully supported by the AdGuard browser extension and AdGuard for Safari already.

**Comment by sfionov** [comment]
Done in #1279.

**Comment by ameshkov** [comment]
@sfionov should we close it anyway?
