### ISSUE TITLE
Userscripts cannot save their settings

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/CoreLibs#1359]
Here are the scripts that do not save their settings when working with AdGuard for Windows, but if you install them in Tampermonkey, the settings are saved.

[Script #1](https://greasyfork.org/ru/scripts/39242-kinozal-tv-me-guru-2020-%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D0%B8-%D1%81%D0%BA%D0%B0%D1%87%D0%B8%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%B2%D0%BD%D1%83%D1%82%D1%80%D0%B8-%D1%80%D0%B0%D0%B7%D0%B4%D0%B0%D1%87%D0%B8)

[Script #2](https://greasyfork.org/ru/scripts/40843-kinozal-tv-me-guru-2020-%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D0%B8-%D1%81%D0%BA%D0%B0%D1%87%D0%B8%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%B2-%D0%BF%D0%BE%D0%B8%D1%81%D0%BA%D0%BE%D0%B2%D0%BE%D0%B9-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B5-%D0%B8-%D0%B2-%D1%80%D0%B0%D0%B7%D0%B4%D0%B0%D1%87%D0%B8-%D0%BF%D0%B5%D1%80%D1%81%D0%BE%D0%BD%D1%8B)

### Steps to reproduce:

1. Install the scripts via AdGuard for Windows ([latest release](https://agrd.io/windows))
2. Go to the [website](http://kinozal.tv/), click on any shared content and check that buttons (download torrent file/magnet link) are available 
3. Click on script settings (see the attached screenshot) and try to change the settings then save it, reload the page

<details>

![img](https://uploads.adguard.com/myMoon7n7jj.png)

</details>

### Expected behaviour:

Settings are saved

### Actual behaviour:

Settings are not saved

**Comment by zubrRB** [comment]
Чуть дополню проблему с сохранением настроек Userscripts, связанную с этими же упомянутыми ресурсами. 
Использую другой userJS для генерирования magnet-ссылки https://greasyfork.org/ru/scripts/14085-kinozal-tv-magnet-links.  
Так как в скрипте прописан только .tv, а мне нужен .me, я внёс изменение в скрипт, прописав дополнительную строчку:
`// @include      /^http:\/\/kinozal.me\/details\.php\?id=\d+$/` 
Проблема выражается в том, что каждые несколько месяцев AdGuard исправно сообщает об обновлении данного скрипта со сбросом ("до заводских значений") внесённого в него изменения, хотя в действительности на сервере сам срипт и его версия не изменяются. Буквально 10.11.2020 это снова повторилось.
![-](https://user-images.githubusercontent.com/50718960/99114333-b47f5a80-2601-11eb-95d0-7fcf13d5c099.png)

**Comment by Alexey71** [comment]
Здравствуйте. Есть продвижения по фиксу?

**Comment by ameshkov** [comment]
Пока нет.

@zubrRB насчет вашей проблемы - вам проще было бы форкнуть этот юзерскрипт и пользоваться своей версии.

**Comment by zubrRB** [comment]
@ameshkov его разработчик по моей просьбе уже обновил юзерскрипт, так что теперь всё хорошо.)

**Comment by Alexey71** [comment]
@ameshkov 
Привет. Будет фикс?. Я еще один нашел скрипт, он вообще не работает https://github.com/AlekPet/Rutor-Preview-Ajax/blob/master/RutorPreviewAjax.user.js

**Comment by Alexey71** [comment]
Задача закрыта с невозможностью исправить ?

**Comment by ameshkov** [comment]
Она больше не повторяется так как автор юзерскрипта исправил все на своей стороне.

**Comment by Alexey71** [comment]
Только что поставил скрипт https://greasyfork.org/ru/scripts/39242-kinozal-rutor-rutracker-%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D0%B8-%D1%81%D0%BA%D0%B0%D1%87%D0%B8%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-torrent-magnet-torrserver
Ничего не исправлено, настройки скрипта не сохраняются

**Comment by ngorskikh** [comment]
I've tried to repro this again this morning and it seemed to reproduce once; however, by the time I could debug anything, it stopped reproducing.

@Alexey71 Could you enable debug logging, reproduce the issue, and then export the logs and provide them here, along with the exact step-by-step description of how to get this problem to occur?
