### ISSUE TITLE
hydrogenaud.io is broken in Firefox

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1361]
@adguard-bot commented on [Tue Oct 13 2020](https://github.com/AdguardTeam/AdguardFilters/issues/65530)

### Issue URL (Incorrect Blocking)
 [https://hydrogenaud.io/index.php?topic=96970.125](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fhydrogenaud.io%2Findex.php%3Ftopic%3D96970.125)
### Comment
Username: @Morku
> Stealth mode kills the layout
> --
> Die folgenden Informationen werden automatisch generiert. Bitte löschen Sie sie nicht.
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/c0BXfkb.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/I0rfvH0.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.5.2
Browser: | Firefox
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br/>Send Do-Not-Track header, <br/>Remove X-Client-Data header from HTTP requests, <br/>Strip URLs from tracking parameters
Filters: | <b>Ad Blocking:</b><br/> AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Russian, <br/>AdGuard German

---

@Alex-302 commented on [Wed Oct 14 2020](https://github.com/AdguardTeam/AdguardFilters/issues/65530#issuecomment-708395928)

@Morku which option causes it?

---

@Morku commented on [Wed Oct 14 2020](https://github.com/AdguardTeam/AdguardFilters/issues/65530#issuecomment-708412715)

Odd, today I have to disable AdGuard completely to make the Layout always work.

I have disabled Blocker, Stealth, Internet security and Extension -> the page still loads broken
When I disable protection completely -> Page always loads fine

Maybe it's because of this...?

<details><summary>Screenshot-1:</summary>

![grafik](https://user-images.githubusercontent.com/6276915/95997654-498d0900-0e34-11eb-8055-98cbf459058d.png)

</details><br/>

---

@Alex-302 commented on [Thu Oct 15 2020](https://github.com/AdguardTeam/AdguardFilters/issues/65530#issuecomment-709488132)

Reproduced on another PC in FF only when refreshed by Ctrl-F5.
Weird thing - in dev tools it id displayed correctly
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/96167143-9f8ea900-0f27-11eb-97e1-45e94c2b2dcf.png)

</details>
Cannot fix it using filters.

**Comment by Morku** [comment]
It's not just Firefox, it is also on Edge Legacy (44.19041.423.0)

<details><summary>Screenshot-1:</summary>

![edge](https://user-images.githubusercontent.com/6276915/96167680-0c05aa00-0f20-11eb-8069-24beae47d88a.png)

</details><br/>

When I always press F5, there 3 three posibilitys:

1. Layout is broken and images not load (Screenshot)
2. Layout and broken and few Banners load
3. Whole page loads fine (rare case).

Also, the page loads somehow slow.

When I disable AdGuard completely, the page always loads quick and fine (F5) with a 100% success chance.

**Comment by wanesoft** [comment]
not reproduced (nightly 23). can you check it again?

**Comment by Morku** [comment]
@wanesoft 
The issue is still with Nightly 23

<details><summary>Screenshot-1:</summary>

![hydrogen](https://user-images.githubusercontent.com/6276915/111341317-b160ad80-8679-11eb-86a3-7718245ba682.png)


</details><br/>

<details><summary>Screenshot-2:</summary>

![hydrogen2](https://user-images.githubusercontent.com/6276915/111341328-b45b9e00-8679-11eb-898b-2b5eb7fb9077.png)


</details><br/>
