### ISSUE TITLE
JS rules are not applied in Whale browser

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/CoreLibs#1362]
### Environment
AdGuard for Windows, versions: 7.5.0 - 7.5.2
Naver Whale version: 2.8.107.16

### Reproduction
1. Add the following rule to AdGuard user filter: ( adguard.com#%#document.cookie = "testasdasd=1"; )
2. [15-10-2020 14:18] Accessing the <adguard.com> site from the Chrome browser new incognito window
3. [15-10-2020 14:20] Accessing the <adguard.com> site from the Whale browser new incognito window
4. Confirmation with testasdasd in cookie
No testasdasd are generated in the Whale browser, but testasdasd are generated in the chromium

### Customer ID & debug logs
2863997

**Comment by ameshkov** [comment]
Is this Whale browser added to the list of filtered apps (settings -> network -> filtered apps)?
It'd be better to test this on example.org

**Comment by akmLaVx** [comment]
Yes - customer claims that other filtering rules are applied without any issues.
I'll ask him to test on example.org.

**Comment by ameshkov** [comment]
@AdguardTeam/qa-team guys, can we reproduce this?

**Comment by Chinaski1** [comment]
Yes, I managed to reproduce the issue in the specified browser.
Also, it stays on Nightly (33).
- [screenshot](https://uploads.adguard.com/Chinaskitr9e5.png)

**Comment by Mo-norn** [comment]
Is there any solution other than to stop using the Whale browser?

**Comment by ameshkov** [comment]
No solutions yet, we'll need to implement a fix on our side first.
