### ISSUE TITLE
Links opened from Google Now may hang in Chrome Beta

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1363]
Here's the detailed description by the user affected by this bug:
https://t.me/adguard/96787

Please check if we can reproduce this issue. If we do, we should fix it in AG for Android v3.6

**Comment by ngorskikh** [comment]
Couldn't repro, need logs

**Comment by ameshkov** [comment]
@ngorskikh check the Telegram post, you'll see the logs there

**Comment by Chinaski1** [comment]
I am in touch with the user - he is ready to provide any necessary information.

Part of the logs and video with the problem I have already passed to @ngorskikh.

**Comment by Joss** [comment]
Can be closed because duplicated issue was resolved:
https://github.com/AdguardTeam/CoreLibs/issues/1374
