### ISSUE TITLE
Add $urltransform (trusted) modifier support

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/CoreLibs#1364]
It might be useful to have a `$rewrite` modifier that supports all kinds of redirections, basically a `$replace` modifier for URLs.

There are many use cases where this modifier may be useful, but overall it's too dangerous to allow it to be used in third-party lists so it should be limited to trusted filters only.

UPD 17.01.2024: uBO [renamed](https://github.com/gorhill/uBlock/commit/cdc5e89f52242f465fdcdb84b9e040992b9cf07c) to uritransform since syntax was changed in 1.54. https://github.com/AdguardTeam/CoreLibs/issues/1364#issuecomment-1864282857

Original report:
<details>
@BlitW0 commented on [Wed Oct 14 2020](https://github.com/AdguardTeam/AdguardForAndroid/issues/3634)

### Problem Description

Add a way to redirect a URL to a different URL based on regex rules.

### Proposed Solution

No idea how it would work, but it might be separate section in settings since standard filter rules do not support URL redirection.

### Alternatives Considered

Tried to see if standard filters with ABP syntax can do this, but was not able to find anything.

---

@TheHasagi commented on [Thu Oct 15 2020](https://github.com/AdguardTeam/AdguardForAndroid/issues/3634#issuecomment-708979617)

@BlitW0 

Hello! Can you explain with more details for what purposes do you need such a feature?

---

@zzebrum commented on [Mon Oct 19 2020](https://github.com/AdguardTeam/AdguardForAndroid/issues/3634#issuecomment-712127579)

@BlitW0 any update? 

---

@BlitW0 commented on [Mon Oct 19 2020](https://github.com/AdguardTeam/AdguardForAndroid/issues/3634#issuecomment-712130029)

My reason was for redirecting reddit's awful mobile website to the compact version or old reddit. It might also be useful for different sites in the same manner? I know it is possible through userscripts but it may not always be possible to write scripts on mobile, so this can be an easier way through GUI.
</details>

**Comment by ameshkov** [comment]
Merged `urltransform` here: https://github.com/AdguardTeam/CoreLibs/issues/1820

Let's call it `urltransform` since there's already existing modifier.

@slavaleleka could you please also create an issue in tsurlfilter?

**Comment by ameshkov** [comment]
One question, I see that it's limited to local resources in uBO. Do we want to allow redirects to any URLs since it's a trusted modifier anyways?

**Comment by Yuki2718** [comment]
uBO [renamed](https://github.com/gorhill/uBlock/commit/cdc5e89f52242f465fdcdb84b9e040992b9cf07c) as `uritransform` since syntax was changed in 1.54

**Comment by imTHAI** [comment]
Hello
I don’t want to put pressure of any kind. I know you do a fantastic job and I'm a huge fan of the Adguard Products. But as I'm the requestor of the duplicate #1557 since some years already (2021), I just wanted to know the status of the feature. I know it's for v1.15 but it looks so far. 
And currently, the only alternative for this kind of advertising/tracking is ClearURLs but it won't work on Safari and the developer is not keeping it up to date anymore.🙁
As this request has been duplicated at least 3 times, I know it is expected by quite a few people. (well, I think).

Kind regards,

**Comment by ameshkov** [comment]
We really want to improve the speed with which CoreLibs updates are rolled out so 1.15 shouldn't be that far.

The main issue with this modifier is that it's kinda too powerful, we may need to make it more clear to the user what it means to make a filter list "trusted".
