### ISSUE TITLE
Hardware accelerated TLS decode/encode

### ISSUE THREAD

**Issue by DBotThePony** [AdguardTeam/CoreLibs#1365]
It seems that adguard does not take advantage of hardware's AES and SHA command set (present on AMD Ryzen CPUs starting from Zen 1), creating severe CPU load and moderate speed slowdown.

"Local" (physically same PC, but on network and logical level server and client are separate PCs (virtual machine)) network produce this CPU load with this speed: 
![ProcessHacker_bfs5zgLYaI](https://user-images.githubusercontent.com/6339511/97420425-e4f6a180-193d-11eb-85ec-f4e2373b8d2a.png)
![wufIMwEQvw](https://user-images.githubusercontent.com/6339511/97420429-e627ce80-193d-11eb-8078-cb7b806eddb9.png)

Disabling adguard service completely yield speed boost from 115 mb/s to 180 mb/s. Server is (nginx) compiled against OpenSSL which support Ryzen CPU SHA/AES instruction set. cURL compiled against OpenSSL with same feature support can achieve 220 mb/s and at this point network adapter virtualization become the bottleneck (and cURL does not fully take one CPU core, only ~80% of it!).
![UrRV15DdZL](https://user-images.githubusercontent.com/6339511/97420565-0d7e9b80-193e-11eb-8b30-7e0ec7c311e6.png)

![cpuz_G6hs3Lgv7E](https://user-images.githubusercontent.com/6339511/97420946-8251d580-193e-11eb-970f-68d99c3cca26.png)

Please consider supporting these instruction sets since this will yield enormous speed boost, CPU resource saving and reduced power usage.

**Comment by sfionov** [comment]
AdGuard uses hardware acceleration for AES. In our tests, encrypting code processes gigabits per second.
Can you please try to turn on redirect mode in AdGuard's advanced settings?
It is recommended mode for gigabit connections but may interfere with some anti-viruses.

**Comment by DBotThePony** [comment]
In redirect mode speed *seems like* to be near original, however, CPU consumption, although dropped from 17% to 5%, is still pretty high while looking at other software compiled with AES+SHA hardware support.

**Comment by ameshkov** [comment]
Don't forget that there's additional load caused by "double" TLS usage - we basically establish two TLS tunnels -- one with the client (browser), and one with the server. Not to mention the pages content and requests/responses modification that also take place at the same time.

**Comment by DBotThePony** [comment]
Thanks for answer

**Comment by DBotThePony** [comment]
После использования драйвера в режиме перенаправления наблюдаются большие проблемы, в частности - браузеры очень быстро теряют отзывчивость, страницы начинают очень долго загружаться.

Наиболее заметные проблемы:
Общая отзывчивость интерфейса любого браузера падает
При открытии новых вкладок на веб-сайты без HTTP/2 или при первичном открытии такого сайта (когда к нему нет активных соединений) происходит `Ожидание кеша...` секунд 6 в браузерах на основе Chromium и `Ожидание...` в FireFox
При переключении вкладок в браузерах на основе Chromium они становятся белыми секунды на одну-три
Переход по ссылкам на очень быстрых веб-сайтах происходит крайне медленно (в то время, когда "на лету" TTFB составляет в основном реальный TTFB + Content Download (без AdGuard страницы начинают отрисовываться раньше, но завершают отрисовываться одинаково))

Остальные симптомы указывают на такую ситуацию, когда у браузера будто открыто множество соединений, которые "висят" без их реального закрытия. Чем больше различных вкладок загружается одновременно, тем сильнее страдает отзывчивость интерфейса. Это не связано с процессорным временем так как во время "зависаний" процесс браузера (AdGuard Service собственно то же) в основном бездействуют.

Отключение режима перенаправления **мгновенно** убивает большинство проблем, но все равно желателен полный перезапуск браузера. Перезапуск браузера без отключения режима перенаправления устраняет проблему лишь временно, по мере сёрфинга проблема возникает вновь.

Примеры веб-сайтов которые должны грузится быстро:
https://e2e4online.ru
Любой сайт на платформе wikia (fandom.com)

**Comment by ameshkov** [comment]
@DBotThePony а у вас какой-то еще сетевой софт кроме AG стоит? Антивирус там или что-то подобное?

**Comment by DBotThePony** [comment]
Нет никаких антивирусов, ни другого сетевого софта (если не считать работу виртуалки VirtualBox с сетевым мостом за сетевой софт)

**Comment by ameshkov** [comment]
@DBotThePony а может ли это быть тем багом, который мы в пятницу чинили?

https://adguard.com/en/blog/chrome-87-bug-fixed.html
