### ISSUE TITLE
Proposals for strippable URL tracking-parameters

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/CoreLibs#1367]
I was directed here after asking about it on Slack, so here I am.

* `gclsrc` (Source: `https://www.jula.no/catalog/fritid/trening/treningsutstyr/manualer-og-vektstenger/manualsett-951150?gclid=Cj0KCQjwlvT8BRDeARIsAACRFiUj4R30NdrcmVwC1-pBi43uGBKic6uEq0zEJfkXS3hxOfGrJ3CrR9waAoy9EALw_wcB&gclsrc=aw.ds`; a temp fix with `$removeparam` has been added to Nordic Filters in the meantime.)
* `_trkparms` (Source: `https://www.ebay.com/itm/Disney-Fairies-Annual-2008/173553616659?_trkparms=aid%3D111001%26algo%3DREC.SEED%26ao%3D1%26asc%3D20160908105057%26meid%3Da7ecc6d2187f43619ceae843d9c7e96e%26pid%3D100675%26rk%3D1%26rkt%3D15%26sd%3D173553616659%26itm%3D173553616659&_trksid=p2481888.c100675.m4236&_trkparms=pageci%3A87956e3f-3968-11e9-ae7f-74dbd1801ed7%7Cparentrq%3A277c9f541690a861b48415dfffeb1383%7Ciid%3A1`)
* `_trksid` (Source: Same as above.)
* `logTag` (Source: `https://www.ixigua.com/6888869154099629319?logTag=Y8JlCALntSDuDesMiPno8`; depends on what `Ixigua`'s logging is actually about.)

**Comment by DandelionSprout** [comment]
In case you guys need more ideas for parameters, I'd recommend keeping an eye on https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt, which has added ≥7 more suggestions in the time since I wrote the OP.

**Comment by ameshkov** [comment]
@DandelionSprout what do you think about adding this filter list to FiltersRegistry?

**Comment by DandelionSprout** [comment]
That would be awesome on paper, but I'd probably need at least a handful of users to waterproof this list first to make sure it doesn't cause catastrophic breakage.

**Comment by ameshkov** [comment]
Btw we wanted to move all the tracking parameters that Stealth Mode strips to a separate filter list instead of keeping them in CoreLibs. That's the end goal of introducing $removeparam.

**Comment by DandelionSprout** [comment]
One other plausible option would be to add https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AnnoyancesList to FiltersRegistry, which also includes the URL shortener list's AdGuard version.

**Comment by ameshkov** [comment]
Let us keep an eye on it for some time and see how active it is, currently it's just too short.

Regarding URL shortener, I guess we should add $removeparam support to the extension first (and it's coming in the next major update).

**Comment by DandelionSprout** [comment]
As for "URL Shortener"'s size, it's still roughly 6 times the size of Stealth Mode's parameter stripping default list.

As for "Dandelion Sprout's Annoyances List", I doublechecked it and was honestly surprised it only had ~2,500 entries, as I thought it had 3 times as much. Looks like I'll have to add more `!#include` lists into it.

>I guess we should add $removeparam support to the extension first (and it's coming in the next major update).

Sounds like very good news to me that it'll be in the extensions as well.

**Comment by ameshkov** [comment]
Ah, my bad, I missed all the includes :)

**Comment by ameshkov** [comment]
See here:
https://github.com/AdguardTeam/FiltersRegistry/issues/401
https://github.com/AdguardTeam/FiltersRegistry/issues/400
