### ISSUE TITLE
oyunkuzusu.com - AdGuard's JS is not injected

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1369]
Steps to reproduce:
1. Go here -  [https://www.oyunkuzusu.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.oyunkuzusu.com%2F)

It seems that the problem is that there is no AdGuard certificate.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/97873314-bef34780-1d17-11eb-92b1-1a41f1ba3ce9.png)

</details>

AdGuard for Windows 7.6 nightly 1 (build 3419, CL 1.7.140)

**Comment by AdamWr** [comment]
Similar issue on this website - [https://yabancidizitv.com/ratched-1-sezon-1-bolum-izle/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fyabancidizitv.com%2Fratched-1-sezon-1-bolum-izle%2F)

**Comment by AdamWr** [comment]
One more website with similar issue - [https://poscigi.pl/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://poscigi.pl/)

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/103350421-3cc99a00-4aa0-11eb-88fa-6425e328a52a.png)

</details>

**Comment by AdamWr** [comment]
Probably one more website with similar issue -  [https://comidoc.net/udemy/100-days-of-code](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fcomidoc.net%2Fudemy%2F100-days-of-code)

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/104610347-506e2680-5684-11eb-9f07-d40a65c3dd5b.png)

</details>

**Comment by sxgunchenko** [comment]
These sites are not filtered at the moment because of the implementation of the filtering mechanism, this will probably be improved in a future version.
