### ISSUE TITLE
Cosmetic rules don't work into iframes with desktop programs

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/CoreLibs#1370]
Cosmetic rules don't work into iframes with desktop programs.

For example in iframes where user marked ads in this issue:
https://github.com/AdguardTeam/AdguardFilters/issues/66827

AG for Mac version: 2.5.1.913 nightly (CL-1.7.134)

**Comment by ameshkov** [comment]
@sfionov a bug?

**Comment by sfionov** [comment]
@ameshkov No, CoreLibs limitation. More tricky blocking method should be used

**Comment by Sergey-Lyapin** [comment]
@sfionov is it ok that HTML-rules and scriptlets don't work there too?
