### ISSUE TITLE
URL parameter stripping doesn't seem to work if the URL contains a "#" character

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/CoreLibs#1372]
Example: `https://www.gymgrossisten.no/deluxe-rubber-dumbbell-136-kg/1091-20.html#fo_c=1711&fo_k=adae6123e501c56ef12857556fc567d4&fo_s=gsurno?utm_source=prisjakt&utm_medium=cpc`, as triggered by going to `https://www.prisjakt.no/product.php?p=5396751` → the `Gymgrossisten` row → `Vis i butikk`.

Tested in AdGuard for Windows 7.5.2.

**Comment by ameshkov** [comment]
Please note, that `#....` is a location hash and not a part of the query so it can't be stripped on the network level.

Here is the URL that the remote server sees: `https://www.gymgrossisten.no/deluxe-rubber-dumbbell-136-kg/1091-20.html`
The "hash" part is only visible to the page javascript.
