### ISSUE TITLE
Onlinetrade.ru не открывается в Firefox

### ISSUE THREAD

**Issue by Eroppo** [AdguardTeam/CoreLibs#1373]
Уже примерно неделю не открывается нормально [сайт](https://www.onlinetrade.ru/) (либо пустая страница, либо без оформления, как на скриншоте). В браузерах на Хромиуме все нормально, в FF удается открыть только после полной выгрузки Adguard с отключением драйвера.
![firefox_2020-11-17_14-50-32](https://user-images.githubusercontent.com/13285107/99390023-0289ac00-28e9-11eb-9799-6afa89a05c9f.jpg)

**Comment by Aydinv13** [comment]
Здравствуйте, проверьте пользовательские правила, возможно там имеются такие, которые мешают работе фильтрации. Попробуйте отключить их, если они имеются. 
Если проблема не решилась, то нужны трейсовые логи (подробный уровень логов debug + запустить Adguard с флагом). Также необходима информация о версии ОС, версии FF, а также версии Adguard и ее настройках.

**Comment by Eroppo** [comment]
> 
> 
> Здравствуйте, проверьте пользовательские правила, возможно там имеются такие, которые мешают работе фильтрации. Попробуйте отключить их, если они имеются.
> Если проблема не решилась, то нужны трейсовые логи (подробный уровень логов debug + запустить Adguard с флагом). Также необходима информация о версии ОС, версии FF, а также версии Adguard и ее настройках.

Добрый день! С последним обновлением программы (7.5.3) проблема вроде решилась (больше пока не наблюдал). Хотел пару дней понаблюдать и отписаться, если точно решится

**Comment by Aydinv13** [comment]
Так как проблема решена, я закрываю обращение. В случае повторной ошибки вы можете открыть обращение заново.
