### ISSUE TITLE
Adobe Creative Cloud sync issue 

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/CoreLibs#1375]
- Several users have complained about issues with the Adobe Creative Cloud synchronization

### Customer ID 

[AdGuard Forum](https://forum.adguard.com/index.php?threads/problem-with-adobe-creative-cloud-big-sur.40472/#post-204824)

### Your environment

* Application version: 2.5.1.918 release (CL-1.7.143)
* OS: Version 11.0.1 (Build 20B29)

### Additional Info
- Users provided log files, I added them to NClound and attachment to Jira.

**Comment by williamli** [comment]
@Chinaski1 the same bug is affecting Apple Music as well.

<img width="439" alt="Screen Shot 2020-11-19 at 22 12 45" src="https://user-images.githubusercontent.com/179761/99678538-e2f3ae80-2ab5-11eb-97fa-d18106145d87.png">

**Comment by sfionov** [comment]
@williamli Do you use Little Snitch?

**Comment by Chinaski1** [comment]
@williamli 

Apple released the Big Sur 11.2 Beta 2 update. Can you please check if the issue still persists on the new OS version?

In order to download the current beta version, you need to join the Apple Beta Software Program: https://beta.apple.com/
