### ISSUE TITLE
igromania.ru is broken

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1376]
@adguard-bot commented on [Sat Nov 14 2020](https://github.com/AdguardTeam/AdguardFilters/issues/67572)

### Issue URL (Incorrect Blocking)
 [https://www.igromania.ru/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.igromania.ru%2F)
### Comment
Username: @AdguardUser
> (Текст от техподдержки Адгард)
> По поводу некорректного отображения некоторых сайтов: 
> Пожалуйста, попробуйте выполнить следующие шаги для решения проблемы:1.Перейдите в AdGuard > Настройки > Общие;
> 2.Прокрутите в конец страницы и выберите “Расширенные настройки“;
> 3.Измените настройки опции “Фильтровать локальные адреса“.
> Если включение указанной опции не принесло результата, следует обратить внимание на настройки “Перехватывать запросы на создание TCP соединений” и “Использовать Драйвер в режиме перенаправления“. Попробуйте различные комбинации этих настроек.
> 
> (Мой ответ)
> Перепробованы все возможные предложенные комбинации. При чем сайт https://www.igromania.ru/ указанным некорректным образом открывается только в браузере Гугл Хром, который установлен основным. В Опере и IE сайт открывается нормально, все блоки сайта на месте. А в Хроме просто белый экран и кнопки наверху. При чём, как было указано раньше, изначально сайт открывается полноценно, но через секунду всё пропадает, кроме кнопок, и остается только белый экран.
> 
> (Для сравнения добавлен скриншот этого же сайта из браузера Опера, через него сайт работает корректно. А в Хроме сайт открывается полноценно лишь на пару секунд, а потом - просто белый экран и кнопки)
> --
> Информация ниже сгенерирована автоматически. Не удаляйте ее.
> 
> Referrer:
> https://www.igromania.ru/
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
> https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/k6ElLwx.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/rUyfdPx.png)
</details>
<details>
  <summary>Screenshot 3</summary>

  ![Screenshot 3](https://reports-img.adguard.com/lFd5BCj.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.5.2
Browser: | Chrome
AdGuard driver: | TDI
Stealth mode options: | Hide your search queries, <br/>Send Do-Not-Track header, <br/>Remove X-Client-Data header from HTTP requests, <br/>Self-destructing third-party cookies (180)
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/> AdGuard Russian
Other extensions used: | Kaspersky Internet Security 21.1.15.500(c)

**Comment by Alex-302** [comment]
Not reproduced on my end.

**Comment by TheHasagi** [comment]
@AdguardUser

А попробуйте обновиться до последней [Nightly](https://agrd.io/windows_nightly) версии и попробовать еще раз.

**Comment by TheHasagi** [comment]
Closed due to no response.
