### ISSUE TITLE
AdGuard не фильтрует домен, который как вредоносный блокирует Norton Security

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/CoreLibs#1380]
При посещении торрент-трекера http://riperam.org/ антивирус Norton Security 22.20.5.39 ориентировочно с октября стал выдавать попытки вторжения с домена `cdn.mp3vizor.com`, который должен фильтроваться правилом в Русском фильтре: `||mp3vizor.com^$third-party`
В журнале фильтрации указанный домен у меня отражается как `tcp://cdn.mp3vizor.com:443` и имеет Status — Bypassed.
При этом у ваших разработчиков фильтров (без использования Norton)  фильтруется https://github.com/AdguardTeam/AdguardFilters/issues/66224.
У меня данный домен тоже сразу же фильтруется в случае изменения ip-адреса в браузере через VPN-расширение, и тогда антивирус в такой ситуации никак уже себя не проявляет. И при включении AdGuard DNS тоже антивирус молчит.

<details><summary>Screenshot:</summary>

![-](https://user-images.githubusercontent.com/50718960/99727062-7b932a00-2ac8-11eb-9f27-6151c06903a9.png)
![2](https://user-images.githubusercontent.com/50718960/99727846-93b77900-2ac9-11eb-880f-9e4477798354.png)
![3](https://user-images.githubusercontent.com/50718960/99727851-94e8a600-2ac9-11eb-94e9-4c2fe0fd1e27.png)
![4](https://user-images.githubusercontent.com/50718960/99727852-95813c80-2ac9-11eb-9329-d71cc1102139.png)

</details><br/>

**Comment by zubrRB** [comment]
В свете поднятой Яндексом и Лабораторией Касперского [паникой ](https://habr.com/ru/company/yandex/blog/534586/) касаемо известных расширений с многомиллионной аудиторией, зашёл на сайт самого известного из них https://ru.savefrom.net/7/. И там подобная ситуация. Norton Security блокирует на сайте данного расширения атаку со стороны `inpagepush.com` aka `tcp://inpagepush.com:443` (в журнале фильтрации), по которому имеется правило `||inpagepush.com^` в Базовом фильтре AdGuard и Фильтре раздражителей.

<details><summary>Screenshot:</summary>

![-](https://user-images.githubusercontent.com/50718960/103105872-bb0de280-4641-11eb-8637-6b92f636a58e.png)
</details><br/>

**Comment by ameshkov** [comment]
Ну это та же история - мы ждем пока по соединению попытаются отправить данные, чтобы точно распознать что это. А туда ничего не идет.

**Comment by zubrRB** [comment]
Антивирус быстрее перехватывает и до AdGuard уже не доходит?)

**Comment by ameshkov** [comment]
Ну несколько вариантов.

Либо они первые хватают и нам ничего не остается.
Либо они хватают вторые, но прерывают соединение раньше нас. Мы то обычно ждем пока TLS установится, чтобы показать страничку про то, что "доступ заблокирован".

**Comment by zubrRB** [comment]
А примитивное proxy-расширение влияет на то, что при его включении первым реагирует AG.

**Comment by ameshkov** [comment]
Ну почему бы и нет, может нортон начинает по-другому блокировать когда трафик через прокси идет.

**Comment by zubrRB** [comment]
> Мы то обычно ждем пока TLS установится, чтобы показать страничку про то, что "доступ заблокирован".

Там страничка "доступ заблокирован" не должна вылазить, чисто фильтроваться сторонние домены.
Отключаю в антивирусе всё, что только можно (автоматическую защиту, интеллектуальный брандмауэр), в Центре уведомлений и самом NS показывает, что функции отключены, но AdGuard все равно не может отфильтровать.

**Comment by ameshkov** [comment]
А вы в браузере открываете просто? А если `||inpagepush.com^$all`, заблокирует?

**Comment by zubrRB** [comment]
Да, просто в Chrome. Параллельное добавление в пользовательский фильтр `||inpagepush.com^$all` ничего не меняет. Единственное, что с этим правилом при одновременном отключении `||inpagepush.com^` в базовом и  фильтре 
раздражителей при попытке захода по прямой ссылке  https://inpagepush.com/400/2983203 выдаёт жёлтую страницу: 

> Запрос заблокирован AdGuard 
AdGuard предотвратил загрузку этой страницы в соответствии со следующим правилом фильтрации ||inpagepush.com^$document,popup

Если же отключить правила по этому домену с включенным VPN-расширением в Chrome антивирус перестаёт как-либо на неё реагировать, а сама ссылка фигурирует в журнале фильтрации AG.

**Comment by ameshkov** [comment]
Ну это уже проблема антивируса, что он не может внутрь проксированного трафика смотреть
