### ISSUE TITLE
JS rules don't work in Samsung Browser v13

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1381]
It seems that JavaScript rules don't work on HTTPS websites in Samsung Browser (Beta) version 13.0.1.64

### Steps to reproduce
1. Install Samsung Browser Beta - https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser.beta
2. Add this rule to user filter:
```
adguard.com,example.org#%#alert(1);
```
3. Go here - https://adguard.com/

### Expected behavior

JavaScript rules should work and there should be an alert box.
### Actual behavior

JavaScript rules don't work on HTTPS websites.
But it works fine on HTTP websites, for example here - http://example.org/

### Your environment

* Samsung Browser (Beta) version 13.0.1.64
* AdGuard for Android v4.0 nightly 7(37)

**Comment by artemiv4nov** [comment]
Hi, @AdamWr !
I just checked your rule in the Samsung browser (both stable and beta versions), and it worked!

Perhaps, one of the beta versions was bugged.

**Comment by AdamWr** [comment]
Hi, @artemiv4nov :)
Unfortunately it still doesn't work on my end.
With AdGuard for Android v4.0 nightly 9(48) and Samsung Browser version 13.2.1.70

**Comment by sfionov** [comment]
@AdamWr This problem was fixed in CoreLibs 1.7.151 and should be already in 3.6 hotfixes. While last published nightly have 1.7.150.

**Comment by AdamWr** [comment]
Okay, I didn't know about that.
Thank you for the information.
