### ISSUE TITLE
Add a "noop" modifier `_`

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1387]
* [x] Check the justification for it here: https://github.com/uBlockOrigin/uBlock-issues/issues/1356#issuecomment-735280463
* [x] Once it's done, please file a new issue to tsurlfilter: https://github.com/AdguardTeam/tsurlfilter
* [x] Also, open a pull request to KB

**Comment by sxgunchenko** [comment]
core/pull-requests/2240
