### ISSUE TITLE
Improve the way negation works for $redirect rules

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1388]
Negating $redirect rules should work just like $replace, $csp and $cookie do.

**Negating $redirect**

This sort of rules work pretty much the same way it works with `$csp` and `$replace` modifiers.

Use `@@` to negate `$redirect`:

* `@@||example.org^$redirect` -- negates **all** `$redirect` rules for URLs that match `||example.org^`.
* `@@||example.org^$redirect=redirectName` -- negates the rule with `$redirect=redirectName` for any request matching `||example.org^`.

* [x] Once it's done, please file a new issue to tsurlfilter: https://github.com/AdguardTeam/tsurlfilter
* [x] Also, open a pull request to KB

**Comment by sxgunchenko** [comment]
core/pull-requests/2237
