### ISSUE TITLE
Encrypted DNS queries aren't sent through the Oubound Proxy configured in AdGuard for Android settings

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/CoreLibs#1390]
@ryota-hasegawa commented on [Tue Dec 15 2020](https://github.com/AdguardTeam/AdguardForAndroid/issues/3692)

### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 4.0 nightly 9 (4.0.48)
- **Filtering mode:**
  - Local VPN (Maybe both)
- **Device:**
  - any
- **Operating system and version:**
  - any supported
- **Root access:**
  - No

### Expected Behavior
Encrypted DNS requests (e.g. DoH or maybe DoT (I tested only DoH)) should be sent through a proxy includes compatible AdGuard VPN

### Actual Behavior
Requests won't be sent through proxy, so my IP address is exposed to DNS server because of them
I found this problem from logs on NextDNS

### Screenshots
<details><summary>Screenshot:</summary>
Nothing
</details>

### Additional Information
I'm sorry for my fluent Engrish

**Comment by sfionov** [comment]
Not CoreLibs problem, should be resolved in AdGuard for Android application.

DnsLibs part is already done (https://github.com/AdguardTeam/DnsLibs/issues/78)
