### ISSUE TITLE
RU AdList JS Fixes usercript issue

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1391]
@adguard-bot commented on [Sun Dec 13 2020](https://github.com/AdguardTeam/AdguardFilters/issues/69924)

### Issue URL (Incorrect Blocking)
 [https://market.yandex.ru/catalog--smartfony-v-omske/16814639/list?cpa=0&hid=91491&glfilter=16816262%3A16816264&onstock=1&local-offers-first=0](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fmarket.yandex.ru%2Fcatalog--smartfony-v-omske%2F16814639%2Flist%3Fcpa%3D0%26hid%3D91491%26glfilter%3D16816262%253A16816264%26onstock%3D1%26local-offers-first%3D0)
### Comment
> Не корректно работает с расширением RU AdList JS Fixes, не сортируется по "цене, рейтингам, отзывам и т.д."
> --
> Информация ниже сгенерирована автоматически. Не удаляйте ее.
> 
> Referrer:
> https://market.yandex.ru/
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
> https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/G0yG0XO.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/IZt4opm.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.5.3
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br/>Send Do-Not-Track header, <br/>Remove X-Client-Data header from HTTP requests, <br/>Self-destructing third-party cookies (180), <br/>Block WebRTC
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> EasyList China, <br/>EasyList Czech and Slovak, <br/>EasyList Italy, <br/>AdGuard French, <br/>AdGuard Russian, <br/>AdGuard German, <br/>AdGuard Dutch, <br/>AdGuard Spanish/Portuguese
Other extensions used: | RU AdList JS Fixes

**Comment by Alex-302** [comment]
Повторяется. Адрес скрипта https://greasyfork.org/scripts/19993-ru-adlist-js-fixes/code/RU%20AdList%20JS%20Fixes.user.js

**Comment by ameshkov** [comment]
Блин, ну это будет сложно. JS Fixes очень "инвазивно" работает и может ломать нам контент скрипт

**Comment by ameshkov** [comment]
Очень рекомендую отключить popup blocker в таком случае
