### ISSUE TITLE
Add full regex support for $network rules

### ISSUE THREAD

**Issue by sxgunchenko** [AdguardTeam/CoreLibs#1394]
For now, only wildcards are supported (like `127.0.*$network`), but there is a feature request for full regex support (see https://github.com/AdguardTeam/AdguardForAndroid/issues/3694).
The syntax of $network rules with regex mask should be [the same](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#regexp-support) as for other basic rules (like `/.+:[1-3][0-9]{2,5}/$network`).

**Comment by sfionov** [comment]
Such rules can't be converted to CIDR kernel rules (feature used on Mac). But anyway they will be applied on proxy level.

**Comment by ameshkov** [comment]
> feature used on Mac

On pre-BigSur Mac you mean? :)
