### ISSUE TITLE
Network issues with AdGuard + NEContentFilter / Little Snitch / Trend Micro

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#1396]
This is main task for Little Snitch problem.

This incompatibility is reported to Apple 2 months ago:
FB8918126
https://developer.apple.com/forums/thread/667962

Related tasks: 
#1371 
#1375 
#1389 
AdguardTeam/AdguardForMac#776
AdguardTeam/AdguardForMac#777
AdguardTeam/AdguardForMac#786
AdguardTeam/AdguardForMac#788 
AdguardTeam/AdguardForMac#789 
AdguardTeam/AdguardForMac#790 
AdguardTeam/AdguardForMac#797 
AdguardTeam/AdguardForMac#798 
AdguardTeam/AdguardForMac#802

**Comment by ameshkov** [comment]
Might be partly resolved in 11.2 Beta 2
