### ISSUE TITLE
AdGuard with VPN mode blocks breaks syncing in Microsoft To Do

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1397]
@adguard-bot commented on [Sat Jan 09 2021](https://github.com/AdguardTeam/AdguardFilters/issues/71951)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=com.microsoft.todos](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.microsoft.todos)
### Comment
Username: @gabbsmo
> AdGuard with VPN mode blocks breaks syncing in Microsoft To Do. Proxy mode is fine. 
> 
> I say break because no request are actually blocked according to the filtering log. I get this error with all content blocking filters and DNS blocking disabled.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/K5buOTH.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/pfHW4YA.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 8.0.0
AdGuard product: | AdGuard for Android v3.6 (1)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | disabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> Frellwit's Swedish Filter
Custom filter subscriptions: |

**Comment by TheHasagi** [comment]
@gabbsmo

All tasks are synced ok, no such error occurs. Could you uncheck protection for To-Do application in AdGuard - Settings - Apps management - To Do and check again?
