### ISSUE TITLE
Validate the modifier in conjunction with the rule type

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#14]
See `testUrlFilterRuleWithWrongOption`

The following modifiers can be used in whitelist rules **only**:
`elemhide`
`jsinject`
`generichide`
`genericblock`
`content`

Blacklist rules **only**:
`mp4`
`empty`
`replace`

**Comment by hmage** [comment]
Fixed in commit 3d6c132a0ebe6b90d9e950d1c42cf92e1046166c.
