### ISSUE TITLE
Check fast.com result on Android with CoreLibs filtering (vs the old engine)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#140]

**Comment by sfionov** [comment]
Average speed:
Without VPN: 49.3 mbps
Adguard: 15.6 mbps
Test app: 28.6 mbps

**Comment by ameshkov** [comment]
Logging, asm?

**Comment by sfionov** [comment]
Without logging and with asm, average speed:
Without VPN: 84.0 mbps
Adguard: 32.0 mbps
Test app: 76.3 mbps

**Comment by ameshkov** [comment]
Awesome!
