### ISSUE TITLE
GM_xmlhttpRequest does not work correctly

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#1400]
@bestpika commented on [Sat Jan 16 2021](https://github.com/AdguardTeam/AdguardForWindows/issues/3664)

### Steps to reproduce

1. Install <https://greasyfork.org/scripts/420151/code/Steam历史最低价格查询.user.js>.
1. Go to any Steam product page like <https://store.steampowered.com/app/1257290/>.

### Expected behavior

The product page will show the relevant price information, just like the first screenshot.

### Actual behavior

The product page will get stuck on retrieving data and you will see an error message in dev tools.
Just like the second and third screenshots.

<details><summary>Screenshot</summary>

![1257290](https://user-images.githubusercontent.com/5698157/104796470-76650980-57f1-11eb-893c-f753af546a28.png)
![1257290](https://user-images.githubusercontent.com/5698157/104796472-7c5aea80-57f1-11eb-96e7-b52828ab7edc.png)
![image](https://user-images.githubusercontent.com/5698157/104796484-a6aca800-57f1-11eb-928e-dfe92fe53411.png)

</details>

### Your environment

Windows 10 x64 and 8.1 x64
AdGuard 7.6 nightly 12 (build 3452, CL 1.7.153)
Cent Browser 4.3.9.248 x86 (Chromium 86.0.4240.198)

**Comment by adbuker** [comment]
@bestpika, could you please specify whether the issue is reproducible on the versions, earlier or equal to [7.6 nightly 6](https://static.adguard.com/windows/nightly/setup-7.6.3435.0.exe)

**Comment by bestpika** [comment]
@adbuker I was able to reproduce the same error with nightly 6.
I even turned all but one other feature off.
![image](https://user-images.githubusercontent.com/5698157/105117939-5c386d80-5b08-11eb-92a2-32b419bb6bc5.png)
![image](https://user-images.githubusercontent.com/5698157/105118050-9570dd80-5b08-11eb-9071-eaa948f45434.png)

**Comment by bestpika** [comment]
This problem seems to be caused by your server not turning on the CORS response header.

**Comment by Lutra-Fs** [comment]
I meet this problem with a different appearance. 
![image](https://user-images.githubusercontent.com/36790218/124100866-2da0c480-daa2-11eb-9170-d96781ed1580.png)
The Promise is fulfilled with an undefined result.

**Comment by Lutra-Fs** [comment]
Another appearance
![image](https://user-images.githubusercontent.com/36790218/124104691-df8dc000-daa5-11eb-983a-d54f882c049e.png)

**Comment by ngorskikh** [comment]
A workaround is to make sure that the script name as stated in the `// @name   ` metadata header does not contain any non-ASCII or non-printable characters (the script can be edited from the application). Fix coming soon.

**Comment by Lutra-Fs** [comment]
Hi Nikita,
I have tried changing the header to English but there is still some issue between the script and AdGuard, test on the latest stable and nightly build (7.7 nightly 30).
on Firefox:
![image](https://user-images.githubusercontent.com/36790218/142700609-230e5206-f5d1-4424-90ab-c81648a38a0e.png)
on Microsoft Edge:
![image](https://user-images.githubusercontent.com/36790218/142700654-00c380a1-9f10-4f36-aa09-728fe7f3f5a5.png)

**Comment by ngorskikh** [comment]
@Lutra-Fs It looks like there's an error in the script on line `314`: it accesses `response.response` instead of `response.responseText`: https://wiki.greasespot.net/GM.xmlHttpRequest#Response_Object

**Comment by Lutra-Fs** [comment]
Thanks for the helping. Not familiar with the GM script, so not find the issue. Now things work well!
