### ISSUE TITLE
VPN Selective mode causes a speed downgrade for non-listed domains

### ISSUE THREAD

**Issue by lolka4toli** [AdguardTeam/CoreLibs#1403]
The problem occurs on the speedtest.net service. It isn't listed in the mode list, same is for any Ookla's domain. Endpoints are the same while using Selective mode and turning off the VPN-connection. Speed downgrade while using the Selective mode is up to 90%.

**Comment by lonsdaleite** [comment]
When are you going to fix this? Selective mode doesn't make sense because of the speed downgrade.
