### ISSUE TITLE
Android app is incompatible with AdGuard filtering

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1404]
The app itself: [cn.cntv-7.1.1-7110-6174.apk.zip](https://github.com/AdguardTeam/CoreLibs/files/5898183/cn.cntv-7.1.1-7110-6174.apk.zip)

It does not work with AdGuard filtering enabled AND ad blocking / https filtering disabled at the same time. However, it does work okay with a different VPN app so the problem must be in the way we bypass traffic in CoreLibs.

* Video with AdGuard: [2021-01-30 18.17.33.mp4.zip](https://github.com/AdguardTeam/CoreLibs/files/5898184/2021-01-30.18.17.33.mp4.zip)
* Video with a different VPN: [2021-01-30 18.17.38.mp4.zip](https://github.com/AdguardTeam/CoreLibs/files/5898185/2021-01-30.18.17.38.mp4.zip)

**Comment by ameshkov** [comment]
The same issue happens with the Windows version of the same app: https://app.cctv.com/appkhdxz/more/index.shtml#page5

**Comment by ngorskikh** [comment]
Got the Windows application working with:
```
@@47.254.129.207:444$network
@@47.254.170.55:444$network
```
It is sending something that looks like HTTP, but isn't.

At the moment, no idea why it doesn't work on Android. I've checked, and it actually doesn't work with other VPNs, too (Windscribe).

**Comment by ameshkov** [comment]
Well, probably we should just provide this solution to the user and be done with it then.
