### ISSUE TITLE
Broken app: com.vsct.vsc.mobile.horaireetresa.android

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1407]
@akmLaVx commented on [Mon Feb 01 2021](https://github.com/AdguardTeam/AdguardFilters/issues/73831)

[//]: # (***You can delete or ignore strings starting with "[//]:" They will not be visible either way.)

***Description***:

App link: https://play.google.com/store/apps/details?id=com.vsct.vsc.mobile.horaireetresa.android&hl=en&gl=US

* **Current behaviour**: 

App throws an "internet connection error" when protection is on.

<details><summary>Screen recording:</summary>

https://mega.nz/file/9Pwg3TJJ#FV-49ZnZK0gIXY0xHhiHsLavgGceG7emNTkt24__mN8

</details><br/>

***Steps to reproduce the problem***:

1. Launch the app and try to reserve a ticket

***System configuration***

**Filters:**

Information                            | Value
---                                    | ---
Operating system:                      | Android
Operating system version (Android/iOS) | 8
Browser:                               | n/a
AdGuard version:                       | 3.6.1
Filters enabled:                       | "Filtre AdGuard Anti nuisances", "Online Malicious URL Blocklist", "Filtre AdGuard des publicités pour mobile", "Filtre AdGuard Anti espionnage", "Fanboy's Social Blocking List", "Filtre AdGuard pour médias sociaux", "Je ne m'intéresse pas aux cookies", "Filtre AdGuard Français", "Filtre Anglais AdGuard"
AdGuard mode (Android only):           | VPN 
Filtering quality (Android only):      | High-quality 
HTTPS filtering (Android only):        | On (Default)
AdGuard DNS:                           | Default DoH
Stealth mode options (Windows only)    | none
Helpdesk ID (if exists):               | 1941291

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

---

@aranud87 commented on [Thu Feb 04 2021](https://github.com/AdguardTeam/AdguardFilters/issues/73831#issuecomment-771191900)

Hi,

I do 2 screenshot with log, i don't found how export

Thank you

EDIT : I try too many exclusions but not run :(

[Screenshot_20210201-230340_AdGuard](https://user-images.githubusercontent.com/2754191/106523875-12755d00-64e2-11eb-9399-fdd6a73eabf8.jpg)

[Screenshot_20210201-230323_AdGuard](https://user-images.githubusercontent.com/2754191/106523869-10ab9980-64e2-11eb-91f1-86a87bd8aae6.jpg)

---

@Alex-302 commented on [Thu Feb 04 2021](https://github.com/AdguardTeam/AdguardFilters/issues/73831#issuecomment-773241875)

@aranud87 Hi. Could you please test when all filters and DNS filtering are disabled, but protection is enabled?

---

@aranud87 commented on [Thu Feb 04 2021](https://github.com/AdguardTeam/AdguardFilters/issues/73831#issuecomment-773325708)

> @aranud87 Hi. Could you please test when all filters and DNS filtering are disabled, but protection is enabled?

Hi,

I do video with disable all and activate Adguard and it is not run as you ask : 
https://mega.nz/file/9TQTVaZa#UHn1bnpGIYwPxANUdAkrM0q-wwjnlANy8u7M6j36fjc

---

@Alex-302 commented on [Thu Feb 04 2021](https://github.com/AdguardTeam/AdguardFilters/issues/73831#issuecomment-773414485)

Great, thanks. It seems AdGuard's bug. I will move this issue to another repository.
Could you please collect debug logs and sent to support@adguard.com?(attach link of the issue to email)
How to collect logs:
https://kb.adguard.com/en/android/solving-problems/log

**Comment by Alex-302** [comment]
@aranud87 you may answer here.

**Comment by aranud87** [comment]
I do 
[adguard_logs_3.6.1_0402_170905.zip](https://github.com/AdguardTeam/CoreLibs/files/5927049/adguard_logs_3.6.1_0402_170905.zip)

**Comment by Chinaski1** [comment]
@aranud87 
Hello!
Try to disable the AdGuard Tracking protection filter will there be any changes?

**Comment by Chinaski1** [comment]
Open this task if the issue occurs again.
