### ISSUE TITLE
Verizon Voicemail app is not working

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1410]
@divisionparzero commented on [Fri Feb 05 2021](https://github.com/AdguardTeam/AdguardFilters/issues/74140)

Hello.

Recently Adguard started blocking the Verizon voicemail app from reaching its servers. I don't get a lot of calls so I'm not exactly sure how long it started. when I pause adguard it works again. I've whitelisted the app for now but just thought y'all would want to address it. I believe the myverizon app was also affected but I've already whitelisted it and don't feel like testing again.

Thanks! 

---

@Alex-302 commented on [Mon Feb 08 2021](https://github.com/AdguardTeam/AdguardFilters/issues/74140#issuecomment-775067601)

Probably filtering bug.

**Comment by Alex-302** [comment]
@divisionparzero Hi. You can write here.

**Comment by Chinaski1** [comment]
@divisionparzero

Please provide a link to the application where the issue occurs.

**Comment by Chinaski1** [comment]
@divisionparzero
Any news?
There are quite a few Verizon voicemail apps in the play store, so I would like to clarify which app in question.

**Comment by Chinaski1** [comment]
The task is closed as the user has not provided further information.
Re-open the task if the issue still persists.

**Comment by elpatogrande** [comment]
This problem continues. It's happening on my Samsung Galaxy S23 Ultra with the App: https://play.google.com/store/apps/details?id=com.vzw.hss.myverizon&hl=en&gl=US
version 17.1.00.15

I'm considering paying for Adguard and resolving this problem is key to my deciding to proceed.

**Comment by sfionov** [comment]
@elpatogrande Can you please reproduce this problem with debug logging enabled and send logs archive to devteam@adguard.com ?

Here is KB article about how to collect debug logs: https://adguard.com/kb/adguard-for-android/solving-problems/log/
