### ISSUE TITLE
blockchain.com is broken

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1411]
@adguard-bot commented on [Tue Feb 09 2021](https://github.com/AdguardTeam/AdguardFilters/issues/74409)

### Issue URL (Incorrect Blocking)
 [https://www.blockchain.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.blockchain.com%2F)
### Comment
Username: `@MrRobb`
> 
> --
> The information below is automatically generated. Do not delete it.
> 
> Referrer:
> 
> 
> Custom userscripts:
> https://userscripts.adtidy.org/beta/popup-blocker/2.5/popupblocker.meta.js
> https://userscripts.adtidy.org/beta/adguard-wot/1.0/wot.meta.js
> https://userscripts.adtidy.org/beta/adguard-extra/1.0/adguard-extra.meta.js
> https://userscripts.adtidy.org/beta/assistant/4.3/assistant.meta.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/czcpa0a.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/241DTxb.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.5.2.942 nightly
Browser: | Safari
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/> AdGuard German, <br/>AdGuard Dutch, <br/>AdGuard Spanish/Portuguese, <br/>Bulgarian list, <br/>EasyList Czech and Slovak, <br/>EasyList Italy

**Comment by Alex-302** [comment]
Only this exclusion helps: `@@||blockchain.com^$document`

**Comment by sfionov** [comment]
Seems to be CSP-patching problem

**Comment by ameshkov** [comment]
@sfionov hotfix?

**Comment by sfionov** [comment]
Yep, it is our bug - every sitee script has invalid nonce, which is rejected by browser, but adguard assumes that csp directive have nonce and add its nonce, denying all site's resources.

**Comment by sfionov** [comment]
But it is extremely rare I think.

**Comment by sfionov** [comment]
Fixed in 1.7.188
