### ISSUE TITLE
hd.kinopoisk.ru

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/CoreLibs#1412]
@adguard-bot commented on [Tue Feb 02 2021](https://github.com/AdguardTeam/AdguardFilters/issues/73901)

### Issue URL (Incorrect Blocking)
 [https://hd.kinopoisk.ru/film/4901b2e6dc7be0eda7432eedca82a783?episode=10&season=3&watch=](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fhd.kinopoisk.ru%2Ffilm%2F4901b2e6dc7be0eda7432eedca82a783%3Fepisode%3D10%26season%3D3%26watch%3D)
### Comment
> 
> --
> Информация ниже сгенерирована автоматически. Не удаляйте ее.
> 
> Referrer:
> 
> 
> Custom userscripts:
> https://greasyfork.org/scripts/19993-ru-adlist-js-fixes/code/RU AdList JS Fixes.user.js
> https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
> https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
> https://userstyles.org/styles/userjs/101141/ru-adlist-css-fixes.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/K9zcAJA.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/JnxkUp7.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.5.3
Browser: | Во всех браузерах такая проблема. Ссылка на сериал "сверхъестественное", но не грузит любой фильм или сериал
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (180)
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> Latvian List, <br/>AdGuard Russian
Other extensions used: | проблема не в них, т.к. после отключения десктопной версии Adguard и обновления сайта - он начинает работать

---

@stanislav-atr commented on [Tue Feb 09 2021](https://github.com/AdguardTeam/AdguardFilters/issues/73901#issuecomment-775852785)

Добрый день! Вы пользуетесь VPN? Проигрывание трейлера у меня работает, но с VPN отлетают кнопки.
@AdguardTeam/filters-maintainers, please, take a look.

---

@ozuuu commented on [Tue Feb 09 2021](https://github.com/AdguardTeam/AdguardFilters/issues/73901#issuecomment-775993017)

> Добрый день! Вы пользуетесь VPN? Проигрывание трейлера у меня работает, но с VPN отлетают кнопки.
> @AdguardTeam/filters-maintainers, please, take a look.

Здравствуйте, нет, vpn отключен

---

@zloyden commented on [Wed Feb 10 2021](https://github.com/AdguardTeam/AdguardFilters/issues/73901#issuecomment-776626377)

Похоже на баг, связанный со скриптом `https://greasyfork.org/scripts/19993-ru-adlist-js-fixes/code/RU AdList JS Fixes.user.js`
Выключите пока что сторонние скрипты, я перенесу задачу в другой репозиторий.

**Comment by sfionov** [comment]
@zloyden Если это ruadlist, причём тут мы? :)

**Comment by zloyden** [comment]
@sfionov в расширении Tampermonkey их скрипт работает нормально, в нашей программе вот такое поведение.

**Comment by ozuuu** [comment]
Отключила RU AdList JS Fixes - кинопоиск починился, получается, проблема действительно в этом

**Comment by Chinaski1** [comment]
Также могу подтвердить, что при использовании указанного скрипта в AdGuard возникла проблема. С Tampermonkey работает корректно.
