### ISSUE TITLE
superonline.net is broken

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1413]
@adguard-bot commented on [Mon Feb 15 2021](https://github.com/AdguardTeam/AdguardFilters/issues/74941)

### Issue URL (Incorrect Blocking)
 [http://www.superonline.net/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fwww.superonline.net%2F)
### Comment
Username: `@unununium1232`
> Also happens on adguard android too
> --
> The information below is automatically generated. Do not delete it.
> 
> Referrer:
> http://www.superonline.net/
> 
> Custom userscripts:
> 
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/IvEWuC7.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/SwiHRH3.png)
</details>
<details>
  <summary>Screenshot 3</summary>

  ![Screenshot 3](https://reports-img.adguard.com/hva7nia.png)
</details>
<details>
  <summary>Screenshot 4</summary>

  ![Screenshot 4](https://reports-img.adguard.com/O1DsKwD.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.5.3
Browser: | Chrome
AdGuard driver: | WFP
DNS filtering: | server: `https://dns-unfiltered.adguard.com/dns-query`<br>
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Turkish, <br/>AdGuard French, <br/>AdGuard Russian, <br/>AdGuard German, <br/>AdGuard Spanish/Portuguese

**Comment by unununium1232** [comment]
after updated to 7.6.1 on windows the problem still exist.

**Comment by ameshkov** [comment]
@unununium1232 v7.6 uses CoreLibs v1.7, this issue is fixed in CL v1.8 which we're yet to use.

Expect it in 1-2 months (first in nightly builds, then beta/stable).
