### ISSUE TITLE
Error 400 bad request on s7.ru

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1414]
Reproduced with the latest AG for Mac nightly - CL-1.7.189.

### Steps to reproduce

1. Start booking a new flight
2. When you get redirected to ibe.s7.ru, you'll see intermittent 400 bad request errors in the browser console

@sfionov please check if this is a CoreLibs issue and whether we need to push a hotfix or not.

**Comment by sfionov** [comment]
I can't reproduce it, there is no 400 errors on ibe.s7.ru in my browser
