### ISSUE TITLE
Some rules with $document modifier work incorrectly

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1421]
I'm not sure if it's a bug or just CoreLibs limitation.

### Steps to reproduce
1. Add this rule:
`||reddit.*^$document,domain=~reddit.com`
2. Go here - [https://duckduckgo.com/?q=site%3Areddit.com&ia=web](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://duckduckgo.com/?q=site%3Areddit.com&ia=web)
3.  Open/Click on any link

### Expected behavior
Website shouldn't be blocked.

### Actual behavior
Website is blocked and if I refresh website then it's not blocked anymore.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/110174205-14438080-7e00-11eb-9e2f-b7c2483ceee5.png)

</details>

It's also not blocked if I open it directly - [https://www.reddit.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.reddit.com/)

### Your environment

* AdGuard for Windows version 7.6 nightly 22 (build 3500, CL 1.7.202)

**Comment by sxgunchenko** [comment]
See https://github.com/AdguardTeam/CoreLibs/issues/1354#issuecomment-704226271 for the upcoming changes

**Comment by wout-codes** [comment]
@sxgunchenko This rule in Base filter works nowhere: `/advertisement.$~script,domain=~advertisement.solutions.zalando.com`, though it works with the extension. I can give an example if you want.

**Comment by sxgunchenko** [comment]
Yup, it seems like I need an example.

Tried some combinations of target and referrer and it works as expected (target = t, referrer = r) :
t = http://advertisement.com/some, r = http://example.com => blocked as rule's pattern matches the target
t = http://advertisement.com/some, r = http://advertisement.solutions.zalando.com => not matched as the referrer is explicitly excluded
t = http://advertisement.solutions.zalando.com/some, r = http://advertisement.com => blocked as the pattern matches the target (see my previous comment https://github.com/AdguardTeam/CoreLibs/issues/1421#issuecomment-795527069 about target exclusion)

**Comment by krystian3w** [comment]
Maybe a little help: https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#removeheader

**Comment by AdamWr** [comment]
It seems that now, rule like this:
```
||reddit.*^$document,domain=~reddit.com
```
blocks `reddit.com`, but I think that it shouldn't be blocked.

Steps to reproduce
1. Add this rule:
```
||reddit.*^$document,domain=~reddit.com
```
2. Go to - https://www.reddit.com/

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/147969329-0caebf9f-5511-479d-ac67-da31d9641d2c.png)

</details>

`reddit.com` shouldn't be blocked.

**Comment by krystian3w** [comment]
Also uBo started mark `*^` in that filters as no needed due `^` no protect path after `TLD/` or `TLD./`.

**Comment by Alex-302** [comment]
@krystian3w `*^` parsed as TLD only?

**Comment by krystian3w** [comment]
uBo use gray color in highlighter, so filter writers can remove this form projects.

IMO nice will be implement enforce limit to tld for `.*^` insted only mark as no power syntax.

**Comment by sxgunchenko** [comment]
> It seems that now, rule like this:
> 
> ```
> ||reddit.*^$document,domain=~reddit.com
> ```
> 
> blocks `reddit.com`, but I think that it shouldn't be blocked.
> 
> Steps to reproduce
> 
>     1. Add this rule:
> 
> 
> ```
> ||reddit.*^$document,domain=~reddit.com
> ```
> 
>     2. Go to - https://www.reddit.com/
> 
> 
> Screenshot
> 
> `reddit.com` shouldn't be blocked.
> 
> AdGuard for Windows version 7.9 nightly 3 (build 3789, CL 1.8.279)

Moved into a separate issue: https://github.com/AdguardTeam/CoreLibs/issues/1579
