### ISSUE TITLE
Pending requests on app.awork.io

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1423]
@adguard-bot commented on [Fri Feb 19 2021](https://github.com/AdguardTeam/AdguardFilters/issues/75308)

### Issue URL (Incorrect Blocking)
 [https://app.awork.io](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fapp.awork.io)
### Comment
> I am using AdGuard on my Windows PC (AdGuard for Windows) and I recently found out that it has issues with one specific website (app.awork.io). This is a paid project management tool (with a trial). The issue is that some requests simply do not go to their servers when navigating the website. I already had a session with their support staff and we found out that as long is AdGuard is active, some requests will show in Chrome Developer tab as "400 Bad Request" but never reach their servers. With AdGuard disabled it worked as expected with no issues.
> 
> I already went ahead and whitelisted the hole site but and there is no block in the AdGuard filter protocol but still timeouts and 400 Bad Request will appear. Therefore I think its an issue with the internal proxy or something network driver related. Please tell me what informations you need from me to analyze the issue.
> 
> Here are some specifics about my setup:
> 
> Windows 10 Pro 2004 - 19041.804
> AdGuard Version: 7.5.3 (build 3430, CL 1.7.150)
> Browser: Chrome 88.0.4324.150
> AV: Kaspersky Internet Security 21.2.16.590 (b)
> 
> I also already created a ticket (3212396)  with the support staff and tried the following:
>  AdGuard > Settings > General > Advanced settings and enable "Use driver in redirect mode", then click on "Save".
> AdGuard > Settings > General > Advanced settings and disable options called "Intercept TCP connection requests" and "Filter local connections"
> 
> The filter log in AdGuard shows the HTTP response code 0 and and empty response header for this request. 
> 
> If you need to my help, please contact me via the email assigned to the ticket number as I do not have an Github account.
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/C0oEeF1.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/YRCZToq.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.5.3 (build 3430, CL 1.7.150)
Browser: | Chrome
AdGuard driver: | WFP
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>I don't care about cookies<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/> AdGuard German
Other extensions used: | Kaspersky Internet Security 21.2.16.590 (b)

---

@Alex-302 commented on [Sat Feb 20 2021](https://github.com/AdguardTeam/AdguardFilters/issues/75308#issuecomment-782708618)

On my end that requests made without errors.
![image](https://user-images.githubusercontent.com/8361299/108601935-f3af0b80-73a7-11eb-9438-f4b01253fef9.png)

---

@Alex-302 commented on [Sat Feb 20 2021](https://github.com/AdguardTeam/AdguardFilters/issues/75308#issuecomment-782708700)

Please write to filters@adguard.com

**Comment by Alex-302** [comment]
Logs was sent to support@adguard.com

**Comment by akmLaVx** [comment]
Logs available in helpdesk ticket 2488614.

**Comment by akmLaVx** [comment]
Received additional HARs in helpdesk ticket Z501524.

**Comment by sfionov** [comment]
Can't be reproduced anymore. Please reopen if it happens.
