### ISSUE TITLE
www.seznamzpravy.cz

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1426]
@adguard-bot commented on [Wed Mar 24 2021](https://github.com/AdguardTeam/AdguardFilters/issues/78337)

### Issue URL (Ads)
 [https://www.seznamzpravy.cz/clanek/velikonoce-musi-lide-stravit-doma-pise-blatny-v-utajovane-zprave-148117](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.seznamzpravy.cz%2Fclanek%2Fvelikonoce-musi-lide-stravit-doma-pise-blatny-v-utajovane-zprave-148117)
### Comment
> 
> --
> Následující informace jsou automaticky generovány. Neodstraňujte je.
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/QWuNvWR.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 11
AdGuard product: | AdGuard for Android v3.6.1 (11)
Browser: | Brave browset
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode: | disabled
DNS filtering: | server: `Vodafone`<br>
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> EasyList Czech and Slovak
Other extensions used: | Avira active shield, Brave browser

**Comment by AdamWr** [comment]
Moved here, because it looks like a bug.

```
Refused to load the script 'https://local.adguard.org/[...]
```

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/112362004-41cf6b80-8cd4-11eb-97b9-86b42fbb7261.png)

</details>

It happens rather rarely and to reproduce it, it's necessary to refresh website few times, it seems that on Android it happens more frequently.

**Comment by ameshkov** [comment]
Are you able to reproduce this? Could it be that HTTPS is not filtered when this happens?

**Comment by AdamWr** [comment]
Yes, I can reproduce it and I can also reproduce this issue - https://github.com/AdguardTeam/CoreLibs/issues/1356
There is AdGuard certificate when it happens.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/112373677-8281b180-8ce1-11eb-8e92-e59e1ae9cc4c.png)

</details>

**Comment by ngorskikh** [comment]
core/pull-requests/2345
