### ISSUE TITLE
Add $header modifier support

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1433]
I think it makes sense to be able to target requests depending on the HTTP headers they have.

Basic idea is to be able to write something like this: `||example.org^$header=/regex/` where regex matches `headername: value` string.

We'll need to come up with a normal syntax spec for that before implementing it.

- [x] Syntax spec
- [x] Implementation
- [x] Update Knowledge base
- [x] Port to tsurlfilter

**Comment by sxgunchenko** [comment]
uBO (https://github.com/uBlockOrigin/uBlock-issues/wiki/Static-filter-syntax#header) and ABP (https://help.eyeo.com/adblockplus/how-to-write-filters#header-filter) already have such a modifier. So it seems like a rule converter update is required as well.

Here is the proposed spec (basically, it's an adapted uBO's one):

#### Basic modifiers

##### **`header`**

The `$header` modifier allows matching the HTTP response having a specific header with a specific value.

###### Syntax

```
$header "=" h_name [":" h_value]
h_value = string / regex
```

where

  * `h_name` — an HTTP header name. It is matched case insesitively.
  * `h_value` — the HTTP header value matching expression, and may be one of the following:
    * `string` — a sequence of characters. It is matched against the header value lexicographically.
    * `regex` — a regular expression, starts and ends with `/`. The pattern works the same way as in the basic URL rules, but the characters `/`, `$`, `,` and `|` must be escaped with `\`.

The modifier `":" h_value` part may be omitted. In that case the modifier matches the header name only.

> **Compatibility with different versions of AdGuard.** Rules with the `$header` modifier are supported by AdGuard for Windows, Mac, and Android, **running CoreLibs version 1.11 or later**.

###### Examples

`||example.com^$header=set-cookie:foo` — blocks the request which response has the `Set-Cookie` header with value matching `foo` literally.
`||example.com^$header=set-cookie` — blocks the request which response has a `Set-Cookie` header with any value.
`@@||example.com^$header=set-cookie:/foo\, bar\$/` — unblocks the request which response has the `Set-Cookie` header with value matching the `foo, bar$` regular expression.
`@@||example.com^$header=set-cookie` — blocks the request which response has a `Set-Cookie` header with any value.

**Comment by ameshkov** [comment]
Works for me

**Comment by piquark6046** [comment]
@ameshkov 
What about extending matching ability of  `$header` modifier to HTTP request header?
https://listauthorschat.slack.com/archives/C010N14G4TF/p1662830803562149

**Comment by ameshkov** [comment]
@piquark6046 generally, I am not against that, but it should be implemented in a safe manner (i.e. like we do with the `set-constant` scriptlet).

Could you please come up with a few examples where we would need to change the header instead of removing it?

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/CoreLibs/issues/1433#issuecomment-1243361370

> Could you please come up with a few examples where we would need to change the header instead of removing it?

How many you need to prove this issue?

**Comment by ameshkov** [comment]
Well, as many as possible:)

@AdguardTeam/filters-maintainers do you have any examples too?

**Comment by Alex-302** [comment]
If I remember correctly, we had some issues, which could be resolved by changing header(ads=enabled/disabled parameter).
May be it can be useful for anti-tracking purpose, when a parameter cannot be removed.

**Comment by ameshkov** [comment]
Well I need concrete examples in order to come up with the implementation details.

I'd like to avoid adding a modifier that would allow setting an arbitrary value as in this case we'll have to limit it's usage to AdGuard filters only.
