### ISSUE TITLE
Remove "strip tracking parameters" option from Stealth Mode

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1438]
This functionality can now be implemented as a filter list so product devs can simply enable that filter list and that's all.

Also, please do the following:

1. Grab the default parameters list and post it here.
2. We'll ask @AdguardTeam/filters-maintainers to create a new filter list for that.

@AdguardTeam/filters-maintainers what name would you like for that new list?

**Comment by sxgunchenko** [comment]
In fact, such a task has already been created (see https://github.com/AdguardTeam/AdguardFilters/issues/57197)

**Comment by ameshkov** [comment]
@sxgunchenko let's at least remove default hardcoded parameters as a part of this task then.

**Comment by sxgunchenko** [comment]
Actually, they have already been moved to the app side. There is nothing left in the CoreLibs related to the tracking parameters except the `$removeparam` rules processing.
