### ISSUE TITLE
Content filtering rule does not work for an element when max-width is set

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#144]
Here is the page content:
https://gist.github.com/Alex-302/b3bf27a2f950e763f0fbec4898e66945

The rule that should work:
`$$style[tag-content="position:relative;width:calc"][max-width="2000"]`

However, for some reason, it does not work properly unless I remove the `max-width` attribute.

**Comment by ngorskikh** [comment]
Should `max-width` be an alias for `max-length`?

**Comment by ameshkov** [comment]
Nope, for sure.

Let's close this as invalid, we can't even check the problematic code anymore.
