### ISSUE TITLE
On some websites there is not AdGuard certificate after disabling and then enabling protection

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1441]
Steps to reproduce:
1. Enable AdGuard
2. Open an incognito tab in Chrome and go here -  [https://kutchuday.in/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://kutchuday.in/)
The same happens on `https://www.facebook.com/` and `https://www.androidpolice.com/`
3. Disable protection
4. Refresh website
5. Enable protection
6. Refresh website

Protection is enabled but ads are not blocked and there is no AdGuard certificate.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/116539933-cd4aa680-a8e9-11eb-9cca-1530049cdcea.png)

</details>

It seems that it happens only on some websites and not every time, but often.
I have to restart web browser and then ads are blocked again.

AdGuard for Windows 7.6 nightly 40 (build 3584, CL 1.7.221)

**Comment by ameshkov** [comment]
@AdamWr quick question - are you on an IPv6-capable network?

**Comment by AdamWr** [comment]
No, if I'm not wrong, my network is using IPv4.

**Comment by ameshkov** [comment]
You can check it by visiting ipv6.google.com

We would probably need debug logs.

**Comment by AdamWr** [comment]
`ipv6.google.com` doesn't open on my end.
I checked also https://ipv6test.google.com/ and I see that:
```
We did not detect any problems.
You're not using IPv6 yet, but you shouldn't have any problems with sites that adopt IPv6 support.
```

The same happens on virtual machine/sandbox with AdGuard stable version (7.6.1).
I will create logs.

**Comment by ameshkov** [comment]
As far as I understand it was improved in Win v7.12 and it shouldn't be happening anymore.

**Comment by AdamWr** [comment]
It seems that it's fine on `https://www.androidpolice.com/`, but I still can reproduce it on `https://www.facebook.com/` and `https://www.youtube.com/` with AdGuard for Windows version 7.14 nightly 9 (build 4328, CL 1.11.118).

**Comment by ameshkov** [comment]
@AdamWr does it go away after a few more refreshes?

**Comment by AdamWr** [comment]
Unfortunately, it doesn't.
I have refreshed website many times, but there wasn't AdGuard's certificate.
