### ISSUE TITLE
Element hiding is not working on novosti-n.org

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1442]
Original issue
https://forum.adguard.com/index.php?threads/https-novosti-n-org.42811/
Banner must be blocked by the rule from Russian filter:
`novosti-n.org##a[target="_blank"][rel="nofollow"] > img`
Wide rules also not working:
`novosti-n.org##body *`
`novosti-n.org##body`
Disable all another adblockers before check.

**Comment by Alex-302** [comment]
Fixed by `novosti-n.org$$script[tag-content="setAttribute('type', 'text')"]`

**Comment by AdamWr** [comment]
If I understand correctly it will not be fixed.
Maybe it's not important issue, but I think that similar approach may be used on other websites as well.
If I understand correctly, currently there is protection from removing and modifying AdGuard style, so why not to add protection also for `type="text/css"`?

**Comment by Alex-302** [comment]
@sxgunchenko

**Comment by sxgunchenko** [comment]
It seems like a content-script issue. @slavaleleka what do you think?
