### ISSUE TITLE
planeta.ru cannot be opened

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1444]
@adguard-bot commented on [Fri Apr 30 2021](https://github.com/AdguardTeam/AdguardFilters/issues/81865)

### Issue URL (Incorrect Blocking)
 [https://planeta.ru/%2A](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplaneta.ru%2F%252A)
### Comment
Username: @Zelgadiss
> Проблема с https://planeta.ru началась после обновления 7.6.1, когда исправили вот эту штуку https://github.com/AdguardTeam/AdguardForWindows/issues/3758#issuecomment-825632767
> 
> и в настройках пропала возможность отключить принудительное использование tsl v1.3. Этот сайт и раньше при включенной этой настройке работал нестабильно.
> 
> Сейчас проблема выглядит так, что сайт после нескольких переходов по его ссылках перестаёт открываться, либо разлогинивает, либо отдаёт 404. Последние две проблемы возникают реже, чем зависание при открытии любой ссылки сайта.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/kPwcvSR.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/Si4Hr2n.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.6.1
Browser: | Firefox
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Disable cache for third-party requests, <br>Block Push API, <br>Block Location API, <br>Block Flash, <br>Block Java
DNS filtering: | server: `Google DNS`<br>
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Language-specific:</b><br/> AdGuard Russian
Userscripts: | Помощник AdGuard 4.3.47
AdGuard Extra 1.0.249
Блокировщик всплывающей рекламы от AdGuard 2.5.38
Web of Trust 1.1.22

**Comment by ameshkov** [comment]
Нет никакой связи с TLS 1.3.

Планета использует достаточно проблемный анти-ДДОС сервис, который триггерится на AdGuard в случае Firefox и ломает на сайте яваскрипт.

**Comment by Zelgadiss** [comment]
> Нет никакой связи с TLS 1.3.
Странно, что нет, т.к. в прошлой версии при его отключении проблема проходила. Хз конечно какая тут может быть связь.
> Планета использует достаточно проблемный анти-ДДОС сервис, который триггерится на AdGuard в случае Firefox и ломает на сайте яваскрипт.
Весело. Как workaround поюзаю для планеты пока другой бразер.
> Я отписал разработчикам планеты, надеюсь они со своей стороны разберутся.
Благодарю.

**Comment by ameshkov** [comment]
@Zelgadiss временное решение - отключить HTTPS-фильтрацию для planeta.ru (можно в настройках сети добавить их в белый список HTTPS-фильтрации).

Обратите внимание, что точно также планета в FF сломается при использовании любого VPN-сервиса и большинства прокси.

**Comment by Zelgadiss** [comment]
> временное решение - отключить HTTPS-фильтрацию для planeta.ru (можно в настройках сети добавить их в белый список HTTPS-фильтрации).

Отлично, спасибо.

> Обратите внимание, что точно также планета в FF сломается при использовании любого VPN-сервиса и большинства прокси.
Хм, надо почекать на личных прокси и впн. Интересный у них детектор =)
