### ISSUE TITLE
GM.setValue causes an error

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1446]
![image](https://user-images.githubusercontent.com/5947035/117527431-bafcf680-afd4-11eb-91f4-970d89eae86e.png)

Script to reproduce:
[test_GM.setValue.user.js.zip](https://github.com/AdguardTeam/CoreLibs/files/6445247/test_GM.setValue.user.js.zip)

**Comment by ngorskikh** [comment]
The same reason as in https://github.com/AdguardTeam/CoreLibs/issues/1400
Waiting on userscript-wrapper fix.

**Comment by ilvjyw** [comment]
@ameshkov  bug recurs in ver7.11

**Comment by ngorskikh** [comment]
@ilvjyw Hello! I can't reproduce the original issue with [test_GM.setValue.user.js](https://github.com/AdguardTeam/CoreLibs/files/6445247/test_GM.setValue.user.js.zip) from the first post on 7.11 right now. Do you have a script that triggers it?

**Comment by ilvjyw** [comment]
> @ilvjyw Hello! I can't reproduce the original issue with [test_GM.setValue.user.js](https://github.com/AdguardTeam/CoreLibs/files/6445247/test_GM.setValue.user.js.zip) from the first post on AdGuard for Windows 7.11 right now. Do you have a script that triggers it?

You can use a remote socks5 proxy to access the web page for testing

**Comment by ilvjyw** [comment]
![73WEZ)O3J J`19T9%JVZ8Q0](https://user-images.githubusercontent.com/3976203/198807790-74f0c970-069a-462d-9cf8-e1e6ed6e9f2d.png)
![HBBA8~NI D$GY7OVY1M 5R6](https://user-images.githubusercontent.com/3976203/198807948-79f28a50-3566-4086-b791-0cea2e559893.png)

**Comment by ilvjyw** [comment]
@ngorskikh use this to test ‘https://github.com/emCupid/adg_cn/raw/master/hack_plus.user.js’

**Comment by ameshkov** [comment]
Do you have a socks proxy configured in your browser? What extension do you use for that?

**Comment by ameshkov** [comment]
Moved it to a new bug:
https://github.com/AdguardTeam/CoreLibs/issues/1680

**Comment by ilvjyw** [comment]
> Do you have a socks proxy configured in your browser? What extension do you use for that?

https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif
You can add a valid proxy test
