### ISSUE TITLE
ad.admitad.com redirects are broken

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1452]
@adguard-bot commented on [Sun May 02 2021](https://github.com/AdguardTeam/AdguardFilters/issues/82120)

### Issue URL (Incorrect Blocking)
 [https://www.pepper.ru/visit/thread/176974](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.pepper.ru%2Fvisit%2Fthread%2F176974)
### Comment
Username: `@Alexey71`
> https://www.pepper.ru/deals/kabel-opticeskii-vsem-izvestnoi-firmy-aksesuarov-176974#comments-last
> Нажать "Перейти к скидке"

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/yMD6XJZ.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/bKOp4U2.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.6 nightly 41
Browser: | Firefox
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Self-destructing third-party cookies (180)
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Other:</b><br/> AdGuard Experimental<br/><br/><b>Language-specific:</b><br/> AdBlockID, <br/>AdGuard Russian
Userscripts: | https://greasyfork.org/scripts/1893-ru-board-whosonline-mod/code/RU-Board%20WhosOnline%20mod.user.js,<br>https://raw.githubusercontent.com/Alexey71/script-adguard/master/Kinozal.tv_Magnet_Links_Mod.js,<br>https://raw.githubusercontent.com/Alexey71/script-adguard/master/RuTor.org_Seed_Graph_Mod_%26_Search_Filter.js,<br>https://userscripts.adtidy.org/beta/popup-blocker/2.5/popupblocker.user.js,<br>https://userscripts.adtidy.org/beta/adguard-extra/1.0/adguard-extra.user.js

---

@Sergey-Lyapin commented on [Tue May 11 2021](https://github.com/AdguardTeam/AdguardFilters/issues/82120#issuecomment-833788661)

Не повторилось (с AG для Windows, Mac и Android)
@Alexey71 у вас еще повторяется?

---

@Alexey71 commented on [Thu May 06 2021](https://github.com/AdguardTeam/AdguardFilters/issues/82120#issuecomment-833791313)

@Sergey-Lyapin Конечно повторяется. Причем на 2 разных браузерах, Microsoft Edge и Firefox

---

@Sergey-Lyapin commented on [Thu May 06 2021](https://github.com/AdguardTeam/AdguardFilters/issues/82120#issuecomment-833796249)

@Alexey71 то есть вы нажимаете на кнопку "Перейти к скидке" и видите белый экран?

---

@Sergey-Lyapin commented on [Thu May 06 2021](https://github.com/AdguardTeam/AdguardFilters/issues/82120#issuecomment-833796594)

@Alex-302 @stanislav-atr @zloyden  посмотрите у себя

---

@Alexey71 commented on [Thu May 06 2021](https://github.com/AdguardTeam/AdguardFilters/issues/82120#issuecomment-833804152)

[msedge_3840x2040_06-05-2021_22H-28M-34S](https://user-images.githubusercontent.com/10572914/117354973-a7f60380-aeba-11eb-9014-092b9e126206.jpg)
[firefox_3840x2040_06-05-2021_22H-29M-52S](https://user-images.githubusercontent.com/10572914/117354978-a9273080-aeba-11eb-8746-40f1e32f0491.jpg)

---

@Alexey71 commented on [Sat May 08 2021](https://github.com/AdguardTeam/AdguardFilters/issues/82120#issuecomment-835468390)

Ну что? На телефоне тоже не открывает...

[Screenshot_20210508-214620](https://user-images.githubusercontent.com/10572914/117550084-eb7d7880-b046-11eb-9b77-45cd77ed1fd2.jpg)

---

@krystian3w commented on [Sun May 09 2021](https://github.com/AdguardTeam/AdguardFilters/issues/82120#issuecomment-835815358)

broken after direct opening `visit.digidip.net`? (https://github.com/AdguardTeam/CoreLibs/issues/1421)

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/118319250-2bd76d80-b503-11eb-9e3c-86192386838b.png)

Cannot open even all modules are disabled.

**Comment by Alexey71** [comment]
Так же ссылки такого плана https://fas.st/2dwQxJ тоже не открываются

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/82120 https://github.com/AdguardTeam/AdguardFilters/issues/83099

**Comment by Alex-302** [comment]
Similar issue: https://github.com/AdguardTeam/AdguardFilters/issues/82593

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/82593

**Comment by temis2k16** [comment]
seems like the issue is not reproducable anymore
@Alex-302 i would recommend to add rule `$removeparam=admitad_uid` to be sure that we reduce interactions with admitad (if it's not already added)

**Comment by Alex-302** [comment]
@temis2k16 We have this rule.
