### ISSUE TITLE
HTTPS filtering does not work for vd.l.qq.com

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1456]
Subj. Easy to reproduce, just try visiting it: https://vd.l.qq.com/

**Comment by AdamWr** [comment]
I'm not sure, but it looks like that `vd.l.qq.com` is in HTTPS exclusions - https://github.com/AdguardTeam/HttpsExclusions/blob/master/exclusions/sensitive.txt#L109
