### ISSUE TITLE
Userscripts compatibility issues

### ISSUE THREAD

**Issue by JohnnyWoong** [AdguardTeam/CoreLibs#1457]
1. https://www.baiduyun.wiki/install.html
2. https://greasyfork.org/zh-CN/scripts/329484-%E8%B1%86%E7%93%A3%E8%B5%84%E6%BA%90%E4%B8%8B%E8%BD%BD%E5%A4%A7%E5%B8%88-1%E7%A7%92%E6%90%9E%E5%AE%9A%E8%B1%86%E7%93%A3%E7%94%B5%E5%BD%B1-%E9%9F%B3%E4%B9%90-%E5%9B%BE%E4%B9%A6%E4%B8%8B%E8%BD%BD

**Comment by TheHasagi** [comment]
@JohnnyWoong 

Hello, seems like it's working fine on my side (see details). Can you share more details about the version of AdGuard and installed AV on your device?

<details>

![img](https://uploads.adguard.com/myMoonucqh9.png)

</details>

**Comment by JohnnyWoong** [comment]
> @JohnnyWoong
> 
> Hello, seems like it's working fine on my side (see details). Can you share more details about the version of AdGuard and installed AV on your device?
> 
> ![img](https://camo.githubusercontent.com/1729b69a5abd738bd3ed9ff2783545b56dd7376f3653fd4a3bd6a815702ee3a3/68747470733a2f2f75706c6f6164732e616467756172642e636f6d2f6d794d6f6f6e75637168392e706e67)

ADG7.6.1, how about first one? this two dont work in my computer

**Comment by TheHasagi** [comment]
@JohnnyWoong 

Unfortunately, I cannot register in that network to check if we can do something with it. But I've checked with another [extension](https://www.baiduyun.wiki/tool/install-panai.html) from the link you've provided and seems like it's ok too:

<details>

![img](https://uploads.adguard.com/myMoonch6h0.png)

</details>

Maybe you should check with only AdGuard & browser? I mean without any other extensions that can prevent the script's work.

**Comment by JohnnyWoong** [comment]
> @JohnnyWoong
> 
> Unfortunately, I cannot register in that network to check if we can do something with it. But I've checked with another [extension](https://www.baiduyun.wiki/tool/install-panai.html) from the link you've provided and seems like it's ok too:
> 
> Maybe you should check with only AdGuard & browser? I mean without any other extensions that can prevent the script's work.

The problem still same, by the way, if i use second user script by Tmonkey, 
![image](https://user-images.githubusercontent.com/5661094/119374719-7cfa1500-bcec-11eb-909b-839e81c173bd.png)
this part of it will disapper,but its not advertising

**Comment by TheHasagi** [comment]
@JohnnyWoong 

Seems like you have other extensions that block the work of the script. As you see it's working on my side with only AdGuard, script, and the browser.

Also, can you provide any examples where you don't need to register in social networks? It is about Netdisk issue.

**Comment by ameshkov** [comment]
Or maybe a test account we could use?

**Comment by JohnnyWoong** [comment]
Its no need for account, open https://movie.douban.com/subject/34913671/?tag=%E7%83%AD%E9%97%A8&from=gaia and you will see this part of it will disapper if you install https://greasyfork.org/zh-CN/scripts/329484-%E8%B1%86%E7%93%A3%E8%B5%84%E6%BA%90%E4%B8%8B%E8%BD%BD%E5%A4%A7%E5%B8%88-1%E7%A7%92%E6%90%9E%E5%AE%9A%E8%B1%86%E7%93%A3%E7%94%B5%E5%BD%B1-%E9%9F%B3%E4%B9%90-%E5%9B%BE%E4%B9%A6%E4%B8%8B%E8%BD%BD by Tmonkey

**Comment by Aydinv13** [comment]
Another compatibility issue with **YouTube: Age Verification Bypass** ( https://greasyfork.org/ru/scripts/375525-youtube-age-verification-bypass ) which is not working correctly (e.g here https://www.youtube.com/watch?v=NV-cnKFH8vU)

https://github.com/AdguardTeam/AdguardForWindows/issues/3835

**Comment by ameshkov** [comment]
One more: https://github.com/AlekPet/Rutor-Preview-Ajax/blob/master/RutorPreviewAjax.user.js

**Comment by sxgunchenko** [comment]
1. The issue with the douban download userscript should be fixed along with https://github.com/AdguardTeam/CoreLibs/issues/1400  
2. The verification bypass userscript is not available by https://greasyfork.org/ru/scripts/375525-youtube-age-verification-bypass, but https://greasyfork.org/en/scripts/423851-simple-youtube-age-restriction-bypass works fine
3. The rutor preview script uses `GM_addValueChangeListener` which is not implemented by our userscript wrapper. We already have a feature request for that (jira/AG-87)

**Comment by JohnnyWoong** [comment]
Yep, its working right now, thx :)
