### ISSUE TITLE
$removeparam rules are applied before URL blocking rules

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1462]
For this reason, some URL blocking rules may not work.

For example this URL
`http://example.org/?param1=1&param2=ad`
is blocked by(the rule like against redirections)
`&param2=ad$document,popup`
But if you add the rule below, request will not be blocked, because nothing to match
`$removeparam=param2`

https://github.com/AdguardTeam/tsurlfilter/issues/18

**Comment by sfionov** [comment]
So `$document,popup` rule without whitelist cookie should disable `$removeparam` rule. Then it will be applied after page reload.

**Comment by ameshkov** [comment]
In theory, `$document` blocking rules aren't unblocked (since main frame still needs to be blocked).

Also, as I understand, the original example was with some sub-request.

**Comment by Alex-302** [comment]
Original example - generic rule, which blocks redirects in clickunders/popups and removeing these parameters - `visitor_id`, `zoneid`:
`.icu/*?zoneid=*&visitor_id=$document,popup`
