### ISSUE TITLE
Replace Rule make some rule does not work

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1463]
@laulguo commented on [Thu Jun 10 2021](https://github.com/AdguardTeam/AdguardFilters/issues/85381)

***Description***:
* **Current behaviour**: 

[//]: # (Substitute this line with a description of the problem)
I previously used
*. *$subdocument,replace=/target="_blank"/target="_self"/
rule to modify the ATTRIBUTE attribute of all pages, but recently I found that loading such a rule will disable the filtering of many pages
The page visited is:http://www.xbiquge.la/15/15003/17163209.html
Time 11:52 minutes, used the rule:*. *$subdocument,replace=/target="_blank"/target="_self"/
 http://www.xbiquge.la/15/15003/17163209.html
recorded yesterday using the full log function that comes with ADGUARD
[//]: # (Replace %screenshot_url% below with a link to the screenshot of the problem. Also, you can paste image from clipboard instead. It will be automatically loaded.)
<details><summary>Screenshot:</summary>
![1](https://user-images.githubusercontent.com/38545281/121468057-c769da00-c9ec-11eb-88b6-5a45cb1c0909.png)
![2](https://user-images.githubusercontent.com/38545281/121468065-c9339d80-c9ec-11eb-9996-1222ab66d9a7.png)

These two diagrams reflect the difference between whether the filter are loaded or not 
Log are here
[adg_logs_7.6.3583.0_0515_1152.zip](https://github.com/AdguardTeam/AdguardFilters/files/6628490/adg_logs_7.6.3583.0_0515_1152.zip)

![3](https://user-images.githubusercontent.com/38545281/121467736-3561d180-c9ec-11eb-9665-50dcd33df342.png)

***System configuration***

**Filters:**

[//]: # (Substitute this line with the list of your active filters, separated by commas)

[//]: # (Please enter the correct values for your case to the table below)

Information                            | Value
---                                    | ---
Operating system:                      | Windows
Operating system version (Android/iOS) | Windows 10
Browser:                               | Firefox/Chrome
AdGuard version:                       | 7.6.1
Filters enabled:                       | Chinese+Base
AdGuard DNS:                           | None 
Stealth mode options (Windows only)    | No
Helpdesk ID (if exists):               | ?

**Comment by AdamWr** [comment]
I'm not sure if I understand correctly the problem, but for example, if I add rules like these:
```
example.org#%#(function() { var s = document.createElement('script'); s.setAttribute("type", "text/javascript"); s.src = 'https://code.jquery.com/jquery-3.6.0.js'; document.getElementsByTagName('head')[0].appendChild(s);})();
||code.jquery.com/jquery-3.6.0.js
||code.jquery.com/jquery-3.6.0.js$replace=/whatever_test_abc/test/
```
and then go to https://example.org/ then `$replace` rule is not applied, because there is no `whatever_test_abc` in this script and blocking rule is also not applied.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/121503826-b7003200-c9e1-11eb-8b92-21674135decb.png)

</details>

**Comment by laulguo** [comment]
In my case it's more like, because of the text replacement rule, the other rules can't be applied, but the attribute editing should be independent of the other filtering rules in my opinion

**Comment by laulguo** [comment]
using 
||http$subdocument,replace=/target="_blank"/target="_self"/
and
|http$subdocument,replace=/target="_blank"/target="_self"/
would get totally different filter applied

**Comment by laulguo** [comment]
> I'm not sure if I understand correctly the problem, but for example, if I add rules like these:
> 
> ```
> example.org#%#(function() { var s = document.createElement('script'); s.setAttribute("type", "text/javascript"); s.src = 'https://code.jquery.com/jquery-3.6.0.js'; document.getElementsByTagName('head')[0].appendChild(s);})();
> ||code.jquery.com/jquery-3.6.0.js
> ||code.jquery.com/jquery-3.6.0.js$replace=/whatever_test_abc/test/
> ```
> 
> and then go to https://example.org/ then `$replace` rule is not applied, because there is no `whatever_test_abc` in this script and blocking rule is also not applied.
> 
> Screenshot

Is there a way to lower the execution priority of text replace filter until after other filters are in effect?
