### ISSUE TITLE
A `$network` exception rule disables HTTPS filtering on some websites

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1466]
### Steps to reproduce

1. Enable `AdGuard Base` filter or add this rule to user filter:
```
@@1.1.1.1:443$network
```
2. Go here - [https://www.nfmovies.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.nfmovies.com%2F)
3. Check if there is AdGuard certificate on this website
<details><summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/29142494/121806632-f1bbd180-cc50-11eb-83f1-8484e21f3248.png)

![image](https://user-images.githubusercontent.com/29142494/121806650-fe402a00-cc50-11eb-9f32-c75a4c4e1073.png)

</details>

4. Disable this rule - `@@1.1.1.1:443$network`
5. Restart web browser
6. Go to [https://www.nfmovies.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.nfmovies.com%2F) and then check certificate
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/121806789-98a06d80-cc51-11eb-98ca-1deb73016ae2.png)

</details>

### Expected behavior

 `@@1.1.1.1:443$network` rule should not disable HTTPS filtering on `https://www.nfmovies.com/`

### Actual behavior

 `@@1.1.1.1:443$network` rule disables HTTPS filtering on `https://www.nfmovies.com/`

<details><summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/29142494/121806632-f1bbd180-cc50-11eb-83f1-8484e21f3248.png)

![image](https://user-images.githubusercontent.com/29142494/121806650-fe402a00-cc50-11eb-9f32-c75a4c4e1073.png)

</details>

### Your environment

* Chrome 91
* AdGuard for Windows 7.7 nightly 2 (build 3592, CL 1.7.227)

**Comment by sfionov** [comment]
This is expected behavior - $network whitelist rules are used for bypassing everything.

**Comment by ameshkov** [comment]
What `1.1.1.1` has to do with that website?

**Comment by sfionov** [comment]
Name:	www.nfmovies.com
Address: 1.1.1.1

**Comment by ameshkov** [comment]
Ehm, that's unexpected. How in the world does it work?

**Comment by AdamWr** [comment]
So what should be done in case of this issue - https://github.com/AdguardTeam/AdguardFilters/issues/84833#issue-910667338?
Should I just close it and tell users that it will be not fixed or just write a comment to disable specific rule or make this rule `@@1.1.1.1:443$network` MacOS/Safari specific?

https://github.com/AdguardTeam/CoreLibs/issues/598
https://github.com/AdguardTeam/AdguardFilters/commit/6f02fbad0896f72e5c49b7a726b57e1ca4b83eae

**Comment by ameshkov** [comment]
@AdamWr do we really need that $network rule? Can it be disabled?

**Comment by ameshkov** [comment]
@AdamWr as I recall, we needed that rule for some rather old version of AG for Mac and it should work okay now.

**Comment by AdamWr** [comment]
Okay, I have commented out these rules - https://github.com/AdguardTeam/AdguardFilters/commit/c56b35321724267e392280fa4b56bd41dbb03f36

**Comment by ameshkov** [comment]
@AdamWr I am 100% sure you can safely remove them, just checked it with AG for Mac.

**Comment by AdamWr** [comment]
Done - https://github.com/AdguardTeam/AdguardFilters/commit/773e82a42b531dc9670133ebbe069103824439f3
