### ISSUE TITLE
Improve XHR detection

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1469]
We could rely on `sec-fetch-dest: empty` to detect XHR at least in Chrome.

See the doc: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-Dest

> empty
> The destination is the empty string. This is used for destinations that do not have their own value. For exmaple fetch(), navigator.sendBeacon(), EventSource, XMLHttpRequest, WebSocket, etc.

So if we encounter `empty` and it's not a WebSocket, we can consider it XHR

**Comment by sxgunchenko** [comment]
Already done, along with https://github.com/AdguardTeam/CoreLibs/issues/1245
