### ISSUE TITLE
Content of requests with response code 302 cannot be filtered

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1471]
For example, there are no AdGuard injections(JS, CSS, element hiding rules) and `$replace`, `$$` rules are not working. 

This issue may be checked on rustorka.com after login(browser extension must be disabled)
![image](https://user-images.githubusercontent.com/8361299/124458660-ea8e6c00-dd95-11eb-87c2-c0d47ccbe6d8.png)

![image](https://user-images.githubusercontent.com/8361299/124459148-84eeaf80-dd96-11eb-860d-e61f1edda6cc.png)

**Comment by AdamWr** [comment]
Another example:
```
https://1shortlink.com/api/v1/full-pages?api_key=cab1700e53ac3a2e1584425a5aad8c3cf3b050aa&url=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xOEwzTmMyOXhocGY4MnpGTVZmVWRIc0hWOUU1WG10M3ovdmlldz91c3A9c2hhcmluZw==&type=2
```
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/147768566-5b2e4220-574a-4517-b7d3-71637f07b29f.png)

</details>

If I understand correctly, if response body contains "Location" header then AdGuard is not injecting scripts.
I think that it may be useful in some cases, so maybe it would be a good idea to change it.

**Comment by ameshkov** [comment]
@AdamWr but what's the case when it's useful? In theory, the browser just skips these pages

**Comment by AdamWr** [comment]
`1shortlink.com` is a url shortener which leads through third party websites to destination page.
If we could inject javascript rules to this link:
```
https://1shortlink.com/api/v1/full-pages?api_key=cab1700e53ac3a2e1584425a5aad8c3cf3b050aa&url=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xOEwzTmMyOXhocGY4MnpGTVZmVWRIc0hWOUU1WG10M3ovdmlldz91c3A9c2hhcmluZw==&type=2
```
then we could redirect to destination page directly, because destination page is encoded in Base64 here:
```
url=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xOEwzTmMyOXhocGY4MnpGTVZmVWRIc0hWOUU1WG10M3ovdmlldz91c3A9c2hhcmluZw==
```
That's why I think it could be useful.
