### ISSUE TITLE
oneprovider.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1474]
@adguard-bot commented on [Sat Jul 03 2021](https://github.com/AdguardTeam/AdguardFilters/issues/87446)

### Issue URL (Incorrect Blocking)
 [https://oneprovider.com/dedicated-servers/paris-france](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Foneprovider.com%2Fdedicated-servers%2Fparis-france)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/h9yffla.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/fro0lML.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.6.1
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Language-specific:</b><br/>AdGuard Chinese
Custom filters: | https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt,<br>https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js,<br>https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
Referrer: | [https://oneprovider.com/dedicated-servers-in-europe](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Foneprovider.com%2Fdedicated-servers-in-europe)

**Comment by AdamWr** [comment]
To reproduce this issue, please scroll website a bit and please disable this rule (from AdGuard Base):
`@@||oneprovider.com^$elemhide,jsinject,extension`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/124911530-240ce480-dfed-11eb-97ff-521dc6335d31.png)

</details>

**Comment by ameshkov** [comment]
Scripts are injected before `<!doctype`, looks strange.
