### ISSUE TITLE
Add global hiding rules and some webpages are abnormal

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/CoreLibs#1476]
@loyingEcu commented on [Thu Jul 08 2021](https://github.com/AdguardTeam/AdguardForWindows/issues/3846)

add rule ##.oasjd5g5g5g5g5sa4da54da6da(You can enter anything )
Visit https://dnf.qq.com/cp/a20210708pack/

Even if there is no such element on the website, it will cause the page to be abnormal 

Tried to add the following rules to no avail
@@||dnf.qq.com^$important
@@||dnf.qq.com^$jsinject
@@||dnf.qq.com^$elemhide

Unless the website is added to the https exclusion 

version : windows 7.7 nightly5

![error](https://user-images.githubusercontent.com/22834701/124908903-6bf73000-e01c-11eb-9d0f-561397116dc0.png)
![normal](https://user-images.githubusercontent.com/22834701/124909122-ab258100-e01c-11eb-85a3-8363094cb17a.png)

**Comment by ameshkov** [comment]
Caused by the website's script that relies on styles order: `var _style=document.getElementsByTagName("style")[0];`, not a bug:(

**Comment by ngorskikh** [comment]
>Unless the website is added to the https exclusion

An HTTPS exclusion is too extreme: `@@||dnf.qq.com^$elemhide,content,extension,jsinject` will prevent modification of the page source without sacrificing URL blocking.
