### ISSUE TITLE
ERR_HTTP2_PROTOCOL_ERROR after sending some forms [Android]

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1480]
I'm not sure if it's correct place to report it because it happens only on Android.

### Steps to reproduce
1. Use AdGuard for Android
2. Go to https://www.wilderssecurity.com/login/
3. Try to login, for example use `test` as a login and password and click on "log in" button

### Expected behavior
Website should reload and show that message - `Incorrect password. Please try again.`

### Actual behavior
Website stuck and show error `ERR_HTTP2_PROTOCOL_ERROR`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/126031105-2fcc3147-3cd6-40f1-a220-c3d85551b089.png)

</details>

### Your environment
* AdGuard for Android v4.0 nightly 17(58)

**Comment by sfionov** [comment]
Yes, we have a problem with login forms in 1.8 and already investigating this.

**Comment by AdamWr** [comment]
It seems that this issue has been fixed in the latest nightly (v4.0 nightly 18(59)) :)
