### ISSUE TITLE
Add modifier to change URL parameter / header value

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1486]
May be useful for disabling ads.
At the moment we have no too much examples.
Fresh sample:
https://boot.pluto.tv/v4/start?appName=web&appVersion=5.101.2-***&deviceVersion=92.0.4515&deviceModel=web&deviceMake=chrome&deviceType=web&clientID=***&clientModelNumber=1.0.0&channelSlug=wipeout&serverSideAds=true&clientTime=2021-07-28T12%3A53%3A22.886Z
`serverSideAds=true` => `serverSideAds=false`

**Comment by ameshkov** [comment]
@AdguardTeam/filters-maintainers please supply as many examples as possible.

**Comment by AdamWr** [comment]
Another example - `https://www.tangdoucdn.com/h5/play?vid=8709180`
Adding `&ad_switch=0` causes that ads are not displayed - `https://www.tangdoucdn.com/h5/play?vid=8709180&ad_switch=0`

**Comment by ameshkov** [comment]
@Alex-302 @AdguardTeam/filters-maintainers 

Duplicates #1364 and #131 

Please upvote those if you think we should implement them faster. Also, more examples would be useful.
