### ISSUE TITLE
Youtube HomePage Ads shows repeatedly with AdGuard 2.5.5.993

### ISSUE THREAD

**Issue by owenzhao** [AdguardTeam/CoreLibs#1487]
### Steps to reproduce

1. Rest AdGuard Statics and Settings
2. Flow the guide assistant.
3. AdGuard works.
4. After some time, maybe Mac sleep or something I don't know, AdGuard no longer working. 

### Expected behavior

Youtube Ads should be removed.

### Actual behavior

Youtube ads shows.

<details><summary>Screenshot:</summary>
<img width="1436" alt="Screen Shot 2021-07-28 at 8 58 15 AM" src="https://user-images.githubusercontent.com/2182896/127246652-73dd6165-d95c-4812-b448-2f049ec554b8.png">

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59):
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)
macOS Big Sur 11.5.1 (20G80)
Safari 14.1.2 (16611.3.10.1.3)
AdGuard 2.5.5.993 nightly (CL-1.8.138, DNS-1.6.14)
ClashX 1.65.0 With Trojan

**Comment by ameshkov** [comment]
To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Menu -> Advanced -> Logging level -> Debug
2. Reproduce the issue (and remember the exact time when it happened).
3. Menu -> Advanced -> Export Logs and System Info...
4. Send the archive to `devteam@adguard.com` and mention this issue number in the subject

**Comment by owenzhao** [comment]
> To troubleshoot this issue, we need to get the app logs.
> 
> Here's what we need you to do:
> 
> 1. Menu -> Advanced -> Logging level -> Debug
> 2. Reproduce the issue (and remember the exact time when it happened).
> 3. Menu -> Advanced -> Export Logs and System Info...
> 4. Send the archive to `devteam@adguard.com` and mention this issue number in the subject

Sent！

**Comment by Chinaski1** [comment]
@owenzhao 

The Nightly 999 was just released, please update and check if the issue still persists.

**Comment by owenzhao** [comment]
> @owenzhao
> 
> The Nightly 999 was just released, please update and check if the issue still persists.

The update works so far.

**Comment by owenzhao** [comment]
> @owenzhao
> 
> The Nightly 999 was just released, please update and check if the issue still persists.

The issue appeared again this morning at 6:21 A.M. GMT+8. Sent you the new log by the email.

<img width="1323" alt="Screen Shot 2021-07-31 at 6 21 15 AM" src="https://user-images.githubusercontent.com/2182896/127717620-1e46c799-ae02-4e88-864a-2c700487a198.png">

**Comment by owenzhao** [comment]
I noticed that this time those issues happened less frequently. And they would disappear after some minutes. For example, when the Mac awake from sleep. The issue likely happened. Then after some minutes, the issue disappeared.

It looked like that AdGuard restarted itself and fixed the issue. However, that was my theory. I didn't know what really happened.

**Comment by sfionov** [comment]
@owenzhao I've just noticed that you use Big Sur 11.5.1. Was there the problem before this release? I think that Apple may have changed way of handling old connections after the protection start. We'll check this.

**Comment by owenzhao** [comment]
> @owenzhao I've just noticed that you use Big Sur 11.5.1. Was there the problem before this release? I think that Apple may have changed way of handling old connections after the protection start. We'll check this.

This issue was first introduced by AdGuard 2.5.5.993 with macOS 10.15. Before that, I didn't find the issue.

**Comment by ameshkov** [comment]
@owenzhao 

> This issue was first introduced by AdGuard 2.5.5.993 with macOS 10.15. Before that, I didn't find the issue.

Did you already have Big Sur 11.5.1 (that version of Big Sur specifically) at the time when you upgraded to the latest nightly?

> ClashX 1.65.0 With Trojan

Could you please tell me more about your ClashX setup? How exactly the traffic is being routed?

@sfionov could it be that we have special rules for localhost?

**Comment by planet0** [comment]
Just adding in that I've having the exact same issue in AdGuard for Windows as well: https://github.com/AdguardTeam/AdguardForWindows/issues/3880

**Comment by ameshkov** [comment]
@planet0 do you still have it? It should've been gone since a day or two ago

**Comment by planet0** [comment]
@ameshkov I haven't noticed any issues today, however I was not on the device for long.

I will be heavily using the device tomorrow and will be able to properly test and monitor if any issues occur.

Will report back within 24 hours on here.

**Comment by owenzhao** [comment]
> @owenzhao
> 
> > This issue was first introduced by AdGuard 2.5.5.993 with macOS 10.15. Before that, I didn't find the issue.
> 
> Did you already have Big Sur 11.5.1 (that version of Big Sur specifically) at the time when you upgraded to the latest nightly?
> 
> > ClashX 1.65.0 With Trojan
> 
> Could you please tell me more about your ClashX setup? How exactly the traffic is being routed?
> 
> @sfionov could it be that we have special rules for localhost?

Clash is set in Ruled mode. 

<img width="780" alt="Screen Shot 2021-08-06 at 8 54 38 AM" src="https://user-images.githubusercontent.com/2182896/128439648-f016a878-5289-4c9e-bb6c-824f846ad95f.png">

Besides, I could use AdGuard extension in Safari to block the ad element myself. For example, below is one rule that I exported from AdGuard.

> youtube.com###contents > ytd-rich-item-renderer.style-scope.ytd-rich-grid-renderer:first-child

**Comment by owenzhao** [comment]
I'd love to talk more about the customized rule, as the behavior of AdGuard/Safari was odd.

> youtube.com###contents > ytd-rich-item-renderer.style-scope.ytd-rich-grid-renderer:first-child

## The rule was generated semi-automatically by AdGuard Safari Extension when ads was shown.
1. Click AdGuard icon on Safari
2. Choose `Block an element`.
3. Click on the Ads
4. Drag the slider to the most fit.
5. Click block.

The rule could be found in AdGuard -> Preferences -> User rules.

### I said the behavior of the rule is odd because
1. After applying the rule, youtube ads was removed once. However, if I refresh youtube homepage, the ads may or may not be shown. Just like without the rule.
2. When ads were shown again. I could use AdGaurd Safari Extension to block the ads again. That should generate another rule. There wasn't. The ads was blocked but the rule was still one.

So I could assumed that,
1. Maybe Safari didn't run AdGuard properly.
2. Maybe AdGuard didn't run its rules properly.
3. Maybe AdGuard couldn't create enough rule for YouTube. The second rule override the first when it should not override.

I didn't have enough knowledge to make known which is the right reason. But I could be sure that youtube's ads could be recognized by AdGuard. The issue is not on the content change of youtube.

**Comment by planet0** [comment]
@ameshkov Just reporting back with using my device, I haven't been able to experience it again all day today.
