### ISSUE TITLE
HTTPS filtering doesn't work on dha.com.tr on Android

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#149]
### Steps to reproduce

1. Add `dha.com.tr##body`
2. Go here - https://www.dha.com.tr/
3. Website should be blank

<details><summary>Screenshots:</summary>

![screenshot_2017-12-15-15-16-18](https://user-images.githubusercontent.com/29142494/34048456-0b22f666-e1b4-11e7-8ce5-5f520e345b1f.png)
![screenshot_2017-12-15-15-16-24](https://user-images.githubusercontent.com/29142494/34048457-0b41d52c-e1b4-11e7-9e4c-5ace51c71c56.png)

</details>

### Your environment

* Adguard version: 2.10.176
* Adguard filtering mode: VPN
* Device model: LG G3
* Operating system and version: Android 6.0
* Rooted or not? Not
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? -

https://github.com/AdguardTeam/AdguardFilters/issues/8292

**Comment by ameshkov** [comment]
Confirmed that there is no issue with the CoreLibs integrated Android build
