### ISSUE TITLE
Allow to apply $removeparam rules to all resources

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1492]
https://github.com/AdguardTeam/tsurlfilter/issues/16
+ another sample
https://github.com/AdguardTeam/AdguardFilters/commit/d24a901d834baa629523f5ab4815d7a517e3b630

**Comment by ameshkov** [comment]
@sfionov moved it to 1.8. Please note that the documentation needs to be updated accordingly.

Re-posting from the tsurlfilter repo:

> I suppose we should only allow it to target other content types if the rule has an explicit content-type modifier.

> By default it should only target documents.
