### ISSUE TITLE
Add SOCKS4 support for outbound proxy

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1493]
Please see this original message:
https://t.me/adguard_en/138147

It appears that in Iran AdGuard's outbound proxy functionality is often used for accessing proxies and there're users from there that badly need SOCKS4 and not just SOCKS5. In theory, it shouldn't be a problem to add it so why not?

**Comment by ngorskikh** [comment]
```
    OPROXY_MODE_SOCKS4,
```
🤔

**Comment by logicianmik** [comment]
Please Add Socks5 To local proxy Mode
and Import .TXT Proxies to Network Setting Option
