### ISSUE TITLE
WeTransfer freezes on macOS

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/CoreLibs#1494]
WeTransfer freezes on macOS 11.5.1 (Safari 14.1.2) when I try to upload a file. It's working fine with AdGuard for Mac (2.5.3) disabled and it's working fine on iOS.
AdGuard Social Media filter is causing the issue.

**Comment by ameshkov** [comment]
wetransfer.com -- this one, right?

Do we need to sign up there?
Does it depend on the file size?

What's exact AdGuard version?

**Comment by ameshkov** [comment]
@Chinaski1 that's probably about nighly

**Comment by Chinaski1** [comment]
Still not reproduced on the latest Nightly

**Comment by iDjay** [comment]
> wetransfer.com -- this one, right? **Yes**
> 
> Do we need to sign up there? **No**
> Does it depend on the file size? **No**
> 
> What's exact AdGuard version? **2.5.3.955 release (CL-1.7.200)**



> I have now tried to upload 1GB and have not encountered any issues.
> AdGuard Social Media filter is ON.
> Application version 2.5.3.955 release

My mistake, it's not the social media filter, I'm still trying to figure out what exactly causes the issue.

**Comment by iDjay** [comment]
> I have now tried to upload 1GB and have not encountered any issues.
> AdGuard Social Media filter is ON.
> Application version 2.5.3.955 release

It's the annoyance filter (sorry for the confusion):
https://we.tl/t-f1p0s3zaO7

**Comment by AdamWr** [comment]
It looks like a filters issue.
Could you please update filters and then check if issue still occurs?

**Comment by Chinaski1** [comment]
@iDjay 
Any updates?

**Comment by iDjay** [comment]
yes, working :)
