### ISSUE TITLE
wiki.cemu.info

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1497]
@adguard-bot commented on [Thu Aug 12 2021](https://github.com/AdguardTeam/AdguardFilters/issues/90759)

### Issue URL (Incorrect Blocking)
 [https://wiki.cemu.info/wiki/Main_Page](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwiki.cemu.info%2Fwiki%2FMain_Page)
### Comment
> When AdGuard protection is enabled, all that is rendered is a blank page. Chrome's Dev Console show an "GET https://wiki.cemu.info/wiki/Main_Page net::ERR_HTTP2_PROTOCOL_ERROR 200" when that happens. Pausing/Disabling AdGuard fixes the issue, it doesn't seem related to any particular filter or user extension...

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/0ZKtw2X.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/v6OglA0.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.6.1
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode: | disabled
DNS filtering: | server: `quic://dns-unfiltered.adguard.com`<br>filters: `User rules`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking<br/><br/><b>Annoyances:</b><br/>Adblock Warning Removal List, <br/>I don't care about cookies, <br/>AdGuard Annoyances<br/><br/><b>Other:</b><br/>Filter unblocking search ads and self-promotion, <br/>AdGuard Experimental<br/><br/><b>Language-specific:</b><br/>AdGuard Spanish/Portuguese
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js,<br>https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js

**Comment by AdamWr** [comment]
The same happens with latest nightly build (Version 7.7 nightly 11 (build 3631, CL 1.8.151))

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/129158917-cb6324ac-b9d2-4ddc-9976-fb03ed4cbb7b.png)

</details>

**Comment by ngorskikh** [comment]
The site is broken: the `content-length` response header value is equal to the uncompressed response body length instead of the actual amount of data sent. It seems that Chrome and Firefox have a workaround for this, while, for example, Safari and Curl do not, and will not fetch this page. I strongly lean towards also not adding a workaround, since it clearly violates the standard: https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2.6 I would rather report the issue to the site owners, however they don't have a feedback button...

**Comment by sfionov** [comment]
@AdamWr Since it is too hard to workaround HTTP/2 protocol implementation errors, adding `@@||wiki.cemu.info^$document` is good solution IMHO

**Comment by ngorskikh** [comment]
`@@||wiki.cemu.info^$document` won't work, unfortunately: the issue is at the HTTP/2 proxy level.

**Comment by ameshkov** [comment]
HTTPS exclusion only.

**Comment by ameshkov** [comment]
And yet I agree that we shouldn't change anything here.
