### ISSUE TITLE
[Android] Connection reset by local client on Android 9

### ISSUE THREAD

**Issue by admitrevskiy** [AdguardTeam/CoreLibs#1499]
Related issue is: https://github.com/AdguardTeam/AdguardForAndroid/issues/3888

These apps are partly broken on Android 9: if filtering is enabled (even without HTTPS filtering and filters) local client starts to reset specific connections. Message in the log: `connection reset by local client`

I've decompiled both apps and they use retrofit2 as HTTP client and it looks like there is no specific version-dependent logic inside the application or library itself.

**Comment by ngorskikh** [comment]
Both apps break in the same way with AdGuard VPN. I'm willing to bet they'll break with any other VPN as well.
