### ISSUE TITLE
Add the $csp modifier support

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#15]
##### **`csp`**

This modifier completely changes the rule behavior. If it is applied to a rule, it will not block the matching request. The response headers are going to be modified instead.

> In order to use this type of rules, it is required to have the basic understanding of the [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) security layer.

For the requests matching a `$csp` rule, we will strengthen response's security policy by adding additional content security policy equal to the `$csp` modifier contents. `$csp` rules are applied independently from any other rule type. Other basic rules have no influence on it **save for document-level exceptions** (see the examples section).

>Multiple rules matching a single request.
>In case if multiple `$csp` rules match a single request, we will apply each of them.

**$csp syntax**

`$csp` value syntax is similar to the Content Security Policy header syntax.

`$csp` value can be empty in the case of exception rules. See examples section for further information.

> Limitations

> 1. Please note, that there're a few characters forbidden in the `$csp` value: (`,`), (`$`)
> 2. `$csp` rules support a limited set of modifiers: `domain`, `important`, `subdocument`
> 3. Rules with `report-*` directives are considered invalid.

###### `$csp` examples

* `||example.org^$csp=frame-src 'none'` — prohibits all frames on example.org and it's subdomains.
* `@@||example.org/page/*$csp=frame-src 'none'` — disables all rules with the `$csp` modifier exactly matching `frame-src 'none'` on all the pages matching the rule pattern. For instance, the rule above.
* `@@||example.org/page/*$csp` — disables all the `$csp` rules on all the pages matching the rule pattern.
* `||example.org^$csp=script-src 'self' 'unsafe-eval' http: https:` — disables inline scripts on all the pages matching the rule pattern.
* `@@||example.org^$document` or `@@||example.org^$urlblock` — disables all the `$csp` rules on all the pages matching the rule pattern.

**Comment by hmage** [comment]
In code review. Implemented in commit 2a1a3b6c5c43ab8244535f278b8e27466078a727

**Comment by hmage** [comment]
Merged in a084b41fb25643ce394091a9b35fc56f4ad5a7e6.

**Comment by sfionov** [comment]
Currently not used in proxy code

**Comment by sfionov** [comment]
also, buildcsp() should return char **, not char *. So every rule goes into separate CSP header. This also helps to reject invalid CSP headers if AGCSPValue class can't parse it.

**Comment by szolin** [comment]
/core/pull-requests/840

**Comment by ameshkov** [comment]
We'll need @timirila1 help to sort out the unsafe-inline issue here.

**Comment by sfionov** [comment]
core/pull-requests/934
