### ISSUE TITLE
www.theluckygene.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1500]
@adguard-bot commented on [Wed Aug 18 2021](https://github.com/AdguardTeam/AdguardFilters/issues/91466)

### Issue URL (Incorrect Blocking)
 [https://www.theluckygene.com/Error?Ads=blocked](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.theluckygene.com%2FError%3FAds%3Dblocked)
### Comment
Username: @TesterMan247
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/r2ispEe.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/r2ispEe.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.7 nightly 12
Browser: | Firefox
AdGuard driver: | WFP
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/>NoCoin Filter List<br/><br/><b>Other:</b><br/>AdGuard Experimental
Userscripts: | https://userscripts.adtidy.org/beta/assistant/4.3/assistant.user.js,<br>https://userscripts.adtidy.org/beta/adguard-extra/1.0/adguard-extra.user.js,<br>https://userscripts.adtidy.org/beta/popup-blocker/2.5/popupblocker.user.js
Referrer: | [https://www.lotterynumbergenerator.net/wednesdaylotto-number-generator](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.lotterynumbergenerator.net%2Fwednesdaylotto-number-generator)

**Comment by AdamWr** [comment]
It seems that there is no AdGuard certificate on this website, so javascript/element hiding rules do not work.

**Comment by sxgunchenko** [comment]
Cannot be MITMed due to CoreLibs limitations. Added to HTTPS exclusions https://github.com/AdguardTeam/HttpsExclusions/pull/435
