### ISSUE TITLE
Incorrect work with userscript Handy Image

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/CoreLibs#1501]
При клике по превью или ссылке, минуя страницу просмотра, должно сразу открываться оригинальное изображение. 
Вместо этого в некоторых случаях приходится специально выделять ссылку в адресной строке Chrome и нажимать Enter.

Handy Image: https://github.com/Owyn/HandyImage
https://sleazyfork.org/ru/scripts/109-handy-image/code
https://greasyfork.org/ru/scripts/109-handy-image/code

Ссылки для теста:
https://imgbb.com/zbxvmVv
https://servimg.com/view/17653514/86
https://fastpic.org/view/115/2021/0817/8418cbb57d69deda882c4769854e4c14.jpg.html

<details><summary>Screenshot:</summary>

![2](https://user-images.githubusercontent.com/50718960/130191250-5bac555f-5e14-419b-9005-47e915a7a406.png)
![1](https://user-images.githubusercontent.com/50718960/130191234-dbd36408-632a-43e6-8c52-9f7bda14ce9e.png)
</details><br/>

**Comment by Chinaski1** [comment]
@zubrRB 

Попробовал воспроизвести указанную ситуацию на AdGuard for macOS 2.5.3.955 release (CL-1.7.200) и AdGuard for Windows 7.7 nightly 14 (build 3643, CL 1.8.158), но не встретил описанных проблем.
При переходе по ссылкам сразу же открывается изображение без страниц просмотра.
Уточните, пожалуйста, какую версию AdGuard вы используете?

**Comment by zubrRB** [comment]
AdGuard 7.7 nightly 14, но началось это гораздо раньше, А каким способом вы открывали ссылки? 
У меня через "копировать адрес ссылки" > "вставить и перейти на страницу" тоже всё сразу срабатывает. 
А через  открытие ссылки в новом окне/вкладке или с переходом кликом с этой страницы, то не работает. 
Для чистоты эксперимента отключил все расширения в браузере и сторонние юзерскрипты в AdGuard, но это не исправило ситуацию. Которая одинаково повторяется на актуальных версиях Chrome и Firefox. 
Применяемые настройки AdGuard: https://github.com/AdguardTeam/AdguardFilters/issues/92131

**Comment by zubrRB** [comment]
Работу юзерскрипта ломает опция антитрекинга "_Скрыть Referrer от сторонних ресурсов_".

**Comment by Chinaski1** [comment]
Вполне допустимо, что некоторые настройки из раздела Антитрекинг могут конфликтовать с расширениями сторонних разработчиков.
Вряд ли мы можем это исправить на стороне приложения.

**Comment by ngorskikh** [comment]
To "hide" the referrer we either substitute a custom referrer (if specified) or make the referrer the target page itself.

The userscript in question has a specific feature to automatically disable itself when the referrer is the current page itself.

To work around this, you can either specify a custom referrer in adguard settings, or patch the script to remove this feature.

**Comment by zubrRB** [comment]
@Owyn please, look conflict in Adguard due to the hide referrer.

**Comment by Owyn** [comment]
@zubrRB **It's intended** that the script doesn't work when previous page is website's main page, else it'd become impossible to upload pictures.

> To work around this, you can either specify a custom referrer in AdGuard settings, or patch the script to remove this feature.

**Comment by zubrRB** [comment]
@Owyn This can not be implemented at the level of your script? Otherwise, in Adguard, this setting will act globally for all sites.

**Comment by Owyn** [comment]
@zubrRB  what can not be implemented? - there is nothing to implement.

Just use custom referrer which is not the website's main page (but current page for example), or just set it up so referrer is only sent for same-website, else you're just breaking sites for yourself on purpose, don't expect any other results...

**Comment by zubrRB** [comment]
@Chinaski1 закавыка в том, что это один из самых популярных UserJS, поддерживающий c тысячу мировых фотохостингов.

**Comment by Chinaski1** [comment]
I close this task because
> To work around this, you can either specify a custom referrer in AdGuard settings or patch the script to remove this feature.

**Comment by zubrRB** [comment]
Собственный referrer будет распространяться на все ресурсы в сети, а не избирательно на один конкретный срипт.
Было бы хорошо по аналогии с пользовательским фильтром, где можно задавать исключения для сайтов, задать для UserJS.

Тут ещё нарисовалась проблема с центрированием изображений при их изначальном открытии.  https://github.com/Owyn/HandyImage/issues/447

<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/50718960/131259407-0b758368-7d78-4b92-b9b7-9622bc371353.png)
</details><br/>

Центрируются они только при лишнем дополнительном клике по фото. В Tampermonkey  этой проблем нет.
<details><summary>Screenshot:</summary>

![2](https://user-images.githubusercontent.com/50718960/131259410-228a222c-ee03-492b-9929-8f29a46d3b2b.png)
![3](https://user-images.githubusercontent.com/50718960/131259413-33cdd11c-ec75-4d17-ab8d-f616990ea2fe.png)
</details><br/>

**Comment by sfionov** [comment]
@zubrRB To disable userscripts for particular website you may use a rule like `@@||example.org^$extension`

**Comment by zubrRB** [comment]
@sfionov а как от обратного... При отсутствии собственного referrer задать его только для данного конкретного скрипта?

**Comment by sfionov** [comment]
Такой возможности нет, функция hide referrer имеет только одну настройку.

Можно попробовать отключить стелсмод для данного сайта с помощь $stealth-правила.

**Comment by zubrRB** [comment]
Это скрипт предназначен для фотохостингов, которых там под тысячу прописано. И чтобы нормально пользоваться им мне нужно прописать в настройках программы собственный referrer, который распространится на абсолютно все сайты в сети.
Легче как-то задать исключение для одного скрипта с тысячей сайтов, чем задать общее правило для миллиардов сайтов.
