### ISSUE TITLE
Kinopoisk.ru authorisation breakage

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/CoreLibs#1502]
If the setting `Self-destruction of third-party cookies(0)` is enabled in desktop apps, then authorization at Kinopoisk does not work (this rule helps `@@||sso.kinopoisk.ru/install?uuid=$stealth,domain=sso.passport.yandex.ru`).

But if you turn on the same in the extension or <a href="https://ibb.co/Nmmg2VQ">similar setting</a> in the browser itself, then authorization does not break.

**Comment by zubrRB** [comment]
У меня при заходе на Kinopoisk и клике на трейлер этот домен в адресной строке Chrome сам появляется и исчезает...

**Comment by zubrRB** [comment]
В такой последовательности у меня автоматически меняются в адресной строке ссылки при запуске трейлера на Kinopoisk: 

```
https://www.kinopoisk.ru/film/929348/

https://sso.passport.yandex.ru/push?retpath=https%3A%2F%2Fwww.kinopoisk.ru%2Fapi%2Fprofile-pending%2F%3Fretpath%3Dhttps%253A%252F%252Fwww.kinopoisk.ru%252Ffilm%252F929348%252F&uuid=320c3b80-48b3-478d-aef5-3083d1133439

https://sso.kinopoisk.ru/install?uuid=ddce3c14-e536-4b6b-9742-3ab441cde9c2

https://www.kinopoisk.ru/film/929348/
```

**Comment by sxgunchenko** [comment]
It seems like we should detect the navigation requests (i.e., ones that have `Sec-Fetch-Mode: navigate` + `Sec-Fetch-Dest: document`) and do not apply the third-party cookies blocking feature to them.
In case a request does not have those headers, the current algorithm should be applied (https://github.com/AdguardTeam/CoreLibs/issues/1401)

**Comment by deartvonrud** [comment]
The user sent a video which may be interesting in case one wants to reproduce the issue: **https://drive.google.com/file/d/1TMJP3KhoFeGPLp3F0A66TSZeB_E_4iuo/view?usp=sharing**
