### ISSUE TITLE
Change $stealth rule semantics

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1504]
@ameshkov commented on [Mon Aug 23 2021](https://github.com/AdguardTeam/tsurlfilter/issues/31)

Currently, `$stealth` rule disables Stealth Mode not just for the website, but also for every request sent from that website, making it work kinda like `$document` modifier.

I.e. `@@||example.org^$stealth` will disable Stealth Mode features for all requests sent **from** example.org. I did a quick search among AG filters and honestly, I don't see any real use for that. Let's simplify this and make `$stealth` only work for requests which URL matches the pattern.

**Comment by sfionov** [comment]
@sxgunchenko 

Let's also add flags for particular steathmode features.

We need some spec with short names of stealth mode features.

**Comment by sxgunchenko** [comment]
CoreLibs already matches `$stealth` rules only against the target domain and doesn't match against the referrer
