### ISSUE TITLE
AG blocks FF Raindrop.io

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/CoreLibs#1506]
When AG macOS is activated it prevents FF Raindrop.io extension to login. 

I added in the whitelist but unfortunately it did not help.

**Comment by Chinaski1** [comment]
@Quorum75 

Hello there!
You should try adding the specified domain to the [HTTPS exclusions](https://uploads.adguard.com/Chinaski6nf3m.png) list

**Comment by Quorum75** [comment]
> @Quorum75 
> 
> 
> 
> Hello there!
> 
> You should try adding the specified domain to the [HTTPS exclusions](https://uploads.adguard.com/Chinaski6nf3m.png) list

I added it to the whitelist but it didn't help. Will try your recommendation and will let you know. Cheers

**Comment by Quorum75** [comment]
> @Quorum75 
> 
> 
> 
> Hello there!
> 
> You should try adding the specified domain to the [HTTPS exclusions](https://uploads.adguard.com/Chinaski6nf3m.png) list

Itb didn't work either.

**Comment by Chinaski1** [comment]
Still not reproducing.

Can you open Dev Tools (F12) (Network&Console tab) -> try logging in to the website -> send screenshots of the two tabs from the console?

**Comment by Quorum75** [comment]
> Still not reproducing.
> 
> 
> 
> Can you open Dev Tools (F12) (Network&Console tab) -> try logging in to the website -> send screenshots of the two tabs from the console?
> 
> 

Are you sure we are doing the same thing?

**Comment by Chinaski1** [comment]
@Quorum75 

I checked with AdGuard disabled and the extension behaves itself as well.
When you go to Sign in a new window opens.
After login, you can open the settings from bookmarks.
[Here is the video](https://uploads.adguard.com/Chinaskidok31.mov).

**Comment by Quorum75** [comment]
Yes exactly that's the way it supposes to work.
But on my side it always opens a new tab each time I click on the extension. 

So what I understand, it's not coming from AG but it is more related to my own configuration...

**Comment by Quorum75** [comment]
@Chinaski1 I finally found the problem. Windscribe FF is responsible of the problem. It also causes a PR_END_OF_FILE_ERROR connection issue. Thanks.
