### ISSUE TITLE
slivy.news

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/CoreLibs#1508]
@adguard-bot commented on [Thu Aug 19 2021](https://github.com/AdguardTeam/AdguardFilters/issues/91590)

### Issue URL (Annoyance)
 [https://slivy.news/bank-belveb-sinekura-dlya-predatelej/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fslivy.news%2Fbank-belveb-sinekura-dlya-predatelej%2F)
### Comment
Username: @zubrRB
> Telegram

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/sNZ3b6x.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.7 nightly 13
Browser: | Chrome
AdGuard driver: | TDI
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (1), <br>Disable cache for third-party requests, <br>Block WebRTC, <br>Block Push API, <br>Block Location API, <br>Block Flash, <br>Hide your Referrer from third-parties (slivy.news), <br>Hide your User-Agent (), <br>Hide your IP address ()
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>AdGuard URL Tracking<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js,<br>https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js,<br>https://github.com/Owyn/HandyImage/raw/master/HandyImage.user.js,<br>https://greasyfork.org/scripts/14085-kinozal-tv-magnet-links/code/kinozaltv magnet links.user.js,<br>https://greasyfork.org/scripts/394820-mouseover-popup-image-viewer/code/Mouseover%20Popup%20Image%20Viewer.user.js,<br>https://download.sf-helper.com/chrome/helper.user.js,<br>https://userscripts.adtidy.org/release/adguard-wot/1.0/wot.user.js
Referrer: | [https://slivy.news/page/2/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fslivy.news%2Fpage%2F2%2F)

---

@zubrRB commented on [Wed Aug 25 2021](https://github.com/AdguardTeam/AdguardFilters/issues/91590#issuecomment-905384642)

Правило пришло, но подписка эта осталась.

---

@zubrRB commented on [Wed Aug 25 2021](https://github.com/AdguardTeam/AdguardFilters/issues/91590#issuecomment-905392276)

Это из-за ошибки фильтрации данного сайта. 

![cert](https://user-images.githubusercontent.com/50718960/130778085-1096b155-7b06-4e4a-a854-685565437b1f.png)

---

@zloyden commented on [Wed Aug 25 2021](https://github.com/AdguardTeam/AdguardFilters/issues/91590#issuecomment-905399370)

Да, что-то с сертификатом. Перенесу в другой репозиторий.

**Comment by zubrRB** [comment]
У двух ресурсов практически идентичные сертификаты, но только у первого проблема с фильтрацией.

![cert](https://user-images.githubusercontent.com/50718960/130780902-c1fabcd8-e960-465e-bd3d-e2df80e24f8d.png)

**Comment by zubrRB** [comment]
В 7.9 nightly 2 были исправили, но в 7.9 nightly 3, видимо, произошёл откат исправлений и поэтому вновь не фильтрует.
