### ISSUE TITLE
Requests with applied $removeparam rules has wrong background color in the filtering log

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1514]
### Steps to reproduce
1. Open filtering log
2. Visit `https://example.org/?test=123`
3. Add `||example.org^$removeparam=test`
4. Refresh the tab.

### Expected behavior
Background color is yellow, like with Stealt Mode or modified requests.

### Actual behavior
Background color is red, as for blocked requests.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/120307239-6a2ea400-c2db-11eb-9c8a-9fb7497ba63d.png)

</details>

### Your environment
AdGuard 7.6 n41

**Comment by sfionov** [comment]
Already fixed in CoreLibs 1.8.
