### ISSUE TITLE
Provide an option to block request when it's opened in the main frame

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#152]
Details:
https://github.com/AdguardTeam/AdguardForWindows/issues/2043

Basically, we need to provide a "strict" level of blocking. When the strict level is enabled, we should block requests even when they're executed in the main browser frame.

Also, we'd better provide a modifier for blocking rules that will allow overriding the default behavior:
https://github.com/AdguardTeam/AdguardForWindows/issues/2084#issuecomment-361669514

The easiest way would be to allow `$document` modifier in the blacklist rules.

Also, add `$all` modifier:
https://github.com/gorhill/ublock/wiki/Static-filter-syntax#all

**Comment by FadeMind** [comment]
@ameshkov thanks for approving my idea. Regards

**Comment by ameshkov** [comment]
@FadeMind it makes perfect sense, thank you! Also, it's quite often when people ask us how to block this or that completely, and using `$empty` is not an ideal solution

**Comment by vshlobinag** [comment]
core/pull-requests/1482

**Comment by ameshkov** [comment]
There are some issues with the current implementation.

`||exoclick.com^$document` for some reason is applied instead of `||syndication.exoclick.com/splash.php?$empty,important,domain=dashishipin.com`:
![image](https://user-images.githubusercontent.com/5947035/66908889-843b4600-f014-11e9-84da-e312d00eaf34.png)

The second issue is that a $document rule is applied to a non-DOCUMENT response.

And finally, the third issue is that the `$all` rule, in this case, won't block non-document requests while it actually should.

**Comment by sxgunchenko** [comment]
core/pull-requests/1564

**Comment by AdamWr** [comment]
Regarding this issue - https://github.com/AdguardTeam/CoreLibs/issues/152#issuecomment-542626310

It seems that it happens again.

Steps to reproduce:
1. Add this rule:
`||cda-tv.online^$document`
2. Go here -  [https://cda-tv.online/filmy-online/malgosia-i-jas/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://cda-tv.online/filmy-online/malgosia-i-jas/) and click on "Proceed anyway" button
3. Click on one of the video players (marked on screenshot below).
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/82811082-3a5eec00-9e90-11ea-827d-3427a172229b.png)

</details>

Request marked as `Other` type is blocked.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/82811044-261aef00-9e90-11ea-856a-0ae3fdc856e2.png)

</details>

**Comment by sxgunchenko** [comment]
It's not a regression since the actual request type detected by the filtering engine is xhr+document.
But there is an issue with the content type displaying which resides in the UI.

**Comment by AdamWr** [comment]
Ok, thank you for your answer.
Anyway, I'm wondering why `$document` must be applied in case like that?
Is there any real case where is needed to apply rule with `$document` modifier to request which is detected as xhr+document?

**Comment by adbuker** [comment]
@AdamWr, as for Adg4Win we'll improve content-type displaying soon - the corresponding task has been created
