### ISSUE TITLE
Add ability to `Hide AppVersion`

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/CoreLibs#1521]
Опция "Скрыть User-Agent" не работает при значении по умолчанию. При вписывании стороннего — подмена работает. 
Дополнительно на специализированных ресурсах параметр `appVersion` выдаёт реальный `userAgent` даже если он скрыт.
Обе проблемы воспроизводятся в AdGuard для Windows и macOS. https://browserleaks.com/javascript | https://whoer.net

**Comment by Chinaski1** [comment]
Оставляя поле пустым, вы используете User-Agent по умолчанию.
Поэтому информация не скрывается.

**Comment by zubrRB** [comment]
Но вот люди на ру-борде понимают подпись для данной опции иначе, как в случае с сокрытием IP, где есть вшитый адрес.

**Comment by zubrRB** [comment]
А что по второму пункту?

![-](https://user-images.githubusercontent.com/50718960/134939938-c0363462-bc84-401a-bec4-3509c331b3e8.png)

**Comment by Chinaski1** [comment]
Добавим указанную возможность в ближайших обновлениях.

**Comment by zubrRB** [comment]
А по `appVersion` (на скриншоте), выдающим реальный UA, даже если тот в строке `userAgent` подменяется на подставной?
