### ISSUE TITLE
AdGuard slows down WebPage loading time

### ISSUE THREAD

**Issue by manirhossen** [AdguardTeam/CoreLibs#1522]
Adguard Slow Down WebPage loading time. Webpage take long time to load With Adguard Windows Program. But without Adguard Page load Faster. But in Adguard Advertisement it shows With Adguard Page load more faster than Regular Page loading time. But In real time It's not true. Please Adguard Team Solve this problem.
I hope Adguard team can do it.

Note: With use other Program Like Ghostery . Page load super fast. I love Adguard but it load page Very slow. Please Adguard Team Solve this problem In next update.

For More Information please See My Report Post in this Link.

https://github.com/AdguardTeam/AdguardFilters/issues/91731#issuecomment-913569235

Username: manirhossen

![image](https://user-images.githubusercontent.com/56219261/132210446-b32ebbe8-485a-4c4a-8db9-853569463d5c.png)
![image](https://user-images.githubusercontent.com/56219261/132210488-9a083afa-30b7-4f36-b2ee-648c419008c1.png)

Adguard Debug Information:
[adg_logs_7.6.3583.0_0906_1725.zip](https://github.com/AdguardTeam/AdguardForWindows/files/7115624/adg_logs_7.6.3583.0_0906_1725.zip)

**Comment by Aydinv13** [comment]
This issue is moved here as it is not related to Windows repository. Devs are taking a look into this problem

**Comment by manirhossen** [comment]
> This issue is moved here as it is not related to Windows repository. Devs are taking a look into this problem

ok Thank You
