### ISSUE TITLE
worldvision.de: Rules with $third-party modifier don't work

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/CoreLibs#1523]
Rules with $third-party modifier don't work on this page:
https://www.worldvision.de/informieren
For example:

<details>
<summary>Screenshots</summary>
<img src="https://user-images.githubusercontent.com/18536328/135282223-1e89798e-6cb9-42d0-b07a-872201f51e26.png" >
<img src="https://user-images.githubusercontent.com/18536328/135282273-fb0f932f-80a2-4547-9036-0e6fd281dead.png" >

</details>

**Comment by sxgunchenko** [comment]
> We could use fetch metadata for $third-party detection

yup, that seems like it could work

> Would only work in Chrome, though

actually, FF behaves pretty similarly to Chrome

**Comment by Sergey-Lyapin** [comment]
It seems this issue is still relevant, please check hager.com. I use AG 7.9 Nightly 3

![gfg](https://user-images.githubusercontent.com/18536328/148979736-20427d92-b007-4ba1-b1b8-e3b6dfedb7a9.png)

**Comment by sxgunchenko** [comment]
The AG 7.9 Nightly 3 has CoreLibs 1.8 under the hood, so this is an expected behavior

**Comment by Sergey-Lyapin** [comment]
@sxgunchenko
What version of AdGuard will contain Corelibs 1.9?

**Comment by sxgunchenko** [comment]
> @sxgunchenko What version of AdGuard will contain Corelibs 1.9?

It seems like the upcoming Nightly 4 should do

**Comment by Sergey-Lyapin** [comment]
Thank you
