### ISSUE TITLE
AdGuard fails at pinning test on badssl.com

### ISSUE THREAD

**Issue by DBotThePony** [AdguardTeam/CoreLibs#1526]
Can not be open in any modern browser: https://pinning-test.badssl.com/

But Adguard accept the certificate on Windows and Android platforms.

<details>
  <summary>Expected:</summary>

![browser_yzoZDyUzE1](https://user-images.githubusercontent.com/6339511/135706214-707f2dc9-2b2f-4773-a59c-5bb765314b4f.png)

![firefox_A5PtrRGPvF](https://user-images.githubusercontent.com/6339511/135706216-3ed15c79-9bb3-4401-bcc5-f61591bc7afb.png)

</details>

<details>
  <summary>Got:</summary>

![27lJ1haUDq](https://user-images.githubusercontent.com/6339511/135706238-013b5773-672e-4daf-bdc0-dd76b9e2c470.png)

![browser_vBuXe3ajfP](https://user-images.githubusercontent.com/6339511/135706245-f8c52dce-de45-4193-b611-d1b2f2fa0058.png)

</details>

**Comment by ameshkov** [comment]
What's really interesting here is why this website cannot be opened in Chrome and Chromium-based browsers.

You see, it tests HPKP support that has been removed from Chromium quite some time ago: https://www.chromestatus.com/feature/5903385005916160

@sfionov do they have some pins hardcoded?

**Comment by DBotThePony** [comment]
Can confirm, that in latest chromium it is indeed can be opened normally, but not in derivatives, such as Opera or Vivaldi.


</details>

<details>
  <summary>Screenshots</summary>

![opera_fNaBlo3RJc](https://user-images.githubusercontent.com/6339511/135835340-dd31e088-3f00-4ad1-aaa4-df3163c103a5.png)
![vivaldi_0RnCUqoKi7](https://user-images.githubusercontent.com/6339511/135835348-3f56f1be-2ae8-452d-8e53-723a0f8a6cf6.png)
![chrome_cOiwWHxlpK](https://user-images.githubusercontent.com/6339511/135835350-016dfcad-f989-44af-96db-aa99b7ca4561.png)

</details>
