### ISSUE TITLE
Сертификат Адгард недействителен более!

### ISSUE THREAD

**Issue by Spok1** [AdguardTeam/CoreLibs#1528]
На Андроид 7.0 перестала выполняться фильтрация в связи с тем,что браузера обходят корневой сертификат, вместо этого используют сертификат с сервера!

**Comment by sfionov** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/3988#issuecomment-932087696

**Comment by Spok1** [comment]
После установки в хранилище и перезагрузки приложения,сертификат снова подменяет собой серверовский. А как быть после выпуска обновления приложения? Удалить этот серттфикат?

**Comment by Spok1** [comment]
После установки в хранилище и перезагрузки приложения,сертификат снова подменяет собой серверовский. А как быть после выпуска обновления приложения? Удалить этот сертификат?

**Comment by sfionov** [comment]
@Spok1 Этот сертификат (ISRG Root X1) есть во всех новых андроидах, начиная с 7.1.1. Можно оставить его, он точно не создаст проблем, а может наоборот решить их ещё и с некоторыми другими приложениями

**Comment by Spok1** [comment]
А,это уже на будущее,когда полностью сертификат DST Root CA X3 перестанет приниматься серверами,о котором ещё год назад писали?

**Comment by sfionov** [comment]
Всё так, будущее наступило 1 октября :)

**Comment by Spok1** [comment]
Так Iden trust заявляли,что до 2023 года продлят действие! Уже передумали?

**Comment by Spok1** [comment]
Так Let’s Encrypt заявляли,что до 2023 года продлят действие DST Root CA X3! Уже передумали?
