### ISSUE TITLE
«Adguard Service» causes ERR_SSL_VERSION_OR_CIPHER_MISMATCH on some sites in Chrome

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1537]
@DandelionSprout commented on [Sun Oct 24 2021](https://github.com/AdguardTeam/AdguardForWindows/issues/3970)

### Steps to reproduce
This one is very difficult to reproduce on command, but here is what seems to be the case:

1. Have AdGuard for Windows installed.
2. Either have AdGuard for Windows turned on, or have its service run in the background.
3. Go to Settings → Network → Network traffic → List of filtered applications, and ensure that Chrome is unchecked.
4. Open AdGuard's logger, and browse a bit around in Chrome for some seconds.
5. See that the logger contains various `tcp://` requests from `chrome.exe`, despite Chrome being supposedly deselected.
6. With this whole configuration still in use, go to Discord or GitHub in Chrome, and try to upload any images to a new comment. There is a 40% chance that the image upload will result in multiple error messages, sometimes needing up to 10 tries before it gets uploaded once the errors begin to happen.
7. This also affects saving commits in GitHub's web GUI, where Chrome will show an "ERR_SSL_VERSION_OR_CIPHER_MISMATCH" error page.

### Expected behavior

1) That having AdGuard turned on, does not result in ERR_SSL_VERSION_OR_CIPHER_MISMATCH errors when uploading images to various websites in Chrome.
2) That AdGuard actually does turn off filtering for applications where users have turned off filtering.
3) That `tcp://` requests is not processed for executables where filtering has been turned off.

### Actual behavior

I began getting a fairly large amount of problems in the past month with ERR_SSL_VERSION_OR_CIPHER_MISMATCH errors when I did work and hobby stuff, and after some weeks of having no idea what was going on, I seem to have pinpointed it to AdGuard. Not necessarily AdGuard for Windows, but my unsure research seem to indicate that this is also caused by the service running in the background. Closing the service fixes the problems instantly.

After further research, it also doesn't seem to be caused by the HTTPS filtering lock symbol next to the application checkbox row is turned on or off.

<details><summary>Screenshot:</summary>

None at the time of writing. I'll see if I'd be able to get any on request.

</details>

### Customer ID 

N/A at the time of writing.

### Your environment

* Environment name and version: Chrome 95.0.4638.54 x64 + AdGuard for Windows 7.7 nightly 27
* Operating system and version: Windows 11 RTM x64

---

@Alex-302 commented on [Sun Oct 24 2021](https://github.com/AdguardTeam/AdguardForWindows/issues/3970#issuecomment-950309272)

Need debug logs https://kb.adguard.com/en/windows/solving-problems/adguard-logs
Send them to support@adguard.com

I did not face this problem.

---

@DandelionSprout commented on [Sun Oct 24 2021](https://github.com/AdguardTeam/AdguardForWindows/issues/3970#issuecomment-950336479)

I've now sent my logs to that E-mail address (Ticket number 546952). I was not immediately able to see any clearcut causes in the logs, so I can only hope you'll understand more of it than me.

It does appear that the errors are far more likely to appear if the image is being pasted into comments from the Windows clipboard, if that is of interest.

**Comment by DandelionSprout** [comment]
I haven't noticed any problems in the past 5 days that I can remember, at least. So I'd declare this to be solved for the time being.
