### ISSUE TITLE
Xiaomi Router Management Page

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1538]
@MHzsz commented on [Tue Oct 12 2021](https://github.com/AdguardTeam/AdguardFilters/issues/97011)

### Steps to reproduce

1.出问题的页面是小米路由器的管理页面,只能截图展示.
2.正常使用Adguard时,二维码和登录按钮会消失;
启用保护并且关闭广告拦截器,关闭隐形模式,关闭DNS保护,关闭扩展时,二维码和登录按钮依然会消失.
3.只有禁用保护的时候,页面才能正常显示.
4.在网络-流量过滤-过滤应用列表中排除chrome之后,chrome访问该页面依然会受到影响.

### Expected behavior

![Snipaste_2110121154_小米路由器 - Vivaldi](https://user-images.githubusercontent.com/39558996/136889585-32c2bdf0-3921-49e7-bb4e-4d86abe37e02.jpg)

### Actual behavior

![Snipaste_2110121158_AdGuard](https://user-images.githubusercontent.com/39558996/136889611-bb298eab-c1fb-4d23-8827-9fbf784d6cb0.jpg)
![Snipaste_2110121158_AdGuard_0](https://user-images.githubusercontent.com/39558996/136889614-4cc7b20e-b149-476e-af79-535dc635e2f8.jpg)

<details><summary>Screenshot:</summary>

</details>

### Customer ID 

The ticket number is 543565.

### Your environment

* Environment name and version: chrome, 94.0.4606.81
* Operating system and version: Windows 10, v.21H1, build 19043.1266)

---

@AdamWr commented on [Tue Oct 26 2021](https://github.com/AdguardTeam/AdguardFilters/issues/97011#issuecomment-951845155)

Hello,
Do I understand correctly that QR code is not displayed even if all modules are disabled (Ad Blocker, Stealth Mode, DNS Protection and Extensions)?

---

@MHzsz commented on [Wed Oct 27 2021](https://github.com/AdguardTeam/AdguardFilters/issues/97011#issuecomment-952523653)

> Hello, Do I understand correctly that QR code is not displayed even if all modules are disabled (Ad Blocker, Stealth Mode, DNS Protection and Extensions)?

Thanks for replying.
Yes, it is. And the button for signing in won't display either, the button looks like ">".

**Comment by Alex-302** [comment]
Another one https://github.com/AdguardTeam/AdguardFilters/issues/98826

**Comment by ameshkov** [comment]
Ordered Xiaomi Router to the office, we need to take a look with our own eyes.

**Comment by ngorskikh** [comment]
@MHzsz You can turn on `Use redirect driver mode` in advanced settings as a workaround while we are working on this issue.

**Comment by MHzsz** [comment]
> @MHzsz You can turn on `Use redirect driver mode` in advanced settings as a workaround while we are working on this issue.
Thank you, I'll try later. For now, 7.8 nightly 1 can fix the issue.
