### ISSUE TITLE
Make Adguard abide the system certificate store or use a custom CA store

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1540]
@inume commented on [Mon Nov 01 2021](https://github.com/AdguardTeam/AdguardForMac/issues/980)

I'm not 100% sure if it is a bug or expected behavior.
On Mac OS Monterey with Adguard installed it seems when Adguard is used for proxying traffic that the system CA store is ignored. This either means Adguard uses its own CA store (in that case it would be expected) or it somehow works around the settings in MacOS. I'd consider this a security issue.
In case Adguard uses its own CA store could you document that and maybe somehow make that configurable.
It would be great if it would work with the native (customized) CA store from MacOS :) 

### Steps to reproduce

In Keychain remove trust from all root CAs in the system roots CA store.
Alternatively distrust selected ones, just make sure that you distrust those which are used on a website for a later test.
Run Adguard.
Connect to any website or to a website where you revoked trust for its used root CA.

### Expected behavior
Adguard or the website should throw some certificate error on connecting to a website where trust for the root CA was revoked.

### Actual behavior
Proxied connections to the website are successfully bypassing the system root CA store.

### Your environment
Mac M1 with Monterey
Automatic proxy mode was used (service could not start with Network extension mode)

**Comment by ngorskikh** [comment]
When trust settings for a system root change, a copy with the new settings is added to the `admin` domain, however we still load the cert with original trust settings from the system domain. Fixed in core/pull-requests/2593

**Comment by inume** [comment]
That was quick :) Do you know if this can also handle the "login keychain" ? Even if you distrust a root CA or if the CA is outdated you can kind of override trust for a single domain by importing the domain certificate into the login keychain. So connections to the website will be trusted but not everything else signed by the root CA. This is a bit like key pinning I guess.

**Comment by ngorskikh** [comment]
If you explicitly trust the leaf certificate, but it chains to an untrusted certificate, AdGuard still won't trust it, however, your browser might. That means that the site might open, AdGuard just won't filter ads on it. For now, that is intended behaviour.

**Comment by inume** [comment]
But isn't AdGuard kind of the browser when doing TLS inspection? It is Browser-> AdGuard -> Website, isn't it?
If AdGuard does not trust the cert or root CA the site should not open.

**Comment by sfionov** [comment]
@inume When AdGuard doesn't trust website's cert, it doesn't MITM. In this case, browser talks directly to website.
