### ISSUE TITLE
www.xnxx.com

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/CoreLibs#1542]
@adguard-bot commented on [Tue Nov 02 2021](https://github.com/AdguardTeam/AdguardFilters/issues/98754)

### Issue URL (Incorrect Blocking)
[NSFW] [https://www.xnxx.com/porn-maker/indian-gf-videos-1#_best](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.xnxx.com%2Fporn-maker%2Findian-gf-videos-1%23_best)

### [NSFW] Screenshots
<details>
  <summary>Screenshot 1</summary>

  [Screenshot 1](https://reports-img.adguard.com/KKiFphF.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  [Screenshot 2](https://reports-img.adguard.com/Xzqb6MG.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.7
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Self-destructing third-party cookies (180), <br>Block WebRTC, <br>Block Push API, <br>Block Location API, <br>Block Flash
DNS filtering: | server: `sdns://AQIAAAAAAAAAFDE3Ni4xMDMuMTMwLjEzMDo1NDQzINErR_JS3PLCu_iZEIbq95zkSV2LFsigxDIuUso_OQhzIjIuZG5zY3J5cHQuZGVmYXVsdC5uczEuYWRndWFyZC5jb20`<br>filters: `User rules`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/>NoCoin Filter List<br/><br/><b>Other:</b><br/>AdGuard Experimental
Userscripts: | https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js,<br>https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js,<br>https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
Referrer: | [https://www.xnxx.com/porn-maker/indian-gf-videos-1](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.xnxx.com%2Fporn-maker%2Findian-gf-videos-1)

**Comment by sfionov** [comment]
@zloyden This is expected behavior. The same problem as in xvideos.com.
```$xmlhttprequest,elemhide,jsinject,extension``` exception should help

**Comment by zloyden** [comment]
Well, ok. I've changed the rule recently https://github.com/AdguardTeam/AdguardFilters/commit/d2a45fc693f9035fd3053c03e195033c65ec300a
