### ISSUE TITLE
Enable more verbose logging for https filtering

### ISSUE THREAD

**Issue by inume** [AdguardTeam/CoreLibs#1543]
When debugging some issue with handshakes, certificates and TLS in general it would be nice to have some more verbose logs.
It looks like ciphers are logged in the debug log also certificate related stuff is mentioned a few times. But I could not find the original website certificate inside the log. Could you maybe add an option that those are logged? I think boringssl is used for TLS so maybe it would also be possible to make use of the ssl keylog file?

**Comment by sfionov** [comment]
@inume We'll consider adding it. For now, you may see original certificate for site in "adguard browser assistant" extension.

**Comment by inume** [comment]
Thanks :). But I guess this only applies to connections done by a browser and not some app?

**Comment by ameshkov** [comment]
@inume Yeah, that's true. Actually, we were thinking about exposing it via the "filtering log", but these are future plans.

@sfionov if logging the original cert is trivial, let's consider it for v1.9 or v1.10.
