### ISSUE TITLE
Rule `@@||example.org^$important,document` doesn't display as whitelisted if not located in the "User rules" filter

### ISSUE THREAD

**Issue by contribucious** [AdguardTeam/CoreLibs#1545]
Hello,
&nbsp;

Here is a second one. :relaxed:
&nbsp;
:warning: **This is only aesthetic and informational because the whitelisting takes place _in fact_ (in AdGuard).**
&nbsp;
&nbsp;

###### :large_blue_diamond: Correct result produced when the rules are added in the "User rules" filter.
&nbsp;

#### :one: Add these two rules in the "User rules" filter:
```
example.org##h1
@@||example.org^$important,document
```
_(The first one only serves as a means to verify the actual behavior.)_
&nbsp;

#### :two: Observe the correct behavior:
![Screenshot 2021-10-29 103355](https://user-images.githubusercontent.com/4764956/139405269-88e7a8b5-1c3e-462a-bb56-aa58e0d1f436.png)
&nbsp;
&nbsp;

###### :large_orange_diamond: Incorrect result produced when the same rules are added elsewhere (in this case, in a new filter added via the "Add custom filter" button).
&nbsp;

#### :three: Observe the _incorrect_ behavior:
![Screenshot 2021-10-29 103633](https://user-images.githubusercontent.com/4764956/139405925-72d9ce5a-d1bd-48b6-a153-e1421b07e189.png)
_... when in fact, the whitelisting **also did** take place — i.e. protection is **disabled**.
Otherwise the `h1` element would have disappeared visually!_
&nbsp;
&nbsp;

:memo: Same problem if added from an external source using the "Import filter" button for information. (Local test web server used in my case, using a well functional filter — loaded from `127.0.0.1` — by the way, because deactivating [the whitelisting rule](https://user-images.githubusercontent.com/4764956/139407734-fa5de041-b2f8-4ded-9b9f-4bf5157e5d54.png) produces the [expected result](https://user-images.githubusercontent.com/4764956/139407850-6d4083bb-5047-4196-a65f-c00512fc6e50.png), i.e. **`h1` element hidden**, for verification.)
&nbsp;
&nbsp;
&nbsp;

:information_source: **AdGuard Browser Assistant version:** 1.1.16 (used on Firefox 93.0)
:information_source: **AdGuard version:** 7.7
:information_source: **OS information:** Windows 10 (21H1)
&nbsp;
&nbsp;

Thanks in advance. :thumbsup:

**Comment by sfionov** [comment]
Both #1545 and #1546 should be fixed in current assistant. In this cases, switch is not available.
