### ISSUE TITLE
planeta.ru is broken by filtering

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1547]
@adguard-bot commented on [Mon Nov 01 2021](https://github.com/AdguardTeam/AdguardFilters/issues/98691)

### Issue URL (Incorrect Blocking)
 [https://planeta.ru](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplaneta.ru)
### Comment
Username: @Zelgadiss
> Если включен AdGuard (даже если сайт внесён в исключения везде), то сайт просто не грузится при большом количестве обращений к сайт: несколько раз обновить страницу или открыть несколько вкладкой с этим сайтом

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/b5PLt6T.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/PgmIVRi.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.7
Browser: | Firefox
AdGuard driver: | WFP
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Language-specific:</b><br/>EasyList Czech and Slovak, <br/>EasyList Hebrew, <br/>Latvian List, <br/>AdBlockID, <br/>Official Polish filters for AdBlock, uBlock Origin & AdGuard, <br/>Polish Anti Adblock Filters, <br/>AdGuard Russian, <br/>AdGuard German
Userscripts: | https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js,<br>https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js,<br>https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js,<br>https://userscripts.adtidy.org/release/adguard-wot/1.0/wot.user.js

---

@zubrRB commented on [Mon Nov 01 2021](https://github.com/AdguardTeam/AdguardFilters/issues/98691#issuecomment-956387909)

Попробуйте с отключенными сторонними фильтрами, ибо у меня с базовыми фильтрами AdGuard не повторяется.

---

@soksanichenko commented on [Mon Nov 01 2021](https://github.com/AdguardTeam/AdguardFilters/issues/98691#issuecomment-956394494)

@zubrRB спасибо, помогло. Выключил все языковые кроме русского. Причём проблема появилась совсем недавно. Видимо после автоподключения одного из языковых фильтров.

---

@zubrRB commented on [Mon Nov 01 2021](https://github.com/AdguardTeam/AdguardFilters/issues/98691#issuecomment-956399844)

Автоподключение языковых фильтров можно отключить в настройках Антибаннера + подключить дополнительные базовые (фирменные):  Фильтр отслеживания по URL;  Фильтр виджетов социальных сетей; Фильтр разждражителей.

---

@soksanichenko commented on [Mon Nov 01 2021](https://github.com/AdguardTeam/AdguardFilters/issues/98691#issuecomment-956400998)

Спасибо, попробую.

---

@soksanichenko commented on [Mon Nov 01 2021](https://github.com/AdguardTeam/AdguardFilters/issues/98691#issuecomment-956610379)

Не, всё равно проблема позже проявилась: снова разлогинило, при открытии нескольких вкладок с сайтом начались ошибки со стороны сайта, а потом он и вовсе отказался открываться.

---

@Alex-302 commented on [Wed Nov 03 2021](https://github.com/AdguardTeam/AdguardFilters/issues/98691#issuecomment-958818299)

@soksanichenko От включенных фильтров проблема зависит? Открыл несколько вкладок, пообновлял - пока работает.

---

@soksanichenko commented on [Wed Nov 03 2021](https://github.com/AdguardTeam/AdguardFilters/issues/98691#issuecomment-958825644)

Нет. Отключил антибаннер совсем, но проблема повторяется: открыл 9 вкладок с поддержанными проектами секунд за 5-6, и проблема проявилась в трёх из 9 вкладкок. На одной сайт выдал красные всплывашки с ошибками, на двух - просто не стал грузиться и браузер предупредил, что сайт замедляет работу браузера.

---

@Alex-302 commented on [Wed Nov 03 2021](https://github.com/AdguardTeam/AdguardFilters/issues/98691#issuecomment-959278753)

@soksanichenko А фильтрация DNS и антитрекинг включены были в этот момент?

---

@soksanichenko commented on [Wed Nov 03 2021](https://github.com/AdguardTeam/AdguardFilters/issues/98691#issuecomment-959281469)

Нет, выключены.

---

@Zelgadiss commented on [Fri Nov 05 2021](https://github.com/AdguardTeam/AdguardFilters/issues/98691#issuecomment-962009143)

Вот такие ошибки вылетает на планете при слишком частом обращении к сайту если включен AdGuard.
http://u.cubeupload.com/ZelGray/screenshot2021110500.png

---

@Zelgadiss commented on [Fri Nov 05 2021](https://github.com/AdguardTeam/AdguardFilters/issues/98691#issuecomment-962176317)

Кстати, на мобильном такая же проблема. 3-5 переходов по сайту, а потом он перестает грузиться

---

@Alex-302 commented on [Mon Nov 08 2021](https://github.com/AdguardTeam/AdguardFilters/issues/98691#issuecomment-963132328)

Возможно баг. У себя повторить не получается. Перенесу в другой репозиторий.

**Comment by ameshkov** [comment]
Это чертов anti-ddos их сумасшедший.

**Comment by ameshkov** [comment]
Может быть вот эта задача чуть поможет - #251

**Comment by soksanichenko** [comment]
@ameshkov я пробовал добавлять сайт в исключения https фильтрации, но это не помогает(

**Comment by ameshkov** [comment]
Так дело в том, что этот нездоровый anti-DDOS, которым они пользуются, в целом работает нестабильно.

Он может вполне легального пользователя посчитать ботом, а так как проверка на это у них написана криво - это ломает загрузку сайта.

**Comment by soksanichenko** [comment]
Мда. По ходу единственный способ: открывать только один таб на этот сайт.

**Comment by ameshkov** [comment]
@soksanichenko вообще, я планете много раз писал про это и они вроде как морально готовы свалить с этого анти-ддос сервиса (в анти-ддос сервис я тоже писал, но там кажется в пустоту мои сообщения попадают).
