### ISSUE TITLE
Add regexp support for $domain modifier

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/CoreLibs#1550]
now there is no chance to create single cosmetic rule for hiding the same element on such domains:
`example1.com, example2.com, example3.org`

it would be nice if $domain modifier supports regular expressions, just like [$path does](https://github.com/AdguardTeam/CoreLibs/issues/124)

something like this:
`[$domain=/example[0-9]\.(com|org)/]##.ad`

**Comment by ameshkov** [comment]
Why limit just to the cosmetic rules? If we do it here, we should extend it to basic rules as well.

@sfionov can we include this in v1.10 for instance?

**Comment by sfionov** [comment]
Yes, assigned to 1.10

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/tsurlfilter/issues/41
 https://github.com/AdguardTeam/tsurlfilter/issues/58
 https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/1109

**Comment by dnmTX** [comment]
@AdguardTeam maybe unrelated question but what about redirects? For example links from `voe.sx` are allways redirected to another domain and they change those domains very frequently. Here is a example:
**Original Link:** https://voe.sx/ffgecklhux79 redirects(as of now) to: https://tubelessceliolymph.com/ffgecklhux79
So basically rules that applied for `voe.sx` simply don't work. And domains like `tubelessceliolymph.com` are disposable and replaced every week or so and user(s) like me have to reaply same rules to the new domain.
Any workaournd(s) for this?

**Comment by krystian3w** [comment]
uBo implemented regex, if someone trust something like:

```adb
/bad-js.$domain=/[a-z-]{18}\.[\w]{2,20}/
/[a-z-]{18}\.[\w]{2,20}/##.bad-class
```

but fail for `,` in cosmetic/scriptlet filters and `|` in network filters if gorhill rejected repair:

https://github.com/uBlockOrigin/uBlock-issues/discussions/2234#discussioncomment-5403472

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AGLint/issues/161
