### ISSUE TITLE
Add $url modifier

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/CoreLibs#1551]
it should be a modifier for matching page url, something like combined $domain and $path

**Comment by sxgunchenko** [comment]
Here's the proposed spec:

### url

`$url` modifier limits the rule application area to URLs matching the specified mask.

#### Syntax

```
url = pattern
```

where `pattern` is pretty much the same as [`pattern` of the basic rules](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#basic-rules-syntax-1) assuming that [some characters](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#syntax-10) must be escaped.
The [special characters](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#special-characters) and [regular expressions](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#regular-expressions-support) are supported as well.

#### Examples

* `[$url=||example.com/ads/*]##.textad` — hides a `div` with a class `textad` at addresses like `http://example.com/ads/banner.jpg` and even `http://subdomain.example.com/ads/otherbanner.jpg`.
* `[$url=||example.org^]###adblock` — hides an element with attribute `id` equals `adblock` at `example.org` and its subdomains.
* `[$url=/\[a-z\]+\\.example\\.com^/]##.textad` — this rule hides `div` elements of the class `textad` for all domains matching the regular expression `[a-z]+\.example\.com^`.

**Comment by ameshkov** [comment]
@AdguardTeam/filters-maintainers what do you think?

**Comment by zloyden** [comment]
It would be nice to use it.
I had also asked the same about blocking request rules, but as far as I've been explained, it can't be done.

---

> [$url=||example.com/ads/*]##.textad

Can it be like this?
```
[$url=||example.*/ads/*]##.textad
```

> [$url=||example.org^]###adblock

So, if I don't want to use the rule on subdomains, how to rewrite this? Something like that?
```
[$url=www.example.org^]###adblock
```

**Comment by sxgunchenko** [comment]
> Can it be like this? `[$url=||example.*/ads/*]##.textad`

Yep

> So, if I don't want to use the rule on subdomains, how to rewrite this?

May be something like this
```
[$url=*://example.org^]...
```

**Comment by zloyden** [comment]
> May be something like this
> 
> ```
> [$url=*://example.org^]...
> ```

If there is no other options, then fine, but I'd rather use the same syntax as in the cosmetic rules.
```
www.example.org##body
```

**Comment by sxgunchenko** [comment]
You could use `$domain` + `$path` in that case
