### ISSUE TITLE
Какой уровень поддержки юзер-скриптов в AdGuard и насколько он кореллирует с greasmonkey и tampermonkey ?

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/CoreLibs#1552]
@Baltazar500 commented on [Mon Nov 15 2021](https://github.com/AdguardTeam/AdguardForAndroid/issues/4031)

Сабж.

Какой уровень поддержки юзер-скриптов в AdGuard и насколько он кореллирует с greasmonkey и tampermonkey ? Понадобилось воткнуть юзер-скрипт, который блюрит на pikabu.ru посты под тегом "жесть" (нужна регистрация и авторизация), но не прокатило. Скрипт на сайте не работает. Хром 71.0.3578.99 Safari/537.36 с параметрами запуска с мимикрией под десктоп

>chrome --user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Safari/537.36" --force-device-scale-factor=1.60

[Pikabu-HARG-bloor.user.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/7538213/Pikabu-HARG-bloor.user.txt)

При этом в 52-м фоксе с greasmonkey (даже не tamper) всё работает на ура. Неужели настолько всё плохо в AdGuard'е с userjs ? Или скрипт надо как-то корректировать под нюансы AdGuard'a ? Скрипт в аттаче, расширение изменено на txt, т.к. он иначе не аттачился.

**Comment by ameshkov** [comment]
@Baltazar500 AdGuard поддерживает процентов 80-90 функционала Tampermonkey и почти весь функционал Greasemonkey.

Мне, честно говоря, не очень понятно почему приложенный юзерскрипт не работает. Причем проблема именно на pikabu, происходит из-за того, что скрипты самого сайта каким-то неведомым образом вмешиваются в работу скрипта.

Если добавите `// @run-at document-start` - скрипт заработает, так как это гарантия, что он запускается раньше скриптов самого сайта.

**Comment by Baltazar500** [comment]
@ameshkov, премного благодарен - заработало. Спасибо. Я ж говррил, что есть какие-то нюансы при работе с userjs движком AG ))) Тред наверное зря закрыли - у меня в запасниках ещё парочка "проблемных" userjs. Ну да ладно, не поможет втыкание в них
>// @run-at document-start
отпишусь в данном треде ;)

**Comment by ameshkov** [comment]
@Baltazar500 ну да, куда ж без нюансов. Но тут они специфические для самого пикабу, что-то этот сайт странное мутит.
