### ISSUE TITLE
Failed to install a custom filter list with `#include` directive

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1553]
Here's a filter example:
https://raw.githubusercontent.com/iam-py-test/my_filters_001/main/special_lists/anti-malware-ubo-extension.txt

Fails on this line: `!#include google-safe-browsing-reverse-engineered.txt`, `error code is AGFPE_FETCH`.
Works fine on AdGuard for Mac so I believe the issue is Windows-specific.

I also recommend you to test this list to check if `#include` is properly handled: https://github.com/DandelionSprout/adfilt/blob/master/AnnoyancesList

**Comment by iam-py-test** [comment]
Any updates?

**Comment by iam-py-test** [comment]
Has this been fixed? Where can I download the beta to test?

**Comment by ameshkov** [comment]
@iam-py-test yeah, it has been fixed, and the fix will be shipped in AG v7.8.

Alternatively, you can try the "nighly" update channel to receive it sooner (the update channel can be changed in AG settings).

**Comment by iam-py-test** [comment]
After setting the channel to Nightly, does hitting the _update_ button install it:
![image](https://user-images.githubusercontent.com/84232764/143786143-4f3c4b96-ddd8-4010-a6ce-46b409f83afd.png)

**Comment by ameshkov** [comment]
@iam-py-test there's a separate "Check updates" button for application updates (via tray icon).

**Comment by iam-py-test** [comment]
> @iam-py-test there's a separate "Check updates" button for application updates (via tray icon).

Sorry, I'm not that familiar with AdGuard :)
It worked, thanks

**Comment by iam-py-test** [comment]
The filter still doesn't work

**Comment by iam-py-test** [comment]
![image](https://user-images.githubusercontent.com/84232764/143786811-00d89a60-5fb1-4aec-ae26-51039dd29705.png)

**Comment by ameshkov** [comment]
That’s okay, the issue is solved in CoreLibs (the filtering engine), but it hasn’t yet been shipped to the users. Expect it to arrive this week in the new nightly.
