### ISSUE TITLE
www.jav321.com

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/CoreLibs#1556]
@adguard-bot commented on [Tue Nov 16 2021](https://github.com/AdguardTeam/AdguardFilters/issues/100249)

### Issue URL (Incorrect Blocking)
[NSFW] [https://www.jav321.com/video/snis00420](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.jav321.com%2Fvideo%2Fsnis00420)
### Comment
Username: @KingwithQueen
> 右上角的广告，以及其他广告（未在截图中显示）。其他广告是点击页面任何部分后会弹窗出广告页面。
> 另外，AdGuard对这个浏览器完全不支持。使用这个浏览器（360极速浏览器X）打开任何网页都无法过滤广告，但是使用edge就可以。然而edge缺少很多功能，所以我想贵公司能够增加对这个浏览器的支持

### [NSFW] Screenshots
<details>
  <summary>Screenshot 1</summary>

  [Screenshot 1](https://reports-img.adguard.com/xrpTc9y.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  [Screenshot 2](https://reports-img.adguard.com/GNWTLDk.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.7.2
Browser: | 360极速浏览器X
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (180), <br>Disable cache for third-party requests, <br>Block WebRTC, <br>Block Push API, <br>Hide your Referrer from third-parties (www.jav321.com), <br>Hide your User-Agent (Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36), <br>Hide your IP address (1.5.0.0)
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Language-specific:</b><br/>AdGuard Chinese, <br/>AdGuard German
Userscripts: | https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js,<br>https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js,<br>https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js

---

@Yuki2718 commented on [Tue Nov 16 2021](https://github.com/AdguardTeam/AdguardFilters/issues/100249#issuecomment-970323755)

@Alex-302 @BlazDT @zloyden @Sergey-Lyapin @stanislav-atr Pls check.

---

@zloyden commented on [Fri Nov 26 2021](https://github.com/AdguardTeam/AdguardFilters/issues/100249#issuecomment-979475746)

Hi @KingwithQueen! I haven't seen ads on Chrome, but I saw that you have been using `360极速浏览器X`. I guess the problem is the browser uses original certificate.
It's not the filter issue, I'll move it to another repository.

**Comment by ameshkov** [comment]
@zloyden does HTTPS filtering in this browser not work when added to the "Filtered apps" list?

Just in case, here's that browser:
https://browser.360.cn/

**Comment by zloyden** [comment]
@ameshkov I think something was wrong that day, because I can see our certificate.
@KingwithQueen please add manually the browser via `Filtered apps` list.

**Comment by ameshkov** [comment]
@zloyden hm, don’t we filter this browser by default? If not, I guess we should add it to the default filtered apps list since it seems to be rather popular.

**Comment by zloyden** [comment]
No, we don't filter it by default.

**Comment by ameshkov** [comment]
* Win: https://github.com/AdguardTeam/AdguardForWindows/issues/4018
* Mac: https://github.com/AdguardTeam/AdguardForMac/issues/999
* Android: https://github.com/AdguardTeam/AdguardForAndroid/issues/4040

**Comment by KingwithQueen** [comment]
@zloyden How can I add manually the browser via Filtered apps list.
I didn't find this list in the set of AdGuard.

**Comment by zloyden** [comment]
There are two ways. You can either add manually to the browser `.exe` file or wait until the tasks above are completed https://github.com/AdguardTeam/CoreLibs/issues/1556#issuecomment-981380019.

**Comment by KingwithQueen** [comment]
@zloyden @ameshkov In addition, the browser's URL is: https://down.360safe.com/cse/360csex_21.0.1040.0.exe
360 browser has three names, the Chinese name is:360安全浏览器（32-bit）、360极速浏览器（32-bit）、360极速浏览器X（64-bit）。They English names is:360 browser (32-bit), 360Chrome (32-bit), 360ChromeX (64-bit).
The browser I used is 360chromeX. And I tried two other browsers, I don't need to adjust anything, as long as AdGuard is installed, you can block your advertisement. But on 360chromeX, AdGuard cannot filter any ads. I see you say that I need to manually add this browser to the filter list, but I don't know how to do it, I didn't find this list in the AdGuard settings. Since the two browser design issues, if there is too much URL in the favorites, the display error will be easily displayed when booting the browser. So I have to use 360chrome.
