### ISSUE TITLE
Preview is broken on dropbox.com

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1558]
@adguard-bot commented on [Fri Nov 26 2021](https://github.com/AdguardTeam/AdguardFilters/issues/101302)

### Issue URL (Incorrect Blocking)
 [http://dropbox.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fdropbox.com)
### Comment
Username: @thegodfatherkangaroo
> Preview of files on dropbox not working anymore. Tested with audio files (.wav & .mp3). Need a direct link to a file on dropbox. 
> 
> Disabling adguard (through the app, not the extension) fixes it. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/0zZmxhV.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/MP8ENYw.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.7.2
Browser: | Edge
AdGuard driver: | WFP
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>AdGuard URL Tracking<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances
Userscripts: | adguard extra
adguard popup blocker

Other extensions used: | none

**Comment by Alex-302** [comment]
Reproduced even if all modules are disabled, and only protection is enabled.
Filter rules do not help, only HTTPS exclusion.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/144613529-7293bbdf-6808-4db3-86fb-c4b78aa9712b.png)

</details>

**Comment by grumaxxx** [comment]
Already resolved in #1518. The problem was related to processing trailers.

**Comment by thegodfatherkangaroo** [comment]
Worked for a few days but unfortunately is broken again. Preview does not load until fully disable adguard.
