### ISSUE TITLE
DNS-over-HTTPS filtering

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1563]
Currently, when the browser uses DoH on its own, AdGuard misses these queries. Instead of that, we should be able to filter DoH queries locally just like what we do with plain DNS.

We should consider linking DnsLibs and CoreLibs.

This task is a prerequisite for #553

**Comment by JohnRTitor** [comment]
Can this also mitigate the behaviour where Adguard can't detect DNS queries when Android private DNS is enabled?

**Comment by ameshkov** [comment]
@JohnRTitor unfortunately. Decrypting DoT on Android would require root.
