### ISSUE TITLE
Breaks internet connection with Shadowrocket (iOS VPN app)

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/CoreLibs#1570]
@ViRb3 commented on [Tue Dec 07 2021](https://github.com/AdguardTeam/AdguardForMac/issues/1006)

### Steps to reproduce

1. Install [Shadowrocket](https://apps.apple.com/us/app/shadowrocket/id932747118) iOS app on a M1 Mac
2. Connect to a VPN server using the app

### Expected behavior
Internet works.

### Actual behavior
Internet does not work unless you disable AdGuard.

`ping` still works, but TCP seem to fail. For example, ssh errors, and HTTP requests result in:
```
$ curl -v google.com
*   Trying 240.0.0.9:80...
* Connected to google.com (240.0.0.9) port 80 (#0)
> GET / HTTP/1.1
> Host: google.com
> User-Agent: curl/7.77.0
> Accept: */*
>
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server
```

I suspect this may be a more general issue with iOS VPN apps in general, but I have not found a good way to test that.

### Your environment
macOS 12.0.1
MacBook Pro M1 Max
AdGuard 2.6.1.1051
Shadowrocket  2.1.92 (1451)

---

@Chinaski1 commented on [Tue Dec 14 2021](https://github.com/AdguardTeam/AdguardForMac/issues/1006#issuecomment-993390557)

Sorry for the late reply.

The thing is that at the moment there is no support for compatibility with iOS VPN applications.
We will work in this direction in the near future.

As a workaround, you can try to configure `upstream proxy` in the AdGuard advanced settings section provided that the VPN can operate in proxy mode.

**Comment by ngorskikh** [comment]
This is most probably due to a bug in macOS 12.0.1 where connections bypassed by the transparent proxy break. Works fine on macOS 12.4 beta. Should also work on the most recent release macOS version.

**Comment by ViRb3** [comment]
I just tested macOS 12.3.1  with Shadowrocket 2.2.4 and AdGuard 2.7.0.1094, and unfortunately, internet access is lost as soon as both are turned on. If I disable AdGuard, internet connectivity is immediately restored. It doesn't matter in what order I turn them on, as soon as the second one is activated, internet is lost. Each one separately works great.

**Comment by ViRb3** [comment]
Regarding @Chinaski1's suggestion, there does not appear to be a way to tell Shadowrocket to "proxy" through AdGuard.

**Comment by ngorskikh** [comment]
@ViRb3 Hi! Some questions to troubleshoot:
1. What kind of proxy do you select in Shadowrocket?
2. Is the proxy in the local network or in the Internet?
3. Have you tried resetting AdGuard's settings?
4. Also: you should _not_ add Shadowrocket to AdGuard's list of filtered apps.

**Comment by ViRb3** [comment]
Good news, it seems to actually work. The problem was that Safari sometimes needs to be restarted after enabling the VPN. Ping from terminal, even with hostname, always works though, so I think everything is good!
