### ISSUE TITLE
www.bbcgoodfood.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1571]
@adguard-bot commented on [Sun Dec 12 2021](https://github.com/AdguardTeam/AdguardFilters/issues/102912)

### Issue URL (Incorrect Blocking)
 [https://www.bbcgoodfood.com/recipes/indian-butternut-squash-curry](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.bbcgoodfood.com%2Frecipes%2Findian-butternut-squash-curry)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/fKIK8P4.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/Q1TdoT0.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.6.1.1051 setapp
Browser: | Safari
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard German, <br/>AdGuard Japanese, <br/>EasyList Italy
Userscripts: | https://userscripts.adtidy.org/beta/adguard-extra/1.0/adguard-extra.meta.js
Other extensions used: | 1Blocker

**Comment by AdamWr** [comment]
It looks like that any extension (userscript) causes that website is broken.
Steps to reproduce:
1. Add this rule to user rules:
```
@@||bbcgoodfood.com^$extension,badfilter
```
2. Enable any extension, for example AdGuard Extra
3. Go to - [https://www.bbcgoodfood.com/recipes/indian-butternut-squash-curry](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.bbcgoodfood.com%2Frecipes%2Findian-butternut-squash-curry)

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/146342488-cfaac45a-9483-4dca-8204-0a7eee451b9b.png)

</details>

AdGuard for Windows Version 7.8 nightly 5 (build 3778, CL 1.8.274)

**Comment by grumaxxx** [comment]
Without this rule site is work well (some scripts is blocked). When we add this rule userscripts conflict with scripts on the site (which were previously blocked correctly) and the site crashes.

**Comment by AdamWr** [comment]
It looks like that it can be also fixed by rule like this:
```
bbcgoodfood.com#%#(function(){window.DD_LOGS={onReady(){},logger:{log(){}}}})();
@@||bbcgoodfood.com^$extension,badfilter
```
but I'm still wondering why any userscript (when an above `#%#` rule is disabled) , even just something like:
```
// ==UserScript==
// @name         Test
// @namespace    Test
// @version      0.1
// @description  Test
// @author       Test
// @match        http://*/*
// @match        https://*/*
// @grant        unsafeWindow
// @run-at       document-start
// ==/UserScript==

(()=>{ console.log("TEST"); })();

```
breaks this website.

**Comment by sfionov** [comment]
@AdamWr 

Typescript team has performed some investigation for this issue.

Issue is triggered by incompatibility of site script - if site script detects more than one script, it reports that fact to datadog logger which we blocked. So, disabling datadog logger on this site using rules seems the only possible solution.

**Comment by sfionov** [comment]
Reopened https://github.com/AdguardTeam/AdguardFilters/issues/102912 since this is not solvable in CoreLibs

**Comment by AdamWr** [comment]
Do I understand correctly, that I should remove `@@||bbcgoodfood.com^$extension` and add `bbcgoodfood.com#%#(function(){window.DD_LOGS={onReady(){},logger:{log(){}}}})();`?

**Comment by sfionov** [comment]
@AdamWr Yes, that would be a solution

**Comment by AdamWr** [comment]
Okay, done.
Thank you for your reply.
