### ISSUE TITLE
com.whatsapp - calling issue

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/CoreLibs#1574]
@Alex-302 commented on [Mon Dec 27 2021](https://github.com/AdguardTeam/AdguardForAndroid/issues/4074)

@adguard-bot commented on [Fri Dec 03 2021](https://github.com/AdguardTeam/AdguardFilters/issues/101902)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=com.whatsapp&hl=en](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.whatsapp%26hl%3Den)
### Comment
Username: @ihrubab
> After yesterday's update to v3.6.5 beta 1, whenever I call or receive a call from Facebook Messenger or the WhatsApp Messenger app, it gets stuck at "Connecting" and never connected. If I turn Off Adguard or disable Adguard Protection in app management, I can call and receive calls without any problems. 
> 
> This problem started happening after yesterday's Adguard update. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/7Y5uHvI.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/NeNY9NO.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 11
AdGuard product: | AdGuard for Android v3.6.5 beta 1 (35)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Block third-party Authorization header, <br>Self-destructing third-party cookies (180), <br>Block WebRTC, <br>Block Push API, <br>Hide your Referrer from third-parties (), <br>Hide your Referrer from third-parties, <br>Hide your IP address (209.141.53.254)
DNS filtering: | server: `https://dns.adguard.com/dns-query`<br>filters: `https://filters.adtidy.org/android/filters/15_optimized.txt`
Filters: | <b>Ad Blocking:</b><br/>Peter Lowe's Blocklist, <br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>Fanboy's Anti-Facebook List, <br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection, <br/>Fanboy's Enhanced Tracking List<br/><br/><b>Social Widgets:</b><br/>Fanboy's Social Blocking List, <br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>Fanboy's Annoyances, <br/>AdGuard Annoyances, <br/>Web Annoyances Ultralist<br/><br/><b>Security:</b><br/>Online Malicious URL Blocklist, <br/>NoCoin Filter List
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js

---

@Chinaski1 commented on [Mon Dec 27 2021](https://github.com/AdguardTeam/AdguardForAndroid/issues/4074#issuecomment-1001532448)

`Block WebRTC` causes this issue.

**Comment by ameshkov** [comment]
This is kinda known issue, some apps rely on WebRTC and blocking it may be problematic.

We need to provide an option to disable stun/turn blocking on per-app basis to filters maintainers: https://github.com/AdguardTeam/CoreLibs/issues/1567

@sfionov would this help?
`*$stealth,app=com.whatsapp`

**Comment by ameshkov** [comment]
The issue is worse than we thought:
https://github.com/AdguardTeam/AdguardForAndroid/issues/4080

**Comment by Xophile** [comment]
Any news on this critical issue?

**Comment by ameshkov** [comment]
The patch is on the way

**Comment by Xophile** [comment]
> The patch is on the way

@ameshkov: Any ETA yet?

Many thanks!

**Comment by ameshkov** [comment]
@Xophile currently in beta channel, should be ready for stable in a couple of days.

**Comment by Xophile** [comment]
> @Xophile currently in beta channel, should be ready for stable in a couple of days.

That was quick ;)

I run the nightly builds on Android and did not see anything relating to this issue in the latest update.

**Comment by ameshkov** [comment]
@Xophile as I recall it's resolved in the nightly channel already. Do you experience any issues now?
