### ISSUE TITLE
`noeval`/`prevent-eval-if` scriptlets are not compatible with extensions (userscripts)

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1575]
Steps to reproduce:
1. Enable any userscript in app
2. Add this rule:
```
example.org#%#//scriptlet('noeval')
```
or
```
example.org#%#//scriptlet('prevent-eval-if', 'test')
```
3. Go to - https://example.org/

Userscripts are broken.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/147576063-db8a67c0-febb-46c7-a209-a5a31ded30b0.png)

</details>

Related to - https://github.com/AdguardTeam/CoreLibs/issues/1566

**Comment by ameshkov** [comment]
@sfionov just in case, this can be fixed in the userscript-wrapper by using Function.ctor instead of eval.
