### ISSUE TITLE
`$removeparam` doesn't work if request is blocked

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1580]
I guess that it may be related to this issue - https://github.com/AdguardTeam/CoreLibs/issues/1462

Steps to reproduce
1. Add these rules:
```
||example.org/1?test$removeparam=test
||example.org/*?test
```
2. Go to - https://example.org/1?test

`?test` should be removed, but it isn't when blocking rule is applied.

<hr>

If I'm not wrong, the same apply to `$cookie` modifier.
Rules:
```
||example.org/*?test
example.org#%#//scriptlet('set-cookie', 'qwerty', '1')
||example.org^$cookie=qwerty
```
Cookie is not removed.

AdGuard for Windows version 7.9 nightly 4 (build 3793, CL 1.9.5)

**Comment by Alex-302** [comment]
But why removeparam should be applied to blocked request?

**Comment by AdamWr** [comment]
Because at the end, request is not blocked at all, and other rules like `$removeparam` or `$cookie` are not applied.

![image](https://user-images.githubusercontent.com/29142494/149199799-9db9108b-d3e1-4908-9714-bea2199e5c24.png)

The real case may be some affiliate links, for example:
```
https://edipresse.hit.gemius.pl/hitredir?id=bao7_4cbOJtYBrxRn8.xCscQHZH89sejZPP4ZOgL8SX.N7&et=action&extra=OfferCount=4|BuildNumber=1448|PlacementPosition=1|Site=polki-pl|PageType=Content|ContentType=ContentVideo|ContentEcomType=C2C_Tresc_redakcyjna|PlacementType=Emisja%20BoxyP|PlacementId=5280|WidgetId=4966|WidgetType=ssr|DynamicAlgorithm=AlgorithmSiteCategoryRotator|CampaignName=Ecom_box|WidgetLayout=x4Modern|ContentName=Pierniki%20czekoladowe%20z%20nut%C4%85%20cytrus%C3%B3w|ContentId=2295|SiteCategory=Polki%2FPrzepisy%2FDesery|PlacementActivityType=OwnSiteAds|VariantAB=0|WidgetStatus=OK|ContentUrl=none|TrafficSource=none|TrafficMedium=none|TrafficContent=none|TrafficCampaign=none|TrafficTerm=none|TrafficReferral=none|OfferPosition=1|OfferType=Product|PromoFlag=0|ShowPrice=2|OfferName=Emisja%20BoxyP%20-%20Fashion%20-%20Ultra%20Ciep%C5%82a%20Czapka%20Zimowa%20z%20Pi%C4%99knym%20Splotem%21%20-%20VIKING%20-%20Bestseller%20z%20Super%20Opiniami%21|OfferId=da696003765202495289e2383c36d2e7|OfferHash=WP25028|PartnerName=Morele.net|PartnerId=2a899579e05a55f48db8a6aeda0b2614|PartnerUrl=https%3A%2F%2Fwww.skapiec.pl%2Fsite%2Fred%2F121%2F896887047%2F225498679%3F9bc018c00be76e6085045bc0e24dbb17%3D22d9d5b048eb273215ec45b166be2556%26utm_campaign%3Dapi|FeedSourceId=7e891a86ed482667f33c048eaedfbca1|FeedSourceName=skapiec|CallToAction=ZOBACZ|OfferActivityType=OwnSiteAds|OfferPrice=none|OfferPriceBefore=none|OfferPriceAlternative=Bestseller%20z%20Super%20Opiniami%21|OfferBrandName=VIKING|CategoryGroup=Fashion|PlacementHash=5280550977|EventType=OfferClick&url=https%3A%2F%2Fwww.skapiec.pl%2Fsite%2Fred%2F121%2F896887047%2F225498679%3F9bc018c00be76e6085045bc0e24dbb17%3D22d9d5b048eb273215ec45b166be2556%26utm_campaign%3Dapi
```
Request is "blocked" by Tracking protection filter, so parameters and cookies are not removed.

**Comment by Alex-302** [comment]
In dev tools request is not blocked?

**Comment by AdamWr** [comment]
In devtools `Status Code: 404` is showed, but the same happens without AdGuard and mentioned rules work fine with AdGuard 7.8

**Comment by Alex-302** [comment]
> Request is "blocked"

Ok, I got it. Not blocked in fact. AdGuard avoids blocking of main frame, but `removerapam` is not applied after loading without URL blocking(second request on screenshot)
![image](https://user-images.githubusercontent.com/8361299/149218250-277d5eac-e86a-4a6e-b2d0-e988ecbf93a0.png)

**Comment by Alex-302** [comment]
It seems no issue with another request types:
```
||api.jquery.com^$removeparam
||api.jquery.com/jquery.get/test.php?name=test
```
Execute `$.get( "test.php", { name: "test" } );` in console on https://api.jquery.com/jquery.get/

**Comment by AdamWr** [comment]
>Ok, I got it. Not blocked in fact. AdGuard avoids blocking of main frame, but removerapam is not applied after loading without URL blocking(second request on screenshot)

Yes, it was what I meant :)
And I think that in case like that, `$removeparam` and `$cookie` rules should be applied.

<hr>

> It seems no issue with another request types:
> 
> ```
> ||api.jquery.com^$removeparam
> ||api.jquery.com/jquery.get/test.php?name=test
> ```
> 
> Execute `$.get( "test.php", { name: "test" } );` in console on https://api.jquery.com/jquery.get/

Yes, in this case request is blocked, so `$removeparam` shouldn't be applied.

**Comment by sxgunchenko** [comment]
@AdamWr, I can confirm that your observations are true, and agree that it should be fixed

**Comment by ameshkov** [comment]
We could probably just make sure that `$removeparam` is applied even after the main frame was unbocked.
