### ISSUE TITLE
Adguard slow to start on boot on opening firefox and loading homepage google.co.uk

### ISSUE THREAD

**Issue by sortmyit** [AdguardTeam/CoreLibs#1581]
Hi 

I have been using Adguard 7.8 on and 8700K 24 Gig DDR4 RAM machine running windows 11 but on boot after I click open firefox it takes a long time to parse webpage and load homepage which is set to google.co.uk. Not an issue with other software if you disable or remove adguard the problem disappears. Have both the desktop application and firefox extension installed. It shows on the bottom left hand corner of firefox the webpages it is requesting and shows "Transfering data from local.adguard.org" then it goes for google.co.uk loading, so the filtering is delayed on clean boot of windows same issue regardless of Fast Startup is turn on or not on windows in control panel>power options. Adguard needs to boot up faster. Tried whether it is a dns issue separately but it isn't. Using cloudflare dns via resolving from  router, windows network adapter and also adguard windows application dns tested all have issues it is all config scenarios. 

Windows 11 21H2 22000.376
Firefox 95.0.2 64Bit
Adguard 7.8
Intel 8700K, 24Gig RAM, Intel 900p Optane SSD boot drive, Asus Z370 TUF Plus Gaming Motherboard

**Comment by Aydinv13** [comment]
@sortmyit is this issue still relevant with v7.12?

**Comment by sortmyit** [comment]
I stopped using Adguard ages ago, went to ublock origin and haven't had to look back, won't be installing adguard again, so bye
________________________________
