### ISSUE TITLE
Userscript manager in AdGuard for Windows doesn't get injected properly in websites.

### ISSUE THREAD

**Issue by wout-codes** [AdguardTeam/CoreLibs#1582]
### Steps to reproduce

1. Link: https://www.kephyr.com/popupkillertest/test/test23.html
2. Install this userscript: https://greasyfork.org/en/scripts/24473-pop-up-blocker
3. Navigate to the website in number 1. 
4. Pop-up is there. 
5. Do the same thing with Tampermonkey extension. Pop-ups are blocked.

### Expected behavior
Pop-up should have been blocked.

### Actual behavior
Pop-up is there.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/76908410/105057534-472ff000-5ab0-11eb-8241-9519eb4e0b16.png)
![image](https://user-images.githubusercontent.com/76908410/105057677-6e86bd00-5ab0-11eb-8eb4-341eb9e85fcf.png)

</details>

### Your environment

* Google Chrome Version 87.0.4280.141 (Official Build) (64-bit)
* Windows Pro Operating System v.20H2

**Comment by zubrRB** [comment]
_Mouseover Popup Image Viewer_ не увеличивает изображения в комментариях Disqus, встроенных на сторонних сайтах. 
Однако увеличивает в комментариях ленты на страницах собственного профиля: https://disqus.com/home/comments/
Эта проблема также отсутствует при использовании данного юзерскрипта в Tampermonkey. https://github.com/tophf/mpiv/issues/89
