### ISSUE TITLE
Redirect driver mode isn't compatible with Shadowsocks-libev

### ISSUE THREAD

**Issue by userbody** [AdguardTeam/CoreLibs#1583]
Конкретно и сильно поломали драйвер перенаправления.
Я использую shadowsocks-libev websocket TLS (v2ray).
Использую браузер Firefox крайней версии на 18.12.2021.
Лицензионный Windows 10 с крайними обновлениями на 18.12.2021.

Проблема: 
При включенной настройке Proxy, в Windows 10 пропадает интернет во всех браузерах кроме Firefox.
![1212](https://user-images.githubusercontent.com/59291386/146655305-23006591-da1e-4158-8581-ae6b8d87d5a9.JPG)

![photo_2021-12-18_22-36-18](https://user-images.githubusercontent.com/59291386/146655185-968e4bdd-a7e2-43cd-be7f-11346d4b4557.jpg)

**Comment by Aydinv13** [comment]
Используете ли вы Докер? Может ли быть проблема в нем?

**Comment by Aydinv13** [comment]
Уточните, пожалуйста, в какой версии у вас начались эти проблемы? Помогает ли отключение/включение Фильтрования локальных адресов? При отключении драйвера перенаправления доступ к интернету появляется?

**Comment by userbody** [comment]
Нет, докер не использую.

пн, 17 янв. 2022 г., 16:07 Aydin Baydarov ***@***.***>:

**Comment by userbody** [comment]
Проблема полностью исчезает когда я отключаю
[image: изображение.png]
Вроде как проблема появилась в версии 7.2 или 7.3

Если у вас осталась версия 7.1 или 7, было бы здорово откатиться!

пн, 17 янв. 2022 г. в 16:13, Aydin Baydarov ***@***.***>:

**Comment by ngorskikh** [comment]
@userbody Здравствуйте.
У вас точно на `[::1]:1080` слушает `ss-local`?
```
Error connecting to [::1]:1080. Error: 10061(No connection could be made because the target machine actively refused it.)
```
Нам рефьюзят все соединения, мы тут бессильны 🙃 

Кстати, я попробовал этот shadowsocks-libev, на моей машинее если `ss-local` слушает на IPv6, то тоже ничего не работает, _без адгарда_:
```
2022-01-17 17:25:36 ERROR: getpeername: [10057] A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied.
```

Попробуйте использовать `ss-local` через IPv4.

**Comment by userbody** [comment]
Нашел решение проблемы
[image: изображение.png]
В этом случае, всё работает!
В случае если указано
[image: изображение.png]
*ИЛИ*
[image: изображение.png]
Проблема возобновляется.

пн, 17 янв. 2022 г. в 17:32, Nikita Gorskikh ***@***.***>:

**Comment by ngorskikh** [comment]
@userbody Ваши приложенные изображения не видно.

**Comment by userbody** [comment]
В сути проблема найдена.
"isIPv6Enabled": true, Полностью решает проблему!
Но в firefox приходится указывать уже не 127.0.0.1 а *::1*
Раньше всё хорошо работало с 127.0.0.1... Жаль

пн, 17 янв. 2022 г. в 18:05, Nikita Gorskikh ***@***.***>:
