### ISSUE TITLE
If $generichide exclusion is already in the filter list, cannot apply another document-level exclusions

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1587]
For example, some site is broken by AdGaurd extension. But filters contain `@@||example.com^$generichide`
In this case `@@||example.com^$extenstion` or `@@||example.com^$generichide,extension` added to user filter does nothing.
Should `@@||example.com^$extenstion` and `@@||example.com^$generichide` be internally combined to `@@||example.com^$generichide,extension`?

**Comment by sfionov** [comment]
@Alex-302 Currently only one basic rule is matched for request (by design).
You may use:
```
@@||example.com^$generichide,badfilter
@@||example.com^$extension,badfilter
@@||example.com^$generichide,extension
```

**Comment by Alex-302** [comment]
It is not obvious for users.

**Comment by ameshkov** [comment]
Hmm, when parsing filters, we probably could combine different document-level exceptions into a single rule, but this is a rather breaking change.

**Comment by sxgunchenko** [comment]
I think it would be better to allow matching several rules with the same priority instead of combining them.
For example, matching several basic rules would allow matching `@@||example.com^$generichide` and `@@||example.*^$extension` against a single request

**Comment by ameshkov** [comment]
Also possible, but this will be even a more breaking change:)

**Comment by sxgunchenko** [comment]
That's for sure :)
