### ISSUE TITLE
Some userscripts do not work due to Content Security Policy

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1589]
Steps to reproduce:
1. Add this userscript - https://github.com/AdguardTeam/Userscripts/blob/master/extendedCssDebugger/extended-css.debugger.user.js
2. Navigate to - https://blog.disqus.com/most-popular-food-website-minimalist-baker

There is an error from `disqus.com/embed/comments/`:
```
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src https:".
```

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/151339325-83244af6-bcca-4213-97b5-9afefb527df7.png)

</details>

AdGuard for Windows version 7.9 nightly 7 (build 3802, CL 1.9.20)

By the way, it seems that this error doesn't occur in stable version (though userscript still doesn't work), here - `https://blog.disqus.com/most-popular-food-website-minimalist-baker`, but it still occurs on `https://disqus.com/embed/comments/`, so I'm not sure if it's a bug.

It's probably due to this script:
```
var d = document;
var toH = d.head.appendChild.bind(d.head);
var m = d.createElement('meta');
m.setAttribute('http-equiv', 'Content-Security-Policy');
m.setAttribute('content', "script-src https:;");
toH(m);
```

**Comment by zubrRB** [comment]
У меня аналогично не работает скрипт Mouseover Popup Image Viewer по ссылке Адама в официальном блоге Disqus, а также при наведении курсора на изображения во встроенных комментариях на сторонних сайтах. https://github.com/AdguardTeam/CoreLibs/issues/1582#issuecomment-1014360324

**Comment by AdamWr** [comment]
It seems that adding:
```
// @run-at document-start
```
to userscript fixes this issue (at least in nigthly build).

**Comment by ameshkov** [comment]
@sfionov @sxgunchenko could you please take a look?

**Comment by zubrRB** [comment]
MPIV developer @tophf removed the exception from it, after which the script worked in the Disqus blog, but the script still does not work in the Disqus comments, even on the Disqus blog itself.

**Comment by ngorskikh** [comment]
I don't think anything can be done by CoreLibs here. We're already patching the CSP headers and `<meta>` tags. However, in this case, a more restrictive policy is added by a script after the page is loaded.
@AdamWr 's workaround seems appropriate:
>```
>// @run-at document-start
>```

**Comment by ameshkov** [comment]
The alternative would be for the userscript to intercept `document.createElement` call and not allow adding new `<meta>` elements dynamically
