### ISSUE TITLE
CSP errors on sport365.live

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#159]
Choose any available stream and check browser's console after a while, a lot of errors and playback stops after a while then.

Thread: https://forum.adguard.com/index.php?threads/http-www-sport365-live.26088/

The problem is caused by the way we process requests to the `sport365.tech` domain -- we're getting 406 responses.

Temporary solution is to disable HTTPS filtering for the `sport365.tech` domain.

**Comment by 0100101000101** [comment]
Whitelist sport365.tech domain in HTTPS filter is not working for me.
