### ISSUE TITLE
Rules with `$all` modifier do not work in some cases

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1590]
Maybe related to this - https://github.com/AdguardTeam/CoreLibs/issues/1531

### Steps to reproduce
1. Add this rule:
```
||iana.org^$all
```
2. Go to - https://www.iana.org/

### Expected behavior
There should be a message that website was blocked.

### Actual behavior
Main document is not blocked, but requests are blocked.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/151708141-c82e0327-61d7-489c-a8f2-df5990b30c45.png)

</details>

<hr>

On https://example.org/ it works fine.
```
||example.org^$all
```

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/151708356-320fa5d9-1b62-4dda-8690-c189e524dafc.png)

</details>

AdGuard for Windows version 7.9 nightly 7 (build 3802, CL 1.9.20)

**Comment by sxgunchenko** [comment]
@AdamWr are you sure that the request is matched by the rule? Could you please reproduce it and check if the request to iana.org bypasses filtering for some reason?

**Comment by AdamWr** [comment]
I can't reproduce this issue on `iana.org` with latest nightly build (7.9 nightly 8 (build 3812, CL 1.9.20)).

According to my screenshot from first post, requests were matched by rule:
![image](https://user-images.githubusercontent.com/29142494/151947672-a1c8b492-c7ae-49ec-bf3e-432f181cbda3.png)

But I still can reproduce it on another websites like:
[https://lenta.ru/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://lenta.ru/)
or
[https://cdaction.pl/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://cdaction.pl/)

Rules:
```
||lenta.ru^$all
||cdaction.pl^$all
```

![image](https://user-images.githubusercontent.com/29142494/151948484-5bf6daae-cb1b-405d-bf9a-e78025243dcc.png)

![image](https://user-images.githubusercontent.com/29142494/151948544-2210bcda-3dc3-4792-aeab-0e0b400ed08d.png)

**Comment by AdamWr** [comment]
Okay, I think that I found a culprit of this issue.
It looks like that issue occurs when this filter list is added to filters - https://hole.cert.pl/domains/domains_adblock.txt

**Comment by krystian3w** [comment]
I recomended change `^` to `^$all` for better support strict-block prompts.

If this need revert on NASK level then try write on wykop on by mail.
