### ISSUE TITLE
Add empty path 

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/CoreLibs#1591]
Guys, please implement empty `$path` that will allow to limit the rule only on the main page.
`[$domain=example.com,path]##body` - has to apply on the `example.com`, but not on the `example.com/news/`.
For now, this rule is inconvenient for frequent creation of such rules
```
[$domain=example.com,path=/^\/$/]##body
```

**Comment by XX-J** [comment]
Добавленный пустой `path` работает некорректно.

 Для примера возьмём яндекс. Мой указатель на главную страницу выглядит следующим образом: `[$domain=yandex.*,path=/^(\/(\[?&\]\[^/\]*)?)?$/]##.desk-notif-card_animated_yes`. Он срабатывает на главной как с завершающим слэшем, так и без оного; как с доп. параметрами после завершающего слэша, так и без них.

 Когда переходишь на [https://yandex.com](https://href.li/?https://yandex.com) из русскоязычного сегмента интернета адрес меняется на [https://yandex.ru/?com=1](https://href.li/?https://yandex.ru/?com=1) (отличается от адреса без параметров наличием ссылки на yandex.com в правой, верхней части страницы), а потом окончание адреса `/?com=1` пропадает.

 В вышеизложенном примере правило `[$domain=yandex.*,path=/^(\/(\[?&\]\[^/\]*)?)?$/]##.desk-notif-card_animated_yes` - срабатывает, скрывая справа анимированную плашку статистики по Коронавирусу, а правило `[$domain=yandex.*,path]##.desk-notif-card_animated_yes` - нет (только после перезагрузки страницы).
<br>

----------
 AdGuard v4.1.1 &nbsp; | &nbsp; FireFox v78.13 ESR &nbsp; | &nbsp; Win7SP1
