### ISSUE TITLE
glastonburyrepublicans.org - ERR_HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1592]
Steps to reproduce
1. Go to - [https://glastonburyrepublicans.org/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fglastonburyrepublicans.org%2F)

Website doesn't open.

```
This site can’t be reached
The web page at https://glastonburyrepublicans.org/ might be temporarily down or it may have moved permanently to a new web address.
ERR_HTTP2_PROTOCOL_ERROR
```

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/153588899-cac6e838-444a-4735-91bf-52bee6ac5b57.png)

</details>

It works fine with AdGuard disabled.

AdGuard for Windows version 7.9 nightly 11 (build 3833, CL 1.9.29)

**Comment by ngorskikh** [comment]
@AdamWr I was able to reproduce this bug for a very short time, but as soon as I fired up the tools to try and debug it, it magically fixed itself, and I can't get it to reproduce any longer :harold:
If it is still reproducing for you, can you please record logs (run AdGuard with `/trace` command line argument and enable debug logging level in the settings)?

**Comment by AdamWr** [comment]
Yes, I can still reproduce it on Android and Windows. I will send you logs in private message.
