### ISSUE TITLE
$popup rule blocks URLs on macOS

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1594]
Oroginal issue: https://forum.adguard.com/index.php?threads/streamsb-and-xstreamcdn.46253/

Caused by(it may be changed):
```
$popup,third-party,domain=animeworld.biz|apl100.me|apl102.me|apl96.me|assia2.com|cloudvideo.tv|databasegdriveplayer.xyz|dir-proxy.net|dirproxy.info|dood.ws|fembed-hd.com|file-upload.com|freeplayervideo.com|geoip.redirect-ads.com|highstream.tv|livetv498.me|loader.to|mangovideo.pw|mixdrop.bz|mixdrop.ch|mixdrop.co|mixdrop.to|myflixer.to|mystream.to|oneproxy.org|piracyproxy.biz|piraproxy.info|play.hydracdn.network|playtube.ws|pouvideo.cc|projectfreetv2.com|sbplay2.com|scloud.online|stape.fun|stape.me|streamas.cloud|streamlare.com|streamon.to|streamta.pe|streamtape.com|strtape.cloud|strtpe.link|supervideo.tv|uproxy.best|uproxy.co|upstream.to|userload.co|vidcloud9.com|videovard.sx|vidlox.me|vivo.sx|voe.sx|vupload.com|watchsb.com|wiztube.xyz|youtubedownloader.sh|ytmp3.sh
```

Not reproduced in Windows in Chrome.

Reproduced in Safari. AdGuard for Mac 4.7.1.1108

Steps to reproduce:

Select player 3-5 on https://www3.gogoanime.cm/gintama-episode-200

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/154459009-10098bfb-5327-4ce5-b10b-58cd73645147.png)

</details>

Disable these rules in Base filter before checking:
```
$popup,third-party,domain=fembed-hd.com,badfilter
$popup,third-party,domain=sbplay2.com,badfilter
$popup,third-party,domain=dood.ws,badfilter
```
Please mention `@AdguardTeam/filters-maintainers` when it will be fixed.

**Comment by sfionov** [comment]
@Alex-302 We can't determine xmlhttprequests in Safari, so some loaded HTML code turns into the blocking page. In this case, there is little we can do.

Anyway you can try to whitelist some urls on this domain intead of disabling $popups.

**Comment by Alex-302** [comment]
That rule is from foreign filter.
