### ISSUE TITLE
`Remove X-Client-Data header from HTTP requests` isn't working properly

### ISSUE THREAD

**Issue by Aydinv13** [AdguardTeam/CoreLibs#1595]
### Steps to reproduce

1. Install the latest build
2. Enable Stealth mode
3. Open Chrome (not incognito mode) and DevTools (Network tab)
4. Visit google.com and check DevTools

### Expected behavior

The header X-Client-Data is removed
### Actual behavior

Seems that AdGuard doesn't remove it correctly. Judging for logs this option is ON and it works but X-Client- Data header is not removed.

Screenshot
https://uploads.adguard.com/up85_9cqd7.png

**Comment by sfionov** [comment]
We can't do anything with how browser shows requests, even if they modified by AdGuard.

AdGuard works on network level.
