### ISSUE TITLE
first param will not be removed if it is appended with & instead of ?

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/CoreLibs#1600]
See https://github.com/uBlockOrigin/uBlock-issues/discussions/2019 , AG (at least extension) suffers the same. Related: https://github.com/AdguardTeam/AdguardFilters/issues/111536

**Comment by uBlock-user** [comment]
`&` is used for appending queries after the first url query which begins with `?`.

**Comment by Yuki2718** [comment]
> `&` is used for appending additional queries after the first url query which begins with `?`.

This is the thing, query must start from `?` and hence the reported URL doesn't include query. Closing as I think there's no valid reason to remove this.
