### ISSUE TITLE
Issue with stealth mode relying on "console"

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1603]
Related to - https://github.com/AdguardTeam/AdguardFilters/issues/112161
It seems that now Stealth mode is using `console.log` to log some informations about iframes (if I'm not wrong).

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/157212876-1430e106-9671-43e3-9742-842a5e44f04f.png)

</details>

The problem is that if website uses `delete` operator (`delete console`) then it may breaks reCAPTCHA.

Steps to reproduce:
1. Enable stealth mode
2. Add this rule to user rules:
```
recaptcha-demo.appspot.com#%#delete console;
```
3. Go to - https://recaptcha-demo.appspot.com/recaptcha-v2-checkbox.php
4. Try to resolve captcha

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/157213820-0334e6e7-4b4d-4ff0-848e-55913cedbf5c.png)

</details>

reCAPTCHA works correctly if stealth mode is disabled, even if rule from second point is added to user rules.

**Comment by ameshkov** [comment]
Nice bug, thank you!
