### ISSUE TITLE
Rules with `:where()` pseudo class are rejected

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1609]
Steps to reproduce
1. Add this rule:
```
example.org##div > :where(h1, p)
```
https://developer.mozilla.org/en-US/docs/Web/CSS/:where

2. Go to - https://example.org/

`div > h1` and `div > p` should be hidden, but rule is rejected.

```
cssfilter: cssfilter_addrule(): Rule is not valid, ignoring it (example.org##div > :where(h1, p))
AGProxyFilter: Rule rejected by all filters: example.org##div > :where(h1, p)
```

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/157828540-cad21084-6237-49ea-b818-d44232d34ec1.png)

</details>

**Comment by ameshkov** [comment]
@AdamWr is it okay in the browser extension?

**Comment by AdamWr** [comment]
No, it isn't.
Reported here - https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1998
