### ISSUE TITLE
Rules with "$" in path don't work

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#161]
For example on this website - `http://axistrivia.altervista.org/` rule like this:
`||axistrivia.altervista.org/$file/` doesn't work.
Another website - `http://www.batsa.co.za/`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/34733174-be4a02f4-f567-11e7-941d-58addb4e1bb6.png)

</details>
<br>

AdGuard for Windows 6.2.437.2171

**EDIT (by @ameshkov):**
We should either change the way the modifiers are parsed OR we should introduce a way of escaping the `$` character. Depends on how many such rules are in the popular filters subscriptions.

**Comment by ameshkov** [comment]
More examples:
https://github.com/AdguardTeam/AdguardForWindows/issues/2096

**Comment by Alex-302** [comment]
Another example with the rules
<details>

```
||kopp-verlag.de/$WS/
```
Is it valid or invalid rule?

Sample URL:
```
https://www.kopp-verlag.de/$WS/ws-logo.gif
```

This rule works in app and extension:
```
||kopp-verlag.de/$WS/ws-logo.gif$image
```
without modifier it does not work:
```
||kopp-verlag.de/$WS/ws-logo.gif
```


</details>
