### ISSUE TITLE
Cannot load boosty.to

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1611]
@adguard-bot commented on [Wed Feb 02 2022](https://github.com/AdguardTeam/AdguardFilters/issues/109150)

### Issue URL (Incorrect Blocking)
[NSFW] [https://boosty.to/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fboosty.to%2F)
### Comment
Username: @yastrebilya2018
> Сайт безопасен.
> Это сайт для продвижения творчества авторов контента.
> В процессе поиска проблемы я выяснил, что если отключить параметры фильтрации в разделе сеть, то проблема исчезнет.
> Второй скриншот показывает главную страницу сайта.
> Это потому, что я не буду делать скрин.
> так как при включении фильтрации сайт просто не открывается, и отображается вкладка google.
> О проблеме я сообщал в поддержку. обращение номер 575202.
> Входе уточнений мы выяснили, что если отключить Фильтрацию трафика и сетевой wfp драйвер, то сайт откроется.
> Так же можно ничего не отключать, а просто отключить защиту через браузерный помощник, но это если сайт нужен, а его блокируют справедливо!
> Мне нужно, чтобы вы исправили эту проблему, так как сайт безопасен, И его блокировка происходит из за фильтрации.
> Так же прошу улучшить adguard фильтры так, чтобы через браузерный помощник показывалось увидомление, что сайт заблокирован.
> В настоящие время это не происходит, и сайты заблокированные таким образом просто не открываются.
> на экране отображается просто вкладка, как-будто ничего не происходит!
> Надеюсь, что вы устраните эту проблему и усовершенствуете миханизм, чтобы можно было сразу сообщить о ложной фильтрации.

### [NSFW] Screenshots
<details>
  <summary>Screenshot 1</summary>

  [Screenshot 1](https://reports-img.adguard.com/liyCDHq.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  [Screenshot 2](https://reports-img.adguard.com/JNs7bUp.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.8
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Self-destructing third-party cookies (180), <br>Disable cache for third-party requests, <br>Block WebRTC, <br>Block Push API, <br>Block Location API, <br>Block Flash, <br>Hide your Referrer from third-parties (0), <br>Hide your User-Agent (0), <br>Hide your IP address (0)
DNS filtering: | server: `https://dns.adguard.com/dns-query`<br>
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js,<br>https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js,<br>https://userscripts.adtidy.org/release/adguard-wot/1.0/wot.user.js
Other extensions used: | Все стандартные расшерения и расширение Web of Trust.

---

@jellizaveta commented on [Tue Feb 15 2022](https://github.com/AdguardTeam/AdguardFilters/issues/109150#issuecomment-1040031208)

У меня не повторяется. @AdguardTeam/filters-maintainers посмотрите у себя, пожалуйста. 

---

@yastrebilya2018 commented on [Tue Feb 22 2022](https://github.com/AdguardTeam/AdguardFilters/issues/109150#issuecomment-1047938509)

Hello!
I understand why the request was closed.
My letter was not published in this thread.
in a letter from you it was said that I can answer the topic directly in the mail.
but in all likelihood my comment was not delivered.
I wrote the following:
Hello!
It should work!
Maybe you forgot to enable dns?
filtration type full. adguard dns provider

Date of sending the message 15.02.
I confirm that the problem is still relevant, and if you disable filtering and dns, then the site will work.

---

@jellizaveta commented on [Fri Feb 25 2022](https://github.com/AdguardTeam/AdguardFilters/issues/109150#issuecomment-1050827561)

@yastrebilya2018 Hello! Cannot reproduce with enabled dns. Please, try to check filter log and tell us what causes an issue.

---

@yastrebilya2018 commented on [Sun Feb 27 2022](https://github.com/AdguardTeam/AdguardFilters/issues/109150#issuecomment-1053529922)

Hello!
I'm talking not only about filtering through the adguard dns server, but also the filtering parameters
in the network/ filtering section.
Due to problems with the adguard application, I will be able to provide you with an accurate answer only when I get a response from the support service on request
580897.
There are problems with blockers now.
"Connection error".
And all the time they offer to send a bug report, which I have already done!
But I strongly recommend enabling full filtering in settings/network/filtering.
Activate all the filtering parameters, and try to log in via Google to the site.
If the problem persists, give instructions on how to find the filtering logs and provide them to you.
Thanks!

---

@Alex-302 commented on [Tue Mar 01 2022](https://github.com/AdguardTeam/AdguardFilters/issues/109150#issuecomment-1055424532)

@jellizaveta 

---

Cannot open without AdGuard.
![image](https://user-images.githubusercontent.com/8361299/156174245-5777c12a-fc48-486b-935e-4a0fe41c6fc9.png)

---

@yastrebilya2018 commented on [Tue Mar 01 2022](https://github.com/AdguardTeam/AdguardFilters/issues/109150#issuecomment-1055821202)

I'm sorry, but my adguard hasn't been working for a week now.
Experts have not yet responded to the request.
I also sent reports.
The update of the program and filters does not work, and ad blocking is everywhere.

---

@Alex-302 commented on [Wed Mar 09 2022](https://github.com/AdguardTeam/AdguardFilters/issues/109150#issuecomment-1062854779)

> The update of the program and filters does not work, and ad blocking is everywhere.

Please try to reinstall AdGuard.

---

@yastrebilya2018 commented on [Wed Mar 09 2022](https://github.com/AdguardTeam/AdguardFilters/issues/109150#issuecomment-1062996093)

After reinstalling the application, the problem disappeared.
I deleted the settings app!
After installing again, I found that the site continues to be blocked.
After reinstalling the application, the problem disappeared.
I deleted the settings app!
After installing again, the application works again!
Now back to this problem.
 I found that the site continues to be blocked.
I have exported the filter log data.
Got this file:
20220309_adguard_filtering_log_records.json
How can I send it to you?

**Comment by Alex-302** [comment]
@yastrebilya2018 You can send logs to support@adguard.com But it seems this is not required, issue can be reproduced easily.

**Comment by ngorskikh** [comment]
The issue is that the site returns `204 No Content` when request has an `X-Forwarded-For` header with any value. That header is added because the `Hide your IP address` is enabled.

There are two possible ways to work around this:
1. Disable `Hide your IP address`, or
2. Add `@@||boosty.to$stealth` to the user filter. *Warning*: this will disable all stealthmode features for `boosty.to` and its subdomains.

There's a [task](https://github.com/AdguardTeam/CoreLibs/issues/1504) to allow `$stealth` exception rules to specify which stealth features to disable. As soon as it's done, it will be possible to just disable the `Hide your IP address` option for a specific website.

**Comment by sxgunchenko** [comment]
> There's a [task](https://github.com/AdguardTeam/CoreLibs/issues/1224) to allow `$stealth` exception rules to specify which stealth features to disable. As soon as it's done, it will be possible to just disable the `Hide your IP address` option for a specific website.

It seems like you linked the wrong task, here's the right one https://github.com/AdguardTeam/CoreLibs/issues/1224

**Comment by yastrebilya2018** [comment]
It's a good idea to disable the ip address hiding feature for a specific  @@site.


@ @sxgunchenko
@ @нгорских
