### ISSUE TITLE
Compact/compresesed hosts File compatibility?

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/CoreLibs#1613]
_N.B.: I'm not sure if this is the right place to ask this._ **Please** _move as you see fit._

Do the various AG products handle `hosts` file compacting (usually called "compression" which seems like wrong terminology), such as that performed by https://github.com/ScriptTiger/Hosts-Conversions?  _(For that matter, can they handle **actual** `hosts`/filterlist compression, like gzip, zip, 7z, &c?)_ There's some discussion that this will need to be done on some _very_ large adblocking lists due to various problems elseplace ([OS issues](https://github.com/StevenBlack/hosts/issues/1853#issuecomment-1069702868), browser storage restrictions, &c), so I thought to ask.

**Comment by ngorskikh** [comment]
AdGuard supports `hosts`-file syntax only in DNS blocklists, and any valid hosts file should work there. If that is not the actually the case, please file an issue [here](https://github.com/AdguardTeam/DnsLibs/issues).
Regarding filter lists compression, there's little point in supporting it for AdGuard, since our apps are bound only by the amount of storage and RAM.

**Comment by TPS** [comment]
@ngorskikh The major reason I asked re: support for such is for a subscription for such from a 3rd party, so, if the (`hosts`|filterlist) file is _served_ in 1 or more of the above ways (e.g., 9-hosts-per-line compacted _&_ gzipped), would that be _directly_ supported?

**Comment by sfionov** [comment]
1. "Compacted" hosts files are valid hosts files, so they are supported.

2. We don't support loading of gzipped files.

DNS filter lists are not loaded into memory. We rely on reads from disk cache. If decompress them, they will take place in memory, which is not acceptable, e.g. on iOS with hard memory limit for network extensions.

**Comment by TPS** [comment]
Thanks very much for the clarification! 🙇🏾‍♂️

**Comment by TPS** [comment]
Another question related to this:  Would there be any advantage/disadvantage to AG apps in using these compacted forms?  Or do they resolve to the same representation internally as the equivalent uncompacted file?

**Comment by ameshkov** [comment]
Pretty much the same for AdGuard

**Comment by TPS** [comment]
Again, thanks very much.
