### ISSUE TITLE
Browser Assistant does not see the new site certificate

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1619]
@zubrRB commented on [Wed Apr 06 2022](https://github.com/AdguardTeam/BrowserAssistant/issues/68)

Срок действия сертификата сайта истёк, после чего он был продлён.  Но браузерный помощник спустя пять часов после этого смог увидеть новый сертификат только после перезапуска защиты (выключение/включение) в AdGuard для Windows. Неоднократный перезапуск браузера Chrome 100 и полная очистка в нём кеша не смогли исправить ситуацию.

![cert](https://user-images.githubusercontent.com/50718960/161919205-bdb23779-96e1-4240-b266-38f712689e33.png) ![cert2](https://user-images.githubusercontent.com/50718960/161919210-754a7504-306d-4f70-ae3e-356f8c52beae.png)

**Comment by sfionov** [comment]
Another case (link to discussion is in internal task tracker)

![image](https://user-images.githubusercontent.com/47204/161943684-c007127b-fcbe-4c9a-88f6-cbd2e829abe9.png)

**Comment by zubrRB** [comment]
А в чём разница между двумя этими сайтами, оба из которых находятся в HTTPS исключениях? 
У сайта МИДа жёлтый замок и обе опции HTTPS-фильтрации согласуются, а у банка зелёный и некое противоречие.  

![mid](https://user-images.githubusercontent.com/50718960/162478900-1b7690b0-09dc-4921-aca9-ad2e9f1b8d10.png) ![bank](https://user-images.githubusercontent.com/50718960/162480914-006d7ecf-2b46-4cdc-a78a-168534795b46.png)

**Comment by zubrRB** [comment]
У мидовского Extended Validation SSL (EV), а у меня по дефолту стоит опция фильтрации сайтов с такими сертификатами.

**Comment by zubrRB** [comment]
Ситуация с правым скриншотом выше (на сайте банка) возникает из-за того, что в HttpsExclusions ранее был добавлен `sber-bank.by`, а теперь банк использует в адресе префикс `www`. Но сертификат сайта банка все равно не подменяется.

**Comment by zubrRB** [comment]
Вчера снова истёк сертификат того же сайта, но теперь браузерный помощник показывает то одно, то другое... 

![2022-10-04_111855](https://user-images.githubusercontent.com/50718960/193771588-eb46c417-d128-4e66-9bc5-d141bf217dd6.gif) ![2022-10-04_112105](https://user-images.githubusercontent.com/50718960/193771600-bc65c22c-9fd4-4d82-b7b3-9293e18a3c2b.gif)
