### ISSUE TITLE
forum.pclab.pl - Website doesn't always loads

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1622]
@adguard-bot commented on [Mon Apr 18 2022](https://github.com/AdguardTeam/AdguardFilters/issues/115884)

### Issue URL (Incorrect Blocking)
 [http://forum.pclab.pl](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fforum.pclab.pl)
### Comment
Username: @the4anoni
> Website doesn't always loads when adguard is enabled, sometimes it stucks like on picture.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/Yt7anqS.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/LxmR9FE.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 12
AdGuard product: | AdGuard for Android v4.0 nightly 34 (75)
Browser: | Vivaldi
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode options: | Self-destructing third-party cookies (0)
DNS filtering: | server: `System`<br>filters: `https://filters.adtidy.org/android/filters/15_optimized.txt, DnsUserRules`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>Fanboy's Anti-Facebook List, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>Fanboy's Annoyances, <br/>AdGuard Annoyances, <br/>I don't care about cookies<br/><br/><b>Security:</b><br/>NoCoin Filter List<br/><br/><b>Language-specific:</b><br/>AlleBlock, <br/>Polish Annoyances Filters, <br/>Polish Anti-Annoying Special Supplement, <br/>Polish GDPR-Cookies Filters, <br/>Polish Social Filters, <br/>EasyList Polish, <br/>Polish Anti Adblock Filters, <br/>Official Polish filters for AdBlock, uBlock Origin & AdGuard
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js,<br>https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.meta.js,<br>https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/polish_ads_wp.user.js

**Comment by Alex-302** [comment]
@the4anoni I can't reproduce. Please collect debug logs and write when it happens
https://kb.adguard.com/en/android/solving-problems/log#collecting-debug-log

**Comment by the4anoni** [comment]
> @the4anoni I can't reproduce. Please collect debug logs and write when it happens https://kb.adguard.com/en/android/solving-problems/log#collecting-debug-log

I've sent logs via app.

**Comment by maxikuzmin** [comment]
@the4anoni issue is in the works. Tell me, is this issue still relevant? Is the site not working?

**Comment by the4anoni** [comment]
> @the4anoni issue is in the works. Tell me, is this issue still relevant? Is the site not working?

Yes, issue is still there.

**Comment by maxikuzmin** [comment]
@the4anoni issue at work
