### ISSUE TITLE
Make `$stealth` exceptions applicable to "Protect from DPI"

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1623]
@adguard-bot commented on [Thu Apr 21 2022](https://github.com/AdguardTeam/AdguardFilters/issues/116164)

### Issue URL (Incorrect Blocking)
 [https://www.ghxi.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.ghxi.com)
### Comment
> Protect from DPI will make the website fruit core peeling website (https://www.ghxi.com) unable to open.
> 
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/sTGB0fQ.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/sTGB0fQ.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 10
AdGuard product: | AdGuard for Android v4.0 nightly 34 (75)
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Block third-party Authorization header, <br>Disable cache for third-party requests, <br>Block WebRTC, <br>Block Push API, <br>Block Location API, <br>Block Flash, <br>Block Java
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>EasyList, <br/>AdGuard Mobile Ads, <br/>Peter Lowe's Blocklist<br/><br/><b>Privacy:</b><br/>Legitimate URL Shortener, <br/>AdGuard Tracking Protection, <br/>Fanboy's Enhanced Tracking List, <br/>AdGuard URL Tracking, <br/>EasyPrivacy<br/><br/><b>Social Widgets:</b><br/>Fanboy's Social Blocking List, <br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>Adblock Warning Removal List, <br/>Web Annoyances Ultralist, <br/>Dandelion Sprout's Annoyances List, <br/>Fanboy's Annoyances, <br/>EasyList Cookie List, <br/>AdGuard Annoyances, <br/>I don't care about cookies<br/><br/><b>Security:</b><br/>Online Malicious URL Blocklist, <br/>NoCoin Filter List<br/><br/><b>Other:</b><br/>AdGuard DNS, <br/>AdGuard Experimental<br/><br/><b>Language-specific:</b><br/>CJX's Annoyances List, <br/>AdGuard Japanese
Custom filters: | https://hacamer.coding.net/p/adgurd/d/adrules/git/raw/main/rules-admin.txt,<br>
Userscripts: | https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.meta.js,<br>https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js

**Comment by sfionov** [comment]
We'll try to make domain-wide $stealth-exceptions appliable to "Protect from DPI"

**Comment by sfionov** [comment]
Some discussion about this task: https://github.com/AdguardTeam/CoreLibs/issues/1615#issuecomment-1115094408

**Comment by AdamWr** [comment]
Probably another website broken by DPI - https://github.com/AdguardTeam/AdguardFilters/issues/117219
[http://go.gov.il](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fgo.gov.il)
But I cannot reproduce it.

**Comment by zubrRB** [comment]
I reproduced with an Israeli ip-address through a VPN. The only difference is that there is a redirect from http://go.gov.il to https://go.gov.il, after which it issues `ERR_CONNECTION_RESET`.
After disabling the option `Protect from DPI` or under the ip-address of another country, there is a redirect to the site https://www.gov.il/, which opens.

**Comment by AdamWr** [comment]
One more website broken by `Protect from DPI` - https://github.com/AdguardTeam/AdguardFilters/issues/118185
Link - [https://www.thegioididong.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.thegioididong.com%2F)

And question from the user:
```
Can you explain what's going on if I enable Protect from DPI that make website load incorrect?
```

**Comment by sfionov** [comment]
Made new task with list: https://github.com/AdguardTeam/CoreLibs/issues/1645
