### ISSUE TITLE
Browser Assistant is sensitive to the `www` prefix in HTTPS Exceptions

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/CoreLibs#1624]
Имеются два сайта, по умолчанию прописанных в HTTPS-исключениях, для которых выдаются разные цветовые схемы.
В https-исключениях изначально прописан без указания префикса `sber-bank.by`, который затем стал использовать банк.  
При этом сертификат сайта не подменяется вне зависимости от того, прописан в исключениях префикс `www` или нет. 
Однако для браузерного помощника этот момент оказывается чувствителен, ибо передвинув в неактивное состояние ползунок https-фильтрации: в https-исключения автоматически добавляется `www.sber-bank.by`, а цвет замка – жёлтый.    

![mid](https://user-images.githubusercontent.com/50718960/162478900-1b7690b0-09dc-4921-aca9-ad2e9f1b8d10.png) ![bank](https://user-images.githubusercontent.com/50718960/162480914-006d7ecf-2b46-4cdc-a78a-168534795b46.png)

**Comment by sfionov** [comment]
@zubrRB Подскажите, какая у вас операционная система/браузер?

**Comment by sfionov** [comment]
Проблема подтверждена с нашей стороны

**Comment by sfionov** [comment]
Проблема подтверждена с нашей стороны

**Comment by sfionov** [comment]
Задача разделена на две - для macOS и Windows - проблема не в корлибсах.
