### ISSUE TITLE
gosuslugi.ru cannot be opened with 'Protect from DPI' enabled

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/CoreLibs#1636]
https://github.com/AdguardTeam/AdguardFilters/issues/116590#issuecomment-1120868914
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/167787660-752e84e6-2c32-43f5-adea-99b3780c7478.png)

</details><br/>

**Comment by zubrRB** [comment]
В профильной ветке: https://github.com/AdguardTeam/CoreLibs/issues/1615#issuecomment-1113466251
