### ISSUE TITLE
Ad isn't blocked with Brook 

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1641]
@adguard-bot commented on [Mon Apr 18 2022](https://github.com/AdguardTeam/AdguardFilters/issues/115898)

### Issue URL (Ads)
 [https://nbyts.online/best-video-editing-software-for-youtube](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fnbyts.online%2Fbest-video-editing-software-for-youtube)
### Comment
Username: @khafan11
> i use this client and vpn protocol 
> https://github.com/txthinking/brook
> 
> and none of ads are blocked in anysite 
> but when i use another vpn its working fine 
> Brook use Socks5 local:1080 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/S7XebyJ.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.9.1
Browser: | Firefox
AdGuard driver: | WFP
Stealth mode: | disabled
DNS filtering: | server: `https://dns.cloudflare.com/dns-query`<br>filters: `User rules`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Other:</b><br/>AdGuard Experimental<br/><br/><b>Language-specific:</b><br/>Iranian
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js,<br>https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
Referrer: | [https://stfly.me/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fstfly.me%2F)
Other extensions used: | f-secure

**Comment by khafan11** [comment]
But its not Resolved ! 
7.11 nightly 6 (build 3994, CL 1.10.51)
it's the same as before

**Comment by sfionov** [comment]
Resolved in CL 1.11, as labels say
