### ISSUE TITLE
cryptpad.fr - broken website

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1644]
@adguard-bot commented on [Fri Jun 03 2022](https://github.com/AdguardTeam/AdguardFilters/issues/120707)

### Issue URL (Incorrect Blocking)
 [https://cryptpad.fr](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fcryptpad.fr)
### Comment
Username: @sysfu
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/X7v27Lp.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/B9jaNfO.png)
</details>
<details>
  <summary>Screenshot 3</summary>

  ![Screenshot 3](https://reports-img.adguard.com/VaxCgUN.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.8.1.1140 release
Browser: | Safari
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Self-destructing first-party cookies (), <br>Self-destructing third-party cookies (), <br>Block Push API, <br>Block Location API, <br>Block Java
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base
Custom filters: | cash back shopping
Userscripts: | Adguard extra
Other extensions used: | Rakuten, Honey, HTTPS Upgrade

**Comment by AdamWr** [comment]
It seems that:
```
@@||cryptpad.fr^$document
```
or
```
@@||sandbox.cryptpad.info^$document
```
doesn't fix issue.

It could be fixed by `$replace` rule, but I'm not sure if it's good idea in this case.

Also, it looks like that element hiding/JS rules do not work on `sandbox.cryptpad.info`.
```
net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep 200
```
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/171795149-dee4149f-4b88-4c51-b63e-1586c0e4813e.png)

</details>

**Comment by grumaxxx** [comment]
`@@||sandbox.cryptpad.info^$document` doesn't fix issue because `$document` does not match `iframes`. So, it could be fixed like:
`@@||cryptpad.fr^$document`
`@@||sandbox.cryptpad.info^$elemhide,jsinject,content`

**Comment by grumaxxx** [comment]
Maybe it need to use `@@||subdocument` like `@@||document` rule, but for iframes. Need some more examples to KB.

**Comment by grumaxxx** [comment]
https://github.com/AdguardTeam/AdguardKnowledgeBase/issues/1077

**Comment by AdamWr** [comment]
This rule:
```
@@||sandbox.cryptpad.info^$elemhide,jsinject,content,extension
```
seems to works fine, I will add it.
Thank you.

By the way, I always thought that `$document` exception disables filtering on specific website even in iframe, learned something.

**Comment by sxgunchenko** [comment]
> By the way, I always thought that `$document` exception disables filtering on specific website even in iframe

It used to, but since the CoreLibs have learned to recognize iframes, it doesn't always behave like this
