### ISSUE TITLE
Page goes blank as link tags are removed

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/CoreLibs#1647]
@Yuki2718 commented on [Thu Jun 09 2022](https://github.com/AdguardTeam/AdguardForWindows/issues/4285)

### Steps to reproduce

1. Visit `https://www.crazygames.com/game/spiderdoll` with Base filter enabled
2. The page will go blank and load will never end. If didn't happen, reload the page.

### Expected behavior

The page should display correctly.

### Actual behavior

Blank and endless loading

<details><summary>Screenshot:</summary>

![crazygames2](https://user-images.githubusercontent.com/58900598/172872087-74c08ead-35b7-4390-b54c-3a39b31a5c24.png)

</details>

### Your environment

* Chrome 102.0.5005.63
* Windows 10 21H1 19043.1706

---

@Yuki2718 commented on [Thu Jun 09 2022](https://github.com/AdguardTeam/AdguardForWindows/issues/4285#issuecomment-1151214748)

Please move to correct repo if not appropriate. Fixed by an exception as you see, but I wonder if it's technically possible not to remove link tags - IMO not worth removed with the cost of breakage like this.

**Comment by Yuki2718** [comment]
Now `@@||crazygames.com^$content,badfilter` will be needed to reporoduce.

**Comment by sfionov** [comment]
What you named `$htmlcollapse` is `$content`, and it is already in filter. I think there's nothing to do for CoreLibs.
