### ISSUE TITLE
(Anti-DPI) Allow to tune HTTPS fragmentation

### ISSUE THREAD

**Issue by Michael1297** [AdguardTeam/CoreLibs#1649]
Защита от dpi в AdGuard больше не помогает заходить на заблокированные сайты. Но благодаря [тонкой настройке ](https://github.com/ValdikSS/GoodbyeDPI/issues/254#issuecomment-1061822246)  программа [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI) по прежнему работает. Было бы неплохо добавить подобную опцию в AdGuard.

**Comment by sfionov** [comment]
Okay, we'll consider adding advanced option for HTTPS fragment size.
