### ISSUE TITLE
`sberbank.ru` не работает с включённым Stealth Mode

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/CoreLibs#1652]
Поэтому я добавил `online.sberbank.ru` в список HTTPS-исключений, а `sberbank.ru` убрал.

И я потестировал — похоже проблема связана со Stealth Mode, так как когда я его полностью отключаю, сайт загружается без ошибок. Но я не смог понять, какая именно настройка вызывает проблему, так как при включённом Stealth Mode, но при всех выключенных настройках, при загрузке сайта я получаю ошибку.

_Originally posted by @rakleed in https://github.com/AdguardTeam/AdguardFilters/issues/122953#issuecomment-1169784695_

**Comment by rakleed** [comment]
Возможно это ещё зависит от провайдера, сейчас у меня МегаФон. А до этого когда был SkyNet, такой проблемы вроде бы не было (но я могу ошибаться).

**Comment by zubrRB** [comment]
`Защищать от DPI`?

**Comment by rakleed** [comment]
@ngorskikh

**Comment by sxgunchenko** [comment]
@rakleed У нас есть задача, в которой мы собираем список сайтов, поломанных этой опцией: https://github.com/AdguardTeam/CoreLibs/issues/1645

**Comment by rakleed** [comment]
@sxgunchenko но в моём случае, при отключении всех опций Stealth Mode (в том числе DPI), сайт всё равно не работает, так как похоже проблема не в нём.

**Comment by rakleed** [comment]
@sxgunchenko

**Comment by rakleed** [comment]
@sxgunchenko please take a look

**Comment by sxgunchenko** [comment]
Извините за задержку. Повторил у себя, в ближайшее время постараюсь решить. В качестве временной меры можете добавить следующее правило: `@@||sberbank.ru^$stealth`.

**Comment by sxgunchenko** [comment]
Кажется, проблема в stealth скрипте - при отключении его инжекта сайт не ломается.
@maximtop

**Comment by maximtop** [comment]
Не нашел проблем в стелс скрипте, никаких ошибок не вижу, предполагаю проблема в маханизмах, которые использует сайт сбербанка для того чтобы показать эту заглушку, скорее всего ему не нравится, что удалили куку, или поменяли юзерагент и тд

**Comment by rakleed** [comment]
@maximtop @sxgunchenko так что, вы добавите в фильтры временно это правило?
`@@||sberbank.ru^$stealth`

**Comment by Alex-302** [comment]
Других жалоб нет. Лучше в пользовательском фильтре оставить.
