### ISSUE TITLE
Microsoft Edge collections are blocked

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/CoreLibs#1653]
### Issue URL (Incorrect Blocking)
 [http://www.google.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fwww.google.com)
### Comment
> adguard開啟後，edge的collections/集錦功能無法使用

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/ElTUbRW.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/MJAHLyX.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.8.1.1140
Browser: | edge
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base
Userscripts: | disabled
Other extensions used: | Edge collections

_Originally posted by @adguard-bot in https://github.com/AdguardTeam/AdguardFilters/issues/123078#issuecomment-1173555488_

**Comment by AdamWr** [comment]
I was able to reproduce and as a temporary solution added rule which should fixes it (at least it works on my side).
Before checking it, please disable this rule:
```
@@||edgeservices.bing.com^$elemhide,jsinject,extension,content
```
or add:
```
@@||edgeservices.bing.com^$elemhide,jsinject,extension,content,badfilter
```
to user rules.
