### ISSUE TITLE
AdGuard блокирует работу скрипта 

### ISSUE THREAD

**Issue by Oniqqqq** [AdguardTeam/CoreLibs#1655]
Пользователь сообщил, что [данный скрипт](https://greasyfork.org/ru/scripts/441304-authortodayextractor) не работает при добавлении в AdGuard. Наш коллега проверял в tampermonkey и в Адгарде. В первом случае все работает, во втором нет. Пользователь оставлял [описание проблемы](https://forum.adguard.com/index.php?threads/%D0%9F%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D0%B0-%D1%81%D0%BE-%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%B0%D0%BC%D0%B8.48926/) на форуме.

**Comment by grumaxxx** [comment]
caused by #1685
