### ISSUE TITLE
sjeccd.instructure.com - page layout is broken with enabled protection

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1656]
@adguard-bot commented on [Tue Jul 12 2022](https://github.com/AdguardTeam/AdguardFilters/issues/124119)

### Issue URL (Incorrect Blocking)
 [https://sjeccd.instructure.com/courses/31756/discussion_topics/426853](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fsjeccd.instructure.com%2Fcourses%2F31756%2Fdiscussion_topics%2F426853)
### Comment
Username: @jimmysofat6864
> Page does not load right when adguard is enabled. Account is required to view so I have some logs attached showing what happens. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/ETreW8r.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/xUmfDRq.png)
</details>
<details>
  <summary>Screenshot 3</summary>

  ![Screenshot 3](https://reports-img.adguard.com/8Bn0g6v.png)
</details>
<details>
  <summary>Screenshot 4</summary>

  ![Screenshot 4](https://reports-img.adguard.com/IgVHcLm.png)
</details>
<details>
  <summary>Screenshot 5</summary>

  ![Screenshot 5](https://reports-img.adguard.com/YK5Tclw.png)
</details>
<details>
  <summary>Screenshot 6</summary>

  ![Screenshot 6](https://reports-img.adguard.com/iMghwfl.png)
</details>
<details>
  <summary>Screenshot 7</summary>

  ![Screenshot 7](https://reports-img.adguard.com/SyqbU2y.png)
</details>
<details>
  <summary>Screenshot 8</summary>

  ![Screenshot 8](https://reports-img.adguard.com/kLKN8XO.png)
</details>
<details>
  <summary>Screenshot 9</summary>

  ![Screenshot 9](https://reports-img.adguard.com/xV7JmOj.png)
</details>
<details>
  <summary>Screenshot 10</summary>

  ![Screenshot 10](https://reports-img.adguard.com/LtWdrL4.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.7.0.1094 release
Browser: | Safari
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (180), <br>Block Push API, <br>Block Location API, <br>Block Java
DNS filtering: | server: `https://doh.opendns.com/dns-query`<br>filters: `https://filters.adtidy.org/mac_v2/filters/15.txt`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads, <br/>EasyList, <br/>Peter Lowe's Blocklist<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>AdGuard URL Tracking, <br/>EasyPrivacy, <br/>Legitimate URL Shortener, <br/>Fanboy's Enhanced Tracking List<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>Fanboy's Annoyances, <br/>Web Annoyances Ultralist, <br/>Adblock Warning Removal List, <br/>I don't care about cookies, <br/>EasyList Cookie List, <br/>Dandelion Sprout's Annoyances List<br/><br/><b>Security:</b><br/>Online Malicious URL Blocklist, <br/>NoCoin Filter List
Userscripts: | https://userscripts.adtidy.org/release/assistant/4.3/assistant.meta.js,<br>https://userscripts.adtidy.org/release/adguard-wot/1.0/wot.meta.js,<br>https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.meta.js,<br>https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
Referrer: | [https://sjeccd.instructure.com/courses/31756/assignments](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fsjeccd.instructure.com%2Fcourses%2F31756%2Fassignments)

---

@Alex-302 commented on [Tue Jul 12 2022](https://github.com/AdguardTeam/AdguardFilters/issues/124119#issuecomment-1181906736)

@jimmysofat6864 Cannot register. What causes an issue - filters, stealth mode, DNS filtering, extensions?

---

@jimmysofat6864 commented on [Fri Jul 15 2022](https://github.com/AdguardTeam/AdguardFilters/issues/124119#issuecomment-1185030650)

> @jimmysofat6864 Cannot register. What causes an issue - filters, stealth mode, DNS filtering, extensions?

@Alex-302 Appears to be filters as disabling everything else doesn't fix the issue. 

---

@Alex-302 commented on [Fri Jul 15 2022](https://github.com/AdguardTeam/AdguardFilters/issues/124119#issuecomment-1185262156)

Please test `@@||instructure.com^$document`

---

@jimmysofat6864 commented on [Fri Jul 15 2022](https://github.com/AdguardTeam/AdguardFilters/issues/124119#issuecomment-1185927399)

@Alex-302 that worked for me

---

@Alex-302 commented on [Wed Jul 20 2022](https://github.com/AdguardTeam/AdguardFilters/issues/124119#issuecomment-1189940016)

Ok, please check one by one:
`@@||instructure.com^$jsinject,extension`
`@@||instructure.com^$elemhide`
`@@||instructure.com^$extension`
`@@||instructure.com^$stealth`

---

@jimmysofat6864 commented on [Thu Jul 21 2022](https://github.com/AdguardTeam/AdguardFilters/issues/124119#issuecomment-1191863356)

> Ok, please check one by one:
> `@@||instructure.com^$jsinject,extension`
> `@@||instructure.com^$elemhide`
> `@@||instructure.com^$extension`
> `@@||instructure.com^$stealth`

@Alex-302 none of those fixed my issue.

**Comment by Alex-302** [comment]
@jimmysofat6864  Please write here)

**Comment by zzebrum** [comment]
@jimmysofat6864 is this still a problem for you?

**Comment by jimmysofat6864** [comment]
Yea it is still not fixed.

**Comment by ngorskikh** [comment]
>Ok, please check one by one:
>@@||instructure.com^$jsinject,extension
>@@||instructure.com^$elemhide
>@@||instructure.com^$extension
>@@||instructure.com^$stealth

This, unfortunately, won't work, since currently only a single basic rule can apply to a given request.

@jimmysofat6864 Greetings! Try `@@||instructure.com^$jsinject,extension,content,elemhide,urlblock`. If it still doesn't work, then add `instructure.com` to HTTPS exclusions; otherwise, remove modifiers from the rule until you find the one removal of which breaks the page. Please report your findings. Sorry to have to bother you with this, alas I can't even open the problematic page: the connection times out, even without AdGuard.

**Comment by jimmysofat6864** [comment]
@ngorskikh Using the rule  `@@||instructure.com^$jsinject,extension,content,elemhide,urlblock` did not work at all but adding `instructure.com` to HTTPS exclusions worked for me.

**Comment by jimmysofat6864** [comment]
@ngorskikh but however now I have a new problem. Now when I use AdGuard for Safari instead of the Mac App I have the same problem as described earlier but I do not see an option for https filtering in AdGuard for Safari.

**Comment by ameshkov** [comment]
Sorry for the late reply. It means that the problem is with ad filtering and not with network filtering in general.

It should be enough to just disable protection in AG for Safari for that website.
