### ISSUE TITLE
www.sberbank.ru does not load

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1662]
@adguard-bot commented on [Sun Aug 14 2022](https://github.com/AdguardTeam/AdguardFilters/issues/127117)

### Issue URL (Incorrect Blocking)
 [http://www.sberbank.ru/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fwww.sberbank.ru%2F)
### Comment
> Здравствуйте.
> При попытке зайти на сайт Сбербанка ( sberbank.ru/ru/person ) блокирует AdGuard, отключаю AdGuard захожу на сайт Сбербанка ( sberbank.ru/ru/person ) всё нормально. Можно связаться со мной murzich.i.n@mail.ru

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/2rME8ty.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/WTM6Dmm.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.10.2
Browser: | Opera
AdGuard driver: | WFP
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js,<br>https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
Referrer: | [http://www.sberbank.ru/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fwww.sberbank.ru%2F)

**Comment by Alex-302** [comment]
Reproduced with disabled Stealth mode, with added `@@||sberbank.ru^$document`

**Comment by zubrRB** [comment]
Может с этой связано https://github.com/AdguardTeam/CoreLibs/issues/1652

**Comment by zubrRB** [comment]
У меня нет проблемы при заходе по https на 7.11 beta 1.

**Comment by zubrRB** [comment]
Домен в исключениях HTTPS. Если удалить оттуда, то проблема проявляется.

**Comment by zzebrum** [comment]
сайт сбербанка действительно в исключениях и не фильтруется по умолчанию. перепроверьте, пожалуйста.
