### ISSUE TITLE
VOT "Voice over translation" script does not work in Google chrome

### ISSUE THREAD

**Issue by Baltazar500** [AdguardTeam/CoreLibs#1665]
Есть вот такой интересный скрипт
https://github.com/ilyhalight/voice-over-translation/blob/master/dist/vot-cloudflare.user.js
который позволяет осуществлять закадровый аудио перевод видео на ютубе, что является фишкой я-браузера. Скрипт в AdGuard успешно втыкается и даже панелька при просмотре видео появляется (хром, десктопный режим). Вот только при попытке перевода идёт обломинго и панелька выкидывает "Не удалось запросить перевод видео". Вероятно в скрипте не учтены какие-то нюансы AdGuard'овского userjs движка и нужен допил скрипта. Ну или AdGuard'овского userjs движок не поддерживает то, что используется в данном скрипте. Вопрос в том, что ?

Оставил автору запрос https://github.com/ilyhalight/voice-over-translation/issues/13#issuecomment-1225731769 но он пока молчит. Может вы проясните ситуацию ?

**Comment by Baltazar500** [comment]
@maxikuzmin,

>уточните также, на какой ОС вы используете скрипт? 

Android. Android 5.1

>Потому что вопрос в репозитории Android, а упоминание про десктоп.

Я не ошибся веткой. Упоминание было про "десктопный режим" ведроидного хрома  ака "Версия для ПК".  В мобильном режиме хрома при подгрузке мобильной версии ютуба эта панелька не появлялась вообще. Поэтому я про "десктопный режим" и упомянул.

**Comment by maxikuzmin** [comment]
@Baltazar500 мы разбираемся в проблеме

**Comment by Baltazar500** [comment]
Посмотрел har-дамп самого AdGuard'а при отработке скрипта и ничего кроме запросов

>https://icongr.am/entypo/language.svg?size=18&color=ffffff
>https://icongr.am/entypo/dots-three-vertical.svg?size=14&color=ffffff
>https://raw.githubusercontent.com/ilyhalight/voice-over-translation/master/img/YAlice.svg

которые происходят при открытии панельки не увидел. Никаких xhr - запросов до api.browser.yandex.ru, да и в принципе xhr - запросов не было. Тут или чего-то не хватает в скрипте или в движке самого AdGuard'a.

**Comment by Baltazar500** [comment]
Через костыли https://github.com/ilyhalight/voice-over-translation/issues/27#issuecomment-1272642869 вопрос автором решён (ниже даже есть линк на видяшку, где всё разжёвано) и issue в целом можно закрывать, но всё-таки у меня повис вопрос, причиной которого вероятно и стало появление сего треда. Позволяет ли userjs-движок adguard'a выполнять полноценные xhr - запросы или про это можно забыть ? Автору VOT вот пришлось городить костыли с cloudflare. Я вот тоже не смог пробиться с xhr дальше локалхоста.

**Comment by Firsto** [comment]
можт когда-нибудь починят, м?

**Comment by Michael1297** [comment]
> the issue cannot be reproduced now, the [VOT userscript](https://github.com/ilyhalight/voice-over-translation/blob/master/dist/vot-cloudflare.user.js) works fine
> 
> checked on:
> 
> * MacOS 14.3 + Chrome Canary 123
> * Windows 11 + Firefox 121
> * Android 12 + Chrome 121 (both mobile and desktop views)

@slavaleleka 
Проблема с этой версией скрипта https://github.com/ilyhalight/voice-over-translation/blob/master/dist/vot.user.js
Cloudflare версия работать, но через костыль

**Comment by ameshkov** [comment]
@slavaleleka эта версия скрипта использует GM_xmlhttprequest:
https://github.com/ilyhalight/voice-over-translation/blob/master/src/yandexRequest.js

А cloudlfare-версия использует fetch. Вот осталось понять что не так с GM_xmlhttprequest'ом.

**Comment by Baltazar500** [comment]
>Вот осталось понять что не так с GM_xmlhttprequest'ом.

Не так ту то, что xhr - запросы не выпускаются дальше локалхоста. Можете поднять http-сервер на локалхосте и поглядеть. На локалхост запросы ходят. Дальше - нет. Возможно это такой механизм защиты, а мб костыль, который где-то что-то прикрывает.
