### ISSUE TITLE
www.wko.at

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1666]
@adguard-bot commented on [Thu Sep 01 2022](https://github.com/AdguardTeam/AdguardFilters/issues/128657)

### Issue URL (Incorrect Blocking)
 [https://www.wko.at/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.wko.at%2F)
### Comment
Username: @gschelli
> Leider läßt sich diese Seite bei aktiviertem AdGuard nicht betrachten. Selbst wenn ich div. Filter deaktiviere.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/bcRq21e.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/m8TMlVk.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v4.1.19
Browser: | Firefox
AdGuard driver: | WFP
Stealth mode: | disabled
DNS filtering: | server: `AdGuard DNS "Nicht filternd"`<br>
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard German
Userscripts: | Benutzerskripte automatisch erkennen;
AdGuard-Assistent;
AdGuard Extra;
AdGuard Pop-up-Blocker;
Web of Trust
Other extensions used: | Panda Dome

---

@Alex-302 commented on [Mon Sep 05 2022](https://github.com/AdguardTeam/AdguardFilters/issues/128657#issuecomment-1237104467)

@gschelli Hi. Cannot reproduce.
Does it happen in another browsers?

---

@gschelli commented on [Mon Sep 05 2022](https://github.com/AdguardTeam/AdguardFilters/issues/128657#issuecomment-1237373782)

Hello Alex, unfortunately the same result with a different browser. I have tested Edge and Firefox. We also have this phenomenon in our company. Can I send you my Adguard config?
Greetings Gunter

**Comment by Alex-302** [comment]
@gschelli Please write here.

**Comment by gschelli** [comment]
@grumaxxx Hello, yes you are right - now the site is working properly!! That's really great - this support!! Many thanks and greetings Günter
