### ISSUE TITLE
Discard adblock agent properly

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1667]
Currently, we only discard `[Adblock`, we should discard more:
`[AdBlock], [Adblock Plus], [uBlock] / [uBlock Origin], [AdGuard]`

See there for the details:
https://github.com/github/linguist/blob/bf853f1c663903e3ee35935189760191f1c45e1c/lib/linguist/heuristics.yml#L681-L700

**Comment by ngorskikh** [comment]
@ameshkov Hmm, I need more context as to what exactly do we need to solve. If I understand correctly, we are talking about handling the first line of the filter list in the filter list processor? Currently, we just pass that to the engine. It won't parse anyway :)

**Comment by ameshkov** [comment]
@ngorskikh search for `[Adblock` in the code.
