### ISSUE TITLE
Can't ping ipv6 addresses with AdGuard enabled

### ISSUE THREAD

**Issue by Trustedinstall** [AdguardTeam/CoreLibs#1668]
[ Yes ] I am running the latest version

AdGuard version:

v3.6.8 (46)
Filtering mode:

Local VPN
Device:

OnePlus 3T
Operating system and version:

Mokee Android 10
Root access:

Yes

AdGuard uses a custom DNS service, which is a DNS service built locally with AdGuardHome, port 5353.
It is not possible to pass the connection test of ipv6 (https://test-ipv6.com/) and it is impossible to access websites with only ipv6 addresses (https://6.ipw.cn).
After turning off the protection, it can be tested by ipv6. In addition, after switching networks, it is also possible to access iPV6 websites normally for a period of time, such as switching from wifi to mobile network or vice versa.
[adguard_logs_3.6.46_2806_121317.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/8997792/adguard_logs_3.6.46_2806_121317.zip)

**Comment by maxikuzmin** [comment]
@Trustedinstall issue in the works

**Comment by sfionov** [comment]
@Trustedinstall This issue was caused by incorrect IPv6 detection in AdGuard 3.6.

AdGuard 4.0 is released where IPv6 detection was reworked, the issue should be gone.

**Comment by Trustedinstall** [comment]
> @Trustedinstall This issue was caused by incorrect IPv6 detection in AdGuard 3.6.
> 
> AdGuard 4.0 is released where IPv6 detection was reworked, the issue should be gone.

Thanks for the heads up, I tried AdGuard 4.0 and the problem has been fixed.
