### ISSUE TITLE
If you select "System default" DNS, the Internet does not work

### ISSUE THREAD

**Issue by awesomeocelot** [AdguardTeam/CoreLibs#1669]
### Issue Details

It appears the issue occurs when using the latest stable version of Adguard for Android, on cellular data (wifi works fine), and with the DNS Filtering option turned on and "System default" selected for the DNS server (turning off DNS Filtering or manually selecting a server such as Adguard DNS seems to work fine). It seems like the issue only started occuring a few months ago based on this forum post, so possibly either a recent Adguard update or Android security update broke it?

See this forum post for more details: https://forum.adguard.com/index.php?threads/ag-blocking-internet-on-cellular-data.47800/

- **AdGuard version:**
  - v3.6.8
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Google Pixel 6 Pro
- **Operating system and version:**
  - Android 12L
- **Root access:**
  - No

### Expected Behavior

Google searches and other websites should load on cellular data with the system default DNS server, just like how it works on WiFi.

### Actual Behavior

Google searches within Chrome fail saying with errors such as stating the DNS address cannot be resolved.

**Comment by JulioQc** [comment]
> @JulioQc @awesomeocelot try another DNS for now, we're looking into the situation

No can do for myself; new local DNS at home for my LAN services to resolve and work wifi blocks all other DNS than those provided by the DHCP. But for others that might do until its fixed :)

**Comment by maxikuzmin** [comment]
@JulioQc issue in the works

**Comment by deepwat3r** [comment]
Seeing the same issue on my Pixel 7, just found this issue.  Unfortunately it appears I have to choose between custom DNS and incessant warnings from AG, or turning off DNS filtering entirely :(

**Comment by maxikuzmin** [comment]
@deepwat3r we're still figuring it out

**Comment by Eugene-Savenko** [comment]
There's a similar problem in the 694532 (CRM ID). The user collected logs, attached them to the December 11th letter. 

> Adguard blocks internet connection when I turn off wifi and use cellular data from second SIM - everything works okay only when using cellular data from first SIM or turn off DNS protection (it's doesn't matter what option I set in DNS protection - it could be system default options or Adguard DNS or Google DNS etc)

**Comment by usmanovms** [comment]
I've been having this problem for half a year. How the issue happens on my side: I use WiFi and everything is just fine. But whenever I switch to the mobile connection everything stops working untill I force stop AG. Later I realized that some apps like Chrome and YouTube display a message saying that there's no connection but continue to work. However some other apps like Spotify don't work (pages and lists are loaded but songs won't play). Trying to find a solution I came across this page and tried the mentioned suggestions. Changing the DNS provider didn't help. However later I realized that DNS servers default to https and if you either disable it or choose non-https encrypted DNS everything works. 

So here's my operational setup:
- AG 3.6.10 in root mode (local proxy in auto mode with Magisk module installed)
- DNS filtering on with Google DNS (DNS-over-TLS)

**Comment by JulioQc** [comment]
You say changing provider from system default doesn't help yet your posted
working config is with Google DNS over HTTPS. Am I missing something here?

**Comment by deepwat3r** [comment]
He said Google DNS over TLS, not HTTPS.

I've been struggling with this issue as well for the last 6 months or more,
to the point where I actually bought a different phone before realizing the
issue was with Adguard. For a while things worked fine just switching from
system DNS to Google but that recently stopped helping, so I'll give this a
try and report back.
