### ISSUE TITLE
Gerrit pages takes a very long time to load

### ISSUE THREAD

**Issue by nkartyshov** [AdguardTeam/CoreLibs#167]
Redirect to the https://review.lineageos.org/  takes a very long time

Original report:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1598

**Comment by nkartyshov** [comment]
This bug was fixed

**Comment by ameshkov** [comment]
Why, let's keep it open so that guys re-test it with CoreLibs

**Comment by ameshkov** [comment]
Confirmed that there are no issues with the CoreLibs integrated Android build
