### ISSUE TITLE
Parental control module (Windows 10) does not block adult sites

### ISSUE THREAD

**Issue by PavelParkhomenko** [AdguardTeam/CoreLibs#1670]
На Windows 10 порносайты не блокируются c включённым родительским режимом (настроено всё правильно): есть и в выдаче всех поддерживаемых поисковиков, некоторые не блокируются при заходе по адресу в строке браузера. Проблема решается только включением семейного DNS сервера. Установлен DrWeb, отключение ничего не меняет
Время в логах, 8.09 15.12-15.16

[adg_logs_7.9.3869.0_0908_1517.zip](https://github.com/AdguardTeam/CoreLibs/files/9526851/adg_logs_7.9.3869.0_0908_1517.zip)

**Comment by ngorskikh** [comment]
Logs show that `@@||yandex.ru$document` applies to the search request. Hence, all filtering is forefeited, including parental control (and safebrowsing, too).
@ameshkov Is this correct behaviour? It's been like this for years.

**Comment by ameshkov** [comment]
It is, but where does this rule come from?

**Comment by ngorskikh** [comment]
New logs came in.
>HTTPS filtering enabled: False
User error :)

**Comment by PavelParkhomenko** [comment]
Enabling HTTPS filtering in the app solved the problem
