### ISSUE TITLE
imi-online.de - element hiding/javascript rules do not work

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1671]
Steps to reproduce:
1. Add these rules:
```adblock
imi-online.de##body
imi-online.de#%#alert(1);
```
2. Go to - [https://www.imi-online.de/2022/09/09/neue-grossoffensive-in-nordsyrien/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.imi-online.de%2F2022%2F09%2F09%2Fneue-grossoffensive-in-nordsyrien%2F)

Website should be "blank" and there should be an alert.
For some reason element hiding and javascript rules do not work.

AdGuard for Windows version 7.11 nightly 10 (build 4039, CL 1.10.80)

**Comment by Alex-302** [comment]
Which browser? Chrome? 
I can't reproduce with the same build.
But after the first visit witout the app, I had to press the buttons on this page to close old connections:
`chrome://net-internals/#sockets`

**Comment by AdamWr** [comment]
Yes, Chrome.
I have checked it out few times in incognito mode and result was always the same - JavaScript and element hiding rules didn't work, but `$$` rules work fine.
I have the same problem on Android.

**Comment by AdamWr** [comment]
I guess that it's caused by not closed `html` tag.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/195088356-b0c47dee-ae57-41cf-95c0-49937a86df04.png)

</details>

If I add a `$replace` rule, for example like this:
```adblock
||imi-online.de^$replace=/(<html xmlns="http:.*?" lang=".*?")/\$1>/
```
to close this tag, then rules work correctly.

**Comment by grumaxxx** [comment]
Actually, this is very rare issue, so it is difficult to prevent all possible errors in html. We have decided to don't change our behavior with problems like this.

In this case adding rule to fix html page is the best solution.

**Comment by AdamWr** [comment]
Okay, I have added this rule.
Thank you for your reply.
