### ISSUE TITLE
belkagomel.by

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/CoreLibs#1672]
При первом заходе выдаёт ошибки (наблюдал минимум трёх видов), при следующих может ломать или нет фильтрации.

<details><summary>Screenshot:</summary>

![belkagomel by](https://user-images.githubusercontent.com/50718960/190427129-dc93b9d7-2fe1-441f-814f-f35697b83582.png)
</details><br/>

**Comment by grumaxxx** [comment]
@zubrRB Подскажите пожалуйста, проблема актуальна? Не смог повторить на разных платформах, попробовал Mac, Android, Win. На каждой корректно происходит фильтрация и подмена сертификата.

**Comment by zubrRB** [comment]
Да, сначала открылся. а после повторной перезагрузки страницы выдало ошибку `ERR_SSL_PROTOCOL_ERROR`.

<details><summary>Screenshots:</summary>

![11](https://user-images.githubusercontent.com/50718960/194544986-cfb28658-82f7-402e-9522-a66a5508144d.png)
![22](https://user-images.githubusercontent.com/50718960/194544994-b82ca7bb-b279-428f-877b-a5d64ba4b3f3.png)
</details><br/>

**Comment by grumaxxx** [comment]
@zubrRB Добрый день, не могли бы вы прислать debug логи на devteam@adguard.com, тк. не получается воспроизвести на нашей стороне.
https://kb.adguard.com/ru/windows/solving-problems/adguard-logs

**Comment by grumaxxx** [comment]
@zubrRB Подскажите пожалуйста, установлен ли у вас Kaspersky? Если да, то помогает ли его отключение?

**Comment by zubrRB** [comment]
Нет, установлен Norton. Возможно, влияет опция "`Защищать от DPI`", но данный сайт не относится к критически важным.

**Comment by grumaxxx** [comment]
Отключение опции `"Защищать от DPI"` помогает?

**Comment by zubrRB** [comment]
Отослал дополнительные логи со всеми описанными выше и воспроизведёнными проблемами с использованием VPN: отвал фильтрации, неподмена сертификата, ошибки `ERR_SSL_PROTOCOL_ERROR` и `ERR_CONNECTION_CLOSED`.

**Comment by grumaxxx** [comment]
@zubrRB в логах видны проблемы с SSL, попробуйте как решение добавить следующее правило:
```adblock
@@||example.com^$stealth=dpi
```
Возможно что эта опция некорректно работает в случае с вашим провайдером.
Чтобы убедиться в этом точно, можно попробовать зайти на этот сайт с мобильной сети и проверить корректность работы.

**Comment by zubrRB** [comment]
Провайдер самый крупный, и с этой опцией без всяких проблем открываются даже заблокированные за политику.
Возможно, со стороны хостинга, но он тоже крупный и с остальными сайтами подобных проблем не было замечено. 
В ранее приводившемся мной списке проблемных сайтов с опцией `dpi` они вообще не открывались, а здесь ломает.

**Comment by zzebrum** [comment]
@zubrRB 🙈 еще актуальна проблема?

**Comment by zubrRB** [comment]
@zzebrum да, актуальна. Нормально работает только после внесения сайта в исключения защиты от DPI.

**Comment by sfionov** [comment]
@zubrRB Помогло ли вам правило `@@||belkagomel.by^$stealth=dpi` ?

**Comment by zubrRB** [comment]
@sfionov именно его я и имел в виду. с ним ресурс работает штатно.

**Comment by sfionov** [comment]
@zubrRB Окей, добавим в фильтры, спасибо
