### ISSUE TITLE
Element hide exception doesn't work if rule contains `~domain`

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1673]
Steps to reproduce
1. Add these rules:
```adblock
##body
~adguard.com#@#body
```
2. Go to - https://example.org/

### Expected behavior
Website should be displayed correctly (shouldn't be "blank").

### Actual behavior
Website is blank.
It looks like that generic exception doesn't work if there is `~domain` in the rule.

AdGuard for Windows Version 7.11 nightly 12 (build 4048, CL 1.10.80)

**Comment by grumaxxx** [comment]
@AdamWr Actual behavior can be achieved with rules:

```
##body
adguard.com#@#body
```
tilde is redundant here

https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#exceptions-2
