### ISSUE TITLE
Some sites are having trouble loading

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/CoreLibs#1674]
После обновления на 7.11 nightly 1 (с новой версией CoreLibs v1.10) возникла проблема с загрузкой некоторых сайтов.
Сразу после обновления страницы форума ru-board стали долго грузиться и (или) открываться далеко не с первого раза. 
Проблема подтверждена его пользователями: https://forum.ru-board.com/topic.cgi?forum=5&topic=50480&start=2020#19

https://user-images.githubusercontent.com/50718960/182345058-fe78bac6-e61e-4ca5-8483-7e641ac65095.mp4

**Comment by zubrRB** [comment]
Вчера истёк срок действия сертификата `forum.ru-board.com`, поэтому пока по https всё грузится и открывается быстро.

**Comment by maxikuzmin** [comment]
@zubrRB понял. Если снова появятся проблемы с загрузкой, дайте знать

**Comment by zubrRB** [comment]
Сертификат продлили и вернулась описанная проблема с указанным форумом, т.е. она связана с HTTPS-фильтрацией.

**Comment by maxikuzmin** [comment]
@zubrRB понял. Мы разбираемся, ожидайте

**Comment by ngorskikh** [comment]
@zubrRB Я посмотрел ваши трейсовые логи. В них и правда видны "тормоза" сетевого и дискового ввода/вывода. Например:
* ~3 секунды на установку соединения:
```
TRACE, AdguardSvc, 30, 11.08.2022 15:05:25.316, AGNFHandler: tcpConnectRequest: [id=2513]
TRACE, AdguardSvc, 30, 11.08.2022 15:05:28.395, AGNFHandler: tcpConnected: [id=2513]
VERBOSE, AdguardSvc, 30, 11.08.2022 15:05:28.396, AGNFHandler: [id=2513] TCP connected with on-the-fly filtering 192.168.100.2:49254->94.156.128.52:443 app C:\Program Files\Google\Chrome\Application\chrome.exe
```
* ~1.5 секунды RTT до сервера:
```
TRACE, AdguardSvc, 33, 11.08.2022 15:05:28.414, AGNFHandler: write: [id=2513-rem] len=517 // отправили ClientHello
TRACE, AdguardSvc, 30, 11.08.2022 15:05:29.793, AGNFHandler: tcpReceive: [id=2513] // Получили ответ
TRACE, AdguardSvc, 33, 11.08.2022 15:05:29.793, AGNFHandler: indicateReadsQueue: [id=2513-rem] Indicating queued read len=6500
```
* ~1.5 секунды на поиск сертификата в бд (дисковый IO, должен попадать в кэш и быть незаметным):
```
VERBOSE, AdguardSvc, 33, 11.08.2022 15:05:33.093, SSLFilter: [id=1000003] SSLFilter::tcp_packet getVerifiedServerCert
VERBOSE, AdguardSvc, 33, 11.08.2022 15:05:34.500, SSLFilter: [id=1000003] Remote server SSL version 303
```

Я пока что не уверен, что проблема именно в CoreLibs. Рекомендую попробовать следующее:
1. Redirect-режим драйвера. Доступен в advanced настройках, саппорт может проконсультировать.
2. Выключить другие программы, которые могут влиять на производительность ввода/вывода, например: антивирусы, файрволлы, сетевые мониторы, инструменты для отладки, "улучшители производительности", и т.п.; или проверить работу AdGuard на "чистой" операционной системе.

**Comment by zubrRB** [comment]
На данный момент эту проблему с торможением загрузки со всеми указанными сайтами больше не наблюдаю (7.12 n1).

**Comment by piquark6046** [comment]
New case found. (Adguard for Windows 7.12 nightly 1)
- https://github.com/AdguardTeam/AdguardFilters/issues/136578
