### ISSUE TITLE
Incorrect stylesheets injection

### ISSUE THREAD

**Issue by jellizaveta** [AdguardTeam/CoreLibs#1676]
Username: `@rakleed`
> When AdGuard is on, `.article__title-code` has no margin from `.article__description`
### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/yd6zKiv.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/MOk6kAj.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.8.1.1147+release
Browser: | Chrome
Stealth mode options: | Hide your search queries, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Disable cache for third-party requests, <br>Hide your Referrer from third-parties (), <br>Hide your User-Agent ()
DNS filtering: | server: `https://dns.cloudflare.com/dns-query`<br>
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>AdGuard URL Tracking<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | AdGuard+Extra+(url:+https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js),<br>IMDb+Tomatoes+(url:+https://greasyfork.org/scripts/15222-imdb-tomatoes/code/IMDb+Tomatoes.user.js)
Referrer: | [https://github.com/doka-guide/platform/issues/990](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fgithub.com%2Fdoka-guide%2Fplatform%2Fissues%2F990)

related to https://github.com/AdguardTeam/AdguardFilters/issues/131310

**Comment by rakleed** [comment]
@grumaxxx @ngorskikh @sfionov @maxikuzmin @sxgunchenko please take a look

**Comment by grumaxxx** [comment]
@rakleed issue in progress

**Comment by grumaxxx** [comment]
You can add this rule: 
```adblock
@@https://doka.guide/html/head/$jsinject,elemhide,extension
```
to prevent this behaviour on this page

**Comment by rakleed** [comment]
@grumaxxx why didn't you fix this problem?

**Comment by sfionov** [comment]
@rakleed Exclusions for XHRs are solved in filters, not in CoreLibs.

**Comment by rakleed** [comment]
@sfionov but because of this, the page now displays a popup about using cookies.

**Comment by rakleed** [comment]
@sfionov please take a look

**Comment by sfionov** [comment]
@rakleed Ok, please try these set of rules:

```
@@||doka.guide/html^$elemhide,jsinject,extension
[$path=/html^]doka.guide$$div[class="cookie-notification"]
```
