### ISSUE TITLE
PR_END_OF_FILE_ERROR

### ISSUE THREAD

**Issue by jellizaveta** [AdguardTeam/CoreLibs#1678]
### Issue URL (Incorrect Blocking)
 [https://corp.agap2.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fcorp.agap2.com)
### Comment
Username: @Theduskofdeath
> Le problème semble apparaître quand le Mode Furtif d'adguard est actif.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/dRcA6aa.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/FqVq9cf.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.10.2
Browser: | Firefox
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (180), <br>Disable cache for third-party requests, <br>Block WebRTC, <br>Block Location API, <br>Block Flash, <br>Block Java
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Russian, <br/>AdGuard German, <br/>AdGuard Dutch, <br/>AdGuard French, <br/>EasyList Czech and Slovak, <br/>Hungarian, <br/>Official Polish filters for AdBlock, uBlock Origin & AdGuard, <br/>Polish Anti Adblock Filters, <br/>Dandelion Sprout's Nordic Filters
Userscripts: | Adguard Extra
Bloqueur de fenêtre pop-up de Adguard
Other extensions used: | Privacy Badger (Mozilla Firefox)

Related to https://github.com/AdguardTeam/AdguardFilters/issues/131684

**Comment by grumaxxx** [comment]
@Theduskofdeath Could you please check one more time how this page works with rule, which disable stealth mode on this page, because on my side it's working fine:
```adblock
@@||corp.agap2.com^$stealth
```
Could you please add this rule to `User rules` and open private window with this page.

**Comment by Theduskofdeath** [comment]
![image](https://user-images.githubusercontent.com/5018266/197402523-f42e2423-dba9-4f9a-b954-c98aaf5497c9.png)
Hello sorry for the delay, the rule is enabled on my side but the problem still occurs.

**Comment by Theduskofdeath** [comment]
> ![image](https://user-images.githubusercontent.com/5018266/197402523-f42e2423-dba9-4f9a-b954-c98aaf5497c9.png) Hello sorry for the delay, the rule is enabled on my side but the problem still occurs.

Wait my bad it worked now... I don't know I just had a restart of my computer and it work.
