### ISSUE TITLE
Can't sign-in to the HP Smart app

### ISSUE THREAD

**Issue by Perfectlynk** [AdguardTeam/CoreLibs#1682]
Hello, when I tried to sign in to the HP smart app, I couldn't connect and got an error. I've checked the DNS and Adguard to see if anything is blocked but nothing is. 

This is the error message:
![Screenshot_20220915-140018.png](https://user-images.githubusercontent.com/72349391/190866487-0aad2203-d0f0-4910-bdab-539f07d14a59.png)

I can sign in fine to the HP Smart app on Windows 10.

I'm on the latest version on Android.

**Comment by Perfectlynk** [comment]
Could it be your certificate by any chance? When you install it during the installation of Adguard.

**Comment by Perfectlynk** [comment]
Just found out that my family member's phone doesn't have the problem linking Google to Hue.  She only has Adguard installed. So weird that I have the problem.

**Comment by sfionov** [comment]
Thank you for information! We'll close the issue then since it works using default settings.
