### ISSUE TITLE
tplinkwifi.net

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1690]
@adguard-bot commented on [Sun Nov 06 2022](https://github.com/AdguardTeam/AdguardFilters/issues/134237)

### Issue URL (Incorrect Blocking)
 [http://tplinkwifi.net/webpages/index.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Ftplinkwifi.net%2Fwebpages%2Findex.html)
### Comment
> 192.168.0.1/index.html#login -  тоже блокируется.
> AdGuard-7.10.2 - работает без проблем с одинаковыми настройками.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/ek3RZzi.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/VNO5vF8.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.11
Browser: | Chrome
AdGuard driver: | TDI
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Self-destructing third-party cookies (180)
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js,<br>https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js

**Comment by sfionov** [comment]
@Alex-302 Problem should be fixed in AG 7.11.3
