### ISSUE TITLE
Add exact match syntax for HTTPS exclusions

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#1691]
add support for the following syntax:
`|domain.com^` -- matches domain exactly, without subdomains

**Comment by ameshkov** [comment]
Maybe just use double-quotes for exact matching there?

**Comment by grumaxxx** [comment]
And some side questions:
 - Should we match `*.example.com` to `sub.sub.example.com`, or only to `sub.example.com` ?
 - Should we parse syntax with exact match and regex, like `|example.*^`
