### ISSUE TITLE
Naver Whale ON: 1508 error

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/CoreLibs#1693]
Naver Whale version: 3.17.145.12
AdGuard for Windows version: 7.11.1
Microsoft Windows version: Windows 10 22H2

The 1508 error is occurred even the following configuration:
 - DNS filtering: disabled
 - Ad blocking: disabled
 - Stealth mode: disabled
 - Filter localhost: disabled
 - TDI and WFP drivers does not matter

  <details><summary>Screenshots</summary>

  ![Screenshot from 2022-11-15 13-41-10](https://user-images.githubusercontent.com/98787049/201937346-37d49c60-3018-4f8c-b114-e1dd7f84b4d0.png)
  ![Screenshot from 2022-11-15 13-41-01](https://user-images.githubusercontent.com/98787049/201937370-d7f89b8f-a941-47ab-8f9c-a05b59e32b85.png)
  ![Screenshot from 2022-11-15 13-40-39](https://user-images.githubusercontent.com/98787049/201937380-a82d7d21-b3a6-4ff3-8d79-dd972b462cb3.png)

  </details>

Also, adding `naver.com` domain into HTTPS exclusions cannot resolve the issue.
The only thing that can resolve the issue is unchecking `Filter HTTPS protocol` in Network settings tab.

**Comment by sfionov** [comment]
@piquark6046 Hello! How to reproduce it? What I should click to get to this popup window?

**Comment by piquark6046** [comment]
To create a Whale ON meeting, you need a NAVER account and phone number.
You don't have to login to Naver Whale if you want to join a meeting.
### NAVER account and Log in
1. Create a NAVER account using [this form](https://nid.naver.com/user2/V2Join?m=agree&lang=en_US).
2. Install Naver Whale by clicking `다운로드` button on [this website](https://whale.naver.com/).
3. Login to Naver Whale
<details>
<summary>Detailed description</summary>

![Screenshot from 2022-11-15 15-25-56](https://user-images.githubusercontent.com/98787049/201963613-c2e3a694-f570-4497-986b-61a648e432a2.png)
![Screenshot from 2022-11-15 15-26-14](https://user-images.githubusercontent.com/98787049/201963662-951a447c-6b0c-4b6b-9334-3e5785b53ba2.png)

</details>

### Create a Whale ON meeting
1. Click _Start meeting_ button.
<details><summary>Screenshot</summary>

![Screenshot from 2022-11-15 15-25-24](https://user-images.githubusercontent.com/98787049/201963734-a6e97933-a8cd-43b8-99dc-030c3850a175.png)

</details>

2. Type a meeting name and click _Start_ button.
<details><summary>Screenshot</summary>

![Screenshot from 2022-11-15 15-36-58](https://user-images.githubusercontent.com/98787049/201964206-940eab7f-fe38-4a74-b773-b72612a4bf90.png)

</details>

3. Type a participant name and click _Join_ button.
<details><summary>Screenshot</summary>

![Screenshot from 2022-11-15 15-37-11](https://user-images.githubusercontent.com/98787049/201964577-66e9e30b-ae5d-4ec3-9e8e-0ead9fabd624.png)

</details>


### Join a Whale ON meeting

1. Click _Join meeting_ button.
<details><summary>Screenshot</summary>

![Screenshot from 2022-11-15 15-25-24](https://user-images.githubusercontent.com/98787049/201963734-a6e97933-a8cd-43b8-99dc-030c3850a175.png)

</details>

2. Type the meeting ID and password, and click _Join_ button.
<details><summary>Screenshot</summary>

![Screenshot from 2022-11-15 15-37-54](https://user-images.githubusercontent.com/98787049/201964951-367f1717-e970-4bbc-8b97-bb74b1aec8b4.png)

</details>

3. Type a participant name and click _Join_ button.
<details><summary>Screenshot</summary>

![Screenshot from 2022-11-15 15-37-11](https://user-images.githubusercontent.com/98787049/201964577-66e9e30b-ae5d-4ec3-9e8e-0ead9fabd624.png)

</details>

**Comment by ameshkov** [comment]
> The only thing that can resolve the issue is unchecking `Filter HTTPS protocol` in Network settings tab.

This one is really interesting. This probably means we just need to figure out which domain should be excluded.

Apparently, this is not a subdomain of `naver.com`.

**Comment by grumaxxx** [comment]
@piquark6046 Hello! Could you please try to add `line-apps.com` to HTTPS exclusion. Does this exclusion resolve your issue?

**Comment by piquark6046** [comment]
@grumaxxx Yeap.

**Comment by grumaxxx** [comment]
We've added this domain to HTTPS excluisons
