### ISSUE TITLE
`Protect from DPI` doesn't work for `mail.proton.me`

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/CoreLibs#1694]
`Protect from DPI` does not work for `mail.proton.me`, although other sites blocked in the Russian Federation open without problems.

**Comment by zubrRB** [comment]
Может используется другой метод его блокировки или блокировка осуществляется на стороне самого сервиса?

**Comment by rakleed** [comment]
@sfionov так а почему нельзя с помощью функции `Protect from DPI` нельзя обойти блокировки РКН, если на других сайтах это работает без проблем? Не хотелось бы ради одного сайта использовать VPN.

**Comment by sfionov** [comment]
@rakleed TCP-соединение реджектится сервером (Connection refused). Функция Protect from DPI имеет смысл только если TCP-соединение установлено.

**Comment by zubrRB** [comment]
У меня изначально была та же проблема, причём с нероссийским ip-адресом, но она исчезала при включении VPN.
Вероятно, сам сервис или его хостинг рубили соединение. Потому что местные блокировки с anti-DPI я легко обхожу.
