### ISSUE TITLE
Some requests that are blocked are displayed as unblocked

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1696]
Probably redundant information about HTTPS Tunnel in the filtering log

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/203949252-0c558679-6ec0-4204-a51b-d422ca18ece0.png)

</details>

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/203949422-8e638900-93fe-4e9b-b3e3-9815c67e63b6.png)

</details>

**Comment by ngorskikh** [comment]
@Alex-302 Maybe some requests of an HTTP/2 connection were blocked, while others were not? Seems logical to report the blocked requests as well as the stats for the whole connection.

**Comment by grumaxxx** [comment]
@Alex-302 Some sessions were cancelled or there were no requests through them, so even if they should have been blocked, they will be reported as `processed`. We believe that it is necessary to display all requests, including those that have been `cancelled'.
