### ISSUE TITLE
Add support for uBO's CSP rules - `inline-script`, `inline-font`

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1697]
[inline-script](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#inline-script)
[inline-font](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#inline-font)

Related to 
* https://github.com/AdguardTeam/FiltersRegistry/issues/683
* https://github.com/AdguardTeam/FiltersRegistry/issues/688

**Comment by sxgunchenko** [comment]
They are already supported

**Comment by slavaleleka** [comment]
but there is no description in KnowledgeBase

**Comment by sxgunchenko** [comment]
here's the link to the issue https://github.com/AdguardTeam/CoreLibs/issues/880
