### ISSUE TITLE
Incorrect stylesheets injection

### ISSUE THREAD

**Issue by jellizaveta** [AdguardTeam/CoreLibs#1699]
Related to https://github.com/AdguardTeam/AdguardFilters/issues/136120

 [https://electrek.co/2022/11/28/tesla-blogs-propagate-fake-news-chip-joint-venture/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Felectrek.co%2F2022%2F11%2F28%2Ftesla-blogs-propagate-fake-news-chip-joint-venture%2F)
### Comment
> Body copy changes to a much tinier size with AdGuard enabled. Disabling AdGuard restores the proper font size for articles. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/7wsNlDo.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/2xufSsA.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.9.1.1217+release
Browser: | Safari
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances
Userscripts: | AdGuard+Extra+(url:+https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js)

**Comment by grumaxxx** [comment]
@jellizaveta I can't reproduce the issue on my side. Is the problem still relevant?

**Comment by jellizaveta** [comment]
Cannot reproduce this issue on my side too.
