### ISSUE TITLE
classical-music.com is broken by any enabled extension in AdGuard apps

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1701]
@adguard-bot commented on [Thu Dec 01 2022](https://github.com/AdguardTeam/AdguardFilters/issues/136344)

### Issue URL (Incorrect Blocking)
 [https://www.classical-music.com/features/artists/who-is-martha-argerich-all-you-need-to-know-about-the-brilliant-pianist/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.classical-music.com%2Ffeatures%2Fartists%2Fwho-is-martha-argerich-all-you-need-to-know-about-the-brilliant-pianist%2F)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/i4yFgkN.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/mnr17zw.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.11.3
Browser: | Firefox
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (180), <br>Disable cache for third-party requests, <br>Block WebRTC, <br>Block Push API, <br>Block Location API, <br>Block Flash, <br>Hide your Referrer from third-parties (www.classical-music.com), <br>Hide your User-Agent ()
DNS filtering: | server: `tls://dns.adguard-dns.com`<br>filters: `https://filters.adtidy.org/windows/filters/15.txt, User+rules`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>Legitimate URL Shortener, <br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>Web Annoyances Ultralist, <br/>Adblock Warning Removal List, <br/>I don't care about cookies, <br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/>Online Malicious URL Blocklist, <br/>NoCoin Filter List<br/><br/><b>Language-specific:</b><br/>Liste FR, <br/>ROList, <br/>ROLIST2, <br/>road-block, <br/>Frellwit's Swedish Filter, <br/>Dandelion Sprout's Nordic Filters, <br/>AdGuard French, <br/>AdGuard Russian, <br/>AdGuard German
Userscripts: | https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js,<br>https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js,<br>https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js

**Comment by Alex-302** [comment]
Reproduced with AdGuard for Windows, Android, Mac.

Added temporary exclusion for extensions. Disable it or Base filter before checking:
`@@||classical-music.com^$extension`

**Comment by AdamWr** [comment]
It looks similar to this issue - https://github.com/AdguardTeam/CoreLibs/issues/1571
If I'm not wrong, the same rule works here:
```adblock
classical-music.com#%#(function(){window.DD_LOGS={onReady(){},logger:{log(){}}}})();
```
I have tested it with:
```adblock
@@||classical-music.com^$extension,badfilter
```

**Comment by sfionov** [comment]
@Alex-302 Can you add rule then?

**Comment by Alex-302** [comment]
Ok.
