### ISSUE TITLE
CSS and images are not loaded irregularly on certain sites.

### ISSUE THREAD

**Issue by Kieaer** [AdguardTeam/CoreLibs#1703]
_adg_logs_7.11.4107.0_1206_1558.zip hidden for security_

Adguard for Windows debug log.
The tested web page URL is https://cafe.naver.com/fx8300/972030.

This problem is the same issue on Windows and Android.
The tested site is m.cafe.naver.com, cafe.naver.com, arca.live, twitter.com, etc...

**Comment by ngorskikh** [comment]
@Kieaer Hi, sorry for the wait. I can't seem to reproduce these issues. Have you tried the latest nightly versions of the [Windows](https://agrd.io/windows_nightly) and [Android](https://agrd.io/android_nightly) applications?

**Comment by Kieaer** [comment]
@ngorskikh Tested on Android using adguard 4.0 nightly 35. same problem
This problem only occurs in Firefox.

**Comment by Kieaer** [comment]
It's not always like that. Sometimes github.com also fails to load css.
It may not be related to a specific sites.

**Comment by ngorskikh** [comment]
@Kieaer I still have not been able to reproduce this, and I can only see one suspicious failed request in your log, which probably doesn't explain the issues you're having. Since you seem to be able to reproduce this reliably on Windows, could you run AdGuard with even higher logging verbosity and share the logs again, also noting the exact time it was malfunctioning? Exit AdGuard and run this from the command line: 
```
C:\"Program Files (x86)"\Adguard\Adguard.exe /trace
```

**Comment by piquark6046** [comment]
@Kieaer This is just a question. Is any online banking security application or anti-virus [^1] installed on your computer having this issue?

[^1]: Except Microsoft Defender Antivirus.

**Comment by Kieaer** [comment]
@piquark6046 Windows using bitdefender, but same problem on android & windows 11
@ngorskikh Sorry for late answer (no alerm 😟)
This problem is a probability that isn't reproducible at once, so i have to try it until it is reproducible.
I'll comment again if it reproduces with this option enabled.

**Comment by Kieaer** [comment]
@ngorskikh How to automatically run ``/trace`` command when PC starts?
I'm still having issues, but I haven't turned ``/trace`` on.

**Comment by Kieaer** [comment]
https://ufile.io/vo1v773y
Debug log
no trace command

**Comment by Kieaer** [comment]
![image](https://github.com/AdguardTeam/CoreLibs/assets/44261958/7faa4472-fc6a-40d6-a797-198122fc73fa)

I finally succeeded in reproducing and attaching the log.
I did a log export as soon as the problem occurred.

log file is here (available for download until August 13, 2023)
https://ufile.io/xvs64qtt

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/CoreLibs/issues/1703#issuecomment-1634434833
@Kieaer 
An AdGuard CoreLib developer downloaded your logs. I think that it is safe to delete it.

**Comment by Kieaer** [comment]
![image](https://github.com/AdguardTeam/CoreLibs/assets/44261958/f66af3e0-3354-4aaf-9a57-5eb7e3fe72f6)
![image](https://github.com/AdguardTeam/CoreLibs/assets/44261958/ad05f909-de2d-476c-a6de-289906d676f1)

find additional problems

**Comment by Kieaer** [comment]
![Screenshot_20230831-083029_Firefox_Beta](https://github.com/AdguardTeam/CoreLibs/assets/44261958/30a15a3d-091f-4617-9284-7a809cca0635)
It can't fixed? using Adguard v4.2 nightly 29

**Comment by piquark6046** [comment]
Please downgrade to its stable channel.
The nightly channel is unstable.

**Comment by Kieaer** [comment]
When will it be fixed? using Adguard for Android 4.1

**Comment by sfionov** [comment]
@Kieaer This issue is fixed in CoreLibs 1.12, which is bundled with Adguard for Android 4.2

**Comment by Kieaer** [comment]
@sfionov 
![Screenshot_20231110-215452_AdGuard](https://github.com/AdguardTeam/CoreLibs/assets/44261958/d8c0ced3-7d17-4a44-8fd9-c6b964945fe6)
No fixed. reinstall also not work.
