### ISSUE TITLE
`$removeparam` exclusions do not work

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1704]
AdGuard 7.12 n2

Sample URL:
`https://use.typekit.net/af/9a7284/0000000000000000000118b2/27/l?primer=7fa3915bdafdf03041871920a205bef951d72bf64dd4c4460fb992e3ecc3a862&fvd=i7&v=3`

Site: classical-music.com

Blocking rule:
`||use.typekit.net^$font,removeparam=~/^(primer|subset_id)=/`

Exclusion rules, which do not work:
`@@||use.typekit.net^$domain=classical-music.com,removeparam`
`@@||use.typekit.net/af/$domain=classical-music.com,removeparam`

**Comment by grumaxxx** [comment]
At the moment it is necessary that the `request-type` is set (https://github.com/AdguardTeam/CoreLibs/issues/1492#issuecomment-894833528). This behavior will be changed in version 1.11.
