### ISSUE TITLE
Add `$extension` modifier disabling specific userscript

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/CoreLibs#1706]
Please consider a `$extension` modifier disabling specific userscript installed in AdGuard like `$extension='name of an userscript'` or `$extension=id1|id2...`. [^1]

The change can provide a benefit that a visitor uses another userscript instead of a default userscript at a website.
For example, a viewer can unblock the limitation that Twitch limits up to 720p about video resolution by installing an userscript into AdGuard for Android.

[^1]: The each ID is given by AdGuard products and configured with `[0-9]{8}`.

**Comment by sfionov** [comment]
Good idea, we'll consider it

**Comment by ameshkov** [comment]
Very good idea indeed, thank you!
