### ISSUE TITLE
uBO HTML filtering conversion issue

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1708]
uBO-syntax HTML filtering rule:
`forbes.com##^script:has-text(scriptTag)`

Is converted to:
`forbes.com$$script[tag-content="scriptTag"][max-length="262144"]`

However, exclusion rule is not converted so nothing is unblocked.

It should be converted to this:
`forbes.com$@$script[tag-content="scriptTag"][max-length="262144"]`

**Comment by Alex-302** [comment]
`forbes.com#@#^script:has-text(scriptTag)`
should not be conderted to this?
`forbes.com$@$script[tag-content="scriptTag"][max-length="262144"]`

**Comment by Alex-302** [comment]
Also browser extension shows an original rule. The app - only result of convertion.'

Details of the log of extenson for Firefox
![image](https://user-images.githubusercontent.com/8361299/208769031-dc7f9e3e-7801-4f1a-8e53-dab71ed3faa0.png)
