### ISSUE TITLE
Send the original rule to the filtering log when applied converted uBO-syntax HTML rule`##^script:has-text()` 

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1709]
The browser extension shows an original rule. The app - only result of convertion.

Expected result:
Details of the log of extenson for Firefox
![image](https://user-images.githubusercontent.com/8361299/208769031-dc7f9e3e-7801-4f1a-8e53-dab71ed3faa0.png)

**Comment by sfionov** [comment]
We did original rules storing in https://github.com/AdguardTeam/CoreLibs/issues/1535.

We'll recheck whats wrong with it.
