### ISSUE TITLE
Filtering and userscripts do not work with Norton 360 installed

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/CoreLibs#1712]
После обновления с версии `7.12 beta 1` на `7.12 nightly 4` перестали работать фильтрация и юзерскрипты (сторонние и собственные AdGuard Extra, Блокировщик всплывающей рекламы). Повсеместно на сайтах присутствуют баннеры, директы, виджеты социальных сетей и раздражители. Трафик при этом крайне медленный.  Обновление на 7.12 nightly 5 ничего не дало.

Проблема исчезает после включения в браузере VPN-расширения ZenMate (или подобных). За неделю до того я обратил внимание разработчиков фильтров, что при включенном прокси ZenMate периодически не фильтруются раздражители. 
После чего поведение изменилось на полностью противоположное: фильтрация и юзерскрипты работают только если включено прокси-расширение. После его отключения — всё снова отваливается. При этом штатно подменяются сертификаты сайтов.

**Comment by northis** [comment]
@zubrRB Пожалуйста, пришлите нам логи на почту devteam@adguard.com

**Comment by zubrRB** [comment]
@northis отослал!

**Comment by northis** [comment]
@zubrRB Есть возможность повторить проблему с включенными трейсовыми логами как описано [тут](https://kb.adguard.com/ru/windows/solving-problems/adguard-logs)?

**Comment by zubrRB** [comment]
@northis да, отправил их с воспроизведённой проблемой.

**Comment by zubrRB** [comment]
@northis отправил ещё трейсовые логи с отключенным ZenMate и последующим его включением.

**Comment by northis** [comment]
@zubrRB Судя по логам, фильтрация всё же есть (сертификат у сайтов от AdGuard?)
Что если попробовать отключить всё, кроме базового фильтра (скрипты, стелсмод и остальные фильтры), будет ли работать фильтрация?

**Comment by zubrRB** [comment]
Сертификаты, как сразу и написал, подменяются, но имеющиеся в фильтрах правила не срабатывают без вкл. ZenMate.
На тестировавшихся сайтах: otzovik везде Яндекс-директ, на VK внизу и по центру вылазят плашки регистрации/входа. 
Все те сайты русскоязычные, поэтому базовый фильтр их, вероятно, не будет затрагивать...

**Comment by northis** [comment]
@zebrum Будет ли повторяться, если включить опцию "Использовать драйвер в режиме перенаправления" и/или "Фильтровать локальные адреса"?

**Comment by zubrRB** [comment]
Никак не повлияло их включение. 
Одни элементы должны блокироваться AdGuard Extra, но не блокируются из-за общей проблемы со скриптами.
Другие должны блокироваться фильтрами, но не блокируются, например, предупреждения об использовании cookie.  
Может загрузиться с рекламой и с неработающими скриптами, а после перезагрузки страницы — без рекламы. 
Страница "Вконтакте" может загрузиться с работающими скриптом Mouseover Popup Image Viewer, потому что увеличиваются изображения, и скриптом SaveFrom helper, так как виден его значок, но при этом на странице всплывают плашки Зарегистрироваться/Войти, которые AdGuard должен блокировать, но почему-то пропускает через раз.

**Comment by northis** [comment]
@zubrRB Пока возможная причина - несовместимость с антивирусом Norton Security. Речь именно о драйвере, который устанавливается в систему.

**Comment by zubrRB** [comment]
Norton 360 (c модулем VPN) на новую версию обновлялся 1 декабря, а в остальном антивирусные базы и, может, патч.

**Comment by ameshkov** [comment]
@zubrRB `https://local.adguard.org/` открывается и пишет `invalid request`?

**Comment by zubrRB** [comment]
Нет, практически всегда ошибка: `ERR_CONNECTION_TIMED_OUT`.

**Comment by ameshkov** [comment]
Проблема 100% в несовместимости с антивирусом. 

Нам нужно знать точную версию Norton 360. Также будем благодарны если попробуете его удалить и проверить исчезла ли проблема.

**Comment by zubrRB** [comment]
До середины месяца проблема ранее не возникала. Видимо, возникла из-за новой версии ночной сборки AdGuard.
Сама версия приведена ниже, но в процессе могут выпускать мелкие патчи без анонса и изменения номера версии.  

N360 22.22.11.12 (RU) https://buy-download.norton.com/downloads/2022/22.22.11/N360/RU/N360-ESD-22.22.11.12-RU.exe
N360 22.22.11.12 (EN) https://buy-download.norton.com/downloads/2022/22.22.11/N360/US/N360-ESD-22.22.11.12-EN.exe

Проблема только в `local.adguard.org`? В брандмауэре антивируса Norton можно задавать правила трафика.

<details><summary>Screenshots:</summary>

![0](https://user-images.githubusercontent.com/50718960/209793508-e45066da-0b7a-4092-937b-4215e3f37b7c.png)
![1](https://user-images.githubusercontent.com/50718960/209793515-46f41481-36d3-4075-a5d1-fc1030d119ca.png)
![2](https://user-images.githubusercontent.com/50718960/209793517-ac943557-1e7f-4bfa-9a59-37ce32247166.png)
![3](https://user-images.githubusercontent.com/50718960/209793519-6c853fff-a8cd-42f3-845b-5dd1e18af777.png)
![4](https://user-images.githubusercontent.com/50718960/209793522-841b74c1-322f-4531-b0be-e27d8063f9e5.png)
![5](https://user-images.githubusercontent.com/50718960/209793523-b9d34aea-46ea-4cb4-9fee-79dad3d51023.png)

</details><br/>

**Comment by ameshkov** [comment]
Проблема шире, `local.adguard.org` это ее симптом. Если вкратце, то проблема похоже с локальным редиректом. Не думаю, что правила в нортоне тут помогут.

А на релизной версии AdGuard она точно не повторяется?

**Comment by zubrRB** [comment]
Если только переустанавливать с понижением версии AdGuard... Но раньше в релизной точно не было.
Я обновлялся последовательно: 7.11.3 > 7.12 nightly 1 > 7.12 nightly 2 > 7.12 nightly 3 > 7.12 beta 1 > 7.12 nightly 4.

**Comment by northis** [comment]
@zubrRB пожалуйста, попробуйте этот билд https://uploads.adguard.org/AdGuard-7.12-nightly-6.exe

**Comment by zubrRB** [comment]
@northis в свойствах должна быть прописана `nightly 6`? Потому что у меня там` nightly 5`. Что-то с ней то же самое.

<details><summary>Screenshot:</summary>

![-](https://user-images.githubusercontent.com/50718960/210097299-1ea6442f-e732-4ec1-954c-10c56537971d.png)
![--](https://user-images.githubusercontent.com/50718960/210097303-d01eb43c-15f7-4e66-9509-8b8265303cb4.png)

</details><br/>

**Comment by northis** [comment]
@zubrRB В разделе "О программе" должно быть `7.12 nightly 6 (build 4152, CL 1.10.182)`. Как вариант, можете обновиться с `nightly 5`, мы выкатили обновление.

**Comment by zubrRB** [comment]
@northis у меня там и в трее после установки маячила пятая, хотя в программах и компонентах прописалась шестая. 
Из-за этого при попытке обновления на шестую отказывалось под предлогом того, что она уже якобы установлена...
Снёс без удаления настроек и установил заново: cитуация та же, как на скриншотах выше.

**Comment by northis** [comment]
@zubrRB В наших тестах проблема повторялась на nightly 5, но не повторяется на nightly 6. Можете, пожалуйста, воспроизвести и прислать трейсовые логи, если это ещё актуально?

**Comment by zubrRB** [comment]
Накануне откатывался на 7.12 beta 1 и с ней проблемы нет, а сейчас обновился на nightly 6 — с ней есть. Отправил логи.

**Comment by adbuker** [comment]
@zubrRB, вы не могли бы записать логи с указанием более детальной информации, а именно
1. таймкоды заходов на сайт без расширения zenmate
2. таймколы заходов на сайт с расширением zenmate (с ним же всё нормально, верно)
3. после того, как вы убедитесь, что запросы к `local.adguard.org` фейлятся (сообщения в консоли разработчика), можете плз скопировать урл и перейти на этот адрес непосредственно в браузере (речь про ссылку типа `https://local.adguard.org/?ts=1673379368403&type=content-script&...`) и также указать таймкод такого перехода.

для удобства просьба между воспроизведением пунктов выше делать паузу по минуте, например, - чтобы в логах было удобнее найтли нужные момент и изолировать их от предыдущих

**Comment by zubrRB** [comment]
Отправил трейсовые логи, но второй и третий пункты сделал в обратной последовательности.

**Comment by northis** [comment]
@zubrRB Пожалуйста, попробуйте этот билд https://uploads.adguard.org/AdGuard.7.12.4155.exe

**Comment by zubrRB** [comment]
@northis работают фильтрация и юзерскрипты!

**Comment by adbuker** [comment]
> Отправил трейсовые логи, но второй и третий пункты сделал в обратной последовательности.

а каков был результат открытия запроса непосредственно в браузере? (п.3)?

**Comment by zubrRB** [comment]
Не открылся, кажись, `ERR_CONNECTION_TIMED_OUT`.

**Comment by adbuker** [comment]
добрый день!
к сожалению, у нас не повторяется ваша проблема, а поэтому проверить работоспособность решений можем только через просьбу проверить тот или иной билд вами. Отправил вам по почте ссылку на билд, попробуйте, пожалуйста, с ним. По факту просьба прислать трейсовые логи. Для этого и последующих сборок просьба сделать следующее:
1. удалить предыдущий билд
2. установить предлагаемый
3. остановить фильтрацию через трей (выбрав "нет")
4. запустить в папке programfiles(86) командную строку и запустить `adguard.exe /trace`
5. воспроизвести проблему
6. выслать на почту полученные логи
Заранее благодарен за помощь в поиске и решении

**Comment by zubrRB** [comment]
@adbuker я выше отписал, что теперь всё работает с тестовой сборкой 7.12.4155, ссылку на которую дал мне @northis.

**Comment by adbuker** [comment]
@zubrRB , всё верно, но сборка 4155 есть не самое изящное решение, которое может иметь некоторые потенциальные проблемы. Так что просьба оставить этот билд как крайний случай

**Comment by zubrRB** [comment]
Протестировал тестовую сборку 7.12 nightly 7 (build 4156, CL 1.10.188), в которой работают фильтрация и юзерскрипты!

**Comment by adbuker** [comment]
@zubrRB , отлично, спасибо за помощь, сегодня прилетит в найтли!
