### ISSUE TITLE
Some requests are not blocked

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1715]
Related to - https://github.com/AdguardTeam/AdguardFilters/issues/139168

Steps to reproduce:
1. Add these rules:
```adblock
||cdn.pear.focus.de/clients/widget.js$badfilter
||cdn.pear.focus.de/clients/public/generated/deal_*.html$redirect=nooptext,important
```
or instead of `$redirect` rule this:
```adblock
||cdn.pear.focus.de/clients/public/generated/deal_*.html$important
```
2. Go to - [https://www.focus.de/panorama/welt/gastbeitrag-von-michael-broecker-willkommen-in-der-failed-city-warum-in-berlin-der-rechtsstaat-versagt_id_182024041.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.focus.de%2Fpanorama%2Fwelt%2Fgastbeitrag-von-michael-broecker-willkommen-in-der-failed-city-warum-in-berlin-der-rechtsstaat-versagt_id_182024041.html)
Or directly to - [https://cdn.pear.focus.de/clients/public/generated/deal_23.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://cdn.pear.focus.de/clients/public/generated/deal_23.html)

Request to `cdn.pear.focus.de/clients/public/generated/deal_` should be redirected/blocked, but for some reason it isn't.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/210525939-23b1d62f-2b40-444b-bee3-563a6ffd7b4b.png)

</details>

AdGuard for Windows version 7.12 nightly 6 (build 4152, CL 1.10.182)

**Comment by ngorskikh** [comment]
@AdamWr Hi!
I've conducted an investigation.
There seems to be a rule in AdGuard Annoyances filter:
```||focus.de$replace=/autoPlay:[\s\S]*\,autoStickiness/autoPlay:false\,autoStickiness/,important,~script,~stylesheet,~xmlhttprequest```
Unfortunately, `$replace` rules disable basic rules. And better yet, when a `$replace` rule doesn't actually replace anything, it is not reported. So, your rules don't work, and you can't even see why.
And worst of all, _this is intended behaviour_ 
![image](https://user-images.githubusercontent.com/57908117/211284272-68f6fc06-8fd1-4d50-8e33-94e224797171.png)

**Comment by AdamWr** [comment]
Hi,
My bad, I wasn't aware that there is a `$replace` rule (I should check it with all filter lists disabled).
Though, maybe it would be a good idea to add info in the filtering log that there is a `$replace` rule, but it wasn't applied.
Another thing is that, sometimes it would be useful to have ability to block request(s) even if there is a `$replace` rule, but it's not applied.

Thank you for checking it and sorry for bothering.
