### ISSUE TITLE
en-ministryofcompliance.anewspring.nl

### ISSUE THREAD

**Issue by jellizaveta** [AdguardTeam/CoreLibs#1718]
According to https://github.com/AdguardTeam/AdguardFilters/issues/139381

### Issue URL (Incorrect Blocking)
https://en-ministryofcompliance.anewspring.nl/do?action=home
### Comment
Username: @sanyer
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/FXUNtli.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/bfDeY14.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.9.1.1217+release
Browser: | Chrome
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (180), <br>Block Push API, <br>Block Location API, <br>Block Java
DNS filtering: | server: `nextdns`<br>
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Russian, <br/>AdGuard German, <br/>AdGuard Dutch
Userscripts: | AdGuard+Extra+(url:+https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js)

**Comment by ngorskikh** [comment]
@jellizaveta Hi! A rule like this:
```
@@||anewspring.*/do?action$xmlhttprequest,jsinject,content,elemhide,extension
```
is required to fix this. The issue is that our script tags get injected into something that looks like an HTML document, but isn't.

**Comment by sanyer** [comment]
This fix worked, thanks @ngorskikh !
