### ISSUE TITLE
portal.azure.com.mcas.ms

### ISSUE THREAD

**Issue by jellizaveta** [AdguardTeam/CoreLibs#1719]
According to https://github.com/AdguardTeam/AdguardFilters/issues/139625
### Issue URL (Incorrect Blocking)
 [https://portal.azure.com.mcas.ms/resource/subscriptions/resourceGroups/Azure_AD_B2C/overview](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fportal.azure.com.mcas.ms%2Fresource%2Fsubscriptions%2FresourceGroups%2FAzure_AD_B2C%2Foverview)
### Comment
Username: @PA1138
> Whenever AdGuard is on, I can't see the resources in a resource group in Azure Cloud. This issue is recent (few months old) that I have raised with Adguard and have advised to follow these steps to report. Nothing seems to be solving this issue unless I disable Adguard.
> 
> Also, on a similar note, this happens across all browsers (Chrome, Firefox and Opera).

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/HNQHmxA.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/o5FyLG6.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.12+nightly+6
Browser: | Edge
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Self-destructing third-party cookies (180)
DNS filtering: | server: `quic://dns.adguard-dns.com`<br>filters: `User+rules`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Dutch
Userscripts: | https://userscripts.adtidy.org/beta/adguard-extra/1.0/adguard-extra.user.js,<br>https://userscripts.adtidy.org/beta/popup-blocker/2.5/popupblocker.user.js,<br>https://userscripts.adtidy.org/beta/adguard-wot/1.0/wot.user.js
Referrer: | [https://portal.azure.com.mcas.ms/signin/index/?cas_app_landing_mgc=%7B%22sle%22%3Afalse%2C%22pt%22%3A1%7D](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fportal.azure.com.mcas.ms%2Fsignin%2Findex%2F%3Fcas_app_landing_mgc%3D%257B%2522sle%2522%253Afalse%252C%2522pt%2522%253A1%257D)
Other extensions used: | BitDefender Total Security (no VPN or other ad blockers).

**Comment by grumaxxx** [comment]
@PA1138 Hello! Sorry for the late reply. Could you provide some information: Do you (or your organization) use additional security controls, because your URL contains `*.mcas.ms `? If so, is it possible for you to try visit Azure Cloud without this defender? (to make sure what's the matter)

**Comment by PA1138** [comment]
> @PA1138 Hello! Sorry for the late reply. Could you provide some information: Do you (or your organization) use additional security controls, because your URL contains `*.mcas.ms `? If so, is it possible for you to try visit Azure Cloud without this defender? (to make sure what's the matter)

Hi - Microsoft Cloud App Security (MCAS), now known as Microsoft Defender for Cloud Apps is enabled on my tenant, however, the issue with this is that it happens with other Azure tenants where MCAS is not in use. Also, this issue as I mentioned in the original post is that it's relatively new, only started few months ago.

As mentioned in the previous post [Here](https://github.com/AdguardTeam/AdguardFilters/issues/139625#issuecomment-1376691006) that this gets "resolved" with the use of AdGuard VPN.

**Comment by PA1138** [comment]
Hey, AdGuard was just updated to version 7.12.4170.

So, I turned off AdGuard VPN and cleared browser cache and it seems to be working now. I also tried with different browsers and incognito and no issues have been observed.

Thanks.
