### ISSUE TITLE
Some element hiding rules sometimes are not applied on google/amp websites on Android

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#172]
Related to this issue - https://github.com/AdguardTeam/AdguardFilters/issues/10969
and this - https://github.com/AdguardTeam/AdguardFilters/issues/10560

I can reproduce these issues on my side with AdGuard 2.10.176 and Android 6.0
It seems that for some reason these rules (from English filter) are not applied:
`ampproject.org##amp-embed[type="taboola"]`
`##.commercial-unit-mobile-top`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/35822142-8a27affe-0aab-11e8-93de-fb1a6d008ce1.png)

</details>
<br>
It works if I add these rules to user filter.

**Comment by sfionov** [comment]
This is because of iframe. Now we have $domain modifier of cosmetic rules to handle this.
