### ISSUE TITLE
historyextra.com is broken by any AdGuard extension

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1722]
Original issue: https://github.com/AdguardTeam/AdguardFilters/issues/141249#issuecomment-1410572263

### Steps to reproduce

1. Disable Base filter or the rule in Base filter `@@||historyextra.com^$extension`
2. Enable any AdGuard extension
3. Go to https://www.historyextra.com/period/modern/britain-strikes-history-industrial-action/

### Actual behavior

When enabled any AdGuard extension, the site is broken (loads for a second and content is suddenly deleted).

The site is not broken, when extensions module is enabled, but all extensions are disabled.

Browser: Chrome 109
AdGuard for Windows 7.12 and AdGuard for Mac 2.9.2.1234

**Comment by AdamWr** [comment]
If I'm not wrong, it looks like that it's related to - https://github.com/AdguardTeam/CoreLibs/issues/1701 and https://github.com/AdguardTeam/CoreLibs/issues/1571

This rule:
```adblock
historyextra.com#%#(function(){window.DD_LOGS={onReady(){},logger:{log(){}}}})();
```
seems to works fine in this case too.

**Comment by Alex-302** [comment]
Ok, added your rule.
