### ISSUE TITLE
`Protect from DPI` does not work in nightly

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/CoreLibs#1723]
### Steps to reproduce

0. You need to be in Russia or another similar country with restrictions
1. Install AdGuard for Mac 2.10.0.1239 nightly
2. Make sure that `Protect from DPI` is enabled
3. Go to https://rutracker.org/forum/index.php or https://nnmclub.to

### Expected behavior

The blocked site opens.

### Actual behavior

The blocked site does not open.

<details><summary>Screenshot</summary>

</details>

### Customer ID

Sent to apple@adguard.com

### Your environment

* Environment name and version: Safari 16.3
* Any specific potentially conflicting software installed:

**Comment by zubrRB** [comment]
После обновления на 7.13 nightly 1 для Windows становится неактивна (и не работает) опция `Защищать от DPI`.
При попытке включить она самопроизвольно отключается после переключения на другой раздел меню настроек.

<details><summary>Screenshot:</summary>

![antidpi](https://user-images.githubusercontent.com/50718960/218057875-163bf45f-2f56-49de-82b2-50ebe14e39d6.png)

</details><br/>

**Comment by zubrRB** [comment]
Моя проблема исправлена в версии 7.13 nightly 2, причём даже опцию включать обратно не пришлось.
