### ISSUE TITLE
`$removeparam` does not modify a request having non-`200` status code and `GET` method

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/CoreLibs#1727]
### Summary
A `$removeparam` rule does not modify a HTTP request having `204` status code and `GET` method.

### Environment
 - Operating System: Microsoft Windows 11 22H2
 - Type of AdGuard products: AdGuard for Windows 7.12
 - Browsers: Google Chrome 110.0.5481.97; Mozilla Firefox Developer Edition 110.0b9

### How to reproduce
1. Apply the following rule:
    ```adblock
    ||search.naver.com/p/crd/rd$removeparam=s
    ``` 
2. Visit [here](https://search.naver.com/search.naver?sm=tab_hty.top&where=view&query=%EC%95%A0%EB%93%9C%EA%B0%80%EB%93%9C).
3. Scroll until new related search result appears.

**Comment by AdamWr** [comment]
The type of this request is showed as an `Image` in the filtering log.
And according to - https://adguard.com/kb/general/ad-filtering/create-own-filters/#removeparam-modifier
```
$removeparam rules that do not have any content type modifiers will match only requests where content type is document.
```

So this rule:
```adblock
||search.naver.com/p/crd/rd$removeparam=s,image
```
should works.
