### ISSUE TITLE
local.adguard.org problem when cached with ServiceWorker

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#1739]
local.adguard.org points to non-working IP, as designed. 

However, caching by ServiceWorkers are problem in this case, because when AdGuard protection is off, such sites can load infinitely, waiting for local.adguard.org.

We should detect this situation and add some hooks to prevent content with `local.adguard.org` from caching.

**Comment by ameshkov** [comment]
We're going to change the way `local.adguard.org` works and make it reset connection instead of dropping packets. It should help.

**Comment by ameshkov** [comment]
This one is resolved, it now resets the connection
