### ISSUE TITLE
Images are not displayed in Edge Bing Chat

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1744]
[https://www.microsoft.com/en-gb/edge?form=MA13FJ](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.microsoft.com%2Fen-gb%2Fedge%3Fform%3DMA13FJ)
### Comment
> AG prevents the Bing AI feature from... drawing images.
> 
> STR:
> 
> - Update to the most recent version of Edge (111.0.1661.62 in my case)
> - Click on the 'b' icon in the upper right to launch the dialogue
> - Ask it to draw an image (可以帮我画一个苹果？)
> 
> Expected: It show an image of an apple (2nd screenshot)
> 
> Actual behavior: It does not show any images
> 
> As soon as you stop AdGuard, it starts working as expected, i.e. shows images.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/FGNz25Y.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/iSnxedN.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.10.0.1270+nightly
Browser: | Edge 111.0.1661.62 (Chromium-based)
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (180), <br>Block Push API, <br>Block Location API, <br>Block Java
DNS filtering: | server: `sdns://AgcAAAAAAAAADDk0LjE0MC4xNC40OQAaZGIxYjY0NDIuZC5hZGd1YXJkLWRucy5jb20KL2Rucy1xdWVyeQ`<br>filters: `https://filters.adtidy.org/mac_v2/filters/15.txt`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>AdGuard Cookie Notices, <br/>AdGuard Popups, <br/>AdGuard Mobile App Banners, <br/>AdGuard Other Annoyances, <br/>AdGuard Widgets<br/><br/><b>Language-specific:</b><br/>AdGuard Russian, <br/>AdGuard German, <br/>AdGuard French, <br/>AdGuard Ukrainian, <br/>AdGuard Chinese, <br/>EasyList Czech and Slovak, <br/>EasyList Italy, <br/>Hungarian
Userscripts: | 全网VIP视频破解去广告免费看+全网音乐下载+知乎增强+短视频无水印下载+(url:+local),<br>AdGuard+Extra+(Beta)+(url:+https://userscripts.adtidy.org/beta/adguard-extra/1.0/adguard-extra.user.js)
Referrer: | [https://www.bing.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.bing.com%2F)

_Originally posted by @adguard-bot in https://github.com/AdguardTeam/AdguardFilters/issues/147117#issuecomment-1497191273_

**Comment by AdamWr** [comment]
It seems that this issue is not caused by filters, because it occurs even with all modules disabled.
I'm not sure exactly, but it's probably related to CSP.

This error occurs:
>Refused to display 'https://www.bing.com/' in a frame. The embedder requires it to enforce the following Content Security Policy: 'frame-src '*'; base-uri 'self'; script-src 'nonce-required' 'strict-dynamic';'. However, the frame neither accepts that policy using the Allow-CSP-From header nor delivers a Content Security Policy which is at least as strong as that one.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/230055558-76a4aa10-ff4e-48ec-adb6-92abb13a9dc3.png)

</details>

If I add these rules:
```adblock
@@||bing.com^$generichide,badfilter
@@||bing.com/search?$generichide,badfilter
@@||bing.com/search?showselans=$elemhide,jsinject,extension,content,important
```
to user rules, then images are displayed correctly and there is no such error related to CSP.

AdGuard for Windows version 7.13 nightly 8 (build 4242, CL 1.11.79)

**Comment by YelenaKoroleva** [comment]
A user from ticket [#740274](https://adguard.zendesk.com/agent/tickets/740274) added these user rules, however, the issue persists for them

**Comment by AdamWr** [comment]
User can try to add:
```adblock
@@||bing.com^$generichide,badfilter
@@||bing.com/search?$generichide,badfilter
@@||bing.com/search?showselans=$document
```
or
```adblock
@@||bing.com^$generichide,badfilter
@@||bing.com/search?$generichide,badfilter
@@||bing.com^$document
```
to user rules.

Although it will probably unblock ads on `bing.com` and I'm not sure if it will work because for whatever reason I don't have access to Edge Bing Chat anymore.

**Comment by sfionov** [comment]
The CSP is set on iframe inside edgeservice.bing.com/shell. We don't patch `csp` attributes on iframe yet.

This rule should be enough for now:
```
@@||bing.com/search?showselans=$document,frame,important
```

**Comment by sfionov** [comment]
csp attribute of iframe is something new: https://w3c.github.io/webappsec-cspee/

I think we should support it in one of future releases

**Comment by AdamWr** [comment]
> @AdamWr The CSP is set on iframe inside edgeservice.bing.com/shell. We don't patch `csp` attributes on iframe yet.
> 
> This rule should be enough for now:
> 
> ```
> @@||bing.com/search?showselans=$document,frame,important
> ```

The problem is that I cannot use Bing chat in the sidebar for whatever reason, so unfortunately I cannot check this rule.
I had Bing Chat in the sidebar before, but now there is only discover with news/trending search.

Does this rule work for you?

**Comment by sfionov** [comment]
@AdamWr Checked with both Win and Mac Bings, rule works for me.

On Windows, chat was unavailable with my current locale. I have to set English as main language in edge://settings/languages . After that, Chat works.

**Comment by AdamWr** [comment]
Thank you for checking it out, I have added this rule.

>On Windows, chat was unavailable with my current locale. I have to set English as main language in edge://settings/languages . After that, Chat works.

I have browser and system language set to English and Chat worked correctly before, I have no idea why it stopped working (and it still doesn't work) ¯\\\_(ツ)_/¯
