### ISSUE TITLE
Multiple videos can be run on vk.com at the same time

### ISSUE THREAD

**Issue by Aydinv13** [AdguardTeam/CoreLibs#1745]
@x0z21n commented on [Sun Apr 02 2023](https://github.com/AdguardTeam/AdguardForWindows/issues/4667)

### Issue Details

If you start watching a video with sound on the VK.com website, and then start another video, then the sound from the first video is superimposed on the sound from the second video.

### Proposed solution

Fix audio overlay in video

---

@Aydinv13 commented on [Thu Apr 06 2023](https://github.com/AdguardTeam/AdguardForWindows/issues/4667#issuecomment-1499112057)

@x0z21n Hello!

I can reproduce the issue. It seems that it's not just about the sound. Several videos from different tabs can run simultaneously, when there should only be one.

**Comment by zubrRB** [comment]
На сайте НТВ в левом нижнем углу миниатюрный плеер: бывает, что он скрыт, а звук от него все равно вовсю херячит.
