### ISSUE TITLE
CoreLibs proxy limits the maximum speed to about 1.4-1.5 Gbps

### ISSUE THREAD

**Issue by ijuliank** [AdguardTeam/CoreLibs#1746]
according to the issue at telegram, showing a user speed of 2.5gbit, was not reachable with adguard turned on
because 
![image](https://user-images.githubusercontent.com/64658680/230786531-51e8705c-f5aa-4c1b-934b-1415b7747fa4.png)

would be awesome if the speed will be even higher than that, since they are in the netherlands already testing 25gbit for a household

**Comment by ijuliank** [comment]
@ameshkov why not higher than 5 gbit?, 1.5gbit is low

**Comment by ameshkov** [comment]
Not sure what you mean here, I didn't mention 5 gbps anywhere. But generally, anything above 1Gbps is a pretty rare thing for consumer hardware. We'll look if there are any obvious optimizations that can be done on our side, but 25gbps is not our goal. I don't think we have hardware good enough to test it.

**Comment by ijuliank** [comment]
any clue in wich windows version this update comes?

**Comment by sfionov** [comment]
Seems that HTTP/2 upload needs an improvement too.

**Comment by sxgunchenko** [comment]
According to the measurements at the moment AdGuard has a throughput of around 3.5 Gbps in case of MITMing

**Comment by ameshkov** [comment]
@sxgunchenko hardware? :)

**Comment by sxgunchenko** [comment]
Oh, sure. :) I've tested it on MacBook Pro (2019) / 2,3 GHz 8-Core Intel Core i9.
