### ISSUE TITLE
Exception rules interfere with each other

### ISSUE THREAD

**Issue by jellizaveta** [AdguardTeam/CoreLibs#1749]
There are two rules in the Basic Filter (from EL) that don't work together:

`@@||www.google.*/search?$generichide`

`@@||www.google.*/search?$domain=google.ae|google.at|google.be|google.bg|google.by|google.ca|google.ch|google.cl|google.co.id|google.co.il|google.co.in|google.co.jp|google.co.ke|google.co.kr|google. co.nz|google.co.th|google.co.uk|google.co.ve|google.co.za|google.com|google.com.ar|google.com.au|google.com.br|google.com.co|google.com.ec|google.com.eg|google.com.hk|google.com.mx|google.com my|google.com.pe|google.com.ph|google.com.pk|google.com.py|google.com.sa|google.com.sg|google.com.tr|google.com.tw|google.com.ua|google.com.uy|google.com.vn|google.cz|google.de|google.dk|google. dz|google.ee|google.es|google.fi|google.fr|google.gr|google.hr|google.hu|google.it|google.lt|google.lv|google.nl|google.no|google.pl|google.pt|google.ro|google.rs|google.ru|google.se|google.sk`

because of this rule : `~hatena.ne.jp##a[href*="//b.hatena.ne.jp/entry/"]` links in google search results are hidden.

<details><summary>Screenshot:</summary>

https://www.google.com/search?q=inurl%3Ab.hatena.ne.jp%2Fentry

<img width="1020" alt="Screenshot 2023-04-12 at 17 09 15" src="https://user-images.githubusercontent.com/91964807/231483926-95ed7731-8885-4af2-aa70-1d7a00341775.png">

</details><br/>

Expected behavior: links are not hidden

<details><summary>Screenshot:</summary>

<img width="1125" alt="Screenshot 2023-04-12 at 17 10 45" src="https://user-images.githubusercontent.com/91964807/231484317-42b92632-ab6e-4b49-8d3e-b62c6b157406.png">

</details><br/>

When I disable one of the rules, the links appear.

https://github.com/AdguardTeam/tsurlfilter/issues/82

Exceptions have been added to the Social Media filter, pay attention to this when checking. https://github.com/AdguardTeam/AdguardFilters/commit/7d05d51da3cc498c9a4911e37393ca7627f4e758

**Comment by ameshkov** [comment]
Please see the discussion in that issue:
https://github.com/AdguardTeam/tsurlfilter/issues/82#issuecomment-1505384187

**Comment by ngorskikh** [comment]
@ameshkov In corelibs, we consider "exception rules with modifiers" the _lowest_ priority, and even have tests that test for that. It looks like the behaviour in the OP is correct. Furthermore, even if we were to shuffle priorities around, then it would only mean that the other rule from the OP would stop working and would become useless altogether. What if instead we started applying some rules (like generichide here) regardless if they are the first match from the urlfilter?

**Comment by ameshkov** [comment]
@ngorskikh I am not sure where this logic comes from, in theory the more specific the rule, the higher the priority should be.
