### ISSUE TITLE
AdGuard desktop version with ECH setting blocks access to domains if VPN extension is enabled

### ISSUE THREAD

**Issue by maxikuzmin** [AdguardTeam/CoreLibs#1751]
Go to AdGuard -> Advanced -> Advanced settings -> network.https.ech.enabled -> true
Connect to any location in AdGuard VPN extension in any browser
Try opening a website -> no access

**Comment by zubrRB** [comment]
Сегодня уже отключение использования ECH срабатывает без необходимости отключения DNS-защиты.
И тест `sni=encrypted` успешно проходит при использовании сторонней службы DNSCrypt (dnscrypt-proxy) по `127.0.0.1`.

**Comment by ameshkov** [comment]
@zubrRB в связке, но проще ECH отключить чем DNS.

Странно, что не помогло.

**Comment by zubrRB** [comment]
Сейчас уже помогает.
