### ISSUE TITLE
incorrect page filtering

### ISSUE THREAD

**Issue by jellizaveta** [AdguardTeam/CoreLibs#1763]
with all filters turned off, there is a lockout error

### Issue URL (Incorrect Blocking)
 [http://devfaq.ru/ru/search?tagid%5B2%5D=315&tagid%5B1%5D=1247&s=&p=1](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fdevfaq.ru%2Fru%2Fsearch%3Ftagid%255B2%255D%3D315%26tagid%255B1%255D%3D1247%26s%3D%26p%3D1)
### Comment
Username: @zubrRB
> заблокированы ответы.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/sKxJ1Hs.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/4Nsq07T.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.13+RC
Browser: | Chrome
AdGuard driver: | TDI
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (1), <br>Disable cache for third-party requests, <br>Block WebRTC, <br>Block Push API, <br>Block Location API, <br>Hide your Referrer from third-parties (example.com), <br>Hide your User-Agent (), <br>Hide your IP address ()
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Russian, <br/>AdGuard Ukrainian
Userscripts: | https://github.com/Owyn/HandyImage/raw/master/HandyImage.user.js,<br>https://greasyfork.org/scripts/14085-kinozal-tv-magnet-links/code/kinozaltv%20magnet%20links.user.js,<br>https://greasyfork.org/scripts/394820-mouseover-popup-image-viewer/code/Mouseover%20Popup%20Image%20Viewer.user.js,<br>https://download.sf-helper.com/chrome/helper.user.js,<br>https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js,<br>https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js

**Comment by ameshkov** [comment]
There's nothing we can do on our side at the moment, please solve this with filtering rules, but please add a detailed comment to that rule.

**Comment by AdamWr** [comment]
Done.

**Comment by zubrRB** [comment]
With this rule, in some places you get an incoherent set of words and important pieces of text are missing.

**Comment by AdamWr** [comment]
@zubrRB Could you please check these rules:
```adblock
@@||devfaq.ru/js/lst_ans_att.js$replace=/"mck"!=a/1===1/,script,domain=devfaq.ru
||devfaq.ru/js/lst_ans_att.js$replace=/getResponseHeader\("Content-MD5"\):a/getResponseHeader("Content-MD5"):'a1f7a9ec9f5115dd07a0a015a0238828'/,script,domain=devfaq.ru
```

**Comment by zubrRB** [comment]
Better, but also has problems.

![-](https://github.com/AdguardTeam/CoreLibs/assets/50718960/038e31a2-2e15-40bf-bbe0-30dceb951137)

**Comment by AdamWr** [comment]
It looks it depends on `Content-MD5` and if it will be changed then it might stop working again.
Could you please check these rules:
```adblock
@@||devfaq.ru/js/lst_ans_att.js$replace=/"mck"!=a/1===1/,script,domain=devfaq.ru
@@||devfaq.ru/*/search?*&method=HEAD$xmlhttprequest,document
```
I didn't notice before that there can be added exception for this request.

**Comment by zubrRB** [comment]
It seems now working fine.

**Comment by AdamWr** [comment]
I have added this rule.
Thank you for checking it out.
