### ISSUE TITLE
Content script is not injected into elements loaded in <object> tag

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1769]
Steps to reproduce:
1. Add these rules:
```adblock
youtube.com##body
youtube.com#%#alert(1);
```
2. Navigate to - https://example.org/
3. In browser console run:
```js
(() => {
  const video = '<object data="https://www.youtube.com/embed/YW9Ojcm1Gkg" style="height: 300px; width: 600px;"></object>';
  const createDiv = document.createElement("div");
  document.body.appendChild(createDiv);
  createDiv.innerHTML = video;
})();
```

### Actual behavior
It looks like that request is detected as a `media` type (though I'm not sure if it's the reason of not applying rules) and rules are not applied.

<details><summary>Screenshots</summary>

![image](https://github.com/AdguardTeam/CoreLibs/assets/29142494/66743b8a-217f-4904-9888-4391a34b6695)

![image](https://github.com/AdguardTeam/CoreLibs/assets/29142494/4a829f2a-56e6-4721-8997-79419b335274)

![image](https://github.com/AdguardTeam/CoreLibs/assets/29142494/d057f8d6-f9de-41f2-bec5-ac092b7e44cf)

</details>

### Expected behavior
Rules should be applied - website in the `object` tag should be blank and there should be message `1`.

AdGuard for Windows 7.13 nightly 16 (build 4279, CL 1.11.111)

**Comment by ameshkov** [comment]
Hmm, interesting, I didn't know object could be used as an iframe.

@sfionov sounds like a legit bug to me, but should be handled carefully.

**Comment by sfionov** [comment]
Yeah, and browser sends `Sec-Fetch-Dest: object` in this case, but it sends it also when object in not iframe-like.

**Comment by AdamWr** [comment]
I'm not aware of any reports (reported by users) with mentioned issue, but I noticed this problem in this case - https://github.com/AdguardTeam/AdguardFilters/issues/152618

There is a video player in some offers, for example here -  [https://www.evium.de/carmarket/details/4fbb8fe5-e1e4-4c14-8b1c-ae4386058a2c](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://www.evium.de/carmarket/details/4fbb8fe5-e1e4-4c14-8b1c-ae4386058a2c) and ad markers are not hidden in the youtube video player, because cosmetic rules are not applied.

<details><summary>Screenshot</summary>

![image](https://github.com/AdguardTeam/CoreLibs/assets/29142494/0484df99-9e85-4882-a5d5-d32d658a475b)

</details>
