### ISSUE TITLE
Improve HTML filtering performance

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1772]
Currently, HTML filtering adds quite a noticeable overhead to the overall page loading speed.

### Steps to reproduce

1. Open `view-source:https://www.rbc.ru/`
2. Measure the loading time (in my case it's about 200ms)
3. Now add this rule to the user rules: `@@||rbc.ru^$content`
4. Refresh the page a few times and measure the loading time
5. In my case it's about 400ms on average, so a 200ms overhead

What is it that slows it down that much?

### Things to do

1. Change the way it works and keep the overhead in acceptable limits.
2. Add performance tests specifically for HTML filtering, we shouldn't miss this again.

**Comment by sfionov** [comment]
We sped things up in CL1.13. However, it may take some time before first CL1.13 nightlies.

**Comment by SeriousHoax** [comment]
> Hi, is there a chance you can backport this fix to CL 1.12 and release with AdGuard 2.12 ?

It would be great if this can be done.

> We sped things up in CL1.13. However, it may take some time before first CL1.13 nightlies.

Can you give us an ETA on this? When can we expect a CL 1.13 based Nightly to be released that contains this fix?

**Comment by ameshkov** [comment]
Expect the first nightlies with it in about 2 weeks from now. There're quite a lot of changes in v1.13, backporting would be problematic.
