### ISSUE TITLE
Explore the protobuf inspection algorithm for YouTube

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1778]
We had `$protobuf` modifier before and it was there specifically for YouTube. Unfortunately, it didn't help us and the ads were still there in the app.

It seems we may have got something wrong.

Please check out the article and the script that removes ads from YT:
https://ericdraken.com/pfsense-decrypt-ad-traffic/#script

Let's think if this can be changed to a declarative approach.

**Comment by ngorskikh** [comment]
The linked approach doesn't seem to work anymore.
