### ISSUE TITLE
Issue with executing userscripts inside frames that require TrustedTypes

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1779]
See the linked issue: https://github.com/Rob--W/dont-track-me-google/issues/53

**Comment by ameshkov** [comment]
@dnmTX

> Slimjet Version 39.0.2.0 (based on Chromium 111.0.5563.41) (Official Build) (64-bit)

Can it be reproduced with Chrome?

**Comment by dnmTX** [comment]
> Can it be reproduced with Chrome?

I unfortunatelly have only Slimjet installed,no other browsers are present here. Trying to keep it tight and clean on my end 😉

**Comment by temis2k16** [comment]
Issue is reproduced with AG and with Tampermokey in Chrome. Can't be reproduced in Firefox. Maybe some security updates in latest chromium could cause the problem and require a workaround on AG side ?

**Comment by zubrRB** [comment]
The developer of the user script of the Mouseover Popup Image Viewer a few days ago made it so that his script began to work, for example, in the comments of Disqus. https://github.com/tophf/mpiv/commits/master

**Comment by zubrRB** [comment]
The developer of the userscript MPIV @tophf I mentioned above is also one of the developers of the Violentmonkey.

**Comment by zubrRB** [comment]
The developer of the userscript MPIV @tophf mentioned above is also one of the developers of the Violentmonkey.
