### ISSUE TITLE
Filtering Log Still Not Fixed After 5 Years

### ISSUE THREAD

**Issue by jputting** [AdguardTeam/CoreLibs#1783]
The design of Adguard's Filtering Log doesn't recognise when parts of a webwpage are blocked by Cosmetic/Element hiding rules, they can be in a subscribed to Filter Lister or a Custom User Created Rule.

This badly designed Filtering Log makes it extremely difficult to determine what is blocking parts of a webpage.

This should NOT be the case, ALL BLOCKED ITEMS should be reported.

This is in a fact a Technical Issue which is created by the badly designed Filtering Logs.

Adguard have stubbornly refused to acknowledge there is a problem created by the Filtering Logs.

This was raised 5 years ago on the Github Forums
Here's the link: [https://github.com/AdguardTeam/CoreLibs/issues/180](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fadguardteam.github.io%2FAnonymousRedirect%2Fredirect.html%3Furl%3Dhttps%253A%252F%252Fadguardteam.github.io%252FAnonymousRedirect%252Fredirect.html%253Furl%253Dhttps%25253A%25252F%25252Fgithub.com%25252FAdguardTeam%25252FCoreLibs%25252Fissues%25252F180)

The Adguard Filtering Log is still NOT fixed after 5 years.

It is absolutely disgusting and very shameful conduct that this was raised on Github 5 very, very long years ago and Adguard have done absolutely NOTHING TO FIX THEIR FILTERING LOGS.

With various other ad blockers such as ublock Origin, the filtering logs do clearly show when a Cosmetic or User/Custom rule is in effect.

When Blocked Items are NOT REPORTED AT ALL, do you understand that this makes discovering the source of a webpage problem an extremely time consuming, difficult and painstaking process.
To discover the source of the problem I literally had to spend several hours of my valuable time disabling each and every single Adguard function one at a time and then reloading the webpage until I discovered the source of the problem.

It is absolutely disgusting and quite shameful that after 5 very, very long years Adguard has still done absolutely NOTHING about this.

**Comment by ameshkov** [comment]
Addressed it here: https://github.com/AdguardTeam/CoreLibs/issues/1784#issuecomment-1649284401
