### ISSUE TITLE
Improve GM_xmlhttpRequest support

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/CoreLibs#1786]
### Summary
`GM_xmlhttpRequest` and `GM.xmlhttpRequest` API that are used in [List-KR/linkproduct-privacy](https://github.com/List-KR/linkproduct-privacy) does not work.
It seems that it is related to lack of AdGuard userscript module's API support.

### Used `GM.xmlhttpRequest` API
`details.url`, `details.method`, `details.responseType`, `details.anonymous`, `details.onload` and `ResponseObject.finalUrl`.

https://violentmonkey.github.io/api/gm/#gm_xmlhttprequest

### References
 - https://github.com/AdguardTeam/CoreLibs/issues/1780
 - https://github.com/List-KR/linkproduct-privacy (Tested version: modified 1.0.1)

**Comment by sfionov** [comment]
This may be caused by same issue as #1785
