### ISSUE TITLE
Support anti-DPI feature for Korea Telecom

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/CoreLibs#1789]
In 2019, South Korean government announced that they use SNI snooping to censor HTTPS websites [^1][^2].

Currently, AdGuard can neutralize DPI systems of [SK Telecom](https://en.wikipedia.org/wiki/SK_Telecom) and [LG U+](https://en.wikipedia.org/wiki/LG_Uplus).
But, DPI system of [Korea Telecom](https://en.wikipedia.org/wiki/KT_Corporation), one of major telecommunication companies of South Korea, cannot be neutralized with AdGuard.

In public, [Unicorn HTTPS](https://getunicorn.app/ko/product/unicorn-https/windows), an anti-DPI program made by Unicornsoft Co Ltd [^3], is widely used for neutralizing the system if a visitor in South Korea doesn't want to use a VPN to neutralize.

[^1]: https://www.forbes.com/sites/davidvolodzko/2019/02/25/is-south-korea-sliding-toward-digital-dictatorship/#62bc1ea2648e
[^2]: https://en.wikipedia.org/wiki/Internet_censorship_in_South_Korea
[^3]: Also, they are developer of [Unicorn Pro adblocker](https://getunicorn.app/ko/product/unicorn-pro/windows).

**Comment by piquark6046** [comment]
In fact, I already tested at June 14 (KST) with AdGuard for Android 4.0 stable.
I cannot access `https://www.womenonweb.org` via my school network using KT with the following configuration:

 - HTTP space juggling + ClientHello fragment 1 + HTTP request fragment 1
 - HTTP space juggling + ClientHello fragment 16 + HTTP request fragment 16
 - ClientHello fragment 16 + HTTP request fragment 16
 - ClientHello fragment 1 + HTTP request fragment 1

> **Note**: the number 16 is blurred in my memory.

**Comment by ameshkov** [comment]
@sfionov I'll order a residential proxy with KST so that we could test it on our side.

**Comment by piquark6046** [comment]
Also, referring the following list can be helpful:
 - PetuBucket ( `https://petubucket.com/` )
 - Many pron websites (examples)
    - `https://hitomi.la/`
    - `https://www.pornhub.com/`
    - `https://xvideos.com/`
    - `https://www.fakku.net/`

**Comment by piquark6046** [comment]
Please reconsider priority of this issue.
This issue can be a fork of choosing between Unicorn Pro adblocker or AdGuard.

**Comment by sfionov** [comment]
@piquark6046 We found a solution and it will be implemented in CoreLibs version currently in development

**Comment by piquark6046** [comment]
The issue is being watched by someone who wants to switch from Unicorn Pro adblocker to AdGuard if the issue is resolved:
 - https://gall.dcinside.com/mgallery/board/view/?id=galaxy&no=998970
 - https://gall.dcinside.com/mgallery/board/view/?id=galaxy&no=999759

**Comment by hsp1020** [comment]
I am korean KT user. I look forward to solving this problem. Due to this issue I have deleted AdGuard and am using Unicorn Pro.

**Comment by hsp1020** [comment]
> @hsp1020 Do you want to experience like Unicorn Pro adblocker with AdGuard? If so, can you describe it?

I don't know what you're talking about. What can I describe to you?

**Comment by hsp1020** [comment]
> @hsp1020 Do you want to experience like Unicorn Pro adblocker with AdGuard? If so, can you describe it?

What exactly should I do?

**Comment by piquark6046** [comment]
@hsp1020 
The question is what the advantage and disadvantage between them when they are compared.

**Comment by hsp1020** [comment]
> @hsp1020 The question is what the advantage and disadvantage between them when they are compared.

Yes,  i can compare the two apps to explain their relative advantage and disadvantage.

**Comment by hsp1020** [comment]
> @hsp1020 The question is what the advantage and disadvantage between them when they are compared.

@piquark6046 
Yes,  i can compare the two apps to explain their relative advantage and disadvantage.

The advantages of Unicorn Pro over AdGuard are 1.KT dpi support (this issue), 2.Web browser Assistant support for Android,  3.Optimized for Korean websites and apps, and faster. Especially in Korea, more than 50% of users use KT. However, because of this issue, many korean users are using Unicorn pro instead of Adguard.

Advantages of AdGuard over Unicorn Pro are 1.DNS filter selectable, 2.There are various types of built-in filters. 3.Block more ads on websites outside of Korea 4.Tracking protection (stealth mode) is more powerful. the default functionality is more power

**Comment by piquark6046** [comment]
> 3.Optimized for Korean websites and apps, and faster. Especially in Korea, more than 50% of users use Korea Telecom. However, because of this issue, many korean users are using Unicorn pro instead of Adguard.

Have you ever tested with only List-KR filter excluding other filters?
And, do you hear about https://github.com/List-KR/filter-customizer that is in development?

**Comment by hsp1020** [comment]
@piquark6046

Yes, I have tested only with List-KR filters except for other filters. However, Unicorn Pro can also use the list-kt filter. The speed difference on the Korean site is estimated to be the difference between the base filters embedded in the two apps. And the biggest reason why Koreans use Unicorn Pro instead of AdGuard is whether it is Support anti-DPI feature for Korea Telecom.

**Comment by piquark6046** [comment]
> However, Unicorn Pro can also use the list-kt filter. 

No. Unicorn Pro adblocker cannot use List-KR filter right now even if the filter can be registered in app.
Unicorn Pro does not support scriptlet, redirection resources, etc that resolve many advertisement and almost anti-adblock script.

**Comment by hsp1020** [comment]
I was wrong about that part. I thought it was working because I could add it to the Unicorn pro filter list. However, for Koreans, the most important part when choosing AdGuard and Unicorn Pro is not whether the list-KR filter is supported, but whether Korea Telecom supports anti-DPI functions. If this issue is not resolved, many Koreans will use Unicorn Pro.

**Comment by piquark6046** [comment]
> This is because even if list-KR does not support Unicorn pro, most advertisements on Korean sites are blocked only by Unicorn pro base filters.

There is common advertisement servers that are used in Korean language websites and other language websites.
For example, Google Ads is used in almost websites regardless of language of a website.

**Comment by hsp1020** [comment]
@piquark6046 
Unicorn Pro also has a dedicated Korean filter that is set by default. As a result, advertisements in Korean can be blocked at a similar level to list-KR. Therefore, whether to support for list-KR is not an important part for Koreans.

**Comment by piquark6046** [comment]
> Unicorn Pro also has a dedicated Korean filter that is set by default. As a result, advertisements in Korean can be blocked at a similar level to list-KR. Therefore, whether to support for list-KR is not an important part for Koreans.

List-KR filter can block advertisements on copyright-abusing torrent and streaming websites as this is mentioned in https://gall.dcinside.com/mgallery/board/view/?id=galaxy&no=998970.
Also, List-KR filter can block Naver PowerLink advertisements on m.humoruniv.com using scriptlets without changing the related rules regularly.

List-KR filter uses scriptlet to mitigate DNS filtering exception.

**Comment by hsp1020** [comment]
@piquark6046 
list-KR filters may perform better than Unicorn pro Korea filters. However, there are many sites that are not accessible in Korea unless Adguard supports Anti-DPI function for Korean Telecom. (Most of the torrents and streaming websites you mentioned are also not accessible.) This dilutes the advantages of list-KR.

**Comment by piquark6046** [comment]
For a visitor who is interested in the issue, currently updated CoreLibs have not been applied CoreLib-based AdGuard program [^1].

[^1]: AdGuard for Windows, AdGuard for Android and AdGuard for Mac

To see what CoreLibs version of AdGuard you use, please refer https://adguard.com/en/versions/windows/release.html.

**Comment by sfionov** [comment]
Adguard for Android 4.3 nightly 19 is out with CoreLibs 1.13

**Comment by piquark6046** [comment]
@hsp1020 @NoName926 Did you test with KT mobile network?

**Comment by zelesdev** [comment]
KT network dpi bypass is not applied even on Android 4.3 nightly 20
It is not a kt mobile network

**Comment by piquark6046** [comment]
Maybe we can receive what is wrong in the coming week.

**Comment by hsp1020** [comment]
> Maybe we can receive what is wrong in the coming week.

Even at home, my phone is using kt (kt mobile), but I updated it to the latest Nightly version, but this problem is not being solved.

**Comment by piquark6046** [comment]
Unfortunately, The checking will be delayed until Nov 13 at least.

**Comment by JadeMin** [comment]
the same problem here

**Comment by piquark6046** [comment]
The delaying between split chunks feature that can help to bypass the DPI system is not included in any AdGuard nightly.
If it is included, you can configure the option in the section where is located:
 - AdGuard for Android: Protection tab -> Tracking protection (privacy protection level: custom) -> Protect against DPI.
 - AdGuard for Windows: AdGuard settings -> General tab -> Advanced Settings

**Comment by sfionov** [comment]
@piquark6046 @hsp1020 @NoName926 Does it work better on 4.3 nightly 32?

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/CoreLibs/issues/1789#issuecomment-1812793591 I don't have a SIM card for KT network. But, if the team wants, I can request for creating one.

**Comment by hsp1020** [comment]
> @피쿼크6046 @hsp1020 @NoName926 4.3 야간 32일 더 잘 작동합니까?



> @piquark6046 @hsp1020 @NoName926 Does it work better on 4.3 nightly 32?

For KT users, the dpi function does not work even with version 4.3 nightly 32.

**Comment by hsp1020** [comment]
> @piquark6046 @hsp1020 @NoName926 Does it work better on 4.3 nightly 32?

For kt users, the anti-dpi feature does not work even with version 4.3 nightly 32.

**Comment by 3k2jd0j2k** [comment]
It doesn't work  in  Android 4.3 nightly 33 too

**Comment by piquark6046** [comment]
Does adjusting [the option](https://github.com/AdguardTeam/CoreLibs/issues/1789#issuecomment-1803401640) not help?

**Comment by sfionov** [comment]
In our tests this option helps for HTTP:
<img width=250 src=https://github.com/AdguardTeam/CoreLibs/assets/47204/38cecf66-d633-43fe-a312-b4565a4bdcca></img>

**Comment by 3k2jd0j2k** [comment]
https://github.com/AdguardTeam/CoreLibs/assets/75906867/971cd408-389f-487e-95ee-cf9c73542840

watch this video. 1.1.1.1 or unicorn app can bypass kt dpi

**Comment by piquark6046** [comment]
The update that includes the split delay will be released in AdGuard for Android nightly this week.

**Comment by sfionov** [comment]
4.3 beta 1 is out, where new stealth mode setting persists. Can you please try with the following settings?

1. Stealth mode on
2. Protect from DPI on
2.1. Split ClientHello offset = 1
2.2. Split HTTP offset = 1
2.3 Split delay ms = 100 (I tested 50 and 100, and 50 not always worked)
3. DNS protection is on and use secure server

**Comment by sfionov** [comment]
@haksal732 If you enter site address with `https://` prefix, does it work?

**Comment by goINTo425** [comment]
> @haksal732 If you enter site address with `https://` prefix, does it work?

It doesn't work for me either.

**Comment by 3k2jd0j2k** [comment]
not working for all kt users. need fix something

**Comment by sfionov** [comment]
Seems that in our tests we used wrong proxy list for KT.

Now we've reproduced a particular blocking page and we continue to find correct blocking parameters.

**Comment by piquark6046** [comment]
Can we keep the current anti-DPI configuration feature [^1] for the non-KT ISP users? 
https://github.com/orgs/List-KR/discussions/52

[^1]: Split ClientHello offset, Split HTTP offset, Split delay and HTTP space juggling.

**Comment by piquark6046** [comment]
And, we need to investigate how AdGuard CoreLib-based app bypasses the HTTP censorship of the SKT network. The censorship can be bypassed by Unicorn HTTPS app.
https://github.com/orgs/List-KR/discussions/52#discussioncomment-7956736

**Comment by goINTo425** [comment]
@sfionov Can you give me a rough timeline for when this feature will be available?

**Comment by piquark6046** [comment]
https://gall.dcinside.com/mgallery/board/view/?id=sff&no=941895

**Comment by scor2** [comment]
The official release notes for ADGUARD 4.3.1 say that it supports the KOREA TELECOM (KT) ANTI-DPI feature, so why is it still not working?
I update NIGHTLY BUILD every week, but the problem is not solved at all.
KT is number 1 in Korea with 41% share of wired internet and number 2 in cellular with 21% share.
This issue must be resolved if ADGUARD is not to abandon the Korean market.
There is already an alternative called [UNICORN PRO](https://getunicorn.app/ko/product/unicorn-pro/android) in Korea, and new KT users are buying UNICORN PRO because of the ADGUARD ANTI-DPI issue.

**Comment by sfionov** [comment]
@scor2 Sorry for delay in resolving of this issue, our team was too busy last months. We will try a pair of other methods before CL1.14 release.

**Comment by uaevuon** [comment]
Also not works on DLIVE ISP

**Comment by scor2** [comment]
AdGuard 4.4 Nightly 37 still does not work with anti-DPI on KT.
I also applied the settings you mentioned above.
Stealth mode on
Protect from DPI on
2.1. Split ClientHello offset = 1
2.2. Split HTTP offset = 1
2.3 Split delay ms = 100 (I tested 50 and 100, and 50 not always worked)
2.4 HTTP space juggling - On
DNS protection is on and use secure server

**Comment by sfionov** [comment]
@scor2 We implemented a new method in CL1.14 but it may take some time for new setting to show up in UI in nightlies. I'll say when it will happen.

**Comment by piquark6046** [comment]
An AdGuard member tested an internal development version of AdGuard for Windows to do QA with an actual IP address of KT located in Jeollabuk-do province yesterday.

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/CoreLibs/issues/1789#issuecomment-1994528861
It does work.

**Comment by uaevuon** [comment]
> [#1789 (comment)](https://github.com/AdguardTeam/CoreLibs/issues/1789#issuecomment-1994528861)
> 
> > An AdGuard member tested an internal development version of AdGuard for Windows to do QA with an actual IP address of KT located in Jeollabuk-do province yesterday.
> 
> It does work.

How about D'LIVE?

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/CoreLibs/issues/1789#issuecomment-1996616666
> How about D'LIVE?

Can you tell me what is your ASN name?
Please check at https://ipinfo.io/.

**Comment by Kinomerc** [comment]
> AdGuard 4.4 Nightly 37 still does not work with anti-DPI on KT. I also applied the settings you mentioned above.
> 
> 1. Stealth mode on
> 2. Protect from DPI on
>    2.1. Split ClientHello offset = 1
>    2.2. Split HTTP offset = 1
>    2.3 Split delay ms = 100 (I tested 50 and 100, and 50 not always worked)
>    2.4 HTTP space juggling - On
> 3. DNS protection is on and use secure server

![스크린샷 2024-03-14 161102](https://github.com/AdguardTeam/CoreLibs/assets/96902592/87f14c70-0e0b-4a64-815c-94fa0ab1eaaa)

it works

check your [General Settings] - [Advanced Setting] - [Korea Telecom DPI Protection] is off

**Comment by scor2** [comment]
> > AdGuard 4.4 Nightly 37 still does not work with anti-DPI on KT. I also applied the settings you mentioned above.
> > 
> > 1. Stealth mode on
> > 2. Protect from DPI on
> >    2.1. Split ClientHello offset = 1
> >    2.2. Split HTTP offset = 1
> >    2.3 Split delay ms = 100 (I tested 50 and 100, and 50 not always worked)
> >    2.4 HTTP space juggling - On
> > 3. DNS protection is on and use secure server
> 
> ![스크린샷 2024-03-14 161102](https://private-user-images.githubusercontent.com/96902592/312737070-87f14c70-0e0b-4a64-815c-94fa0ab1eaaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDM0ODEsIm5iZiI6MTcxMDQwMzE4MSwicGF0aCI6Ii85NjkwMjU5Mi8zMTI3MzcwNzAtODdmMTRjNzAtMGUwYi00YTY0LTgxNWMtOTRmYTBhYjFlYWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA3NTk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwODg5OGYzMzIwNGI3MzcxM2FjZTE1ZjZiYzE4NzI2M2ZjYmRiNzhmMGJiNzE5OGU1ZmU3NGQ3MWNkMzI1NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WfZLInKZ21VoHmWUt2LfIKUPFUu02erB3bxIt_vm0C0) ![스크린샷 2024-03-14 163103](https://private-user-images.githubusercontent.com/96902592/312741069-1e1b45c6-cfcb-40bc-8374-a79449186c10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDM0ODEsIm5iZiI6MTcxMDQwMzE4MSwicGF0aCI6Ii85NjkwMjU5Mi8zMTI3NDEwNjktMWUxYjQ1YzYtY2ZjYi00MGJjLTgzNzQtYTc5NDQ5MTg2YzEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA3NTk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ZmU1MzEwMTNkNjVhYjVjOTAzNTcwM2QyZTE4MzA4NjJkNjk1NmE0OTAxNjI4MWNjYTM4MTM3YjU0MzFiZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._j-mX2PzQrvrLuMvpwuoQIiwTg1MpllE9hq0dQqzws8)
> 
> it works at kt network
> 
> check your [General Settings] - [Advanced Setting] - [Korea Telecom DPI Protection] is off

Did you found Korea Telecom DPI Protection option on Android?
Other users have also reported finding the option on Windows and MAC platforms, but not on Android.
I'll try uninstalling and reinstalling the app first.

**Comment by piquark6046** [comment]
@scor2 https://github.com/AdguardTeam/CoreLibs/issues/1789#issuecomment-1994370128
I think that it is not applied into the UI yet.

**Comment by uaevuon** [comment]
> [#1789 (comment)](https://github.com/AdguardTeam/CoreLibs/issues/1789#issuecomment-1996616666)
> 
> > How about D'LIVE?
> 
> Can you tell me what is your ASN name? Please check at https://ipinfo.io/.

asn: "AS10036",
name: "DLIVE",
domain: "dlive.kr"

**Comment by uaevuon** [comment]
> @uaevuon Does [#1789 (comment)](https://github.com/AdguardTeam/CoreLibs/issues/1789#issuecomment-1996725638) not work?

I never used Windows version before, so I just installed and tested it. Works on D'LIVE.
Any ETA for android version?

**Comment by uaevuon** [comment]
> @uaevuon Does [#1789 (comment)](https://github.com/AdguardTeam/CoreLibs/issues/1789#issuecomment-1996725638) not work?

I've never used Adguard on Windows, so just installed and tested it.
Works on D'LIVE.
Any ETA for android version?

**Comment by 3k2jd0j2k** [comment]
> > it works at kt network
> > check your [General Settings] - [Advanced Setting] - [Korea Telecom DPI Protection] is off
> 
> Did you found Korea Telecom DPI Protection option on Android? Other users have also reported finding the option on Windows and MAC platforms, but not on Android. I'll try uninstalling and reinstalling the app first.



> @scor2 We implemented a new method in CL1.14 but it may take some time for new setting to show up in UI in nightlies. I'll say when it will happen.

android user waited for 2weeks...check plz

**Comment by piquark6046** [comment]
@3k2jd0j2k 

> It is in progress by design team, it was also renamed to not to mention trademarks

**Comment by ameshkov** [comment]
Sorry for the delay, it's coming soon I promise.

The predicament is rather simple: we initially called this feature `Korea Telecom DPI Protection` while in fact it is not specified to Korea, it's just another rather popular method of anti-DPI protection: increasing the first packet size so that the hostname information was shifted to the second packet.

**Comment by ameshkov** [comment]
@sfionov new issue here?

**Comment by sfionov** [comment]
@ameshkov No, just leaving it open until it is deployed to every platform

**Comment by Kinomerc** [comment]
![Screenshot_20240418_230435_AdGuard](https://github.com/AdguardTeam/CoreLibs/assets/96902592/37f45590-b8d1-4dd1-93e7-e5338081b193)
is this new trademark you have made for 2 weeks? or still in progress?

**Comment by Kinomerc** [comment]
![Screenshot_20240418_230435_AdGuard](https://github.com/AdguardTeam/CoreLibs/assets/96902592/5aea3365-bb93-4810-b15d-3689119e344d)
is this new trademark you have made for 2 weeks? or still in progress?

**Comment by sfionov** [comment]
@Kinomerc You guessed right, this is exact option that should work for Korean providers.

It is already in the latest nightly on Android, and the latest betas on Windows and Mac.

**Comment by ScathachSkadi** [comment]
Thanks for making this happen. I had both Unicorn pro and Adguard and I completely ditched Unicorn now. Working fine so far on MacOS normal release and Android Nightly.

**Comment by uaevuon** [comment]
Finally removed unicorn shit on my phone.

**Comment by zubrRB** [comment]
Release AdGuard v7.17 for Windows. 

![7 17](https://github.com/AdguardTeam/CoreLibs/assets/50718960/a026e3b5-b8fc-460e-8bdc-31bd30f0289c)

**Comment by Taewan-P** [comment]
From what version is this feature supported? I just checked out the 4.4 Release of Android with this issue linked in release notes but I don't see any of the settings inside the app.

**Comment by sfionov** [comment]
@Taewan-P Protection -> Tracking protection -> Custom -> Protect against DPI -> Increase first packet size

**Comment by Taewan-P** [comment]
@sfionov Thank you for the kind reply. It was hidden under Custom 😅

**Comment by ScathachSkadi** [comment]
On the latest Android nightly, the feature doesn't seem to work on WiFi. On Cellular data it works, but not on WiFi. Both Korea Telecom of course.

**Comment by piquark6046** [comment]
@ScathachSkadi Please try its stable channel again.

**Comment by ScathachSkadi** [comment]
@piquark6046 I can confirm stable works.

**Comment by juicycool92** [comment]
> @uaevuon Does [#1789 (comment)](https://github.com/AdguardTeam/CoreLibs/issues/1789#issuecomment-1996725638) not work?

i did work on latest stable build on mac and windows. ( July 9, 2024 )
each platforms options labels are differences but yes, its worked!

**Comment by juicycool92** [comment]
Is there any plan for support iOS version too? I checked testflight version but options are not implemented on iOS yet i guess.

**Comment by Kinomerc** [comment]
> iOS 버전도 지원할 계획이 있나요? 테스트플라이트 버전을 확인했지만 아직 iOS에서 옵션이 구현되지 않은 것 같아요.

the feature is seen as a corelib feature.
As you can see in update log, unless corelib is supported by ios, i think it seems unlikely to be implemented

**Comment by juicycool92** [comment]
> > iOS 버전도 지원할 계획이 있나요? 테스트플라이트 버전을 확인했지만 아직 iOS에서 옵션이 구현되지 않은 것 같아요.
> > the feature is seen as a corelib feature.
> > As you can see in update log, unless corelib is supported by ios, i think it seems unlikely to be implemented

Thankyou for reply!

**Comment by Kinomerc** [comment]
https://gall.dcinside.com/mgallery/board/view/?id=adguard&no=10335
https://gall.dcinside.com/mgallery/board/view/?id=adguard&no=10331
https://gall.dcinside.com/mgallery/board/view/?id=adguard&no=10326
https://gall.dcinside.com/mgallery/board/view/?id=adguard&no=10348
KT internet users said the anti-DPI solution does not work AGAIN

https://gall.dcinside.com/mgallery/board/view/?id=adguard&no=10364
https://gall.dcinside.com/mgallery/board/view/?id=adguard&no=10341
If they use other anti-DPI programs, they work fine
only AdGuard's anti-DPI solution seems to be ineffective
