### ISSUE TITLE
No access to web pages when running with Screen Time

### ISSUE THREAD

**Issue by Aydinv13** [AdguardTeam/CoreLibs#1790]
### AdGuard version

2.11

### Browser version

-

### OS version

Ventura 13.4

### Issue Details

Steps to reproduce:
1. Open AdGuard (default settings)
2. Go to system `settings - Screen Time - Content&Privacy - Content Restrictions - Access to Web Content - Limit Adult Websites - Customize` then add `example.org` to Restricted sites
3. Open any browser and search for anything.

### Expected Behavior

No issues while surfing websites

### Actual Behavior

Websites don't open

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by sfionov** [comment]
Content filtering of screen time is breaking AdGuard as well as many other filtering apps, may break VPNs also.

It is recommended to turn off "Content & Privacy" of "Screen time" (*reboot is needed to fully turn off it*), and use AdGuard's functionality instead.

**Comment by ameshkov** [comment]
@Stillness-2 can we detect screen time and and alert the user about it?

**Comment by Stillness-2** [comment]
Unfortunately, there is no way to clearly detect that content filtering of screen time is enabled.
