### ISSUE TITLE
One empty line is added when add a comment on the Naver site.

### ISSUE THREAD

**Issue by Kieaer** [AdguardTeam/CoreLibs#1804]
![Screenshot_20230908-175115_Firefox_Beta](https://github.com/AdguardTeam/CoreLibs/assets/44261958/aba62f87-0f17-45e2-b9df-6dc4f19998ca)

Using Adguard for Android 4.1

How to Reproduction (Require NAVER account)
1. Open cafe.naver.com and go to any cafe site using Firefox android browser.
2. Add comment to any posts
3. You can now see the first blank line inserted.

**Comment by grumaxxx** [comment]
@Kieaer Could you please collect logs with logging level - Debug ([How to do it](https://adguard.com/kb/adguard-for-android/solving-problems/log/)) and send them to our e-mail `devteam@adguard.com` (mentioning in the subject line the number of this issue and the time of reproduction).

**Comment by Kieaer** [comment]
@grumaxxx sented.

**Comment by grumaxxx** [comment]
@Kieaer Got them, thanks!

**Comment by grumaxxx** [comment]
@Kieaer 
I apologize for the wait. Unfortunately on my side I can't reproduce, also your logs don't show anything unusual. So please could you check the following:

1) Check if everything works correctly without AdGuard enabled.
2) If the problem disappears when AdGuard is turned off, please try disabling the Ad blocking protection module and see if the problem persists.

Also, you mentioned that you are using Firefox, perhaps you have noticed if the problem repeats in other browsers, Chrome?

**Comment by Kieaer** [comment]
@grumaxxx No blank line inserted without adguard enabled.
I tried disable ad blocking protection module but still blank line inserted.
It issue can reproduce only Firefox (both PC and Android version), not Edge, Chrome.

**Comment by Kieaer** [comment]
Oops, I found bug from firefox browser
Other browsers doesn't insert new blank texts.
not adguard bug.
