### ISSUE TITLE
Bing Contribute voice clips poup does not appear

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/CoreLibs#1808]
Even if no filters lists, DNS filtering and userscripts are enabled, Bing Contribute voice clips poup does not appear.

To reproduce, please follow the following instructions:
1. Prepare macOS with AdGuard for macOS or a Windows virtual machine with AdGuard for Windows.
2. Visit https://www.bing.com/account/general with a Chromium web browser.
3. Click `.vsaudio_container` element with `Contribute voice clips` title.

<details><summary>Screenshots</summary>

![Screenshot from 2023-09-25 19-48-04](https://github.com/AdguardTeam/CoreLibs/assets/98787049/e59e3c01-83f0-4a51-8542-4e9cc709ab2b)
![Screenshot 2023-09-25 at 7 46 03 PM](https://github.com/AdguardTeam/CoreLibs/assets/98787049/d035072d-140b-424e-8c3f-7c9d452edd56)

</details> 

GitHub Issue URL: https://github.com/AdguardTeam/AdguardFilters/issues/162188#issuecomment-1733317090

**Comment by AdamWr** [comment]
I think that as a workaround, this rule:
```adblock
@@||bing.com/VisualSystem/AudioConsentInfo$xmlhttprequest,elemhide,jsinject,extension
```
can be added (at least it works fine on my end with AdGuard for Windows).

**Comment by sfionov** [comment]
The rule is a solution.

**Comment by TesterMan247** [comment]
This could also be related somewhat: https://github.com/AdguardTeam/AdguardFilters/issues/236213#top
