### ISSUE TITLE
KissAnime Auto Captcha extention does not work with Adguard

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#181]
@wyterabitt commented on [Wed Feb 28 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2134)

The usercript "KissAnime Auto Captcha 3.2" does not work with Adguard. With Tampermonkey is works fine, in Adguard the script just continually reloads the page giving the "first run" message.

It is supposed to automate the captcha before watching episodes on kissanime.ru

https://greasyfork.org/en/scripts/30964-kissanime-auto-captcha-v3-2

Adguard 6.2.437.2171
Firefox 58.0.2 - with currently no add-ons 
Windows 10

**Comment by temis2k16** [comment]
Original website has been closed and sites that are mirrors of original site don't have capcha
