### ISSUE TITLE
CORS policy problem on web.samokat.ru

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1813]
AdGuard for Windows 7.15.0 nightly 19 (4419) (CL 1.12.78, DL 2.2.24 )

Original issue: https://github.com/AdguardTeam/AdguardFilters/issues/163561 

<details>
<summary>Screenshot</summary>

![image](https://github.com/AdguardTeam/CoreLibs/assets/8361299/3f2c5a32-6741-4aba-810c-723726a2a407)

</details>

Rules don't help, only HTTPS exclusion.

**Comment by sfionov** [comment]
DDoS protection in triggered. May be it is because current ClientHello lacks ECH grease, so it is not matching Chrome's

**Comment by sfionov** [comment]
@Alex-302 Is it reproducable with 7.15.2?

**Comment by Alex-302** [comment]
It seems works with 7.15.1 CL 1.12.87

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/CoreLibs/assets/8361299/dd2e732c-5691-46ee-9be1-994dfd91de3f)


</details>
