### ISSUE TITLE
Reserve function in Google Maps app is broken

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1819]
Original report: https://github.com/AdguardTeam/AdguardFilters/issues/164222#issuecomment-1773608963

Reproduced with AdGuard 4.3 n15

Steps to preproduce:
1. Open Google Maps app and go somewhere in USA
2. Press on a restaurant (not all have this function)
3. Press the Reserve button

<details>
<summary>Video</summary>

https://github.com/AdguardTeam/CoreLibs/assets/8361299/d7d5394d-74a5-4032-9b44-d6bc47396842

</details>

Disabling stealth mode and adding to `QUIC bypass packages` does not help.

**Comment by grumaxxx** [comment]
@Alex-302 This function doesn't work due to a blocked DNS request to `google-analytics` caused by a rule in AdGuard DNS Filter. If I add a rule that disables the previous one, the feature works fine.
