### ISSUE TITLE
Latest nightly Adguard blocks QUIC connections

### ISSUE THREAD

**Issue by DavidOsipov** [AdguardTeam/CoreLibs#1822]
### AdGuard version

7.15.0 nightly 26 (4434)

### Browser version

Microsoft Edge Version 118.0.2088.76 (Official build) (64-bit)

### OS version

Windows 11 Pro 23H2 (22631.2506)

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard DNS filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Strip URLs of tracking parameters, Disable cache for third-party requests, Block Flash, Turn off Advertising ID, Hide your Referrer from third-parties

### Issue Details

1. Enable Filter HTTP/3 in Adguard
2. Visit https://quic.nginx.org/quic.html
3. Make sure Adguard is filtering the website - check the website certificate
4. Run the test
5. Only HTTP connections are being established - dark gray pixels on the map.

### Expected Behavior

QUIC connections are being established - green pixels on the map.

### Screenshots

![Screenshot 2023-11-01 091843](https://github.com/AdguardTeam/AdguardForWindows/assets/38164582/7dddb488-a7c7-4b3a-a4ab-262affab187a)

### Additional Information

Tested with the latest stable/beta. Turning off traffic filtering and restarting the system helps. Switching traffic filtering from WFP to Proxy doesn't help. No third-party antivirus is installed, except Microsoft Defender.

**Comment by sfionov** [comment]
@DavidOsipov Thank you for your report!

Edge is not supported now, it has the same problem as other Chrome-based browsers - certificate verifier does not allow User and Enterprise CAs for HTTP/3 connections.

Therefore, the only supported browsers for this feature are Firefox and Safari. There was a mistake in release notes.

The problem on quic.nginx.org is reproducable, we'll take a look.

**Comment by sfionov** [comment]
@DavidOsipov The issue with https://quic.nginx.org/quic.html should be fixed in recently released version 7.16.

**Comment by DavidOsipov** [comment]
@sfionov 

No, it's not. It's a pity, because time of my subscription is ticking.

<img width="700" alt="image" src="https://github.com/AdguardTeam/CoreLibs/assets/38164582/11c43c3a-4fe4-4777-b5cc-53abb5952b40">
