### ISSUE TITLE
Scriptlets are not applied to Cyrillic domains

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1826]
AdGuard for Mac 2.12 / CL 1.12.78
AdGuard for Windows 7.15.0 n28 / CL 1.13.79

Doesn't work with Cyrillic domain
`реманга.орг#%#//scriptlet('set-local-storage-item', 'isPromoHidden', 'true')`
works with punycode
`xn--80aaig9ahr.xn--c1avg#%#//scriptlet('set-local-storage-item', 'isPromoHidden', 'true')`

**Before test disable Annoyances or AdGuard Mobile App Banners filter.**

Original issue: https://github.com/AdguardTeam/AdguardFilters/issues/166005

**Comment by sfionov** [comment]
Duplicate of #32
