### ISSUE TITLE
mall.sk - content script is not injected

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1834]
It looks like that AdGuard content script is not injected and also HTML filtering rules (`$$`) do not work on `mall.sk`.
`$replace` rules work correctly, though.

Steps to reproduce:
1. Add this rule:
```adblock
mall.sk##body
```
or
```adblock
mall.sk$$div
```
2. Navigate to - [https://www.mall.sk/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.mall.sk%2F)

Website should be blank.

Related to - https://github.com/AdguardTeam/AdguardFilters/issues/168427

AdGuard for Windows 7.15.1/7.16.0 nightly 8 (4511) (CL 1.13.98, DL 2.4.18 )

**Comment by rakleed** [comment]
@sfionov do you have any news? The macOS app and browser extension do not have this problem, only the Windows app. But because of this problem, advertisements are displayed on quite a few sites.

**Comment by sfionov** [comment]
@rakleed This problem is fixed in CoreLibs 1.14 which will be included in future releases

**Comment by rakleed** [comment]
@sfionov will you make a hotfix for Windows app?
