### ISSUE TITLE
Too many reloads on yandex market with enabled remove tracking url parameters feature

### ISSUE THREAD

**Issue by sxgunchenko** [AdguardTeam/CoreLibs#1835]
Maybe not a bug. Checked only with the Android version: 
AdGuard v4.3 Nightly 41 (10141990)

Kit v5.0.244
CoreLibs v1.13.79
DnsLibs v2.4.0.

STR:
1. Enable remove tracking url parameters feature in stealth mode 
2. Go to any product page (e.g. [here](https://market.yandex.ru/product--nakleiki-my-little-pony-novoe-pokolenie/1464019445?hid=15524436&show-uid=17024542917227127293116002&from=search&text=Little%20pony&rs=eJwljz9IQmEUxb-HSShtOcu3tUpOVsIbczFp6g_EU2gPIlof8fYgcn9Lq4NIYBa9pakGB5dA5MPFweVNGTiUv-Py43LPuefeuxtlGt6V9-GZ8KkKm28r-uODFW0EkxYdd4lq0hfqPJ3kV565PCev9GvQfvdJSKVu44wX1G4T1UwGqH_yP8Nkh-SkvI9zAP0iNLc43SGz8Z2S7-m7R228fufaqfzndMysQn_JVJCSaYdsDzaU34N-DtVYfbq19pAc11V_khNkqOO29v4o-Uv3n8nTha6kX0bydHRbpF2nUo_Fgj66UOYDDGtst0f64oapMLuHp1T9B-ZLjEI%2C&sku=101480522831&cpa=1&cpc=2W1U3IXL5fUsiPCTMBpdT-u0Bv-XYPmK9dr7LoevMGuYJzK0D0cx0xXzgQmMQ3hd4mYBVFXek_QSyvcAetvKu88TaeCBMwDIlJpI9CRYZHWMVMVG2jLPkMo213OmJzVRSWm9aW_s2qmyzIfsSxFcREA6k6x_V6ZfvRfz0XU1G2cqnF1aTXf--eDlP5S308L1tAl4cjpihXisKgbUWgTDq1JuX3ReRFrwVP08BK_YxLjvih_jiraqwNk3pMt4xvNixCHCT76PXk9a0hrM8o7cmg%2C%2C&cc=Ci4xNzAyNDU0MjkxMTI3L2U3MmNhOTY0OTY2NjdlNmRmNmRiNDQ4NzVmMGMwNjAwEDCAfebtBg%2C%2C))
3. Go to the reviews page

Expected behavior: the page loads just like without adguard

Actual behavior: there about 10 page reloads before it successfully loads

**Comment by Alex-302** [comment]
Disabled `||market.yandex.$removeparam=uniqueId` for Android.
