### ISSUE TITLE
Cosmetic filtering not work properly

### ISSUE THREAD

**Issue by antek821** [AdguardTeam/CoreLibs#1838]
Hi, on website: https://www.geoportal.gov.pl
rule: ``geoportal.gov.pl###saycookie`` does not work on the currently stable version of AdGuard for Windows (7.15.1) and Android (4.2), and information about cookies is displayed:
![image](https://github.com/AdguardTeam/CoreLibs/assets/77172951/43ce8b25-3b10-4695-b00e-607de781690a)

The same rule in uBlock Origin works fine

**Comment by sfionov** [comment]
@antek821  Thank you for your report! gov.pl is in [HTTPS filtering exclusions list](https://github.com/AdguardTeam/HttpsExclusions/blob/fbd9005b177e342643eeec2c90b2978ca412f0d2/exclusions/sensitive.txt#L89) as a domain with sensitive data. If you want AdGuard to filter it, you may remove gov.pl from HTTPS exclusions in AdGuard settings.

**Comment by antek821** [comment]
@sfionov Thanks for the information! I did not know. So I'm closing the issue :)
