### ISSUE TITLE
One of the subdomains is not filtered due to different site certificates

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/CoreLibs#1839]
Не фильтруется https://ihelper.mts.by/selfcare/.
Но фильтруются https://www.mts.by и https://2024.mts.by.
При этом у всех разные сертификаты: у двух последних, где нет проблемы — Let's Encrypt.
Если отключить `Проверять прозрачность сертификатов сайтов`, то фильтрация появляется. 
(`AdGuard 7.16 nightly 11 x64`) 

<details><summary>Screenshots:</summary>

![1](https://github.com/AdguardTeam/AdguardForWindows/assets/50718960/e9752342-a161-45d0-9d9d-ac6c75d0eb40)
![2](https://github.com/AdguardTeam/AdguardForWindows/assets/50718960/9c5cc059-3be0-4ad1-a7f3-5adca0bf9859)
![3](https://github.com/AdguardTeam/AdguardForWindows/assets/50718960/c77e4aa5-d644-49e2-a4bf-d102cbed4e08)

</details><br/>

**Comment by sfionov** [comment]
@zubrRB Спасибо за отзыв! `ihelper.mts.by` находится в списке HTTPS-исключений как сайт с чувствительными данными. Если его оттуда убрать, сайт должен начать фильтроваться

**Comment by zubrRB** [comment]
Я смотрел, у меня там его нету, ибо на этом субдомене продольный рекламный баннер, который растягивает страницу.

**Comment by zubrRB** [comment]
Фильтрация не осуществляется по причине того, что срок действия платного сертификата якобы истёк, но это не так.

**Comment by sfionov** [comment]
@zubrRB У вас версия CoreLibs 1.13.104 ?

**Comment by zubrRB** [comment]
Да, `7.16.0 nightly 11 (4528) (CL 1.13.104)`.
