### ISSUE TITLE
`Hide User-Agent` option removes `sec-ch-ua*` headers

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1841]
This issue probably related to https://github.com/AdguardTeam/AdguardFilters/issues/168834
https://account.adobe.com/?lang=en is broken (register/login before check), when used `Hide User-Agent` option in AdGuard for Windows 7.16.0 n12.

This rule solves mentioned issue `@@||account.adobe.com^$document,domain=services.adobe.com,stealth=useragent` (added to AdGuard Base filter)

I compared headers with and without that option, and the only difference is in the headers - removed these headers with enabled `Hide User-Agent`:

* `sec-ch-ua`
* `sec-ch-ua-mobile`
* `sec-ch-ua-platform`

User-Agent sting is not modified:

<details>
<summary>Screenshot</summary>

![image](https://github.com/AdguardTeam/CoreLibs/assets/8361299/9d4eb47a-48f6-43cd-8178-50bffd0fb9be)

</details>

Removed that headers using Fiddler, but the problem with the site loading is not reproduced.

```
		oSession.oRequest.headers.Remove("sec-ch-ua");
		oSession.oRequest.headers.Remove("sec-ch-ua-mobile");
		oSession.oRequest.headers.Remove("sec-ch-ua-platform");
```

(in `OnBeforeRequest` function in Fiddler rules)

**Comment by Yuki2718** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/239494
It seems “Hide User-Agent” is removing `sec-ch-ua-full-version`, `sec-ch-ua-platform-version`, `sec-ch-ua-arch`, and `sec-ch-ua-model` as well, which seems to be the cause of the issue. This might be intended; however, these headers are sent only if the server requested with an `accept-ch` header, that probably means the server wants to know them and thus removing them is likely to cause such issues.

**Comment by ngorskikh** [comment]
@Yuki2718 

`Accept-CH` is an [opt-in](https://httpwg.org/specs/rfc8942.html#accept-ch) mechanism, i.e., it indicates support for the listed hints, not a requirement to send each one.

I actually couldn't reproduce the [linked issue](https://github.com/AdguardTeam/AdguardFilters/issues/239494), albeit I tried with a desktop Chrome simulating a mobile client. It could have been a server misconfiguration that has already been fixed.

**Comment by Yuki2718** [comment]
@ngorskikh Did you disable the exception rule I [added](https://github.com/AdguardTeam/AdguardFilters/commit/5e2e1c598e3f6d813bd3c675509d29d34eb229d4)?

**Comment by ngorskikh** [comment]
@Yuki2718 No, but I've tested without any filters added.

**Comment by Yuki2718** [comment]
You don't have to use mobile UA. The issue still happens with my exception disabled.

<img width="1310" height="871" alt="Image" src="https://github.com/user-attachments/assets/dec19940-17e5-4dc6-9b22-c3c0fd8585a1" />
