### ISSUE TITLE
Add an option to use `|` as a separator in `$permissions`

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1850]
https://adguard.com/kb/general/ad-filtering/create-own-filters/#permissions-modifier
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#permissions

Change `\,` to `|` as more simple and habitual.

AdGuard:
`$permissions=storage-access=()\, camera=()`
uBO:
`*$permissions=oversized-images=()|unsized-media=()`

**Comment by dnmTX** [comment]
thank you 👍
