### ISSUE TITLE
`$all` modifier does not work with non-domain-like URL part

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1860]
AdGuard 7.17.0 nightly 2 (4585) (CL 1.13.118, DL 2.4.38 )
Chrome 121

### Steps to reproduce

1. Disable all filters, DNS filtering, safebrowsing
2. Add `&pbsubid=$all` rule to user rules
3. Open `http://iyfbodn.com/?dn=maphuahin.com&pid=9POT3387I&pbsubid=f3de3781-7342-44ad-8fd6-4839cebfd6d7&noads=http`

### Expected behavior

URL is blocked with a dummy, like with `||iyfbodn.com^$all`

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/CoreLibs/assets/8361299/31eac181-20c5-4306-8ff5-c0fcd2ed686a)

</details>

### Actual behavior

The page is loaded.

Also `http$all` only blocks resources of pages.

<details>
<summary>Details</summary>

</details>

**Comment by sfionov** [comment]
@Alex-302 Domain does not exist, and with `https://example.org/?dn=maphuahin.com&pid=9POT3387I&pbsubid=f3de3781-7342-44ad-8fd6-4839cebfd6d7&noads=http` it works as expected.

**Comment by sfionov** [comment]
Ok, I see. works with https:// but http:// does not match.
