### ISSUE TITLE
Cannot parse QUIC ClientHello split into two packets

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#1861]
Steps to reproduce:

1. Download latest Chromium snapshot from https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac_Arm/1260335/
2. Run `Chromium --enable-quic --origin-to-force-quic-on=http3.is:443`
3. See `AGQuicProcessingUnit: Failed to parse ClientHello` in log

**Comment by ameshkov** [comment]
Why do they split it?

We'll need this in v1.14 or later?

**Comment by sfionov** [comment]
@ameshkov They now send "post-quantum" X25519Kyber768Draft00 key (additional 1200+ bytes) in `key_share` extension along with usual X25519 key. Also, on sites with ECH, ClientHello is split due to ECH extension.

I think we may correct it in CL1.15
