### ISSUE TITLE
`vk-metabot.user.js` does not work via AdGuard

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/CoreLibs#1871]
### AdGuard version

Version 2.13.0.1558 release

### Browser version

Version 121.0.6167.184 (Official Build) (arm64)

### OS version

14.3 (23D56)

### Support ticket ID

871981

### Issue Details

Steps to reproduce:
1. Download [api.botnadzor.org/update/vk-metabot.user.js](https://api.botnadzor.org/update/vk-metabot.user.js)
2. Import it to AdGuard 
3. Check if it works (you will find an example in the support ticket)

### Expected Behavior

The user script works and highlights comments left by bots

### Actual Behavior

It does not work (no highlighting) if you run it via AdGuard, but works fine via Tampermonkey

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardForMac/assets/15856304/72c0fbcf-e3d7-4c4c-8f4a-8118220a6630)

</details>

**Comment by slavaleleka** [comment]
first of all, the userscript uses `unsafeWindow` so it should be granted (which is not in current version of the userscript)
https://www.tampermonkey.net/documentation.php?locale=en#meta:grant:~:text=//%C2%A0%40grant%C2%A0unsafeWindow

**Comment by DotTheI** [comment]
AdGuard 2.15.1.1731. Still not working

**Comment by slavaleleka** [comment]
@DotTheI 
`unsafeWindow` is still not granted in v4.1.3 of the script
