### ISSUE TITLE
acea.it - codepage is broken by extensions module

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#188]
@Alex-302 commented on [Fri Apr 21 2017](https://github.com/AdguardTeam/AdguardForMac/issues/195)

https://github.com/AdguardTeam/AdguardForWindows/issues/1704

**Comment by temis2k16** [comment]
The issue is similar to https://github.com/AdguardTeam/CoreLibs/issues/1720
so it could be fixed the same way (with $replace rule).

But now website from the issue is changed so issue can't be reproduced anymore
