### ISSUE TITLE
AdGuard systematically crashes and freezes

### ISSUE THREAD

**Issue by pdkpv** [AdguardTeam/CoreLibs#1880]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

v4.4 Nightly 43

### Environment

- OS version: HyperOS, Android 14
- Device: Xiaomi Poco F5 Pro (23013PC75G)

### HTTPS filtering

- [X] yes, I do

### Routing mode

Local VPN

### Which DNS server do you use?

Cloudflare for Families - Malware Blocking

### DNS protocol

DNS-over-HTTPS

### Issue Details

Steps to reproduce:
1. Enable the proxy server in AdGuard (SOCKS5, 0.0.0.0, 2080) for the NekoBox 1.2.9 program.
2. Enable, switch and disable proxies in the NekoBox application.
3. Almost immediately the bug repeats itself.

### Actual Behavior

AdGuard systematically crashes and freezes.

<details>
  <summary>Screencast</summary>
  
  https://github.com/AdguardTeam/AdguardForAndroid/assets/43634070/0ee01a36-3862-407e-a1a6-aabcd5db2112
  
</details>

### Additional Information

Detailed information, logcat and preliminary cause of this bug can be found in Alexey Dmitrevsky.

**Comment by bropines** [comment]
on the version of AdGuard v4.4 Nightly 46 is still not fixed)

**Comment by sfionov** [comment]
@bropines New DnsLibs should arrive in one of the next nightlies

**Comment by sfionov** [comment]
@bropines Is your problem solved with latest release?

**Comment by bropines** [comment]
> @bropines Is your problem solved with latest release?

Yes. In general, yes. There is also a problem with the fact that when you turn on a proxy, for some reason the connection disappears in YouTube and YouTube Revanced (as in Google services), but I think this is not related to the problem.

**Comment by bropines** [comment]
> > @bropines Is your problem solved with latest release?
> 
> Yes. In general, yes. There is also a problem with the fact that when you turn on a proxy, for some reason the connection disappears in YouTube and YouTube Revanced (as in Google services), but I think this is not related to the problem.

https://github.com/AdguardTeam/CoreLibs/assets/57861007/5ed2bd79-dd60-4e8d-85cf-e67449878b5f

If necessary, I can post the log

**Comment by Extreme-Icer** [comment]
> @bropines Is your problem solved with latest release?

i have same question in adguard 4.5.16.when i turn off protection,the app will automatically crash,or irregular automatically crash.

oneui5.1/Android13/sm-n9860

**Comment by sfionov** [comment]
@Extreme-Icer Do you have release or nightly build?

**Comment by Extreme-Icer** [comment]
> @Extreme-Icer Do you have release or nightly build?

adguard 4.5 nightly 6 have this problem
the newest nightly8 not test

**Comment by sfionov** [comment]
@Extreme-Icer Does problem persist on the 4.6.1 release or the latest nightly?

**Comment by Extreme-Icer** [comment]
yes it’s solved.
________________________________
发件人: Sergey Fionov ***@***.***>
发送时间: 2024年7月30日 17:20
收件人: AdguardTeam/CoreLibs ***@***.***>
抄送: Extreme_Ice ***@***.***>; Mention ***@***.***>
主题: Re: [AdguardTeam/CoreLibs] AdGuard systematically crashes and freezes (Issue #1880)


@Extreme-Icer<https://github.com/Extreme-Icer> Does problem persist on the 4.6.1 release or the latest nightly?

―
