### ISSUE TITLE
For random adserver domain names generic rule idea is that possible?

### ISSUE THREAD

**Issue by kodiakhub** [AdguardTeam/CoreLibs#1888]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Is it possible to block all domain names that are random except true words in all languages with new feature?

For example:

afsdgkldf.xyz (ad server blocked)
jhgjhgjhj.com (ad server blocked)
lordmod.com (ad server but not blocked due to true words) etc.

**Comment by sfionov** [comment]
Unfortunately, we do not plan to implement such feature.
