### ISSUE TITLE
Content script is not injected on www.huya.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1897]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

7.18.0 nightly 11 (4784) (CL 1.15.63, DL 2.5.38 )

### Browser version

Chrome 127

### OS version

Windows 11

### Issue Details

Steps to reproduce:
1. Add this rule:
```adblock
www.huya.com#%#alert(1);
```
2. Go to - https://www.huya.com/
3. Refresh website (few times, but it might be not necessary)

### Expected Behavior

Alert should be displayed.

### Actual Behavior

There is no `local.adguard.org` so rules are not applied.

### Additional Information

It doesn't occur every time, sometimes it works, but sometimes doesn't.
If you cannot reproduce try to refresh website or click on the website logo few times.

**Comment by Alex-302** [comment]
@AdamWr On my end injection works 

<details>
<summary>Details</summary>

![image](https://github.com/user-attachments/assets/87c56a96-0212-45b9-9673-36846b317b64)


</details>

Maybe is it caused by failed Popup Blocker?

**Comment by AdamWr** [comment]
This problem occurs only sometimes, I have to reload website few/several times and it's not related to Popup Blocker.
When it happens then there is no `local.adguard.org` in page source.

https://github.com/user-attachments/assets/c8b77a40-7162-4cd1-85d7-d723e22f1b70
