### ISSUE TITLE
Access to function "GM_getValue" is not allowed

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/CoreLibs#1905]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

AdGuard for Windows 7.18.1

### OS version

Windows 11

### Issue Details

Steps to reproduce:
1. Install microShield by using https://cdn.jsdelivr.net/gh/List-KR/microShield@latest/microShield.user.js
2. Visit https:/dogdrip.net
3.
4.

### Expected Behavior

Getting a value from the userscript manager's storage is successful.

### Actual Behavior

Getting a value from the userscript manager's storage fails with `Access to function "GM_getValue" is not allowed` in DevTool console tab.

**Comment by ngorskikh** [comment]
@piquark6046 Hi! As a workaround, you can change the dots in your `@grant`s to underscores, for example: `GM.getValue` to `GM_getValue`. We'll handle this automatically in the future.
