### ISSUE TITLE
$replace rules applied to HTML prevents document level exceptions

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#191]
How to reproduce:
Add `@@||forums.overclockers.ru^$document` and open forums.overclockers.ru source. 
`$("body").html` line is removed
![image](https://user-images.githubusercontent.com/8361299/37875262-27001e74-3045-11e8-948d-b42492fe737b.png)
`$generichide` and `$elemhide` exclusion also is not working in this case, `forums.overclockers.ru##body` still works.

AdGuard 6.2.437.2171

**Comment by Alex-302** [comment]
The problem is still present.

**Comment by ameshkov** [comment]
Use `$document,important`

**Comment by sfionov** [comment]
replace rules and basic rules are now matching separately

**Comment by sfionov** [comment]
They do
