### ISSUE TITLE
QUIC traffic is not routed to the VPN server.

### ISSUE THREAD

**Issue by Seohare** [AdguardTeam/CoreLibs#1926]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.6.4

### OS version

Android 14

### Issue Details

Steps to reproduce:
You need to install NekoBox because you use ProtonVPN and AdGuard at the same time.

https://list-kr-community.pages.dev/docs/AdGuard/use-another-vpn-with-adguard
Follow the link above to set up NekoBox and AdGuard.

### Actual Behavior

Except for QUIC traffic, only the rest of the traffic passes through the VPN server.

### Screenshots

<details><summary>Screenshot 1</summary>

 
![1](https://github.com/user-attachments/assets/78e27255-9081-4f23-b538-beecaa0a6e3c)

</details>

### Additional Information

As shown in the screenshot above, AdGuard does not route QUIC traffic to the VPN server.

**Comment by zzebrum** [comment]
@yumesakisaki is `Route UDP through SOCKS5` option enabled in the proxy settings in AdGuard?

**Comment by Seohare** [comment]
I changed the proxy type from HTTP to SOCKS 5 and it worked out.
Thank you.
