### ISSUE TITLE
[Nightly Windows] Decrypted string is an invalid IDN name

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/CoreLibs#197]
WARNING, AdguardSvc, 31, 05.04.2018 12:12:17.777, Cannot convert string bestofthelist.com/wp-content/plugins/dc-facebook-like-box-popup-increase-facebook-fans to punycode: System.ArgumentException: Die entschlüsselte Zeichenfolge ist kein gültiger IDN-Name.
Parametername: unicode
Source: mscorlib
Stack trace:    bei System.Globalization.IdnMapping.GetAsciiUsingOS(String unicode)
  bei System.Globalization.IdnMapping.GetAscii(String unicode, Int32 index, Int32 count)
  bei System.Globalization.IdnMapping.GetAscii(String unicode, Int32 index)
  bei Adguard.Commons.Network.UrlUtils.ToPunycode(String unicode)

**Comment by BlazDT** [comment]
[Logs.zip](https://github.com/AdguardTeam/CoreLibs/files/1879602/Logs.zip)

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdguardForWindows #2163](https://github.com/AdguardTeam/AdguardForWindows/issues/2163) via [**ZenHub**](https://www.zenhub.com/)
