### ISSUE TITLE
Make proxy filters not singletons

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#198]
We should be able to initialize new filters while old proxy server is still processing requests.
Context parameter may be added to most of AGFilter methods.
Proxy initialization is being splitted into constructor and start().
After this issue will be implemented, there may be init() method that doesn't require that old server is not running (initializes all not-singleton entities), and start(), that will require this.
This will allow seamless transition from old proxy instance to new one.

**Comment by sxgunchenko** [comment]
Merged, core/pull-requests/220
