### ISSUE TITLE
Add README and build-scripts

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#20]
- [ ] README with build instructions for each platform
- [ ] Buildscript for building JNI code at host, to run classic Java tests from Android Studio
- [ ] Buildscript for running native tests
- [ ] Drop Maven support, merge "java" and "android" directories

**Comment by ameshkov** [comment]
Regarding JNI and android, you'd better move everything to a new folder named `android` and get rid of other java-related folders.

**Comment by ameshkov** [comment]
Wait for us to merge the filtering branch, though
