### ISSUE TITLE
$network rules support

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#202]
We need to support $network rules
Basic functionality may be done within corelibs proxy, and platform-specific proxy may do additional work (e.g. pushing rules to kernel extension)

**Comment by sfionov** [comment]
https://github.com/AdguardTeam/AdguardForMac/issues/171
https://github.com/AdguardTeam/AdguardForWindows/issues/1297

**Comment by sfionov** [comment]
UDP - always kext. 
addRule to kernel driver should support network masks.
QUIC - ?

**Comment by sfionov** [comment]
So, finally list of tasks is:
1. addRule to kernel driver should support network masks.
This may be implemented by userspace function that converts $network rule to list of nf-rules with CIDR prefixes.
2. Every blocked connection must send some data to control socket, userspace code should read this data from control socket and launch specified callback.

**Comment by szolin** [comment]
/core/pull-requests/456
