### ISSUE TITLE
Add $extension modifier support

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#207]
This is necessary for the proper userscripts support.

* `@@||example.org^$extension` -- disables userscripts on `example.org`
* `$document` modifier includes `extension` by default.
* However, a rule like that: `@@||example.org^$document,~extension` will unblock everything on `example.org`, but it will keep userscripts working.

**Comment by hmage** [comment]
Implemented in urlfilter -- /pull-requests/415/

Needs to be used further down the chain.
