### ISSUE TITLE
$genericblock should be returned by the `findBasicRule` method

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#21]
See `testGenericBlockModifier` for the details.

`$genericblock` should be returned as a result if it is a reason why no basic rule found.
Same goes for `$urlblock` rules

Also, it makes sense to add `isGenericBlock` property to the `NativeFilterRule` object.

**Comment by hmage** [comment]
Fixed in a44e2846bc6df134fdfe36617f65a38e086ec38c. Rewrote C tests to be close to java tests.
