### ISSUE TITLE
Send TLS alerts when intercepted connection is going to be closed

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#211]
Now connection is silently closed, but we may send TLS record with TLS alert (fatal internal_error / warning close_notify)

**Comment by sfionov** [comment]
#208 done instead

**Comment by sfionov** [comment]
Reopening, because some TLS clients doesn't work well with TCP reset.

**Comment by szolin** [comment]
core/pull-requests/423
