### ISSUE TITLE
businessman.ru is broken by HTTPS filtering [Windows]

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#212]
URL:
https://businessman.ru/new-individualizaciya-yuridicheskogo-lica-osobennosti-sredstva-i-sposoby.html

Actual behavior:
![image](https://user-images.githubusercontent.com/8361299/39172999-19a39c64-47ac-11e8-90da-bc40c48c85e5.png)
Response(not header):
```
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 23 Apr 2018 21:19:01 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Strict-Transport-Security: max-age=63072000;
    includeSubdomains; preload
```

This site works as expected on Android and MacOS.

**Comment by szolin** [comment]
Works normally on Windows.
It seems they fixed the issue on server side.  Now it's like this:
`Strict-Transport-Security: max-age=63072000;    includeSubdomains; preload`

**Comment by Alex-302** [comment]
Yes. It works now.
