### ISSUE TITLE
Make userscript wrapper compatible with IE10

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#214]
> in IE10-: `property or method __lookupGetter__(f) doesn't supported`

**Comment by seanl-adg** [comment]
Reproduction steps?

**Comment by ameshkov** [comment]
@adbuker ping

**Comment by seanl-adg** [comment]
I tested with IE 10 emulation mode of IE11 on my end and couldn't reproduce it.
If it is reproduced, could you execute `Object.getOwnPropertyNames(window).filter(function(name) { var desc = Object.getOwnPropertyDescriptor(window, name); if ('writable' in desc) { return false; } return true; });` in the console and check its result?

**Comment by adbuker** [comment]
Steps to reproduce:
1. Start emulating ie10 in ie 11
2. Goto the `https://adblockplus.org/subscriptions`
3. Error occurs - https://uploads.adguard.com/adguard_ls8ts.png

The function, described above returns https://uploads.adguard.com/buker_rouv4.png, whereas ie11 (without ie10 emulating) returns https://uploads.adguard.com/buker_p66n2.png
