### ISSUE TITLE
Domain Redirects Even Though Added in Malware List

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/CoreLibs#216]
@Nzzyme commented on [Sat Apr 21 2018](https://github.com/AdguardTeam/AdguardForAndroid/issues/1836)

When browsing some sites or if you click on an ad/pop-up (which was not blocked by AG), the ad/pop-up redirects and hops multiple domains quickly to take you to some target page. However, if one of the domain was included in the Malware/Phishing list, it still quickly bypasses that and continues to redirect to another page. 

The expected behavior is that as soon as the domain is encountered, it should be blocked and the warning page should be displayed. However, I can confirm that this does not happen.

**Example**: 

The domain "calcch.com" is added to the malware/phishing list as seen here: http://prntscr.com/j8768r

However, when opening the site "musicforyou.ga" (in Firefox) at times redirects via the following domains seen here: http://image.ibb.co/e3amic/Screenshot_20180421170700.jpg

You many have to reload the site once to see the redirects. As you can see from the above screenshot, the domain "secure.calcch.com" was not not blocked by AG and it continued to proceed to the next domain "leadzuaf.com".

**System**:
- Android version: 6.0.1 MMB29M
- MIUI version: MIUI Global 9.5 - Stable [ 9.5.3.0 (MHOMIFA) ]

**AdGuard Version**:
- AdGuard for Android 2.11.81

**Filters**:
English, Spyware, Social Media, Annoyances, Mobile Ads, Simplified domain names, EasyList China, Anti-Adblock Killer-Reek

**AdGuard Settings**:

- Phishing & Malware Protection: Enabled
- Block ads in all apps: Enabled
- Search ads & self-promotion of sites: Disabled
- DNS Filtering: Disabled
- HTTPS Filtering: Enabled
- High quality filtering: Enabled
- Filtering mode is Local VPN

**Comment by vozersky** [comment]
This is a desync issue, I guess, we should look into it

**Comment by Nzzyme** [comment]
By the way, I can confirm that this happens even on PC running Windows.

Example: 

http://emcv.eu/j1/24314/19/87827574/eyJzIjogNDcsICJmIjogMiwgImMiOiA1MTgwNSwgInNkIjogMH0=/e30=/

Even though emcv.eu is added to the block list, clicking the above link quickly redirects to http://parkingpage.namecheap.com instead of blocking the page instantly.

**Comment by Nzzyme** [comment]
Hi, is someone looking into this issue? It's been open since a long time now. Thanks!

**Comment by ameshkov** [comment]
@Nzzyme it's on the roadmap, but we have more pressing issues before implementing it.

Basically, the issue is by the current design (AG for Android and CoreLibs v1.1), but it's working properly in AG for Windows. Yet to be implemented in CoreLibs.

**Comment by Nzzyme** [comment]
I thought I had replied on this. I am currently using AG for Chrome extension and although the domain is added to the block list (domain was reported earlier in Phishing section in forum), AG still offers the file for download even though the page displays AG warning message. Check this domain as an example:

mobileoffers-bn-download.com

**Comment by sfionov** [comment]
Since CL already implemented Safebrowsing V2, I think this issue may be closed.
