### ISSUE TITLE
Unit tests for the content script, stealth script and the userscript wrapper

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#218]
I'd like us to automate content script and userscript wrapper testing under different browsers.

We can use https://www.browserstack.com/ to do it.

**Comment by seanl-adg** [comment]
ToDo for stealth mode script's unit testing:

 - Defining an indexed property on `navigator.plugins` object yields different result among browsers. We must check in unit tests that wrapped `plugins` object behaves in the same way.
   - On Chrome and FF, it throws a TypeError, and we need to make sure that it is an instance of respective `window`'s `window.TypeError`
   - On IE and Edge, such properties are defined, but when deleted it reveals native values.

**Comment by ameshkov** [comment]
```
  88 passing (10m)
  3 failing

  1) Subscription test
       Clicking on an abp:subscription link must open a new tab/window having expected url:
     Error: the object {
  "column": 116
  "line": 9
  "sourceURL": "http://localhost:3000/build/content-script.js"
} was thrown, throw an Error :slightly_smiling_face:
      at process._tickCallback (internal/process/next_tick.js:178:7)

  2) Subscription test
       Clicking on an abp:subscription link must open a new tab/window having expected url:
     Error: the object {
  "description": "Unable to get property 'moveBy' of undefined or null reference"
  "number": -2146823281
  "stack": "TypeError: Unable to get property 'moveBy' of undefined or null reference\n   at Anonymous function (http://localhost:3000/build/content-script.js:9:115)"
} was thrown, throw an Error :slightly_smiling_face:
      at process._tickCallback (internal/process/next_tick.js:178:7)

  3) Subscription test
       Clicking on an abp:subscription link must open a new tab/window having expected url:
     Error: the array [] was thrown, throw an Error :slightly_smiling_face:
      at process._tickCallback (internal/process/next_tick.js:178:7)
```

**Comment by ameshkov** [comment]
1. For the stealth-script -- we need to add tests on ActiveX and blocking location API.
2. For the content-script -- we need to test style elements protection and we need to figure out if there's an issue with Safari unit-tests.
