### ISSUE TITLE
Add the subscription detection mechanism

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#219]
It is described here:
https://github.com/AdguardTeam/AdguardForWindows/issues/1945

The implementation needs to be changed compared to what we have in the Win version (no more relying on `window.open`).

**Comment by TPS** [comment]
So, this means also that, e.g., <kbd>Subscribe</kbd> works on https://filterlists.com/?

**Comment by ameshkov** [comment]
It will work, yes
