### ISSUE TITLE
Add more callbacks: `onBeforeRequest` and `onSessionClosed`

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#231]
* `onBeforeRequest` -- notifies about a request that is about to be executed. This request might be either processed or blocked. Required arguments: `sessionId`, `requestId`, request data (URL, referrer, headers).

* `onSessionClosed` -- notifies about closing the session. We need the following: timing, bytes received/sent, session ID.

I'd like to emphasize that `onBeforeRequest` must be called for any type of request, even for bypassed ones.

**Comment by sxgunchenko** [comment]
Merged, core/pull-requests/269
