### ISSUE TITLE
Move the stealth.js to a separate repo

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#232]
Just like it was done in the #206, we need to move the stealth.js to a separate repo and use modern build process for it.

What needs to be done:

1. Stealth script repo: `EXTENSIONS/repos/stealth-script/browse`
2. Use a modern build system (choose whichever you like more)
3. Use a transpiler (the stealth script needs to work in IE10)

The content script interface (configuration) needs to be clearly described in the repo README.

**Comment by TPS** [comment]
Belongs to https://github.com/AdguardTeam/StealthMode, or a different repo?

**Comment by ameshkov** [comment]
No, this is a module that is used in AG for Windows, and, potentially, can
be used in AG for Mac/Android.
