### ISSUE TITLE
Provide a helper method that will test a specified proxy

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#242]
```
/**
 * Tests the specified proxy
 */
boolean testProxy(ProxyServerConfig.OutboundProxyConfig proxyConfig, int timeout);
```

This method should try to load `http://mobile-api.adguard.com/generate_204` through the specified proxy and return `true` in case of a success.

**Comment by sfionov** [comment]
Merged, core/pull-requests/280
