### ISSUE TITLE
Provide a helper method that generates a CertKeyPair

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#243]

**Comment by sfionov** [comment]
Now the following methods are in CoreLibs:
byte[][] certPairBytes = ProxyUtils.generateCACertKeyPair("Sample CA");
KeyStore.PrivateKeyEntry entry = ProxyUtils.certKeyPairToKeyStoreEntry(certPairBytes);
Is they enough?

**Comment by ameshkov** [comment]
Yep
