### ISSUE TITLE
Host name is missing from some requests

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#248]
Steps to reproduce:

1. Run AG (from the corelibs branch) + Yandex browser
2. Check the filtering log
3. You'll see a few requests with a missing hostname (`openssl s_client` shows that this IP address corresponds to a  `startup.mobile.yandex.net` domain).

**Comment by sfionov** [comment]
It is detected in SslBypassFilter, but not saved anywhere at this moment

**Comment by sxgunchenko** [comment]
Merged, core/pull-requests/278

**Comment by ameshkov** [comment]
Not fully resolved, easily reproducible with Yandex apps (Yandex Taxi for instance).

**Comment by sxgunchenko** [comment]
core/pull-requests/296
