### ISSUE TITLE
CoreLibs does not indicate blocked HTTPS tunnel requests

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#249]
## Steps to reproduce:

1. Add `||example.org` to the user filter
2. Disable HTTPS filtering for the Chrome browser in the Apps Management settings
3. Try opening example.org in Chrome

## Expected result:
`onRequestProcessed` is called for the `example.org` tunnel (with the blocking rule info)

## Actual result:
`onRequestProcessed` is not called at all

**Comment by sfionov** [comment]
May be related to #248

**Comment by sxgunchenko** [comment]
Merged, core/pull-requests/284

**Comment by sxgunchenko** [comment]
Filter result was not assigned in `onRequestProcessed` event, which caused event not being logged.
Fixed in core/pull-requests/292
