### ISSUE TITLE
Avoid detection by mitm watch

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#251]
I am not saying we should solve all the cases listed below. What I am saying is that it'd be a right thing to properly copy all the TLS extensions (and no just ciphers) when we handshake with the remote (or local) endpoint.

Test website:
https://mitm.watch

Paper:
https://jhalderm.com/pub/papers/interception-ndss17.pdf

> We describe the heuristics for each browser below:

> **Mozilla Firefox** 
> Firefox was the most consistent of the four browsers, and by default, each version produces a nearly identical Client Hello message regardless of operating system and platform. All parameters, including TLS extensions, ciphers, elliptic curves, and compression methods are predetermined and hard-coded by the browser. Users can disable individual ciphers, but they cannot add new ciphers nor reorder them. To determine whether a Firefox session has been intercepted, we check for the presence and order of extensions, cipher suites, elliptic curves, EC point formats, and handshake compression methods. Mozilla maintains its own TLS implementation, Mozilla Network Security Services (NSS) [42]. NSS specifies extensions in a different order than the other TLS libraries
we tested, which allows it to be easily distinguished from other implementations. The library is unlikely to be directly integrated into proxies because it is seldom used in server-side applications.

> **Google Chrome** 
> Chrome was one of the most challenging browsers to fingerprint because its behavior is dependent on hardware support and operating system. For example, Chrome prioritizes ChaCha-20-based ciphers on Android devices that lack hardware AES acceleration [10] and Chrome on Windows XP does not advertise support for ECDSA keys at all. These optimizations result in several valid cipher and extension orderings for each version of Chrome, and furthermore, users can disable individual cipher suites. We check for ciphers and extensions that Chrome is known to not support, but do not check for the inclusion of specific ciphers or extensions, nor do we validate their order. When appropriate, we check the presence and order of elliptic curves, compression methods, and EC point formats. We note that because Chrome uses BoringSSL, an OpenSSL fork, connections have a similar structure to OpenSSL. However, Chrome supports considerably fewer options, including a subset of the default extensions, ciphers, and elliptic curves advertised by OpenSSL.

> **Microsoft Internet Explorer and Edge** 
> Internet Explorer is less consistent than the other browsers for two reasons: (1) administrators can enable new ciphers, disable default ciphers, and arbitrarily reorder cipher suites through Windows Group Policy and registry changes, and (2) IE uses the Microsoft SChannel library, an OS facility which behaves differently depending on both Windows updates and browser version. Because of this additional flexibility, it is hard to rule out handshakes that include outdated ciphers, so we introduce a third categorization, unlikely, which we use to indicate configurations that are possible but improbable in practice (e.g., including an export-grade cipher suite). We note that minor OS updates alter TLS behavior, but are not indicated by the HTTP User-Agent header. We mark behavior consistent with any OS update as valid. SChannel connections can by uniquely identified because SChannel is the only TLS library we tested that includes the OCSP status request extension before the supported groups and EC point formats extensions. 

> **Apple Safari** 
> Apple Safari ships with its own TLS implementation, Apple Secure Transport, which does not allow user customization. The order of ciphers and extensions is enforced in code. While extension order does not vary, the NPN, ALPN, and OCSP stapling extensions are frequently excluded, and the desktop and mobile versions of Safari have different behavior. One unique aspect of Secure Transport is that it includes the TLS_EMPTY_RENEGOTIATION_INFO_SCSV cipher first, whereas the other libraries we investigated include the cipher last. Similar to Microsoft, Apple has changed TLS behavior in minor OS updates, which are not indicated in the HTTP UserAgent header. We allow for any of the updates when validating handshakes, and we check for the presence and ordering of ciphers, extensions, elliptic curves, and compression methods.

Useful links:
* https://mitm.watch/
* https://github.com/cloudflare/mitmengine
* https://malcolm.cloudflare.com/
* https://www.ssllabs.com/ssltest/viewMyClient.html

**Comment by askingforafoe** [comment]
Is this feature implemented for each AdGuard version? And would you expect that the fingerprint stays the same if AdGuard is running or not?
I only made a small test. One on Windows. With Chrome the fingerprint stayed the same. In Firefox it changed.
On MacOS the fingerprint for Safari also changed.

**Comment by ameshkov** [comment]
@askingforafoe in theory it should be done automatically, but we revisit this from time to time.

Currently, there's an open issue about that:
https://github.com/AdguardTeam/CoreLibs/issues/1503
