### ISSUE TITLE
You must strip `*.` from CN before matching against the url filter

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#259]
1. `*.appmetrica.webvisor.com` is not blocked while it must be. 
2. It is confusing to see such value in the log

What I suggest:

1. Fixing the blocking functionality
2. I suggest placing CN in a new field: `RequestProcessedEvent.serverCommonName`

**Comment by sfionov** [comment]
Still persists in RequestProcessedEvent if HTTPS filtering is enabled

**Comment by sfionov** [comment]
core/pull-requests/476
