### ISSUE TITLE
AG blocks URLs opened in a top-level frame

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#262]
It must've been working differently by default (at least until we introduce #70 functionality) 
Smth is wrong with the temp cookies.

How to reproduce:
1. Add `||example.org` to the user filter
2. Try opening https://example.org

Expected result: example.org will be opened despite being blocked by AdGuard
Actual result: you'll see a "blocked by Adguard" page.

**Comment by TPS** [comment]
Wait, ___why___ is this an error⁉️  Who shouldn't expect exactly this behavior?

**Comment by ameshkov** [comment]
The default behavior would be to block subrequests, but when you deliberately open a page on an ad domain, this page should not be blocked.

**Comment by ameshkov** [comment]
Malware is a different story and I am talking about ad blocking.

> AG should minimally put up an interstitial

This is why we'll do #70.

**Comment by ameshkov** [comment]
Outright blocking is quite problematic:
1. It will prevent navigation on some websites. The simple example -- Google, you won't be able to open any search result.
2. It will mess with you when you're trying to actually use a website, read or whatever.

**Comment by TPS** [comment]
So, this will be general behavior (_all_ hostname-based filters) or specific (_certain_ such filters)?

**Comment by szolin** [comment]
core/pull-requests/303
