### ISSUE TITLE
$network rules do not work on the proxy level

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#267]
## Steps to reproduce

1. Comment out `connectionFilter.findConnectionRule` in the `LocalVpnService`
2. Build and run AdGuard
3. Add `93.184.216.34$network` to the user filter (the IP address of `example.org`)
4. Try opening `https://example.org` in your browser

## Expected result
1. Connection is blocked
2. `onRequestProcessed` is called right after that

**Comment by sfionov** [comment]
Proxy session may use FilterUrl's matchIp

**Comment by szolin** [comment]
core/pull-requests/328

**Comment by sfionov** [comment]
Reopening since it is not integrated yet with `net` module. But additional discussion is needed here.
