### ISSUE TITLE
Conflicts of stealth-script and Popup Blocker dev version

### ISSUE THREAD

**Issue by seanl-adg** [AdguardTeam/CoreLibs#268]

**Comment by ameshkov** [comment]
Any details?

**Comment by danidoedel** [comment]
Hmm just that you can’t browse any website, html and stuff loads fine, but the page won’t be displayed, after few seconds the tab crashes („page not responding“). 
It happens with the latest nightly (6.3.1052.3379), the nightly before was fine. Popupblocker beta is also working fine.

**Comment by ameshkov** [comment]
@danidoedel I mean technical details -- what exact conflict is causing this issue. I suppose this is somehow connected to the `IProxyService` but I'd like to learn the details.

**Comment by ameshkov** [comment]
@seanl nvm, I've just read it in slack

**Comment by danidoedel** [comment]
@ameshkov Ahh ok sry ;)

**Comment by ameshkov** [comment]
@adbuker re-build the stealth script and check if there's any conflict now please.

**Comment by ameshkov** [comment]
Is it resolved @seanl-adg ?
