### ISSUE TITLE
500 error on a non-URL referrer

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#269]
Take a look at this request data:
https://photos.app.goo.gl/eBYmkGePViLsDgrf2

**Comment by sfionov** [comment]
At this moment error 500 if request was blocked, but User-Agent is not a browser.
Otherwise it should be 502.

**Comment by ameshkov** [comment]
I am quite sure it is not blocked. The issue happens for any page opened from within any app (Twitter, Reddit, whatever)

**Comment by ameshkov** [comment]
However, once I reload the page (with an empty referer) -- it is opened just okay.

**Comment by sxgunchenko** [comment]
core/pull-requests/316
