### ISSUE TITLE
my.docshell.ru, HTTPS filtering issue

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#274]
Related issue https://github.com/AdguardTeam/AdguardForWindows/issues/2196.
I've done small investigations and find that we get an error in DotNetZip (a zipfile class library: http://dotnetzip.codeplex.com), more precisely `incomplete dynamic bit lengths tree`.

**Comment by ameshkov** [comment]
Resolved, confirmed in the Android build
