### ISSUE TITLE
[MacOS] `~third-party` wrong modifier behavior

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#276]
### Steps to reproduce

1. Enable Russian filter or add `/branding/*.css$~third-party`
2. Open https://www.bbc.co.uk/programmes/b0070hvg

### Actual behavior
Page is broken, because `https://branding.files.bbci.co.uk/branding/live/css/*.css` is blocked.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/40480663-d9f0c1aa-5f57-11e8-8b26-981ac96daa8d.png)

</details>

### Expected behavior
`https://branding.files.bbci.co.uk/branding/live/css/*.css` should not be blocked, because `bbci.co.uk` is third-party request for `bbc.co.uk`

### Your environment
MacOS, Safari, AdGuard 1.5.6

**Comment by ameshkov** [comment]
Resolved, confirmed in the Android build
