### ISSUE TITLE
Improve pseudo-classes validation

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#283]
The current implementation is flawed as it only takes into account the first pseudo-class in the rule.

Instead, we need to properly (!) tokenize the selector and parse every pseudo-class from there.

Tokenizing a selector is quite a complicated thing to do, though. You might want to take a look at the Chromium code.

**Comment by sfionov** [comment]
Currently there is no such limitation, and tokenizer is not working with BNF of CSS but parses any number of pseudo-classes correctly.
