### ISSUE TITLE
Yandex.Transport works incorrectly

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#287]
Hangs (on route details)

**Comment by ameshkov** [comment]
Похоже реально есть какая-то проблема с обработкой их соединений.

1. HTTPS фильтрация отключена
2. Все блокирующие правила вырублены
3. Яндекс карты не грузят пробки

Чтобы вылечить нужны выключить AG и **обязательно** перезапустить карты

**Comment by sfionov** [comment]
Problem is probably in internal buffering in SslBypassFilter. Assigning to @szolin.

**Comment by szolin** [comment]
core/pull-requests/349
