### ISSUE TITLE
Wrong `ts` field value in the content script URL

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#291]
The point of this field is to benefit from the browser cache while still having a way to update it once the filter configuration changes.

Instead of this, we seem to be using the current time every time:
`nanoseconds timestamp = duration_cast<nanoseconds>(system_clock::now().time_since_epoch());`

The timestamp must be set once -- when the `AGProxyFilter` instance is initialized, and it needs to be updated every time its state changes (currently, doing it on every `addRule` and `clearRule` call would be sufficient -- but this might change in the future).

**Comment by sfionov** [comment]
core/pull-requests/343
