### ISSUE TITLE
Add PCap file capture option

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#30]
For the managed interface, let's add a "pCapOutputPath" parameter to the NetworkStack constructor.

If this parameter is not valid or points to a file, that cannot be accessed, just ignore it.
Otherwise, create a new empty file and start recording pcap.

**Comment by TPS** [comment]
Just in case, like y'all do for logs, if said file _does_ exist accessibly, maybe you should backup/rename using same method?

**Comment by ameshkov** [comment]
> Just in case, like y'all do for logs, if said file does exist accessibly, maybe you should backup/rename using same method?

It makes sense, indeed.

**Comment by sfionov** [comment]
Fixed in 157d9dd473fc78116ae807e2181591feb15f7588
