### ISSUE TITLE
read.amazon.com is broken

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#301]
Original issue - https://github.com/AdguardTeam/AdguardFilters/issues/17166
Reported here as it seems that it happens on Mac too.

### Steps to reproduce

1. Add any element hiding rule for `read.amazon.com`, for example - `read.amazon.com###testTest`
(you can disable all filter lists and just add one rule)
2. Go here - https://read.amazon.com/
3. Log in

### Expected behavior

Website should load.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/40836299-78d5f45e-6596-11e8-91d7-6a754eb8e625.png)

</details>

### Actual behavior

Website show a spinning wheel and never finish loading.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/40837085-772bce6e-6599-11e8-87ae-805ab551daad.png)

</details>
<br>

I added `@@||read.amazon.com^$elemhide` as a temporary solution, but it seems that it take effect only after cleaning cache/"force refresh" or after browser restart.

### Your environment

* Environment name and version: Chrome 67.0.3396.62
* Operating system and version: Windows 10, v.1803

**Comment by szolin** [comment]
Added the rule `read.amazon.com###testTest` and logged in to amazon kindle successfully.  Site doesn't hang.
