### ISSUE TITLE
Add ability to set DNS servers on Android

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#304]
Libevent uses its own asynchronous dns resolver which needs DNS servers to be set.
On Android, we currently read net.dns1 / net.dns2 properties, but on some systems it may be unavailable, and 8.8.8.8 is used.

**Comment by ameshkov** [comment]
References:

* `FilteringDnsProxyServer.NetworkReceiver`
* `NetworkUtils.getDnsServers`

**Comment by sfionov** [comment]
core/pull-requests/373
