### ISSUE TITLE
Extend the browser API callback with rx/tx fields

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#309]
I suggest adding two fields there:

* remoteBytesSent
* remoteBytesReceived

For most browser API requests these fields are equal to 0.

The only exception is `safebrowsing` and `gm-xml-httprequest` as they might cause a remote connection.

**Comment by ameshkov** [comment]
It seems that you don't count headers size

**Comment by szolin** [comment]
core/pull-requests/425

**Comment by ameshkov** [comment]
It counts gigabytes in the current nightly version.

**Comment by szolin** [comment]
core/pull-requests/434
