### ISSUE TITLE
[Android Nightly] Broken page - m.focus.de

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#323]
@BlazDT commented on [Thu Jun 07 2018](https://github.com/AdguardTeam/AdguardForAndroid/issues/1909)

https://m.focus.de/politik/deutschland/rechter-shitstorm-nazis-nicht-willkommen-berliner-cafe-verbietet-afd-anhaengern-zutritt_id_9051318.html

Since the latest nightly (previous was fine) the site just displays 
script type='text/javascript'> try { TFT_Ext_FOL_mobileAmznAds = true; } catch(e) {}

On unrooted Amazon Fire which is based on Android 4.4 on Silk browser.Disabling AdGuard and the site displays fine. Probably due to new CoreLibs. On Chrome the site just stays empty.

![screenshot_2018-06-07-02-35-06](https://user-images.githubusercontent.com/34266271/41071994-68bc79ee-69fb-11e8-94cc-74f6c5a5984d.png)

**Comment by BlazDT** [comment]
Error also occurs with jsinject,elemhide,extension,urlblock,important exclusion.

Used filters:
English
Spyware
Social
Annoyance
Russian
German
French
Japanese
Spanish
Turkish
Experimental
Mobile Ads

**Comment by ameshkov** [comment]
`@@||focus.de$jsinject,elemhide,extension,urlblock,important ` ?

Have you tried simply adding it to the whitelist in?

**Comment by ameshkov** [comment]
Guys, it appears that the issue is specific to Android 4.4 (Amazon Fire).

**Comment by sfionov** [comment]
@BlazDT Does problem persist on the latest Nightly? There were fixes for stale pages in the filtering code in 2.12.74n.

**Comment by BlazDT** [comment]
Working in latest Nightly, thank you.

Sadly white page on https://kotaku.com - not even the site title is received.

**Comment by sfionov** [comment]
Thank you for information!
Problem with https://kotaku.com will be solved in #364
