### ISSUE TITLE
A $webrtc rule blocks requests 

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#324]
`$webrtc,domain=xda-developers.com` blocks a `https://api.xda-developers.com` request.

![image](https://user-images.githubusercontent.com/5947035/41095560-6b84e51c-6a5a-11e8-9f6f-bef3e40add58.png)

**Comment by hmage** [comment]
4ee892e3e2fd63532e1f6ca45dfc21fd9907e9dc

**Comment by TPS** [comment]
I'm having this problem in AG Android 2.12.52η w/ _many_ `$webrtc` filters builtin to the default filterlists.  Until this is completely resolved, can we get a global `Low Level Setting` to outright _disable/ignore_ such filters?

**Comment by ameshkov** [comment]
Resolved in the latest nightly

**Comment by TPS** [comment]
Confirmed, thanks.
