### ISSUE TITLE
[Android Nightly] Unexpected stop of protection

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#327]
19:59 - start
20:00 - opened Chrome with m.news.yandex.ua
At the same time protection was suddenly stopped.

Log:
[adguard (1).log](https://github.com/AdguardTeam/CoreLibs/files/2081388/adguard.1.log)
another log
[adguard.log](https://github.com/AdguardTeam/CoreLibs/files/2081410/adguard.log)

**Comment by sfionov** [comment]
Looks like a crash, do you have any crash info in `adb logcat` at the time one line before 
```20:05:44.419 [main] INFO  c.a.android.filtering.commons.g - Found resource [assets/logback.xml] at [assets/logback.xml]``` ?

**Comment by ameshkov** [comment]
Cannot reproduce. Now that we have an automatic crash reporting, it'd be much easier to find and fix issues like this.
