### ISSUE TITLE
[Android Nightly] `$script` rule doesn't work

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/CoreLibs#328]
`.*.com/show.html?$script`

Website: http://www.alleng.ru/edu/chem9.htm”

Request example: http://to.dedicatedgroups.com/show.html?GK3ozNSthJS4jenN-cnV-YSMoCSgzFzUiIS4_enc

**Comment by sxgunchenko** [comment]
Seems like it was caused by wrong logic of reapplying filters. 
Related to #329
