### ISSUE TITLE
[Android Nightly] $replace rules are not applied to some requests

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#329]
Tested on example.org and m.news.yandex.ua

* Not applied to HTML
`example.org^$replace=/Example Domain/Example Domain123/,important`

* Not applied to some JS

This rule must remove content from the script which starting with `Ya[*digits*]('{ common`
`||news.yandex.*/*/*-*-*-*-$replace=/^(\s)*Ya(\s)*\[\d+\][\s\S]*'\)//,script,important,domain=news.yandex.by|news.yandex.com|news.yandex.fr|news.yandex.kz|news.yandex.ru|news.yandex.ua`

but this rule works
`||news.yandex.*/*/*-*-*-*-$replace=/^(\s)*Ya(\s)*\[\d+\][\s\S]*'\)//,important,domain=news.yandex.by|news.yandex.com|news.yandex.fr|news.yandex.kz|news.yandex.ru|news.yandex.ua`
It seems content type cannot be defined, or `$script` modifier does not work as it should. Probably related to this issue: https://github.com/AdguardTeam/CoreLibs/issues/328
How to reproduce:
open the site and check the scripts with the long random names.
Expected result: script with no content.

AdGuard 2.12.47n, Chrome

**Comment by Alex-302** [comment]
Sample of ad content:
https://gist.githubusercontent.com/Alex-302/3073cbadf3d92516382aec69c9aad793/raw/b943d82d181507f528cb133b98e1fb0ec54a809d/CoreLibs-issues-329

**Comment by sxgunchenko** [comment]
core/pull-requests/394
