### ISSUE TITLE
allo.google.com

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#333]
@adguard-bot commented on [Mon Apr 23 2018](https://github.com/AdguardTeam/AdguardFilters/issues/15184)

### Issue URL (Incorrect Blocking)
[https://allo.google.com/web](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fallo.google.com%2Fweb)
### Comment
Username: @altokarev
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/2PycNBO.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Mac
AdGuard version: | 1.5.6
Browser: | Chrome
Filters: | Russian,<br>English,<br>Spyware,<br>Social media,<br>Filter unblocking search ads and self-promotion,<br>Annoyances

---

@Alex-302 commented on [Tue Apr 24 2018](https://github.com/AdguardTeam/AdguardFilters/issues/15184#issuecomment-383899552)

what is wrong?

---

@ameshkov commented on [Fri Jun 08 2018](https://github.com/AdguardTeam/AdguardFilters/issues/15184#issuecomment-395886821)

Does not work with AG for Mac enabled. Seems to a bug.

**Comment by nkartyshov** [comment]
It's bug in the CoreLibs.
Workaround: Excluding an application from ad blocking.

**Comment by sfionov** [comment]
Wrong ticket?

**Comment by nkartyshov** [comment]
@sfionov Sorry, confused tasks.

**Comment by sxgunchenko** [comment]
cannot reproduce on the current version
