### ISSUE TITLE
When filtering is disabled via Assistant, the rule should have the $important modifier

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#337]

**Comment by TPS** [comment]
Like the exclusion system in the filtering log, shouldn't this be adaptable? From what I see, `$important` is _only_ added to the excluding rule whenever the blocking rule _also_ has it.

**Comment by BlazDT** [comment]
Issue is sometimes we have $important rules to override third-party exclusion rules and if the user wants to unblock that site, it should be unblocked, completely.

**Comment by TPS** [comment]
Sure, but if I want to fine-tune my exclusion w/ higher-level block, I'm SOL when I've an `$important` exception, per the [blocking order](https://github.com/AdguardTeam/AdguardForAndroid/issues/1187#issuecomment-298334821).  Or don't external filters follow that?

**Comment by BlazDT** [comment]
I understand you, but the text in Extension is "Protection on this website" and therefore that switch should do what it actually says.

**Comment by szolin** [comment]
This is already implemented for 'change_filtering_state' event from userscripts.
