### ISSUE TITLE
JavaScript rules don't work on elsfile.org

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#339]
AdGuard nightly 2.12.52

To reproduce go here - http://elsfile.org/srnwne2g5mmr
You will see antiadblock message which should be fixed by `JS` rule.
For test purpose I added rule like that:
`elsfile.org#%#console.log("test");`
but it also doesn't work

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/41242781-b88dc8e4-6da0-11e8-8494-20123ea92a97.png)

</details>
<br>

By the way, I noticed that on http://www.cdaction.pl/ `JS` rules are not applied to main page, for example I added `cdaction.pl#%#console.log("test");` and `cdaction.pl#%#alert("test");` and it was applied only to iframes like `ifr-lib.cdaction.pl`, but not to main page.
<details><summary>Screenshot</summary>

![screenshot_2018-06-11-17-53-19](https://user-images.githubusercontent.com/29142494/41243084-9550402c-6da1-11e8-9930-bc7b7f6c7852.png)

</details>
<br>

https://github.com/AdguardTeam/AdguardFilters/issues/17684

**Comment by ameshkov** [comment]
Thank you for reporting it!

**Comment by sxgunchenko** [comment]
core/pull-requests/396
