### ISSUE TITLE
`$generichide` doesn't work on oploverz.in

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#340]
AdGuard nightly 2.12.52
To reproduce:
Enable English filter and go here - https://www.oploverz.in
It seems that `$generichide` doesn't work correctly.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/41248567-bbebdeb6-6db1-11e8-9091-cc10dc0f3a82.png)

</details>
<br>

One more thing, I'm not sure if it's a bug, but it looks strange.
There are other scripts between
 `<!-- Start: injected by Adguard -->` and `<!-- End: injected by Adguard -->` tag.
It happens on https://m.onet.pl/
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/41248921-c0a6d89c-6db2-11e8-8e3d-df3af7ff406a.png)

</details>
<br>

https://github.com/AdguardTeam/AdguardFilters/issues/17679

**Comment by ameshkov** [comment]
Assigned to myself, for now, I'll collect more details.

**Comment by ameshkov** [comment]
Resolved in `core/pull-requests/426`
