### ISSUE TITLE
AdGuard does not work well with antizapret proxy

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#341]
## Steps to reproduce

1. Install the Firefox browser
2. Install and setup AdGuard
3. Set up http://antizapret.prostovpn.org/ proxy in the browser settings
4. Try opening `lostfilm.tv`

## Expected result
The website works

## Actual result
Proxy error

![2018-06-13 13 06 49](https://user-images.githubusercontent.com/5947035/41344798-a9b6fb54-6f0a-11e8-90aa-961131d8e669.jpg)

**Comment by sxgunchenko** [comment]
can't reproduce

**Comment by ameshkov** [comment]
Logs

[adguard_logs_2.12.52_1506_2319.zip](https://github.com/AdguardTeam/CoreLibs/files/2110500/adguard_logs_2.12.52_1506_2319.zip)

Time: 23:18

**Comment by sxgunchenko** [comment]
core/pull-requests/406
