### ISSUE TITLE
Consider using stream regex libraries instead of PCRE

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#342]
e.g. std::regex

**Comment by hmage** [comment]
http://lh3lh3.users.sourceforge.net/reb.shtml

**Comment by TPS** [comment]
That's _VERY_ stale (~2010:exclamation:).…  Google-fu does better: https://www.google.com/search?q=Benchmark+of+Regex+Libraries&tbs=qdr:y&sa=X

**Comment by sfionov** [comment]
Newer does not mean better. PCRE2 has a great performance.

**Comment by TPS** [comment]
[A more recent comparison](https://www.nightfall.ai/blog/best-go-regex-library) concurs.  Also, [RE2 has been actively updated](https://github.com/google/re2/commits), so what counts as newer?
