### ISSUE TITLE
Content types negation does not work

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#343]
* `||example.org^$~stylesheet` must match every request save for stylesheets
* `||example.org^$~stylesheet,~script` must match every request save for stylesheets and scripts

Here's the list of content type modifiers:
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#content-type-modifiers

**Comment by hmage** [comment]
Already implemented, but had no explicit tests for each of the modifiers in negative form.

/pull-requests/413/
