### ISSUE TITLE
[Android] HAR file is not recorded

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#345]
Resulting file is just a dummy:
```
{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "AGProxy",
      "version": "1.0"
    },
    "browser": {
      "name": "",
      "version": ""
    },
    "entries": [
    ]
  }
}
```
Android 5.1.1 rooted, AdGuard 2.12.52b

**Comment by ameshkov** [comment]
Guys, please handle this issue as well:
https://fiddler.ideas.aha.io/ideas/FID-I-349

**Comment by Alex-302** [comment]
This is another issue
https://github.com/AdguardTeam/CoreLibs/issues/326

**Comment by sxgunchenko** [comment]
core/pull-requests/407
