### ISSUE TITLE
Youtube app gets network connection error when 'mobile filter' is turned on

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/CoreLibs#347]
report from telegram, reproduced
v2.12.60

It works well on previous nightly version and @Alex-302 said that there is no bad rules in the mobile filter.

**Comment by ameshkov** [comment]
Might be the same issue as #346

**Comment by Alex-302** [comment]
@ameshkov try to stop Youtube and clear app's data.

**Comment by ameshkov** [comment]
The same thing, it works as it should.

**Comment by zebrum** [comment]
I have android 6.

**Comment by ameshkov** [comment]
This must be related to HTTPS filtering guys.

**Comment by Alex-302** [comment]
I can't reproduce this issue without filters. But exclusions don't help.

**Comment by sxgunchenko** [comment]
core/pull-requests/438

**Comment by ameshkov** [comment]
It's back after the last nightly update

**Comment by sxgunchenko** [comment]
core/pull-requests/495
