### ISSUE TITLE
Embedded web view fails to display page when some resources are blocked in Yandex apps

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#348]

**Comment by sfionov** [comment]
Seems to be a bug in Yandex.Weather - they don't show map if tracking host cannot be accessed.

**Comment by Alex-302** [comment]
added `@@||awaps.yandex.ru^$app=ru.yandex.searchplugin`

**Comment by sfionov** [comment]
Reopened.
Yandex uses chromium view with some error callbacks set. And displays error every time when some page element is not loaded in that view due to connection error. So, blocking connections to ad sites leads to full screen error notification :(

**Comment by sfionov** [comment]
@Alex-302 Seems that we can't do nothing more on CoreLibs side.

**Comment by Alex-302** [comment]
What should we do with it?

**Comment by ameshkov** [comment]
Not a CoreLibs bug anyway.

As I understand, the issue is already resolved.
