### ISSUE TITLE
Reachability test breaks Telegram

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#350]
When server is unavailable (e.g. blocked by government), Adguard caches this fact and starts refusing connections to this server to save network traffic. But seems that for Telegram "Connection refused" to its server means "try again". So, Telegram may stuck trying to connect to 3 blocked servers indefinitely.

We should repeat behaviour of original connection.

**Comment by szolin** [comment]
core/pull-requests/436
