### ISSUE TITLE
HTTPS issues [Android, Windows]

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#351]
* https://ria.ru/
`err_connection_refused`
* https://66.ru/
`err_connection_reset`

AdGuard - last nightly builds.

**Comment by ameshkov** [comment]
> https://ria.ru/

Works okay on Win.

> https://66.ru/

It does load on the latest pre-nighly build on Win, but HTTPS is not filtered due to an old TLS version.
Will be resolved in #336

**Comment by Alex-302** [comment]
> Works okay on Win.

not on my end(Win/Droid)

**Comment by ameshkov** [comment]
PM'd you another build, try it

**Comment by ameshkov** [comment]
@sfionov 
It seems that 66.ru won't work without 3DES:

> They can be re-enabled using the
> enable-weak-ssl-ciphers option to Configure.

**Comment by TPS** [comment]
Umm, then is this worth "fixing"⁉️  Isn't [3DES ___way___ deprecated](https://sweet32.info/)?

**Comment by sfionov** [comment]
We shouldn't deprecate more than browsers to be able to filter all possible websites.

**Comment by TPS** [comment]
What are ramifications if AG supports ancient broken ciphers, but system (other than some outdated browser cipher stack) doesn't?  Can a toggle to allow this be buried in `Advanced` someplace (defaulted off‼), with a ___GIANT___ notice⁉️

**Comment by ameshkov** [comment]
AG does not strengthen the browser's security. We should use exactly the same ciphers as the browser being filtered and if Chrome devs prefer to use this cipher, we won't change it.

**Comment by TPS** [comment]
I'm not so much worried about strengthening browser's security as weakening system's.  If I've no apps/system that supports, e.g., 3DES, will this affect me?

**Comment by sfionov** [comment]
No, because AdGuard use same ciphersuites set as application use. If application doesn't use 3DES, AdGuard will not use it too. This task about restoring support of ciphers, that are still rarely used, in bundled OpenSSL, not about enabling them for every connection.
