### ISSUE TITLE
Return UrlFilterRule object with all known properties instead of ruleText in events on Mac

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#357]
See NativeUrlFilterRule and RequestProcessedEvent in the Android adapter.

**Comment by sfionov** [comment]
1) Android - Return RuleType in NativeFilterRule object
2) Mac - return object like NativeFilterRule in both RequestProcessedEvent and HtmlElementRemovedEvent. Now only ruleText is returned in ANUrlFilterResult, not rule object.

**Comment by sxgunchenko** [comment]
core/pull-requests/461
