### ISSUE TITLE
Unable to play videos on chocotv.com.tw by chrome

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#364]
@lancelot-moon commented on [Tue Jun 26 2018](https://github.com/AdguardTeam/AdguardForAndroid/issues/1941)

https://www.chocotv.com.tw/drama/9550/eps/1

It still doesn't work even if I already manually added chocotv.com.tw in the whitelist of HTTPS filtering.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/oDkHGa2.png)
</details><br/>

I don't know if the solution is the same as what was reported in Adguard For Windows.
https://github.com/AdguardTeam/AdguardForWindows/issues/2264

PS: Need Taiwan IP for watching videos on chocotv.com.tw.
Thanks.

---

@ameshkov commented on [Tue Jun 26 2018](https://github.com/AdguardTeam/AdguardForAndroid/issues/1941#issuecomment-400301041)

Stable or nightly AG?

---

@lancelot-moon commented on [Tue Jun 26 2018](https://github.com/AdguardTeam/AdguardForAndroid/issues/1941#issuecomment-400301800)

AG v2.12.74η

It also provides Android app.
https://play.google.com/store/apps/details?id=com.chocolabs.app.chocotv&hl=zh_TW

If **not** adding chocotv.com.tw in the whitelist of HTTPS filtering, videos can be still normally played in its app.

The problem is in browsers.

Thanks.

**Comment by ameshkov** [comment]
Multiple issues with this website.

Test page: https://www.chocotv.com.tw/drama/9778/eps/1

Issue 1: HTML parser seems to be failing: the filtered HTML response is 550kb while when AdGuard is disabled it is over 800kb.

Issue 2: The issue is not gone even when the website is added to the whitelist.

**Comment by sfionov** [comment]
Another broken site is https://kotaku.com

**Comment by sfionov** [comment]
Fixed in CL 1.1.16 / AG 2.12.82n
