### ISSUE TITLE
Unnecessary onEvCertificate callback

### ISSUE THREAD

**Issue by Stillness-2** [AdguardTeam/CoreLibs#370]
Set in proxy configuration:
```
httpsFiltering.filterEvCertificates = NO;
httpsFiltering.alwaysFilterEvDomainList = @"apple.com";
```
After that go to `apple.com` in `Safari`. You will obtain the callbacks on: `www.apple.com`, `securemetrics.apple.com`, but should not.

**Comment by Stillness-2** [comment]
Also, `onEvCertificate` callback is only necessary when this is a unique event,
when the first time we found such a certificate on the site.

**Comment by szolin** [comment]
/core/pull-requests/504

**Comment by Stillness-2** [comment]
Domains in `httpsFiltering.alwaysFilterEvDomainList` must applyed to subdomains too.

**Comment by sfionov** [comment]
Fixed in https://github.com/AdguardTeam/CoreLibs/issues/437
