### ISSUE TITLE
Privat24 app misbehaves when AG root+proxy mode

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#371]
## Steps to reproduce

1. Switch AG to proxy+root mode
2. Install and run Privat24 app

## Expected result
It runs okay

## Actual result
It refuses to run and tells that there is a newer version available

**Comment by ameshkov** [comment]
There are actually more issues like that with proxy mode. For instance, there's an issue with Discord

**Comment by sxgunchenko** [comment]
core/pull-requests/457
