### ISSUE TITLE
AG for Android v2.12.102η will crash when searching "adguard" on google with language and time conditions by chrome.

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#381]
@lancelot-moon commented on [Tue Jul 10 2018](https://github.com/AdguardTeam/AdguardForAndroid/issues/1969)

As the title, it will crash when searching "adguard" on google with language and time conditions by chrome.

https://i.imgur.com/tM1ReVP.png

B/R

**Comment by ameshkov** [comment]
Report data:
http://sentry.adguard.com/adg/adguard-android-rs/issues/5852/

**Comment by lancelot-moon** [comment]
In my case, after enabling AG for Android...
Reproduction steps:
1. Search "adguard" on google by chrome.
2. Set the conditions "Chinese language" and "the latest 24 hrs" for the searching results.
3. If AG doesn't crash at that time, repeatedly try to search other words and then search adguard on google by chrome. And slide the page.
4. Finally, AG will crash.

**Comment by sfionov** [comment]
Fixed in core/pull-requests/477

**Comment by ameshkov** [comment]
Available in the Android nightly 2.12.106
