### ISSUE TITLE
Extend HtmlElementRemovedEvent

### ISSUE THREAD

**Issue by admitrevskiy** [AdguardTeam/CoreLibs#391]
Please, extend HtmlElementRemovedEvent with field of URL that triggered the block.

It's necessary to build unblock rules for users.

**Comment by ameshkov** [comment]
What we need to know:

1. Rule type that caused this event.
2. If the element was removed due to a basic rule, we need to know what was the URL of the element
3. Removed element tag name
4. Content type

**Comment by sfionov** [comment]
@ameshkov Content type of what thing? Rule object have requesttypes of url filter rule, if needed. Is it about them?

**Comment by sfionov** [comment]
core/pull-requests/485
