### ISSUE TITLE
ppomppu.co.kr cannot be opened

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#392]
@adguard-bot commented on [Tue Jul 10 2018](https://github.com/AdguardTeam/AdguardFilters/issues/19521)

### Issue URL (Incorrect Blocking)
[http://www.ppomppu.co.kr/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fwww.ppomppu.co.kr%2F)
### Comment
> I can't open the site:www.ppomppu.co.kr , even though I already added whitelist.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/jPXU1Xv.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 8.1.0
AdGuard version: | 2.12.102
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | disabled
Filters: | English,<br>Spyware,<br>Social media,<br>Mobile Ads,<br>List-KR

---

@bug-killer commented on [Tue Jul 10 2018](https://github.com/AdguardTeam/AdguardFilters/issues/19521#issuecomment-403899453)

[adguard_logs_2.12.102_1107_0131.zip](https://github.com/AdguardTeam/AdguardFilters/files/2181417/adguard_logs_2.12.102_1107_0131.zip)
Log files

**Comment by szolin** [comment]
/core/pull-requests/493
