### ISSUE TITLE
Videos fail to play, apps won't work properly (Google Play Services).

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/CoreLibs#394]
AdGuard version (Nightly): 2.12.106n
Android version: 7.1.2 - 8.1.0

Settings by default.

This problem exists if AdGuard filters Google Play Services.

Videos do not play properly, apps won't load normally or crashes.

Examples:
*GPS in the filtering list.
"...The latest nightly, 2.12.106, crashes if I try to play any short video clip showcasing an app on Google Play. I can reproduce it on any of my Samsung devices, so it shouldn't be hard to replicate..."

*GPS not in the filtering list.
"...If I fully disable filtering of Google Play Services, AdGuard no longer crashes when I try to play video clips in the Play Store. And the clips are then playable, too..."

**Comment by ameshkov** [comment]
@TheHasagi what about the certificate, is it moved to the system store?

@sfionov could it be that this is a protobuffilter crash?

**Comment by TheHasagi** [comment]
@ameshkov 
"...I'll send you the logs later today.

Yes, the certificate is in the system store..."

**Comment by sxgunchenko** [comment]
Crash was fixed along with #374.
Failure to play videos is related to #347.

**Comment by sxgunchenko** [comment]
Fixed along with #347
