### ISSUE TITLE
Internet speed test doesn't work on speed.measurementlab.net

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#396]
Original issue - https://github.com/AdguardTeam/AdguardFilters/issues/19783

### Steps to reproduce
1. Open this website - http://speed.measurementlab.net/
2. Begin test.

### Expected behavior
Test should start.

### Actual behavior
Test doesn't work.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/42784375-543b7268-894f-11e8-997e-2e6f630bf541.png)

</details>

### Your environment
AdGuard 2.12.106n

**Comment by ameshkov** [comment]
Thank you! That's a bug indeed.

**Comment by sfionov** [comment]
May be because we don't properly handle 100-continue.

**Comment by sxgunchenko** [comment]
Our current scheme with reachability tester causes this issue. As we connect to the server twice (in the tester and in the proxy session) second connect is refused by the server in this case.
Seems like it will be fixed along with #424

**Comment by sxgunchenko** [comment]
Fixed along with #424

**Comment by sxgunchenko** [comment]
As getting rid of reachability tester raised some issues and the tester is going to be restored this one becomes actual again

**Comment by sfionov** [comment]
Test works now
