### ISSUE TITLE
Pics can't be attached to a message

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/CoreLibs#399]
[vk.com](vk.com)
### Comment
Username: @kolyan-246
> Невозможно загружать изображения в диалоги, сразу же ошибка, однако через браузер изображения отправляются нормально. Проблема появилась с обноелвнием adguard до 2.12.113n

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/RZPPLTT.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 7.0
AdGuard version: | 2.12.113η
Browser: | Kate Mobile 50.1
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | Russian,<br>Mobile Ads,<br>Annoyances,<br>English,<br>Spyware,<br>Social media

**Comment by sxgunchenko** [comment]
core/pull-requests/539
