### ISSUE TITLE
Possible heap corruption on AArch64 with optimizations enabled

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#400]

**Comment by ameshkov** [comment]
Might be an openssl bug as all these crashes do happen at random places inside the openssl code:

https://sentry.adguard.com/adg/adguard-android-rs/issues/6925/activity/
https://sentry.adguard.com/adg/adguard-android-rs/issues/6932/activity/
https://sentry.adguard.com/adg/adguard-android-rs/issues/6930/activity/

**Comment by sfionov** [comment]
We may try prebuilding OpenSSL with the good old GCC, but some CI engineering is needed for that.

**Comment by sfionov** [comment]
OpenSSL is built with GCC already
