### ISSUE TITLE
AGCertificateVerifier::verifyDNSName crash

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#407]
https://sentry.adguard.com/adg/adguard-android-rs/issues/6532/?query=is:unresolved

**Comment by sfionov** [comment]
https://sentry.adguard.com/adg/adguard-android-rs/issues/6643/ -- for new version

**Comment by sfionov** [comment]
https://sentry.adguard.com/adg/adguard-android-rs/issues/6769/ -- for new version
Note that on this time it crashes on malloc, not free.
Looks like heap corruption.

**Comment by sfionov** [comment]
For new version:
https://sentry.adguard.com/adg/adguard-android-rs/issues/6879/
https://sentry.adguard.com/adg/adguard-android-rs/issues/6813/

**Comment by ameshkov** [comment]
https://sentry.adguard.com/adg/adguard-android-rs/issues/7055/activity/

**Comment by sfionov** [comment]
Done by updating OpenSSL to the stable version
