### ISSUE TITLE
Timeout exception while stopping the WebSocket server

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#411]
Crash report:
https://sentry.adguard.com/adg/adguard-android-rs/issues/6624/?query=is:unresolved

```
11:14:50.077 [pool-5-thread-1] INFO  Native.AGProxyServer - Destroying WebSocket Server...
11:15:50.056 [protection-pool-1-thread-2] ERROR com.adguard.android.service.y - Cannot finish the task StopProtection execution in time
```

**Comment by szolin** [comment]
added more logs - /core/pull-requests/520

**Comment by sfionov** [comment]
Logs from new version:
https://sentry.adguard.com/adg/adguard-android-rs/issues/6624/events/341625/

**Comment by sfionov** [comment]
Logs from new version:
https://sentry.adguard.com/adg/adguard-android-rs/issues/6928/

**Comment by sfionov** [comment]
Both backtraces have `cssfilter_buildcss` at cssfilter.c:504 while getting content script.

**Comment by szolin** [comment]
core/pull-requests/531
