### ISSUE TITLE
 Protection doesn't start

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/CoreLibs#414]
MIUI Global 9.5
AG 2.12.125n

logs: https://uploads.adguard.com/adguard_logs_2.12.125_2507_1837_2018-07-25_19-09-38.zip

**Comment by sfionov** [comment]
Issue moved to [AdguardTeam/AdguardForAndroid #2001](https://github.com/AdguardTeam/AdguardForAndroid/issues/2001) via [**ZenHub**](https://www.zenhub.com/)
