### ISSUE TITLE
YouTube search is broken by `Strip tracking parameters from URLs`

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#417]
URL: https://www.youtube.com/results?search_query=Wizardry&page=&utm_source=opensearch
![image](https://user-images.githubusercontent.com/8361299/43387971-9768e8f8-93f0-11e8-93c7-17efc09e5922.png)

When `&page=` or `&utm_source=` is removed from url, page loads.

AdGaurd for Windows 6.3.1399.4073

**Comment by sxgunchenko** [comment]
can't reproduce with corelibs build
