### ISSUE TITLE
Extract the userscripts C API

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#429]
Instead of the current console app, we'd better have a C API that can be used directly from the client apps.

Unlike the case of the console tool, we don't really need an option to download the userscript.

What we need from it:

* An option to parse the userscript content and download its resources. The result must be a `meta.json` file.
* An option to parse the userscript WITHOUT downloading its resources (that will be used for the update check & validation).
* The download process needs to be delegated to the client app. The thing is there might be a proxy server configured in the app settings or on the system level, and it'd be easier if the files are downloaded by the client app.

Let's use `feature/userscripts_api ` branch for this task

### Checklist

* [x] Expose API for parsing userscripts source code and downloading resources
* [x] Fix the userscripts validation in CoreLibs (it must not crash on an invalid/unknown property)
* [x] Make it understand more tags than it does now (see the comment 1)

**Comment by ameshkov** [comment]
Also, the current userscript parser implementation ignores some of the tags which we might need.

To see the list of tags, check the `UserscriptMeta.cs`

**Comment by szolin** [comment]
core/pull-requests/583

**Comment by szolin** [comment]
/core/pull-requests/588

**Comment by szolin** [comment]
/core/pull-requests/607
