### ISSUE TITLE
VpnService.protect does not work as it should

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#436]
The log is in PM.

**Comment by ameshkov** [comment]
The issue still happens even with .171 build. Any idea on how to mitigate that? Maybe we should restrict the number of active connections from a single app? Smth like - start dropping connections if there're more than 500 active connections?

**Comment by TPS** [comment]
> start dropping connections if there're more than 500 active connections?

@ameshkov That seems like a breaking _mitigation_ if Android can handle said 500 connections _w/o_ AG.…

**Comment by ameshkov** [comment]
After all, it appears that the issue is caused by AdGuard app filtering itself (despite that we configured Android explicitly to not do it). This issue requires additional investigation.

**Comment by sfionov** [comment]
We already checked it in https://github.com/AdguardTeam/CoreLibs/issues/440 - no problems with protect.

This may be a buggy firmware in which disallowedApplications doesn't work for AdGuard itself.
So it may be better to restore old behaviour when socket protecting was always on.

**Comment by sfionov** [comment]
Duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/2093
