### ISSUE TITLE
Websites from SSL whitelist are still signed with AdGuard Personal CA

### ISSUE THREAD

**Issue by admitrevskiy** [AdguardTeam/CoreLibs#437]
Some sites from SSL whitelist are signed with AG Personal CA

For example domains from default ssl whitelist:
`lastpass.com`
`instapaper.com`

This behavior is observed since 2.12.45 AG for Android.

**Comment by ameshkov** [comment]
The problem is that CoreLibs checks domains for exact matches while it should include subdomains as well.

**Comment by sxgunchenko** [comment]
core/pull-requests/579
