### ISSUE TITLE
Use X-Requested-With to detect object-subrequest content type

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#44]
https://github.com/AdguardTeam/AdguardForWindows/issues/1435

Review ID: ADWIN-CR-222

**Comment by ameshkov** [comment]
Please don't forget to update java tests as well.

**Comment by hmage** [comment]
Need to update C API to pass more headers than just `Accept` from request and `Content-Type` from response, preferably all request and response headers and let C do the logic.
