### ISSUE TITLE
Check that AdGuard works when you enable filtering of itself in the Apps Mgmt

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#440]

**Comment by sfionov** [comment]
> // Note that some old Android custom firmwares might ignore addDisallowedApplication call
> // That's why we check the Android version additionally
May be there are buggy firmwares exist even with android 7.0+ ?

**Comment by sxgunchenko** [comment]
Was checked on nexus 6p (android 8.1.0) and nexus 5 (android 6.0.1) in both cases AdGuard works well

**Comment by sfionov** [comment]
IMHO that it is easier just not to emit socket protection for any firmwares and settings.
Or create the list of buggy firmwares that ignores adguard in disallowedApplications.
