### ISSUE TITLE
com.viber.voip

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#441]
@adguard-bot commented on [Sun Aug 12 2018](https://github.com/AdguardTeam/AdguardFilters/issues/20991)

### Issue URL (Incorrect Blocking)
[https://com.viber.voip](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fcom.viber.voip)
### Comment
> Добрый день, Как я писал на 4pda иногда из-за AdGuard не могут отправиться сообщения в Viber или WhatsApp. Высылаю лог. Сообщение пытался отправить в 16:16-16:17. После чкго сделал обновление фильтров в AdGuard (произошел автоматически перезапуск защиты) и сразу после этого сообщения ушли. Случается весьма часто и порядком надоело. :( Надеюсь логи вам помогут!

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/PY9dCfw.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 8.0.0
AdGuard version: | 2.12.140
Browser: | Viber
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | disabled
Filters: | Russian,<br>English,<br>Spyware,<br>Social media,<br>Mobile Ads,<br>Annoyances

---

@bug-killer commented on [Sun Aug 12 2018](https://github.com/AdguardTeam/AdguardFilters/issues/20991#issuecomment-412302300)

[debug.txt](https://github.com/AdguardTeam/AdguardFilters/files/2280562/debug.txt)
[state (14).txt](https://github.com/AdguardTeam/AdguardFilters/files/2280563/state.14.txt)
[license (4).txt](https://github.com/AdguardTeam/AdguardFilters/files/2280564/license.4.txt)

**Comment by sfionov** [comment]
We need to test it with all ports except 80 blocked.
It seems that our HTTP bypassing is not so good for pseudo-http, and switching to full bypass is needed.

**Comment by sfionov** [comment]
This is not plain HTTP problem. Leaving open.

**Comment by sfionov** [comment]
Can't reproduce. Please reopen if there will be reports with after version 2.12.196
