### ISSUE TITLE
viewer.ipaper.io

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#442]
@adguard-bot commented on [Fri Aug 10 2018](https://github.com/AdguardTeam/AdguardFilters/issues/20943)

### Issue URL (Incorrect Blocking)
[http://viewer.ipaper.io/moment/kniga-1/?page=241&ForceLanguage=ru](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fviewer.ipaper.io%2Fmoment%2Fkniga-1%2F%3Fpage%3D241%26ForceLanguage%3Dru)
### Comment
> При отключении AdGuard страница открывается без ошибок. После включения url не открывается
> 
> http://viewer.ipaper.io/moment/kniga-1/?page=241&ForceLanguage=ru

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/C6bYimg.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 6.0
AdGuard version: | 2.12.140β
Browser: | Boat Browser
AdGuard mode: | proxy
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | Russian,<br>Mobile Ads,<br>English,<br>Spyware,<br>Social media

**Comment by szolin** [comment]
The problem was due to "Content-Encoding: deflate".
core/pull-requests/594
