### ISSUE TITLE
router.asus.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#444]
@adguard-bot commented on [Thu Aug 16 2018](https://github.com/AdguardTeam/AdguardFilters/issues/21167)

### Issue URL (Incorrect Blocking)
[http://router.asus.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Frouter.asus.com)
### Comment
> My network address, 192.168.2.1, which redirects me to my Asus router's admin page (address then shows up as router.asus.com) is being blocked by Adguard. I tried adding both addresses to the whitelist but that didn't solve the issue. Thank you.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/DffbJLl.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/HCBBJRX.png)
</details>
<details>
  <summary>Screenshot 3</summary>

  ![Screenshot 3](https://reports-img.adguard.com/xwsZWvz.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 9
AdGuard version: | 2.12.178η
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | Mobile Ads,<br>Annoyances,<br>English,<br>Spyware,<br>Social media,<br>Spanish/Portuguese
Other extensions used: | None

---

@BlazDT commented on [Thu Aug 16 2018](https://github.com/AdguardTeam/AdguardFilters/issues/21167#issuecomment-413614431)

I sadly don't have an Asus router.

Please try this rule:

`@@||192.168.2.1^$document`

---

@AdamWr commented on [Thu Aug 16 2018](https://github.com/AdguardTeam/AdguardFilters/issues/21167#issuecomment-413624781)

I have Asus router and I can reproduce it, but unfortunately it doesn't look like a filter lists issue, because it doesn't work even with all filter lists disabled.

**Comment by ameshkov** [comment]
@AdamWr most likely this is due to a flawed HTTP implementation on the Asus router.

@sfionov what kind of logs would you need to figure out what's wrong?

**Comment by lancelot-moon** [comment]
Mine is also ASUS router.
I can reproduce it.

With Lumen Privacy Monitor's certificate, I can open ASUS router's setting page.
https://play.google.com/store/apps/details?id=edu.berkeley.icsi.haystack

But I can't open ASUS router's setting page with AdGuard's certificate even if disabling HTTPS filtering.

**Comment by sfionov** [comment]
@lancelot-moon 
New nightly 2.12.191 has fixes for HTTP protocol.
Can you please check if the problem persists?

**Comment by sfionov** [comment]
Thanks!
