### ISSUE TITLE
[Android] lk-subscr.tricolor.tv

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#449]
@adguard-bot commented on [Wed Aug 15 2018](https://github.com/AdguardTeam/AdguardFilters/issues/21111)

### Issue URL (Incorrect Blocking)
[https://lk-subscr.tricolor.tv/Mobile#Login](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Flk-subscr.tricolor.tv%2FMobile%23Login)
### Comment
Username: @shaman4ik2006
> После недавнего обновления не работают многие страницы сайта tricolor.tv , в частности личный кабинет, страница активации карт экспресс оплаты, страница оплаты банковскими картами.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/iKtL6vi.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 5.0
AdGuard version: | 2.12.140β
Browser: | Chrome
AdGuard mode: | proxy
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | disabled
Filters: | Russian,<br>Filter unblocking search ads and self-promotion,<br>Mobile Ads,<br>English

---

@Alex-302 commented on [Fri Aug 24 2018](https://github.com/AdguardTeam/AdguardFilters/issues/21111#issuecomment-415816587)

Возможно баг. Исключения `$elemhide,urlclock,jsinject,content` не помогают, только `$document`.

**Comment by Alex-302** [comment]
Disable mobile filter before checking.

**Comment by sxgunchenko** [comment]
cannot reproduce with current version
