### ISSUE TITLE
Allow applying multiple $replace rules to a single web request

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#45]
##### **`replace`**

This modifier completely changes the rule behavior. If it is applied, the rule will not block the request. The response is going to be modified instead. 

> #### Please note
> You will need some knowledge of regular expressions to use this modifier.

> #### Compatibility with different versions of AdGuard
> Rules are supported by AdGuard for Windows, Mac, Android and by the AdGuard's Firefox add-on.
> This type of rules don't work in extensions for other browsers because they are unable to modify content on the network level.

###### `$replace` rules features

* `$replace` rules apply to any text response, but will not apply to binary (`media`, `image`, `object`, etc).
* `$replace` rules do not apply if the size of the original response is more than 3MB.
* `$replace` rules have a higher priority than other basic rules (**including** exception rules). So if the request corresponds to two different rules one of which has the `$replace` modifier, this rule will be applied.
* Document-level exception rules with `$content` or `$document` modifiers do disable $replace rules for requests matching them. Exception rules with `$content` or `$document` modifier.
> `$replace` value can be empty in the case of exception rules. See examples section for further information.

> Multiple rules matching a single request.
> In case if multiple `$replace` rules match a single request, we will apply each of them. **The order is defined alphabetically.**

###### **$replace Syntax**

In general, `replace` syntax is similar to replacement with regular expressions [in Perl](http://perldoc.perl.org/perlrequick.html#Search-and-replace).

```
replace = "/" regex "/" replacement "/" modifiers
```

* `regex` — regular expression.
* `replacement` — a string, that will be used to replace the string corresponding to` regex`.
* `modifiers` — regular expression flags. For example, `i` - insensitive search, or` s` - single-line mode.

In the `$replace` value, two characters must be escaped: comma (`,`) and (`$`). Use (`\`) for it. For example, an escaped comma looks like this: `\,`.

###### `$replace` example

```
||example.org^$replace=/(<VAST[\s\S]*?>)[\s\S]*<\/VAST>/\$1<\/VAST>/
```

There are three parts in this rule:

* Regular expression: `(<VAST(.|\s)*?>)(.|\s)*<\/VAST>`
* Replacement `\$1<\/VAST>` (please note, that `$` is escaped)
* regular expression flags: `i` (insensitive search)

You can see how this rule works here:
http://regexr.com/3cesk

###### Multiple `$replace` rules example

1. `||example.org^$replace=/X/Y/`
2. `||example.org^$replace=/Z/Y/`
3. `@@||example.org/page/*$replace=/Z/Y/`

* Both rule 1 and 2 will be applied to all requests sent to `example.org`.
* Rule 2 is disabled for requests matching `||example.org/page/`, **but rule 1 still works!**.

###### Disabling`$replace` rules

* `@@||example.org^$replace` will disable all `$replace` rules matching `||example.org^`.
* `@@||example.org^$document` or `@@||example.org^$content` will disable all `$replace` rules **originated from** pages of `example.org` **including the page itself**.

**Comment by ilvjyw** [comment]
Allow $replace and other rules(like Element hiding rules and CSS rules) to a single web request !
@ameshkov

**Comment by ameshkov** [comment]
`$replace` -- for sure.
CSS/element hiding - are already applied that way

**Comment by ilvjyw** [comment]
@ameshkov You don't understand what I mean
[how-to-create-your-own-ad-filters]:"If a replace rule was applied to the page, other rules (e.g. cosmetic) are not going to be applied to the code."
I hope:
" If a replace rule was applied to the page, other rules should also to be applied to the code."

**Comment by ameshkov** [comment]
@ilvjyw 
Ops, it seems that the documentation is a bit outdated. 
`$replace` rules can be applied along with cosmetic rules at the moment.

**Comment by ilvjyw** [comment]
@ameshkov 
Adguard for windows is ok,but Adguard for Android Unrealized!!!
You  can test it yourself!

**Comment by ameshkov** [comment]
@ilvjyw should be ok according to what I see in the source code. Are you on the latest AG for Android version (2.9.135)? How do you check it?

**Comment by ilvjyw** [comment]
@ameshkov 
I used AG for Android version (2.9.135)

**Comment by ameshkov** [comment]
Need more details: website, rule, how did you check it

**Comment by ilvjyw** [comment]
website:http://m.baidu.com/
user rule:
baidu.com##[id^="tab_news"],#bottom
baidu.com$replace=/B.init/fuck/

**Comment by ilvjyw** [comment]
@ameshkov Let me know if there is any result

**Comment by ameshkov** [comment]
@ilvjyw I can't find `B.init` in the `m.baidu.com` source code. Where is it?

**Comment by ilvjyw** [comment]
@ameshkov 
Please use Android  or IOS user-agent access
If you can not find "B.init" ,You can test other word that you can find
![Uploading `E]XJM4RBR$E][CQA]5OKQB.png…]()

**Comment by ilvjyw** [comment]
@ameshkov  Help me please!

**Comment by ameshkov** [comment]
@ilvjyw please wait a bit. The issue will be released before new Android version release.

**Comment by ilvjyw** [comment]
@ameshkov Thanks! waiting

**Comment by szolin** [comment]
/core/pull-requests/648

**Comment by ameshkov** [comment]
Does not work as it should.

### Steps to reproduce

1. Add these three rules:
    ```
    ||example.org^$replace=/Example/Hello/
    ||example.org^$replace=/Domain/Tester/
    @@||example.org^$replace=/Domain/Tester/
    ```
2. Open example.org

### Expected

Expected title: `Hello Domain`

Expected: All rules which were applied to the request must have been indicated in the RequestProcessedEvent:
```
||example.org^$replace=/Example/Hello/
@@||example.org^$replace=/Domain/Tester/
```

### Actual result

Title has not been changed
No rules were indicated

**Comment by szolin** [comment]
/core/pull-requests/800
