### ISSUE TITLE
com.washingtonpost.rainbow

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#452]
@adguard-bot commented on [Sun Aug 19 2018](https://github.com/AdguardTeam/AdguardFilters/issues/21281)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.washingtonpost.rainbow](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.washingtonpost.rainbow)
### Comment
Username: @Yevhen1996
> the user receives this mesage only on nightly though cellular connection. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/TrOkChL.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 7.1.2
AdGuard version: | 2.12.184η
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | Russian,<br>Mobile Ads,<br>Annoyances,<br>English,<br>Spyware,<br>Social media

---

@Alex-302 commented on [Tue Aug 28 2018](https://github.com/AdguardTeam/AdguardFilters/issues/21281#issuecomment-416544050)

Not reproduced.

**Comment by sfionov** [comment]
It may be yet another IPv6-only network problem. Part of that problems will be fixed by https://github.com/AdguardTeam/AdguardForAndroid/issues/1884.

**Comment by zebrum** [comment]
@Yevhen1996 
change logging level to Record everything in Advanced settings of AdGuard, reproduce the issue and send logs to devteam at adguard.com. Mention the link to this issue in your letter please.
