### ISSUE TITLE
Pikabu app won't load articles/pictures when protection is on

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/CoreLibs#455]
@TheHasagi commented on [Wed Aug 29 2018](https://github.com/AdguardTeam/AdguardForAndroid/issues/2091)

### Steps to reproduce

1. Open AdGuard and start protection
2. Open Pikabu application [App](https://play.google.com/store/apps/details?id=ru.pikabu.android&hl=ru)

### Expected behaviour

Everything should be okay

### Actual behavior

Pikabu application won't load any images, articles and etc (Screenshot attached)

<details><summary>Screenshot:</summary>

![pkb](https://user-images.githubusercontent.com/37797229/44770099-8f60b780-ab6f-11e8-909d-4d0147fc2d74.jpg)
![pkb2](https://user-images.githubusercontent.com/37797229/44770101-8f60b780-ab6f-11e8-8200-76133a9d1d0d.jpg)

</details>

### Your environment

* Adguard version: 2.12.192n
* Adguard filtering mode: VPN / Proxy(manual/auto)
* Device model: (e.g. Google Pixel) Google Pixel
* Operating system and version (e.g. Android 7.1.2) Android 9

---

@TheHasagi commented on [Wed Aug 29 2018](https://github.com/AdguardTeam/AdguardForAndroid/issues/2091#issuecomment-416955600)

[adguard.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/2332305/adguard.zip)

---

@TheHasagi commented on [Wed Aug 29 2018](https://github.com/AdguardTeam/AdguardForAndroid/issues/2091#issuecomment-416969331)

Info update*

The issue exists only if proxy (for example, SOCKS5) is enabled.

**Comment by sfionov** [comment]
@TheHasagi Could you please check it without AdGuard but with proxy, e.g. with Shadowsocks VPN mode?

**Comment by TheHasagi** [comment]
![sh](https://user-images.githubusercontent.com/37797229/44977846-dbe23380-af71-11e8-9cc0-918f3ad7e488.png)
![sh1](https://user-images.githubusercontent.com/37797229/44977854-df75ba80-af71-11e8-9f2e-6da70f6e1d27.png)
*Update

The same issue with Shadowsocks only.

**Comment by sfionov** [comment]
Seems that app doesn't work well through any proxy.
