### ISSUE TITLE
m.4gtv.tv - some requests are blocked even if are "whitelisted"

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#456]
### Steps to reproduce
1. Open this website - https://m.4gtv.tv/show_sub.html?fsVOD_NO=201601190018
2. Play the video.

### Expected behavior

Video should plays fine and it shouldn't be an anti adblock message.

### Actual behavior

Website show anti adblock message and for some reason `imasdk.googleapis.com/js/sdkloader/ima3.js` request is not listed in the filtering log even with `@@||4gtv.tv^$document` added to user filter.
After adding `4gtv.tv` to HTTPS whitelist this request is visible in  the filtering log.
<details><summary>Screenshots:</summary>

![4gtv_3](https://user-images.githubusercontent.com/29142494/44806245-c0200b80-abc6-11e8-8299-f7915f8ec6b0.png)
![4gtv_1](https://user-images.githubusercontent.com/29142494/44806246-c0200b80-abc6-11e8-90d9-7d2874af1c07.png)

After adding `4gtv.tv` to HTTPS exclusion
![4gtv_2](https://user-images.githubusercontent.com/29142494/44806244-bf877500-abc6-11e8-8e50-3940a37fc74d.png)

</details>

### Your environment

* Adguard version: 2.12.192

**Comment by sfionov** [comment]
Adblock message is displayed even without filters

**Comment by lancelot-moon** [comment]
There are several issues.
https://github.com/AdguardTeam/AdguardForAndroid/issues/2090

1. The issue about visiting the website by Android's chrome.
We first only discuss about visiting the website, [https://www.4gtv.tv/](url).
With AG for Windows, there is no problem even if **not** adding 4gtv.tv in the whitelist of HTTPS filtering.
But the process of loading its pages by Android's chrome with AG v2.12 isn't very smooth.
Even AG v2.12 ever randomly crashed when visiting 4gtv.tv.
Something wrong in CoreLibs?

2. The issue about watching its videos by mobile browsers. (anti-adblock)
For solving its anti-adblock when watching videos on 4gtv.tv, the rules by @AdamWr are valid for desktop browsers with AG for PC, but not valid for mobile browsers with AG for Android v2.12 / Safari with the content blocker of AG Pro for iOS.

3. The issue about watching its videos by its Android app.
iOS app:
https://itunes.apple.com/tw/app/si-ji-xian-shang-ying-shi-4gtv/id1206365569?l=zh&mt=8

Android app:
https://play.google.com/store/apps/details?id=tv.fourgtv.fourgtv

With SDN filter in the subscription of AG Pro for iOS, its iOS app can normally play videos.

But its Android app can't normally play videos even if adding 4gtv.tv in the whitelist of HTTPS filtering.
The playing of videos on its Android app will be frozen with AG for Android v2.12 nightly.

**Comment by lancelot-moon** [comment]
I use AG v3.0.109 nightly.
With the new rules by @AdamWr, it can normally play videos on mobile browsers.
https://github.com/AdguardTeam/AdguardFilters/issues/26460

For its Android app, I also made rules.
https://github.com/AdguardTeam/AdguardFilters/issues/26520

I am not sure if it's because the bugs of CoreLibs were fixed.
Well, now everything seems to work well.
