### ISSUE TITLE
hu.vodafone.apps.myvodafone

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#462]
@adguard-bot commented on [Mon Aug 13 2018](https://github.com/AdguardTeam/AdguardFilters/issues/21051)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=hu.vodafone.apps.myvodafone](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dhu.vodafone.apps.myvodafone)
### Comment
> First picture: AdGuard enabled › Our systems are unavailable az the moment.
> Second picture: AdGuard disabled › no problem logging in (PIA VPN was disabled both times)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/m614fID.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/LypmfIN.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 9
AdGuard version: | 2.12.171η
AdGuard mode: | proxy
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | disabled
Filters: | Mobile Ads,<br>Annoyances,<br>English,<br>hufilter,<br>List-KR,<br>Spyware,<br>Social media,<br>German,<br>Japanese

**Comment by domebacsi** [comment]
It looks like AdGuard version 2.12.224η fixed the problem!
