### ISSUE TITLE
HTTP proxy don't work in the latest build

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#470]
`23:44:50.569 [Thread-1277] ERROR Native.OPROXY - oproxy_read_http_connect_resp: Not all bytes were parsed -- invalid HTTP headers?`

**Comment by lancelot-moon** [comment]
Have you read my questions on telegram?
HTTP proxy doesn't work.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/UZYgl3s.jpg)

![image](https://i.imgur.com/1Fk9lE6.jpg)

![image](https://i.imgur.com/Akm4bIA.jpg)

![image](https://i.imgur.com/iiFsLCh.jpg)
</details><br/>

**Comment by sfionov** [comment]
Merged, core/pull-requests/651
