### ISSUE TITLE
Cosmetic rules with only top-level domain don't work

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#475]
### Steps to reproduce
1. Add this rule to user filter - `com##body`
2. Go to https://www.google.com/ or https://adguard.com/

### Expected behavior
Website should be blank.

### Actual behavior
Cosmetic rule doesn't work.

### Your environment
AdGuard nightly 2.12.220

**Comment by ameshkov** [comment]
@AdamWr I think it behaves this way in every AG version :)

It's just in other versions it ignores `com` and applies the rule to ALL domains.

**Comment by AdamWr** [comment]
No, it works fine in AG for Windows and extension, a rule like this - `com##body` is applied only to `.com` websites.

**Comment by sxgunchenko** [comment]
core/pull-requests/781
