### ISSUE TITLE
bla.aeiou.pt is not loading chat until app is closed

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#478]
@BlazDT commented on [Tue Sep 11 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2329)

https://github.com/AdguardTeam/AdguardFilters/issues/22022

Only when I close AdGuard for Windows, it is connecting to the chat. Disabling every AdGuard module didn't work - only closing the app via tray icon.

**Comment by temis2k16** [comment]
bla is not available anymore
