### ISSUE TITLE
AdGuard Stealth Mode-third party cookies

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#479]
@dnmTX commented on [Mon Sep 10 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2328)

This could be a bug or just me imagining(if it's the latter,apologies).It's about blocking(destroying) the third-party cookies.In my Chromium browser they are set to be blocked and naturally when they got blocked you see a little icon on the address bar indicating it.

Like this one:
![cookies](https://user-images.githubusercontent.com/34774426/45317452-a86a5080-b4ff-11e8-9c1e-459ee7acd031.PNG)

In AdGuard's stealth mode they're set to be destroyed immediately:
![stealth](https://user-images.githubusercontent.com/34774426/45317555-f2ebcd00-b4ff-11e8-9c79-5944ad2cfa25.PNG)

The thing is that i still see the little icon in the address bar showing up,sometime after small delay,sometime right a way  and considering the fact that AdGuard should intercept all the traffic before the browser the third-party cookies should be destroyed by it not blocked by the browser.
I've been observing this for a while now before deciding to open a issue here so unless i'm wrong and there is no explanation on why i thing it should be looked at.Thank you.

### Your environment
**AdGuard 6.3.1399.4073** (TDI filter IN USE)
**Slimjet 20.0.2.0 (based on Chromium 68.0.3440.75) (Official Build) (64-bit)**
**Windows 10, v.1607, build 14393.2457**

P.S. It's worth mentioning that when try reproducing the issue it's probably a good idea to have 
**Avast AV(free)** installed also as all my problems so far are somehow related to it(see #2310).

---

@ameshkov commented on [Thu Sep 13 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2328#issuecomment-420821211)

This might be caused by the fact that AG removes cookies by modifying/adding a `Set-Cookie` header with a zero expiration timeout, which Chrome might anyway consider a third-party cookie (despite zero lifetime). But we'd better check it.

Moving to CoreLibs.

**Comment by dnmTX** [comment]
@ameshkov one more thing i discovered today. If "Stealth Mode" is ON it's not possible to login to `origin.com(signin.ea.com)`.I checked every block domain individually from the filter and they don't affect this in any way. Couldn't figure it out which option from "stealth mode" is the problematic one but i guess making some filter exception rule could work,instead of disabling stealth mode in general.Just to let you know,anyway the subject here is "Stealth Mode".Thank you.

**Comment by dnmTX** [comment]
@ameshkov  DONE!
https://github.com/AdguardTeam/AdguardFilters/issues/22422

**Comment by dnmTX** [comment]
@ameshkov you might want to close this one :smile
I was cleaning my old subscriptions and saw it 👍
