### ISSUE TITLE
Add support for domain.* TLD matching

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#48]
`google.*##example.org` should match all the `google.TLD` domains.

After that, add a task to AdguardKnowledgeBase -- this should be described there.

**Comment by sxgunchenko** [comment]
core/pull-requests/1500

**Comment by sxgunchenko** [comment]
core/pull-requests/1489

**Comment by sxgunchenko** [comment]
Testing instructions:
1) add the following rule: `google.*#%#alert('alert');`
2) check that alert is displayed on both `google.com` and `google.ru`

**Comment by TPS** [comment]
_N.B.: I hate to necropost, but this seems to be the closest issue I can post this to w/o adding bunch of background info._

Are y'all _sure_ of this syntax?  It seems like `google.evildomain.whatever` would slip through, too, &/or any TLD _not_ on Google's official list @ httpS://www.google.com/supported_domains (especially w/ the recent explosion of allowable TLDs, e.g., https://data.iana.org/TLD/tlds-alpha-by-domain.txt).

It seems like having explicit TLD/subdomain matchers (similar to `$domain` @ https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#basic-modifiers) would be more secure.

**Comment by ameshkov** [comment]
@TPS Note, that TLD only means any domain from the public suffix list: https://publicsuffix.org/.

**Comment by TPS** [comment]
The PSL seems to be an honorable resource, but comments like https://github.com/publicsuffix/list/issues/1563#issuecomment-1111699549 don't inspire confidence.  Also,
- e.g., in the case of Google, when an official list is provided, it might be higher worth than the PSL.
- ICANN's might be somewhere in between
- Is the process y'all use for https://github.com/AdguardTeam/companiesdb better?

Overall, this seems to be a similar problem to https://github.com/AdguardTeam/HttpsExclusions/issues/24

**Comment by ameshkov** [comment]
PSL is not just a honorable resource, it is used by all browsers to detect domains that cannot have cookies.

Anyways, I actually seem to be wrong here and we actually use ICANN at least in the browser extension.

> e.g., in the case of Google, when an official list is provided, it might be higher worth than the PSL.

The rule syntax cannot be linked to a particular company. The current definition is that when the domain is written as `example.*`, `.*` means any ICANN-registered TLD.
