### ISSUE TITLE
Strava.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#483]
@adguard-bot commented on [Wed Sep 12 2018](https://github.com/AdguardTeam/AdguardFilters/issues/22341)

### Issue URL (Incorrect Blocking)
[https://www.Strava.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.Strava.com)
### Comment
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](http://res.cloudinary.com/adguard/image/private/s--Rl0CgTI9--/v1536758440/ibf689hybue5nacset8s.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 7.0
AdGuard version: | 2.12.219
Browser: | Strava application
AdGuard mode: | VPN
Filtering quality: | Simplified
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | EasyList Italy,<br>AdGuard Mobile Ads,<br>Liste FR,<br>AdGuard Annoyances,<br>AdGuard French,<br>AdGuard Base,<br>(Obsolete) Anti-Adblock Killer | Reek,<br>AdGuard Spyware,<br>AdGuard Social Media,<br>AdGuard Experimental

---

@BlazDT commented on [Thu Sep 13 2018](https://github.com/AdguardTeam/AdguardFilters/issues/22341#issuecomment-420870462)

Please try to disable HTTPS filtering.
Can't sign up to get the app - please check @AdamWr.

---

@AdamWr commented on [Thu Sep 13 2018](https://github.com/AdguardTeam/AdguardFilters/issues/22341#issuecomment-420973906)

It happens even with all filters disabled, so it looks like a bug.
https://play.google.com/store/apps/details?id=com.strava

**Comment by sfionov** [comment]
Can't reproduce on the latest nightly
