### ISSUE TITLE
Implement a DNS proxy module

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#484]
I'd like us to implement a DNS proxy module/library supporting the following functionality:

* DoH / DoT client
* DNSCrypt client
* Applying filtering rules to it (both adblock and hosts files syntax)

The interface of the module/library is to be discussed additionally.

Why do I want us to do it:

1. The current implementation that we use in the Android app is quite heavy and slow compared to other parts of the program;
2. There's a request from users to embed DNS filtering functionality into other AG products;

**Comment by ameshkov** [comment]
I am not setting a milestone yet.

**Comment by sfionov** [comment]
https://github.com/AdguardTeam/DnsLibs
