### ISSUE TITLE
Handle URL parts along with the URL parameters, when "strip" URL with stealth-mode

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#485]
At this moment we strip only URL parameters like `utm-medium=...` etc. We should also handle cases when extra data is not a parameter, but a part of the URL. 
Also, we should allow the user to customize the list of the parameters/url parts which will be stripped.
Related thread - https://forum.adguard.com/index.php?threads/how-does-stealth-mode-strip-tracking-paramters-work.29387/#post-171563

**Comment by ameshkov** [comment]
Requires rewrite functionality. We may consider it for trusted filters in a separate issue.

**Comment by AJolly** [comment]
So are we tracking this elsewhere, or how should I clean up amazon urls?
