### ISSUE TITLE
Check that QUIC v44 is blocked properly

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#486]
@ameshkov commented on [Sat Sep 15 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2335)

I've got a report that QUIC in Chrome 71 is not blocked properly.

Something has changed in QUIC v44, we should check what exactly.

**Comment by sfionov** [comment]
QUIC 44 uses IETF QUIC header.
Google started changing QUIC to be the same as IETF QUIC eventually.

**Comment by sfionov** [comment]
Merged, 
core/pull-requests/659
