### ISSUE TITLE
`certIsEV` check might be causing random memory corruption

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#488]
The experiment with commenting it out seems to help and reduce the number of crashes drastically. Tomorrow, we will know it for sure, but I hope the situation with crashes remains the same as of now.

If that is so, I suggest fixing this issue in two steps.

1. Do not call `certIsEV` in the case when users do not need it (i.e. when AG filters all domains including EV). This is the default behavior so it will cover 99% of users. It will not take much time to implement this change so we can roll out the patch tomorrow (and finally release the stable 2.12 on Wednesday).

2. Investigate the real cause of this issue and implement the final fix in future updates.

**Comment by sfionov** [comment]
Merged:
core/pull-requests/660 (don't check for EV if not needed)
core/pull-requests/661 (update to OpenSSL 1.1.1)
