### ISSUE TITLE
shahid.mbc.net - cosmetic rules doesn't work until cache is cleared

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#489]
https://github.com/AdguardTeam/AdguardFilters/issues/22564
### Steps to reproduce
1. Please firstly open this website - https://shahid.mbc.net/ar/
2. Then add any cosmetic rule, for example - `shahid.mbc.net##body` and refresh website.

### Expected behavior
Cosmetic rule should works and website should be "blank".

### Actual behavior
Cosmetic rule doesn't work until cache is cleared.

AdGuard 2.12.221 nightly

**Comment by karina-archazh** [comment]
Duplicated to https://github.com/AdguardTeam/CoreLibs/issues/141
