### ISSUE TITLE
brainpop.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#490]
@adguard-bot commented on [Sun Sep 16 2018](https://github.com/AdguardTeam/AdguardFilters/issues/22598)

### Issue URL (Incorrect Blocking)
[https://www.brainpop.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.brainpop.com)
### Comment
> When I push the login button, Adguard is blocking the login window from popping up. I have turned off filtering on the website; however, it still prevents the login window from showing up. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](http://res.cloudinary.com/adguard/image/private/s--9Yj03qKV--/v1537122066/alz2xuxxon7gf5aklmra.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 6.3
Browser: | Chrome
AdGuard driver: | TDI
Filters: | AdGuard Base
Other extensions used: | none

---

@adguard-bot commented on [Mon Sep 17 2018](https://github.com/AdguardTeam/AdguardFilters/issues/22598#issuecomment-421915525)

### Issue URL (Incorrect Blocking)
[https://www.brainpop.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.brainpop.com%2F)
### Comment
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](http://res.cloudinary.com/adguard/image/private/s--3K3ERfPb--/v1537169776/bf3ngivrw93t4yx8zhtz.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Mac
AdGuard version: | 1.5.8
Browser: | Chrome
Filters: | AdGuard Base,<br>AdGuard Spyware,<br>AdGuard Social Media,<br>AdGuard Safari,<br>AdGuard Annoyances

---

@BlazDT commented on [Tue Sep 18 2018](https://github.com/AdguardTeam/AdguardFilters/issues/22598#issuecomment-422355385)

Getting the same error on my Windows Chrome, but even without AdGuard. In Edge login is displayed fine, so looks like a site issue to me.

@AdamWr please double-check.

---

@AdamWr commented on [Tue Sep 18 2018](https://github.com/AdguardTeam/AdguardFilters/issues/22598#issuecomment-422370799)

I think it's a bug, it happens even with all filters disabled, but works if I disable AdGuard and clear cache.
Added as a temporary solution:
`@@||brainpop.com/*.php$extension,jsinject,elemhide`

**Comment by karina-archazh** [comment]
We will add this site to exceptions in the new version of popup blocker.

**Comment by karina-archazh** [comment]
Issue moved to [AdguardTeam/AdguardForWindows #2344](https://github.com/AdguardTeam/AdguardForWindows/issues/2344) via [**ZenHub**](https://www.zenhub.com/)

**Comment by karina-archazh** [comment]
Issue moved to [AdguardTeam/AdguardForWindows #2345](https://github.com/AdguardTeam/AdguardForWindows/issues/2345) via [**ZenHub**](https://www.zenhub.com/)
