### ISSUE TITLE
Rule with "$script" modifier blocks also "ajax/xmlhttprequest"

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#493]
### Steps to reproduce
1. Add this rule to user filter `|https://$script,third-party` or `.*.$script,third-party` or `.*.$script`
2. Open this website - https://shahid.mbc.net/ar/ or https://accounts.google.com/

### Expected behavior
Ajax/xmlhttprequest shouldn't be blocked.

### Actual behavior
Ajax/xmlhttprequest are blocked.

<details><summary>Screenshot:</summary>

![screenshot_2018-09-19-15-51-22](https://user-images.githubusercontent.com/29142494/45758239-735bad80-bc25-11e8-98b7-80d1224b7b5f.png)
![screenshot_2018-09-19-16-46-11](https://user-images.githubusercontent.com/29142494/45761037-be78bf00-bc2b-11e8-96d4-edec91aefc87.png)

</details>

### Your environment
* Adguard version: 2.12.224

**Comment by ameshkov** [comment]
The problem here is that this is a SCRIPT loaded via an AJAX request so it matches both xmlhttprequest and script

**Comment by ameshkov** [comment]
On the other hand, we should've indicated this in the filtering log

**Comment by ameshkov** [comment]
Wait, I am wrong, we should not detect it as script.

**Comment by szolin** [comment]
/core/pull-requests/868
