### ISSUE TITLE
CoreLibs messes with some streaming apps

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#499]
@zebrum commented on [Thu Sep 20 2018](https://github.com/AdguardTeam/AdguardForAndroid/issues/2126)

@adguard-bot commented on [Fri Sep 14 2018](https://github.com/AdguardTeam/AdguardFilters/issues/22452)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=deezer.android.app](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Ddeezer.android.app)
### Comment
Username: @Jzamoras
> Adguard enabled breaks deezer streaming 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](http://res.cloudinary.com/adguard/image/private/s--rSGeAxqO--/v1536937713/wl14ugdytfrauxxqnc81.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 8.0.0
AdGuard version: | 2.12.219
AdGuard mode: | VPN
Filtering quality: | Simplified
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | AdGuard Simplified domain names

**Comment by ameshkov** [comment]
Examples are: Spotify and Deezer

**Comment by sxgunchenko** [comment]
core/pull-requests/674
