### ISSUE TITLE
$extension modifier is not a part of $document

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#501]
According to the documentation, it must be a part of `$document`:
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#extension-modifier

* `@@||example.org^$document` -- disables filtering completely **including extensions**.
* `@@||example.org^$document,~extension` -- disables filtering but keeps extensions working.

**Comment by szolin** [comment]
It seems that this is already implemented.
