### ISSUE TITLE
CoreLibs cannot properly handle an RST frame following by a new stream 

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#502]
A common issue for most of the video players working with mp4 files.

When you try to rewind the video, a new request with a `range` header is sent, and after some time the browser has to restart the request:

```
t=28243 [st=    9]     +HTTP_TRANSACTION_READ_HEADERS  [dt=30003]
t=58246 [st=30012]        HTTP2_STREAM_ERROR
                          --> description = "Abandoned."
                          --> net_error = "ERR_CONNECTION_CLOSED"
                          --> stream_id = 19
t=58246 [st=30012]        HTTP_TRANSACTION_RESTART_AFTER_ERROR
                          --> net_error = -100 (ERR_CONNECTION_CLOSED)
```

Test website:
https://www.quirksmode.org/html5/tests/video.html

The pattern is the same:

1. Client sends an RST_STREAM
2. It is passed to the server
3. A new stream is initialized by the client and bypassed to the server
4. No response from the server after that

**Comment by ameshkov** [comment]
Temporary solution in `core/pull-requests/695`

Need a better one.

**Comment by sfionov** [comment]
FIxed
core/pull-requests/695 
core/pull-requests/703
