### ISSUE TITLE
gall.dcinside.com broken pictures

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/CoreLibs#509]
https://gall.dcinside.com/mgallery/board/view/?id=su&no=451963&exception_mode=recommend&page=1

When you visit the site the yellow picture with "destiny child" is not loading. Tested on AdGuard for Windows latest nightly and final Extension.

`https://imgur.com/2ef9j30`

With document exclusion it is not working in Extension while it works on Windows.
For Windows I have to add this rule to make the picture appear:

`@@||gall.dcinside.com^$urlblock,important,content,jsinject,elemhide`

Which is nearly the same as document exclusion. Please check.

**Comment by NO-KR** [comment]
@@||gall.dcinside.com^$urlblock,important,content,jsinject,elemhide

This rule invalidates ad blocking. The image is not loaded.
As far as I know, that site does not fully support https.
This is not a problem with AdGuard. http should be used.

**Comment by ameshkov** [comment]
Just re-checked on my side, it seems that the website does not work well with https indeed, half of the images aren't loaded regardless of whether AG is enabled or not.

**Comment by sxgunchenko** [comment]
just figured out that in stealth mode with "Hide your Referrer from third-parties" option enabled and nonempty custom referer server responses with `403 Access Denied` for the picture requests

**Comment by sxgunchenko** [comment]
> just checked with corelibs build and figured out that in stealth mode with "Hide your Referrer from third-parties" option enabled and nonempty custom referer server responses with `403 Access Denied` for the picture requests

in other cases it looks ok, but i don't see the yellow picture (`https://imgur.com/2ef9j30`) whether AG is enabled or nor
