### ISSUE TITLE
Add a helper method to check the rule type

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#51]
It's quite often when we need to check if rule falls under one of three categories: whitelist, blocking, content modifying.

Let's add two simple helpers to check these cases:
```
NativeFilterUtils.isBlockingRule(NativeFilterRule rule) {
    return rule != null && !rule.isWhitelist && !isContentModifyingRule(rule);
}

NativeFilterUtils.isContentModifyingRule(NativeFilterRule rule) {
    return rule != null && !rule.isWhitelist && !rule.isReplace && !rule.isProtobuf;
}
```

I'd better have this on the library side as criteria might change in future and it'd be better if library controlled it.

**Comment by hmage** [comment]
Sure.

**Comment by ameshkov** [comment]
Or maybe instead of utils let's add these methods to `NativeFilterRule` class

**Comment by ameshkov** [comment]
Done
