### ISSUE TITLE
on-mag.fr

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#524]
To reproduce -- disable this rule: `@@||on-mag.fr^$extension`

@AdamWr commented on [Thu Oct 04 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2349)

@adguard-bot commented on [Mon Oct 01 2018](https://github.com/AdguardTeam/AdguardFilters/issues/23259)

### Issue URL (Incorrect Blocking)
[https://www.on-mag.fr/index.php/video-hd/news/home-cinema/18481-le-cedia-a-recompense-les-plus-belles-installations-home-cinema-et-smart-home-de-l-annee-2018](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.on-mag.fr%2Findex.php%2Fvideo-hd%2Fnews%2Fhome-cinema%2F18481-le-cedia-a-recompense-les-plus-belles-installations-home-cinema-et-smart-home-de-l-annee-2018)
### Comment
> Hello,
> The problem on this page is : in the photo gallery of this page, if I click on a photo the screen become black but with no photo displayed.
> --
> L'information ci-dessous est générée automatiquement, prière de ne pas la supprimer.
> 
> Custom userscripts:
> https://cdn.adguard.com/public/Userscripts/AdguardAssistant/4.0/assistant.user.js
> https://itube.aimersoft.com/userscript/itube-helper.meta.js
> https://cdn.adguard.com/public/Userscripts/AdguardPopupBlocker/2.2/popupblocker.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/dn18sHQ.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 6.3.1399.4073
Browser: | Chrome
AdGuard driver: | WFP
Filters: | EasyList China,<br>EasyList Czech and Slovak,<br>EasyList Italy,<br>(Obsolete) Wiltteri,<br>AdGuard Annoyances,<br>AdGuard French,<br>AdGuard Base,<br>Official Polish filters for AdBlock, uBlock Origin & AdGuard,<br>Juvander's Adblock List for Finland,<br>(Obsolete) Official Polish filters for AdBlock, uBlock Origin & AdGuard - supplement for AdGuard,<br>AdGuard German,<br>AdGuard Japanese,<br>AdGuard Dutch,<br>AdGuard Spanish/Portuguese

---

@karina-archazh commented on [Mon Oct 08 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2349#issuecomment-427905934)

![image](https://user-images.githubusercontent.com/41899455/46622555-bed1ef00-cb33-11e8-8e91-f0d8becd7107.png)
This issue repeated and with only Frech/Russian/Base filters on.

**Comment by Pierre7855** [comment]
Hello,
do I need to wait adguard for windows V7 in order to have this issue solved ?

**Comment by ameshkov** [comment]
Works okay now
