### ISSUE TITLE
Cosmetic rules aren't applied when there's an upstream proxy

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#528]
## Steps to reproduce

1. Install switchyomega and configure an upstream proxy
2. Open any website and examine the browser console
3. You'll see `net::ERR_ABORTED 400 (Bad Request)` in response to the content script requests

**Comment by sxgunchenko** [comment]
related to #223

**Comment by sxgunchenko** [comment]
core/pull-requests/757
