### ISSUE TITLE
EXC_BAD_ACCESS in urlfilter_applyreplace

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#537]
https://sentry.adguard.com/adg/adguard-mac/issues/11865/?query=is:unresolved
https://sentry.adguard.com/adg/adguard-mac/issues/11866/?query=is:unresolved
https://sentry.adguard.com/adg/adguard-mac/issues/11867/?query=is:unresolved
https://sentry.adguard.com/adg/adguard-mac/issues/11868/?query=is:unresolved

**Comment by szolin** [comment]
/core/pull-requests/716
