### ISSUE TITLE
elon.se

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#538]
@adguard-bot commented on [Thu Oct 11 2018](https://github.com/AdguardTeam/AdguardFilters/issues/23738)

### Issue URL (Incorrect Blocking)
[https://www.elon.se/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.elon.se%2F)
### Comment
Username: @Xophile
> Works perfectly fine when I disable AG. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/zg9et1t.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 8.1.0
AdGuard version: | 2.12.234η
Browser: | Firefox
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | disabled
DNS requests blocking: | disabled
Filters: | AdGuard Mobile Ads,<br>AdGuard Annoyances,<br>AdGuard Base,<br>Fanboy's Swedish,<br>AdGuard Spyware,<br>AdGuard Social Media

**Comment by TheHasagi** [comment]
@Xophile

Can you try to clear the cache in FF and try again?

Seems to me it can be reproduced but without clearing the cache.

**Comment by Xophile** [comment]
Hi!

Clearing the cache does not help. The issue is still there.

**Comment by sfionov** [comment]
Can't reproduce. Can you please say what is inside "Show details"?

**Comment by ameshkov** [comment]
I cannot reproduce it on the latest AG for Mac alpha build as well. I guess some of the other changes helped with this bug :)
