### ISSUE TITLE
Код  в шапке страницы в новой версии приложения!

### ISSUE THREAD

**Issue by Big-U-Boss** [AdguardTeam/CoreLibs#539]
https://github.com/AdguardTeam/AdguardFilters/issues/23648#issue-368287720
https://github.com/AdguardTeam/AdguardFilters/issues/22313#issuecomment-426697697

**Comment by sfionov** [comment]
Проблема исправлена в найтли 2.12.239 и попадёт в ближайший хотфикс-релиз 2.12.

**Comment by sfionov** [comment]
Duplicate of #443
