### ISSUE TITLE
Uploading large files does not work

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#542]
## Steps to reproduce

1. Run the latest AG for Mac dev build
2. Go to https://ezgif.com/gif-to-mp4
3. Upload this gif: https://cdn.adguard.com/public/Adguard/Blog/AGHome/dashboard.gif?1
4. Eventually, you'll end up with the `ERR_CONNECTION_CLOSED` error

**Comment by lancelot-moon** [comment]
Yes, another Taiwanese user ever wrote about the issue in his article on PTT.
"When uploading big files to Google Drive by chrome on macOS, internet bandwidth is occupied.
So he disabled chrome's filtering."

I think he said he couldn't upload big files with AdGuard enabled.

**Comment by sfionov** [comment]
core/pull-requests/758
