### ISSUE TITLE
Integration mode is not fully functional

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#543]
https://kb.adguard.com/en/browser-extensions/integration-mode

Actions originated from the browser extensions don't work in AG.

**Comment by ameshkov** [comment]
It's better now.

Disabling protection works as it should.
Enabling it back does not work -- it seems the rule stays in the urlfilter.

**Comment by ameshkov** [comment]
Wrong rule is added to the user filter (@Stillness-2): `@@//meduza.io^$document`
Where's `~extension` ??

**Comment by ameshkov** [comment]
@szolin @Stillness-2 

Let's change the callbacks a little. Let it be CoreLibs who is responsible for the rule text, and let's pass the exact rule text to the `change-state` callback.

**Comment by sfionov** [comment]
core/pull-requests/768

**Comment by ameshkov** [comment]
Let's close it when the issue is resolved in the Mac app as well.

Currently, it is not.

**Comment by ameshkov** [comment]
Again, it does not work:
https://uploads.adguard.com/up04_jj8pj_Notification_Centre.png

### Steps to reproduce

1. DIsable protection via extension
2. Enable it back

Expected: it's enabled back
Actually: no it's not

**Comment by szolin** [comment]
/core/pull-requests/795
