### ISSUE TITLE
Safebrowsing requests are stuck due to a DNS error

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#544]
This issue is randomly reproduced when I spend some time with Wi-Fi off, and then get the connection back.

`/safebrowsing.js` requests are stuck for 15+ seconds in this case

Also, I observe a lot of similar records in the log:
```
2018/10/17 01:21:48:711  AGUrlRequest	[id=3122] Error connecting to sb.adtidy.org:443. DNS error: 4(non-recoverable failure in name resolution)
2018/10/17 01:21:48:712  AGFilterSafebrowsing	failed to download safebrowsing list match information from safebrowsing api -- some internal error happened (status code 1)
```

**Comment by sfionov** [comment]
We don't have a function to reread DNS servers settings on network change in AGDnsSettings/ProxyUtils for Mac and Windows platform.

**Comment by sfionov** [comment]
Also, on Mac we may implement triggering this in objc adapter - add FSEvents handler on any change of /etc/resolv.conf.

**Comment by sfionov** [comment]
core/pull-requests/764
