### ISSUE TITLE
japan.cnet.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#554]
@adguard-bot commented on [Fri Oct 19 2018](https://github.com/AdguardTeam/AdguardFilters/issues/24065)

### Issue URL (Ads)
[https://japan.cnet.com/article/35127262/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fjapan.cnet.com%2Farticle%2F35127262%2F)
### Comment
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/JYiE8Mk.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 5.1.1
AdGuard version: | 2.12.248η
Browser: | Firefox Rocket 3.3.0(7202) WebView version: 59.0.3 / FOSS Browser v 6.0
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | AdGuard Mobile Ads,<br>AdGuard Annoyances,<br>AdGuard Base,<br>AdGuard Spyware,<br>AdGuard Social Media,<br>AdGuard Japanese

**Comment by AdamWr** [comment]
<details><summary>Screenshot</summary>

![japan cnet](https://user-images.githubusercontent.com/29142494/47216830-88ec0080-d3a6-11e8-8fff-7531232062eb.png)

</details>

**Comment by ameshkov** [comment]
@sfionov might be the same issue as on MS websites: #597

**Comment by sfionov** [comment]
core/pull-requests/825
