### ISSUE TITLE
imagesatintl.com is broken

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#556]
### Steps to reproduce
1. Open this website - https://www.imagesatintl.com/

### Actual behavior

Website doesn't work

<details><summary>Screenshot:</summary>

![imagesatintl](https://user-images.githubusercontent.com/29142494/47230511-b0ed5b00-d3ca-11e8-8c14-ed11df3f98fe.png)

</details>

### Your environment
* Adguard version: 2.12.248 nightly

**Comment by ameshkov** [comment]
Same issue on Mac btw

**Comment by ameshkov** [comment]
@sfionov the website seems to use the old SPDY protocol, wouldn't it be better to enforce HTTP/1.1 in this case?

**Comment by sxgunchenko** [comment]
core/pull-requests/762
