### ISSUE TITLE
AdGuard does not filter Chrome Canary

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#558]
See the same task in the Mac repo. The simple solution was committed by @Stillness-2 but we'd better come up with something more foolproof.

**Comment by szolin** [comment]
/core/pull-requests/791

**Comment by Stillness-2** [comment]
also need implement in main app

**Comment by sfionov** [comment]
@Stillness-2 Can I close this?

**Comment by ameshkov** [comment]
You can:)
