### ISSUE TITLE
Add the `sendAnonymousStatistics` parameter to the SafeBrowsing configuration

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#559]

**Comment by adbuker** [comment]
Also, let's distinguish the safebrowsing-related parameters within the `AGProxyServerConfigC` into the separate `SafeBrowsingConfiguration` (e.g. as `ParentalControlConfiguration` is implemented)

**Comment by sxgunchenko** [comment]
core/pull-requests/987

**Comment by sfionov** [comment]
Testing instructions:
- Enable setting in UI
- Go to malicious site and see that this parameter is present in page source
