### ISSUE TITLE
$important option behaviour

### ISSUE THREAD

**Issue by Stillness-2** [AdguardTeam/CoreLibs#56]
At this moment blocking rule with `important` option has higher priority then whitelist rule. It is correct behaviour. 
But in some cases this causes to trouble.

For example, user wants to turn off filtering on the site `lenta.ru`. 
Adguard Assistant produces rule for that: `@@||lenta.ru$document`, 
but some filter has rule: `||lenta.ru^$important,domain=lenta.ru,replace=/this\[\"Anti-AdBlock\"\]/`.
Note that this is `contentModified` rule...

As result, user does not get what he wants.

**Comment by sfionov** [comment]
This is already fixed
