### ISSUE TITLE
Use uniform approach for the passing IP address

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#561]
At this moment we explore 3 different approaches:
1. `byte[16] address` and `uint addressType`
2. `*byte address` and `byte addressLength`
3. `struct AGAddr = {byte[16] address; uint addressType}` structure

Let's start use `struct AGAddr = {byte[16] address; byte addressLength}` in all places

**Comment by sxgunchenko** [comment]
core/pull-requests/846
