### ISSUE TITLE
Avoid .Net's (or another adapter's) memory allocating while using the userscript's download callback

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#562]
The problem is in the fact, that if CoreLibs invokes adapter's download callback, the memory for the content will be allocated on the adapter's side. In this case, on the one hand, CoreLibs cannot free this memory, and on the other hand adapter's doesn't know when memory should be freed. 
The solution is using the following approach:
1. CoreLibs invokes the download callback
2. Adapter get the response stream and pass the response's content-length  (if it exists) to the CoreLibs
3. Within the callback, the adapter sends fixed-length content's chunks to the CoreLibs
4. Once the CoreLibs gets another chunk, it base64s it and append to the existing part 
5. Once the entire content will be passed, callback completed and the CoreLibs can free fixed-size memory (equal to the chunk size), allocated beforehand

**Comment by szolin** [comment]
/core/pull-requests/813

**Comment by szolin** [comment]
Done, but we need to use partial base64 encoder.  After that we can close the issue.
