### ISSUE TITLE
Safari doesn't work when Stealth mode is enabled

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/CoreLibs#563]
1. Settings - Privacy - Advanced tracking protection is checked
2. Open Safari and go to `google.com` or `bing.com`

Actual result:
https://uploads.adguard.com/Bing_2018-10-26_13-18-01.png

**Comment by ameshkov** [comment]
Most likely this is caused by the invalid stealth script configuration as `navigator.userAgent` returns "null" even though "hide user-agent" is unchecked in the settings.

**Comment by sfionov** [comment]
@zebrum Can you please check with 2.0.0.481 nightly?

**Comment by sfionov** [comment]
Thanks!

**Comment by sfionov** [comment]
core/pull-requests/797
