### ISSUE TITLE
Crash in the onBeforeRequest_cb handler

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#564]
https://sentry.adguard.com/adg/adguard-mac/issues/12589/?query=is:unresolved

**Comment by sfionov** [comment]
Seems that `nil` is not allowed as value in collections in Obj-C
https://developer.apple.com/documentation/foundation/nsnull?language=objc

**Comment by sfionov** [comment]
Issue moved to [AdguardTeam/AdguardForMac #352](https://github.com/AdguardTeam/AdguardForMac/issues/352) via [**ZenHub**](https://www.zenhub.com/)
