### ISSUE TITLE
Plain HTTP responses with `Connection: close` are truncated if server closes connection first

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#565]
@adguard-bot commented on [Thu Oct 25 2018](https://github.com/AdguardTeam/AdguardFilters/issues/24391)

### Issue URL (Incorrect Blocking)
[http://yamaiga.com/hen/index.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fyamaiga.com%2Fhen%2Findex.html)
### Comment
> If you turn on adguard, text and URL etc will disappear.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/iq2mnsv.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/atpFTF2.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 8.0.0
AdGuard version: | 2.12.247
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | disabled
Filters: | AdGuard Mobile Ads,<br>AdGuard Base,<br>AdGuard Japanese

**Comment by sfionov** [comment]
core/pull-requests/783
