### ISSUE TITLE
Connections are randomly left unfiltered when filtering rules are reloaded

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#566]
## Steps to reproduce

1. Install AdGuard for Mac and AG browser extension
2. Open Pereferences -> Filters
3. Add some random filtering rule there (whatever, just to make it reload rules)
4. Reload any website a few times

You'll observe that the website becomes unfiltered and integration mode stops working (randomly).

**Comment by szolin** [comment]
/core/pull-requests/789
