### ISSUE TITLE
Strip tracking parameters from location.hash

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/CoreLibs#567]
When an external site like this puts a link to bild.de, bild.de adds tracking parameter according to referrer to it:
`http://www.pi-news.net/2018/10/zerstueckelungs-mord-an-khashoggi-war-auch-ein-inner-islamischer-konflikt/
`

Tracking parameter:
`###wt_ref=http%3A%2F%2Fwww.pi-news.net%2F2018%2F10%2Fzerstueckelungs-mord-an-khashoggi-war-auch-ein-inner-islamischer-konflikt%2F&wt_t=1540811893317`

Full bild.de url with tracking parameter:
`https://m.bild.de/politik/ausland/politik-ausland/khashoggi-diese-maenner-sollen-ihn-lebendig-zerstueckelt-haben-57914626.bildMobile.html###wt_ref=http%3A%2F%2Fwww.pi-news.net%2F2018%2F10%2Fzerstueckelungs-mord-an-khashoggi-war-auch-ein-inner-islamischer-konflikt%2F&wt_t=1540811893317`

**Comment by ameshkov** [comment]
Added to v2.0 milestone for now, but probably we'll need that earlier.
