### ISSUE TITLE
Fix some issues with the ANBrowserApiRequestInfo class

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#569]
1. The class is not documented at all, it's hard to understand what's going on there
2. The second issue is with the `ruleText` field. It is populated for `change-filtering-state` requests only, but it makes sense to set it for other requests as well.
3. The same is true for Win/Android API

**Comment by ameshkov** [comment]
Adding @adbuker here as the Win API should be changed accordingly

**Comment by szolin** [comment]
/core/pull-requests/796
