### ISSUE TITLE
'com.countercultured.irc4android' misbehaves after the last update

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#572]
From the Telegram chat:

> Hey. After the latest update IRC for Android disconnects every other second.

> All settings remain the same as before the AdGuard update.

> Disabling the monitor for this particular app does the trick, but this is not the proper way to solf it. Unsecured connection is used.

**Comment by sfionov** [comment]
Paid software:
https://play.google.com/store/apps/details?id=com.countercultured.irc4android&hl=ru

I'm IRC user, I'll try to reproduce it after vacation.

**Comment by ameshkov** [comment]
Cannot reproduce anymore
