### ISSUE TITLE
Content script requests authorization

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#573]
content-script.js, safebrowsing.js, userscripts.js, and the browser API requests must be authorized in order for them to send `Access-Control-Allow-Origin: *` in response.

Here's what needs to be done:
1. Use the nonce value we generate as the auth token for requests for static content;
2. If you received a request with an invalid token value, set the flag for clearing browser cache;
3. `/generate_204` request also requires auth (just like other requests from the extensions) 
4. Decrease the cache's max-age from 86400 to 3600;
5. Browser API requests need to be authorized already;
6. Make sure that all the other requests get the following response: `400 Bad Request `, no access-control-allow-origin header, connection: close
7. Also, you're adding this header literally to every custom response (for example, stealth mode redirect response when tracking parameters are stripped). This is simply wrong.

Also, change the safebrowsing.js path (`/adguard/injections/`) -- do we really need this prefix? If we do, replace it with `/injections/`.

**Comment by sxgunchenko** [comment]
core/pull-requests/808
