### ISSUE TITLE
Enabling "Hide User-Agent" makes Google serve mobile version

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#576]
Why so? By default, we should just strip extra properties from the user agent and on my configuration, it means basically that user agent stays the same.

Expected: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36`
Actual: `Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36`

**Comment by sfionov** [comment]
Also, tests are needed for this case

**Comment by sfionov** [comment]
"null" is passed to stealth script quoted, but should be passed unquoted

**Comment by sxgunchenko** [comment]
> "null" is passed to stealth script quoted, but should be passed unquoted

may it be related to https://github.com/AdguardTeam/CoreLibs/issues/563#issuecomment-434609567 ?

**Comment by sxgunchenko** [comment]
core/pull-requests/794
