### ISSUE TITLE
Images, captured to HAR file, cannot be opened in HAR viewer(Fiddler)

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#578]
HAR example:
https://drive.google.com/file/d/10ZqO-gMdZymRDJEWGJAYf45LkJDgPQku/view?usp=drivesdk

**Comment by Alex-302** [comment]
@szolin 
[adguard.zip](https://github.com/AdguardTeam/CoreLibs/files/2585088/adguard.zip)
Also in cannot be opened in https://toolbox.googleapps.com/apps/har_analyzer/?lang=ru

Recorded by AdGuard
<details>

![image](https://user-images.githubusercontent.com/8361299/48550296-04c06680-e8db-11e8-9759-fdb00df12c95.png)

</details>

Requested by Fiddler

<details>

![image](https://user-images.githubusercontent.com/8361299/48550323-1570dc80-e8db-11e8-9b89-0ffaf4778dd6.png)

</details>

**Comment by szolin** [comment]
/core/pull-requests/861
