### ISSUE TITLE
Crash in ANConnectionInfo initWithConnInfo

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#588]
https://sentry.adguard.com/adg/adguard-mac/issues/11441/?query=is:unresolved

**Comment by sfionov** [comment]
Related issues:
https://sentry.adguard.com/adg/adguard-mac/issues/12845/?query=is:unresolved
https://sentry.adguard.com/adg/adguard-mac/issues/12847/?query=is:unresolved
@szolin Seems that related to process info cache.

**Comment by szolin** [comment]
/core/pull-requests/812
