### ISSUE TITLE
Add helper modifiers support

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#59]
* `first-party` -- This is the very same as `~third-party`
* `xhr` -- this is the very same as `xmlhttprequest`
* `popunder` -- the same as `popup` (needs investigation)

* [1p](https://github.com/gorhill/ublock/wiki/Static-filter-syntax#1p)
* [3p](https://github.com/gorhill/ublock/wiki/Static-filter-syntax#3p)
* [all](https://github.com/gorhill/ublock/wiki/Static-filter-syntax#all)
* [css](https://github.com/gorhill/ublock/wiki/Static-filter-syntax#css)
* [frame](https://github.com/gorhill/ublock/wiki/Static-filter-syntax#frame)

**Comment by hmage** [comment]
Already done.

`filtering/urlfilter/src/urlfilter.cc:956`

**Comment by ameshkov** [comment]
Hmm, what about tests? Do we need it to add tests to the android library code?

**Comment by hmage** [comment]
Yeah, having tests is nice idea, they should be relatively simple -- just see if `first-party` is accepted and if rule matches the way it should.

**Comment by ameshkov** [comment]
Re-assigned to myself then

**Comment by sxgunchenko** [comment]
core/pull-requests/1437
