### ISSUE TITLE
Unable to reach web interface of Synology router

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/CoreLibs#598]
It's unable to access https://91.205.8.2:8001/ with enabled AdGuard via Safari browser.

## Steps to reproduce:

1. Start AdGuard (Release or Nightly)
2. Open Safari and try to open https://91.205.8.2:8001/
3. You'll see "connection is not private" warning
4. Click "show details" and click "visit the website"

## Expected behavior:

You should see the log-in page.

## Actual behavior:

You get the "connection is not private" warning again.

Customer ID: 2025544

**Comment by sfionov** [comment]
@TheHasagi Can you please check if it happens with 2.0.0.484 nightly?

**Comment by ameshkov** [comment]
It does
