### ISSUE TITLE
Hide referer from third-parties option working incorrectly

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/CoreLibs#599]
Settings in AG: https://uploads.adguard.com/AdGuard_Preferences_-_Privacy_2018-11-08_12-05-46.png

STR: go to google.com, search for ‘xhause.com/headers’

Actual result: `Hide referer from third-parties` is off, but referer has the attribute of that option.

https://uploads.adguard.com/xhaus.comheaders_-_Poisk_v_Google_2018-11-08_12-07-30.png

Expected behaviour: referer is the same as host.

**Comment by sxgunchenko** [comment]
core/pull-requests/829
