### ISSUE TITLE
Implement filtering library

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#6]
https://trello.com/c/xvFo8sPM/9-filtering-engine-library

Tasks as of now:
- [x] Basic filtering
  - [x] $match-case
  - [x] $genericblock
  - [x] $urlblock
  - [x] $network
  - [x] $app
  - [x] $websocket
  - [x] $important
- [x] Fix testcases failing in java UrlFilter code:
  - [x] testUrlFilterAddRemoveRule(com.adguard.filter.rules.TestUrlFilter)
  - [x] testUrlFilter(com.adguard.filter.rules.TestUrlFilter)
  - [x] testUrlBlockingFilterNotMatchCase(com.adguard.filter.rules.TestUrlFilter)
  - [x] testComplexNotMatchCaseRule(com.adguard.filter.rules.TestUrlFilter)
- [x] Try to reduce gperf size for TLD list (now it's 2mb)
- [x] Return what rule has matched.
- [x] $first-party as alias to $~third-party
- [x] findBasicRule (consider content modifying rules logic)
- [x] Implement NativeUrlFilter, NativeBasicFilterRule java interfaces
- [x] Memory for hashtable keys must be stored separately from `rule_entry`.
- [x] Use our own logger library.
- [x] findConnectionRule
- [x] Helper methods 
  - [x] detectContentType
  - [x] isThirdParty
  - [x] getHost
- [x] Rule parsing — handle multiple '$' properly
- [x] Add $protobuf modifier support 
- [x] applyReplaceRule(String ruleText, String content)
- [x] Unit tests — rule vs expected options.
- [x] URLFILTER_CONTENTTYPE_NONE -> URLFILTER_CONTENTTYPE_ANY
- [x] Remove isFiltered method (not used in the interface)

**Comment by ameshkov** [comment]
@hmage let's move the checklist here.

**Comment by ameshkov** [comment]
It's important to pay attention on $genericblock, $urlblock modifiers.
Please read the "RequestFilter" code to understand better how it is supposed to work.

**Comment by Bluscream** [comment]
So the /en/filterrules.html page moved to the kb. Have to read that soon :)

**Comment by hmage** [comment]
- [ ] Basic filtering
  - [ ] $match-case
  - [ ] $genericblock
  - [ ] $urlblock
  - [ ] $network
  - [x] $app
  - [ ] $websocket
  - [ ] $important
- [ ] Domain handling — UTF8 to punycode.
- [ ] $stealth modifier?
- [ ] $first-party as alias to $~third-party
- [ ] Fix testcases failing in java UrlFilter code:
  - [ ] testUrlFilterAddRemoveRule(com.adguard.filter.rules.TestUrlFilter)
  - [ ] testUrlFilter(com.adguard.filter.rules.TestUrlFilter)
  - [ ] testUrlBlockingFilterNotMatchCase(com.adguard.filter.rules.TestUrlFilter)
  - [ ] testComplexNotMatchCaseRule(com.adguard.filter.rules.TestUrlFilter)

**Comment by ameshkov** [comment]
We should discuss the final interface once you're back on 10th of April.

**Comment by ameshkov** [comment]
Moved everything to separate issues, time to close this issue.
