### ISSUE TITLE
Crash in the onNewConnection_cb

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#603]
See the details here:
https://sentry.adguard.com/adg/adguard-mac/issues/11441/?query=is:unresolved

**Comment by szolin** [comment]
/core/pull-requests/837

**Comment by szolin** [comment]
/core/pull-requests/839

**Comment by ameshkov** [comment]
Still happens:
https://sentry.adguard.com/adg/adguard-mac/issues/11441/events/493405/

**Comment by szolin** [comment]
/core/pull-requests/866
