### ISSUE TITLE
MikroTik app is broken [AdGuard 3.0]

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#604]
Cannot log in.
https://play.google.com/store/apps/details?id=com.mikrotik.android.tikapp
[adguard.log](https://github.com/AdguardTeam/CoreLibs/files/2566984/adguard.log)
It works with 2.12

AdGuard 3.0.56n

**Comment by sfionov** [comment]
Not reproducable on latest AG
