### ISSUE TITLE
Crash in AGProxyServer::stop()

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#610]
@zzebrum commented on [Mon Nov 12 2018](https://github.com/AdguardTeam/AdguardForAndroid/issues/2290)

2 different patterns:

- turn on protection and turn it off --> crash

- turn on protection, open any webpage in a browser, open AG and turn off protection --> crash

**Comment by sfionov** [comment]
https://sentry.adguard.com/adg/adguard-android-rs/issues/13177/

**Comment by sxgunchenko** [comment]
core/pull-requests/842
