### ISSUE TITLE
Wrong behavior of content filtering rule

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#611]
speedtest.net is broken by
`$$script[wildcard="*!function(*"mzs"*"zmctrack"*"][max-length="9000"]`
this rule works wrong because of `"`
this rule works as expected:
`$$script[wildcard="*!function(*mzs*zmctrack*"][max-length="9000"]`
Both these rules works fine on http://blog.i.ua/

The first rule removes wrong script:
<details>

![image](https://user-images.githubusercontent.com/8361299/48404575-2e418c80-e739-11e8-9f55-aa3dbabe38e9.png)

</details>

<details>

![image](https://user-images.githubusercontent.com/8361299/48404474-f2a6c280-e738-11e8-872d-9fe89ff4bf9b.png)

</details>

AdGuard 6.4 and AdGuard for MAC with CoreLibs.

**Comment by sfionov** [comment]
We may reject this rule as it contains unquoted text. Content rules without quotes are not accepted by CoreLibs now.

**Comment by ameshkov** [comment]
Double-quotes must be escaped

**Comment by ameshkov** [comment]
Here it is: `""` === `"`

**Comment by ameshkov** [comment]
So your rule must have looked lie this:
`$$script[wildcard="*!function(*""mzs""*""zmctrack""*""][max-length="9000"]`

**Comment by Alex-302** [comment]
Got it.

**Comment by sfionov** [comment]
@szolin Can you please add more protection to htmlfilter rule parsing for non-pair quotes in the middle of parameter?

**Comment by szolin** [comment]
/core/pull-requests/857
