### ISSUE TITLE
[Feature Request] Self-Destructing First-Party Cookies Exceptions

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#613]
@tomiams commented on [Mon Nov 12 2018](https://github.com/AdguardTeam/AdguardForMac/issues/370)

Regarding Self-Destructing First-Party Cookies, there should be a whitelist with its own Time to Live.

Example use cases:
I want my Amazon cookies to be remembered so I don't get signed out. (Whitelist)
I don't want every news website I visit to set cookies.

---

@ameshkov commented on [Tue Nov 13 2018](https://github.com/AdguardTeam/AdguardForMac/issues/370#issuecomment-438271868)

Nice feature request btw.

**Comment by tomiams** [comment]
Can we expect this feature to show up in the nightly sometime soon?

**Comment by ameshkov** [comment]
@tomiams the current solution would be to use `$stealth` exception like this:
`@@||example.org^$stealth`

**Comment by ameshkov** [comment]
It's not final though

**Comment by tomiams** [comment]
>@@||example.org^$stealth

This is a suitable temporary solution, thank you. But I'm assuming all the features of the "Stealth Mode" tab would be disabled for the domain mentioned in that rule?

**Comment by ameshkov** [comment]
> But I'm assuming all the features of the "Stealth Mode" tab would be disabled for the domain mentioned in that rule?

Yeah, that's right

**Comment by tomiams** [comment]
Any updates on this feature?

**Comment by ameshkov** [comment]
@tomiams no news yet, we were quite busy solving Windows-specific issues.

Let me assign this to a milestone so that we don't miss this feature request.

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/CoreLibs/issues/1224
