### ISSUE TITLE
Upload interrupted in Safari but keeps going in Adguard

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#615]
@choco commented on [Tue Nov 13 2018](https://github.com/AdguardTeam/AdguardForMac/issues/374)

This is a really strange issue, when I try to do a speedtest on http://www.dslreports.com/speedtest (I select gigabit as connection type) when the test starts the upload part, after a couple of seconds the upload speed goes to 0 and the test reports the error. But with LittleSnitch I can see that the connection is actually still active, and Adguard is still uploading data.

This is the first time I can actually reproduce it reliably, but it has already happened that a connection is still active in Adguard (whether in up or download)  while the browser is already closed or reporting it as disconnected.

macOS 10.14.1 
Aguard Nightly 2.0.0.484
(but I can reproduce it even with the current stable release)

**Comment by sfionov** [comment]
There was a bug with stale connections, it may be fixed in the next nightly.

**Comment by ameshkov** [comment]
@choco could you please check if you face this issue with the latest nightly version?

**Comment by szolin** [comment]
@choco, Can you send us debug logs?
You can switch on debug logging from app menu (Settings->Advanced->Logging level->Debug) and use Console app to find them (com.adguard.Adguard).

**Comment by choco** [comment]
I installed latest nightly, and the bug is even stranger now. The upload isn't interrupted just like before, and when it finishes (little snitch doesn't report Adguard uploading) connection start hanging (nothing loading, need to restart adguard).

I tried enabling debug log, but during the testing process (visiting dslreports, performing the speed test, waiting for error for dslreports and closing the tab) I don't get any additional output....

**Comment by ameshkov** [comment]
@szolin I am starting to think that the compatibility issue here is not with AG filtering, but with our `tcpkill` tool.

**Comment by ameshkov** [comment]
@choco what exact version of Little Snitch do you use?

**Comment by choco** [comment]
I use the latest version 4.2.3. Here's a video of the issue https://gfycat.com/TerribleWellmadeCoati (the upload isn't a glitch in Little Snitch, I can see the same bandwidth values in my router statistics page).

**Comment by ameshkov** [comment]
I managed to reproduce it

**Comment by sxgunchenko** [comment]
core/pull-requests/1177
