### ISSUE TITLE
Nest app

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#617]
@adguard-bot commented on [Wed Aug 08 2018](https://github.com/AdguardTeam/AdguardFilters/issues/20873)

### Issue URL (Incorrect Blocking)
[https://nest.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fnest.com)
### Comment
Username: @ntsik
> When attempting to load the Android native Nest app with AdGuard enabled, the app never continues past the initial loading screen. In the filtering log, I see that AdGuard is blocking requests from the Nest app. The app works correctly when AdGuard is disabled.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/6JehMNe.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 7.1.2
AdGuard version: | 2.12.140β
Browser: | Native Nest app
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | Mobile Ads,<br>Annoyances,<br>English,<br>Spyware

---

@BlazDT commented on [Thu Aug 30 2018](https://github.com/AdguardTeam/AdguardFilters/issues/20873#issuecomment-417379677)

Please try to disable DNS filtering and check again.

---

@ntsik commented on [Thu Aug 30 2018](https://github.com/AdguardTeam/AdguardFilters/issues/20873#issuecomment-417391409)

I disabled DNS and HTTPS filtering, all ad blocking filters, and set AdGuard to simplified filtering quality. Even with all of that disabled, the Nest app does not progress past its initial loading screen - it only works if I disable AdGuard completely.

**Comment by zzebrum** [comment]
The app is working on both 2.12 and 3.0n versions with https-filtering enabled for this app on my side.

@ntsik please collect a debug log according to the [instruction](https://kb.adguard.com/en/android/solving-problems/log). On step 5 export the logs directly into a local file and send it to devteam@adguard.com

**Comment by ntsik** [comment]
Actually, I can no longer reproduce this issue - the Nest app now loads successfully with Adguard enabled.
