### ISSUE TITLE
uschnews.com

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#619]
@adguard-bot commented on [Mon Nov 12 2018](https://github.com/AdguardTeam/AdguardFilters/issues/25272)

### Issue URL (Incorrect Blocking)
[http://www.uschnews.com/up/index.php](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fwww.uschnews.com%2Fup%2Findex.php)
### Comment
Username: @Yevhen1996
> Rapidleech is not reaching the required result with enabled Adguard (2nd screenshot) 
> 
> Rapidleech is a tool to leech file from various filehosting. To demonstrate,
> - visit rapidleech hosted here: http://www.uschnews.com/up/index.php
> - put this link (https://speed.hetzner.de/1GB.bin) inside the top box
> - tap Transload File
> 
> Expected behaviour is, there should be a progress bar indicating download speed and download percent. But the stats will only shows up after the file finished leeching. (screenshot 1) Turning off Adguard will fix the issue.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/V03OYnJ.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/HPwDcM4.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 7.1.2
AdGuard version: | v3.0.56η (1.2.102cl)
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | AdGuard Russian,<br>AdGuard Mobile Ads,<br>AdGuard Annoyances,<br>AdGuard Simplified domain names,<br>AdGuard Base,<br>AdGuard Spyware,<br>AdGuard Social Media

**Comment by ameshkov** [comment]
Confirmed on AG for Mac as well

**Comment by sxgunchenko** [comment]
core/pull-requests/900
