### ISSUE TITLE
m.ruliweb.com

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#623]
@adguard-bot commented on [Thu Nov 15 2018](https://github.com/AdguardTeam/AdguardFilters/issues/25403)

### Issue URL (Incorrect Blocking)
[https://m.ruliweb.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fm.ruliweb.com%2F)
### Comment
Username: @Yevhen1996
> Sometimes HTTPS filtering appears
> to be malfunctioning. The reason I think so is because the
> advertisement is not visible but the vacancy remains. At that time,
> when I restart HTTPS filtering or ad blocking, the error disappears.
> 
> User: seica9733@gmail.com
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/WiTL98A.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/jNPdJOD.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 8
AdGuard version: | 2.12.247
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | disabled
Filters: | AdGuard Base,<br>AdGuard Spyware,<br>AdGuard Social Media,<br>AdGuard Mobile Ads,<br>AdGuard Annoyances,<br>EasyList,<br>ABP Japanese Filters

---

@seica9733 commented on [Sun Nov 18 2018](https://github.com/AdguardTeam/AdguardFilters/issues/25403#issuecomment-439673693)

Here are additional site and screenshot what have a same problem.
https://m.clien.net/
![screenshot_2018-11-17-20-58-48](https://user-images.githubusercontent.com/45121987/48669830-cd0e2480-eb4f-11e8-8a3c-82c1f3568715.png)
![screenshot_2018-11-17-20-59-20](https://user-images.githubusercontent.com/45121987/48669831-cd0e2480-eb4f-11e8-87a4-d0d12afeeef3.png)

---

@Alex-302 commented on [Mon Nov 19 2018](https://github.com/AdguardTeam/AdguardFilters/issues/25403#issuecomment-439852120)

I can't reproduce. HTTPS issues cannot be resolved using filters.

**Comment by Alex-302** [comment]
@zzebrum please check this site for HTTPS issues.

**Comment by zzebrum** [comment]
@seica9733  will you able to collect [debug log](https://kb.adguard.com/en/android/solving-problems/log)?

**Comment by seica9733** [comment]
I changed the logging level to "record everything" when the problem occered.
Then I exported logs that attached below.

2018년 11월 22일 (목) 오후 8:35에 zzebrum <notifications@github.com>님이 작성:

**Comment by zzebrum** [comment]
@seica9733, unfortunately, you can not attach files via email. It would be better if you send log to devteam[at]adguard[dot]com
