### ISSUE TITLE
Cookie self-destruction does not check the Expires/MaxAge value sent by a server

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#626]
Amazon sign-in is broken by stealth mode.

I have both first-party and third-party cookie self-destruction enabled, and it seems it messes up Amazon sign in. I suspect it corrupts one of the cookies instead of just changing the TTL.

**Comment by ameshkov** [comment]
The main issue is that you're modifying cookies which are passed as already expired:

Without AG: `set-cookie: ap-fid=""; Domain=.amazon.com; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/ap/; Secure`
With AG: `set-cookie: ap-fid=""; Domain=.amazon.com; Path=/ap/; Secure; max-age=86400; expires=Fri, 23 Nov 2018 14:15:06 GMT`

**Comment by sxgunchenko** [comment]
core/pull-requests/874
