### ISSUE TITLE
URL should be trimmed to 4k before checking it

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#63]
I've seen URLs longer than 256k chars.

**Comment by TPS** [comment]
Wouldn't then advertisers &/or trackers just avoid anything in the URL in the 1st 4k chars that matches any filter pattern?  Maybe rather than trimming, better/special handling of super-long URLs?

**Comment by ameshkov** [comment]
@TPS they can't avoid adding their domain address there:)

**Comment by TPS** [comment]
@ameshkov Are you saying that you've seen 4k-char _domains_⁉️ 😮   _I_ meant, anything that _can't_ be DNS-blocked can be shrewd enough to avoid heuristic assumptions, such as "checking the 1st 4k chars of a URL will be enough."

**Comment by ameshkov** [comment]
I mean that they can't hide the most important part as domain names are relatively short:)

**Comment by hmage** [comment]
URL can contain username+password in form of `https://username:password@somedomain.com/`. I'm pretty sure there will be someone that puts 4k-long username and password.

**Comment by ameshkov** [comment]
@hmage on HTTP-level username/password won't be in the URL, so that's not a problem

**Comment by hmage** [comment]
@ameshkov HTML page could still have one.

**Comment by ameshkov** [comment]
Yeah, we won't remove it from the page code in this case, but it will anyway reach the network level and be handled there.

**Comment by ameshkov** [comment]
Also, we can remove it from the page code with `$$` rules if it is really necessary

**Comment by sfionov** [comment]
Merged, core/pull-requests/77
