### ISSUE TITLE
ERR_INCOMPLETE_CHUNKED_ENCODING  on tokyomotion.net

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#635]
@adguard-bot commented on [Wed Nov 21 2018](https://github.com/AdguardTeam/AdguardFilters/issues/25685)

### Issue URL (Incorrect Blocking)
[NSFW][https://www.tokyomotion.net/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.tokyomotion.net%2F)
### Comment
> This is a bug.
> https://github.com/AdguardTeam/AdguardFilters/issues/23838#issuecomment-429558217

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/LReOJkN.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/vShweJE.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 5.1.1
AdGuard version: | v3.0.72η (1.2.116cl)
Browser: | Firefox Focus 7.0.10 (Build #322741931)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | AdGuard Mobile Ads,<br>AdGuard Annoyances,<br>AdGuard Simplified domain names,<br>AdGuard Base,<br>Malware Domains,<br>NoCoin Filter List,<br>AdGuard Spyware,<br>AdGuard Social Media,<br>AdGuard Japanese

**Comment by ameshkov** [comment]
I am almost sure that the issue is triggered by having both `Connection: close` and `Transfer-Encoding: chunked` response headers.

**Comment by sfionov** [comment]
Decompression error happens because they don't close zlib stream, but whole page is contained in gzip part transmitted to us. 
The problem is that we don't pass eof and last chunk of data properly to filters in case of decompression error.

**Comment by sfionov** [comment]
core/pull-requests/889
