### ISSUE TITLE
Some domain specific exceptions don't work

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#637]
### Steps to reproduce

1. Enable Base/English filer or for example add this rule to user filter:
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=androgalaxy.in|boo.tw|b00.tw`
2. Open this website - https://www.androgalaxy.in/ or http://boo.tw/hZTjP

### Expected behavior
`pagead2.googlesyndication.com/pagead/js/adsbygoogle.js` shouldn't be blocked.

### Actual behavior
`pagead2.googlesyndication.com/pagead/js/adsbygoogle.js` is removed.
It seems that it happens only when script is removed.

<details><summary>Screenshot:</summary>

![screenshot_2018-11-30-10-15-01](https://user-images.githubusercontent.com/29142494/49279889-ff414f80-f488-11e8-9860-8a74542c3c82.png)

</details>

### Your environment
* AdGuard version: 3.0.109

**Comment by ameshkov** [comment]
It's not just about exceptions btw.

Here's another example:

1. Add `||cryptomundo.com/wp-content/uploads/creatureplica-ad.jpg$domain=cryptomundo.com` to the user filter
2. Go to https://cryptomundo.com/
3. Expected result: AG removes the image with that src from the page code.
3. Actual result: it does not happen.

**Comment by sxgunchenko** [comment]
core/pull-requests/899

**Comment by AdamWr** [comment]
Could you please tell me if it was fixed in the latest Android nightly version 3.0.137/3.0.145 (1.2.150cl)?
If so, I still/again can reproduce that issue.

**Comment by sfionov** [comment]
@AdamWr No, CoreLibs 1.3 with this fix was not released yet. We're planning to complete it in a week.

**Comment by AdamWr** [comment]
Ok, thank you for your answer :)
