### ISSUE TITLE
CoreNetworkUtils may return link-local DNS server address without interface

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#638]
That may be a bug in Inet6Address.getHostAddress() implementation on some Androids.
We have two options:
1) Return address with interface attached, and make sure that Android's DnsUpstream and CoreLibs evdns supports it.
2) Simply strip out such addrs.

**Comment by ameshkov** [comment]
Let's simply strip them

**Comment by ameshkov** [comment]
Resolved in `core/pull-requests/996`

I've no idea how to test it properly so no instructions for QA, you'll have to simply believe us:)

**Comment by ameshkov** [comment]
@admitrevskiy  `inetAddress.isSiteLocalAddress` was unneccessary and must be removed
