### ISSUE TITLE
localplace.jp - HTTPS filtering is not working

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#640]
@adguard-bot commented on [Wed Oct 31 2018](https://github.com/AdguardTeam/AdguardFilters/issues/24649)

### Issue URL (Social Widget)
[https://localplace.jp/sp/t100304768/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Flocalplace.jp%2Fsp%2Ft100304768%2F)
### Comment
> 

### System configuration

Information | value
--- | ---
Platform: | And 5.1.1
AdGuard version: | 2.12.248η
Browser: | InBrowser v.2.42(76) UA:Safari(iPhone)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | AdGuard Mobile Ads,<br>AdGuard Annoyances,<br>AdGuard Base,<br>AdGuard Spyware,<br>AdGuard Social Media,<br>AdGuard Japanese

**Comment by Alex-302** [comment]
Reproduced with the last nightly build.

**Comment by szolin** [comment]
I can't reproduce this with the latest corelibs v1.2.150.
@Alex-302 Can you check one more time?
