### ISSUE TITLE
Indicate modified cookies in an event

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#644]
We'll need it for indicating cookies modified by $cookie rules or stealth mode:

* https://github.com/AdguardTeam/AdguardForAndroid/issues/2365
* https://github.com/AdguardTeam/AdguardForMac/issues/386
* https://github.com/AdguardTeam/AdguardForWindows/issues/2387

**Comment by sxgunchenko** [comment]
core/pull-requests/935
