### ISSUE TITLE
Ignore scriptlets and snippets properly

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#646]
There are some ABP- and uBO- specific rules that we should process gracefully:

* snippets: `#$#snippet_name(param, param)`
* uBO HTML filters: https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#html-filters
* uBO scriptlet injections: https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#scriptlet-injection

**Comment by sxgunchenko** [comment]
core/pull-requests/942
