### ISSUE TITLE
Change the case when domain is automatically added to https exclusions

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#647]
We should prevent false-positives here.

Here's what I suggest.

General rule: if a connection to a host is reset on the handshake stage 3 or more times during 5 minutes - do not filter this host it anymore.

**Exceptions:**

1. If handshake with the client was successful, do not add it to exceptions even if the server resets the connection.
2. If the client rejects the connection with `unknown_ca` or `certificate_unknown `, add the host to exceptions right away and don't wait for it to be rejected second time. *Maybe we should add more alerts types here?*

**Comment by szolin** [comment]
/core/pull-requests/905

**Comment by sfionov** [comment]
core/pull-requests/908
