### ISSUE TITLE
Chrome malformed response encoding

### ISSUE THREAD

**Issue by choco** [AdguardTeam/CoreLibs#648]
To reproduce just check http://bebop.choco.me in Chrome and other browsers. Disabling Aguard fixes it. Looking at the response header in Developer tools, the Encoding is set to chunked? this doesn't happen with either other browsers or with Adguard disabled.

The page is provided by a HAProxy instance if you want to reproduce it locally. I don't know how long I'll keep the test case online.

**Comment by ameshkov** [comment]
@sfionov can we check it asap?

**Comment by sfionov** [comment]
I've found what's the problem is.

**Comment by sfionov** [comment]
core/pull-requests/916
