### ISSUE TITLE
club.huawei.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#649]
@adguard-bot commented on [Wed Nov 28 2018](https://github.com/AdguardTeam/AdguardFilters/issues/26146)

### Issue URL (Incorrect Blocking)
[https://club.huawei.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fclub.huawei.com)
### Comment
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/1kBe1LG.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/sW9wFqF.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 9
AdGuard version: | 2.12.247
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-speed
HTTPS filtering: | disabled
DNS requests blocking: | disabled
Filters: | EasyList China,<br>AdGuard Mobile Ads,<br>AdGuard Annoyances,<br>AdGuard Base

**Comment by sfionov** [comment]
The problem is in header:
```
get-ban-to-cache-result/portal.php: userdata not support
```
`/` symbol is not allowed in HTTP header name, so technically it is not HTTP/1.1 :)

**Comment by ameshkov** [comment]
haha

**Comment by lancelot-moon** [comment]
Adding huawei.com in the whitelist of HTTPS filtering is a temporary solution.

But is it possible to solve it without whitelist?

**Comment by ameshkov** [comment]
Sure, browsers somehow handle this stuff so we should as well

**Comment by szolin** [comment]
/core/pull-requests/941
