### ISSUE TITLE
Exception rules don't work in Stealth mode.

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/CoreLibs#650]
Exception rules don't work in Stealth mode.

Steps to reproduce:

Run AdGuard - Enable stealth mode - Change user agent - Add an exception rule (@@||example.org^) -  Check result in the console (for example).

**Comment by ameshkov** [comment]
The same issue with `$stealth` rules which are supposed to be independent of regular exceptions.

**Comment by sxgunchenko** [comment]
core/pull-requests/907
