### ISSUE TITLE
com.google.android.apps.fitness [Android]

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#654]
@adguard-bot commented on [Sun Dec 02 2018](https://github.com/AdguardTeam/AdguardFilters/issues/26411)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.google.android.apps.fitness](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.google.android.apps.fitness)
### Comment
Username: @Rakleed
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/Jdm3YWi.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/YJnU7YE.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 8.0.0
AdGuard version: | v3.0.109η (1.2.150cl)
AdGuard mode: | proxy
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | AdGuard Russian,<br>Filter unblocking search ads and self-promotion,<br>AdGuard Mobile Ads,<br>AdGuard Base,<br>AdGuard Spyware,<br>AdGuard Social Media

**Comment by sxgunchenko** [comment]
cannot reproduce
