### ISSUE TITLE
Let the null manager users list means that all users must be managed by Parental Control

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#655]
At this moment we have the following rules for the `managedUsers` field within the `AGProxyParentalControlConfig`:
```
'\n'-separated list of users managed by parental control
   - null means that all users are being managed by parental control
   - empty string means that none of users are being managed by parental control
```
In fact the third case is not a significant one, because if user doesn't want to prevent anybody to be managed by the parental control, he can simply disable this module. Moreover, this third option is not implemented in the UI parts (ay least in Windows) because of uselessness. Let's combine the second and the third case -i.e. `null or empty string means that all users are being managed by parental control`

**Comment by sxgunchenko** [comment]
core/pull-requests/1018
