### ISSUE TITLE
com.dartit.RTcabinet

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#656]
@adguard-bot commented on [Tue Dec 04 2018](https://github.com/AdguardTeam/AdguardFilters/issues/26488)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.dartit.RTcabinet](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.dartit.RTcabinet)
### Comment
> При запуске приложения Ростелеком интерфейс телефона зависает. Помогает только перезагрузка.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/4rL8EFC.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/O6u5Pmx.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 9
AdGuard version: | 2.12.247
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | disabled
Filters: | AdGuard Russian,<br>AdGuard Mobile Ads,<br>AdGuard Annoyances,<br>AdGuard Base,<br>AdGuard Spyware,<br>AdGuard Social Media
Other extensions used: | Eset mobile security

**Comment by sfionov** [comment]
@TheHasagi Can you check it please?

**Comment by TheHasagi** [comment]
Checked, unable to reproduce with the latest release & beta version.
