### ISSUE TITLE
Filtering rules limitations (custom filter, user filter)

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#659]
@ameshkov commented on [Tue Dec 18 2018](https://github.com/AdguardTeam/AdguardForAndroid/issues/2401)

1. Custom filters must not support powerful modifiers ($replace and JS) unless they are explicitly enabled by the user filter (there should be a "Trusted" checkbox in the custom filter dialog)
2. Change the CSS rules validation process and discard those with `url` in the style text

`[ ] Trusted filter`
`Filters marked as trusted can use powerful filtering rules modifiers which can be dangerous in the wrong hands. Do not check this box unless you fully trust it.`

------

Let's add flags to configuratoin of filter passed to proxy.

**Comment by szolin** [comment]
/core/pull-requests/924

**Comment by ameshkov** [comment]
Guys, this needs to be done for all filters trusted included.

> Change the CSS rules validation process and discard those with url in the style text

**Comment by sxgunchenko** [comment]
core/pull-requests/1122
