### ISSUE TITLE
Detect STUN/TURN protocol

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#66]
This is mostly about UDP traffic (but happens with TCP as well).

We should be able to detect STUN/TURN(s) protocols (and to block requests afterwards).

Detection is possible if we analyze the very first outgoing packet (decrypted in case of stun/turn over tls over tcp).

**Comment by sfionov** [comment]
Done for TCP in corelibs proxy, but still needed in TCP stack for UDP

**Comment by sxgunchenko** [comment]
core/pull-requests/880
core/pull-requests/884
mac/pull-requests/134

**Comment by sfionov** [comment]
Testing instruction: Turn on stealth mode and webRTC blocking, try to test webrtc leak with something like: https://browserleaks.com/webrtc

**Comment by TPS** [comment]
Maybe this needs to be tweaked b/c of https://github.com/AdguardTeam/AdguardForAndroid/issues/3627#issuecomment-991664862?
