### ISSUE TITLE
Use alternative to scan /proc/net/tcp in the next Android version

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#661]
Android will limit what files can be read from `/proc/*`.

So I've filed a feature request and it was implemented:
https://issuetracker.google.com/issues/109758967

Patch:
https://android-review.googlesource.com/q/topic:%22getConnectionOwnerUid%22+(status:open%20OR%20status:merged)

API currently is:
`int getConnectionOwnerUid(int protocol, InetSocketAddress local, InetSocketAddress remote);`

This API is available to VPN apps **only** and the VPN must be up and running.

1. We should use in the VPN mode
2. We should find a way to read from `/proc/net/*` in the rooted mode

https://developer.android.com/reference/android/net/ConnectivityManager.html#getConnectionOwnerUid(int,%20java.net.InetSocketAddress,%20java.net.InetSocketAddress)

**Comment by sfionov** [comment]
> We should find a way to read from /proc/net/* in the rooted mode

That API is allowed to use either with active VPN or with `NETWORK_STACK` permission in manifest.
So adding permission may be a solution.

**Comment by ameshkov** [comment]
This is a signature-level signature

**Comment by MediumOne** [comment]
I have filed a request for the `getConnectionOwnerUid` API to be allowed for all apps (not only for VPN or System apps) - https://issuetracker.google.com/u/1/issues/131204361

I wanted to know if this idea was already discussed in your initial feature request (https://issuetracker.google.com/issues/109758967), it looks like your feature request report is not public. Could you please make it public, if it is okay? If not, could you please tell me if this was discussed before. Does the Android team have any issues allowing this API for all apps to use?

**Comment by ameshkov** [comment]
Initially, I asked it to be available to all apps and not just the VPN apps, but they refused. Tbh, I haven't pushed it too much.

Your usecase seems valid, but I suppose we'll need more examples to make it feasible to implement.

Also, I can't change issue visibility, it seems it was marked as private automatically when it was created.
