### ISSUE TITLE
AdGuard scriptlets syntax

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#664]
What we want to achieve:

1. Implement declarative syntax for scriptlets injections.
2. Improve compatibility with third-party filter lists like uBlock filters and ABP anti-circumvention list (see https://github.com/gorhill/uBlock/wiki/Resources-Library and https://adblockplus.org/jsdoc/adblockpluscore/snippets.js.html).

@timirila1 this is a draft specification, add or change it if you feel that something is wrong.

## Syntax

```
rule = [domains]  "#%#//scriptlet(" scriptletName arguments ")"
```

* `scriptletName` is a name of the scriptlet from AdGuard's scriptlets library
* `arguments` a list of `String` arguments (no other types of arguments are supported)

### Examples

* `example.org#%#//scriptlet('abort-on-property-read', 'somePropertyName')` - applies scriptlet `abort-on-property-read` on all pages of `example.org`

### Scriptlets library

Every scriptlet we implement needs to be defined in the documenation. In this issue I will do it for one scriptlet, but we will continue as time goes.

#### abort-on-property-read

Aborts execution of a script when it attempts to read specified property. Console output is suppressed.

**Syntax**

```
#%#//scriptlet('abort-on-property-read', property)
```

**Parameters**

* `property`
Property (or a chain of properties) attached to the `window`.

**Examples**

```
example.org#%#//scriptlet('abort-on-property-read', 'I10C')
```

**Compatibility**

We maintain compatibility with uBO's [`abort-on-property-read.js` scriptlet](https://github.com/gorhill/uBlock/wiki/Resources-Library#abort-on-property-readjs-) and ABP's `abort-on-property-read`.

### Scriptlets development

Scriptlet is defined as a simple javascript function:
```
function(source, arg1[, ...[, argN]]) {
    .....
}
```

* `source` - is a special object that contains the call properties.
    * `name` - scriptlet name. Please note that for converted rules there will be a prefix (`ubo-` or `abp-`). See the section below for the details.
    * `engine` - AdGuard engine type (`extension`, `corelibs`)
    * `version` - Engine version
    * `hit()` - records rule hit. This function needs to be called if we consider that the scriptlet was executed and done its work. We need this to record rule hits and print them to the filtering log.
* `arg1[, ...[, argN]]` - scriptlet arguments. All arguments are optional. Argument type is always `String` (**TODO: it seems that uBO supports both strings and regexes, should we do the same?**).

#### Cross-blocker compatibility

For every scriptlet we should define a list of aliases which are supported by other blockers.

Let's take `abort-on-property-read` as an example.

* Alias for uBO compatibilitiy would be: `ubo-abort-on-property-read.js`
* Alias for ABP snippet would be: `abp-abort-on-property-read`

**Conversion rules**

When doing the conversion, we should add a prefix to the scriptlet name (depending on what 

Here is how we should convert uBO scriptlet rules internally:

* From: `example.org##+js(abort-on-property-read.js, BetterJsPop)`
* To: `example.org#%#//scriptlet('ubo-abort-on-property-read.js', 'BetterJsPop')`

Here is how we should convert ABP snippets:

* From `example.org#$#abort-on-property-read I11C`
* To `example.org#%#//scriptlet('abp-abort-on-property-read', 'I11C')`

## What needs to be done

* [ ] Scriptlets library first implementation
* [ ] Unit-tests for the scriptlets
* [ ] Scriptlets build for browser extension
* [ ] Scriptlets build for corelibs
* [ ] Scriptlets build for AdGuard for Safari

**Comment by patrickdrd** [comment]
will they support "defuser" too?
please keep in mind to release a guide/documentation when it's ready,
in order for us who create our own custom fillters to convert them too

**Comment by ameshkov** [comment]
> will they support "defuser" too?

It depends, but the idea is to support the most popular generic scriptlets.

> please keep in mind to release a guide/documentation when it's ready,
> in order for us who create our own custom fillters to convert them too

Sure, we'll do. But again, I'd like us to support other blockers syntax seamlessly.

**Comment by patrickdrd** [comment]
I think ublock is the most widely used, 
so if you could integrate it seamlessly it would be absolutely amazing!

**Comment by ameshkov** [comment]
Scriptlets library has been published:
https://github.com/AdguardTeam/Scriptlets

CoreLibs integration task:
https://github.com/AdguardTeam/CoreLibs/issues/687

Browser extension integration task:
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1366
