### ISSUE TITLE
Userscript wrapper doesn't fallback to XHR if connect to Websocket server failed

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#665]

**Comment by sfionov** [comment]
TODO list: 
- [ ] Change XHR response to single format
- [ ] Use this format in `"data"` field in every websocket response. Userscript-wrapper should extract this value and handle in same way as XHR response.

Single format for XHR response:
```
{"result": result value (currently it is always boolean value), "error": string or null}
```
Example websocket response:
```
{"type":"action","payload":{"type":"is-filtered","actionId":2,"data":{"result": result value (currently it is always boolean value), "error": string or null}}}
```
(Please note that type of "data" field changed from String to Object).

**Comment by szolin** [comment]
/core/pull-requests/949

**Comment by szolin** [comment]
/core/pull-requests/989
