### ISSUE TITLE
[Bug] Some element hiding rules are not applied

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#668]
### Steps to reproduce
1. Enable Russian filter and go to https://glav.su/forum/

### Actual behavior
Ad is not hidden

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/50549084-78d28600-0c5f-11e9-8828-7a83ba35d07f.png)

</details>

these elements must be hidden by
```
glav.su##.c-bl-ad+table[class="blueHeader f"][style="margin-top: 20px;"]+table.f[width="100%"]
glav.su##.c-bl-ad+table[class="blueHeader f"][style="margin-top: 20px;"]
```
not reproduced with AdGuard for Android and browser extension.

### Your environment

* Environment name and version (e.g. Chrome 59): Chrome
* AdGuard 7.0.1994.5263
* Operating system and version (e.g. Windows 10, v.1703, build 15063.413)

**Comment by sxgunchenko** [comment]
Can't reproduce with corelibs

**Comment by adbuker** [comment]
It can be related to the https://github.com/AdguardTeam/CoreLibs/issues/699
