### ISSUE TITLE
Incomplete chain with CA url in the certificate

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#669]
@adguard-bot commented on [Sun Dec 30 2018](https://github.com/AdguardTeam/AdguardFilters/issues/27680)

### Issue URL (Annoyance)
[https://www.jaguar.hu](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.jaguar.hu)
### Comment
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/3G3cufF.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 9
AdGuard version: | v3.0.157η (1.2.150cl)
Browser: | Chrome
AdGuard mode: | proxy
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | disabled
Filters: | AdGuard Mobile Ads,<br>AdGuard Annoyances,<br>AdGuard Base,<br>hufilter,<br>Malware Domains,<br>Spam404,<br>AdGuard Spyware,<br>AdGuard Social Media,<br>AdGuard Japanese

---

@krystian3w commented on [Wed Jan 02 2019](https://github.com/AdguardTeam/AdguardFilters/issues/27680#issuecomment-450817604)

`###cookie-notification`

---

@AdamWr commented on [Wed Jan 02 2019](https://github.com/AdguardTeam/AdguardFilters/issues/27680#issuecomment-450871015)

`###cookie-notification` is already in AdGuard Annoyances filter.

It looks like a bug with certificate/HTTPS filtering, similar to this - https://github.com/AdguardTeam/CoreLibs/issues/554

**Comment by ameshkov** [comment]
Yep, reproduced with the current Mac nightly.

**Comment by AdamWr** [comment]
Similar issue on these websites:
https://beenox.com/en/ --- https://github.com/AdguardTeam/AdguardFilters/issues/27532
https://techland.pl --- https://github.com/AdguardTeam/AdguardFilters/issues/27557
https://hyundai.hu --- https://github.com/AdguardTeam/AdguardFilters/issues/27666
https://www.landrover.hu --- https://github.com/AdguardTeam/AdguardFilters/issues/27682

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/27847

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/27996

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/28000

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/28105

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/28104

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/28133

**Comment by szolin** [comment]
/core/pull-requests/975
