### ISSUE TITLE
a wrong way to filter the url

### ISSUE THREAD

**Issue by wellser** [AdguardTeam/CoreLibs#67]
when i use the rule "||bing.com^" , i still can browse the web page , Meanwhile , the scripts on this page still can work normally. so i think that the kind of block rules writing like "||*^" is not a strict way. for example , when i use the rules named "easylist" , some sites still are not filtered .

**Comment by ameshkov** [comment]
The thing is that AG won't block requests executed in a browser tab -- to not prevent pages loading.

You can overcome it with a modifier $empty.

**Comment by TPS** [comment]
@ameshkov Please clarify this.…  I'd thought `$important` was enough.

**Comment by ameshkov** [comment]
$important gives a rule higher priority comparing to other rules, but it does not change how the rules work.

`||bing.com` won't block access to the bing.com when you open it in a browser tab. That's done for your convenience as sometimes ad domains are used as intermediate "click" domains.

**Comment by TPS** [comment]
I _think_ IC.…  W/o `$empty`, I can open `doubleclick.net` _directly_ from the browser, & it'll load, but another site can't use it to load an ad?  Isn't there a `$first-party`|`$third-party`|some-such modifier already?
