### ISSUE TITLE
Adding new Facebook tracking parameters

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/CoreLibs#671]
Facebook recently decided to add a whole new bunch of tracking parameters, and I thought I'd share the ones they use when trying to click on pretty much anything on the website. Would be good if they were added to the default entries alongside the older Facebook parameters currently there.

This one is the major one (pretty much on any internal link):
`__tn__`

These are the others, some seem to replace older methods (eg. `fb_ref` is now `fref`):
`__xts__%5B0%5D`
`eid`
`source_ref`
`ref_type`
`ref`
`cref`
`fref`
`ls_ref`
`hc_ref`
`hc_location`
`comment_tracking`
`action_history`
`placement`
`campaign_id`
`extra_1`
`acontext`
`ref_newsfeed_story_type`
`feed_story_type`

**Comment by ameshkov** [comment]
Are they all purely tracking? I mean can we break anything if we add them?

@sfionov please be cautious with adding any new param, we need to test carefully how it works. In this particular case, we will need to surf facebook and click links there:)

**Comment by planet0** [comment]
> Are they all purely tracking? I mean can we break anything if we add them?

I've had these added on the beta browser extension and on the macOS nightly build, and I haven't noticed any problem when removed.

Most of these are from the News Feed, when hovering over names, photos, internal and external links. I've avoided the ones that are required, like `https://www.facebook.com/photo.php?fbid=xxxx&set=xxxx&type=xxxx` as `fbid`, `set` and `type` are needed.

I'd say `__tn__`, `__xts__%5B0%5D` and `eid` would be the three big ones that seem to be purely tracking related... but I could be wrong, you guys definitely are the experts 🏆
