### ISSUE TITLE
Add a validity checking for rules with domain modifier

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#672]
@AdamWr commented on [Sun Jan 06 2019](https://github.com/AdguardTeam/FiltersCompiler/issues/38)

Rules like these:
`|http*$domain=|example.org`
`|http*$script,domain=|example.org`
should be treated as invalid or converted to:
`|http*$domain=example.org`
`|http*$script,domain=example.org`
otherwise they are applied to all websites due to `domain=|`

**Comment by szolin** [comment]
/core/pull-requests/952
