### ISSUE TITLE
Content script is not injected to www.linkedin.com

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#675]
@JonoHaysom commented on [Wed Jan 09 2019](https://github.com/AdguardTeam/AdguardForMac/issues/401)

### Steps to reproduce

1. head to LinkedIn.com
2. top ad shown and the Adguard assistant doesn't load so I'm unable to block it manually
3.
4.

### Expected behavior
no ads and the adguard assistant should show

### Actual behavior
some ads show and no adguard assistant loads

<details><summary>Screenshot:</summary>

![screenie](https://user-images.githubusercontent.com/8393299/50920833-da64d280-145f-11e9-8afc-5954f27512b2.jpg)

</details>

Running the last MacOs Mojave developer beta and the latest version of safari

---

@zzebrum commented on [Thu Jan 10 2019](https://github.com/AdguardTeam/AdguardForMac/issues/401#issuecomment-453140997)

@JonoHaysom hi! About missed ad, it's better to report here: https://reports.adguard.com/en/new_issue.html

Assistant is not showing on the site - looks like a bug to me, because it is present with v2.5.14

You've mentioned in other thread that you [found a conflict](https://github.com/AdguardTeam/AdguardAssistant/issues/263#issuecomment-448111281) - what was that?

---

@JonoHaysom commented on [Fri Jan 11 2019](https://github.com/AdguardTeam/AdguardForMac/issues/401#issuecomment-453452467)

@zzebrum the conflict was a rule, but that seems to have not been a long term fix as its regressed and its not showing again. .

**Comment by ameshkov** [comment]
Subj, verified with the latest nightly.

Raw HTML in my case:
https://gist.github.com/ameshkov/937ca9dccae1074359293723bce88c20/raw/3d859c19835ceb80460cba372bc1ccb8870bd9f6/linkedin.html

**Comment by JonoHaysom** [comment]
thanks @ameshkov

**Comment by ameshkov** [comment]
`apple.com` might be on the list of HTTPS exclusions (so no content filtering at all)
`macrumors.com` -- I can confirm, the same issue there.

**Comment by ameshkov** [comment]
Ah, no, can't confirm macrumors:)

**Comment by sxgunchenko** [comment]
core/pull-requests/966

**Comment by JonoHaysom** [comment]
good news is that linked is fixed in the new nightly for Mac with new corelibs. 

macrumors.com is not :( cc @sxgunchenko @ameshkov

**Comment by sxgunchenko** [comment]
Ok, I will check it

**Comment by JonoHaysom** [comment]
thanks @sxgunchenko ive done regression testing with rules as well and the rules removal for macrumors.com dont involve the Adguard assistant in the new Mac nightly with latest corelibs

**Comment by ameshkov** [comment]
As I've said, the issue on macrumors has nothing to do with CoreLibs, it's just website styles somehow mess with AG Assistant, we'll handle it in https://github.com/AdguardTeam/AdguardAssistant/issues/272
