### ISSUE TITLE
Add proxy server config

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#68]
Need to discuss how to do it. We are already have interface of NativeUrlFilter in Java, so it may be enough to export urlfilter_t pointer.

**Comment by ameshkov** [comment]
Don't forget that there are also cssfilter and jsfilter.

I suppose that at the moment we'd better have a simple interface:
```
setRules(String rules)
```

Which will parse the rules string, detect the rules type and add them to the corresponding filter.

**Comment by sfionov** [comment]
Merged, core/pull-requests/42
