### ISSUE TITLE
Blocked POST requests over HTTP/2 stuck in pending state

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#681]
It seems that we somehow mess with the `POST` requests made while posting a reply on Twitter web version.

I have stealth mode enabled so that might be important.

@zzebrum please try reproducing it with AG for Mac nightly.

**Comment by ameshkov** [comment]
This is caused by blocking `POST` request to `twitter.com/i/jot ` causes this.

**Comment by sfionov** [comment]
core/pull-requests/993

**Comment by sfionov** [comment]
Testing instructions for QA:
1) Enable Spyware filter
2) Goto twitter.com and do some actions
Requests to twitter.com/i/jot should not hang in the Developer Console.
