### ISSUE TITLE
$popup rules and iframes

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#682]
Fixing this one requires some blocking page changes. The idea is to detect that we're inside an iframe and the rule has $popup modifier, and bypass this request in this case.

`||example.org^$popup`

**Comment by sfionov** [comment]
@timirila1 I've created test page for `||example.org^$popup`: 
https://sfionov.github.io/web/test.html 
Here are two issues:
1) iframe still blocked
2) popup is blocked, but URL is whitelisted for 5 seconds anyway, next popup will succeed.

**Comment by sfionov** [comment]
@timirila1 Seems that it is not completely fixed: https://github.com/AdguardTeam/CoreLibs/issues/1039

**Comment by ameshkov** [comment]
Actually, this creates more problems than it solves. Let's make $popup rules simply block frames.
