### ISSUE TITLE
Crash/Hang in AGUrlRequest.cpp:326

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#683]
Hang on Android:
https://sentry.adguard.com/adg/adguard-android-rs/issues/16193/
Crash on Android:
https://sentry.adguard.com/adg/adguard-android-rs/issues/16179/

**Comment by sxgunchenko** [comment]
core/pull-requests/995

This one happens quite rarely and randomly, so there is no some certain algorithm to reproduce it and i close it without QA check.
