### ISSUE TITLE
Add `baseUrl` parameter  to the parameter to the userscripts' `http_download_t` callback 

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#685]
The `@require` and `@resource` metatags can contain relative paths to the data (`The URL specified may be relative to the URL the script is being installed from`  - https://wiki.greasespot.net/Metadata_Block), so we should pass the `baseUrl` path as the parameter in the download callback at least in `dload_requiremets()` and `dload_resources()` methods.

**Comment by szolin** [comment]
/core/pull-requests/994

**Comment by szolin** [comment]
How to test: find a userscript which has a relative URL in `@require` or `@resource` dependency, and then try to install it
