### ISSUE TITLE
IP leaks with enabled Block WebRTC function

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/CoreLibs#686]
@TheHasagi commented on [Fri Jan 25 2019](https://github.com/AdguardTeam/AdguardForAndroid/issues/2466)

WebRTC function doesn't work. This function was worked perfectly in the previous version, but broken in 180.

### Steps to reproduce

1. Start AdGuard protection and enable Block WebRTC function in stealth mode
2. Open a browser and go to whoer.net (example)

### Expected behavior

WebRTC should be disabled or empty
### Actual behavior

WebRTC shows your real IP

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/43952607/51739598-f0e76c80-20a2-11e9-8dc1-77f47b6f830a.png)

</details>

### Your environment

* Adguard version: 5.0/6.0
* Adguard filtering mode: VPN

**Comment by karina-archazh** [comment]
Do not reproduce on previous version 3.0.165
Android 5.1/6/8

**Comment by sxgunchenko** [comment]
Can't reproduce with current version

**Comment by zzebrum** [comment]
seems to be working.
