### ISSUE TITLE
Add scriptlets support to the filtering engine

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#687]
CoreLibs side of
https://github.com/AdguardTeam/CoreLibs/issues/664

Scriptlets library:
https://github.com/AdguardTeam/Scriptlets

1. [x] Add integration with AdGuard scriptlets: https://github.com/AdguardTeam/Scriptlets
2. [ ] Automatically convert `##+js` scriptlets and `#$#` snippets to AG rules
3. [ ] Make sure that we're compatible with `##+js` (check that popular rules work similarly)
4. [ ] Make sure that we're compatible with `#$#` (check that popular rules work similarly)

**Comment by sxgunchenko** [comment]
core/pull-requests/1210
adblock's and ublock's rules conversion will be implemented in #880
