### ISSUE TITLE
When uploading photos to imgur.com by chrome on Android, the process is frozen.

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#689]
@lancelot-moon commented on [Sat Oct 06 2018](https://github.com/AdguardTeam/AdguardForAndroid/issues/2156)

When uploading photos to imgur.com by chrome after enabling AdGuard, the process is frozen.
It always shows "Processing..."
Some photos were failed to be uploaded.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/Vm3uzMP.png)
</details><br/>

Please solve it.

Thanks.

---

@karina-archazh commented on [Mon Oct 08 2018](https://github.com/AdguardTeam/AdguardForAndroid/issues/2156#issuecomment-427827002)

Hi!

Please provide:
1. Amount of images
2. AdGuard settings (DNS, HTTPS on/off)
3. Could you repeat this issue using WIFI network
4. Do you using Imgur app or web application

And please send to us some logs.

---

@lancelot-moon commented on [Mon Oct 08 2018](https://github.com/AdguardTeam/AdguardForAndroid/issues/2156#issuecomment-427917742)

I tried to only upload 1 photo to imgur.com.
Still failed.
1. 1 or several photos (5).
See.
Use Wi-Fi.
With AG, only 1 photo was uploaded by chrome but it was always processing...
Frozen.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/Ytzd5lv.png)
</details><br/>

2. DNS settings are disabled.
HTTPS filtering is on.

3. Yes, failed in both cellular network and Wi-Fi.

4. I use chrome for uploading photos on Android.

5. log:
https://app.box.com/s/lwgyb0dwgmmepa6htslfqevae1nyjfbx

---

@ameshkov commented on [Tue Oct 09 2018](https://github.com/AdguardTeam/AdguardForAndroid/issues/2156#issuecomment-427996716)

Need to be re-tested with a newer CoreLibs version (I think this upload issue is resolved there).

Might be the same as this one:
https://github.com/AdguardTeam/CoreLibs/issues/513

---

@lancelot-moon commented on [Sat Jan 26 2019](https://github.com/AdguardTeam/AdguardForAndroid/issues/2156#issuecomment-457795381)

@Revertron

In AG v3.0.195η or earlier version, the issue occurred again. (Stealth mode is disabled.)
When uploading photos to imgur.com by chrome after enabling AdGuard, the process is frozen.
It always shows "Processing..."
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/PfQ8lgp.png)
</details><br/>

**Comment by ameshkov** [comment]
Might be a duplicate of https://github.com/AdguardTeam/CoreLibs/issues/688

**Comment by ameshkov** [comment]
@lancelot-moon hi! can you reproduce this issue with the latest nightly? I cannot repro #688 so this one might be fixed as well.

**Comment by lancelot-moon** [comment]
Hi, it's related to the photo's size.
If I only upload 1 photo with 3 MB size, uploading is failed.

**Comment by lancelot-moon** [comment]
In AG for Android v3.0.217η, I tested again.
1. Only one photo with 4MB:
Successfully uploaded.

2. 5 photos, each photo is about 500kb:
Failed to upload.
The process was frozen.

**Comment by patrickdrd** [comment]
I think this falls under the uploading problems faced with AG enabled,
I've had similar problems with files uploading with drivesync and es file explorer etc,
I posted a while ago, but neither I got an answer, nor did there was a fix I guess,
anyway, in my case I just completely disabled AG for these apps and 
the problem was gone,
however you cannot do that obviously,
anyway I think that disabling AG because there are problems with uploading is not the solution,
but the team should sit down and find a solution sometime to this problem

**Comment by lancelot-moon** [comment]
In the previous nightly version, the issue ever was solved.

But it occurred again in the recent nightly versions.
Recently, AG team also updated CoreLibs...

**Comment by sxgunchenko** [comment]
core/pull-requests/1047

**Comment by TheHasagi** [comment]
Working fine now.
