### ISSUE TITLE
Element hiding is not working properly in AdGuard 7.0

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#695]
Some elements are not hidden after reboot.

#### Steps to reproduce:
0. Russian filter must be enabled;
1. Reboot system;
2. Open `i.ua`

#### Actual behavior:

<details>

![image](https://user-images.githubusercontent.com/8361299/51980378-89f9f700-2498-11e9-87f9-da9dc4810388.png)
</details> 

#### Expected behavior:

Ad is blocked:

<details>

![image](https://user-images.githubusercontent.com/8361299/51980494-e0673580-2498-11e9-9c2e-db195d9fed05.png)
</details>

If you enable/disable any filter or just restart protection, it will work as expected.

AdGuard 7.0.2092.5459

**Comment by adbuker** [comment]
As the experiment shows, this issue related to the issue with an error in the certificate validation (so called "status 7" error)

**Comment by szolin** [comment]
/core/pull-requests/1027
