### ISSUE TITLE
Wrong marking direct connection as redirected to the local api server

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#699]
As the local API server has not been started, it was not listening to the API requests in fact.

**Comment by adbuker** [comment]
[Logs1.zip](https://github.com/AdguardTeam/CoreLibs/files/2820691/Logs1.zip) - Creation of the local API server fails (the further API requests were not be handled)
[Logs2.zip](https://github.com/AdguardTeam/CoreLibs/files/2820690/Logs2.zip) - Creation of the local API server was successful (the further API requests were handled)

**Comment by sxgunchenko** [comment]
It might be fixed along with #698, as we are going to reuse one of service threads for the server.

**Comment by sxgunchenko** [comment]
core/pull-requests/1013
