### ISSUE TITLE
AdGuard fails to load huge pages when they are filtered

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#701]
Original title: AdGuard fails to load store.cherryaudio.com/

It fails to handle a page of this size (raw HTML weighs 27MB according to wget -- https://gist.github.com/ameshkov/8a9117979943e1676152b5767f5ff8a1).

On the other hand, Chrome loads it just okay, and according to Chrome, the size is 1MB only.

**Comment by sfionov** [comment]
Another case: https://github.com/AdguardTeam/AdguardFilters/issues/32120

**Comment by sfionov** [comment]
Fixed in core/pull-requests/1184
