### ISSUE TITLE
Speed cap at 400-500 Mbps

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/CoreLibs#702]
Internet connection speed is degrading when AdGuard is on and it does not depend on what filters are enabled at the same time. This problem exists even if Stealth mode enabled/disabled, the result is the same.

Affected platforms:

Mac/Win

It's not reproducible with Android.

Evidence (logs, screenshots, tests) will be provided per request.

#### Customer ID: 2061703

The same [issue](https://github.com/AdguardTeam/AdguardForMac/issues/299).

**Comment by sfionov** [comment]
Users are reporting that problem is not fixed.

**Comment by ameshkov** [comment]
@sfionov it'd be better to open a new issue about that then.
