### ISSUE TITLE
Crash in cmdGmXmlHttpRequest

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#704]
It seems that this is the most popular crash on AG for Mac at the moment:
https://sentry.adguard.com/adg/adguard-mac/issues/17042/

**Comment by sxgunchenko** [comment]
core/pull-requests/1019

**Comment by sxgunchenko** [comment]
Testing instructions:
- enable assistant in adguard
- install web of trust userscript extension
- surf the internet for some time - adguard is expected to work stable
