### ISSUE TITLE
In case of HTTPS tunnel filtering event does not contain whitelisted request status

### ISSUE THREAD

**Issue by Revertron** [AdguardTeam/CoreLibs#705]
If I disable HTTPS filtering for Firefox (or it is disabled for some other app), filtering events in filtering log are as HTTPS tunnel. This is right.
But if I add some whitelist rule to user filter like `@@||example.org$app=org.mozilla.firefox`, the event's request status should become `Whitelisted`, not just `Processed`.

![screenshot_1549450229](https://user-images.githubusercontent.com/105154/52340346-d355c380-2a0f-11e9-9c5f-0e0ed2b639cc.png)

The `RequestProcessedEvent` object has relevant applied rules and type is `BASIC_EXCEPTIONS`, we need just to add request status `WHITELISTED` for such events.

**Comment by sxgunchenko** [comment]
core/pull-requests/1024
