### ISSUE TITLE
Extend the HTTPS filtering whitelist syntax: allow specifying domain+applications pairs

### ISSUE THREAD

**Issue by nkartyshov** [AdguardTeam/CoreLibs#706]
We should extended the current HTTPS filtering exclusions list format and allow specifying app name.

**Comment by ameshkov** [comment]
Also, it'd be great to have limited wildcards support there.

For instance:
`mozilla.org$app=org.mozilla.firefox`

**Comment by sxgunchenko** [comment]
core/pull-requests/1036

**Comment by sxgunchenko** [comment]
Testing instructions:
- turn on the https filtering
- turn off `filter blacklist only` flag
- add `*.stackexchange.com` record to the https whitelist
    - check that `psychology.stackexchange.com` and `chemistry.stackexchange.com` are not filtered
- add `example.*` record to the https whitelist
    - check that `example.org` and `example.com` are not filtered
- add `mozilla.org$app=org.mozilla.firefox` record to the https whitelist
    - check that `mozilla.org` is not filtered in the firefox browser, but is filtered in any other one
- add `*$app=org.mozilla.firefox` record to the https whitelist
    - check that, for example, `yandex.ru`, `mail.ru`, and `google.com` are not filtered in the firefox browser, but are filtered in any other one

**Comment by Alex-302** [comment]
@sxgunchenko will `example.com` exclude also `example.com.tr` ?

**Comment by sxgunchenko** [comment]
> @sxgunchenko will `example.com` exclude also `example.com.tr` ?

Nope. We match only the specified domain and it's sub-domains.
