### ISSUE TITLE
Crash in SSLFilter::asyncComplete

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#714]
https://sentry.adguard.com/adg/adguard-android-rs/issues/17332/events/626960/

**Comment by ameshkov** [comment]
This one might be related as well:
https://sentry.adguard.com/adg/adguard-android-rs/issues/17336

**Comment by szolin** [comment]
/core/pull-requests/1028

**Comment by sfionov** [comment]
This task doesn't need testing.
