### ISSUE TITLE
Content script issues

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#718]
1. sfbr-script fails to load with 400 bad request
    https://uploads.adguard.com/up04_fzl9t_Windows_7_Enterprise_1.png

2. Add `ts=` parameter back to the content-script URL

**Comment by szolin** [comment]
/core/pull-requests/1034

**Comment by sfionov** [comment]
Notes for QA: 
- Safebrowsing should work again.
