### ISSUE TITLE
Protection reload issues in the Windows CoreLibs build

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#719]
Currently, it takes a couple of seconds and while it's in progress, a website might be loaded without filtering. We need to figure out how to reload protection without crashes and without leaving unfiltered connections.

**Comment by szolin** [comment]
/core/pull-requests/1037

**Comment by szolin** [comment]
/core/pull-requests/1040

**Comment by sfionov** [comment]
After reconfig crashes gone, "double clutch" was activated, so this issue is resolved.
