### ISSUE TITLE
Third-party "Hide your user agent" breaks Safari

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/CoreLibs#724]
e.g.  set up Hide your user agent with theese params: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36` or `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0` and try to open google.com or yandex.ru in Safari

**Comment by ameshkov** [comment]
Moved to https://github.com/AdguardTeam/AdguardAssistant/issues/279
