### ISSUE TITLE
$generichide exclusion is indicated as applied to HTTPS tunnel requests

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#725]
1. Disable HTTPS filtering
2. Add `@@||i.ua^$generichide`
3. Visit i.ua (desktop version)

<details><summary>Actual behavior:</summary>

![image](https://user-images.githubusercontent.com/8361299/52736576-d3872d80-2fd2-11e9-946e-67f462101365.png)

</details>

Expected behavior: this rule is not applied

**Comment by sxgunchenko** [comment]
core/pull-requests/1048

**Comment by TheHasagi** [comment]
Still not working (3.0.257n 1.3.170cl):
![img](https://uploads.adguard.com/up22_fcibf.png)

**Comment by ameshkov** [comment]
Argh

**Comment by sxgunchenko** [comment]
core/pull-requests/1095
