### ISSUE TITLE
Don't block injection host

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#728]
Guys, it seems we can block it by a filtering rule, that's not right:
https://github.com/AdguardTeam/AdguardAssistant/issues/263#issuecomment-464023251

**Comment by sxgunchenko** [comment]
core/pull-requests/1050

**Comment by sxgunchenko** [comment]
Testing instructions:
- enable Adguard Assistant
- add the following rule: ||local.adguard.org^
- go to any website
- the assistant should appear on the page
