### ISSUE TITLE
Indicate what exactly was modified in the onRequestProcessed callback

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#729]
See here:
https://github.com/AdguardTeam/AdguardForAndroid/issues/2518

**Comment by patrickdrd** [comment]
patrickdrd:
@AMeshkov please fix "modified" issue, it's very annoying, I'm entering zoogle.com and all I get is a blank page, I suspect it's a cookie issue, but since I can't see, how would I know which rule to whitelist?

**Comment by ameshkov** [comment]
Well, zoogle.com is empty with or without AG so I doubt that's our issue.

**Comment by patrickdrd** [comment]
correct, 
but it has happened before with cookies, 
I mean blank page
