### ISSUE TITLE
Fix crash reporting on Windows

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#737]
There're no reports for access violation crashes when it happens in managed code.

Relevant links:

* https://stackoverflow.com/questions/233255/how-does-setunhandledexceptionfilter-work-in-net-winforms-applications
* https://stackoverflow.com/questions/13876222/creating-dump-file-at-the-moment-of-access-violation

**Comment by northis** [comment]
Resolved in `adguard-windows/pull-requests/308` & `core/pull-requests/1058`
