### ISSUE TITLE
External apps integration

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#740]
We should rework the current approach so that the browser extension integration could've been possible in a more secure and easy way.

We need to add one request:

1. `/auth` -- authenticates the extension or the external app. All other requests must be sent with an auth token received.

Other requests are basically the same as what we have in the browser API.

**Comment by sfionov** [comment]
How to make it compatible with service workers ? Tokens will not be valid after restart.

**Comment by ameshkov** [comment]
Well, the extension will have to store token in the browser storage
