### ISSUE TITLE
'Use AdGuard as HTTP proxy' doesn't work

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/CoreLibs#744]
the proxy is configured on android device, cert is installed.

in filtering log all requests are green and there are no https requests

<details>

![image 4](https://user-images.githubusercontent.com/44832195/53178118-4eb79780-3602-11e9-8a15-7b6099e92115.png)

</details>

<details>

![image 5](https://user-images.githubusercontent.com/44832195/53178139-56773c00-3602-11e9-892e-d931774aed72.png)

</details>

**Comment by Stillness-2** [comment]
Also exists problem of accessing to certificate page from other devices in local network
