### ISSUE TITLE
Unable to open euroset/svyaznoy websites

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/CoreLibs#745]
Sometimes its unable to reach euroset.ru\svyaznoy.ru with enabled AdGuard and stealth mode. Filters are disabled (including user filter and automatic)

Turn on AdGuard enable/disable Stealth mode

Open Safari and go to google.com - type euroset.ru - open first link.

MacOS version: macOS High Sierra 10.13.6/macOS Mojave 10.14.3

AdGuard version: 1.5.14/2.0.0.511

**Comment by TheHasagi** [comment]
Fixes will be available with the update.

**Comment by zzebrum** [comment]
not fixed, but closed as dup #674
