### ISSUE TITLE
CSP issue at browse.startpage.com

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#751]
### Steps to reproduce

1. Open [browse.startpage.com](https://browse.startpage.com/do/proxy?ep=4b524257467a7362566c63494643564b46555a545052414e467a52485277515948533466444631546278734b4844524a5831684a436941454d79392b52563444585359625730306243443844556b39486477394651694e48515530664753746355774e6662566350586e6856566c6764477951664542524163426b4a51576f5846565162434478614541514e63416f45556a4a56514759634853314c4867675762517762515474485856346147537463514156655a785143516a3841586b306643447865514641576251776251544a495646414248587745433146526242524e58434e5751316f4f4448464f474149576455554452534e57514278634f576b4c4f30554352673863526e6c4658466f4f565339574551456559786347464756674655774c47546859514159424e52344f55444d5343674658535839595467494a4f55304e42544d51426c39585143304d535159474a676f625869516241683862433346304b5455425453777542526c4d636773684f576b4b4f55554452463459515770414177344b4858774a486c55495a526b4f416d5155425670594858774d543155484d526c62416d38514242384a436a774554455a456142304756477043566c384f4453424e5778514e5a42304e55434a4b52773d3d&ek=534868724q56636q4q7n6p766545773566574177&ekdata=2f58c7fcefcc35fcd750cca2e9ac1e2e)

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/53418356-484d6500-39e0-11e9-8aa4-07fea5d14b18.png)

</details>

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/53418652-ef320100-39e0-11e9-822c-95a4f5f87464.png)

</details>

### Expected behavior

<details>

![image](https://user-images.githubusercontent.com/8361299/53418538-b85beb00-39e0-11e9-9250-d16f1ce92e49.png)

</details>

### Your environment
AdGuard for Androing nightly, AdGuard for Windows 6.4 and 7.0

**Comment by sfionov** [comment]
Adguard breaks detection of browser CSP capabilities.
@Alex-302 This rule will help
`@@||session.proxy.startpage.com/csp_check$document`

**Comment by Alex-302** [comment]
Added
