### ISSUE TITLE
Unnecessary SSL exception in the log

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#752]
```
AGSslDomainFilter: [id=1000537] TLS connection is not HTTPS, adding 'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe#127.0.0.1:57402#' to exceptions
```

**Comment by sfionov** [comment]
Testing instructions for Windows:
1) Load some site with AdGuard enabled and debug logging is on
2) Make sure that Assistant is injected.
3) See last log in C:\ProgramData\Adguard\Logs\service

There should be no log messages with containing `chrome.exe#127.0.0.1`
