### ISSUE TITLE
Crash in asyncOCSPfree (SSLDataProvider::free)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#754]
https://sentry.adguard.com/adg/adguard-mac/issues/18744/?query=is:unresolved

**Comment by sfionov** [comment]
Same crash on Windows:
https://sentry.adguard.com/adg/adguard-windows/issues/18808/?query=is:unresolved

**Comment by sfionov** [comment]
Related to async OCSP check

**Comment by ameshkov** [comment]
One more:
https://sentry.adguard.com/adg/adguard-mac/issues/18827/?query=is:unresolved

**Comment by sfionov** [comment]
No need to test, no new crashes in Sentry

**Comment by adbuker** [comment]
Seems, that the issue comes back https://sentry.adguard.com/adg/adguard-windows/issues/23286
