### ISSUE TITLE
Some network rules cause that JS and cosmetic rules not work

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#759]
### Steps to reproduce

1. For example add these rules:
`||example.com^`
`example.com##body`
`example.com#%#alert("test");`
2. Go to http://example.com/

### Expected behavior

Website should show "alert" and be blank due to `example.com##body`.

### Actual behavior

JS and cosmetic rules don't work.

I'm not sure if it's by design now, but it seems that AdGuard doesn't inject script/stylesheet to website, but injects code related to blocked website?
"AdGuard has blocked access to this page"

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/53671903-ac8e5400-3c80-11e9-9cee-4d1dc9c3075e.png)

</details>
<br>

AdGuard 7.0.2243.5761

**Comment by ameshkov** [comment]
Yeah, I can confirm this issue -- it does not apply any cosmetic rule when there's a matching blocking rule.

**Comment by sxgunchenko** [comment]
core/pull-requests/1100
