### ISSUE TITLE
$empty modifier shouldn't remove script from website

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#760]
### Steps to reproduce

1. For example add this rule:
`||adguard.com/js/main.min.js$empty,important`
2. Go to https://adguard.com/

### Expected behavior

Request should be "blocked", but script shouldn't be removed from website.

### Actual behavior

Script is removed.

AdGuard 7.0.2243.5761

**Comment by sxgunchenko** [comment]
core/pull-requests/1096

**Comment by sxgunchenko** [comment]
Testing instructions:
- add rule `||adguard.com/js/main.min.js$empty,important`
- go to https://adguard.com/
- check in console that there was request by url `adguard.com/js/main.min.js` and it was responded with empty response
