### ISSUE TITLE
Speedtest.net doesn't work and display error

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#761]
@AdamWr commented on [Sat Mar 02 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2449)

In the latest nightly version (7.0.2243.5761) speed test on speedtest.net doesn't work and show error.

### Steps to reproduce

1. Go to https://www.speedtest.net/
2. Click on GO button
3. Wait a moment as test will finish

### Expected behavior

Speed test should works correctly.

### Actual behavior

Speed test on speedtest.net doesn't work and show error.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/53666036-4e0baa80-3c6d-11e9-8940-751f29558ed5.png)

</details>

### Your environment

* Environment name and version: Chrome 72.0.3626.119
* Operating system and version: Windows 10, v.1809, build 17763.316

**Comment by ameshkov** [comment]
Same issue on Mac as well

**Comment by sfionov** [comment]
Not reproducable with current code
