### ISSUE TITLE
No mapping for the Unicode character exists in the target multi-byte code page

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#762]
https://sentry.adguard.com/adg/adguard-windows/issues/18983/?query=is:unresolved
https://sentry.adguard.com/adg/adguard-windows/issues/18878/?query=is:unresolved

**Comment by adbuker** [comment]
resolved in `adguard-windows/pull-requests/321`  and in `core/pull-requests/1092`

**Comment by adbuker** [comment]
related cases:
https://sentry.adguard.com/adg/adguard-windows/issues/19099
https://sentry.adguard.com/adg/adguard-windows/issues/19125
https://sentry.adguard.com/adg/adguard-windows/issues/19101
https://sentry.adguard.com/adg/adguard-windows/issues/19137

**Comment by adbuker** [comment]
resolved in `core/pull-requests/1114`

**Comment by adbuker** [comment]
additional patches were applied in `core/pull-requests/1126` along with `core/pull-requests/1131` and `core/pull-requests/1133`
