### ISSUE TITLE
Rule is not applied on android

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/CoreLibs#764]
the link: https://reshak.ru/otvet/otvet_txt.php?otvet1=/spotlight11/images/pic/6b_2

ads are not blocked on android 

android:
<details>

![screenshot_20190304-154742_chrome 1](https://user-images.githubusercontent.com/44832195/53734676-b210b780-3e95-11e9-8300-7e4d0777b911.jpg)

</details>
mac:
<details>

![image 7](https://user-images.githubusercontent.com/44832195/53734231-66114300-3e94-11e9-93ef-0fec2d83afdd.png)

<img width="970" alt="2 6b spotlight 11 2019-03-04 15-53-02" src="https://user-images.githubusercontent.com/44832195/53734637-a2916e80-3e95-11e9-8f74-183add0b4a04.png">

</details>

**Comment by TheHasagi** [comment]
Cannot reproduce with the latest nightly build (android).
