### ISSUE TITLE
Update ExtendedCss to v1.1.2

### ISSUE THREAD

**Issue by maximtop** [AdguardTeam/CoreLibs#765]
Note that ExtendedCss has a new signature for the `init` function.

**Comment by sfionov** [comment]
We need it integrated to content script. Can you please do it?

**Comment by ameshkov** [comment]
Additionally, we have added `{ remove: true }` support, we should handle it.

**Comment by sfionov** [comment]
Updated to 1.1.2

**Comment by sfionov** [comment]
core/pull-requests/1142
core/pull-requests/1143
