### ISSUE TITLE
muve.pl - broken website

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#767]
### Steps to reproduce

1. Go here - https://muve.pl/sklep/digital/strzelaniny/metro-exodus-pc-pl-digital,701062

### Expected behavior

There should be video player and gallery (like on screenshot below).

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/53753903-b6979900-3eb2-11e9-9b16-d6c45b3a1d57.png)

</details>

### Actual behavior

Video player and gallery are not displayed.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/53753943-d0d17700-3eb2-11e9-8c45-e8accacfd857.png)

</details>
<br>

It seems that it happens only on first visit* and only if "Browsing Security" module is enabled.

*or when developer console is enabled and option "Disable cache" is enabled

### Your environment

* AdGuard 7.0.2243.5761
* Environment name and version: Chrome 72.0.3626.121
* Operating system and version: Windows 10, v.1809, build 17763.348

**Comment by vshlobinag** [comment]
Element has opacity 0.001. Possible fix: delayed load of SB script.

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/CoreLibs/issues/1221
