### ISSUE TITLE
Cannot block third-party iframe [CL 1.3.195]

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#771]
Steps to reproduce:
1. Open https://www.pravda.com.ua/news/2019/02/24/7207524/index.amp

Actual behavior: Not blocked
<details>

![image](https://user-images.githubusercontent.com/8361299/53877946-376da680-4013-11e9-9ada-9ba2bb11cb9a.png)

</details>

<details>

![image](https://user-images.githubusercontent.com/8361299/53878558-e5c61b80-4014-11e9-9c66-904bf44d286a.png)

</details>

AG 6.4 blocks it by `||orbit*.lun.ua^$third-party`

<details>

![image](https://user-images.githubusercontent.com/8361299/53878513-bdd6b800-4014-11e9-8eb9-97516da932bf.png)

</details>

Note: Please add this exclusion before checking `pravda.com.ua#@#amp-iframe[src*=".lun.ua/"]`

**Comment by ameshkov** [comment]
@timirila1 looks like a bug in the blocking page code -- it fails to detect that this is an iframe.

**Comment by ameshkov** [comment]
More examples here:https://github.com/AdguardTeam/CoreLibs/issues/730
