### ISSUE TITLE
Some "xmlhttprequest/ajax" requests are treated as "other"

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#774]
### Steps to reproduce

1. Open filtering log
2. Go to https://vod.tvp.pl/video/korona-krolow,odc-184,41268622
3. Search in filtering log for `ad.txt`

### Expected behavior

Request should be treated as xmlhttprequest.

### Actual behavior

Request is treated as other.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/53892704-15811d80-402d-11e9-95c5-3e42c3af0869.png)

![image](https://user-images.githubusercontent.com/29142494/53892725-216cdf80-402d-11e9-977b-20c5875cd4cf.png)

</details>

### Your environment

* AdGuard 7.0.2261.5797
* Environment name and version: Chrome 72.0.3626.121
* Operating system and version: Windows 10, v.1809, build 17763.348

**Comment by ameshkov** [comment]
That'd be not easy to solve btw, it's hard to detect XHR properly on the network level.
