### ISSUE TITLE
Slow loading of tiles on maps.yandex.ru

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#777]
It's rather easy to reproduce, just open it with disabled caching. The first load is very slow. Compare it to what you have with disabled AdGuard.

**Comment by roboderpy** [comment]
This is caused by slow HTTP/2 filtering, both on Smartphone and on Desktop (after 7.0 is released)

**Comment by sfionov** [comment]
Fixed in CL 1.3.275.
