### ISSUE TITLE
krunker.io - game not works

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#782]
### Steps to reproduce

1. Go to https://krunker.io/
2. Wait a moment

### Expected behavior

Game should works.

### Actual behavior

Game not works.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/53951654-41ed7600-40cf-11e9-9c5a-dd734790bb57.png)

</details>

### Your environment

* AdGuard 7.0.2281.5837

**Comment by sxgunchenko** [comment]
core/pull-requests/1192
