### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION_EXEC in onVerifyComplete

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#784]
https://sentry.adguard.com/adg/adguard-windows/issues/19177/?query=is:unresolved

**Comment by sfionov** [comment]
May be related to https://github.com/AdguardTeam/CoreLibs/issues/780

**Comment by adbuker** [comment]
once again https://sentry.adguard.com/adg/adguard-windows/issues/19149

**Comment by sfionov** [comment]
core/pull-requests/1135
