### ISSUE TITLE
Unable to reach some websites

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/CoreLibs#786]
@TheHasagi commented on [Thu Mar 07 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2483)

It's unable to reach vk.com/ok.ru/mail.ru with such extensions like [this](https://chrome.google.com/webstore/detail/uvpn-free-and-unlimited-v/coahpcpgfnnaddeelpphpifmgfobflog) with AdGuard (nightly 7.0.xxx) enabled.

### Steps to reproduce

1. Download and install AdGuard (latest nightly from [this link](agrd.io/windows_nightly)
2. Add [this extension](https://chrome.google.com/webstore/detail/uvpn-free-and-unlimited-v/coahpcpgfnnaddeelpphpifmgfobflog) to Chrome
3. Open Chrome - uVPN - Settings - enable "Unblock mode"

### Expected behavior

Everything should be in order

### Actual behavior

Website wont load at all

**Comment by sfionov** [comment]
May be related to #785

**Comment by sfionov** [comment]
Does it happen with 7.0.2346n ?

**Comment by ameshkov** [comment]
@TheHasagi ping?

**Comment by TheHasagi** [comment]
Now it works fine as it should.
