### ISSUE TITLE
Some websites load very slowly

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#788]
To reproduce open this website - https://player.pl/
Website loads very slowly with AdGuard enabled.

Maybe related to this issue - https://github.com/AdguardTeam/CoreLibs/issues/777

AdGuard 7.0.2286.5847

**Comment by AdamWr** [comment]
I'm not sure if it's the same issue, but images on this website also loads slowly (on first visit) - https://www.nbcnews.com/

**Comment by AdamWr** [comment]
One more website - https://www.timesofmalta.com/
If I'm not wrong it happens on many websites.

**Comment by roboderpy** [comment]
This is caused by slow HTTP/2 filtering, both on Smartphone and on Desktop (after 7.0 is released)

**Comment by danidoedel** [comment]
@ameshkov Could this get some attention in the near future please? The Windows nightly is unusable right now :(

**Comment by ameshkov** [comment]
@danidoedel well, yeah, this is the most important issue at the moment. Actually, there are different reasons for different websites, and we're addressing them one by one. So if you see a **really slow** website, please report it here. It'd be easier for us if we have more examples.

Btw, besides that, try switching driver to "redirect mode" (you can do it in advanced settings) and check if there's a noticeable difference.

**Comment by ameshkov** [comment]
@sfionov merging these two here:
https://github.com/AdguardTeam/AdguardForWindows/issues/2554
https://github.com/AdguardTeam/AdguardForWindows/issues/2549

**Comment by AdamWr** [comment]
Two more websites which load really slow on my end (on first visit):
https://open.spotify.com/browse/featured
https://wiedzmin.fandom.com/wiki/Wied%C5%BAmin_Wiki

Several others which load just slow:
https://www.wolframalpha.com/
https://www.neowin.net/
https://www.filmweb.pl/
https://www.gram.pl/
and YouTube (on first visit, maybe not slow like other websites, but without AdGuard it loads faster), for example - https://www.youtube.com/watch?v=z77ILqE1l5M

**Comment by sfionov** [comment]
core/pull-requests/1197

**Comment by AdamWr** [comment]
It's definetly better now, but it seems that on https://www.timesofmalta.com/ images again/still load slowly, the same on https://www.cdaction.pl/ (on first visit).
AdGuard for Windows Version 7.0.2591.6457n(CL 1.3.313)/7.0.2617.6509n(CL 1.3.325)

Could you please check it again?

**Comment by sfionov** [comment]
@AdamWr Did you try with verbose logging on or off?

**Comment by AdamWr** [comment]
I checked it with "Logging level" set to "Default".
