### ISSUE TITLE
Some extended CSS rules are not working

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#789]
@Alex-302 commented on [Fri Mar 08 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2488)

### Steps to reproduce

1. Open https://ok.ru/feed and log in
2. Add `ok.ru##.feed-list > .feed-w:has(.feed_label:contains(Реклама))`
Please check if ad label is not obfuscated

<details>

![image](https://user-images.githubusercontent.com/8361299/54033463-0b8e2480-41bd-11e9-8a9f-a905b12759a5.png)
</details>

### Expected behavior
Ad in the feed is hidden

### Actual behavior

<details>
Ad is not hidden. Browser extension can hide it

![image](https://user-images.githubusercontent.com/8361299/54033372-d08bf100-41bc-11e9-9f40-0d2ab4b43303.png)

</details>

### Your environment
AdGuard 7.0.2286.5847

**Comment by sfionov** [comment]
Works on 7.1.2818
