### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION_WRITE in http_parser_on_header_value

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#791]
https://sentry.adguard.com/adg/adguard-windows/issues/19451

**Comment by adbuker** [comment]
An another crash. It's not absolutely the same, but is very similar i guess: https://sentry.adguard.com/adg/adguard-windows/issues/19610

**Comment by sfionov** [comment]
Another case:
https://sentry.adguard.com/adg/adguard-mac/issues/23368/
