### ISSUE TITLE
com.teamviewer.teamviewer.market.mobile - cannot login

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#794]
@adguard-bot commented on [Sat Mar 02 2019](https://github.com/AdguardTeam/AdguardFilters/issues/30345)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.teamviewer.teamviewer.market.mobile](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.teamviewer.teamviewer.market.mobile)
### Comment
Username: @AChekanoff
> Включенный AG не позволяет залогиниться приложению TeamViewer.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/aegEUUT.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/XSGAieq.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 7.0
AdGuard version: | 2.12.250
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | disabled
Filters: | AdGuard Russian,<br>AdGuard Mobile Ads,<br>AdGuard Base,<br>AdGuard Tracking Protection,<br>AdGuard Social Media

---

@Alex-302 commented on [Tue Mar 05 2019](https://github.com/AdguardTeam/AdguardFilters/issues/30345#issuecomment-469629185)

@AChekanoff может фильтрацию HTTPS включили для этого приложения? Она должна быть выключена. У меня авторизация работает.

---

@AChekanoff commented on [Tue Mar 05 2019](https://github.com/AdguardTeam/AdguardFilters/issues/30345#issuecomment-469642417)

Для конкретного приложения не включал HTTPS фильтрацию. Всё по умолчанию стоит. А вот в общих настройках AG HTTPS фильтрация включена. Попробовал отключить - всё равно не логинится, пока не сниму галку с "пропускать траффик приложения через AG".

---

@Alex-302 commented on [Mon Mar 11 2019](https://github.com/AdguardTeam/AdguardFilters/issues/30345#issuecomment-471682378)

Странно. Перенесу в более подходящий репозиторий.

**Comment by Alex-302** [comment]
@zzebrum please check it. I can't reproduce.

**Comment by AChekanoff** [comment]
@Alex-302 Только что обновил фильтры и teamviewer стал логиниться. (на момент создания багрепорта фильтры тоже были обновлены)

**Comment by ameshkov** [comment]
Ну тогда по ходу надо закрывать:)
