### ISSUE TITLE
Can't load protanki.tv

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#797]
@adguard-bot commented on [Mon Mar 11 2019](https://github.com/AdguardTeam/AdguardFilters/issues/30817)

### Issue URL (Incorrect Blocking)
[NSFW][https://protanki.tv/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fprotanki.tv%2F)
### Comment
> Не отображаеться сайт
> --
> Информация ниже сгенерирована автоматически, не удаляйте ее.
> 
> Referrer:
> https://protanki.tv/
> 
> Custom userscripts:
> https://cdn.adguard.com/public/Userscripts/AdguardPopupBlocker/2.5/popupblocker.user.js
> https://cdn.adguard.com/public/Userscripts/AdguardAssistant/4.2/assistant.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/iP83Duf.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/48FEQPm.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 6.4.1814.4903
Browser: | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
AdGuard driver: | WFP
Filters: | AdGuard Russian,<br>Filter unblocking search ads and self-promotion,<br>AdGuard Base,<br>AdGuard Tracking Protection,<br>AdGuard Social Media

**Comment by Alex-302** [comment]
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/54218346-11a23f00-44f6-11e9-814a-60d004aee84c.png)

</details>

**Comment by TheHasagi** [comment]
Unable to reproduce with the release build.
