### ISSUE TITLE
Brotli support

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#8]
Details:
https://github.com/AdguardTeam/AdguardForWindows/issues/1545

**Comment by sfionov** [comment]
Will be done in http module

**Comment by TPS** [comment]
>Will be done in http module

@sfionov What issue, so 1 can keep track of progress?

**Comment by sfionov** [comment]
@TPS It is done in http module. Eventually there will be issues about integrating HTTP filtering code to specific platform.

**Comment by TPS** [comment]
My latest update of Android System Webview β (v83.0.4103.14) now installs a launcher icon for itself, which leads to an included tab for flags (I guess the equivalent to Chrome's [chrome://flags](chrome://flags)).  Therein listed is a toggle for `WebViewBrotliSupport`, which brings this capability to _most_ browsers on Android.

How would such connections be listed in the AG-Android Filtering Log?  How is AG-A currently handling them?  Something like [`QUIC`](https://github.com/AdguardTeam/CoreLibs/issues/487)?

**Comment by sfionov** [comment]
Brotli is one of compression algorithms supported by CoreLibs. Brotli encoded responses are regular responses, so doesn't require specific handling to be displayed in filtering log.

**Comment by TPS** [comment]
_Could_ there be a note in the log whenever Brotli is encountered?  I'd be very curious as to how often I might run into it.
