### ISSUE TITLE
AdGuard's JS is injected to the page despite of `$document` exclusion

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#801]
Steps to reproduce:
1. Add `@@//github.com^$document` and `##body`
2. Go to github.com

#### Actual behavior:

Page content is hidden.

<details>

![image](https://user-images.githubusercontent.com/8361299/54393137-1ca1ce80-46b2-11e9-8c6e-66b2a4fa1843.png)

</details>

#### Expected behavior:

Page content is not hidden, and no AdGuard injections.

AdGuard 7.0.2325.5925

**Comment by Alex-302** [comment]
is not it related to https://github.com/AdguardTeam/CoreLibs/issues/800?

**Comment by ameshkov** [comment]
Nope, this is smth new

**Comment by sxgunchenko** [comment]
Seems like the issue is in windows app, not in corelibs. I cannot reproduce it with corelibs only test application, also i could not reproduce it on mac.

**Comment by sfionov** [comment]
core/pull-requests/1136
