### ISSUE TITLE
Update blocking-pages translations

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/CoreLibs#805]
Some languages' warning page of browsering security aren't localized via AG for Android.

We don't talk about the locales which have no translator.

The warning page already has Japanese, German and other languages' page.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/35S8Pcg.png)

![image](https://i.imgur.com/KpmcLCi.png)

![image](https://i.imgur.com/8gMlY8b.png)
</details><br/>

Why is it still English page for Chinese [Taiwan (zh-TW) and China (zh-CN)] and Portuguese [Portugal (PT-PT) and Brazil (PT-BR)]?

Something wrong because Chinese and Portuguese separately have 2 locales?

**Comment by sfionov** [comment]
@timirila1 Can you please update translations of `blocking-pages`?
They are in `Miscellaneous` project:
https://adguard.oneskyapp.com/collaboration/translate/project/project/119172/

**Comment by sfionov** [comment]
@lancelot-moon I'll check, but probably it is because of country code in locale.

**Comment by lancelot-moon** [comment]
I'm very afraid to see Simplified Chinese (zh-CN) in Traditional Chinese (zh-TW) interface.
Please remember to add zh-TW and zh-CN.
Chinese has **2 different locales**.
Thanks a lot for the checking of your codes!

**Comment by sfionov** [comment]
Ok, checked, so the list of tasks which should be done:
[ ] Android: pass one of supported languages to CoreLibs instead of country name of locale (zh, pt is passed now)
[ ] blocking-pages: use language codes from Windows app, including: use "pt" for "pt-BR" locale and "pt-pt" for "pt-PT"
[ ] blocking-pages: update completed translations

**Comment by lancelot-moon** [comment]
Need suitable length per line and line break for a long translation.
ex: The Japanese blocking page.
(The Traditional Chinese translation should not be affected because it's not long.)
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/EfCpQej.png)
</details><br/>

**Comment by sfionov** [comment]
Also, `errorPage` has incorrect title - Access denied.

**Comment by lancelot-moon** [comment]
This is fixed in v3.0.344η.
The blocking page can be Traditional Chinese.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/Bw5HIVV.png)
</details><br/>

But we need to **update the translations of blocking page**.
And other minor problems.

**Comment by sfionov** [comment]
core/pull-requests/1247

**Comment by lancelot-moon** [comment]
Confirmed.
The translations of blocking page were updated.
You can close the issue.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/3gAcpnw.png)
</details><br/>

**Comment by lancelot-moon** [comment]
@sfionov 

For better looking, I added spaces between English words and Chinese characters as follows on onesky.
ex:
AdGuard已封鎖至...
- > AdGuard 已封鎖至...

於example.com之網域...
-> 於 example.com 之網域...

May you again update the translations of blocking page for AG for Windows/Mac/Android?
Sorry to bother you.
