### ISSUE TITLE
Websocket is not detected

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#809]
or `ws` and `wss` are replaced by `https` in the filtering log.

Steps to reproduce:
1. Open https://www.anilibria.tv/release/black-clover-special.html
2. Search for `static.anilibria.tv/ws/` in filtering log

Actual behavior:

`https://static.anilibria.tv/ws/`

`|ws*://$domain=anilibria.tv` is not working.

Expected:

`wss://static.anilibria.tv/ws/`

AdGuard for Windows 7.0 / 3.2.288 AdGuard for Android

**Comment by sfionov** [comment]
filtering ws:// and wss:// is not implemented yet.

**Comment by ameshkov** [comment]
Uh, this is bad.

**Comment by sxgunchenko** [comment]
core/pull-requests/1137
