### ISSUE TITLE
Matching empty $csp and $cookie rules

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#812]
### Steps to reproduce:

1. Add this rule: `$csp=script-src 'none',domain=example.org`
2. Open `example.org`

### Expected result:

The rule matches `https://example.org`.

### Actual result:

No match.

### Explanation

This behavior is different from how browser extensions behave. The thing is that browser extensions pass `documentUrl` even for a request for this very document, that's why there's a match.

We should do the same -- pass `referrer` when we request $csp or $cookie rules.

**Comment by sxgunchenko** [comment]
core/pull-requests/1168
