### ISSUE TITLE
Windows application is crashing constantly while running in proxy mode

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#813]
> Aguard 7x Nightly third second and first release are all creating huge problems running in proxy mode. 

Please find the logs and settings backup in our NCloud.

**Comment by dyingjedi** [comment]
Thanks for creating this bug report @ameshkov Hi5

![Adguard Nightly 7x 3rd release Manual off Logs showing Manual_Proxy - also showing everything in IP's constant crashing what it looks like when it crashes Screenshot_3 16 19](https://user-images.githubusercontent.com/526981/55276657-d6f12280-52bb-11e9-9e83-c5d56db3c536.png)
![Adguard instagram com straight crashing 3 15 19 ](https://user-images.githubusercontent.com/526981/55276658-d789b900-52bb-11e9-8ea7-fb25196499aa.png)
![Adguard Nightly 7x 3rd release constant crashing Screenshot_3 16 19](https://user-images.githubusercontent.com/526981/55276659-d789b900-52bb-11e9-8bda-0985e0062a5d.png)
![Adguard Nightly 7x 3rd release constant crashing what it looks like when it crashes Screenshot_3 16 19](https://user-images.githubusercontent.com/526981/55276660-d789b900-52bb-11e9-9a51-a2a1cda40f39.png)
![Adguard Nightly 7x 3rd release Glasswire showing arp and mac changes Screenshot_3 16 19](https://user-images.githubusercontent.com/526981/55276661-d8224f80-52bb-11e9-9150-5e321ade7652.png)
![Adguard Nightly 7x 3rd release Loaded Logs from Dec 2018 showing everything as domain names constant crashing what it looks like when it crashes Screenshot_3 16 19](https://user-images.githubusercontent.com/526981/55276662-d8224f80-52bb-11e9-8e56-468df567eafc.png)
![Adguard Nightly 7x 3rd release Logs showing Manual_Proxy - also showing everything in IP's constant crashing what it looks like when it crashes Screenshot_3 16 19](https://user-images.githubusercontent.com/526981/55276663-d8224f80-52bb-11e9-9bcd-93b71ca3a47a.png)

**Comment by dyingjedi** [comment]
@ameshkov Would you like me to drop all the same logs here to?

**Comment by ameshkov** [comment]
@dyingjedi 

Hi! No, we have them in our private file storage, I don't think placing logs here is a good idea.

**Comment by ameshkov** [comment]
@dyingjedi btw, do you still have this issue in the latest nightly?

**Comment by adbuker** [comment]
@dyingjedi, hello! Which nightly version do you use? If it is not the latest (7.0.2408), please try it (https://agrd.io/windows_nightly), seems that this issue should gone away with this build
