### ISSUE TITLE
No CSS injections into AMP documents

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#816]
Here's an example:
https://amp-reddit-com.cdn.ampproject.org/v/s/amp.reddit.com/r/dataisbeautiful/comments/3qeepr/recommended_data_visualization_tools_free/?usqp=mq331AQECAEoAQ%3D%3D&amp_js_v=0.1

For some reason, there's no AG injections there.

**Comment by sfionov** [comment]
content-script in injected (AG 3.0.297)

**Comment by ameshkov** [comment]
Ah, my bad, you're right
