### ISSUE TITLE
HTTP/2 Filtering is REALLY slow

### ISSUE THREAD

**Issue by roboderpy** [AdguardTeam/CoreLibs#817]
Я раньше грешил на смартфон (когда перешёл на третью версию Адгуарда), но после того как адгуард 7.0 вышел на настольный пк, я понял, что проблема именно в CoreUtils.
Как я заметил, на смартфоне скорость лочится на ~360 КБ/сек на сайтах с HTTP/2, на ПК около ~700 КБ/сек

AdGuard with CoreUtils which can filter HTTP/2 is slow in general. It is not bottlenecked to CPU or anything (in videos below AdGuard were using ~1.2% of entire CPU (6.5% is one CPU core))

Example 1: https://derpibooru.org
[Without AdGuard enabled](https://i.dbotthepony.ru/2019/03/08-29-15-b099e158.webm)
[With AdGuard enabled](https://i.dbotthepony.ru/2019/03/08-30-02-4593d4a3.webm)

Example 2: https://www.artstation.com
[Without AdGuard enabled](https://i.dbotthepony.ru/2019/03/08-32-08-93d746eb.webm)
[With AdGuard enabled](https://i.dbotthepony.ru/2019/03/08-31-04-ec65b687.webm)

Example 3: https://deviantart.com
[Without AdGuard enabled](https://i.dbotthepony.ru/2019/03/08-44-01-8ea9c4d6.webm)
[With AdGuard enabled](https://i.dbotthepony.ru/2019/03/08-44-44-6b7257c4.webm)

**Comment by sfionov** [comment]
Нет, замедление на некоторых сайтах происходит на обоих протоколах (HTTP/1.1 и HTTP/2).

**Comment by sfionov** [comment]
Duplicate of #788

**Comment by roboderpy** [comment]
На 1.1 замедление едва заметно, ибо там более заметен TTFB

**Comment by sfionov** [comment]
Спасибо, интересно. Посмотрим эти примеры тоже.

**Comment by ameshkov** [comment]
Закрываю как дубликат #788 но спасибо большое за примеры!

**Comment by sfionov** [comment]
@roboderpy Можете попробовать новую найтли 7.0.2463. Там решены многие проблемы производительности.

**Comment by roboderpy** [comment]
![pic](https://i.dbotthepony.ru/2019/04/Adguard_16-10-38-550ce6d.png)
Неа, адгуард все ещё продолжает резать скорость. Примеры обновлять не буду, ибо те же страницы с адгуардом грузятся явно медленнее. Попробовал ещё адгуард в режиме перенаправления, разницы не увидел.
![networx_16-15-55-33a7e45](https://user-images.githubusercontent.com/6339511/56090753-97882000-5ed0-11e9-81c7-9885451a9c92.png)

**Comment by ameshkov** [comment]
@sfionov я утащил ссылку в #861. Я хз с чем связано, но у кого-то оверхед на H2 сильно заметен, у кого-то он минимальный.

Вообще нам нужен тест с загрузкой большого файла over HTTP/2, на нем заметнее должно быть в чем тут конкретно проблема.

Я таки предполагаю что проблема в нашем Flow Control. Можно каким-нибудь тупейшим тестом проверить, например сходу размер окна увеличивать до 10МБ и смотреть как все поменяется.

**Comment by sfionov** [comment]
@roboderpy Ограничение скорости из-за несбалансированных настроек HTTP/2 действительно имело место. :( В найтли 7.0.2475 ситуация должна сильно улучшиться.

**Comment by roboderpy** [comment]
оно работает

**Comment by ameshkov** [comment]
Всмысле все норм теперь? Ну и прекрасно.

**Comment by roboderpy** [comment]
Да, спасибо большое
