### ISSUE TITLE
uscr_make_meta_json hangs installing the userscript when non-js content passed as a userscript source

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#818]
For example, if the content of the `https://github.com/reek/anti-adblock-killer/blob/master/anti-adblock-killer.user.js` (HTML page) is passing as a userscript's source in the `uscr_make_meta_json`, execution of this method is fails into the infinite loop

**Comment by sxgunchenko** [comment]
core/pull-requests/1148

**Comment by sxgunchenko** [comment]
Testing instructions:
- try to add extension by entering some non-userscript containing url (for example, https://yandex.ru/)
- adguard should not hang trying to add one
