### ISSUE TITLE
Corrupted stack at urlfilter_search (urlfilter.cc:2134)

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#820]
https://sentry.adguard.com/adg/adguard-windows/issues/20343
https://sentry.adguard.com/adg/adguard-windows/issues/20336

**Comment by adbuker** [comment]
once again https://sentry.adguard.com/adg/adguard-windows/issues/22264

**Comment by ameshkov** [comment]
https://sentry.adguard.com/adg/adguard-windows/issues/24921/

**Comment by sxgunchenko** [comment]
core/pull-requests/1370
