### ISSUE TITLE
[Nightly] Adguard Broken Download File hash

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#822]
@swan201 commented on [Tue Mar 26 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2535)

Adguard 7.0.2372.6019 

http://isoredirect.centos.org/centos/7/isos/x86_64/CentOS-7-x86_64-Minimal-1810.iso

Download ISO manytime always File Hash is diffenrent and File is Crash

---

@sfionov commented on [Tue Mar 26 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2535#issuecomment-476761167)

Thank you for report! 
Confirmed, moving to CoreLibs repository.

**Comment by sfionov** [comment]
@swan205 As a workaround, to be able to download large files before fix, you may switch on redirect driver mode in: 
Settings -> General -> Advanced settings -> [x] Use redirect driver mode

**Comment by sfionov** [comment]
@swan201 As a workaround, to be able to download large files before fix, you may switch on redirect driver mode in: 
Settings -> General -> Advanced settings -> [x] Use redirect driver mode

**Comment by swan201** [comment]
I am currently running a nightly version in a system for debugging. But thank you for the information. I'll check the problem again at the next update.
