### ISSUE TITLE
Loading sites with AIA extension in certificate hangs

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/CoreLibs#823]
@Eugene-Savenko commented on [Mon Mar 25 2019](https://github.com/AdguardTeam/HttpsExclusions/issues/146)

### Issue URL (Incorrect Blocking)
[https://tk-barn.ru/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Ftk-barn.ru%2F)
### Comment
> Исправили добавив tk-barn.ru в исключения HTTPS.
> 
> --
> Информация ниже сгенерирована автоматически, не удаляйте ее.
> 
> Referrer:
> 
> 
> Custom userscripts:
> https://cdn.adguard.com/public/Userscripts/Wot/1.0/wot.meta.js
> https://cdn.adguard.com/public/Userscripts/AdguardAssistant/4.2/assistant.meta.js
> https://cdn.adguard.com/public/Userscripts/AdguardPopupBlocker/2.5/popupblocker.meta.js

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/87ZFwQv.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/LEVINaY.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Mac
AdGuard version: | 2.0.0.524 nightly
Browser: | Chrome
Filters: | AdGuard Russian,<br>AdGuard Annoyances,<br>AdGuard Base,<br>AdGuard Tracking Protection,<br>AdGuard Social Media

---

@Eugene-Savenko commented on [Mon Mar 25 2019](https://github.com/AdguardTeam/HttpsExclusions/issues/146#issuecomment-476106134)

https://github.com/AdguardTeam/AdguardFilters/issues/31578

---

@zzebrum commented on [Wed Mar 27 2019](https://github.com/AdguardTeam/HttpsExclusions/issues/146#issuecomment-477074431)

@Eugene-Savenko it seems to CL bug

**Comment by sfionov** [comment]
Should work with CL 1.3.241.
