### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION_READ in strlen within the adg_proxy_start 

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#829]
https://sentry.adguard.com/adg/adguard-windows/issues/20351

**Comment by adbuker** [comment]
a new one within the `AGHttpHeaders` ctor- https://sentry.adguard.com/adg/adguard-windows/issues/22278

**Comment by sfionov** [comment]
@adbuker Last one is related to https://github.com/AdguardTeam/CoreLibs/issues/877

**Comment by sfionov** [comment]
This one is fixed in #873
