### ISSUE TITLE
2 notifications appear after manual ad blocking via assistant

### ISSUE THREAD

**Issue by Stillness-2** [AdguardTeam/CoreLibs#830]
AdguardTeam/AdguardForMac#419
Mac app receives 2 `add` event.

**Comment by sfionov** [comment]
One without isWebsocket, another one without ruleText

**Comment by timirila1** [comment]
It seems like Assistant throw an error, and userscript-wrapper fallback to XMLHttpRequest, and the same request sent twice.

**Comment by ameshkov** [comment]
> It seems like Assistant throw an error, and userscript-wrapper fallback to XMLHttpRequest, and the same request sent twice.

What kind of error?

**Comment by timirila1** [comment]
>What kind of error?
```
Cannot read property 'style' of null
```

in line
`iframeAnchor.style.setProperty("display", "block", "important")`

**Comment by sfionov** [comment]
>Cannot read property 'style' of null 
> in line
> iframeAnchor.style.setProperty("display", "block", "important")

Still needs to be fixed is Assistant. I leave it open.
