### ISSUE TITLE
'Block Location API' doesn't hide the fact that location was allowed in the browser settings

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/CoreLibs#832]
### Steps to reproduce
1. Allow your location in your browser settings for the site - https://browserleaks.com
# 
e.g. Chrome
![image](https://user-images.githubusercontent.com/43952607/55400482-ae388980-5556-11e9-9948-b934d7b59466.png)

2. Go to the Adguard settings -> Stealth Mode -> Enable 'Block location API'
3. Test  - https://browserleaks.com/geo

### Actual behavior
![image](https://user-images.githubusercontent.com/43952607/55400569-dfb15500-5556-11e9-9b7f-2981df3880bc.png)

### Your environment
* Adguard 2.0.1.526 beta (CL-1.3.250)
* Chrome 75.0.3745.4
* MacOS Mojave

**Comment by sfionov** [comment]
@aspasskaya But it doesn't determine actual location - shows "PERMISSION_DENIED". Stealth script is working as expected.
