### ISSUE TITLE
Blocked 'WebRTC, location API, push API' doesn't show in modified request in filtering log

### ISSUE THREAD

**Issue by Stillness-2** [AdguardTeam/CoreLibs#833]
AdguardTeam/AdguardForMac#449

**Comment by sfionov** [comment]
А что не так? На андроиде показывается

**Comment by sfionov** [comment]
Seems that these options doesn't work in Mac app.

**Comment by sfionov** [comment]
Works fine in Windows app.

**Comment by sfionov** [comment]
Fixed in
`core/pull-requests/1171`
and
`mac/pull-requests/191`

For QA:
1) Stealth mode should now work even when all filters are disabled
2) Options WebRTC / block Push API / block location API should be in Filtering log
