### ISSUE TITLE
$replace rule performance issue

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#834]
AdGuard 7.0.2428.6131

Steps to reproduce:
1. Add `||e.mail.ru/api-proxy/rb-mimic/v1/page?page_id=$replace=/.+\"direct\":\{\"ads\"://`
2. Refresh e.mail.ru (log in before)

Actual behavior:
High CPU usage. Site works is very slow(loading of mails and navigation in the box).

**Comment by ameshkov** [comment]
Cannot reproduce this one. If this happens again, please collect the debug log and reopen this issue

**Comment by Alex-302** [comment]
UPD: changed description. Only current site is affected.

**Comment by ameshkov** [comment]
The problem is in the rule itself

**Comment by ameshkov** [comment]
Ah, not really, I am wrong

**Comment by ameshkov** [comment]
Nvm, the $replace is too slow
