### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION_READ in cookierule_apply_...

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#835]
Issue both in the `cookierule_apply_response` - https://sentry.adguard.com/adg/adguard-windows/issues/20880 and the `cookierule_apply_request` - https://sentry.adguard.com/adg/adguard-windows/issues/20881. This issue starts with cl `1.3.253`

**Comment by ameshkov** [comment]
Assigned to v1.3

**Comment by sxgunchenko** [comment]
core/pull-requests/1172
