### ISSUE TITLE
$replace rules are reported 4 times instead of one

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#836]
STR (for Mac)

1. Add `||e.mail.ru/api-proxy/rb-mimic/v1/page?$replace=/.*\"direct\":\{\"ads\"://`
2. Open the filtering log
3. Open `https://e.mail.ru/api-proxy/rb-mimic/v1/page?ajax_call=1&x-email=aypetrov%40mail.ru&tarball=e.mail.ru-f-beepteam-mail-68339-d.dorofeev-1553856532.tgz&tab-time=1554285241&o_ss=AAA%3D&o_v=41&page_id=27219&stat_id=1512006&slot=368518&search_uid=&location=https%3A%2F%2Fe.mail.ru%2Fmessages%2Finbox%2F&referer=https%3A%2F%2Fe.mail.ru%2Fmessages%2Finbox%2F%3Fback%3D1&agent=Mozilla%2F5.0%20(Macintosh%3B%20Intel%20Mac%20OS%20X%2010_14_0)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F73.0.3683.86%20Safari%2F537.36&q=368518.27219.1512006&key=`
4. You'll see that it was applied 4 times: https://uploads.adguard.com/up04_fzzd4_Monosnap.png

**Comment by sxgunchenko** [comment]
core/pull-requests/1182
