### ISSUE TITLE
Comments in filter validation rules

### ISSUE THREAD

**Issue by northis** [AdguardTeam/CoreLibs#838]
Comments is still valid rule, but now they are invalid.

**Comment by sfionov** [comment]
I've already done this :)

**Comment by slavaleleka** [comment]
I still can't add comment to user filter (Win 10, AG 7.0.2430.6135, CL 1.3.253)

**Comment by sfionov** [comment]
Yes, will be fixed in next release.

**Comment by sfionov** [comment]
core/pull-requests/1173
