### ISSUE TITLE
Regexp issue in $replace rules

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#845]
Regexp does not matches the text.

Steps to reproduce:
1. Open CSS which contains branded background on 4pda.ru
For example, http://s.4pda.to/eysS2ZibqnseT5h1FU934Iz2z1mOY.css?_=1554321292 (URL is random, find the necessary file using dev tools) 
2. Add:
`||s.4pda.to/*.css$replace=/(background:#e6e7e9) url\("\/\/s\.4pda\.to\/[A-Za-z0-9]+.jpg"\)/\$1/`
https://regex101.com/r/mPgB6R/2

#### Expected result:

Background on 4pda.ru is gray

#### Current result:

Background is branded. This rule works as expected in AG 6.4

**Comment by sxgunchenko** [comment]
core/pull-requests/1289
