### ISSUE TITLE
`$app` modifier is case sensitive

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#846]
`||api.taboola.com^$app=Mahjong.exe` - works
`||api.taboola.com^$app=mahjong.exe` - not working

AdGuard 7.0 last night, Win10

**Comment by ameshkov** [comment]
Well, but that's right, this is how it supposed to be

**Comment by Alex-302** [comment]
But `Mahjong.exe` is equal to `mahjong.exe`. "There can be only one".

**Comment by ameshkov** [comment]
Why, process names are case sensitive (btw, the same is true for android package names) so that's why we made $app case sensitive.

**Comment by Alex-302** [comment]
ok
