### ISSUE TITLE
qamqor.gov.kz

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#847]
@adguard-bot commented on [Thu Apr 04 2019](https://github.com/AdguardTeam/AdguardFilters/issues/32084)

### Issue URL (Incorrect Blocking)
[http://qamqor.gov.kz](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fqamqor.gov.kz)
### Comment
> При включенном adguard сайт не открывается.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/WSmBj5B.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/KDCftkh.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 6.0.1
AdGuard version: | v3.0.297 (1.3.207cl)
Browser: | Chrome (data compression)
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing first-party cookies (4320), Self-destructing third-party cookies (180), Block WebRTC, Block Location API, Hide your Referrer from third-parties (), Hide your Referrer from third-parties, Hide your User-Agent (), Hide your IP address (209.141.53.254)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | AdGuard Russian,<br>EasyList,<br>AdGuard Mobile Ads,<br>RU AdList,<br>EasyPrivacy,<br>Fanboy's Annoyances,<br>Fanboy's Social Blocking List,<br>AdGuard Annoyances,<br>AdGuard Base,<br>Peter Lowe's list,<br>Adblock Warning Removal List,<br>Malware Domains,<br>Spam404,<br>RU AdList: Counters,<br>RU AdList: BitBlock,<br>I don't care about cookies,<br>Fanboy's Cookiemonster List,<br>NoCoin Filter List,<br>AdGuard Tracking Protection,<br>AdGuard Social Media

---

@Alex-302 commented on [Thu Apr 04 2019](https://github.com/AdguardTeam/AdguardFilters/issues/32084#issuecomment-480028469)

Обновите приложение. С более новой 3.0 не повторяется.

---

@AlexeyGOOD commented on [Fri Apr 05 2019](https://github.com/AdguardTeam/AdguardFilters/issues/32084#issuecomment-480257930)

Alex-302, добрый день. У меня установлена последняя версия. И не открывается сайт. Это я создал issue.

**Comment by AlexeyGOOD** [comment]
Hello everybody. Can anybody help me to resolve the issue? 🙄

**Comment by ameshkov** [comment]
@AlexeyGOOD а можете заодно проверить с последней nightly-версией приложения?

Канал обновления можно переключить в настройках.

**Comment by AlexeyGOOD** [comment]
@ameshkov, переключил на nightly версию 3.0.310 . В ней сайт открывается правильно. В чем проблема была? В стабильной исправить можно?

**Comment by ameshkov** [comment]
@AlexeyGOOD ну просто судя по всему этот баг уже исправлен в одном из обновлений nightly.

> В стабильной исправить можно?

Только с выходом следующей стабильной версии.

Пока что временным решением будет в настройках HTTPS-фильтрации добавить в белый ссписок `gov.kz`
