### ISSUE TITLE
Add new CSP directives support

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#848]
https://www.chromestatus.com/feature/5141352765456384

**Comment by sxgunchenko** [comment]
core/pull-requests/1215

**Comment by sxgunchenko** [comment]
Testing instructions:
- set "Experimental Web Platform features" flag in the Chrome browser (enter "chrome://flags" in address string and find it there) - in 73.0.3683.103 version those directives are not enabled by default
- add the following rules: `||example.org^$csp=style-src-elem 'none'` and `||example.org^$csp=script-src-elem 'none'`
- go to `example.org` and check the browser console - there should not be any csp related errors
