### ISSUE TITLE
forum.ru-board.com - net::ERR_INCOMPLETE_CHUNKED_ENCODING

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#849]
AdGuard 7.0.2442.6159/CL 1.3.266

#### Steps to reproduce:
1. Open https://forum.ru-board.com/board.cgi?catplace=11 and navigate the site.

#### Actual behavior:

Page is not loaded.
Screenshots:

<details>

![image](https://user-images.githubusercontent.com/8361299/55727825-84caa280-5a1b-11e9-92bc-70c01288eda5.png)
![image](https://user-images.githubusercontent.com/8361299/55727723-43d28e00-5a1b-11e9-8d33-2adb22943390.png)
</details>

**Comment by sfionov** [comment]
@Alex-302 Does it happen on 7.0.2454 nightly (CL 1.3.275) ?

**Comment by Alex-302** [comment]
@sfionov yes. On Win7 only.

**Comment by sfionov** [comment]
Cannot reproduce on the latest nightly

**Comment by zubrRB** [comment]
@sfionov 
У меня на 7 BETA (Win 7, Chrome 74.0.3729.157) повторяется: форум и его страницы открываются только после значительно числа перезапусков страницы. Та же проблема и с форумом-миллионником https://talks.by/showthread.php?t=14410856. При попытке его открытия - белый фон и отсутствует помощник. При выключении Защиты форум мгновенно загружается.

**Comment by zubrRB** [comment]
Аналогичная проблема с крупным сайтом https://www.kp.ru и его региональными зеркалами.

**Comment by zubrRB** [comment]
Та же проблема с сайтом крупного телеком-оператора https://www.velcom.by/ru/

**Comment by zubrRB** [comment]
Тоже с файлообменником http://depositfiles.com/files/qruy1pkax

**Comment by ameshkov** [comment]
@sfionov кстати кажется это только на винде - на маке не повторяется

**Comment by ameshkov** [comment]
@sfionov проблема в заголовке `Connection: close` и том что `FIN` слишком быстро летит
