### ISSUE TITLE
AdGuard crashes on cdaction.pl

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#850]
@AdamWr commented on [Mon Apr 08 2019](https://github.com/AdguardTeam/AdguardForAndroid/issues/2692)

AdGuard crashes everytime I visit this website - https://www.cdaction.pl/
### Steps to reproduce

1. Go to this website - https://www.cdaction.pl/ and wait a moment.

### Expected behavior

AdGuard shouldn't crash.
### Actual behavior

AdGuard crashes.

### Your environment

* Adguard version: 3.0.310n (1.3.261cl)
* Adguard filtering mode: Local VPN
* Device model: Samsung Galaxy S9
* Operating system and version: Android 9
* Root access: No
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?: -

**Comment by sfionov** [comment]
It was a sockets bug in 1.3.260, not reproduced in 1.3.267 (AG3.0.311)

**Comment by AdamWr** [comment]
Yes, you are right, with 1.3.267 (AG3.0.311) I can't reproduce it too.
Thank you.
