### ISSUE TITLE
Blocked by CORS policy issue

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#851]
@TheHasagi commented on [Mon Apr 08 2019](https://github.com/AdguardTeam/AdguardForMac/issues/454)

Customer facing an issue "redirect has been blocked by CORS policy issue" in dev-tools - console.

<details><summary>Short clip:</summary>

[link](https://cl.ly/669db8)

</details>

### Customer ID 1817719

Logs will be provided upon request.

---

@ameshkov commented on [Mon Apr 08 2019](https://github.com/AdguardTeam/AdguardForMac/issues/454#issuecomment-480943747)

When AG blocks a request, it responds with a fake error response (status=500) that does not have an `Access-Control-Allow-Origin` header (which seems to be required by the CORS policy of the website).

To solve this, we'll need to add `Access-Control-Allow-Origin` header with smth like `https://origin-domain` to these "blocked" responses.

**Comment by sxgunchenko** [comment]
core/pull-requests/1196

**Comment by TheHasagi** [comment]
Waiting for the customer.

**Comment by sfionov** [comment]
@TheHasagi Waiting for the customer timeout :)
