### ISSUE TITLE
AdGuard's JS is not injected on ilkfullfilmizle.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#860]
### Steps to reproduce
1. Add these rules:
`ilkfullfilmizle.com##body`
`ilkfullfilmizle.com#%#alert("test");`
2. Go to https://www.ilkfullfilmizle.com/roman-empire-3-sezon-turkce-dublaj-izle-tum-bolumleri.html

### Expected behavior

Website should be blank and there should be an alert.

### Actual behavior

Cosmetic and JavaScript rules not work.

By the way, on main page https://www.ilkfullfilmizle.com/ it works fine.

AdGuard 7.0.2454.6183 (CL 1.3.275)
<hr>

**EDIT** 24.04.2019

Website changed address, now it is ilkfullfilmizle1.com
Rules:
`ilkfullfilmizle1.com##body`
`ilkfullfilmizle1.com#%#alert("test");`
Link:
https://www.ilkfullfilmizle1.com/roman-empire-3-sezon-turkce-dublaj-izle-tum-bolumleri.html

**Comment by sxgunchenko** [comment]
Seems like the bug is in content script actually. There are some errors in browser console during its evaluation.

**Comment by ameshkov** [comment]
@sxgunchenko check the source code, there is no `local.adguard.org` there

**Comment by sxgunchenko** [comment]
yep, i was wrong
fixed in core/pull-requests/1249
