### ISSUE TITLE
HTTP/2 performance optimization

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#861]
I feel there's some space for optimizations here. I can see some overhead on processing H2 connections.

**Comment by sfionov** [comment]
I can't reproduce slowdown with tiles.

**Comment by ameshkov** [comment]
Relevant:
https://github.com/AdguardTeam/CoreLibs/issues/817

**Comment by sfionov** [comment]
Testing instructions: Make sure that sites from #817 are not noticeable slower with AdGuard than without it.
