### ISSUE TITLE
Content-Encoding: gzip header is missing from response

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#866]
Steps to reproduce: invite someone on Github to your team or organization.

This page will be broken:
https://github.com/orgs/AdguardTeam/invitations/USERNAME/edit

**Comment by sxgunchenko** [comment]
Cannot reproduce. Please, provide more details.

**Comment by ameshkov** [comment]
Well, I guess we should try reproducing this on my laptop then.

**Comment by sfionov** [comment]
Duplicate of https://github.com/AdguardTeam/CoreLibs/issues/951
