### ISSUE TITLE
trading.just2trade.online is broken

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#867]
@adguard-bot commented on [Mon Feb 11 2019](https://github.com/AdguardTeam/AdguardFilters/issues/29527)

### Issue URL (Incorrect Blocking)
[https://trading.just2trade.online](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Ftrading.just2trade.online)
### Comment
> с выключенной программой сайт открывается без проблем
> wilne83@mail.ru

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/1ODedx3.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/IG2eDKi.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Mac
AdGuard version: | 1.5.14
Browser: | Safari
Stealth mode options: | 
Filters: | AdGuard Russian,<br>AdGuard Base,<br>AdGuard Spyware,<br>AdGuard Social Media,<br>ABPindo
Other extensions used: | нет

**Comment by Alex-302** [comment]
Steps to reproduce:
1. Log in
2. Go to demo section

**Comment by slavaleleka** [comment]
logging in isn't needed, you can check here too
![image](https://user-images.githubusercontent.com/45171506/56577207-1701a780-65d3-11e9-9a81-9efe0479b266.png)

**Comment by sfionov** [comment]
```Invalid HTTP header field was received: frame type: 1, stream: 105, name: [proxy-connection], value: [Keep-Alive]```
