### ISSUE TITLE
Invoke the callback, when browser cannot validate our cert

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#868]
Issue related to the https://github.com/AdguardTeam/AdguardForWindows/issues/2390.
We need to get at least the `domain` and the `processName` as a parameters for this callback

**Comment by sfionov** [comment]
Okay, we may turn EvCertificateEvent into just CertificateEvent of two types:
1) UNKNOWN_CA
2) EV_CERT

**Comment by sxgunchenko** [comment]
core/pull-requests/1218

**Comment by sxgunchenko** [comment]
core/pull-requests/1226
