### ISSUE TITLE
Root: automatically detect an active VPN app and not filter it's traffic

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/CoreLibs#871]
https://play.google.com/store/apps/details?id=com.guoshi.httpcanary

Already moved both apps' certificates to system store.
The app can catch HTTPS packets.
With AG (local proxy auto mode), lose internet.

Incompatible?

**UPD**: https://github.com/AdguardTeam/CoreLibs/issues/871#issuecomment-485067042

**Comment by ameshkov** [comment]
Have you disabled filtering for this app? Otherwise, you'll get in an infinite recursion (AG -> HttpCanary -> AG -> ...)

**Comment by lancelot-moon** [comment]
Can you disable filtering for this app by default?

**Comment by ameshkov** [comment]
Reopened this issue.

Here's what we should do:
1. Remove the VPN apps from the default list of exceptions;
2. When we're in the root+proxy mode, we should automatically detect the VPN-based apps, and not filter them.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdguardForAndroid #2712](https://github.com/AdguardTeam/AdguardForAndroid/issues/2712) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lancelot-moon** [comment]
Before, KB teach the solution for real VPN with AG.
Ex:
NordVPN + AG local proxy auto mode (root).

Will AG not filter NordVPN traffic?
Then ads won't be blocked.
