### ISSUE TITLE
AGUrlRequest: failed to set SNI with Firefox

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#873]

**Comment by sfionov** [comment]
Added more logging

**Comment by sfionov** [comment]
More logging helped: I see garbage instead of safebrowsing host sometimes.

**Comment by sfionov** [comment]
Seems to be a problem in managed code.

**Comment by sfionov** [comment]
Testing instructions: 
- Turn on debug mode in Adguard
- Surf the Internet in Firefox
- Make sure that is no "Failed to set SNI" messages in Adguard log
