### ISSUE TITLE
Consider binding to interface when CoreLibs resolves some host

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#876]

**Comment by ameshkov** [comment]
For what reason?

**Comment by sfionov** [comment]
@ameshkov There are may be misconfigured VPNs that doesn't provide own DNS addresses, but redirects IP of DNS used in system. DNS then refuses queries because they originate from address which is not allowed.

Windows system resolver can handle this, CoreLibs can't (at this time).

**Comment by ameshkov** [comment]
Huh, let's not mess with resolving DNS until we've figured this one then.

@adbuker plz take a look. Let's rollback the DNS resolving part for now.
