### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION_READ in http_parser_on_message_complete

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#877]
https://sentry.adguard.com/adg/adguard-windows/issues/21683

Can be related to https://github.com/AdguardTeam/CoreLibs/issues/244, https://github.com/AdguardTeam/CoreLibs/issues/157, https://github.com/AdguardTeam/CoreLibs/issues/395

**Comment by sfionov** [comment]
Not related actually.
Seems that crash is because `http_session` pointer is garbage or already freed.

**Comment by sfionov** [comment]
Another examples of garbage session:
https://sentry.adguard.com/adg/adguard-windows/issues/21204/
https://sentry.adguard.com/adg/adguard-windows/issues/22278

**Comment by adbuker** [comment]
the issue comes back https://sentry.adguard.com/adg/adguard-windows/issues/23160

**Comment by sfionov** [comment]
Crash is from 1.3.340 while it is fixed in 1.3.344
