### ISSUE TITLE
Internal filters conversion

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#880]
* Scriptlets/snippets conversion (don't forget about converting `#@#+js`).
* Convert `:style` uBO rules to `#$#`.
* Convert `##^script:has-text` to `$$script[tag-containts]`
* `inline-script` -- the same as `csp=script-src 'self' 'unsafe-eval' http: https: data: blob: mediastream: filesystem:`
* `inline-font`  -- the same as `csp=font-src 'self' 'unsafe-eval' http: https: data: blob: mediastream: filesystem:`

**Comment by sxgunchenko** [comment]
core/pull-requests/1459
