### ISSUE TITLE
Handle split of first request properly

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#882]
@swan201 reported:

![image](https://user-images.githubusercontent.com/12713262/56708460-a89a2200-6757-11e9-99be-885d4470fd7f.png)

https://memo.naver.com/ site show HTTP protocol error too

(Need to required account)

edited, Chrome is work fine, only firefox have this problem

**Comment by sfionov** [comment]
So, Firefox sends TLS record with "G" and then TLS record with "ET / HTTP...".
May be to broke some transparent proxies, and they've succeed in it.

**Comment by sxgunchenko** [comment]
core/pull-requests/1252
