### ISSUE TITLE
Parental SafeSearch doesn't work

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#886]
Can be related to the fact, that within the method `processHttpRequest` we check for the condition `nullptr == strstr(host, query.hostPattern)`, but this header can be absense https://uploads.adguard.com/buker_w3xh7.png

**Comment by sxgunchenko** [comment]
core/pull-requests/1234

**Comment by sfionov** [comment]
Testing instructions: Make sure that SafeSearch is working at search sites with HTTP/2 (e.g. google.com or yandex.ru)
