### ISSUE TITLE
HTTPS filtering does not work in YaBro and partly works in Chrome Dev on Android

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#888]
It seems, that it works only partially. Most of the domains are processed as "HTTPS tunnel" while for some it still works.

More than that, it seems that the similar issue exists for Chrome Dev. I see that at the same the very same domain can be reported as "tunnelled", and filtered (for some requests).

**Comment by ameshkov** [comment]
Also, there might be something wrong with `onRequestProcessed` callbacks. They seem to be called more times than they should (that's why there might be more HTTPS tunnel events than it should).

**Comment by sfionov** [comment]
They send Unknown CA alert when MITM is detected. 
Fixed for Windows in https://github.com/AdguardTeam/AdguardForWindows/issues/2565 by ignoring unknown CA (it was not ignored due to related bug, but on Android it is not ignored by design).
