### ISSUE TITLE
Some requests are not blocked on Android

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#889]
It happens only on Android.

### Steps to reproduce
1. Enable  `Simplified domain names filter` or add this rule to user filter:
`||nextclick.pl^`
2. Go to this website:
https://m.mistrzowie.org/
or
https://m.cda.pl/video/show/james_bond

### Expected behavior

Requests from `nextclick.pl` should be blocked.
### Actual behavior

Requests from `nextclick.pl` are not blocked.

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/29142494/57239837-53022700-702d-11e9-9493-e04742cff09b.png)
![image](https://user-images.githubusercontent.com/29142494/57240048-e5a2c600-702d-11e9-9727-c2816e1ba2b2.png)
![Screenshot_20190506-183258_AdGuard](https://user-images.githubusercontent.com/29142494/57240136-1256dd80-702e-11e9-8847-12c369400aa3.jpg)

</details>

### Your environment

* Adguard version: 3.0.344n(1.3.312cl)
* Adguard filtering mode: VPN

**Comment by ameshkov** [comment]
Two issues here:

1. No HTTPS filtering for that domain
2. It is not blocked despite having that rule

**Comment by sxgunchenko** [comment]
core/pull-requests/1245
