### ISSUE TITLE
Add $badfilter modifier support

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#89]
https://github.com/uBlockOrigin/uAssets/issues/192#issuecomment-285904675

**Comment by hmage** [comment]
In code review. Done in commit f50a012de4f731eff0956f4d3376ba2f11bf4cd2.

**Comment by hmage** [comment]
Merged in a084b41fb25643ce394091a9b35fc56f4ad5a7e6.
