### ISSUE TITLE
Edge Chromium won't load images on some sites.

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#892]
@SHJordan commented on [Sat May 11 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2632)

### Steps to reproduce
1. Open Edge Chromium browser.
2.Navigate to a google spreadsheet page.

### Expected behavior
Display images and block ads.

### Actual behavior
Many images aren't load and chrome console spams some errors:

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/884602/57570489-e4301f80-73d8-11e9-9e75-1e1c5b730ebb.png)

</details>

### Customer ID 
I'll update this when i receive the autoreply
### Your environment
* Environment name and version: Microsoft Edge Version 76.0.155.0 (Official build) canary (64-bit)
* Operating system and version: Windows 10, v.1809, build 17763.475

**Comment by TheHasagi** [comment]
Unable to reproduce with the latest release.

**Comment by zzebrum** [comment]
@SHJordan  reopen if needed then.
