### ISSUE TITLE
AdGuard Assistant doesn't work

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#894]
@TheHasagi commented on [Tue Apr 30 2019](https://github.com/AdguardTeam/AdguardAssistant/issues/284)

AdGuard assistant doesn't work on all web pages, it is just non-clickable and the whole page is unavailable after you click on the assistant icon.

![img](https://uploads.adguard.com/TheHasagi3dmvf.jpg)

App version:

![img](https://uploads.adguard.com/TheHasagir6w57.jpg)

**Comment by ameshkov** [comment]
@sfionov XHR API is broken again?

**Comment by sxgunchenko** [comment]
core/pull-requests/1253
