### ISSUE TITLE
Android TCP stack implementation (to be used by VpnService)

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#9]
https://trello.com/c/GJ9konJN/11-android-tcp-stack-implementation-to-be-used-by-vpnservice

- [x] TCP stack implementation (LWIP)
- [x] Prepare prototype Android app
- [x] Add TCP proxy redirect
- [x] Add TCP reject
- [x] Pass code review
- [x] Support UDP protocol
- [x] Support ICMP protocol
- [x] Unit-tests and leak profiling

**Comment by ameshkov** [comment]
Guys, here is one more thing regarding UDP protocol exclusively -- instead of redirect/reject rules we will need special "packet filtering" rules.

**Comment by sfionov** [comment]
Please keep in mind that `recvfrom()` on linux may return errno ECONNREFUSED is ICMP port unreachable is received, even if udp socket is unconnected. We should ignore it.

**Comment by ameshkov** [comment]
@vozersky we need to thoroughly test this new implementation.

Try using it for some time, just use your device with the prototype app enabled.
To test UDP protocol implementation try using popcorntv app.
