### ISSUE TITLE
$document rules include $elemhide, $content, $jsinject, $urlblock

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#90]

**Comment by ameshkov** [comment]
See updated tests in the `filtering/bug/90` branch

**Comment by hmage** [comment]
In code review. Fixed in commit 95c4ca6a68a86adbf3f2765d696c3344c2d78b4c

**Comment by hmage** [comment]
Merged in 0ab727f821ec85f3c32df4ad5b00a9f6fe1895e0
