### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION_READ in AGEventLoop::cancel 

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#900]
https://sentry.adguard.com/adg/adguard-windows/issues/22424

crashed in `std::list<AGEventLoop::TaskInfo,std::allocator<AGEventLoop::TaskInfo> >::begin()`

**Comment by sfionov** [comment]
The same bug as in https://github.com/AdguardTeam/CoreLibs/issues/862
