### ISSUE TITLE
AdGuard Assistant not shown on sites in IE11

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#901]
@BlazDT commented on [Tue May 14 2019](https://github.com/AdguardTeam/AdguardAssistant/issues/286)

When opening the following sites in Internet Explorer 11 the Assistant is not shown, in Chrome it is shown:

https://www.naver.com
https://www.daum.net

Rules to the sites are applied though (tested with ##body).

When checking in console I see over 30 errors with:

This object does not support this property or method "includes". When clicking the location it points to local.adguard.com and this code snippet (I cannot find that code section in a filter rule though):

`return r},a=function(){return Date.now()-n};return{isIgnoredEventType:function(){return e.includes(s())&&a()<10}}}(),w=[],N`

**Comment by aspasskaya** [comment]
The problem is still exist
- Error 
![image](https://user-images.githubusercontent.com/43952607/59505175-577ff200-8ead-11e9-9baa-cfdacd499a90.png)

**Comment by sfionov** [comment]
It is another problem, in Adguard Extra extension

**Comment by ameshkov** [comment]
@aspasskaya please check for updaates and re-test it
