### ISSUE TITLE
Slow upload speed to YouTube

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#903]
AdGurad 7.0.2591.6457
![image](https://user-images.githubusercontent.com/8361299/57858439-c0664280-77f9-11e9-8eca-c6a5633c2168.png)

**Comment by Alex-302** [comment]
@zubrRB

**Comment by zubrRB** [comment]
Полчаса назад отправил логи по этому багу и двум другим на devteam@adguard.com.

**Comment by zubrRB** [comment]
Похоже, с Google Диск https://drive.google.com та же проблема... Хотя он добавлен в исключения.

**Comment by sfionov** [comment]
Fixed in core/pull-requests/1347

**Comment by zubrRB** [comment]
В v7.2.2990 Hotfix (CL 1.4.167) этот баг уже должен быть устранён? А то он у меня всё ещё есть.

**Comment by Alex-302** [comment]
Запишите на всякий случай логи
https://kb.adguard.com/ru/windows/solving-problems/adguard-logs
перед записью можно выгрузить Адгард и удалить старые. Также нужно указать временные отметки событий(открытие сайта, начало загрузки)

**Comment by zubrRB** [comment]
Отправил. Время там в пределах двух минут. 
Воспроизводится данный баг в настоящий момент и у других пользователей, в том числе на крайних найтли 7.3.  Просто прикрепление этих логов, объёмом всего в 320 КБ, к электронному письму заняло неадекватно много времени. Хотя должно было занять всего секунду. 
При этом если раньше при добавлении файла показывало изначально малое (реальное) время его загрузки на серверы Google с учётом ширины интернет-канала пользователя, а затем время постепенно увеличивалось в разы, то сейчас сразу показывает рекордно долгое время, измеряемое часами вместо минут. 

![1](https://user-images.githubusercontent.com/50718960/70386831-c5b1f700-19ae-11ea-8275-355549d3c766.png)
![2](https://user-images.githubusercontent.com/50718960/70386810-6a800480-19ae-11ea-9e84-19ae5bbb47ea.png)

**Comment by ameshkov** [comment]
А найтли версию не попробуете? А то там до релиза все равно всего ничего осталось времени

**Comment by zubrRB** [comment]
Скрины (выше и ниже) — не мои, но сделаны они именно на 7.3 nightly 14, т.е. ситуация там та же. 

![-](https://user-images.githubusercontent.com/50718960/70398374-bd4bd180-1a2b-11ea-942d-b384ab23cfd3.png)
