### ISSUE TITLE
Не обновляется системное время

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/CoreLibs#904]
При активном Adguard при попытке ручного обновления (нажать "Обновить сейчас") системного времени выдаёт ошибку синхронизации с сервером времени в Интернет. Если убить в Диспетчере задач службу AG, то время без всяких проблем синхронизируется. Этот баг повторяется у других и был замечен ещё как минимум в н. 2017 года. [Windows 7 x32 SP1] 
Логи отправил на devteam@adguard.com.
![90d6a129a4f4f80ae7629d7cffd84223](https://user-images.githubusercontent.com/50718960/57913543-7af75300-7895-11e9-96c7-95c7c620e30c.png)

**Comment by ameshkov** [comment]
Да, я его встречал, но мы так и не смогли его повторить.

Есть впечатление, что это проблема на драйверном уровне.
Можете перечислить весь сетевой софт который у вас установлен? Антивирус, фаерволл, впн?

**Comment by zubrRB** [comment]
NIS 2014 + Simple DNSCrypt (ранее - OpenDNS). Фаервол и ВПН - не используются.

**Comment by zubrRB** [comment]
Готов поклясться, что вчера системное время обновлялось, но сегодня после перезапуска снова нет.

**Comment by ameshkov** [comment]
А не может днскрипт как-то влиять?

**Comment by zubrRB** [comment]
Отключение/удаление dnscrypt-proxy не помогает. 
При попытке обновить время выдаёт ошибку, но если закрыть окно настройки и снова открыть, то выдаёт ложное сообщение, что время было успешно синхронизировано, хотя на самом деле оно не синхронизируется. А вчера все работало нормально, хотел даже сообщить о решении проблемы, но решил дождаться перезапуска ПК, и вот снова проявилось.  
![-](https://user-images.githubusercontent.com/50718960/58088100-7f7f7c80-7bb1-11e9-9ce8-88d03a39f5d5.png)

**Comment by zubrRB** [comment]
На v6.4 была проблема с соединением со службой #AdguardTeam/AdguardForWindows/issues/2512: в трее при старте системы постоянно был красный значок. @northis отписался, что проблемы, которые были у меня в логе, уже исправлены в 7.0. И действительно в бета- и найтли-версиях при старте ОС лишь изредка на несколько секунд мог покраснеть значок программы. Однако после обновления 31 мая на стабильный релиз 7.0 у меня с воскресенья по среду включительно каждый день система запускалась с красным восклицательным знаком на значке программы, длительностью в районе минуты. При этом системное время все эти дни в течение работы системы без проблем синхронизировалось. Но сегодня система запустилась без ошибки соединения со службой AdGuard и системное время опять не синхронизируется.
P.S. Фаервол (брандмауэр) у меня всё-таки имеется в Norton Security и настроен по умолчанию.

**Comment by zubrRB** [comment]
У меня до сих пор эта проблема имеет место. После остановки службы AdGuard системное время — синхронизируется.

**Comment by ameshkov** [comment]
У нас проблема повторяется но только на Win7 и похоже связана с TDI-драйвером. Win7 с поддержки сняли да и TDI я бы честно говоря не хотел лишний раз трогать, так что оставим как won't fix.

**Comment by zubrRB** [comment]
Windows 7 пока ещё получает Ежемесячный набор исправлений качества системы безопасности и др. в рамках ESU.

**Comment by zubrRB** [comment]
Заметил, что в версии 7.19 Beta / RC эта проблема с обновлением системного времени вдруг перестала воспроизводиться.
