### ISSUE TITLE
Broken video player

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/CoreLibs#905]
https://github.com/AdguardTeam/AdguardFilters/issues/33933

Video player is broken, even when I disable "Extensions" module in AdGuard for Windows.

But when adding this rule to user filter, it works:

`@@||indoxxi.cx^$extension`

To test you have to disable that rule in Base filter.

**Comment by Hafidzgtg** [comment]
How to do it?

**Comment by BlazDT** [comment]
@Hafidzgtg
This is an topic for the filter devs to fix the bug.

**Comment by Hafidzgtg** [comment]
sorry this is the first time i use adguard pc windows and android phones.
so I don't know how.
please teach me so that the film functions

**Comment by ameshkov** [comment]
@Hafidzgtg 

Settings -> Ad Blocker -> Filter Editor -> add the rule there

**Comment by Hafidzgtg** [comment]
please show the picture

Pada tanggal Sen, 20 Mei 2019 pukul 14.15 Andrey Meshkov <
notifications@github.com> menulis:

**Comment by sxgunchenko** [comment]
Cannot reproduce with the current nightly version.
Seems to be a pre-corelibs problem.

**Comment by Hafidzgtg** [comment]
So what? Have you tried your PC?

Pada tanggal Sel, 21 Mei 2019 19.41, Sergei Gunchenko <
notifications@github.com> menulis:

**Comment by BlazDT** [comment]
@sxgunchenko
When I posted I could reproduce with the nightly. Just tried with latest nightly 7.0.2626.6527 and reproducable.

**Comment by ameshkov** [comment]
@BlazDT hm I cannot reproduce it as well. Could it be that one of the filter lists somehow messes with extensions/userscripts?

**Comment by BlazDT** [comment]
I just disabled adblocker module and still reproducable.

**Comment by ameshkov** [comment]
@BlazDT so this is due to "hide referrer" stealth mode feature, we need to add a `$stealth` exclusion for the video file URL.

The question is why `$extension` rule helped. I reckon this is because any whitelist rule disables stealth mode features as well.

**Comment by Hafidzgtg** [comment]
yes ( hide your search queries and hide your referrer from third-parties )

**Comment by BlazDT** [comment]
Added to English filter (update available in about 3 hours):
`@@||akubebas.com/?token=$stealth`

@ameshkov 
Did you opened a new ticket regarding why extension exclusion disabled stealth?

**Comment by ameshkov** [comment]
> Did you open a new ticket regarding why extension exclusion disabled stealth?

Not yet, please open it.

**Comment by BlazDT** [comment]
https://github.com/AdguardTeam/CoreLibs/issues/910

**Comment by Hafidzgtg** [comment]
just forget about it

Pada tanggal Kam, 23 Mei 2019 23.42, BlazDT <notifications@github.com>
menulis:

**Comment by Hafidzgtg** [comment]
yeahhh thanks it can after updating Windows adguard.
but only movies can except TV series can't.
please fix it.
https://indoxx1.show/ sorry the site has moved
