### ISSUE TITLE
Userscript with regexp-based @include doesn't work

### ISSUE THREAD

**Issue by zubrRB** [AdguardTeam/CoreLibs#906]
После перехода на v7 BETA перестал работать простенький юзерскрипт, генерирующий магнет-ссылку на крупном торрент-трекере (для генерации требуется регистрация).

1. Зарегистрироваться на https://kinozal.tv. 
2. Установить скрипт  https://greasyfork.org/ru/scripts/14085-kinozal-tv-magnet-links.
3. Открыть страницу с раздачей http://kinozal.tv/details.php?id=1665801. (На скриншоте крестиком помечено, где должна быть сгенерирована магнет-ссылка с изображением красного значка).
![magnet](https://user-images.githubusercontent.com/50718960/57968484-c4f63c80-795a-11e9-8171-d0435b1a25db.png)

**Comment by adbuker** [comment]
resolved in `core/pull-requests/1257`
