### ISSUE TITLE
$extension disables stealth module

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/CoreLibs#910]
https://github.com/AdguardTeam/AdguardFilters/issues/33933

To reproduce enable hide referrer in stealth options, disable "@@||akubebas.com/?token=$stealth" in base filter and choose any movie, you will get an error.
Now when adding "@@||indoxxi.cx^$extension" to user filter (or current domain the site has) it works as it seems to disable stealth module then.

**Comment by sxgunchenko** [comment]
fixed along with #1106
