### ISSUE TITLE
Fatal Error in find_stream_on_goaway_func

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#920]
https://sentry.adguard.com/adg/adguard-windows/issues/23072/

crash via `abort`

**Comment by sfionov** [comment]
core/pull-requests/1294

**Comment by adbuker** [comment]
The issue has come back and it is very "popular" (e.g. events/892973)

**Comment by adbuker** [comment]
The issue is in the `1.4.13` again and happens too often - https://sentry.adguard.com/adg/adguard-windows/issues/24315

**Comment by sfionov** [comment]
One from @Alex-302
https://sentry.adguard.com/adg/adguard-windows/issues/24315/
