### ISSUE TITLE
GM_xmlhttpRequest doesn't support some parameters

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#926]
At this moment, there are stubs for the `user` and `password` fields. Moreover, the presence and non-emptiness of the `headers` field invokes the error response. 
As a first step, let's simply ignore the `headers` field instead of invoking the error response, and as a second step - we need to implement supporting of these `GM_xmlhttpRequest`'s fields

**Comment by adbuker** [comment]
The script for the test is in the NCloud

**Comment by sxgunchenko** [comment]
core/pull-requests/1342
