### ISSUE TITLE
$network rules do not work on Windows

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#927]
### Steps to reproduce:

1. Add `93.184.216.*$network` (it should block `example.org`)
2. Open `example.org`

### Expected
Connection reset

### Actual result
It's possible to open the website

**Comment by sfionov** [comment]
core/pull-requests/1291

**Comment by ameshkov** [comment]
It seems that they are now dropping packets instead of rejecting connections

**Comment by ameshkov** [comment]
Also, here's a crash related to this: https://sentry.adguard.com/adg/adguard-windows/issues/26262/?query=is:unresolved

## Steps to reproduce
1. Add `93.184.216.34$network` to the user filter
2. Restart protection ($network rules aren't applied without a restart -- another bug)
3. Try opening example.org
4. Page loading will hang (due to https://github.com/AdguardTeam/CoreLibs/issues/927#issuecomment-506804711)
5. Open user filter and edit the rule, change it to `@@93.184.216.34$network`
6. AdGuard will crash
