### ISSUE TITLE
TLS 1.3 support

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#93]
Check my comment here:
https://github.com/AdguardTeam/AdguardForWindows/issues/1737#issuecomment-302839792

* Check my patch for the TLS 1.3 support (migrating to the OpenSSL 1.1 branch) and check what should be done to CoreLibs to finish the migration.
* We should find a way to access `SSL.packet_length` as removing this check may cause issues.

**Comment by ameshkov** [comment]
UPD: It appears that the guys have already solved both issues in CoreLibs:)

The only thing left is to recompile it with OpenSSL 1.1.1 once we're ready to test TLS 1.3.

**Comment by ameshkov** [comment]
Approved:
https://www.ietf.org/mail-archive/web/ietf-announce/current/msg17592.html

**Comment by ameshkov** [comment]
Guys, we should also let users configure if TLS 1.3 is enabled or not.

**Comment by TPS** [comment]
I'm all for more `Settings > Advanced`, but why make _this_ configurable, unless part of a Min/Max TLS setting (for completeness)?

**Comment by ameshkov** [comment]
> I'm all for more Settings > Advanced, but why make this configurable, unless part of a Min/Max TLS setting (for completeness)?

We'll put it to the low-level settings, people won't really need to change it except for really rare cases.

> Min/Max TLS

That would be too much for an intermediate proxy like ours (the chance of an error if you set min version is too high). The max version is required though to avoid issues like we just encountered with the Win version: https://github.com/AdguardTeam/AdguardForWindows/issues/2241 (it seems that ISP's DPI was not ready to the type of TLS 1.3 handshake AG sends).

**Comment by TPS** [comment]
Then isn't the correct response to fix the TLS support, rather than disabling it? ___Not complaining___, but, according to that issue, it seems to be an implementation problem from AG's side, since Chrome's works, right?

**Comment by ameshkov** [comment]
We did fix it indeed. But it shows that using TLS 1.3 **might** cause issues and to mitigate the possible issues (and to check if TLS is the cause) we need a new setting.

**Comment by szolin** [comment]
core/pull-requests/367
