### ISSUE TITLE
Slow handshake with IPv6 websites when driver is in redirect mode

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#936]
Logs are uploaded to the private nextcloud

Look for `[2001:41d0:305:2100::5172]` there.

**Comment by sfionov** [comment]
IPv6 is unavailable (timing out), but we accept connection, so browser doesn't try IPv4.

**Comment by ameshkov** [comment]
Ah, so we really need "reachability tester" migrated to Win.

**Comment by sxgunchenko** [comment]
core/pull-requests/1326
