### ISSUE TITLE
Adguard blocks VPN connection via UDP on port 443

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#937]
@andronov-alexey commented on [Mon Jun 03 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2707)

I have a private VPN server which configured to using UDP protocol on port 443
After I updated Adguard to the latest release VPN stopped working.
After disabling protection in AdGuard all works just fine. Also everything works when I switch to TCP.
Looking through AdGuard logs I found an interesting entry which seems related to the problem:
> INFO, AdguardSvc, 28, 02.06.2019 17:51:53.421, Adguard.Core.Driver.DriverApi |
> Blocking UDP port 443 rule status: NF_STATUS_SUCCESS.

Seems like an explicit prohibition rule
If so, how can I overcome the issue?
I'd very much prefer to continue using UDP on 443 port for my VPN

AdGuard 7.0.2693.6661 RELEASE
Windows 10, v.1803

---

@ameshkov commented on [Mon Jun 03 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2707#issuecomment-498199165)

Yeah, this is a bug. This must have been done for browsers processes only to suppress QUIC, and not for every process as it is now.

**Comment by adbuker** [comment]
resolved in `core/pull-requests/1298`
