### ISSUE TITLE
Abort in request_finished()

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#940]
https://sentry.adguard.com/adg/adguard-windows/issues/21592

All crashes are on Win7, TDI Driver

**Comment by adbuker** [comment]
A new bunch of crashes - https://sentry.adguard.com/adg/adguard-windows/issues/25791 - cl1.4.32

**Comment by sfionov** [comment]
1) run stress-test with ag_set_dns_servers and try to debug find the race
2) if not solved, drop DNS request on which assertion is failing with warning

**Comment by vshlobinag** [comment]
core/pull-requests/1477

**Comment by ameshkov** [comment]
Move back to Current Sprint when new crash reports with extended logging are available.

**Comment by vshlobinag** [comment]
There is no new crashes
