### ISSUE TITLE
Upload to `rapid.ufanet.ru` fails and causes high CPU

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#956]
Happens in FF on http://rapid.ufanet.ru/

Screenshot:
<details>

![00001](https://user-images.githubusercontent.com/5947035/58947142-fe6adc80-878f-11e9-832e-83263f4bc87c.png)
</details>

**Comment by sxgunchenko** [comment]
needs to be checked if it was fixed along with #790

**Comment by TheHasagi** [comment]
Unable to reproduce.
