### ISSUE TITLE
Implement filter rules for removing tracking parameters

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#958]
Syntax that is currently being implemented differs from original feature request.

Original feature request is:
@arturbikbaev commented on [Thu Jun 06 2019](https://github.com/AdguardTeam/AdguardForMac/issues/525)

**Feature request for the AdGuard desktop app (macOS and Windows)**

Please consider adding the following features to the **Strip tracking parameters** section under the **Stealth Mode** partition in the AdGuard desktop app (macOS and Windows):

1. Ability to use wildcards in rules, i.e. `pd_rd_*`
2. Ability to set rules for specific domains, i.e. `*@amazon.com`

**As a result** we will be able to use complex rules like `pd_rd_*@amazon.*` in the **Strip tracking parameters** section under the **Stealth Mode** partition in the AdGuard desktop app

**My environment**

- macOS Mojave 10.14.5
- Safari 12.1.1 (14607.2.6.1.1)
- AdGuard 2.0.4.552
- macOS Mojave's built-in Firewall
- No antivirus

**Comment by sxgunchenko** [comment]
core/pull-requests/1933

related issues: 
https://github.com/AdguardTeam/AdguardKnowledgeBase/issues/509
https://github.com/AdguardTeam/AdguardFilters/issues/57197
