### ISSUE TITLE
[Firefox compat] Pages cannot be loaded with enabled Windscribe extension

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/CoreLibs#960]
@TheHasagi commented on [Sat Jun 01 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2703)

Pages won't load with enabled Windscribe extension.

### Steps to reproduce

1. Enable AdGuard
2. Open Firefox and enable Windscribe extension

### Expected behaviour

Everything should be in order

### Actual behaviour

Pages can't be loaded

### Your environment

* Environment name and version: (e.g. Firefox 67.0)
* Operating system and version: (e.g. Windows 10, v.1703, build 15063.413)

---

@adbuker commented on [Wed Jun 05 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2703#issuecomment-499019902)

@TheHasagi , please try it with the latest nightly build

**Comment by TheHasagi** [comment]
It's working. To block IPv6 you need to use [...]$network.
