### ISSUE TITLE
Add DuckDuckGo support to Safe Search

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#962]
@terlan2 commented on [Mon Jun 10 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2752)

Parental contro (Safe search) doesnt work on duckduckgo.com search engine. Please take a look at this.

**Comment by vshlobinag** [comment]
core/pull-requests/1460

Note: duckduckgo interface may show safe search status "off" but search results remain filtered.
