### ISSUE TITLE
Modifiers are ignored in apps

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#964]
It seems that modifiers are ignored in apps where HTTPS filtering is disabled.

### Steps to reproduce

1. Add this rule:
`*.*$media`
2. Open any app where HTTPS filtering is disabled.

### Expected behavior

Only `$media` requests should be blocked.

### Actual behavior

In apps where HTTPS filtering is disabled all requests are blocked.

<details><summary>Screenshot:</summary>

![Screenshot_20190610-111037_AdGuard](https://user-images.githubusercontent.com/29142494/59185499-ea005880-8b70-11e9-9512-283729664f2c.jpg)

</details>

### Your environment

* Adguard version: 3.1.9n (1.4.13cl)
* Adguard filtering mode: Local VPN
* Operating system and version: Android 9

**Comment by sxgunchenko** [comment]
core/pull-requests/1313
