### ISSUE TITLE
phimmedia.tv

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#965]
@adguard-bot commented on [Sat Jun 08 2019](https://github.com/AdguardTeam/AdguardFilters/issues/34947)

### Issue URL (Ads)
[http://phimmedia.tv](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fphimmedia.tv)
### Comment
> Dear Developers,
> 
> Adguard for Windows failed to block any ads on phimmedia.tv site. I enabled the ABPVN filter and it still doesn't work either. However, the Adguard adblocker extension for Edge browser does work. I used the same exact settings and filters for both. What is wrong with the new version 7.0 of Adguard PC? My computer is using the latest Windows 10 version May 2019 Update. Please look into this issue and find a fix soon for Adguard PC.
> 
> I had sent an email but told I have to report it here. So I have to do it again. The picture I uploaded was after I uninstalled Adguard PC and use the Adguard Adblocker extension for Edge. The Edge extension works perfectly at removing all ads on this website as you can see there are no ads. 
> 
> Thanks 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/0XvIFwc.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 7.0
Browser: | Edge
AdGuard driver: | WFP
Filters: | AdGuard Base,<br>AdGuard Tracking Protection,<br>AdGuard Social Media,<br>AdGuard Annoyances,<br>Malware Domains,<br>Spam404,<br>ABPVN List,<br>NoCoin Filter List

**Comment by AdamWr** [comment]
It seems that AdGuard's JS is not injected (there is no local.adguard.org in source code).

**Comment by sfionov** [comment]
Works for me:
![image](https://user-images.githubusercontent.com/47204/59201278-c0602500-8ba2-11e9-9832-f235d73621e3.png)

Does site have AG certificate?
Can you please send debug log?

**Comment by sfionov** [comment]
Ah ok, local.adguard.org is really missing. I'll check this

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/CoreLibs/issues/965
