### ISSUE TITLE
drive.google.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#969]
@adguard-bot commented on [Wed Jun 12 2019](https://github.com/AdguardTeam/AdguardFilters/issues/35120)

### Issue URL (Incorrect Blocking)
[https://drive.google.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fdrive.google.com%2F)
### Comment
> He intentado subir los archivos (varios) al google drive a una cuenta que poseo, pero con el adguard activado me da error, muchas veces el error persiste aun desactivando el adguard, no se si sea porque no le hice refresh a la pagina, aun en modo incognito da error al subir archivos (una vez que finaliza la subida comienza de cero y continua asi, como un loop) pero al subir  desde una maquina virtual (virtual box) sube sin problemas. he contactado a google y al servicio de cable y manifiestan estar todo bien, pero sigo con esos errores, de hecho probando el Epic Privacy browser (con vpn incorporado) sube los archivos sin problemas, muy lento pero los sube, probe instalar el firefox desde cero pero no funciona tampoco, asi que me queda descartar que sea el Adguard, ya que al desactivarlo y hacer refresh a la pagina de google drive (y desaparece el logo verde en la pagina) alli si sube los archivos sin problemas.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/4X0Gczc.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/K7IbStt.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 7.0.2693.6661
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Block third-party Authorization header, Block Location API, Hide your IP address (209.141.53.254)
Filters: | Filter unblocking search ads and self-promotion,<br>EasyList Italy,<br>AdGuard Base,<br>AdGuard Tracking Protection,<br>AdGuard Social Media,<br>AdGuard Spanish/Portuguese
Other extensions used: | malwarebytes

---

@BlazDT commented on [Mon Jun 17 2019](https://github.com/AdguardTeam/AdguardFilters/issues/35120#issuecomment-502500373)

Uploaded a file just fine, please check @AdamWr 

---

@AdamWr commented on [Mon Jun 17 2019](https://github.com/AdguardTeam/AdguardFilters/issues/35120#issuecomment-502658452)

I can reproduce this issue if I try to upload file (probably) larger than 60MB.
When it finish uploading file I see errors like this `net::ERR_SPDY_PROTOCOL_ERROR 400` and something about `CORS policy` and then it starts uploading file from the beginning.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/59603184-0704d080-9109-11e9-8fc0-7a548dc4389d.png)

</details>

It happens even if I disable Ad Blocker, Stealth Mode, Browsing Security and Extensions module.

**Comment by zubrRB** [comment]
Slow upload speed to YouTube #903

**Comment by zubrRB** [comment]
#903

**Comment by zubrRB** [comment]
Slow upload speed to YouTube #903

**Comment by sfionov** [comment]
Fixed with #903
