### ISSUE TITLE
Rules from referrer site are active

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/CoreLibs#972]
1. Add this rule to user filter: `@@||forum.adguard.com^$elemhide,jsinject,genericblock,important`
2. Open https://forum.adguard.com/index.php?threads/missed-ad-sacbee-com.33094/ and visit the site there
3. Added rule (`@@||forum.adguard.com^$elemhide,jsinject,genericblock,important`) is applied to target url.
<img width="334" alt="rule-applied" src="https://user-images.githubusercontent.com/34266271/59650271-b97a7900-9185-11e9-8e9c-7723fd7d49f3.png">

Tested on latest Windows nightly.

**Comment by ameshkov** [comment]
It is reported as applied, but as I recall, it won't actually disable js/elemhide, right?

**Comment by BlazDT** [comment]
Elemhide is disabled on target site at least.

**Comment by sxgunchenko** [comment]
resolved along with #1106
