### ISSUE TITLE
Incompatibility with Sophos antivirus and Firefox

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/CoreLibs#976]
When Sophos antivirus installed alongside with AdGuard Firefox can't be filtered. (Certificate can't be installed)

Windows 10
AdGuard 7.1.2814 NIGHTLY (CL 1.4.31)

**Comment by ameshkov** [comment]
In the next version, it will be filtered, but there could be issues with corrupting FF internal connections in this configuration.

**Comment by adbuker** [comment]
related to https://github.com/AdguardTeam/AdguardForWindows/issues/2710
