### ISSUE TITLE
Amediateka app — video loading is broken until DNS Filtering is enabled

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/CoreLibs#977]
### [Issue URL](https://github.com/AdguardTeam/AdguardFilters/issues/33130)

[Amediateka — old app (!!)](https://play.google.com/store/apps/details?id=com.spbtv.tv4.amedia)

### Steps to reproduce

1. Disable all filters, turn off Stealth Mode and DNS Filtering.
2. Video doesn't load. For example, Spoiler Room is free to try.

#### Actual behavior

> При попытке просмотра любой серии, например игра престолов при включенном адгвард постоянно крутится кружок загрузки и видео не проигрывается. После отключения защиты все работает нормально.

### Your environment

* Adguard: 3.1.37n
* Android: 9

**Comment by TheHasagi** [comment]
Successfully reproduced.

**Comment by slavaleleka** [comment]
There are no free episodes in [new Amediateka app](https://play.google.com/store/apps/details?id=com.amdteka) anymore and free videos (e.g. series trailers) loads fine now
