### ISSUE TITLE
Useragent rotate.

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#978]
@optomux commented on [Sat Jun 22 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2780)

Hi! Please add a feature to rotate useragents.

Thanks.

**Comment by optomux** [comment]
Is this going anywhere?

**Comment by ameshkov** [comment]
Eventually, yes. But we should first do what's planned: https://github.com/AdguardTeam/CoreLibs/milestone/13https://github.com/AdguardTeam/CoreLibs/milestone/13

**Comment by optomux** [comment]
There also needs to be a setting to change it per process otherwise some websites will not work.
Youtube is just one example.
