### ISSUE TITLE
studopedia.su

### ISSUE THREAD

**Issue by Lacki23** [AdguardTeam/CoreLibs#979]
new filter:
<div id="opaco" style="display: block; height: 9532px;"></div>
<div id="popup" style="display: block;"><span class="arrow"></span>
	<p align="center"><b>Отключите adBlock!</b><br><small>очень нужно</small></p>
	<p><img style="max-width: inherit;" ;="" src="/css/img/aaa.png"></p>
</div>

**Comment by ameshkov** [comment]
https://agrd.io/report
