### ISSUE TITLE
Do not print proxy name/address in the log

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#982]
@ameshkov commented on [Wed Jun 26 2019](https://github.com/AdguardTeam/AdguardForAndroid/issues/2841)

When a user sends AdGuard logs to the support service, they can see the socks proxy address in the users' logs:
`Using outbound proxy SOCKS5 username@proxy_address` 

I think it makes sense to hide the real proxy address and the username.

---

@sfionov commented on [Wed Jun 26 2019](https://github.com/AdguardTeam/AdguardForAndroid/issues/2841#issuecomment-505851406)

This is CoreLibs' message

**Comment by sfionov** [comment]
core/pull-requests/1346
