### ISSUE TITLE
Any changes in the certificates must lead to the SSL entities reload

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#984]
At this moment cert-related properties are in the `filteringConfinguration` structure, so any changes in certs (e.g. cert reinstalling) lead neither to "SSL context" reloading, but must.
As a temporary workaround, if we detect cert-related properties changing, we will invoke the whole server restarting instead of just filtering reconfiguring.
The workaround will be implemented within the https://github.com/AdguardTeam/AdguardForWindows/issues/2782

**Comment by sxgunchenko** [comment]
core/pull-requests/1343
