### ISSUE TITLE
Kee delay (Firefox Addon)

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#985]
@Chinaski1 commented on [Wed Jun 26 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2785)

When protection is enabled, the extension (Key Manager) works with a delay. Reproduced on video.

[AdGuard ON](https://www.dropbox.com/s/r5ssuvus9ok6t61/withadguard.mp4?dl=0)

[AdGuard OFF](https://www.dropbox.com/s/0z5u6a3yqmnvu19/withoutadguard.mp4?dl=0)
### Customer ID 
[Forum](https://forum.adguard.com/index.php?threads/adguard-7-delays-start-of-kee-firefox-addon.32788/#post-184314)
### Your environment

* Environment name and version: AdGuard 7.1.2817 / Firefox 67.0.4 / KeePass is 2.42.1 with german language Plugin | KeePassRPC 1.9.0.0 Kee AddOn is 3.2.7
* Operating system and version: Windows is 1903 Build 18362.175 x64

**Comment by ameshkov** [comment]
@Chinaski1 once $network rules start working again, the temporary solution would be to disable localhost filtering: `@@127.0.0.1$network`.

**Comment by Chinaski1** [comment]
<details><summary>Screenshot:</summary>


![image](https://user-images.githubusercontent.com/49645813/60278060-69c74a80-9907-11e9-9553-ffc45304af08.png)


</details>

**Comment by ameshkov** [comment]
No issue with 7.3
