### ISSUE TITLE
Chrome on Android works slowly when IPv6 is not available

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/CoreLibs#993]
The user has problems with connection speed when protection is ON

**The first part of Logs(DNS filtering is ON):**
1)12:47 Argos.co.uk
2)12:47 N4G.com
3)12:48 Steam website.

**The second part of Logs (Without DNS filtering):**
1)13:53 bitchute.com
2)13:54 Argos.co.uk
3)13:55 dunelm.com

*Logs in Ncloud*

**Comment by Chinaski1** [comment]
**2242629**

www.linkedin.com
www.tweakers.net

*Logs in Ncloud*

**Comment by ameshkov** [comment]
The issue is caused by the pause Chrome makes after an attempt to connect to an IPv6 address (which is unreachable):
https://uploads.adguard.com/up04_qq3rm_httpsnetlog-viewer.appspot.comeventss68062.png

At the same time, here's what we have in AG logs:
```
08:08:15.024 [VpnService-main] DEBUG Native.TCPIP.TCPMNGR - [LWIP id=445] new TCP connection 2001:db8:ad:0:ff:::48962 -> 2a05:f500:10:101::b93f:9101:443
08:08:15.026 [Thread-794] DEBUG Native.AGIpReachabilityTester - [id=445] operator() Connection to [2a05:f500:10:101::b93f:9101]:443 failed: Error connecting to [2a05:f500:10:101::b93f:9101]:443. Error: 101(Network is unreachable)
08:08:15.027 [Thread-794] DEBUG Native.AGIpReachabilityTester - Destination [2a05:f500:10:101::b93f:9101]:443 is unreachable
```

**Comment by Chinaski1** [comment]
**Logs In Ncloud**

*15.20 - ibik.ru 
 15.21 -  help.kustom.rocks
 15.22 - ibik.ru
***15.23 - DNS on  in adguard settings***
15.24 - help.kustom.rocks*

[Forum](https://forum.adguard.com/index.php?threads/adguard-choking-internet-on-pixel-3-xl.32428/#post-185139)

**Comment by sfionov** [comment]
core/pull-requests/1400
