### ISSUE TITLE
Network rules do not block sometimes on Android nightly 3.1.53

### ISSUE THREAD

**Issue by artemiv4nov** [AdguardTeam/CoreLibs#994]
#### Steps to reproduce on Android

* Add ||graph.facebook.com to the content blocking user filter
* Install any app that uses Facebook SDK (for instance, Yandex Maps)
* Run it
* Check the filtering log

#### Expected behavior on Android
* Connections to graph.facebook.com must be blocked. 

#### Actual behavior
* Connections aren't blocked

[https://app.zenhub.com/files/74596049/f767be37-7035-4328-a513-b21c4ea17e8c/download](https://app.zenhub.com/files/74596049/f767be37-7035-4328-a513-b21c4ea17e8c/download)

**Comment by sxgunchenko** [comment]
core/pull-requests/1366

**Comment by ameshkov** [comment]
The issue is still present.

### Steps to reproduce

1. Go to `cnn.com`
2. Open menu, open `US politics`
3. Inspect the filtering log

### Expected result

No `tcp://` requests from Chrome

### Actual result

* `tcp://code.jquery.com/`
